import type { Language } from '../phrases.ts';

/**
 * Arabic: Modern Standard Arabic with a light, pan-regional warmth, the way a
 * friendly stranger would talk from Rabat to Muscat. The listener is addressed
 * in the polite plural (أهلًا بكم, تفضلوا), which Arabic uses to a single
 * guest and which never has to choose a gender; the speaker only ever uses
 * first-person verbs, which do not mark one either.
 */
const AR: Language = {
  locale: 'ar',
  name: 'Arabic',
  rtl: true,
  join: ' ',
  compass: ['شمالًا', 'إلى الشمال الشرقي', 'شرقًا', 'إلى الجنوب الشرقي', 'جنوبًا', 'إلى الجنوب الغربي', 'غربًا', 'إلى الشمال الغربي'],
  lines: {
    morning: [
      ['صباح الخير!', 'Good morning!'],
      ['صباح الورد!', 'A morning of roses to you!'],
      ['صباح الخير! يوم جميل، أليس كذلك؟', "Good morning! A lovely day, isn't it?"],
      ['أهلًا! صباح الخير عليكم.', 'Oh, hello! Good morning to you.'],
    ],
    afternoon: [
      ['مساء الخير!', 'Good afternoon!'],
      ['السلام عليكم!', 'Peace be upon you!'],
      ['أهلًا وسهلًا!', 'Hello and welcome!'],
      ['مرحبًا! نهار لطيف، أليس كذلك؟', 'Hi! Nice afternoon, this.'],
    ],
    evening: [
      ['مساء الخير!', 'Good evening!'],
      ['مساء الورد!', 'An evening of roses to you!'],
      ['أهلًا! أمسية جميلة للمشي.', 'Hello! Nice evening for a walk.'],
      ['السلام عليكم، مساء الخير.', 'Peace be upon you, good evening.'],
    ],
    night: [
      ['مساء الخير! الوقت متأخر، أليس كذلك؟', "Good evening! It's late, isn't it?"],
      ['يا إلهي! أفزعتموني. أهلًا!', 'Goodness! You gave me a fright. Hello!'],
      ['أهلًا! نزهة في الليل؟', 'Hello! Out for a night walk?'],
      ['مساء الخير! أم أنه صار صباحًا؟', 'Good evening! Or is it morning already?'],
    ],
    again: [
      ['أنتم مرة أخرى! أهلًا!', 'Oh, you again! Hello!'],
      ['رجعتم؟ يسعدني أن أراكم.', 'Back again? Nice to see you.'],
      ['أهلًا من جديد!', 'Hello again!'],
      ['التقينا من قبل! ما زلتم تستكشفون؟', "We've met! Still exploring?"],
      ['آه، أنتم! هل وجدتم طريقكم؟', "Ah, it's you! Did you find your way?"],
    ],
    welcome: [
      ['أهلًا بكم في {town}!', 'Welcome to {town}!'],
      ['هذه مدينة {town}. هل جئتم للزيارة؟', 'This is {town}. Are you visiting?'],
      ['أول مرة في {town}؟', 'First time in {town}?'],
      ['اخترتم يومًا جميلًا لزيارة {town}.', "You've picked a good day to see {town}."],
      ['حياكم الله! مدينة {town} ترحب بكم.', 'God give you life! {town} bids you welcome.'],
      ['ما الذي جاء بكم إلى {town}؟', 'So, what brings you to {town}?'],
    ],
    capitalHere: [
      ['مدينة {town} عاصمة بلدنا.', '{town} is the capital of our country.'],
      ['هذه العاصمة، كما تعلمون. كل شيء يحدث في {town}.', 'This is the capital, you know. Everything happens in {town}.'],
      ['هنا في {town} مقر الحكومة. ناس مهمون كثيرون ببدلات رسمية.', 'The government sits here in {town}. Lots of important people in suits.'],
      ['العاصمة لا تنام أبدًا، والناس هنا لا يهدؤون.', 'The capital never sleeps, and nobody here ever slows down.'],
    ],
    capitalThere: [
      ['عاصمتنا {capital}، وهي تستحق الزيارة.', "Our capital is {capital}, and it's worth a visit."],
      ['هل زرتم {capital} بعد؟ هي عاصمتنا.', 'Have you been to {capital} yet? That is our capital.'],
      ['أهل {capital} يظنون أنهم يديرون البلد. وهم كذلك فعلًا.', 'People in {capital} think they run the country. Well, they do.'],
      ['{capital} أكبر، لكنني أفضّل العيش هنا.', "{capital} is bigger, but I'd rather live here."],
    ],
    big: [
      ['هذه مدينة كبيرة. من السهل أن تضيعوا هنا!', "This is a big city. It's easy to get lost here!"],
      ['ما أكثر الناس! يعيش المرء هنا عمره كله ولا يعرف كل الشوارع.', 'So many people! You could live here all your life and not know every street.'],
      ['الزحمة هنا، بصراحة! لكن هناك دائمًا ما يحدث.', 'The traffic here, honestly! But there is always something going on.'],
      ['مدينة كبيرة مثل هذه لا تتوقف أبدًا. وأنا أحبها، في الغالب.', 'A big city like this never stops. I love it, mostly.'],
    ],
    middling: [
      ['ليست كبيرة ولا صغيرة. على المقاس تمامًا.', 'Not big, not small. Just the right size.'],
      ['كبيرة بما يكفي لتجدوا كل شيء، وصغيرة بما يكفي لتمشوها.', 'Big enough to have everything, small enough to walk it.'],
      ['مدينة {town} بحجم لطيف. يوم أو يومان وترون كل شيء.', "{town} is a nice size. You'll see it all in a day or two."],
      ['الكل يشتكي من الهدوء، ولا أحد يرحل أبدًا.', 'Everybody complains it is too quiet, and nobody ever leaves.'],
    ],
    small: [
      ['إنه مكان صغير. الجميع هنا يعرفون بعضهم.', "It's a small place. Everybody knows everybody here."],
      ['بلدة صغيرة: إن عطس أحد، قال له الشارع كله يرحمك الله!', 'A small town: if somebody sneezes, the whole street says bless you!'],
      ['لا يحدث الكثير في {town}، ونحن نحب الأمر هكذا.', 'Not much happens in {town}, and we like it that way.'],
      ['أنتم أكثر شيء مثير حدث هنا هذا الأسبوع!', "You're the most exciting thing to happen here all week!"],
    ],
    coast: [
      ['نعيش هنا بجانب الماء. السمك لذيذ جدًا.', 'We live by the water here. The fish is very good.'],
      ['اذهبوا وانظروا إلى البحر. كل يوم له لون مختلف.', 'Go and look at the sea. It has a different colour every day.'],
      ['تشمّون هذه الرائحة؟ إنه البحر. لا يُملّ منه أبدًا.', "Smell that? That's the sea. You never get tired of it."],
      ['تخرج القوارب مع الفجر وتعود بأطيب سمك في الدنيا.', 'The boats go out at dawn and come back with the best fish in the world.'],
    ],
    inland: [
      ['نحن بعيدون عن البحر، لكن الأرض هنا جميلة.', 'We are far from the sea, but the land here is beautiful.'],
      ['لا شاطئ هنا للأسف. لكن انظروا إلى هذه الحقول.', "No beach here, I'm afraid. But look at those fields."],
      ['البحر؟ بصراحة لم أره قط. إنه بعيد جدًا.', "The sea? Never seen it, to be honest. It's a long way."],
      ['هنا الأرض هي كل شيء. تربة طيبة وناس طيبون.', 'Out here the land is everything. Good soil, good people.'],
    ],
    high: [
      ['نحن في مكان مرتفع. على مهلكم، الهواء خفيف.', "We're high up here. Take it slowly, the air is thin."],
      ['هنا في الجبال، المنظر أغلى ما نملك.', 'Up in the mountains like this, the view is the best thing we have.'],
      ['من يعيش هنا تقوى ساقاه. لا شيء مستوٍ!', 'Whoever lives up here gets strong legs. Nothing is flat!'],
      ['انتبهوا لأنفاسكم! الجبال تحتاج وقتًا للتعوّد.', 'Mind your breath! The mountains take some getting used to.'],
    ],
    snowy: [
      ['الثلج هنا تسعة أشهر في السنة، وفي الثلاثة الباقية نشتكي من الوحل.', 'Snow nine months a year. The other three, we complain about the mud.'],
      ['كل شيء أبيض هنا. ستحتاجون أحذية أفضل من هذه.', "Everything is white out here. You'll want better boots than those."],
      ['البرد لا يزعجنا، فهو يُبعد السياح. إلا أنتم طبعًا!', "We don't mind the cold. It keeps the tourists away. Present company excepted!"],
      ['حين يكون الثلج جديدًا، يصير الهدوء عجيبًا.', 'When the snow is fresh, the quiet is a wonder.'],
    ],
    forest: [
      ['الغابة هنا تمتد أيامًا. لا تتركوا الطريق!', 'The woods go on for days round here. Stay on the path!'],
      ['تمشّوا في الغابة، فهي تريح البال.', 'Go for a walk in the forest. It eases the mind.'],
      ['كل خريف نجمع الفطر والتوت من هناك.', 'We pick mushrooms and berries out there every autumn.'],
      ['أشجار وأشجار وأشجار. لا أريد العيش في مكان آخر.', "Trees, trees and more trees. I wouldn't live anywhere else."],
    ],
    desert: [
      ['رمال على مدّ البصر.', 'Sand as far as the eye can see.'],
      ['اشربوا ماءً كثيرًا. الصحراء لا ترحم.', 'Drink plenty of water. The desert shows no mercy.'],
      ['ليالي الصحراء باردة، هل تصدقون؟ لا أحد يصدق.', 'Desert nights are cold, would you believe it? Nobody does.'],
      ['انتظروا النجوم الليلة. هنا تُرى بالملايين.', 'Wait for the stars tonight. Out here you see millions of them.'],
    ],
    plains: [
      ['أرض مستوية على مدى كيلومترات. ترون المطر قادمًا قبل يوم.', 'Flat land for miles. You can see the rain coming a day away.'],
      ['سماء واسعة هنا، ولا شيء يوقف الريح.', 'Big sky out here, and nothing to stop the wind.'],
      ['كلها مراعٍ طيبة. انتبهوا للقطعان.', 'Good grazing land, all of it. Watch out for the herds.'],
      ['العشب يمتد بلا نهاية، كأنه بحر أخضر.', 'The grass goes on forever, like a green sea.'],
    ],
    tropical: [
      ['كل شيء ينمو هنا. اغرسوا عودًا فيصير شجرة.', 'Everything grows here. Plant a stick and it becomes a tree.'],
      ['حين ينزل المطر هنا ينزل بقوة، ثم يتوقف فجأة.', 'When the rain comes here, it really comes. Then it stops, just like that.'],
      ['جرّبوا فواكه السوق. لم تذوقوا مثلها في حياتكم.', "Try the fruit from the market. You've never tasted anything like it."],
      ['الخضرة هنا طوال السنة. الشتاء؟ ما هو الشتاء؟', "It's green all year round. Winter? What's winter?"],
    ],
    landmark: [
      ['لا تفوّتوا {landmark}! على بعد نحو {km} كم {dir}.', "Don't miss {landmark}! It's about {km} km {dir}."],
      ['هل رأيتم {landmark}؟ على بعد {km} كم {dir}، ويستحق كل خطوة.', "Have you seen {landmark}? It's {km} km {dir}, worth every step."],
      ['الجميع يذهب إلى {landmark}، على بعد نحو {km} كم {dir}.', "Everyone goes to {landmark}. It's about {km} km {dir}."],
      ['لمحبي الأماكن العريقة: {landmark}، على بعد {km} كم {dir}. يأتيه الناس من كل مكان.', 'For lovers of old places: {landmark}, {km} km {dir}. People come from all over.'],
    ],
    landmarkNear: [
      ['{landmark} على بعد خطوات من هنا!', '{landmark} is just a few steps from here!'],
      ['هل زرتم {landmark}؟ المكان قريب جدًا.', "Have you been to {landmark} yet? It's very close."],
      ['كل يوم نمرّ بجانب {landmark}، والدهشة لا تزول.', 'Every day we walk past {landmark}, and the wonder never fades.'],
      ['اذهبوا لرؤية {landmark} باكرًا، قبل الزحام. المكان قريب.', "Go and see {landmark} early, before the crowds. It's close."],
    ],
    plane: [
      ['هناك طائرة صغيرة في حقل {dir}، إن كنتم تعرفون الطيران!', "There's a little plane in a field {dir}, if you can fly!"],
      ['أحدهم ترك طائرة في حقل {dir}. ما رأيكم في جولة في السماء؟', 'Somebody left a plane in a field {dir}. Fancy a flight?'],
      ['هل تجيدون الطيران؟ هناك طائرة تنتظر {dir}.', "Can you fly? There's a plane waiting {dir}."],
      ['إن أردتم رؤية كل شيء من فوق، فهناك طائرة {dir}.', "If you want to see it all from above, there's a plane {dir}."],
    ],
    balloon: [
      ['هناك منطاد هواء ساخن في حقل {dir}! تخيلوا المنظر.', "There's a hot-air balloon in a field {dir}! Imagine the view."],
      ['هل ركبتم منطادًا من قبل؟ هناك واحد {dir}.', 'Have you ever flown in a balloon? There is one {dir}.'],
      ['يرتفع منطاد من الحقل {dir}. شيء ساحر.', 'A balloon goes up from the field {dir}. It is magical.'],
      ['لطالما أردت ركوب المنطاد {dir}، لكنني أخاف!', "I've always wanted to ride the balloon {dir}. But I'm scared!"],
    ],
    boat: [
      ['هناك قارب عند الماء {dir}، إن أردتم الخروج إلى البحر.', "There's a boat by the water {dir}, if you want to go out."],
      ['إن كنتم تحبون البحر فهناك قارب {dir}. فقط أعيدوه!', "If you like the sea, there's a boat {dir}. Just bring it back!"],
      ['هناك قارب مربوط {dir}. من هنا يمكن الإبحار إلى أي مكان.', 'A boat is tied up {dir}. From here you could sail anywhere.'],
      ['خذوا القارب {dir} وشاهدوا الساحل من الماء.', 'Take the boat {dir} and see the coast from the water.'],
    ],
    hot: [
      ['الجو حار اليوم! ابحثوا عن ظل.', "It's hot today! Find some shade."],
      ['يا له من حر! اشربوا ماءً، يبدو أنكم تحتاجونه.', 'What heat! Drink some water, you look like you need it.'],
      ['حرّ لا يُطاق. لا شيء يُفعل إلا الجلوس في الظل.', 'Unbearable heat. Nothing to do but sit in the shade.'],
      ['في هذا الحر حتى القطط لا تخرج.', 'In this heat, even the cats stay indoors.'],
      ['حار، أليس كذلك؟ وهذا عندنا يوم لطيف!', "Hot, isn't it? And this is a mild day for us!"],
    ],
    cold: [
      ['برر، الجو بارد اليوم! تدفّأوا جيدًا.', "Brr, it's cold today! Keep warm."],
      ['برد قارس! أين قفازاتكم؟', 'Bitter cold! Where are your gloves?'],
      ['من شدة البرد لم أعد أشعر بأنفي.', "It's so cold I can't feel my nose any more."],
      ['بارد بما يكفي؟ انتظروا حتى تهبّ الريح.', 'Cold enough for you? Wait till the wind picks up.'],
      ['اشربوا شيئًا ساخنًا، فهو يساعد كثيرًا.', 'Have something hot to drink. It helps a lot.'],
    ],
    mild: [
      ['ما أجمل الطقس اليوم!', 'What lovely weather today!'],
      ['لا حر ولا برد. يوم مثالي، أليس كذلك؟', "Not hot, not cold. Perfect day, isn't it?"],
      ['في يوم كهذا يحب المرء أن يبقى في الهواء الطلق.', 'A day like this, you want to be outside.'],
      ['طقس رائع! نرجو أن يدوم.', "Beautiful weather! Let's hope it lasts."],
      ['من أجل أيام كهذه نعيش هنا.', 'Days like this are why we live here.'],
    ],
    late: [
      ['لقد تأخر الوقت. الشوارع هادئة في الليل.', "It's late. The streets are quiet at night."],
      ['في هذه الساعة لا يسهر إلا القطط. ونحن!', 'At this hour only the cats are up. And us!'],
      ['كان يجب أن أكون في فراشي. وأنتم، لماذا لم تناموا بعد؟', "I should be in bed. And you, why aren't you asleep yet?"],
      ['انظروا إلى النجوم! من هنا تبدو أجمل.', 'Look at the stars! They look their best from here.'],
    ],
    early: [
      ['استيقظتم باكرًا! هذا أجمل وقت في اليوم.', "You're up early! The best part of the day."],
      ['الفرن فتح للتو. اتبعوا رائحة الخبز!', 'The bakery has just opened. Follow the smell of bread!'],
      ['المدينة ما زالت نائمة. أنتم من أهل الصباح إذن!', 'The town is still asleep. Early birds, then!'],
      ['أحب الصباح هنا، قبل أن تبدأ الضوضاء.', 'I love the morning here, before the noise starts.'],
    ],
    country: [
      ['{country} بلد جميل. استمتعوا بكل لحظة!', '{country} is a beautiful country. Enjoy every moment!'],
      ['ما رأيكم في {country} حتى الآن؟', 'How do you like {country} so far?'],
      ['تجوّلوا في كل أنحاء {country} إن استطعتم. كل زاوية مختلفة.', 'Travel all over {country}, if you can. Every corner is different.'],
      ['أهلًا بكم في {country}! البيت بيتكم.', 'Welcome to {country}! Make yourself at home.'],
    ],
    dish: [
      ['لا بد أن تذوقوا {dish} ما دمتم هنا.', "You have to try {dish} while you're here."],
      ['هل جربتم {dish}؟ لا؟ يجب أن تجربوا!', 'Have you had {dish} yet? No? Oh, you must!'],
      ['لا أحد يطبخ {dish} مثل أمي.', 'Nobody makes {dish} like my mother.'],
      ['إذا جعتم فاطلبوا {dish}. لن تندموا.', "If you get hungry, order {dish}. You won't regret it."],
    ],
    drink: [
      ['اشربوا شيئًا من {drink} قبل أن ترحلوا. هذا ما نشربه هنا.', 'Have some {drink} before you go. It is what we drink here.'],
      ['لا شيء يضاهي {drink} في آخر النهار.', 'Nothing beats {drink} at the end of the day.'],
      ['لم تعرفوا طعم الحياة حتى تذوقوا {drink}.', "You haven't tasted life until you've tried {drink}."],
      ['اطلبوا {drink} مثل أهل البلد، وسيحبونكم.', "Order {drink} like a local and they'll love you for it."],
    ],
    festival: [
      ['ارجعوا إلينا في {festival}. شيء لا يُنسى!', 'Come back for {festival}. It is unforgettable!'],
      ['أجمل وقت هنا هو {festival}. البلد كله يحتفل.', 'The best time to be here is {festival}. The whole country celebrates.'],
      ['هل سمعتم عن {festival}؟ لا بد أن تعيشوا الأجواء.', 'Have you heard of {festival}? You have to feel the atmosphere.'],
      ['أعدّ الأيام حتى {festival} كل عام.', 'I count the days till {festival} every year.'],
    ],
    sport: [
      ['هنا لا حديث إلا عن {sport}.', 'Here nobody talks about anything but {sport}.'],
      ['هل تتابعون {sport}؟ هنا الكل متحمس.', 'Do you follow {sport}? Here everybody is mad about it.'],
      ['في المواسم الكبيرة لا تتكلم البلدة إلا عن {sport}.', 'In the big season the whole town talks about nothing but {sport}.'],
      ['عائلتي كلها تعشق {sport}. أما جدتي فتكتفي بالصراخ.', 'My whole family loves {sport}. My grandmother just shouts.'],
    ],
    wonder: [
      ['إن كان لديكم وقت فاذهبوا لرؤية {wonder}. مشهد لا يُنسى.', 'If you have time, go and see {wonder}. A sight you never forget.'],
      ['هل رأيتم {wonder}؟ لا يوجد مثل ذلك في أي مكان في العالم.', 'Have you seen {wonder}? There is nothing like that anywhere in the world.'],
      ['على كل إنسان أن يرى {wonder} مرة في عمره.', 'Everybody should see {wonder} once in their life.'],
      ['زرت {wonder} في طفولتي، وما زلت أحلم بذلك اليوم.', 'I went to see {wonder} as a child, and I still dream of that day.'],
    ],
    pride: [
      ['أكثر ما نعتز به هنا: {pride}.', 'What we are proudest of here: {pride}.'],
      ['لا تغادروا قبل أن تتعرفوا على {pride}. هذا نحن.', "Don't leave without learning about {pride}. It's who we are."],
      ['تعرفون ما الذي يجعلنا نفخر؟ {pride}.', 'You know what makes us proud? {pride}.'],
      ['اسألوا أي أحد هنا عن {pride}، وسيحدثكم لساعات.', 'Ask anyone here about {pride}, and they will talk for hours.'],
    ],
    proverb: [
      ['كما نقول هنا: «{proverb}»', 'As we say here: “{proverb}”'],
      ['كانت جدتي تقول دائمًا: «{proverb}»', 'My grandmother always said: “{proverb}”'],
      ['عندنا مثل يقول: «{proverb}»', 'We have a saying: “{proverb}”'],
      ['تعرفون المثل؟ «{proverb}»', 'You know the saying? “{proverb}”'],
    ],
    chat: [
      ['من أين أنتم؟ واضح أنكم لستم من هنا.', "Where are you from? You're clearly not from around here."],
      ['خذوا وقتكم وتجوّلوا. هناك الكثير لتروه.', 'Take your time and look around. There is a lot to see.'],
      ['هل تسافرون وحدكم؟ هذه شجاعة.', "Are you travelling alone? That's brave."],
      ['يبدو أنكم مشيتم طريقًا طويلًا.', 'You look like you have walked a long way.'],
      ['إن ضعتم فاسألوا. الناس هنا طيبون.', 'If you get lost, just ask. People here are kind.'],
      ['ما أجمل مكان زرتموه حتى الآن؟', "What's the most beautiful place you've been so far?"],
      ['طالما حلمت بالسفر. ربما يومًا ما، إن شاء الله.', 'I have always dreamed of travelling. One day, God willing.'],
      ['تفضلوا، اشربوا الشاي معنا. لا داعي للعجلة.', 'Please, have some tea with us. No need to hurry.'],
    ],
    childGreet: [
      ['مرحبًا!', 'Hi!'],
      ['أهلًا! من أنتم؟', 'Hello! Who are you?'],
      ['مرحبًا! ما أطولكم!', "Hi! You're so tall!"],
      ['سلام سلام!', 'Hello, hello!'],
    ],
    childChat: [
      ['أنا أركض بسرعة كبيرة! تريدون أن تروا؟ ربما لاحقًا.', 'I can run really fast! Want to see? Maybe later.'],
      ['هل أنتم سياح؟ صديقي يقول إن السياح أغنياء.', 'Are you tourists? My friend says tourists are rich.'],
      ['سقط سني أمس! انظروا! آه، لا يمكن رؤيته.', "I lost a tooth yesterday! Look! Oh, you can't see it."],
      ['أمي تقول إن الكلام مع الغرباء ممنوع. لكن شكلكم لطيف.', "My mum says I mustn't talk to strangers. But you look nice."],
      ['هل عندكم قطة؟ أريد قطة صغيرة.', 'Do you have a cat? I want a kitten.'],
      ['عندما أكبر سأطير بطائرة حول العالم كله!', "When I grow up I'm going to fly a plane all round the world!"],
      ['هل تعرفون ألعابًا؟ أنا أعرف ألعابًا كثيرة.', 'Do you know any games? I know lots of games.'],
    ],
    childBye: [
      ['باي باي!', 'Bye bye!'],
      ['مع السلامة! ارجعوا لنلعب!', 'Bye! Come back and play!'],
      ['يجب أن أذهب، أمي تناديني!', 'I have to go, my mum is calling!'],
      ['إلى اللقاء! لا تنسوني!', "See you! Don't forget me!"],
    ],
    grumpyGreet: [
      ['همم. ماذا تريدون؟', 'Hm. What do you want?'],
      ['نعم؟ ما الأمر؟', 'Yes? What is it?'],
      ['آه. سياح مرة أخرى.', 'Oh. Tourists again.'],
      ['همف. أهلًا، على ما أظن.', 'Hmph. Hello, I suppose.'],
    ],
    grumpyChat: [
      ['كانت الحياة هنا أحسن قبل أن يأتي كل هؤلاء الزوار.', 'It was better here before all these visitors started coming.'],
      ['كل شيء صار بضعف سعره.', 'Everything costs twice what it used to.'],
      ['من فضلكم لا تسدّوا الرصيف. هنا يعيش ناس.', "Don't block the pavement, please. People live here."],
      ['شباب هذه الأيام، عيونهم دائمًا في الهواتف.', 'Young people these days, eyes always on their phones.'],
      ['لا أعرف لماذا يأتي الناس إلى هنا. لا شيء يستحق.', "I don't know why anybody comes here. Nothing worth seeing."],
      ['حتى الخبز لم يعد كما كان.', 'Even the bread is not what it used to be.'],
    ],
    grumpyBye: [
      ['طيب. اذهبوا في حال سبيلكم.', 'Right. Off you go, then.'],
      ['لن أعطّلكم أكثر.', "Well, I won't keep you."],
      ['همم. مع السلامة.', 'Hm. Goodbye.'],
      ['انتبهوا لطريقكم. وأغلقوا الباب وراءكم.', 'Mind how you go. And shut the gate behind you.'],
    ],
    elderChat: [
      ['في شبابي كان كل هذا حقولًا.', 'In my youth, this was all fields.'],
      ['عشت هنا عمري كله. ثمانون سنة! تصدقون؟', 'I have lived here all my life. Eighty years! Can you believe it?'],
      ['في أيامنا كنا نمشي إلى كل مكان. وأنتم تمشون أيضًا، هذا جميل!', 'In our day we walked everywhere. You walk too, how nice!'],
      ['أحفادي يعيشون في الخارج الآن. يتصلون بي كل جمعة.', 'My grandchildren live abroad now. They call me every Friday.'],
      ['الدنيا تتغير بسرعة، لكن الحارات القديمة باقية كما هي.', 'The world changes so fast. But the old lanes stay the same.'],
      ['أذكر أيامًا كنا نحمل فيها الماء من البئر.', 'I remember the days when we carried water from the well.'],
    ],
    chattyChat: [
      ['آه، أحب لقاء المسافرين! احكوا لي كل شيء. لا، انتظروا، دعوني أحكي أولًا.', "Oh, I love meeting travellers! Tell me everything. No, wait, let me tell you first."],
      ['ابن عمي سافر مرة، ورجع بلحية وزوجة!', 'My cousin went travelling once. He came back with a beard and a wife!'],
      ['أصحابي يقولون إنني أتكلم طول النهار. وهم محقون!', "My friends say I talk all day. They're not wrong!"],
      ['هل أكلتم شيئًا؟ لا بد أن تأكلوا عندنا، البيت بيتكم!', 'Have you eaten anything? You must eat with us, our home is yours!'],
      ['سأقول لكم سرًّا: أجمل منظر في البلدة من التلة خلف السوق.', 'Let me tell you a secret: the best view in town is from the hill behind the market.'],
    ],
    bye: [
      ['مع السلامة! رحلة سعيدة.', 'Goodbye! Have a good trip.'],
      ['في أمان الله!', 'Go in the safety of God!'],
      ['الله معكم! استمتعوا ببقية الرحلة.', 'God be with you! Enjoy the rest of your journey.'],
      ['توصلون بالسلامة!', 'Safe travels!'],
      ['إلى اللقاء! زورونا مرة أخرى.', 'Bye now! Come back and see us.'],
      ['سُررت بالحديث معكم. انتبهوا لأنفسكم!', 'Nice talking to you. Look after yourself!'],
    ],
  },
  countries: {
    // Every fact is a definite noun phrase as it stands mid-sentence (الكشري, عيد الفطر),
    // which the templates take as an object, after a colon or after a separate preposition.
    EGY: {
      dish: ['الكشري', 'koshari'],
      drink: ['الكركديه', 'hibiscus tea'],
      festival: ['شم النسيم', 'Sham el-Nessim, the spring festival'],
      sport: ['كرة القدم', 'football'],
      wonder: ['أهرامات الجيزة', 'the pyramids of Giza'],
      pride: ['السينما المصرية', 'Egyptian cinema'],
      proverb: ['القرد في عين أمه غزال', "In his mother's eyes, the monkey is a gazelle"],
    },
    SAU: {
      dish: ['الكبسة', 'kabsa'],
      drink: ['القهوة العربية', 'Arabic coffee'],
      festival: ['موسم الرياض', 'Riyadh Season'],
      sport: ['كرة القدم', 'football'],
      wonder: ['مدائن صالح في العلا', 'Hegra in AlUla'],
      pride: ['كرم الضيافة', 'our hospitality'],
      proverb: ['الجار قبل الدار', 'Choose the neighbour before the house'],
    },
    DZA: {
      dish: ['الشخشوخة', 'chakhchoukha'],
      drink: ['الشاي بالنعناع', 'mint tea'],
      festival: ['عيد الفطر', 'Eid al-Fitr'],
      sport: ['كرة القدم', 'football'],
      wonder: ['طاسيلي ناجر', "the Tassili n'Ajjer"],
      pride: ['موسيقى الراي', 'raï music'],
      proverb: ['من جدّ وجد، ومن زرع حصد', 'Who strives, finds; who sows, reaps'],
    },
    MAR: {
      dish: ['الطاجين', 'tagine'],
      drink: ['أتاي بالنعناع', 'atay, mint tea'],
      festival: ['مهرجان الورود في قلعة مكونة', 'the Rose Festival of Kelaat M’Gouna'],
      sport: ['كرة القدم', 'football'],
      wonder: ['جبال الأطلس', 'the Atlas Mountains'],
      pride: ['الزليج', 'zellige tilework'],
      proverb: ['اللي فاتك بليلة فاتك بحيلة', 'Whoever is one night older than you is one trick wiser'],
    },
    IRQ: {
      dish: ['المسكوف', 'masgouf, grilled river fish'],
      drink: ['الشاي بالهيل', 'cardamom tea'],
      festival: ['عيد الأضحى', 'Eid al-Adha'],
      sport: ['كرة القدم', 'football'],
      wonder: ['أهوار الجنوب', 'the southern marshes'],
      pride: ['المقام العراقي', 'the Iraqi maqam'],
      proverb: ['الوقت كالسيف، إن لم تقطعه قطعك', "Time is like a sword: if you don't cut it, it cuts you"],
    },
    SDN: {
      dish: ['العصيدة', 'asida'],
      drink: ['قهوة الجبنة', 'jebena coffee'],
      festival: ['عيد الفطر', 'Eid al-Fitr'],
      sport: ['كرة القدم', 'football'],
      wonder: ['أهرامات مروي', 'the pyramids of Meroë'],
      pride: ['كرم الضيافة السوداني', 'Sudanese hospitality'],
      proverb: ['الصبر مفتاح الفرج', 'Patience is the key to relief'],
    },
    YEM: {
      dish: ['السلتة', 'saltah'],
      drink: ['القهوة اليمنية', 'Yemeni coffee'],
      festival: ['عيد الفطر', 'Eid al-Fitr'],
      sport: ['كرة القدم', 'football'],
      wonder: ['جزيرة سقطرى', 'the island of Socotra'],
      pride: ['العسل الدوعني', "Do'an honey"],
      proverb: ['رُبّ أخ لك لم تلده أمك', 'Many a brother of yours was not born to your mother'],
    },
    SYR: {
      dish: ['الكبة', 'kibbeh'],
      drink: ['العرقسوس', 'licorice juice'],
      festival: ['عيد الفطر', 'Eid al-Fitr'],
      sport: ['كرة القدم', 'football'],
      wonder: ['دمشق القديمة', 'old Damascus'],
      pride: ['صابون حلب', 'Aleppo soap'],
      proverb: ['إيد لوحدها ما بتصفق', 'One hand alone cannot clap'],
    },
    TUN: {
      dish: ['الكسكسي', 'couscous'],
      festival: ['مهرجان قرطاج الدولي', 'the Carthage International Festival'],
      sport: ['كرة القدم', 'football'],
      wonder: ['جزيرة جربة', 'the island of Djerba'],
      pride: ['زيت الزيتون', 'our olive oil'],
      proverb: ['من طلب العلا سهر الليالي', 'Whoever seeks the heights stays up the nights'],
    },
    JOR: {
      dish: ['المنسف', 'mansaf'],
      drink: ['القهوة السادة', 'bitter Arabic coffee'],
      festival: ['مهرجان جرش', 'the Jerash Festival'],
      sport: ['كرة القدم', 'football'],
      wonder: ['البتراء', 'Petra'],
      pride: ['الدبكة', 'the dabke dance'],
      proverb: ['بكرة بيذوب الثلج وبيبان المرج', 'Tomorrow the snow melts and the meadow shows'],
    },
    ARE: {
      dish: ['اللقيمات', 'luqaimat, sweet dumplings'],
      drink: ['القهوة العربية', 'Arabic coffee'],
      festival: ['مهرجان دبي للتسوق', 'the Dubai Shopping Festival'],
      sport: ['سباقات الهجن', 'camel racing'],
      wonder: ['صحراء ليوا', 'the Liwa desert'],
      pride: ['الصقارة', 'falconry'],
      proverb: ['العين ما تعلى على الحاجب', 'The eye does not rise above the eyebrow'],
    },
    LBY: {
      dish: ['البازين', 'bazeen'],
      festival: ['عيد الفطر', 'Eid al-Fitr'],
      sport: ['كرة القدم', 'football'],
      wonder: ['مدينة غدامس القديمة', 'the old town of Ghadames'],
      pride: ['آثار لبدة الكبرى', 'the ruins of Leptis Magna'],
      proverb: ['الصديق وقت الضيق', 'A friend is for the hard times'],
    },
    LBN: {
      dish: ['التبولة', 'tabbouleh'],
      drink: ['الجلاب', 'jallab'],
      festival: ['مهرجانات بعلبك', 'the Baalbeck Festival'],
      sport: ['كرة السلة', 'basketball'],
      wonder: ['مغارة جعيتا', 'the Jeita Grotto'],
      pride: ['شجرة الأرز', 'the cedar tree'],
      proverb: ['كل تأخيرة فيها خيرة', 'Every delay holds some good'],
    },
    PSE: {
      dish: ['الكنافة النابلسية', 'knafeh from Nablus'],
      drink: ['الشاي بالميرمية', 'sage tea'],
      festival: ['موسم قطف الزيتون', 'the olive harvest'],
      sport: ['كرة القدم', 'football'],
      pride: ['التطريز الفلسطيني', 'Palestinian embroidery'],
      proverb: ['الغايب حجّته معه', 'The absent one carries his excuse with him'],
    },
    OMN: {
      dish: ['الشواء العماني', 'Omani shuwa'],
      drink: ['القهوة العمانية', 'Omani coffee'],
      festival: ['عيد الفطر', 'Eid al-Fitr'],
      sport: ['كرة القدم', 'football'],
      wonder: ['جبل شمس', 'Jebel Shams'],
      pride: ['اللبان', 'frankincense'],
      proverb: ['في التأني السلامة وفي العجلة الندامة', 'In patience lies safety, in haste regret'],
    },
    KWT: {
      dish: ['المجبوس', 'machboos'],
      drink: ['القهوة العربية', 'Arabic coffee'],
      festival: ['هلا فبراير', 'Hala February'],
      sport: ['كرة القدم', 'football'],
      wonder: ['أبراج الكويت', 'the Kuwait Towers'],
      pride: ['نسيج السدو', 'Al Sadu weaving'],
      proverb: ['القناعة كنز لا يفنى', 'Contentment is a treasure that never runs out'],
    },
    MRT: {
      drink: ['الشاي الموريتاني', 'Mauritanian tea'],
      festival: ['مهرجان مدائن التراث', 'the Festival of the Ancient Cities'],
      sport: ['كرة القدم', 'football'],
      wonder: ['عين الصحراء', 'the Eye of the Sahara'],
      pride: ['مخطوطات شنقيط', 'the manuscripts of Chinguetti'],
      proverb: ['لكل مقام مقال', 'Every occasion has its fitting words'],
    },
    QAT: {
      dish: ['الهريس', 'harees'],
      drink: ['شاي الكرك', 'karak tea'],
      festival: ['القرنقعوه', 'Garangao, the children’s mid-Ramadan night'],
      sport: ['كرة القدم', 'football'],
      wonder: ['خور العديد', 'Khor Al Adaid, the inland sea'],
      pride: ['متحف الفن الإسلامي', 'the Museum of Islamic Art'],
      proverb: ['اللي ما يعرف الصقر يشويه', "Whoever doesn't know a falcon will roast it"],
    },
    BHR: {
      dish: ['المحمّر', 'muhammar, sweet rice'],
      festival: ['عيد الفطر', 'Eid al-Fitr'],
      sport: ['كرة القدم', 'football'],
      wonder: ['شجرة الحياة', 'the Tree of Life'],
      pride: ['اللؤلؤ البحريني', 'Bahraini pearls'],
      proverb: ['خير الكلام ما قلّ ودلّ', 'The best speech is brief and to the point'],
    },
    COM: {
      festival: ['عيد الفطر', 'Eid al-Fitr'],
      sport: ['كرة القدم', 'football'],
      wonder: ['بركان كارتالا', 'the Karthala volcano'],
      pride: ['الفانيليا', 'our vanilla'],
      proverb: ['العلم نور', 'Knowledge is light'],
    },
  },
};

export default AR;
