import type { Language } from '../phrases.ts';

const BN: Language = {
  locale: 'bn',
  name: 'Bengali',
  join: ' ',
  compass: ['উত্তরে', 'উত্তর-পূর্বে', 'পূর্বে', 'দক্ষিণ-পূর্বে', 'দক্ষিণে', 'দক্ষিণ-পশ্চিমে', 'পশ্চিমে', 'উত্তর-পশ্চিমে'],
  lines: {
    morning: [
      ['শুভ সকাল!', 'Good morning!'],
      ['আসসালামু আলাইকুম! সকালটা কী সুন্দর, তাই না?', 'Peace be upon you! Lovely morning, isn’t it?'],
      ['এই যে, শুভ সকাল!', 'Hey there, good morning!'],
      ['সকাল সকাল দেখা হয়ে গেল! কেমন আছেন?', 'Meeting so early! How are you?'],
    ],
    afternoon: [
      ['শুভ অপরাহ্ন!', 'Good afternoon!'],
      ['আসসালামু আলাইকুম!', 'Peace be upon you!'],
      ['এই যে, কেমন আছেন?', 'Hey there, how are you?'],
      ['দুপুরে খাওয়া হয়েছে?', 'Had your lunch?'],
    ],
    evening: [
      ['শুভ সন্ধ্যা!', 'Good evening!'],
      ['সন্ধ্যা হয়ে এলো, কেমন আছেন?', 'Evening’s falling, how are you?'],
      ['আসসালামু আলাইকুম! হাঁটতে বেরিয়েছেন?', 'Peace be upon you! Out for a walk?'],
      ['বাহ, কী সুন্দর সন্ধ্যা!', 'Wow, what a lovely evening!'],
    ],
    night: [
      ['শুভ সন্ধ্যা! অনেক রাত হয়ে গেছে, তাই না?', 'Good evening! It’s very late, isn’t it?'],
      ['ওমা! ভয় পাইয়ে দিয়েছিলেন। আসসালামু আলাইকুম!', 'Oh my! You gave me a fright. Peace be upon you!'],
      ['এত রাতে হাঁটছেন?', 'Walking so late at night?'],
      ['রাত তো অনেক হলো! ঘুম আসছে না বুঝি?', 'It’s late indeed! Can’t sleep, is that it?'],
    ],
    again: [
      ['আরে, আবার আপনি! কেমন আছেন?', 'Oh, you again! How are you?'],
      ['আবার দেখা হয়ে গেল!', 'We meet again!'],
      ['আবারও আপনি! ঘোরাঘুরি চলছে তো?', 'You again! Still wandering about?'],
      ['আরে, আপনি! পথ খুঁজে পেয়েছেন?', 'Oh, it’s you! Did you find your way?'],
    ],
    welcome: [
      ['স্বাগতম! এটাই {town}।', 'Welcome! This is {town}.'],
      ['এটা {town}। আপনি কি বেড়াতে এসেছেন?', 'This is {town}. Are you here visiting?'],
      ['প্রথমবার {town} আসা?', 'First time in {town}?'],
      ['আজ {town} দেখার জন্য দারুণ দিন।', 'Today is a great day to see {town}.'],
      ['স্বাগতম, স্বাগতম! {town} আপনাকে পেয়ে খুশি।', 'Welcome, welcome! {town} is glad to have you.'],
      ['তা, {town} কেমন লাগছে?', 'So, how do you like {town}?'],
    ],
    capitalHere: [
      ['{town} আমাদের দেশের রাজধানী।', '{town} is the capital of our country.'],
      ['রাজধানী বলে কথা! সব কাজকর্ম এখানেই হয়।', 'It’s the capital, after all! Everything gets done right here.'],
      ['সরকার এখানেই বসে। চারদিকে বড় বড় অফিস আর স্যুট-পরা মানুষ।', 'The government sits right here. Big offices and people in suits everywhere.'],
      ['রাজধানী তো, {town} কখনো ঘুমায় না।', 'Being the capital, {town} never sleeps.'],
    ],
    capitalThere: [
      ['আমাদের রাজধানী {capital}। সেখানে একবার যাওয়ার মতো।', 'Our capital is {capital}. It’s worth going once.'],
      ['{capital} গেছেন কখনো? ওটাই আমাদের রাজধানী।', 'Ever been to {capital}? That’s our capital.'],
      ['রাজধানী {capital} শহরের লোকেরা ভাবে দেশটা তারাই চালায়। তা, চালায়ও বটে।', 'People in the capital, {capital}, think they run the country. Well, they do.'],
      ['{capital} বড় শহর, কিন্তু আমার এখানেই ভালো লাগে।', '{capital} is a big city, but I like it here.'],
    ],
    big: [
      ['এটা একটা বড় শহর। এখানে সহজেই পথ হারানো যায়!', 'This is a big city. It’s easy to get lost here!'],
      ['এত মানুষ! সারা জীবন থেকেও সব গলি চেনা যাবে না।', 'So many people! You could live here all your life and not know every lane.'],
      ['এখানকার জ্যাম, বাপরে! তবে সবসময় কিছু না কিছু হচ্ছে।', 'The traffic jams here, good grief! But something is always going on.'],
      ['বড় শহর, কখনো থামে না। আমার তো ভালোই লাগে।', 'A big city never stops. I quite like it.'],
    ],
    middling: [
      ['খুব বড়ও না, খুব ছোটও না। ঠিকঠাক।', 'Not too big, not too small. Just right.'],
      ['দরকারি সবকিছুই আছে, আবার হেঁটেই ঘোরা যায়।', 'It has everything you need, and you can walk it all.'],
      ['এক-দুই দিনেই পুরো {town} দেখে ফেলতে পারবেন।', 'You can see all of {town} in a day or two.'],
      ['সবাই বলে জায়গাটা বড্ড শান্ত, কিন্তু কেউ ছেড়ে যায় না।', 'Everyone says it’s too quiet, but nobody ever leaves.'],
    ],
    small: [
      ['এটা একটা ছোট জায়গা। এখানে সবাই সবাইকে চেনে।', 'It’s a small place. Everybody knows everybody here.'],
      ['ছোট্ট জায়গা। হাঁচি দিলেও পুরো পাড়া জেনে যায়।', 'Tiny place. Sneeze and the whole neighbourhood knows.'],
      ['{town} এলাকায় তেমন কিছু ঘটে না, আর আমরা সেটাই পছন্দ করি।', 'Not much happens around {town}, and we like it that way.'],
      ['এই সপ্তাহে আপনিই সবচেয়ে বড় খবর!', 'You’re the biggest news this week!'],
    ],
    coast: [
      ['আমরা এখানে পানির ধারে থাকি। মাছ খুব ভালো।', 'We live by the water here. The fish is very good.'],
      ['গিয়ে পানির দিকে তাকান। প্রতিদিন রং বদলায়।', 'Go and look at the water. It changes colour every day.'],
      ['গন্ধটা পাচ্ছেন? সাগরের। কখনো পুরনো হয় না।', 'Smell that? The sea. It never gets old.'],
      ['ভোরে নৌকা বের হয়, ফেরে তাজা মাছ নিয়ে।', 'The boats go out at dawn and come back with fresh fish.'],
    ],
    inland: [
      ['সাগর অনেক দূরে, কিন্তু এখানকার প্রকৃতি খুব সুন্দর।', 'The sea is far away, but the countryside here is beautiful.'],
      ['এখানে সৈকত নেই। কিন্তু এই মাঠগুলো দেখুন।', 'No beach here. But look at these fields.'],
      ['সাগর? সত্যি বলতে কখনো দেখিনি। অনেক দূর।', 'The sea? Honestly, I’ve never seen it. It’s very far.'],
      ['এখানে মাটিই সব। ভালো মাটি, ভালো মানুষ।', 'Here the soil is everything. Good soil, good people.'],
    ],
    high: [
      ['আমরা অনেক উঁচুতে আছি। আস্তে হাঁটুন, বাতাস পাতলা।', 'We’re high up. Walk slowly, the air is thin.'],
      ['পাহাড়ে থাকার সবচেয়ে ভালো জিনিস এই দৃশ্য।', 'The best thing about living in the hills is this view.'],
      ['এখানে থাকলে পা শক্ত হয়ে যায়। কিছুই সমান না।', 'Living here makes your legs strong. Nothing is flat.'],
      ['দম সামলে! পাহাড়ে অভ্যস্ত হতে সময় লাগে।', 'Mind your breath! The hills take getting used to.'],
    ],
    snowy: [
      ['বছরে নয় মাস বরফ। বাকি তিন মাস কাদা নিয়ে অভিযোগ।', 'Snow nine months a year. The other three, complaints about mud.'],
      ['এখানে সব সাদা। এই জুতোয় চলবে না।', 'Everything’s white here. Those shoes won’t do.'],
      ['তাজা বরফ পড়লে এত নীরব যে নিজের নিঃশ্বাস শোনা যায়।', 'When fresh snow falls it’s so quiet you can hear yourself breathe.'],
      ['ঠান্ডা আমাদের গা-সওয়া। এক কাপ গরম চা থাকলেই হলো।', 'We’re used to the cold. A cup of hot tea is all it takes.'],
    ],
    forest: [
      ['এখানে জঙ্গল মাইলের পর মাইল। পথ ছেড়ে যাবেন না!', 'The forest goes on for miles here. Don’t leave the path!'],
      ['বনে একটু হেঁটে আসুন। মাথা হালকা হয়ে যায়।', 'Take a little walk in the woods. It clears the head.'],
      ['সন্ধ্যায় বন থেকে পাখির ডাক শোনা যায়।', 'In the evening you hear the birds calling from the forest.'],
      ['গাছ আর গাছ। অন্য কোথাও থাকতে মন চায় না।', 'Trees and more trees. I wouldn’t want to live anywhere else.'],
    ],
    desert: [
      ['এখানে যতদূর চোখ যায় শুধু বালি।', 'Here it’s sand as far as the eye can see.'],
      ['অনেক পানি খান। মরুভূমি কাউকে ক্ষমা করে না।', 'Drink plenty of water. The desert forgives no one.'],
      ['মরুভূমির রাত কিন্তু ঠান্ডা। কেউ বিশ্বাস করে না।', 'Desert nights are cold, you know. Nobody believes it.'],
      ['আজ রাতে তারা দেখবেন। এখানে লাখ লাখ তারা।', 'Look at the stars tonight. There are millions here.'],
    ],
    plains: [
      ['মাইলের পর মাইল সমতল। ঝড় আসার আগেই দেখা যায়।', 'Flat for miles. You can see a storm before it arrives.'],
      ['খোলা আকাশ, বাতাস আটকানোর কিছু নেই।', 'Open sky, nothing to stop the wind.'],
      ['সবটাই চারণভূমি। গরু-ছাগল থেকে সাবধান।', 'It’s all grazing land. Watch out for the cows and goats.'],
      ['ঘাস আর ঘাস, যেন সবুজ সমুদ্র।', 'Grass and more grass, like a green sea.'],
    ],
    tropical: [
      ['এখানে সব গজায়। একটা ডাল পুঁতে দিলেই গাছ।', 'Everything grows here. Stick a branch in the ground and it’s a tree.'],
      ['বৃষ্টি এলে ঝমঝমিয়ে আসে, তারপর হঠাৎ থেমে যায়।', 'When the rain comes it pours, then suddenly stops.'],
      ['বাজারের ফল খেয়ে দেখুন। এমন স্বাদ কোথাও পাবেন না।', 'Try the fruit at the market. You won’t find a taste like it anywhere.'],
      ['সারা বছর সবুজ। শীত? সেটা আবার কী?', 'Green all year. Winter? What’s that?'],
    ],
    landmark: [
      ['{landmark} অবশ্যই দেখবেন! এখান থেকে প্রায় {km} কিমি {dir}।', 'Be sure to see {landmark}! It’s about {km} km from here, {dir}.'],
      ['{landmark} দেখতে ভুলবেন না! মাত্র {km} কিমি {dir}।', 'Don’t forget to see {landmark}! Only {km} km {dir}.'],
      ['সবাই {landmark} দেখতে যায়। এখান থেকে প্রায় {km} কিমি {dir}।', 'Everyone goes to see {landmark}. About {km} km from here, {dir}.'],
      ['পুরনো জিনিস ভালো লাগলে {landmark} যান, {km} কিমি {dir}। দূর-দূরান্ত থেকে লোক আসে।', 'If you like old things, go to {landmark}, {km} km {dir}. People come from far away.'],
    ],
    landmarkNear: [
      ['{landmark} খুব কাছেই। আপনি সহজেই খুঁজে পাবেন!', '{landmark} is very close. You’ll find it easily!'],
      ['{landmark} একদম কাছেই। না দেখে যাবেন না।', '{landmark} is right nearby. Don’t leave without seeing it.'],
      ['রোজ {landmark} দেখি, তবু মুগ্ধ হই।', 'I see {landmark} every day, and it still amazes me.'],
      ['{landmark} তো এখানেই! ভিড়ের আগে সকাল সকাল যান।', '{landmark} is right here! Go early, before the crowds.'],
    ],
    plane: [
      ['{dir} একটা মাঠে ছোট্ট একটা বিমান আছে, ওড়াতে পারলে!', 'There’s a little plane in a field {dir}, if you can fly!'],
      ['কেউ {dir} একটা বিমান রেখে গেছে। উড়বেন নাকি?', 'Somebody left a plane {dir}. Fancy a flight?'],
      ['ওড়াতে জানেন? {dir} একটা বিমান অপেক্ষা করছে।', 'Can you fly? A plane is waiting {dir}.'],
      ['ওপর থেকে সব দেখতে চাইলে {dir} একটা বিমান আছে।', 'If you want to see it all from above, there’s a plane {dir}.'],
    ],
    balloon: [
      ['{dir} মাঠে একটা গরম বাতাসের বেলুন আছে! ভাবুন তো কী দৃশ্য!', 'There’s a hot-air balloon in a field {dir}! Imagine the view!'],
      ['কখনো বেলুনে উড়েছেন? {dir} একটা আছে।', 'Ever flown in a balloon? There’s one {dir}.'],
      ['{dir} মাঠ থেকে একটা বেলুন ওড়ে। জাদুর মতো লাগে।', 'A balloon goes up from the field {dir}. It’s like magic.'],
      ['{dir} বেলুনটায় চড়ার খুব শখ, কিন্তু আমার ভয় করে!', 'I’d love to ride the balloon {dir}, but I’m scared!'],
    ],
    boat: [
      ['{dir} ঘাটে একটা নৌকা আছে, ঘুরতে চাইলে।', 'There’s a boat at the landing {dir}, if you want to go out.'],
      ['পানি ভালোবাসলে {dir} একটা নৌকা আছে। শুধু ফেরত দেবেন!', 'If you love the water, there’s a boat {dir}. Just bring it back!'],
      ['{dir} একটা নৌকা বাঁধা আছে। এখান থেকে যেখানে খুশি যাওয়া যায়।', 'A boat is tied up {dir}. From here you can go wherever you like.'],
      ['{dir} নৌকাটা নিয়ে পানি থেকে পাড়টা দেখে আসুন।', 'Take the boat {dir} and see the shore from the water.'],
    ],
    hot: [
      ['আজ খুব গরম! একটু ছায়া খুঁজে নিন।', 'It’s very hot today! Find some shade.'],
      ['উফ, কী গরম! একটু পানি খান।', 'Phew, what heat! Have some water.'],
      ['এই গরমে ছায়ায় বসে থাকা ছাড়া কিছু করার নেই।', 'In this heat there’s nothing to do but sit in the shade.'],
      ['এমন গরমে কুকুরগুলোও ঘর থেকে বের হয় না।', 'In heat like this even the dogs stay indoors.'],
      ['গরম, তাই না? আর এটা আমাদের হিসাবে ঠান্ডা দিন!', 'Hot, isn’t it? And by our standards this is a cool day!'],
    ],
    cold: [
      ['উফ, আজ বেশ ঠান্ডা! গরম কাপড় পরে নিন।', 'Ooh, it’s quite cold today! Put on something warm.'],
      ['কনকনে ঠান্ডা! আপনার দস্তানা কোথায়?', 'Biting cold! Where are your gloves?'],
      ['এত ঠান্ডা যে নাকটা আর টের পাচ্ছি না।', 'It’s so cold I can’t feel my nose any more.'],
      ['এ তো কিছুই না, বাতাস উঠুক আগে।', 'This is nothing, wait till the wind gets up.'],
      ['গরম কিছু খেয়ে নিন। এক কাপ চা হলে তো কথাই নেই।', 'Have something hot. A cup of tea, and there’s nothing better.'],
    ],
    mild: [
      ['আজ আবহাওয়াটা কী সুন্দর।', 'What lovely weather today.'],
      ['খুব গরমও না, খুব ঠান্ডাও না। দারুণ দিন, তাই না?', 'Not too hot, not too cold. A great day, isn’t it?'],
      ['এমন দিনে ঘরে বসে থাকা যায় না।', 'You can’t stay indoors on a day like this.'],
      ['চমৎকার আবহাওয়া! এমনই থাকুক।', 'Wonderful weather! May it stay like this.'],
      ['এমন দিনের জন্যই তো এখানে থাকি।', 'Days like this are why we live here.'],
    ],
    late: [
      ['রাত হয়ে গেছে। রাতে রাস্তাগুলো শান্ত থাকে।', 'It’s late. The streets are quiet at night.'],
      ['এই সময়ে শুধু বিড়ালেরা বাইরে থাকে। আর আমরা!', 'At this hour only the cats are out. And us!'],
      ['আমার তো এতক্ষণে ঘুমিয়ে পড়ার কথা। আপনি জেগে কেন?', 'I should have been asleep by now. Why are you up?'],
      ['তারাগুলো দেখুন! এখান থেকে সবচেয়ে ভালো দেখা যায়।', 'Look at the stars! You see them best from here.'],
    ],
    early: [
      ['এত সকালে উঠেছেন! দিনের সবচেয়ে ভালো সময়।', 'Up so early! The best time of the day.'],
      ['চায়ের দোকান এইমাত্র খুলল। গন্ধ ধরে চলে যান!', 'The tea stall has just opened. Follow the smell!'],
      ['শহর এখনো ঘুম থেকে ওঠেনি।', 'The town isn’t even awake yet.'],
      ['কোলাহল শুরুর আগের সকালটা আমার খুব প্রিয়।', 'I love the morning here before the noise starts.'],
    ],
    country: [
      ['{country} একটি সুন্দর দেশ। উপভোগ করুন!', '{country} is a beautiful country. Enjoy it!'],
      ['এ পর্যন্ত {country} কেমন লাগছে?', 'How do you like {country} so far?'],
      ['পারলে পুরো {country} ঘুরে দেখুন। প্রতিটা কোনা আলাদা।', 'If you can, travel all over {country}. Every corner is different.'],
      ['মানচিত্রে {country} ছোট, কিন্তু মনটা বিশাল।', 'On the map {country} is small, but its heart is huge.'],
    ],
    dish: [
      ['এখানে এসে {dish} না খেয়ে যাবেন না।', 'Don’t leave here without eating {dish}.'],
      ['{dish} খেয়েছেন? না? অবশ্যই খাবেন!', 'Have you had {dish}? No? You must!'],
      ['{dish} রান্নায় আমার মায়ের কোনো তুলনা নেই।', 'Nobody cooks {dish} like my mother.'],
      ['খিদে পেলে {dish} খান। আফসোস করবেন না।', 'If you’re hungry, have {dish}. You won’t regret it.'],
    ],
    drink: [
      ['যাওয়ার আগে একটু {drink} খেয়ে যান। এখানে সবাই খায়।', 'Have some {drink} before you go. Everybody here does.'],
      ['দিনশেষে {drink}, এর চেয়ে ভালো কিছু নেই।', '{drink} at the end of the day, nothing better.'],
      ['{drink} না খেলে কিছুই খাননি।', 'If you haven’t had {drink}, you haven’t had anything.'],
      ['স্থানীয়দের মতো {drink} চান, সবাই খুশি হবে।', 'Ask for {drink} like a local and everyone will be pleased.'],
    ],
    festival: [
      ['{festival} উপলক্ষে আবার আসবেন। দারুণ হয়!', 'Come back for {festival}. It’s wonderful!'],
      ['এখানে আসার সেরা সময় {festival}। সারা দেশ উৎসবে মাতে।', 'The best time to come is {festival}. The whole country celebrates.'],
      ['{festival} সম্পর্কে শুনেছেন? আপনার খুব ভালো লাগবে।', 'Have you heard of {festival}? You’d love it.'],
      ['প্রতি বছর {festival} আসার দিন গুনি।', 'Every year I count the days till {festival}.'],
    ],
    sport: [
      ['এখানে সবকিছুই {sport}। সবাই খেলে।', 'Here it’s all about {sport}. Everybody plays.'],
      ['{sport} ভালো লাগে? এখানে সবাই পাগল।', 'Do you like {sport}? Everyone here is crazy about it.'],
      ['খেলার দিন পুরো শহর শুধু {sport} নিয়েই কথা বলে।', 'On match day the whole town talks about nothing but {sport}.'],
      ['আমাদের পুরো পরিবার {sport} খেলে। দাদি অবশ্য শুধু চেঁচায়।', 'My whole family plays {sport}. Grandma just shouts, mind you.'],
    ],
    wonder: [
      ['সময় পেলে {wonder} দেখে আসুন। কোনোদিন ভুলবেন না।', 'If you have time, go and see {wonder}. You’ll never forget it.'],
      ['{wonder} দেখেছেন? পৃথিবীতে এমন আর নেই।', 'Have you seen {wonder}? There’s nothing like it in the world.'],
      ['জীবনে একবার হলেও {wonder} দেখা উচিত।', 'Everyone should see {wonder} at least once in their life.'],
      ['ছোটবেলায় {wonder} দেখতে গিয়েছিলাম। এখনো স্বপ্নে দেখি।', 'I went to see {wonder} as a child. I still dream about it.'],
    ],
    pride: [
      ['{pride} নিয়ে আমাদের খুব গর্ব।', 'We are very proud of {pride}.'],
      ['{pride} সম্পর্কে না জেনে যাবেন না। এটাই আমরা।', 'Don’t leave without learning about {pride}. That’s who we are.'],
      ['আমাদের গর্ব কী জানেন? {pride}।', 'Do you know what our pride is? {pride}.'],
      ['যে কাউকে {pride} নিয়ে জিজ্ঞেস করুন, ঘণ্টার পর ঘণ্টা বলবে।', 'Ask anyone about {pride}, and they’ll talk for hours.'],
    ],
    proverb: [
      ['আমাদের এখানে বলে: “{proverb}”', 'As we say here: “{proverb}”'],
      ['আমার দাদি সবসময় বলতেন: “{proverb}”', 'My grandmother always said: “{proverb}”'],
      ['একটা কথা আছে না? “{proverb}”', 'You know the saying? “{proverb}”'],
      ['এখানে একটা প্রবাদ আছে: “{proverb}”', 'There’s a proverb here: “{proverb}”'],
    ],
    chat: [
      ['আপনি কোথা থেকে এসেছেন? আপনি তো এখানকার নন।', 'Where have you come from? You’re not from around here.'],
      ['ধীরে-সুস্থে ঘুরে দেখুন। এখানে দেখার অনেক কিছু আছে।', 'Take your time looking around. There’s a lot to see here.'],
      ['একা একা ঘুরছেন? সাহস আছে বলতে হবে।', 'Travelling all alone? That takes courage, I must say.'],
      ['মনে হচ্ছে অনেক দূর হেঁটে এসেছেন।', 'Looks like you’ve walked a long way.'],
      ['পথ হারালে যে কাউকে জিজ্ঞেস করবেন। এখানকার মানুষ খুব আন্তরিক।', 'If you get lost, ask anyone. People here are very warm.'],
      ['এ পর্যন্ত কোন জায়গাটা সবচেয়ে ভালো লেগেছে?', 'Which place have you liked best so far?'],
      ['আমারও ঘোরার খুব শখ। একদিন নিশ্চয়ই।', 'I’d love to travel too. One day, for sure.'],
      ['এক কাপ চা খাবেন?', 'Will you have a cup of tea?'],
    ],
    childGreet: [
      ['হাই!', 'Hi!'],
      ['এই যে! আপনি কে?', 'Hey! Who are you?'],
      ['হাই! আপনি কত লম্বা!', 'Hi! You’re so tall!'],
      ['হ্যালো হ্যালো!', 'Hello, hello!'],
    ],
    childChat: [
      ['আমি খুব জোরে দৌড়াতে পারি! দেখবেন? পরে।', 'I can run really fast! Want to see? Later.'],
      ['আপনি কি ট্যুরিস্ট? আমার বন্ধু বলে ট্যুরিস্টরা অনেক বড়লোক।', 'Are you a tourist? My friend says tourists are very rich.'],
      ['কাল আমার একটা দাঁত পড়েছে! দেখুন! ওহ, দেখা যাচ্ছে না।', 'A tooth fell out yesterday! Look! Oh, you can’t see it.'],
      ['আম্মু বলেছে অচেনা লোকের সাথে কথা না বলতে। কিন্তু আপনাকে ভালো মনে হচ্ছে।', 'Mum said not to talk to strangers. But you seem nice.'],
      ['আপনার কুকুর আছে? আমার একটা বিড়াল ছানা চাই।', 'Do you have a dog? I want a kitten.'],
      ['বড় হয়ে আমি বিমান চালিয়ে সারা দুনিয়া ঘুরব!', 'When I grow up I’ll fly a plane all round the world!'],
      ['আপনি কোনো খেলা জানেন? আমি অনেক খেলা জানি।', 'Do you know any games? I know lots of games.'],
    ],
    childBye: [
      ['টাটা!', 'Ta-ta!'],
      ['বাই! আবার খেলতে আসবেন!', 'Bye! Come back and play!'],
      ['যাই, আম্মু ডাকছে!', 'Gotta go, Mum’s calling!'],
      ['বাই বাই! আবার দেখা হবে!', 'Bye bye! See you again!'],
    ],
    grumpyGreet: [
      ['হুঁ। কী চাই?', 'Hm. What do you want?'],
      ['হ্যাঁ? কী ব্যাপার?', 'Yes? What is it?'],
      ['ওহ। আরেকজন ট্যুরিস্ট।', 'Oh. Another tourist.'],
      ['হুম। আচ্ছা, সালাম।', 'Hm. Well, hello.'],
    ],
    grumpyChat: [
      ['আগে এখানে অনেক ভালো ছিল, সবাই বেড়াতে আসার আগে।', 'It was much better here before everybody started visiting.'],
      ['সবকিছুর দাম দ্বিগুণ হয়ে গেছে।', 'Everything costs double now.'],
      ['রাস্তা আটকাবেন না, দয়া করে। এখানে মানুষ থাকে।', 'Don’t block the road, please. People live here.'],
      ['আজকালকার ছেলেমেয়েরা সারাদিন ফোনে মুখ গুঁজে থাকে।', 'Young people these days, faces buried in their phones all day.'],
      ['কেন যে লোকে এখানে আসে বুঝি না। দেখার কিছু নেই।', 'I don’t see why people come here. There’s nothing to see.'],
      ['আমাদের সময় এক টাকায় এক হালি ডিম পাওয়া যেত।', 'In our day you could get four eggs for one taka.'],
    ],
    grumpyBye: [
      ['আচ্ছা। এবার যান।', 'Right. Off you go now.'],
      ['যান যান, আপনাকে আটকে রাখব না।', 'Go on, go on, I won’t keep you.'],
      ['হুম। বিদায়।', 'Hm. Goodbye.'],
      ['সাবধানে যাবেন। আর গেটটা লাগিয়ে দেবেন।', 'Mind how you go. And shut the gate.'],
    ],
    elderChat: [
      ['আমার ছোটবেলায় এখানে শুধু ধানখেত ছিল।', 'When I was little, this was all rice fields.'],
      ['সারাজীবন এখানেই কাটালাম। আশি বছর! বিশ্বাস হয়?', 'I’ve spent my whole life here. Eighty years! Can you believe it?'],
      ['আমাদের সময় সবাই হেঁটে চলত। আপনিও হাঁটেন, ভালো!', 'In our day everybody walked. You walk too, good!'],
      ['নাতি-নাতনিরা এখন বিদেশে থাকে। প্রতি শুক্রবার ফোন করে।', 'The grandchildren live abroad now. They call every Friday.'],
      ['দিনকাল কত দ্রুত বদলায়। কিন্তু পুরনো গলিগুলো আগের মতোই আছে।', 'How fast the times change. But the old lanes are just as they were.'],
    ],
    chattyChat: [
      ['ওমা, মুসাফির! সব খুলে বলুন। না না, আগে আমি বলি।', 'Oh my, a traveller! Tell me everything. No, no, let me go first.'],
      ['আমার এক খালাতো ভাই একবার ঘুরতে গিয়েছিল। ফিরল দাড়ি আর বউ নিয়ে!', 'A cousin of mine went travelling once. He came back with a beard and a wife!'],
      ['বন্ধুরা বলে আমি সারাদিন কথা বলতে পারি। ভুল বলে না!', 'My friends say I could talk all day. They’re not wrong!'],
      ['খেয়েছেন? আপনাকে ক্ষুধার্ত লাগছে। আমার কাছে সবাইকেই ক্ষুধার্ত লাগে।', 'Have you eaten? You look hungry. Everybody looks hungry to me.'],
      ['একটা গোপন কথা বলি? এলাকার সবচেয়ে সুন্দর দৃশ্য নদীর ঘাট থেকে।', 'Shall I tell you a secret? The best view around is from the river landing.'],
    ],
    bye: [
      ['বিদায়! আপনার যাত্রা শুভ হোক।', 'Goodbye! Have a good journey.'],
      ['ভালো থাকবেন! বাকি যাত্রা উপভোগ করুন।', 'Stay well! Enjoy the rest of your trip.'],
      ['সাবধানে যাবেন!', 'Go safely!'],
      ['আবার আসবেন কিন্তু!', 'Do come again, now!'],
      ['আপনার সাথে কথা বলে ভালো লাগল। নিজের খেয়াল রাখবেন!', 'It was nice talking to you. Look after yourself!'],
      ['যান তাহলে! দেখার অনেক কিছু বাকি।', 'Off you go, then! There’s lots left to see.'],
    ],
  },
  countries: {
    // Each fact is a bare noun with no case ending, and no template ever attaches one to it.
    BGD: {
      dish: ['কাচ্চি বিরিয়ানি', 'kacchi biryani'],
      drink: ['বোরহানি', 'borhani'],
      festival: ['পহেলা বৈশাখ', 'Pohela Boishakh'],
      sport: ['ক্রিকেট', 'cricket'],
      wonder: ['সুন্দরবন', 'the Sundarbans'],
      pride: ['জামদানি শাড়ি', 'the jamdani sari'],
      proverb: ['যত গর্জে তত বর্ষে না', 'It never rains as hard as it thunders'],
    },
  },
};

export default BN;
