import type { Language } from '../phrases.ts';

const CS: Language = {
  locale: 'cs',
  name: 'Czech',
  join: ' ',
  compass: [
    'severně odtud', 'severovýchodně odtud', 'východně odtud', 'jihovýchodně odtud',
    'jižně odtud', 'jihozápadně odtud', 'západně odtud', 'severozápadně odtud',
  ],
  lines: {
    morning: [
      ['Dobré ráno!', 'Good morning!'],
      ['Dobré ráno! To je ale krásné ráno, že?', "Good morning! What a lovely morning, isn't it?"],
      ['Zdravím, dobré ráno!', 'Hello, good morning!'],
      ['Á, dobré ráno vám!', 'Ah, good morning to you!'],
    ],
    afternoon: [
      ['Dobré odpoledne!', 'Good afternoon!'],
      ['Dobrý den!', 'Hello!'],
      ['Zdravím!', 'Greetings!'],
      ['Á, dobrý den! Hezké odpoledne, co?', 'Ah, hello! Nice afternoon, eh?'],
    ],
    evening: [
      ['Dobrý večer!', 'Good evening!'],
      ['Dobrý večer! Hezký večer na procházku.', 'Good evening! Nice evening for a walk.'],
      ['Á, dobrý večer vám.', 'Ah, good evening to you.'],
      ['Zdravím! To už je večer? Ten čas letí.', 'Hello! Evening already? Time flies.'],
    ],
    night: [
      ['Dobrý večer! Už je pozdě, že?', "Good evening! It's late, isn't it?"],
      ['Jéžišmarjá, to je lekačka! Dobrý večer.', 'Goodness, what a fright! Good evening.'],
      ['Noční procházka? Dobrý večer!', 'A night walk? Good evening!'],
      ['Dobrý večer! Nebo už dobré ráno?', 'Good evening! Or is it good morning already?'],
    ],
    again: [
      ['Á, to jste zase vy! Dobrý den!', "Ah, it's you again! Hello!"],
      ['Zase se vidíme! To mě těší.', 'We meet again! That makes me happy.'],
      ['Ještě jednou dobrý den!', 'Hello once more!'],
      ['Už se známe! Pořád objevujete?', 'We know each other! Still exploring?'],
      ['A, vy! Našla se cesta?', 'Ah, you! Did you find your way?'],
    ],
    welcome: [
      ['Vítejte ve městě {town}!', 'Welcome to {town}!'],
      ['Tohle je {town}. Jste tu na návštěvě?', 'This is {town}. Are you visiting?'],
      ['Poprvé ve městě {town}?', 'First time in {town}?'],
      ['{town} vás vítá!', '{town} welcomes you!'],
      ['Dnes je ideální den na prohlídku. {town} čeká!', 'Today is a perfect day for a look round. {town} awaits!'],
      ['Co vás přivádí do města {town}?', 'What brings you to {town}?'],
    ],
    capitalHere: [
      ['{town} je hlavní město naší země.', '{town} is the capital of our country.'],
      ['Tady je hlavní město, víte? Všechno se děje tady.', 'This is the capital, you know. Everything happens here.'],
      ['Sedí tu vláda. Samí důležití lidé v oblecích.', 'The government sits here. Nothing but important people in suits.'],
      ['Hlavní město nikdy nespí a {town} je toho důkazem.', 'The capital never sleeps, and {town} is the proof.'],
    ],
    capitalThere: [
      ['Naše hlavní město je {capital}. Stojí za návštěvu.', "Our capital is {capital}. It's worth a visit."],
      ['Už znáte naše hlavní město? Je to {capital}.', 'Do you know our capital yet? It is {capital}.'],
      ['Ve městě {capital} si myslí, že řídí celou zemi. A mají pravdu.', "In {capital} they think they run the whole country. And they're right."],
      ['Město {capital} je větší, ale tady je to lepší.', '{capital} is bigger, but it is better here.'],
    ],
    big: [
      ['Tohle je velké město. Snadno se tu ztratíte!', "This is a big city. You'll get lost here easily!"],
      ['Tolik lidí! Tady můžete žít celý život a neznat všechny ulice.', 'So many people! You can live here all your life and not know every street.'],
      ['Ty zácpy, to je hrůza. Ale pořád se tu něco děje.', "The traffic jams are awful. But there's always something going on."],
      ['Velké město nikdy nespí. Většinou mě to baví.', 'A big city never sleeps. Mostly I enjoy it.'],
    ],
    middling: [
      ['Ani velké, ani malé. Akorát.', 'Not big, not small. Just right.'],
      ['Je tu všechno, a přitom se dá všude dojít pěšky.', 'Everything is here, and yet you can walk everywhere.'],
      ['Město {town} má tak akorát velikost. Za den dva ho projdete.', "{town} is just the right size. You'll walk it in a day or two."],
      ['Všichni si stěžují, že je tu nuda, a nikdo se neodstěhuje.', "Everybody complains it's dull here, and nobody moves away."],
    ],
    small: [
      ['Je to malé místo. Tady se všichni znají.', "It's a small place. Everybody knows everybody here."],
      ['Kýchnete na jednom konci a na druhém vám řeknou „na zdraví“.', 'Sneeze at one end and they say "bless you" at the other.'],
      ['Ve městě {town} se toho moc neděje, a tak je to dobře.', "Not much happens in {town}, and that's how it should be."],
      ['Jste tu největší událost týdne!', "You're the biggest event of the week here!"],
    ],
    coast: [
      ['Žijeme tady u vody. Ryby jsou výborné.', 'We live by the water here. The fish is excellent.'],
      ['Běžte se podívat na vodu. Každý den je jiná.', "Go and look at the water. It's different every day."],
      ['U vody je nejlíp. Kdo by potřeboval moře?', 'By the water is best. Who needs the sea?'],
      ['Rybáři vyrážejí brzy ráno a vracejí se s nejlepšími rybami.', 'The fishermen head out early and come back with the best fish.'],
    ],
    inland: [
      ['Moře je daleko, ale krajina je tu krásná.', 'The sea is far away, but the countryside here is beautiful.'],
      ['Pláž tu nemáme, ale podívejte se na ta pole.', "We don't have a beach, but look at those fields."],
      ['Moře? To je daleko. Nám stačí rybník.', "The sea? That's far off. A pond does us fine."],
      ['Tady je půda všechno. Dobrá hlína, dobří lidé.', 'Here the land is everything. Good soil, good people.'],
    ],
    high: [
      ['Jsme tu vysoko. Jděte pomalu, vzduch je řidší.', "We're high up. Go slowly, the air is thinner."],
      ['Na horách je nejlepší výhled.', 'In the mountains, the view is the best part.'],
      ['Tady nic není rovné. Budete mít nohy ze železa.', "Nothing is flat here. You'll have legs of iron."],
      ['Popadněte dech! Na hory si člověk musí zvyknout.', 'Catch your breath! The mountains take getting used to.'],
    ],
    snowy: [
      ['Sníh devět měsíců v roce. Zbylé tři si stěžujeme na bláto.', 'Snow nine months a year. The other three, we complain about the mud.'],
      ['Všechno je tu bílé. Chtělo by to lepší boty.', 'Everything is white here. You could do with better boots.'],
      ['Zima nám nevadí. Odhání turisty. Vás samozřejmě ne!', "The cold doesn't bother us. It keeps tourists away. Not you, of course!"],
      ['Když napadne čerstvý sníh, je takové ticho, že slyšíte vlastní myšlenky.', "When fresh snow falls, it's so quiet you can hear your own thoughts."],
    ],
    forest: [
      ['Lesy se tu táhnou na kilometry. Držte se cesty!', 'The woods go on for miles here. Stay on the path!'],
      ['Jděte se projít do lesa. Vyčistí vám hlavu.', 'Go for a walk in the woods. It clears your head.'],
      ['Na podzim chodí na houby celá vesnice.', 'In autumn the whole village goes mushroom picking.'],
      ['Stromy, stromy a zase stromy. Nikde jinde bydlet nechci.', "Trees, trees and more trees. I don't want to live anywhere else."],
    ],
    desert: [
      ['Tady je písek, kam oko dohlédne.', 'Here it is sand as far as the eye can see.'],
      ['Pijte hodně vody. Poušť neodpouští.', 'Drink plenty of water. The desert does not forgive.'],
      ['Noci v poušti jsou studené. Nikdo tomu nevěří.', 'Desert nights are cold. Nobody believes it.'],
      ['Počkejte na noc. Hvězd je tu jako máku.', 'Wait for the night. Stars here are as many as poppy seeds.'],
    ],
    plains: [
      ['Rovina, kam se podíváte. Bouřku vidíte hodinu předem.', 'Flat wherever you look. You see a storm an hour before it comes.'],
      ['Velké nebe a nic, co by zastavilo vítr.', 'A big sky and nothing to stop the wind.'],
      ['Samé pastviny. Pozor na stáda!', 'Pasture everywhere. Watch out for the herds!'],
      ['Tráva až k obzoru. Jako zelené moře.', 'Grass to the horizon. Like a green sea.'],
    ],
    tropical: [
      ['Tady roste všechno. Zapíchnete klacek a vyroste strom.', 'Everything grows here. Stick a twig in the ground and a tree comes up.'],
      ['Když tu prší, tak pořádně. A pak najednou přestane.', 'When it rains here, it really rains. And then it suddenly stops.'],
      ['Ochutnejte ovoce z trhu. Takové jinde nenajdete.', "Try the fruit from the market. You won't find anything like it elsewhere."],
      ['Zelená celý rok. Zima? Jaká zima?', 'Green all year. Winter? What winter?'],
    ],
    landmark: [
      ['{landmark} — to si nenechte ujít! Je to asi {km} km {dir}.', "{landmark}: don't miss it! It's about {km} km {dir}."],
      ['Stojí za to: {landmark}. Je to zhruba {km} km {dir}.', "Worth it: {landmark}. It's roughly {km} km {dir}."],
      ['Každý turista se ptá na jedno: {landmark}. Asi {km} km {dir}.', 'Every tourist asks about one thing: {landmark}. About {km} km {dir}.'],
      ['Zajímají vás památky? {landmark} je {km} km {dir}.', 'Interested in monuments? {landmark} is {km} km {dir}.'],
    ],
    landmarkNear: [
      ['{landmark} je úplně blízko. Nemůžete to minout!', "{landmark} is really close. You can't miss it!"],
      ['{landmark} je hned za rohem.', '{landmark} is just round the corner.'],
      ['Denně se dívám na tohle: {landmark}. Pořád mi to bere dech.', 'Every day I look at it: {landmark}. It still takes my breath away.'],
      ['Běžte se podívat, {landmark} je hned tady. Nejlíp ráno, než přijdou davy.', 'Go and see, {landmark} is right here. Best in the morning, before the crowds.'],
    ],
    plane: [
      ['{dir} stojí na poli malé letadlo. Umíte létat?', '{dir} there is a little plane in a field. Can you fly?'],
      ['Někdo nechal letadlo na poli, {dir}. Proletíte se?', 'Somebody left a plane in a field, {dir}. Fancy a flight?'],
      ['Umíte pilotovat? Letadlo čeká {dir}.', 'Can you fly a plane? One is waiting {dir}.'],
      ['Chcete vidět všechno shora? Letadlo stojí {dir}.', 'Want to see it all from above? There is a plane {dir}.'],
    ],
    balloon: [
      ['Na poli {dir} je horkovzdušný balon! Představte si ten výhled.', "There's a hot-air balloon in the field {dir}! Imagine the view."],
      ['Let balonem? Jeden je {dir}.', "A balloon flight? There's one {dir}."],
      ['Z louky {dir} startuje balon. Kouzelné!', 'A balloon goes up from the meadow {dir}. Magical!'],
      ['Balon stojí {dir}. Láká mě to, ale strašně se bojím výšek!', "The balloon is {dir}. I'm tempted, but I'm terribly scared of heights!"],
    ],
    boat: [
      ['U vody {dir} je loďka, jestli se chcete projet.', "There's a boat by the water {dir}, if you want to go out."],
      ['Loďka čeká {dir}. Jen ji pak vraťte!', 'A boat is waiting {dir}. Just bring it back afterwards!'],
      ['Loď je uvázaná {dir}. Odsud doplujete kamkoli.', 'A boat is tied up {dir}. From here you can sail anywhere.'],
      ['Vezměte loďku {dir} a podívejte se na břeh z vody.', 'Take the boat {dir} and see the shore from the water.'],
    ],
    hot: [
      ['Dnes je horko! Najděte si stín.', "It's hot today! Find some shade."],
      ['Uf, to je vedro! Napijte se vody.', 'Phew, what heat! Have some water.'],
      ['Takové horko, že se nedá nic dělat. Jen sedět ve stínu.', "So hot you can't do anything. Just sit in the shade."],
      ['V tomhle vedru zůstávají doma i psi.', 'In this heat even the dogs stay at home.'],
      ['Horko, co? A to je pro nás ještě chladný den!', 'Hot, eh? And for us this is still a cool day!'],
    ],
    cold: [
      ['Brr, dnes je zima! Oblečte se teple.', "Brr, it's cold today! Dress warmly."],
      ['To je kosa! Kde máte rukavice?', "It's freezing! Where are your gloves?"],
      ['Taková zima, že necítím nos.', "So cold I can't feel my nose."],
      ['Zima? Počkejte, až začne foukat.', 'Cold? Wait till the wind starts.'],
      ['Dejte si něco teplého. Pomáhá to.', 'Have something hot. It helps.'],
    ],
    mild: [
      ['To je dnes krásné počasí.', 'What lovely weather today.'],
      ['Ani horko, ani zima. Ideální den, že?', "Not hot, not cold. A perfect day, isn't it?"],
      ['V takový den se chce být venku.', 'On a day like this you want to be outside.'],
      ['Krásně je! Ať to vydrží.', "It's lovely out! May it last."],
      ['Kvůli takovým dnům tu žijeme.', 'Days like this are why we live here.'],
    ],
    late: [
      ['Už je pozdě. V noci jsou ulice tiché.', "It's late. The streets are quiet at night."],
      ['V tuhle hodinu jsou venku jen kočky. A my!', 'At this hour only the cats are out. And us!'],
      ['Tou dobou už člověk patří do postele. Co vy tady?', 'At this hour a person belongs in bed. What are you doing here?'],
      ['Podívejte na hvězdy! Odsud je vidět nejlíp.', 'Look at the stars! You see them best from here.'],
    ],
    early: [
      ['Vy jste ale ranní ptáče!', 'What an early bird you are!'],
      ['Pekárna právě otevřela. Jděte po vůni!', 'The bakery has just opened. Follow the smell!'],
      ['Město ještě spí a vy už jste na nohou!', "The town's still asleep and you're already up!"],
      ['Ráno je tu nejkrásněji, než začne ruch.', 'Mornings are the loveliest here, before the bustle begins.'],
    ],
    country: [
      ['{country} je krásná země. Užijte si ji!', '{country} is a beautiful country. Enjoy it!'],
      ['Jak se vám tu líbí? {country} umí překvapit.', 'How do you like it here? {country} knows how to surprise you.'],
      ['Procestujte, co se dá. {country} má v každém koutě něco jiného.', 'Travel all you can. {country} has something different in every corner.'],
      ['{country} je malá země s velkým srdcem.', '{country} is a small country with a big heart.'],
    ],
    dish: [
      ['{dish} — to musíte ochutnat!', '{dish}: you have to taste it!'],
      ['{dish}? To ještě neznáte? To se musí napravit!', "{dish}? You don't know it yet? That must be put right!"],
      ['Nejlepší na světě? {dish} od mojí mámy.', "The best in the world? My mum's {dish}."],
      ['Máte hlad? Dejte si tohle: {dish}. Nebudete litovat.', "Hungry? Have this: {dish}. You won't regret it."],
    ],
    drink: [
      ['{drink} — to si dejte, než odjedete.', '{drink}: have some before you leave.'],
      ['Na konci dne není nic lepšího než {drink}.', 'At the end of the day there is nothing better than {drink}.'],
      ['{drink}, to se tu pije nejvíc.', "{drink}: that's what we drink most here."],
      ['Chcete vypadat jako místní? Objednejte si tohle: {drink}.', 'Want to look like a local? Order this: {drink}.'],
    ],
    festival: [
      ['{festival}, to je nejlepší doba sem přijet.', '{festival}: that is the best time to come here.'],
      ['Nejkrásnější čas roku? {festival}. Slaví celá země.', 'The loveliest time of the year? {festival}. The whole country celebrates.'],
      ['{festival} — to musíte jednou zažít!', '{festival}: you have to experience it once!'],
      ['Celý rok se těším na jedno: {festival}.', 'All year I look forward to one thing: {festival}.'],
    ],
    sport: [
      ['Tady se žije jedním: {sport}.', 'Here we live for one thing: {sport}.'],
      ['Když je zápas, celé město řeší jen jedno: {sport}.', 'When there is a match, the whole town talks about one thing: {sport}.'],
      ['{sport}, to je u nás skoro náboženství.', '{sport}: here it is almost a religion.'],
      ['Celá rodina žije tímhle: {sport}. Babička jen křičí na televizi.', 'The whole family lives for it: {sport}. Grandma just shouts at the telly.'],
    ],
    wonder: [
      ['{wonder} — jestli máte čas, musíte to vidět.', '{wonder}: if you have time, you must see it.'],
      ['{wonder}, to nikde jinde na světě nenajdete.', "{wonder}: you won't find that anywhere else in the world."],
      ['Každý by to měl jednou vidět: {wonder}.', 'Everyone should see it once: {wonder}.'],
      ['Říkám vám: {wonder}, to je zážitek na celý život.', "I'm telling you: {wonder} is an experience for a lifetime."],
    ],
    pride: [
      ['Naše pýcha? {pride}.', 'Our pride? {pride}.'],
      ['Víte, na co jsme tu hrdí? {pride}.', 'Do you know what we are proud of here? {pride}.'],
      ['{pride}, to je náš poklad.', '{pride}: that is our treasure.'],
      ['Zeptejte se kohokoli na tohle: {pride}. Bude mluvit hodiny.', "Ask anyone about this: {pride}. They'll talk for hours."],
    ],
    proverb: [
      ['Jak se u nás říká: „{proverb}“', 'As we say here: “{proverb}”'],
      ['Babička vždycky říkala: „{proverb}“', 'Grandma always said: “{proverb}”'],
      ['Máme takové přísloví: „{proverb}“', 'We have a proverb: “{proverb}”'],
      ['Znáte to rčení? „{proverb}“', 'Do you know the saying? “{proverb}”'],
    ],
    chat: [
      ['Odkud jste? Nejste odsud.', "Where are you from? You're not from here."],
      ['Nespěchejte a rozhlédněte se. Je tu co vidět.', "Take your time and look around. There's plenty to see."],
      ['Cestujete na vlastní pěst? To je odvaha!', "Travelling on your own? That's brave!"],
      ['Vypadáte, že máte za sebou pořádný kus cesty.', 'You look like you have come a long way.'],
      ['Když se ztratíte, klidně se zeptejte. Lidi jsou tu přátelští.', 'If you get lost, just ask. People here are friendly.'],
      ['Kde se vám zatím líbilo nejvíc?', 'Where have you liked it most so far?'],
      ['Cestování je krása. Jednou se taky vydám do světa.', 'Travelling is wonderful. One day I will set off into the world too.'],
      ['Máte mapu? Mapa je základ.', 'Have you got a map? A map is the basics.'],
    ],
    childGreet: [
      ['Ahoj!', 'Hi!'],
      ['Ahoj! A kdo jsi ty?', 'Hi! And who are you?'],
      ['Čau! Kolik ti je let?', 'Hiya! How old are you?'],
      ['Ahoj, ahoj!', 'Hi, hi!'],
    ],
    childChat: [
      ['Umím strašně rychle běhat! Chceš to vidět? Možná potom.', 'I can run super fast! Want to see? Maybe later.'],
      ['Kamarád říká, že turisti jsou bohatí. Je to pravda?', 'My friend says tourists are rich. Is it true?'],
      ['Včera mi vypadl zub! Koukej! Aha, není to vidět.', "My tooth fell out yesterday! Look! Oh, you can't see it."],
      ['Mamka říká, že se nemá mluvit s cizími. Ale ty vypadáš mile.', "Mum says you mustn't talk to strangers. But you look nice."],
      ['Máš psa? Já chci psa!', 'Do you have a dog? I want a dog!'],
      ['Až vyrostu, poletím letadlem kolem celého světa!', "When I grow up, I'll fly a plane round the whole world!"],
      ['Znáš nějakou hru? Já jich znám hromadu!', 'Do you know any games? I know heaps!'],
    ],
    childBye: [
      ['Pa pa!', 'Bye bye!'],
      ['Čau! Přijď si zase hrát!', 'Bye! Come and play again!'],
      ['Musím jít, mamka volá!', 'I have to go, mum is calling!'],
      ['Ahoj, ahoj, zatím!', 'Bye, bye, see you!'],
    ],
    grumpyGreet: [
      ['Hm. Co chcete?', 'Hm. What do you want?'],
      ['No? Co je?', "Well? What is it?"],
      ['Aha. Zase turisti.', 'Right. Tourists again.'],
      ['Hmpf. No, dobrý den.', 'Hmph. Well, hello.'],
    ],
    grumpyChat: [
      ['Dřív tu bylo líp, než sem začali jezdit všichni.', 'It was better here before everybody started coming.'],
      ['Všechno stojí dvakrát tolik co dřív.', 'Everything costs twice what it used to.'],
      ['Nestůjte na chodníku, prosím. Lidi tu bydlí.', "Don't stand in the pavement, please. People live here."],
      ['Ta dnešní mládež. Pořád jen ty mobily.', 'Young people today. Always those phones.'],
      ['Nevím, proč sem kdo jezdí. Nic tu není.', "I don't know why anyone comes here. There's nothing here."],
    ],
    grumpyBye: [
      ['No tak jděte.', 'Off you go, then.'],
      ['Nebudu vás zdržovat.', "I won't keep you."],
      ['Hm. Na shledanou.', 'Hm. Goodbye.'],
      ['Dávejte pozor. A zavřete branku.', 'Mind how you go. And shut the gate.'],
    ],
    elderChat: [
      ['Za mého mládí tu byla samá pole.', 'When I was young, this was all fields.'],
      ['Bydlím tu celý život. Osmdesát let! Věříte tomu?', "I've lived here all my life. Eighty years! Can you believe it?"],
      ['Za nás se chodilo všude pěšky. Vy taky chodíte. Dobře!', 'In our day we walked everywhere. You walk too. Good!'],
      ['Vnoučata teď žijí v cizině. Volají každou neděli.', 'My grandchildren live abroad now. They call every Sunday.'],
      ['Všechno se mění tak rychle. Jen staré uličky zůstávají stejné.', 'Everything changes so fast. Only the old lanes stay the same.'],
    ],
    chattyChat: [
      ['Cestovatelé, to je moje! Povídejte všechno. Ne, počkejte, nejdřív já!', 'Travellers, my favourite! Tell me everything. No, wait, me first!'],
      ['Bratranec jednou vyrazil na cesty. Vrátil se s plnovousem a s manželkou!', 'My cousin went travelling once. He came back with a full beard and a wife!'],
      ['Kamarádi říkají, že dokážu mluvit celý den. Mají pravdu!', "My friends say I can talk all day. They're right!"],
      ['Nemáte hlad? Mně všichni připadají hladoví!', 'Not hungry? Everybody looks hungry to me!'],
      ['Prozradím vám tajemství: nejhezčí výhled je z kopce za kostelem.', "I'll tell you a secret: the best view is from the hill behind the church."],
    ],
    bye: [
      ['Na shledanou! Šťastnou cestu.', 'Goodbye! Have a good trip.'],
      ['Mějte se hezky! Užijte si zbytek cesty.', 'Take care! Enjoy the rest of your journey.'],
      ['Ať se daří!', 'All the best!'],
      ['Na shledanou! Zase přijeďte.', 'Goodbye! Come again.'],
      ['Bylo mi potěšením. Opatrujte se!', 'It was a pleasure. Look after yourself!'],
      ['Tak šťastnou cestu! Je tu toho ještě tolik k vidění.', "Safe travels, then! There's still so much to see."],
    ],
  },
  countries: {
    // Every fact in the nominative: the templates set it off by a comma, a dash or a colon, or after "než".
    CZE: {
      dish: ['svíčková', 'svíčková, beef in cream sauce'],
      drink: ['plzeňské pivo', 'Pilsner beer'],
      festival: ['masopust', 'Masopust, the carnival'],
      sport: ['hokej', 'ice hockey'],
      wonder: ['Český ráj', 'Bohemian Paradise'],
      pride: ['české sklo', 'Bohemian glass'],
      proverb: ['Bez práce nejsou koláče', 'No work, no cakes'],
    },
  },
};

export default CS;
