import type { Language } from '../phrases.ts';

const DE: Language = {
  locale: 'de',
  name: 'German',
  join: ' ',
  compass: [
    'nördlich von hier', 'nordöstlich von hier', 'östlich von hier', 'südöstlich von hier',
    'südlich von hier', 'südwestlich von hier', 'westlich von hier', 'nordwestlich von hier',
  ],
  lines: {
    morning: [
      ['Guten Morgen!', 'Good morning!'],
      ['Morgen! Schöner Start in den Tag, was?', 'Morning! Nice start to the day, eh?'],
      ['Oh, hallo! Guten Morgen.', 'Oh, hello! Good morning.'],
      ['Na, auch schon wach? Guten Morgen!', 'Well, up already too? Good morning!'],
    ],
    afternoon: [
      ['Guten Tag!', 'Good afternoon!'],
      ['Hallo!', 'Hello!'],
      ['Tag! Schöner Nachmittag, oder?', 'Afternoon! Lovely afternoon, isn’t it?'],
      ['Ach, hallo! Schönen Nachmittag noch!', 'Oh, hello! Have a nice afternoon!'],
    ],
    evening: [
      ['Guten Abend!', 'Good evening!'],
      ['’n Abend!', 'Evening!'],
      ['Hallo! Schöner Abend für einen Spaziergang.', 'Hello! Nice evening for a walk.'],
      ['Na, guten Abend!', 'Well, good evening!'],
    ],
    night: [
      ['Guten Abend! Ganz schön spät, oder?', 'Good evening! Pretty late, isn’t it?'],
      ['Huch! Haben Sie mich erschreckt. Hallo!', 'Whoa! You gave me a fright. Hello!'],
      ['Hallo! Noch ein kleiner Nachtspaziergang?', 'Hello! Out for a little night walk?'],
      ['’n Abend! Oder ist es schon Morgen?', 'Evening! Or is it morning already?'],
    ],
    again: [
      ['Ach, Sie schon wieder! Hallo!', 'Oh, you again! Hello!'],
      ['Da sind Sie ja wieder! Schön.', 'There you are again! Nice.'],
      ['Hallo nochmal!', 'Hello again!'],
      ['Wir kennen uns doch! Immer noch unterwegs?', 'We’ve met before! Still on the road?'],
      ['Ah, Sie sind’s! Haben Sie den Weg gefunden?', 'Ah, it’s you! Did you find your way?'],
    ],
    welcome: [
      ['Willkommen in {town}!', 'Welcome to {town}!'],
      ['Das hier ist {town}. Sind Sie zu Besuch?', 'This is {town}. Are you visiting?'],
      ['Zum ersten Mal in {town}?', 'First time in {town}?'],
      ['Sie haben sich einen guten Tag für {town} ausgesucht.', 'You’ve picked a good day for {town}.'],
      ['Herzlich willkommen! Schön, dass Sie in {town} vorbeischauen.', 'A warm welcome! Nice of you to drop by {town}.'],
      ['Und, was führt Sie nach {town}?', 'So, what brings you to {town}?'],
    ],
    capitalHere: [
      ['{town} ist die Hauptstadt unseres Landes.', '{town} is the capital of our country.'],
      ['Das hier ist die Hauptstadt, wissen Sie. In {town} passiert alles.', 'This is the capital, you know. Everything happens in {town}.'],
      ['Hier in {town} sitzt die Regierung. Lauter wichtige Leute in Anzügen.', 'The government sits here in {town}. Lots of important people in suits.'],
      ['Als Hauptstadt schläft {town} eigentlich nie.', 'Being the capital, {town} never really sleeps.'],
    ],
    capitalThere: [
      ['Unsere Hauptstadt ist {capital}. Sie ist einen Besuch wert.', 'Our capital is {capital}. It’s worth a visit.'],
      ['Waren Sie schon in {capital}? Das ist unsere Hauptstadt.', 'Have you been to {capital}? That’s our capital.'],
      ['Die in {capital} glauben, sie regieren das Land. Na ja, stimmt ja auch.', 'The people in {capital} think they run the country. Well, they do.'],
      ['{capital} ist größer, aber ich wohne lieber hier.', '{capital} is bigger, but I’d rather live here.'],
    ],
    big: [
      ['Das ist eine große Stadt. Hier verläuft man sich leicht!', 'This is a big city. It’s easy to get lost here!'],
      ['So viele Leute! Man wohnt hier ein Leben lang und kennt nicht jede Straße.', 'So many people! You live here a lifetime and still don’t know every street.'],
      ['Der Verkehr hier, ehrlich. Aber es ist immer was los.', 'The traffic here, honestly. But there’s always something going on.'],
      ['Eine Großstadt wie diese steht nie still. Ich mag das. Meistens.', 'A big city like this never stands still. I like it. Mostly.'],
    ],
    middling: [
      ['Nicht groß, nicht klein. Genau richtig.', 'Not big, not small. Just right.'],
      ['Groß genug, dass es alles gibt, klein genug für zu Fuß.', 'Big enough to have everything, small enough to do on foot.'],
      ['{town} hat eine schöne Größe. In ein, zwei Tagen haben Sie alles gesehen.', '{town} is a nice size. You’ll have seen it all in a day or two.'],
      ['Alle sagen, hier ist nichts los. Und keiner zieht weg.', 'Everybody says nothing happens here. And nobody moves away.'],
    ],
    small: [
      ['Es ist ein kleiner Ort. Hier kennt jeder jeden.', 'It’s a small place. Everybody knows everybody here.'],
      ['Kleiner Ort. Wenn Sie niesen, sagt die ganze Straße Gesundheit.', 'Small town. If you sneeze, the whole street says bless you.'],
      ['In {town} passiert nicht viel, und das ist uns ganz recht.', 'Not much happens in {town}, and that suits us fine.'],
      ['Sie sind die größte Aufregung hier seit Wochen!', 'You’re the biggest excitement around here in weeks!'],
    ],
    coast: [
      ['Wir leben hier am Wasser. Der Fisch ist sehr gut.', 'We live by the water here. The fish is very good.'],
      ['Schauen Sie sich das Wasser an. Jeden Tag sieht es anders aus.', 'Go and look at the water. It looks different every day.'],
      ['Riechen Sie das? Frische Luft vom Wasser. Davon kriegt man nie genug.', 'Smell that? Fresh air off the water. You never get enough of it.'],
      ['Die Boote fahren früh raus und bringen den besten Fisch mit.', 'The boats go out early and bring back the best fish.'],
    ],
    inland: [
      ['Das Meer ist weit weg, aber die Landschaft hier ist wunderschön.', 'The sea is far away, but the countryside here is beautiful.'],
      ['Einen Strand gibt’s hier leider nicht. Aber schauen Sie sich die Felder an.', 'No beach here, I’m afraid. But look at those fields.'],
      ['Das Meer? Hab ich ehrlich gesagt ewig nicht gesehen.', 'The sea? To be honest, I haven’t seen it in ages.'],
      ['Hier draußen ist das Land alles. Guter Boden, gute Leute.', 'Out here the land is everything. Good soil, good people.'],
    ],
    high: [
      ['Wir sind hier ganz schön weit oben. Langsam, die Luft ist dünn.', 'We’re pretty high up here. Take it slowly, the air is thin.'],
      ['Hier oben in den Bergen ist die Aussicht das Beste, was wir haben.', 'Up here in the mountains, the view is the best thing we have.'],
      ['Wer hier oben wohnt, kriegt starke Waden. Nichts ist flach.', 'Live up here and you get strong calves. Nothing is flat.'],
      ['Achten Sie auf Ihren Atem! An die Höhe muss man sich erst gewöhnen.', 'Mind your breath! The altitude takes some getting used to.'],
    ],
    snowy: [
      ['Neun Monate Schnee im Jahr. Die anderen drei schimpfen wir über den Matsch.', 'Snow nine months a year. The other three, we grumble about the slush.'],
      ['Hier ist alles weiß. Sie brauchen bessere Schuhe als die da.', 'Everything is white here. You need better shoes than those.'],
      ['Die Kälte stört uns nicht. Sie hält die Touristen fern. Anwesende ausgenommen!', 'The cold doesn’t bother us. It keeps the tourists away. Present company excepted!'],
      ['Wenn frischer Schnee liegt, ist es so still, dass man sich denken hört.', 'When the snow is fresh, it’s so quiet you can hear yourself think.'],
    ],
    forest: [
      ['Der Wald hier geht tagelang weiter. Bleiben Sie auf dem Weg!', 'The forest here goes on for days. Stay on the path!'],
      ['Gehen Sie im Wald spazieren. Das macht den Kopf frei.', 'Go for a walk in the woods. It clears the head.'],
      ['Jeden Herbst sammeln wir da draußen Pilze und Beeren.', 'Every autumn we gather mushrooms and berries out there.'],
      ['Bäume, Bäume und noch mehr Bäume. Ich würde nirgends anders wohnen wollen.', 'Trees, trees and more trees. I wouldn’t want to live anywhere else.'],
    ],
    desert: [
      ['Hier draußen gibt es Sand, so weit das Auge reicht.', 'Out here there is sand as far as the eye can see.'],
      ['Trinken Sie viel Wasser. Die Wüste verzeiht nichts.', 'Drink plenty of water. The desert forgives nothing.'],
      ['Die Nächte in der Wüste sind kalt, wissen Sie. Das glaubt einem keiner.', 'Desert nights are cold, you know. Nobody ever believes it.'],
      ['Warten Sie heute Nacht auf die Sterne. Hier draußen sind es Millionen.', 'Wait for the stars tonight. Out here there are millions.'],
    ],
    plains: [
      ['Hier ist alles flach. Das Wetter sieht man einen Tag vorher kommen.', 'It’s all flat here. You see the weather coming a day ahead.'],
      ['Viel Himmel hier draußen. Nichts hält den Wind auf.', 'Lots of sky out here. Nothing stops the wind.'],
      ['Gutes Weideland, alles hier. Achten Sie auf die Herden.', 'Good grazing land, all of it. Watch out for the herds.'],
      ['Das Gras hört einfach nicht auf. Wie ein grünes Meer.', 'The grass just never ends. Like a green sea.'],
    ],
    tropical: [
      ['Hier wächst alles. Stecken Sie einen Stock in die Erde, und es wird ein Baum.', 'Everything grows here. Stick a twig in the ground and it becomes a tree.'],
      ['Wenn hier der Regen kommt, dann richtig. Und plötzlich hört er auf.', 'When the rain comes here, it really comes. And then it suddenly stops.'],
      ['Probieren Sie das Obst vom Markt. So was haben Sie noch nie gegessen.', 'Try the fruit from the market. You’ve never eaten anything like it.'],
      ['Hier ist das ganze Jahr alles grün. Winter? Was ist Winter?', 'Everything is green all year here. Winter? What’s winter?'],
    ],
    landmark: [
      ['Nicht verpassen: {landmark}! Etwa {km} km {dir}.', 'Don’t miss it: {landmark}! About {km} km {dir}.'],
      ['{landmark} liegt etwa {km} km {dir}. Jeder Schritt lohnt sich!', '{landmark} is about {km} km {dir}. Worth every step!'],
      ['Da wollen alle hin: {landmark}, etwa {km} km {dir}.', 'Everybody wants to go there: {landmark}, about {km} km {dir}.'],
      ['Mögen Sie alte Sachen? {landmark} ist {km} km {dir}. Da kommen Leute von überall.', 'Like old things? {landmark} is {km} km {dir}. People come from all over.'],
    ],
    landmarkNear: [
      ['{landmark} ist ganz in der Nähe. Nicht zu verfehlen!', '{landmark} is very close. You can’t miss it!'],
      ['Schon gesehen? {landmark}, gleich um die Ecke.', 'Seen it yet? {landmark}, just round the corner.'],
      ['Wir sehen es jeden Tag, und es haut mich immer noch um: {landmark}.', 'We see it every day and it still blows me away: {landmark}.'],
      ['{landmark} ist gleich hier. Gehen Sie früh hin, vor den Massen.', '{landmark} is right here. Go early, before the crowds.'],
    ],
    plane: [
      ['Auf einem Feld {dir} steht ein kleines Flugzeug. Können Sie fliegen?', 'There’s a little plane in a field {dir}. Can you fly?'],
      ['Da hat jemand ein Flugzeug auf dem Feld {dir} stehen lassen. Lust auf einen Flug?', 'Somebody left a plane in the field {dir}. Fancy a flight?'],
      ['Können Sie fliegen? {dir} wartet ein Flugzeug.', 'Can you fly? {dir} a plane is waiting.'],
      ['Alles von oben sehen? Da steht ein Flugzeug, {dir}.', 'See it all from above? There’s a plane, {dir}.'],
    ],
    balloon: [
      ['Auf einem Feld {dir} steht ein Heißluftballon! Stellen Sie sich die Aussicht vor.', 'There’s a hot-air balloon in a field {dir}! Imagine the view.'],
      ['Sind Sie schon mal Ballon gefahren? {dir} steht einer.', 'Have you ever been up in a balloon? There’s one {dir}.'],
      ['Vom Feld {dir} steigt ein Ballon auf. Einfach zauberhaft.', 'A balloon goes up from the field {dir}. Simply magical.'],
      ['Den Ballon {dir} wollte ich immer mal ausprobieren. Ich trau mich nur nicht!', 'I’ve always wanted to try the balloon {dir}. I just don’t dare!'],
    ],
    boat: [
      ['Am Wasser {dir} liegt ein Boot, falls Sie rausfahren wollen.', 'There’s a boat by the water {dir}, if you want to go out.'],
      ['Mögen Sie das Wasser? {dir} liegt ein Boot. Aber bringen Sie es zurück!', 'Like the water? {dir} there’s a boat. But bring it back!'],
      ['Ein Boot ist {dir} festgemacht. Damit kommen Sie überall hin.', 'A boat is moored {dir}. You could go anywhere in it.'],
      ['Nehmen Sie das Boot {dir} und schauen Sie sich das Ufer vom Wasser aus an.', 'Take the boat {dir} and see the shore from the water.'],
    ],
    hot: [
      ['Heute ist es heiß! Suchen Sie sich etwas Schatten.', 'It’s hot today! Find yourself some shade.'],
      ['Puh, diese Hitze! Trinken Sie was, Sie sehen aus, als bräuchten Sie es.', 'Phew, this heat! Have a drink, you look like you need it.'],
      ['Viel zu heiß, um irgendwas zu machen. Außer im Schatten sitzen.', 'Far too hot to do anything. Except sit in the shade.'],
      ['Bei der Hitze bleiben sogar die Hunde drinnen.', 'In this heat even the dogs stay indoors.'],
      ['Heiß heute, was? Ich schwitze schon beim Reden.', 'Hot today, eh? I’m sweating just talking.'],
    ],
    cold: [
      ['Brr, heute ist es kalt! Ziehen Sie sich warm an.', 'Brr, it’s cold today! Wrap up warm.'],
      ['Eiskalt! Wo haben Sie denn Ihre Handschuhe?', 'Freezing! Where are your gloves?'],
      ['So kalt, dass meine Nase nicht mehr mitmacht.', 'So cold my nose has given up.'],
      ['Kalt genug? Warten Sie, bis der Wind aufdreht.', 'Cold enough? Wait till the wind picks up.'],
      ['Holen Sie sich was Heißes zu trinken. Das hilft.', 'Get yourself something hot to drink. It helps.'],
    ],
    mild: [
      ['Was für ein schönes Wetter heute.', 'What lovely weather today.'],
      ['Nicht zu warm, nicht zu kalt. Ein perfekter Tag, oder?', 'Not too warm, not too cold. A perfect day, isn’t it?'],
      ['An so einem Tag will man einfach draußen sein.', 'On a day like this you just want to be outside.'],
      ['Herrliches Wetter! Hoffentlich bleibt es so.', 'Glorious weather! Let’s hope it stays like this.'],
      ['Wegen solcher Tage wohnen wir hier.', 'Days like this are why we live here.'],
    ],
    late: [
      ['Es ist spät. Nachts sind die Straßen ruhig.', 'It’s late. The streets are quiet at night.'],
      ['Um diese Zeit sind nur noch die Katzen unterwegs. Und wir!', 'At this hour only the cats are out. And us!'],
      ['Eigentlich gehöre ich längst ins Bett. Und Sie?', 'I really should have been in bed ages ago. And you?'],
      ['Schauen Sie mal, die Sterne! Von hier sieht man sie am besten.', 'Look, the stars! You see them best from here.'],
    ],
    early: [
      ['Sie sind aber früh auf! Die schönste Zeit des Tages.', 'You’re up early! The best time of the day.'],
      ['Der Bäcker hat gerade aufgemacht. Immer der Nase nach!', 'The bakery has just opened. Follow your nose!'],
      ['So früh schon unterwegs? Die Stadt schläft ja noch.', 'Out so early? The town is still asleep.'],
      ['Ich liebe den Morgen hier, bevor der Lärm losgeht.', 'I love the morning here, before the noise starts.'],
    ],
    country: [
      ['{country} – ein wunderschönes Land. Genießen Sie es!', '{country}: a beautiful country. Enjoy it!'],
      ['Ich sage ja immer: {country} – klein auf der Karte, groß im Herzen.', 'I always say: {country}, small on the map, big in the heart.'],
      ['Reisen Sie ruhig kreuz und quer. {country}: Jede Ecke ist anders.', 'Travel all over, go on. {country}: every corner is different.'],
      ['Das schönste Land der Welt: {country}! Na gut, ich bin befangen.', 'The most beautiful country in the world: {country}! All right, I’m biased.'],
      ['Man sagt ja: {country} – einmal gesehen, nie vergessen.', 'As they say: {country}, seen once, never forgotten.'],
    ],
    dish: [
      ['{dish} – das müssen Sie hier unbedingt probieren!', '{dish}: you really must try it here!'],
      ['Mein Tipp, wenn Sie Hunger haben: {dish}.', 'My tip if you’re hungry: {dish}.'],
      ['Nirgends so gut wie bei meiner Mutter: {dish}.', 'Nowhere as good as at my mother’s: {dish}.'],
      ['Was man hier essen muss? {dish}, ganz klar.', 'What you have to eat here? {dish}, obviously.'],
    ],
    drink: [
      ['{drink} – das trinkt man hier. Probieren Sie mal!', '{drink}: that’s what we drink here. Give it a try!'],
      ['Nach einem langen Tag gibt es nichts Besseres: {drink}.', 'After a long day there’s nothing better: {drink}.'],
      ['Ein Muss vor der Abreise: {drink}.', 'A must before you leave: {drink}.'],
      ['Bestellen Sie wie die Leute hier: {drink}. Dann mögen Sie alle.', 'Order like the locals: {drink}. Then everyone will like you.'],
    ],
    festival: [
      ['Die schönste Zeit im Jahr? {festival}! Kommen Sie dann wieder.', 'The best time of the year? {festival}! Come back then.'],
      ['Kennen Sie das schon: {festival}? Das würde Ihnen gefallen.', 'Do you know it yet: {festival}? You’d love it.'],
      ['Ich zähle jedes Jahr die Tage bis dahin: {festival}.', 'Every year I count the days until it: {festival}.'],
      ['Dann ist hier alles auf den Beinen: {festival}. Herrlich!', 'Then everybody here is out and about: {festival}. Wonderful!'],
    ],
    sport: [
      ['Hier dreht sich alles um eins: {sport}.', 'Here everything revolves around one thing: {sport}.'],
      ['{sport} – da sind wir hier ganz verrückt danach.', '{sport}: we’re completely crazy about it here.'],
      ['Am Wochenende gibt’s hier nur ein Thema: {sport}.', 'At the weekend there’s only one topic here: {sport}.'],
      ['Bei uns in der Familie heißt es immer: {sport}! Und Oma schreit vom Rand.', 'In our family it’s always: {sport}! And Grandma shouts from the side.'],
    ],
    wonder: [
      ['Wenn Sie Zeit haben: {wonder}. Unvergesslich!', 'If you have time: {wonder}. Unforgettable!'],
      ['{wonder} – das muss man einmal im Leben gesehen haben.', '{wonder}: you have to see it once in your life.'],
      ['So etwas gibt es nirgends sonst: {wonder}.', 'There’s nothing like it anywhere else: {wonder}.'],
      ['Als Kind war ich einmal dort: {wonder}. Davon träume ich heute noch.', 'I went there once as a child: {wonder}. I still dream about it.'],
    ],
    pride: [
      ['Worauf wir hier stolz sind? {pride}.', 'What we’re proud of here? {pride}.'],
      ['{pride} – darauf sind wir hier mächtig stolz.', '{pride}: we’re mighty proud of that here.'],
      ['Ein Stichwort, und hier redet jeder stundenlang: {pride}.', 'One word, and anyone here will talk for hours: {pride}.'],
      ['Das sind wir, das macht uns aus: {pride}.', 'That’s us, that’s what we are: {pride}.'],
    ],
    proverb: [
      ['Wie man hier so sagt: „{proverb}“', 'As we say here: “{proverb}”'],
      ['Meine Oma hat immer gesagt: „{proverb}“', 'My grandma always said: “{proverb}”'],
      ['Bei uns heißt es: „{proverb}“', 'Round here they say: “{proverb}”'],
      ['Kennen Sie den Spruch? „{proverb}“', 'Do you know the saying? “{proverb}”'],
    ],
    chat: [
      ['Woher kommen Sie? Sie sind nicht von hier, oder?', 'Where are you from? You’re not from here, are you?'],
      ['Lassen Sie sich Zeit und schauen Sie sich um. Es gibt viel zu sehen.', 'Take your time and look around. There’s a lot to see.'],
      ['Sind Sie allein unterwegs? Mutig!', 'Travelling alone? Brave!'],
      ['Sie sehen aus, als wären Sie schon weit gelaufen.', 'You look like you’ve walked a long way.'],
      ['Wenn Sie sich verlaufen, fragen Sie einfach. Die Leute hier sind nett.', 'If you get lost, just ask. People here are nice.'],
      ['Was war bisher Ihr schönster Ort?', 'What’s been your favourite place so far?'],
      ['Ich wollte immer schon mal reisen. Vielleicht irgendwann.', 'I’ve always wanted to travel. Maybe someday.'],
      ['Haben Sie eine Karte dabei? Ohne Karte geht man nicht aus dem Haus.', 'Have you got a map? You don’t leave the house without a map.'],
    ],
    childGreet: [
      ['Hallo!', 'Hello!'],
      ['Hallo! Wer bist du denn?', 'Hello! Who are you, then?'],
      ['Hi! Du bist aber groß!', 'Hi! You’re really tall!'],
      ['Hallo, hallo!', 'Hello, hello!'],
    ],
    childChat: [
      ['Ich kann superschnell rennen! Willst du mal sehen? Später vielleicht.', 'I can run super fast! Want to see? Maybe later.'],
      ['Machst du hier Ferien? Mein Kumpel sagt, wer Ferien macht, ist reich.', 'Are you on holiday here? My mate says people on holiday are rich.'],
      ['Mir ist gestern ein Zahn rausgefallen! Guck! Ach, sieht man nicht.', 'A tooth fell out yesterday! Look! Oh, you can’t see it.'],
      ['Mama sagt, ich soll nicht mit Fremden reden. Aber du siehst nett aus.', 'Mum says I mustn’t talk to strangers. But you look nice.'],
      ['Hast du einen Hund? Ich will so gern einen Hund.', 'Do you have a dog? I really want a dog.'],
      ['Wenn ich groß bin, fliege ich mit einem Flugzeug um die ganze Welt!', 'When I grow up I’m going to fly a plane round the whole world!'],
      ['Kennst du ein Spiel? Ich kenne ganz viele Spiele.', 'Do you know any games? I know loads of games.'],
    ],
    childBye: [
      ['Tschüss!', 'Bye!'],
      ['Tschüss! Komm wieder spielen!', 'Bye! Come back and play!'],
      ['Ich muss los, Mama ruft!', 'I have to go, Mum’s calling!'],
      ['Tschüssikowski!', 'Bye-bye-ski!'],
    ],
    grumpyGreet: [
      ['Hm. Was wollen Sie?', 'Hm. What do you want?'],
      ['Ja? Was gibt’s?', 'Yes? What is it?'],
      ['Ach. Schon wieder Besuch.', 'Oh. Visitors again.'],
      ['Pff. Hallo. Meinetwegen.', 'Pff. Hello. If I must.'],
    ],
    grumpyChat: [
      ['Früher war es hier schöner. Bevor alle herkamen.', 'It was nicer here before. Before everybody came.'],
      ['Alles kostet heute das Doppelte.', 'Everything costs double these days.'],
      ['Stehen Sie nicht mitten auf dem Gehweg. Hier wohnen Leute.', 'Don’t stand in the middle of the pavement. People live here.'],
      ['Die jungen Leute heute, immer nur am Handy.', 'Young people these days, always on their phones.'],
      ['Keine Ahnung, was alle hier wollen. Hier gibt’s nichts zu sehen.', 'No idea what everybody wants here. There’s nothing to see.'],
    ],
    grumpyBye: [
      ['So. Dann gehen Sie mal.', 'Right. Off you go, then.'],
      ['Na, ich will Sie nicht aufhalten.', 'Well, I won’t keep you.'],
      ['Hm. Wiedersehen.', 'Hm. Goodbye.'],
      ['Passen Sie auf sich auf. Und machen Sie das Tor zu.', 'Mind how you go. And shut the gate.'],
    ],
    elderChat: [
      ['Als ich jung war, waren hier nur Felder.', 'When I was young, this was all fields.'],
      ['Ich wohne mein ganzes Leben hier. Achtzig Jahre! Stellen Sie sich das vor.', 'I’ve lived here all my life. Eighty years! Imagine that.'],
      ['Früher sind wir überall zu Fuß gegangen. Sie ja auch. Recht so!', 'We used to walk everywhere. So do you. Quite right!'],
      ['Meine Enkel wohnen jetzt im Ausland. Sonntags rufen sie immer an.', 'My grandchildren live abroad now. They always call on Sundays.'],
      ['Alles ändert sich so schnell. Aber die alten Gassen bleiben.', 'Everything changes so fast. But the old lanes stay.'],
    ],
    chattyChat: [
      ['Ach, ich liebe Reisende! Erzählen Sie alles. Nein, warten Sie, ich zuerst.', 'Oh, I love travellers! Tell me everything. No, wait, me first.'],
      ['Mein Cousin ist mal verreist. Zurück kam er mit Bart und Ehefrau!', 'My cousin went travelling once. He came back with a beard and a wife!'],
      ['Ich könnte den ganzen Tag reden, sagen meine Freunde. Stimmt ja auch!', 'I could talk all day, my friends say. And it’s true!'],
      ['Haben Sie schon gegessen? Sie sehen hungrig aus. Das sage ich zu jedem.', 'Have you eaten? You look hungry. I say that to everyone.'],
      ['Ein Geheimtipp: Die schönste Aussicht hat man vom Hügel hinter der Kirche.', 'Insider tip: the best view is from the hill behind the church.'],
    ],
    bye: [
      ['Auf Wiedersehen! Gute Reise.', 'Goodbye! Have a good trip.'],
      ['Machen Sie’s gut! Genießen Sie den Rest der Reise.', 'Take care! Enjoy the rest of your journey.'],
      ['Kommen Sie gut an!', 'Get there safely!'],
      ['Tschüss! Besuchen Sie uns mal wieder.', 'Bye! Come and see us again.'],
      ['War nett, mit Ihnen zu plaudern. Passen Sie auf sich auf!', 'Nice chatting with you. Look after yourself!'],
      ['Na dann, los! Es gibt so viel zu sehen.', 'Off you go, then! There’s so much to see.'],
    ],
  },
  countries: {
    // Every fact is a nominative noun phrase, with its article where German uses one; the templates set it off by a colon or a dash, so no case or agreement touches it.
    DEU: {
      dish: ['die Currywurst', 'currywurst'],
      drink: ['ein frisch gezapftes Pils', 'a freshly tapped pilsner'],
      festival: ['das Oktoberfest', 'Oktoberfest'],
      sport: ['der Fußball', 'football'],
      wonder: ['die Zugspitze', 'the Zugspitze'],
      pride: ['unser Brot', 'our bread'],
      proverb: ['Morgenstund hat Gold im Mund', 'The morning hour has gold in its mouth'],
    },
    AUT: {
      dish: ['das Wiener Schnitzel', 'Wiener schnitzel'],
      drink: ['eine Wiener Melange', 'a Viennese melange'],
      festival: ['der Wiener Opernball', 'the Vienna Opera Ball'],
      sport: ['das Skifahren', 'skiing'],
      wonder: ['der Großglockner', 'the Grossglockner'],
      pride: ['die Wiener Kaffeehauskultur', 'Vienna’s coffee house culture'],
      proverb: ['Es wird nichts so heiß gegessen, wie es gekocht wird', 'Nothing is eaten as hot as it is cooked'],
    },
    CHE: {
      dish: ['das Käsefondue', 'cheese fondue'],
      drink: ['eine heisse Schokolade', 'a hot chocolate'],
      festival: ['die Basler Fasnacht', 'the Basel Carnival'],
      sport: ['das Schwingen', 'Schwingen, our Alpine wrestling'],
      wonder: ['das Matterhorn', 'the Matterhorn'],
      pride: ['die Schweizer Uhrmacherkunst', 'Swiss watchmaking'],
      proverb: ['Gut Ding will Weile haben', 'A good thing wants its time'],
    },
    LIE: {
      dish: ['die Käsknöpfle', 'Käsknöpfle, our cheese dumplings'],
      festival: ['der Staatsfeiertag am 15. August', 'the National Day on 15 August'],
      sport: ['das Skifahren', 'skiing'],
      wonder: ['das Schloss Vaduz', 'Vaduz Castle'],
      pride: ['unsere Briefmarken', 'our postage stamps'],
      proverb: ['Wer rastet, der rostet', 'Whoever rests, rusts'],
    },
  },
};

export default DE;
