import type { Language } from '../phrases.ts';

const EL: Language = {
  locale: 'el',
  name: 'Greek',
  join: ' ',
  compass: [
    'βόρεια από εδώ', 'βορειοανατολικά από εδώ', 'ανατολικά από εδώ', 'νοτιοανατολικά από εδώ',
    'νότια από εδώ', 'νοτιοδυτικά από εδώ', 'δυτικά από εδώ', 'βορειοδυτικά από εδώ',
  ],
  lines: {
    morning: [
      ['Καλημέρα!', 'Good morning!'],
      ['Καλημέρα σας!', 'Good morning to you!'],
      ['Καλημέρα! Τι ωραίο πρωινό, ε;', 'Good morning! What a lovely morning, eh?'],
      ['Α, καλημέρα! Καλή σας μέρα.', 'Oh, good morning! Have a good day.'],
    ],
    afternoon: [
      ['Γεια σας!', 'Hello!'],
      ['Χαίρετε!', 'Greetings!'],
      ['Καλησπέρα!', 'Good afternoon!'],
      ['Καλησπέρα σας! Ωραίο απόγευμα, ε;', 'Good afternoon! Nice afternoon, eh?'],
    ],
    evening: [
      ['Καλησπέρα!', 'Good evening!'],
      ['Καλησπέρα σας! Ωραία βραδιά για βόλτα.', 'Good evening! A nice evening for a stroll.'],
      ['Γεια σας, καλησπέρα.', 'Hello, good evening.'],
      ['Καλησπέρα! Πώς πέρασε κιόλας η μέρα;', 'Good evening! Where did the day go?'],
    ],
    night: [
      ['Καλησπέρα! Είναι αργά, έτσι δεν είναι;', "Good evening! It's late, isn't it?"],
      ['Παναγία μου, με τρομάξατε! Καλησπέρα.', 'Holy Mother, you frightened me! Good evening.'],
      ['Νυχτερινή βόλτα; Καλησπέρα!', 'A night walk? Good evening!'],
      ['Καλησπέρα! Ή μήπως καλημέρα πια;', 'Good evening! Or is it good morning already?'],
    ],
    again: [
      ['Α, πάλι εσείς! Γεια σας!', 'Oh, you again! Hello!'],
      ['Ξανασυναντιόμαστε! Ακόμα εξερευνάτε;', 'We meet again! Still exploring?'],
      ['Γεια σας και πάλι!', 'Hello again!'],
      ['Α, εσείς! Βρήκατε τον δρόμο σας;', 'Ah, you! Did you find your way?'],
    ],
    welcome: [
      ['Καλώς ήρθατε στην πόλη {town}!', 'Welcome to {town}!'],
      ['Εδώ είναι η πόλη {town}. Ήρθατε για επίσκεψη;', 'This is {town}. Are you here for a visit?'],
      ['Πρώτη φορά στην πόλη {town};', 'First time in {town}?'],
      ['Διαλέξατε καλή μέρα για να δείτε την πόλη {town}.', 'You picked a good day to see {town}.'],
      ['Καλώς ορίσατε! Η πόλη {town} σας καλωσορίζει.', 'Welcome! {town} is glad to have you.'],
      ['Τι σας φέρνει στην πόλη {town};', 'What brings you to {town}?'],
    ],
    capitalHere: [
      ['Η πόλη {town} είναι η πρωτεύουσα της χώρας μας.', '{town} is the capital of our country.'],
      ['Εδώ είναι η πρωτεύουσα, ξέρετε. Όλα γίνονται εδώ.', 'This is the capital, you know. Everything happens here.'],
      ['Εδώ έχει την έδρα της η κυβέρνηση. Παντού σοβαροί άνθρωποι με κοστούμια.', 'The government has its seat here. Serious people in suits everywhere.'],
      ['Ως πρωτεύουσα, η πόλη {town} δεν κοιμάται ποτέ.', 'Being the capital, {town} never sleeps.'],
    ],
    capitalThere: [
      ['Πρωτεύουσά μας είναι η πόλη {capital}. Αξίζει να την επισκεφθείτε.', 'Our capital is {capital}. It is worth a visit.'],
      ['Έχετε πάει στην πόλη {capital}; Είναι η πρωτεύουσά μας.', 'Have you been to {capital}? It is our capital.'],
      ['Στην πόλη {capital} νομίζουν ότι κυβερνούν τη χώρα. Και έχουν δίκιο.', "In {capital} they think they run the country. And they're right."],
      ['Η πόλη {capital} είναι μεγαλύτερη, αλλά εγώ προτιμώ εδώ.', '{capital} is bigger, but I prefer it here.'],
    ],
    big: [
      ['Είναι μεγάλη πόλη. Εδώ χάνεσαι εύκολα!', "It's a big city. You get lost easily here!"],
      ['Τόσος κόσμος! Ζεις μια ζωή εδώ και δεν μαθαίνεις όλους τους δρόμους.', 'So many people! You live a lifetime here and never learn every street.'],
      ['Η κίνηση εδώ, μη ρωτάτε. Αλλά πάντα κάτι γίνεται.', "The traffic here, don't ask. But there's always something going on."],
      ['Μια μεγάλη πόλη δεν σταματά ποτέ. Μου αρέσει. Συνήθως.', 'A big city never stops. I like it. Usually.'],
    ],
    middling: [
      ['Ούτε μεγάλη ούτε μικρή. Ό,τι πρέπει.', 'Not big, not small. Just right.'],
      ['Αρκετά μεγάλη για να έχει τα πάντα, αρκετά μικρή για να την περπατήσετε.', 'Big enough to have everything, small enough to walk.'],
      ['Την πόλη {town} τη γυρίζετε σε μια-δυο μέρες.', 'You can get round {town} in a day or two.'],
      ['Όλοι παραπονιούνται ότι είναι ήσυχα, και κανείς δεν φεύγει.', "Everybody complains it's quiet, and nobody leaves."],
    ],
    small: [
      ['Είναι ένα μικρό μέρος. Εδώ όλοι γνωρίζονται.', "It's a small place. Everybody knows each other here."],
      ['Φταρνίζεσαι στη μια άκρη και από την άλλη σου λένε «γείτσες».', 'You sneeze at one end and from the other they say "bless you".'],
      ['Στην πόλη {town} δεν γίνονται πολλά, και έτσι μας αρέσει.', 'Not much happens in {town}, and that is how we like it.'],
      ['Είστε το πιο συναρπαστικό πράγμα που έγινε εδώ όλη την εβδομάδα!', "You're the most exciting thing to happen here all week!"],
    ],
    coast: [
      ['Εδώ ζούμε δίπλα στο νερό. Το ψάρι είναι εξαιρετικό.', 'We live by the water here. The fish is excellent.'],
      ['Πηγαίνετε να δείτε το νερό. Κάθε μέρα είναι αλλιώς.', 'Go and look at the water. It is different every day.'],
      ['Τη μυρίζετε; Είναι η αύρα του νερού. Δεν τη χορταίνεις ποτέ.', "Smell it? That's the breeze off the water. You never get enough of it."],
      ['Τα καΐκια βγαίνουν χαράματα και γυρίζουν με το καλύτερο ψάρι.', 'The boats go out at dawn and come back with the best fish.'],
    ],
    inland: [
      ['Είμαστε μακριά από τη θάλασσα, αλλά ο τόπος είναι πανέμορφος.', 'We are far from the sea, but the land is beautiful.'],
      ['Παραλία δεν έχουμε, αλλά δείτε τι κάμπος!', "We have no beach, but look at these fields!"],
      ['Θάλασσα; Είναι μακριά, τη βλέπουμε σπάνια.', 'The sea? It is far away, we rarely see it.'],
      ['Εδώ η γη είναι το παν. Καλό χώμα, καλοί άνθρωποι.', 'Here the land is everything. Good soil, good people.'],
    ],
    high: [
      ['Είμαστε ψηλά εδώ. Σιγά σιγά, ο αέρας είναι αραιός.', "We're high up here. Slowly, slowly, the air is thin."],
      ['Στα βουνά, το καλύτερο που έχουμε είναι η θέα.', 'In the mountains, the best thing we have is the view.'],
      ['Εδώ τίποτα δεν είναι ίσιο. Τα πόδια σας θα γίνουν ατσάλι.', 'Nothing is flat here. Your legs will turn to steel.'],
      ['Πάρτε ανάσα! Το βουνό θέλει τον χρόνο του.', 'Catch your breath! The mountain takes its time.'],
    ],
    snowy: [
      ['Χιόνι εννιά μήνες τον χρόνο. Τους άλλους τρεις γκρινιάζουμε για τη λάσπη.', 'Snow nine months a year. The other three, we grumble about the mud.'],
      ['Όλα είναι λευκά εδώ. Θα θέλατε καλύτερες μπότες.', 'Everything is white here. You would want better boots.'],
      ['Το κρύο δεν μας πειράζει. Διώχνει τους τουρίστες. Εσάς όχι, εννοείται!', "The cold doesn't bother us. It keeps tourists away. Not you, of course!"],
      ['Όταν πέφτει φρέσκο χιόνι, έχει τέτοια ησυχία που ακούς τις σκέψεις σου.', "When fresh snow falls, it's so quiet you hear your own thoughts."],
    ],
    forest: [
      ['Τα δάση εδώ δεν τελειώνουν. Μην βγείτε από το μονοπάτι!', 'The forests here never end. Stay on the path!'],
      ['Κάντε μια βόλτα στο δάσος. Καθαρίζει το μυαλό.', 'Take a walk in the forest. It clears the mind.'],
      ['Κάθε φθινόπωρο μαζεύουμε μανιτάρια.', 'Every autumn we go gathering mushrooms.'],
      ['Δέντρα, δέντρα και πάλι δέντρα. Δεν θα ζούσα πουθενά αλλού.', "Trees, trees and more trees. I wouldn't live anywhere else."],
    ],
    desert: [
      ['Εδώ έχει άμμο όσο φτάνει το μάτι.', 'Here there is sand as far as the eye can see.'],
      ['Πίνετε πολύ νερό. Η έρημος δεν συγχωρεί.', 'Drink plenty of water. The desert does not forgive.'],
      ['Οι νύχτες στην έρημο είναι κρύες. Κανείς δεν το πιστεύει.', 'Desert nights are cold. Nobody believes it.'],
      ['Περιμένετε να νυχτώσει. Εδώ τα αστέρια είναι εκατομμύρια.', 'Wait until nightfall. Here the stars are in their millions.'],
    ],
    plains: [
      ['Κάμπος όσο φτάνει το μάτι. Βλέπεις την μπόρα να έρχεται από μακριά.', 'Flat land as far as the eye can see. You watch the storm coming from afar.'],
      ['Μεγάλος ουρανός και τίποτα να σταματήσει τον αέρα.', 'A big sky and nothing to stop the wind.'],
      ['Καλά βοσκοτόπια. Προσοχή στα κοπάδια!', 'Good pasture. Mind the herds!'],
      ['Το χορτάρι φτάνει ως τον ορίζοντα. Σαν πράσινη θάλασσα.', 'The grass reaches the horizon. Like a green sea.'],
    ],
    tropical: [
      ['Εδώ φυτρώνουν τα πάντα. Φυτεύεις ένα ξύλο και γίνεται δέντρο.', 'Everything grows here. Plant a stick and it becomes a tree.'],
      ['Όταν βρέχει εδώ, βρέχει για τα καλά. Και μετά σταματά απότομα.', 'When it rains here, it really rains. And then it stops, just like that.'],
      ['Δοκιμάστε τα φρούτα από την αγορά. Τέτοια δεν έχετε ξαναφάει.', "Try the fruit from the market. You've never tasted anything like it."],
      ['Πράσινο όλο τον χρόνο. Χειμώνας; Ποιος χειμώνας;', 'Green all year round. Winter? What winter?'],
    ],
    landmark: [
      ['Μην χάσετε το αξιοθέατο {landmark}! Είναι περίπου {km} χιλιόμετρα {dir}.', "Don't miss {landmark}! It's about {km} km {dir}."],
      ['Έχετε δει το αξιοθέατο {landmark}; Είναι {km} χιλιόμετρα {dir}, αξίζει κάθε βήμα.', "Have you seen {landmark}? It's {km} km {dir}, worth every step."],
      ['Όλοι πηγαίνουν στο αξιοθέατο {landmark}. Είναι κάπου {km} χιλιόμετρα {dir}.', "Everyone goes to {landmark}. It's some {km} km {dir}."],
      ['Αν σας αρέσουν τα παλιά, το αξιοθέατο {landmark} είναι {km} χιλιόμετρα {dir}.', 'If you like old things, {landmark} is {km} km {dir}.'],
    ],
    landmarkNear: [
      ['Το αξιοθέατο {landmark} είναι πολύ κοντά. Δεν μπορείτε να το χάσετε!', "{landmark} is very close. You can't miss it!"],
      ['Πήγατε στο αξιοθέατο {landmark}; Είναι εδώ στη γωνία.', 'Have you been to {landmark}? It is just round the corner.'],
      ['Βλέπουμε το αξιοθέατο {landmark} κάθε μέρα και ακόμα μας κόβει την ανάσα.', 'We see {landmark} every day and it still takes our breath away.'],
      ['Πηγαίνετε να δείτε το αξιοθέατο {landmark}, είναι ακριβώς εδώ. Νωρίς, πριν από τον κόσμο.', 'Go and see {landmark}, it is right here. Early, before the crowds.'],
    ],
    plane: [
      ['Υπάρχει ένα μικρό αεροπλάνο σε ένα χωράφι {dir}, αν ξέρετε να πετάτε!', "There's a little plane in a field {dir}, if you can fly!"],
      ['Κάποιος άφησε ένα αεροπλάνο σε ένα χωράφι {dir}. Μια πτήση;', 'Somebody left a plane in a field {dir}. Fancy a flight?'],
      ['Ξέρετε να πιλοτάρετε; Ένα αεροπλάνο περιμένει {dir}.', 'Can you fly a plane? One is waiting {dir}.'],
      ['Αν θέλετε να τα δείτε όλα από ψηλά, υπάρχει αεροπλάνο {dir}.', "If you want to see it all from above, there's a plane {dir}."],
    ],
    balloon: [
      ['Υπάρχει ένα αερόστατο σε ένα χωράφι {dir}! Φανταστείτε τη θέα.', "There's a hot-air balloon in a field {dir}! Imagine the view."],
      ['Έχετε πετάξει ποτέ με αερόστατο; Υπάρχει ένα {dir}.', "Have you ever flown in a balloon? There's one {dir}."],
      ['Ένα αερόστατο σηκώνεται από το χωράφι {dir}. Μαγεία!', 'A balloon goes up from the field {dir}. Magic!'],
      ['Πάντα ήθελα να δοκιμάσω το αερόστατο {dir}. Αλλά φοβάμαι!', "I've always wanted to try the balloon {dir}. But I'm scared!"],
    ],
    boat: [
      ['Υπάρχει μια βάρκα στο νερό {dir}, αν θέλετε να βγείτε.', "There's a boat on the water {dir}, if you want to go out."],
      ['Σας αρέσει η θάλασσα; Υπάρχει μια βάρκα {dir}. Μόνο φέρτε την πίσω!', "Like the sea? There's a boat {dir}. Just bring it back!"],
      ['Μια βάρκα είναι δεμένη {dir}. Από εδώ πάτε όπου θέλετε.', 'A boat is tied up {dir}. From here you can go wherever you like.'],
      ['Πάρτε τη βάρκα {dir} και δείτε την ακτή από τη θάλασσα.', 'Take the boat {dir} and see the coast from the sea.'],
    ],
    hot: [
      ['Κάνει ζέστη σήμερα! Βρείτε λίγη σκιά.', "It's hot today! Find some shade."],
      ['Ουφ, τι ζέστη! Πιείτε λίγο νερό.', 'Phew, what heat! Drink some water.'],
      ['Με τέτοια ζέστη, μόνο για σκιά και φραπέ είναι.', 'In heat like this, it is only good for shade and a frappé.'],
      ['Με αυτή τη ζέστη ούτε τα σκυλιά δεν βγαίνουν.', 'In this heat not even the dogs go out.'],
      ['Ζέστη, ε; Και για μας αυτή είναι δροσερή μέρα!', 'Hot, eh? And for us this is a cool day!'],
    ],
    cold: [
      ['Μπρρ, κάνει κρύο σήμερα! Ντυθείτε ζεστά.', "Brr, it's cold today! Dress warmly."],
      ['Παγωνιά! Πού είναι τα γάντια σας;', 'Freezing! Where are your gloves?'],
      ['Κάνει τόσο κρύο που δεν νιώθω τη μύτη μου.', "It's so cold I can't feel my nose."],
      ['Κρύο; Περιμένετε να σηκωθεί ο αέρας.', 'Cold? Wait till the wind gets up.'],
      ['Πιείτε κάτι ζεστό. Βοηθάει.', 'Have something hot to drink. It helps.'],
    ],
    mild: [
      ['Τι ωραίος καιρός σήμερα.', 'What lovely weather today.'],
      ['Ούτε ζέστη ούτε κρύο. Τέλεια μέρα, ε;', 'Not hot, not cold. A perfect day, eh?'],
      ['Τέτοια μέρα θέλεις να είσαι έξω.', 'On a day like this you want to be outside.'],
      ['Υπέροχος καιρός! Μακάρι να κρατήσει.', 'Wonderful weather! Let us hope it lasts.'],
      ['Για τέτοιες μέρες ζούμε εδώ.', 'Days like this are why we live here.'],
    ],
    late: [
      ['Είναι αργά. Τη νύχτα οι δρόμοι είναι ήσυχοι.', "It's late. The streets are quiet at night."],
      ['Τέτοια ώρα έξω είναι μόνο οι γάτες. Κι εμείς!', 'At this hour only the cats are out. And us!'],
      ['Θα έπρεπε να κοιμάμαι. Εσείς γιατί δεν κοιμάστε;', "I should be asleep. Why aren't you sleeping?"],
      ['Κοιτάξτε τα αστέρια! Από εδώ φαίνονται καλύτερα.', 'Look at the stars! You see them best from here.'],
    ],
    early: [
      ['Νωρίς ξυπνήσατε! Η καλύτερη ώρα της μέρας.', 'You woke up early! The best time of the day.'],
      ['Ο φούρνος μόλις άνοιξε. Ακολουθήστε τη μυρωδιά!', 'The bakery has just opened. Follow the smell!'],
      ['Η πόλη ακόμα κοιμάται κι εσείς ήδη στο πόδι!', 'The town is still asleep and you are already up and about!'],
      ['Μου αρέσει το πρωί εδώ, πριν αρχίσει η φασαρία.', 'I love the morning here, before the noise starts.'],
    ],
    country: [
      ['{country}: μια πανέμορφη χώρα. Απολαύστε τη!', '{country}: a beautiful country. Enjoy it!'],
      ['Πώς σας φαίνεται η χώρα μας; {country}: ήλιος, θάλασσα και φιλοξενία!', 'How do you find our country? {country}: sun, sea and hospitality!'],
      ['{country}: μικρή στον χάρτη, μεγάλη στην καρδιά.', '{country}: small on the map, big at heart.'],
      ['Γυρίστε όσο περισσότερο μπορείτε. {country}: κάθε γωνιά κι άλλος κόσμος.', 'Travel as much as you can. {country}: every corner a different world.'],
    ],
    dish: [
      ['Πρέπει να δοκιμάσετε {dish} όσο είστε εδώ.', "You must try {dish} while you're here."],
      ['Δοκιμάσατε ήδη {dish}; Όχι; Α, πρέπει!', 'Have you tried {dish} yet? No? Oh, you must!'],
      ['Κανείς δεν φτιάχνει {dish} όπως η μάνα μου.', 'Nobody makes {dish} like my mother.'],
      ['Αν πεινάτε, πάρτε {dish}. Δεν θα το μετανιώσετε.', "If you're hungry, get {dish}. You won't regret it."],
    ],
    drink: [
      ['Πιείτε {drink} πριν φύγετε. Αυτό πίνουμε εδώ.', "Have {drink} before you leave. It's what we drink here."],
      ['Τίποτα δεν συγκρίνεται με {drink} στο τέλος της μέρας.', 'Nothing compares with {drink} at the end of the day.'],
      ['Αν δεν δοκιμάσετε {drink}, δεν έχετε ζήσει.', "If you haven't tried {drink}, you haven't lived."],
      ['Παραγγείλτε {drink} και οι ντόπιοι θα σας λατρέψουν.', 'Order {drink} and the locals will love you.'],
    ],
    festival: [
      ['Να ξανάρθετε για {festival}. Είναι υπέροχα!', 'Come back for {festival}. It is wonderful!'],
      ['Θέλετε την καλύτερη εποχή; Ελάτε για {festival}. Γιορτάζει όλος ο τόπος.', 'Want the best time of year? Come for {festival}. The whole land celebrates.'],
      ['Έχετε ακούσει για {festival}; Θα σας άρεσε πολύ.', "Have you heard of {festival}? You'd love it."],
      ['Κάθε χρόνο μετράω τις μέρες ως {festival}.', 'Every year I count the days till {festival}.'],
    ],
    sport: [
      ['Εδώ όλοι τρελαίνονται για {sport}.', 'Here everybody is crazy about {sport}.'],
      ['Εδώ ζούμε και αναπνέουμε για {sport}.', 'Here we live and breathe for {sport}.'],
      ['Μέρα αγώνα, όλη η πόλη συζητά μόνο για {sport}.', 'On match day the whole town talks about nothing but {sport}.'],
      ['Όλη μου η οικογένεια λατρεύει {sport}. Η γιαγιά μόνο φωνάζει στην τηλεόραση.', 'My whole family loves {sport}. Grandma just shouts at the TV.'],
    ],
    wonder: [
      ['Αν έχετε χρόνο, πηγαίνετε να δείτε {wonder}. Αξέχαστο!', 'If you have time, go and see {wonder}. Unforgettable!'],
      ['Έχετε δει {wonder}; Δεν υπάρχει κάτι τέτοιο πουθενά.', "Have you seen {wonder}? There's nothing like it anywhere."],
      ['Όλοι πρέπει να δουν {wonder} μια φορά στη ζωή τους.', 'Everyone should see {wonder} once in their life.'],
      ['Είδα {wonder} όταν ήμουν παιδί. Ακόμα το ονειρεύομαι.', 'I saw {wonder} as a child. I still dream about it.'],
    ],
    pride: [
      ['Καμαρώνουμε πολύ για {pride}.', 'We are very proud of {pride}.'],
      ['Μην φύγετε χωρίς να μάθετε για {pride}. Αυτό είμαστε.', "Don't leave without learning about {pride}. It's who we are."],
      ['Ξέρετε για τι καμαρώνουμε; Για {pride}.', 'Do you know what we are proud of? {pride}.'],
      ['Ρωτήστε όποιον θέλετε για {pride} και θα σας μιλάει ώρες.', "Ask anyone you like about {pride} and they'll talk for hours."],
    ],
    proverb: [
      ['Όπως λέμε εδώ: «{proverb}»', 'As we say here: “{proverb}”'],
      ['Η γιαγιά μου πάντα έλεγε: «{proverb}»', 'My grandmother always said: “{proverb}”'],
      ['Έχουμε μια παροιμία: «{proverb}»', 'We have a proverb: “{proverb}”'],
      ['Την ξέρετε την παροιμία; «{proverb}»', 'Do you know the proverb? “{proverb}”'],
    ],
    chat: [
      ['Από πού είστε; Δεν είστε από εδώ.', "Where are you from? You're not from here."],
      ['Με την ησυχία σας, κοιτάξτε γύρω. Έχει πολλά να δείτε.', 'Take your time and look around. There is a lot to see.'],
      ['Ταξιδεύετε χωρίς παρέα; Μπράβο το θάρρος!', 'Travelling without company? Hats off to your courage!'],
      ['Φαίνεται πως έχετε περπατήσει πολύ.', 'You look like you have walked a long way.'],
      ['Αν χαθείτε, ρωτήστε. Οι άνθρωποι εδώ είναι φιλικοί.', 'If you get lost, just ask. People here are friendly.'],
      ['Ποιο είναι το ωραιότερο μέρος που έχετε δει ως τώρα;', 'What is the most beautiful place you have seen so far?'],
      ['Πάντα ήθελα να ταξιδέψω. Ίσως κάποια μέρα.', 'I have always wanted to travel. Maybe one day.'],
      ['Έχετε χάρτη; Ο χάρτης είναι το παν.', 'Have you got a map? A map is everything.'],
    ],
    childGreet: [
      ['Γεια!', 'Hi!'],
      ['Γεια! Πώς σε λένε;', "Hi! What's your name?"],
      ['Γεια σου! Πόσο χρονών είσαι;', 'Hello! How old are you?'],
      ['Γεια, γεια!', 'Hi, hi!'],
    ],
    childChat: [
      ['Τρέχω πολύ γρήγορα! Θες να δεις; Μάλλον αργότερα.', 'I run really fast! Want to see? Maybe later.'],
      ['Ο φίλος μου λέει ότι οι τουρίστες είναι πλούσιοι. Αλήθεια;', 'My friend says tourists are rich. Is it true?'],
      ['Χθες μου έπεσε ένα δόντι! Κοίτα! Α, δεν φαίνεται.', "A tooth fell out yesterday! Look! Oh, you can't see it."],
      ['Η μαμά λέει να μη μιλάω με ξένους. Αλλά εσύ έχεις καλό πρόσωπο.', 'Mum says not to talk to strangers. But you have a kind face.'],
      ['Έχεις σκύλο; Εγώ θέλω σκύλο!', 'Do you have a dog? I want a dog!'],
      ['Όταν μεγαλώσω, θα πετάξω με αεροπλάνο γύρω από τον κόσμο!', "When I grow up, I'll fly a plane round the world!"],
      ['Ξέρεις κανένα παιχνίδι; Εγώ ξέρω ένα σωρό!', 'Do you know any games? I know loads!'],
    ],
    childBye: [
      ['Γεια γεια!', 'Bye bye!'],
      ['Γεια! Έλα πάλι να παίξουμε!', 'Bye! Come back and play!'],
      ['Πρέπει να φύγω, με φωνάζει η μαμά!', 'I have to go, mum is calling me!'],
      ['Τα λέμε!', 'See you!'],
    ],
    grumpyGreet: [
      ['Χμ. Τι θέλετε;', 'Hm. What do you want?'],
      ['Ναι; Τι είναι;', 'Yes? What is it?'],
      ['Α. Πάλι τουρίστες.', 'Oh. Tourists again.'],
      ['Χμφ. Γεια σας, λοιπόν.', 'Hmph. Hello, then.'],
    ],
    grumpyChat: [
      ['Παλιά ήταν καλύτερα, πριν έρθουν όλοι αυτοί.', 'It was better before all these people came.'],
      ['Όλα κοστίζουν τα διπλά απ’ ό,τι παλιά.', 'Everything costs double what it used to.'],
      ['Μην κλείνετε το πεζοδρόμιο, παρακαλώ. Εδώ μένει κόσμος.', "Don't block the pavement, please. People live here."],
      ['Οι νέοι σήμερα, όλο με το κινητό στο χέρι.', 'Young people today, always a phone in hand.'],
      ['Δεν ξέρω τι έρχεται να δει ο κόσμος εδώ. Τίποτα δεν έχει.', "I don't know what people come here to see. There's nothing."],
    ],
    grumpyBye: [
      ['Καλά. Πηγαίνετε τώρα.', 'Fine. Off you go now.'],
      ['Δεν σας κρατάω.', "I won't keep you."],
      ['Χμ. Γεια σας.', 'Hm. Goodbye.'],
      ['Προσέχετε πού πατάτε. Και κλείστε την πόρτα.', 'Watch your step. And shut the gate.'],
    ],
    elderChat: [
      ['Στα χρόνια μου, εδώ ήταν όλο χωράφια.', 'In my day, this was all fields.'],
      ['Όλη μου τη ζωή εδώ μένω. Ογδόντα χρόνια! Το πιστεύετε;', "I've lived here all my life. Eighty years! Can you believe it?"],
      ['Στον καιρό μας πηγαίναμε παντού με τα πόδια. Κι εσείς περπατάτε. Μπράβο!', 'In our time we went everywhere on foot. You walk too. Well done!'],
      ['Τα εγγόνια μου ζουν τώρα στο εξωτερικό. Παίρνουν τηλέφωνο κάθε Κυριακή.', 'My grandchildren live abroad now. They ring every Sunday.'],
      ['Όλα αλλάζουν τόσο γρήγορα. Μόνο τα παλιά σοκάκια μένουν ίδια.', 'Everything changes so fast. Only the old alleys stay the same.'],
    ],
    chattyChat: [
      ['Α, λατρεύω τους ταξιδιώτες! Πείτε μου τα όλα. Όχι, σταθείτε, πρώτα εγώ!', 'Oh, I love travellers! Tell me everything. No, wait, me first!'],
      ['Ο ξάδερφός μου πήγε κάποτε ταξίδι. Γύρισε με γένια και με γυναίκα!', 'My cousin went on a trip once. He came back with a beard and a wife!'],
      ['Οι φίλοι μου λένε ότι μιλάω όλη μέρα. Έχουν δίκιο!', "My friends say I talk all day. They're right!"],
      ['Φάγατε; Όλοι μου φαίνονται πεινασμένοι!', 'Have you eaten? Everybody looks hungry to me!'],
      ['Να σας πω ένα μυστικό: η καλύτερη θέα είναι από τον λόφο πίσω από την εκκλησία.', 'Let me tell you a secret: the best view is from the hill behind the church.'],
    ],
    bye: [
      ['Αντίο! Καλό ταξίδι.', 'Goodbye! Have a good trip.'],
      ['Να προσέχετε! Καλή συνέχεια στο ταξίδι σας.', 'Take care! Enjoy the rest of your journey.'],
      ['Καλό δρόμο!', 'Safe travels!'],
      ['Γεια σας! Να ξανάρθετε.', 'Goodbye! Come again.'],
      ['Χάρηκα πολύ. Να είστε καλά!', 'Lovely to meet you. Be well!'],
      ['Άντε, στο καλό! Έχετε τόσα να δείτε.', 'Go well, then! You have so much to see.'],
    ],
  },
  countries: {
    // Every fact in the accusative with its article, as the object of a verb or after "για", "με" or "ως".
    GRC: {
      dish: ['τον μουσακά', 'moussaka'],
      drink: ['το ούζο', 'ouzo'],
      festival: ['το Πάσχα', 'Greek Easter'],
      sport: ['το ποδόσφαιρο', 'football'],
      wonder: ['τα Μετέωρα', 'Meteora'],
      pride: ['τη φιλοξενία μας', 'our hospitality'],
      proverb: ['Σιγά σιγά η αγουρίδα γίνεται μέλι', 'Little by little the sour grape turns to honey'],
    },
    CYP: {
      dish: ['το χαλλούμι', 'halloumi'],
      drink: ['την κουμανδαρία', 'Commandaria, our sweet wine'],
      festival: ['τον Κατακλυσμό', 'Kataklysmos, the festival of the flood'],
      sport: ['το ποδόσφαιρο', 'football'],
      wonder: ['την Πέτρα του Ρωμιού', "Aphrodite's Rock"],
      pride: ['τα λευκαρίτικα κεντήματα', 'Lefkara lace'],
      proverb: ['Η γλώσσα κόκαλα δεν έχει και κόκαλα τσακίζει', 'The tongue has no bones, yet it breaks bones'],
    },
  },
};

export default EL;
