import type { CountryLines } from '../phrases.ts';

/**
 * The facts of every country whose townsfolk speak English to the traveller.
 * Each is a bare noun phrase that stands mid-sentence in every English template
 * (a drink as a mass noun, a festival as a named day); a pair keeps the local
 * word said and glosses it in the meant half.
 */
export const EN_COUNTRIES: Readonly<Record<string, CountryLines>> = {
  // North America and the Caribbean
  USA: {
    dish: 'barbecue',
    drink: 'root beer',
    festival: 'the Fourth of July',
    sport: 'baseball',
    wonder: 'the Grand Canyon',
    pride: 'our national parks',
    proverb: "There's no such thing as a free lunch",
  },
  CAN: {
    dish: 'poutine',
    drink: 'ice wine',
    festival: 'Canada Day',
    sport: 'hockey',
    wonder: 'Niagara Falls',
    pride: 'our maple syrup',
  },
  JAM: {
    dish: 'ackee and saltfish',
    drink: 'Blue Mountain coffee',
    festival: 'Reggae Sumfest',
    sport: 'cricket',
    wonder: "Dunn's River Falls",
    pride: 'reggae music',
    proverb: ['Every mickle mek a muckle', 'Every little bit adds up to a lot'],
  },
  TTO: {
    dish: 'doubles',
    drink: 'sorrel',
    festival: 'Carnival',
    sport: 'cricket',
    wonder: 'Maracas Bay',
    pride: 'the steelpan',
  },
  BHS: {
    dish: 'conch fritters',
    drink: 'Goombay Smash',
    festival: 'Junkanoo',
    wonder: 'the swimming pigs of Exuma',
    pride: 'our turquoise water',
  },

  // Africa
  NGA: {
    dish: 'jollof rice',
    drink: 'palm wine',
    festival: 'the Durbar festival',
    sport: 'football',
    wonder: 'Zuma Rock',
    pride: 'Nollywood and Afrobeats',
  },
  ETH: {
    dish: ['injera', 'injera flatbread'],
    drink: 'Ethiopian coffee',
    festival: ['Meskel', 'Meskel (the feast of the True Cross)'],
    sport: 'football',
    wonder: 'the rock churches of Lalibela',
    pride: 'our long-distance runners',
    proverb: ['ቀስ በቀስ እንቁላል በእግሩ ይሄዳል', 'Little by little, the egg will walk on its own legs'],
  },
  ZAF: {
    dish: 'bobotie',
    drink: 'rooibos tea',
    festival: 'Heritage Day',
    sport: 'rugby',
    wonder: 'Table Mountain',
    pride: 'the Springboks',
    proverb: ['Umuntu ngumuntu ngabantu', 'A person is a person through other people'],
  },
  UGA: {
    dish: ['matoke', 'matoke (steamed green bananas)'],
    drink: 'Ugandan coffee',
    sport: 'football',
    wonder: 'the source of the Nile at Jinja',
    pride: 'our mountain gorillas',
  },
  GHA: {
    dish: 'fufu with light soup',
    drink: ['sobolo', 'sobolo (a hibiscus drink)'],
    festival: ['Homowo', 'Homowo (the harvest festival)'],
    sport: 'football',
    wonder: 'the canopy walk at Kakum',
    pride: 'kente cloth',
  },
  MWI: {
    dish: ['nsima', 'nsima (maize porridge)'],
    drink: 'Malawian tea',
    festival: 'the Lake of Stars festival',
    sport: 'football',
    wonder: 'Lake Malawi',
    pride: 'our warm hospitality',
  },
  ZMB: {
    dish: ['nshima', 'nshima (maize porridge)'],
    drink: ['munkoyo', 'munkoyo (a sweet maize drink)'],
    festival: 'the Kuomboka ceremony',
    sport: 'football',
    wonder: 'Victoria Falls',
    pride: 'our 2012 Africa Cup of Nations win',
  },
  ZWE: {
    dish: ['sadza', 'sadza (maize porridge)'],
    drink: ['maheu', 'maheu (a maize drink)'],
    festival: 'the Harare International Festival of the Arts',
    sport: 'football',
    wonder: 'Great Zimbabwe',
    pride: 'our stone sculpture',
  },
  SOM: {
    dish: ['canjeero', 'canjeero (a spongy pancake)'],
    drink: ['shaah', 'shaah (spiced tea)'],
    festival: 'Eid al-Fitr',
    sport: 'football',
    wonder: 'Lido Beach',
    pride: 'our poetry',
  },
  RWA: {
    dish: 'goat brochettes',
    drink: 'Rwandan coffee',
    festival: ['Kwita Izina', 'Kwita Izina (the gorilla naming ceremony)'],
    sport: 'football',
    wonder: 'Volcanoes National Park',
    pride: 'our thousand hills',
  },
  NAM: {
    dish: ['kapana', 'kapana (street-grilled beef)'],
    drink: 'Namibian beer',
    festival: 'the Windhoek Oktoberfest',
    sport: 'rugby',
    wonder: 'the dunes of Sossusvlei',
    pride: 'our starry night skies',
  },
  BWA: {
    dish: ['seswaa', 'seswaa (pounded beef)'],
    festival: 'the Maitisong festival',
    sport: 'football',
    wonder: 'the Okavango Delta',
    pride: 'our elephants',
  },

  // South and Southeast Asia
  MMR: {
    dish: ['mohinga', 'mohinga (fish noodle soup)'],
    drink: 'milk tea',
    festival: ['Thingyan', 'Thingyan (the water festival)'],
    sport: ['chinlone', 'chinlone (cane ball)'],
    wonder: 'the temples of Bagan',
    pride: 'the Shwedagon Pagoda',
  },
  NPL: {
    dish: 'momos',
    drink: ['chiya', 'chiya (spiced milk tea)'],
    festival: 'Dashain',
    sport: 'football',
    wonder: 'Mount Everest',
    pride: 'our mountaineers',
  },
  LKA: {
    dish: 'rice and curry',
    drink: 'Ceylon tea',
    festival: 'the Sinhala and Tamil New Year',
    sport: 'cricket',
    wonder: 'Sigiriya',
    pride: 'our 1996 Cricket World Cup win',
  },
  KHM: {
    dish: 'fish amok',
    drink: 'sugarcane juice',
    festival: 'Khmer New Year',
    sport: 'football',
    wonder: 'Angkor Wat',
    pride: 'our Apsara dance',
  },
  LAO: {
    dish: ['larb', 'larb (minced meat salad)'],
    drink: 'Lao coffee',
    festival: ['Pi Mai', 'Pi Mai (the Lao New Year)'],
    sport: 'football',
    wonder: 'the Kuang Si Falls',
    pride: 'our sticky rice',
  },

  // Central Asia, Mongolia and the Caucasus
  UZB: {
    dish: ['plov', 'plov (rice pilaf)'],
    drink: 'green tea',
    festival: 'Navruz',
    sport: 'football',
    wonder: 'the Registan in Samarkand',
    pride: 'the old cities of the Silk Road',
    proverb: ["Mehmon otangdan ulug'", 'A guest is greater than your father'],
  },
  AZE: {
    dish: 'dolma',
    drink: 'black tea',
    festival: 'Novruz',
    sport: 'football',
    wonder: 'the mud volcanoes of Gobustan',
    pride: 'our carpets',
  },
  TJK: {
    dish: ['qurutob', 'qurutob (bread in a yoghurt sauce)'],
    drink: 'green tea',
    festival: 'Navruz',
    sport: 'football',
    wonder: 'the Pamir Mountains',
    pride: 'our hospitality',
  },
  TKM: {
    dish: 'plov',
    drink: 'green tea',
    festival: 'Navruz',
    sport: 'football',
    wonder: 'the Darvaza gas crater',
    pride: 'our Akhal-Teke horses',
  },
  GEO: {
    dish: 'khachapuri',
    drink: 'Georgian wine',
    festival: ['Tbilisoba', 'Tbilisoba (the city festival)'],
    sport: 'rugby',
    wonder: 'Mount Kazbek',
    pride: 'our polyphonic singing',
  },
  ARM: {
    dish: ['khorovats', 'khorovats (barbecue)'],
    drink: 'Armenian brandy',
    festival: ['Vardavar', 'Vardavar (the water festival)'],
    sport: 'chess',
    wonder: 'Lake Sevan',
    pride: 'our apricots',
  },
  MNG: {
    dish: ['buuz', 'buuz (steamed dumplings)'],
    drink: ['airag', "airag, fermented mare's milk"],
    festival: 'Naadam',
    wonder: 'the Gobi Desert',
    pride: 'our horsemen',
  },

  // Europe
  GBR: {
    dish: 'fish and chips',
    drink: 'real ale',
    festival: 'Bonfire Night',
    sport: 'football',
    wonder: 'Stonehenge',
    pride: 'Shakespeare',
    proverb: 'Every cloud has a silver lining',
  },
  HUN: {
    dish: ['gulyás', 'goulash soup'],
    drink: ['pálinka', 'pálinka (fruit brandy)'],
    festival: "St Stephen's Day",
    sport: 'water polo',
    wonder: 'Lake Balaton',
    pride: 'our thermal baths',
    proverb: ['Lassan járj, tovább érsz', 'Walk slowly and you will get further'],
  },
  SRB: {
    dish: ['pljeskavica', 'pljeskavica (a grilled patty)'],
    drink: ['rakija', 'rakija (fruit brandy)'],
    festival: 'the EXIT festival',
    sport: 'basketball',
    wonder: 'the Kalemegdan fortress',
    pride: 'our trumpet bands',
  },
  BGR: {
    dish: ['banitsa', 'banitsa (a cheese pastry)'],
    drink: ['rakia', 'rakia (fruit brandy)'],
    festival: ['Baba Marta Day', 'Baba Marta Day (the welcome of spring)'],
    sport: 'football',
    wonder: 'the Rila Monastery',
    pride: 'our yoghurt',
  },
  DNK: {
    dish: ['smørrebrød', 'smørrebrød (open sandwiches)'],
    drink: ['gløgg', 'gløgg (mulled wine)'],
    festival: ['Sankt Hans aften', 'Midsummer Eve'],
    sport: 'handball',
    wonder: 'the white cliffs of Møns Klint',
    pride: 'hygge',
    proverb: ['Hvad man ikke har i hovedet, må man have i benene', "What you don't have in your head, you must have in your legs"],
  },
  FIN: {
    dish: ['karjalanpiirakka', 'Karelian pies'],
    drink: 'coffee',
    festival: ['juhannus', 'Midsummer'],
    sport: 'ice hockey',
    wonder: 'the northern lights over Lapland',
    pride: 'the sauna',
    proverb: ['Oma maa mansikka, muu maa mustikka', 'Your own land a strawberry, other lands a blueberry'],
  },
  SVK: {
    dish: ['bryndzové halušky', 'dumplings with sheep cheese'],
    drink: ['borovička', 'borovička (juniper brandy)'],
    festival: 'the Východná folk festival',
    sport: 'ice hockey',
    wonder: 'the High Tatras',
    pride: 'our castles',
  },
  NOR: {
    dish: ['fårikål', 'fårikål (lamb and cabbage stew)'],
    drink: 'aquavit',
    festival: 'Constitution Day on the seventeenth of May',
    sport: 'handball',
    wonder: 'the fjords',
    pride: 'our skiers',
    proverb: ['Det finnes ikke dårlig vær, bare dårlige klær', "There's no bad weather, only bad clothes"],
  },
  IRL: {
    dish: 'Irish stew',
    drink: 'stout',
    festival: "St Patrick's Day",
    sport: 'hurling',
    wonder: 'the Cliffs of Moher',
    pride: 'our traditional music',
    proverb: ['Ar scáth a chéile a mhaireann na daoine', "People live in each other's shelter"],
  },
  HRV: {
    dish: ['peka', 'peka (meat baked under a bell)'],
    drink: 'Dalmatian wine',
    festival: 'the Rijeka Carnival',
    sport: 'football',
    wonder: 'the Plitvice Lakes',
    pride: 'the necktie, which we invented',
  },
  BIH: {
    dish: ['ćevapi', 'ćevapi (grilled meat)'],
    drink: 'Bosnian coffee',
    festival: 'the Sarajevo Film Festival',
    sport: 'football',
    wonder: 'the Old Bridge in Mostar',
    pride: 'our hospitality',
  },
  ALB: {
    dish: ['tavë kosi', 'tavë kosi (lamb baked in yoghurt)'],
    drink: ['raki', 'raki (grape brandy)'],
    festival: ['Dita e Verës', 'Dita e Verës (the Summer Day festival)'],
    sport: 'football',
    wonder: 'the old town of Berat',
    pride: ['besa', 'besa (our word of honour)'],
  },
  LTU: {
    dish: ['cepelinai', 'cepelinai (potato dumplings)'],
    drink: ['gira', 'gira (a bread drink)'],
    festival: ['Joninės', 'Joninės (Midsummer)'],
    sport: 'basketball',
    wonder: 'the Curonian Spit',
    pride: 'our amber',
  },
  SVN: {
    dish: ['potica', 'potica (a nut roll)'],
    drink: 'Slovenian wine',
    festival: ['Kurentovanje', 'Kurentovanje (the carnival of Ptuj)'],
    sport: 'basketball',
    wonder: 'Lake Bled',
    pride: 'our beekeeping',
  },
  LVA: {
    dish: 'grey peas with bacon',
    drink: 'Riga Black Balsam',
    festival: ['Jāņi', 'Jāņi (Midsummer)'],
    sport: 'ice hockey',
    wonder: 'the old town of Riga',
    pride: 'our Song and Dance Festival',
  },
  MKD: {
    dish: ['tavče gravče', 'tavče gravče (baked beans)'],
    drink: ['rakija', 'rakija (fruit brandy)'],
    festival: 'the Ohrid Summer Festival',
    sport: 'handball',
    wonder: 'Lake Ohrid',
    pride: 'our ajvar',
  },
  EST: {
    dish: 'black rye bread',
    drink: ['kali', 'kali (a bread drink)'],
    festival: 'the Song Festival',
    sport: 'basketball',
    wonder: 'the old town of Tallinn',
    pride: 'Skype, which was made here',
  },
  MNE: {
    dish: ['njeguški pršut', 'Njeguši ham'],
    drink: 'Vranac wine',
    festival: 'the Mimosa Festival in Herceg Novi',
    sport: 'water polo',
    wonder: 'the Bay of Kotor',
    pride: 'our mountains',
  },
  MLT: {
    dish: ['pastizzi', 'pastizzi (cheese pastries)'],
    drink: 'Kinnie',
    festival: 'the village festas',
    sport: 'football',
    wonder: 'the Blue Grotto',
    pride: 'our ancient temples',
  },
  ISL: {
    dish: ['kjötsúpa', 'kjötsúpa (lamb soup)'],
    drink: ['brennivín', 'brennivín (the local schnapps)'],
    festival: ['Þorrablót', 'Þorrablót (the midwinter feast)'],
    sport: 'handball',
    wonder: 'Gullfoss waterfall',
    pride: 'our sagas',
    proverb: ['Þetta reddast', 'It will all work out'],
  },

  // Oceania
  AUS: {
    dish: 'meat pies',
    drink: 'Australian shiraz',
    festival: "New Year's Eve in Sydney",
    sport: 'Aussie rules football',
    wonder: 'the Great Barrier Reef',
    pride: 'our beaches',
    proverb: "She'll be right",
  },
  PNG: {
    dish: ['mumu', 'mumu (an earth-oven feast)'],
    drink: 'highland coffee',
    festival: 'the Goroka Show',
    sport: 'rugby league',
    wonder: 'the Sepik River',
    pride: 'our eight hundred languages',
  },
  NZL: {
    dish: ['hāngī', 'hāngī (food cooked in an earth oven)'],
    drink: ['L&P', 'L&P lemonade'],
    festival: ['Matariki', 'Matariki (the Māori New Year)'],
    sport: 'rugby',
    wonder: 'Milford Sound',
    pride: 'the All Blacks',
    proverb: ['Whaowhia te kete mātauranga', 'Fill the basket of knowledge'],
  },
  FJI: {
    dish: ['kokoda', 'kokoda (raw fish in coconut)'],
    drink: 'kava',
    festival: 'the Hibiscus Festival',
    sport: 'rugby sevens',
    wonder: 'the Yasawa Islands',
    pride: 'our Olympic sevens gold',
  },
};
