import type { Language } from '../phrases.ts';
import { EN_COUNTRIES } from './en-countries.ts';

/**
 * English: spoken wherever `SPOKEN` does not name a language, and the shape
 * every other file follows. Its lines are their own meaning.
 */
const EN: Language = {
  locale: 'en',
  name: 'English',
  join: ' ',
  compass: [
    'to the north', 'to the northeast', 'to the east', 'to the southeast',
    'to the south', 'to the southwest', 'to the west', 'to the northwest',
  ],
  lines: {
    morning: ['Good morning!', 'Morning!', "Morning! Lovely start to the day, isn't it?", 'Oh, hello! Good morning to you.'],
    afternoon: ['Good afternoon!', 'Hello there!', 'Afternoon!', 'Oh, hi! Nice afternoon, this.'],
    evening: ['Good evening!', 'Evening!', 'Hello! Nice evening for a walk.', 'Oh, good evening to you.'],
    night: ["Good evening! It's late, isn't it?", "Oh! You gave me a fright. Hello!", "Hello! Out for a night walk?", "Evening! Or is it morning already?"],
    again: ['Oh, you again! Hello!', 'Back again? Nice to see you.', 'Hello again!', "We've met! Still exploring?", "Ah, it's you! Did you find your way?"],
    welcome: [
      'Welcome to {town}!',
      'This is {town}. Are you visiting?',
      'First time in {town}?',
      "You've picked a good day to see {town}.",
      'Welcome, welcome! {town} is glad to have you.',
      "So, what brings you to {town}?",
    ],
    capitalHere: [
      '{town} is the capital of our country.',
      'This is the capital, you know. Everything happens in {town}.',
      'The government sits here in {town}. Lots of important people in suits.',
      "Being the capital, {town} never really sleeps.",
    ],
    capitalThere: [
      "Our capital is {capital}. It's worth a visit.",
      'Have you been to {capital} yet? That is our capital.',
      'People in {capital} think they run the country. Well, they do.',
      "{capital} is bigger, but I'd rather live here.",
    ],
    big: [
      "This is a big city. It's easy to get lost here!",
      'So many people! You could live here all your life and not know every street.',
      'The traffic here, honestly. But there is always something going on.',
      "A big city like this never stops. I love it, mostly.",
    ],
    middling: [
      'Not a big town, not a small one. Just right.',
      "Big enough to have everything, small enough to walk it.",
      "It's a nice size, {town}. You'll see it all in a day or two.",
      'Everybody complains it is too quiet, and nobody ever leaves.',
    ],
    small: [
      "It's a small place. Everybody knows everybody here.",
      "Small town. If you sneeze, the whole street says bless you.",
      'Not much happens in {town}, and we like it that way.',
      "You're the most exciting thing to happen here all week!",
    ],
    coast: [
      'We live by the water here. The fish is very good.',
      'Go and look at the water. It is different every day.',
      "Smell that? That's the sea. You never get tired of it.",
      'The boats go out early and come back with the best fish you ever had.',
    ],
    inland: [
      'We are far from the sea, but the land here is beautiful.',
      "No beach here, I'm afraid. But look at those fields.",
      "The sea? Never seen it, to be honest. It's a long way.",
      'Out here the land is everything. Good soil, good people.',
    ],
    high: [
      "We're high up here. Take it slowly, the air is thin.",
      'Up in the hills like this, the view is the best thing we have.',
      "You'll get strong legs living up here. Nothing is flat.",
      "Mind your breath! The mountains take some getting used to.",
    ],
    snowy: [
      'Snow nine months a year. The other three, we complain about the mud.',
      "Everything is white out here. You'll want better boots than those.",
      "We don't mind the cold. It keeps the tourists away. Present company excepted!",
      'When the snow is fresh, it is so quiet you can hear yourself think.',
    ],
    forest: [
      'The woods go on for days round here. Stay on the path!',
      'Go for a walk in the forest. It clears the head.',
      'We pick mushrooms and berries out there every autumn.',
      "Trees, trees and more trees. I wouldn't live anywhere else.",
    ],
    desert: [
      "Out here it's sand as far as you can see.",
      'Drink plenty of water. The desert does not forgive.',
      'The nights in the desert are cold, you know. People never believe it.',
      'Wait for the stars tonight. Out here there are millions of them.',
    ],
    plains: [
      "It's flat for miles. You can see the weather coming a day away.",
      'Big sky out here. Nothing to stop the wind.',
      'Good grazing land, all of it. Watch out for the herds.',
      "The grass goes on forever. It's like a green sea.",
    ],
    tropical: [
      'Everything grows here. Plant a stick and it becomes a tree.',
      'When the rain comes here, it really comes. Then it stops, just like that.',
      "Try the fruit from the market. You've never tasted anything like it.",
      "It's green all year round. Winter? What's winter?",
    ],
    landmark: [
      "Don't miss {landmark}! It's about {km} km {dir}.",
      "Have you seen {landmark}? It's {km} km {dir}, worth every step.",
      "Everyone goes to {landmark}. It's about {km} km {dir}.",
      "If you have a free day, {landmark} is {km} km {dir}. People come from all over.",
    ],
    landmarkNear: [
      "{landmark} is very close. You can't miss it!",
      'Have you been to {landmark} yet? It is just round the corner.',
      'We see {landmark} every day and it still takes my breath away.',
      "Go and see {landmark}, it's right here. Early, before the crowds.",
    ],
    plane: [
      "There's a little plane in a field {dir}, if you can fly!",
      'Somebody left a plane in a field {dir}. Fancy a flight?',
      "Can you fly? There's a plane waiting {dir}.",
      "If you want to see it all from above, there's a plane {dir}.",
    ],
    balloon: [
      "There's a hot-air balloon in a field {dir}! Imagine the view.",
      'Have you ever flown in a balloon? There is one {dir}.',
      "A balloon goes up from the field {dir}. It's magical.",
      "I've always wanted to try the balloon {dir}. I'm too scared!",
    ],
    boat: [
      "There's a boat by the water {dir}, if you want to go out.",
      "If you like the sea, there's a boat {dir}. Just give it back!",
      'A boat is tied up {dir}. You could sail anywhere from here.',
      "Take the boat {dir} and go and see the coast from the water.",
    ],
    hot: [
      "It's hot today! Find some shade.",
      "Phew, what heat! Drink some water, you look like you need it.",
      "It's too hot to do anything but sit in the shade.",
      'In this heat, even the dogs stay indoors.',
      "Hot, isn't it? And this is a cool day for us!",
    ],
    cold: [
      "Brr, it's cold today! Keep warm.",
      'Freezing! Where are your gloves?',
      "It's so cold my nose has stopped working.",
      'Cold enough for you? Wait till the wind picks up.',
      'Get yourself something hot to drink. It helps.',
    ],
    mild: [
      'What lovely weather today.',
      "Not too hot, not too cold. Perfect day, isn't it?",
      'A day like this, you want to be outside.',
      "Beautiful weather! Let's hope it lasts.",
      'Days like this are why we live here.',
    ],
    late: [
      "It's late. The streets are quiet at night.",
      'At this hour, only the cats are out. And us!',
      'I should be in bed. Why are you up?',
      'Look at the stars! You can see them best from here.',
    ],
    early: [
      "You're up early! The best part of the day.",
      'The bakery has just opened. Follow the smell!',
      "Early bird, eh? The town isn't even awake yet.",
      'I love the morning here, before the noise starts.',
    ],
    country: [
      '{country} is a beautiful country. Enjoy it!',
      'How do you like {country} so far?',
      "People say {country} is small on the map, but it's big in the heart.",
      "Travel all over {country}, if you can. Every corner is different.",
    ],
    dish: [
      "You have to try {dish} while you're here.",
      'Have you had {dish} yet? No? Oh, you must!',
      'Nobody makes {dish} like my mother.',
      "If you're hungry, get some {dish}. You won't regret it.",
    ],
    drink: [
      'Have some {drink} before you go. It is what we drink here.',
      'Nothing beats {drink} at the end of the day.',
      "You haven't lived until you've tried {drink}.",
      "Order {drink} like a local and they'll love you for it.",
    ],
    festival: [
      "You should come back for {festival}. It's wonderful!",
      'The best time to be here is {festival}. The whole country celebrates.',
      "Have you heard of {festival}? You'd love it.",
      'I count the days till {festival} every year.',
    ],
    sport: [
      "Here it's all about {sport}. Everybody plays.",
      'Do you like {sport}? Here we are crazy about it.',
      "On a match day, the whole town talks about nothing but {sport}.",
      'My whole family plays {sport}. Well, my grandmother just shouts.',
    ],
    wonder: [
      "If you have time, go and see {wonder}. It's unforgettable.",
      'Have you seen {wonder}? Nothing like it anywhere in the world.',
      "Everybody should see {wonder} once in their life.",
      "I went to see {wonder} as a child. I still dream about it.",
    ],
    pride: [
      'We are very proud of {pride}.',
      "Don't leave without learning about {pride}. It's who we are.",
      'You know what makes us proud? {pride}.',
      'Ask anyone here about {pride}, and they will talk for hours.',
    ],
    proverb: [
      'As we say here: “{proverb}”',
      'My grandmother always said: “{proverb}”',
      'There is a saying here: “{proverb}”',
      'You know the saying? “{proverb}”',
    ],
    chat: [
      "Where are you from? You're not from around here.",
      'Take your time and look around. There is a lot to see.',
      "Are you travelling alone? That's brave.",
      'You look like you have walked a long way.',
      'If you get lost, just ask. People here are friendly.',
      "What's the best place you've been so far?",
      'I have always wanted to travel. Maybe one day.',
      'Have you got a map? Everyone should carry a map.',
    ],
    childGreet: ['Hi!', 'Hello! Who are you?', "Hi! You're tall!", 'Hello, hello!'],
    childChat: [
      "I can run really fast! Want to see? Maybe later.",
      'Are you a tourist? My friend says tourists are rich.',
      "I lost a tooth yesterday! Look! Oh, you can't see it.",
      'My mum says I must not talk to strangers. But you look nice.',
      'Do you have a dog? I want a dog.',
      "When I grow up I'm going to fly a plane all round the world!",
      "Do you know any games? I know lots of games.",
    ],
    childBye: ['Bye bye!', 'Bye! Come back and play!', 'I have to go, my mum is calling!', 'See you later, alligator!'],
    grumpyGreet: ['Hm. What do you want?', 'Yes? What is it?', "Oh. Another tourist.", "Hmph. Hello, I suppose."],
    grumpyChat: [
      "It was better here before everybody started visiting.",
      'Everything costs twice what it used to.',
      "Don't block the pavement, please. People live here.",
      'The young people these days, always on their phones.',
      "I don't know why anybody comes here. Nothing to see.",
    ],
    grumpyBye: ['Right. Off you go, then.', "Well, don't let me keep you.", 'Hm. Goodbye.', 'Mind how you go. And shut the gate.'],
    elderChat: [
      'When I was young, this was all fields.',
      "I have lived here all my life. Eighty years! Can you believe it?",
      'Back in my day we walked everywhere. Look at you, you walk too. Good!',
      'My grandchildren live abroad now. They call every Sunday.',
      'Things change so fast. But the old streets stay the same.',
    ],
    chattyChat: [
      "Oh, I love meeting travellers! Tell me everything. No, wait, let me tell you first.",
      'My cousin went travelling once. He came back with a beard and a wife!',
      "I could talk all day, my friends say. They're not wrong!",
      'Have you eaten? You look hungry. Everybody looks hungry to me.',
      "Let me tell you a secret: the best view in town is from the hill behind the church.",
    ],
    bye: [
      'Goodbye! Have a good trip.',
      'Take care! Enjoy the rest of your journey.',
      'Safe travels, friend!',
      'Bye now! Come back and see us.',
      'Nice talking to you. Look after yourself!',
      "Off you go, then! There's so much to see.",
    ],
  },
  countries: EN_COUNTRIES,
};

export default EN;
