import type { Language } from '../phrases.ts';

const ES: Language = {
  locale: 'es',
  name: 'Spanish',
  join: ' ',
  compass: ['al norte', 'al noreste', 'al este', 'al sureste', 'al sur', 'al suroeste', 'al oeste', 'al noroeste'],
  lines: {
    morning: [
      ['¡Buenos días!', 'Good morning!'],
      ['¡Buen día!', 'Good day!'],
      ['¡Buenos días! Qué mañana tan bonita, ¿no?', 'Good morning! What a lovely morning, eh?'],
      ['¡Hola, buenos días!', 'Hello, good morning!'],
    ],
    afternoon: [
      ['¡Buenas tardes!', 'Good afternoon!'],
      ['¡Buenas!', 'Hi there!'],
      ['¡Hola! Qué buena tarde hace.', 'Hello! What a nice afternoon.'],
      ['¡Buenas tardes! ¿De paseo?', 'Good afternoon! Out for a stroll?'],
    ],
    evening: [
      ['¡Buenas noches!', 'Good evening!'],
      ['¡Hola, buenas noches!', 'Hello, good evening!'],
      ['¡Buenas noches! Buena hora para pasear.', 'Good evening! A good time for a walk.'],
      ['¡Buenas! Qué noche tan agradable.', 'Evening! What a pleasant night.'],
    ],
    night: [
      ['¡Buenas noches! Qué tarde es ya, ¿no?', "Good evening! It's late already, isn't it?"],
      ['¡Ay, qué susto! Hola.', 'Oh, you scared me! Hello.'],
      ['¡Hola! ¿Paseo nocturno?', 'Hello! A night walk?'],
      ['¡Buenas noches! ¿O ya son buenos días?', 'Good evening! Or is it good morning already?'],
    ],
    again: [
      ['¡Otra vez por aquí! ¡Hola!', 'Here again! Hello!'],
      ['¡Hola de nuevo!', 'Hello again!'],
      ['¡Ya nos conocemos! ¿Sigues explorando?', 'We have met! Still exploring?'],
      ['¡Ah, eres tú! ¿Encontraste el camino?', "Ah, it's you! Did you find your way?"],
      ['¡Qué gusto verte otra vez!', 'How nice to see you again!'],
    ],
    welcome: [
      ['¿Primera vez en {town}?', 'First time in {town}?'],
      ['Esto es {town}. ¿Estás de visita?', 'This is {town}. Are you visiting?'],
      ['Elegiste un buen día para conocer {town}.', 'You picked a good day to see {town}.'],
      ['¿Y qué te trae por {town}?', 'So what brings you to {town}?'],
      ['¡Te damos la bienvenida a {town}!', 'Welcome to {town}!'],
      ['{town} te recibe con los brazos abiertos.', '{town} welcomes you with open arms.'],
    ],
    capitalHere: [
      ['{town} es la capital, ¿sabías?', '{town} is the capital, did you know?'],
      ['Esto es la capital. Aquí en {town} pasa de todo.', 'This is the capital. Everything happens here in {town}.'],
      ['Aquí está el gobierno. Mucha gente importante de traje y corbata.', 'The government is here. Lots of important people in suits and ties.'],
      ['Como buena capital, {town} nunca duerme.', 'Like any proper capital, {town} never sleeps.'],
    ],
    capitalThere: [
      ['Nuestra capital es {capital}. Merece una visita.', 'Our capital is {capital}. It is worth a visit.'],
      ['¿Ya estuviste en {capital}? Es nuestra capital.', 'Have you been to {capital} yet? It is our capital.'],
      ['En {capital} creen que lo mandan todo. Y la verdad, sí.', 'In {capital} they think they run everything. And honestly, they do.'],
      ['{capital} es más grande, pero yo me quedo con esto.', "{capital} is bigger, but I'll take this place."],
    ],
    big: [
      ['Esta es una ciudad grande. ¡Aquí es fácil perderse!', "This is a big city. It's easy to get lost here!"],
      ['Cuánta gente. Puedes vivir aquí toda la vida y no conocer todas las calles.', 'So many people. You could live here all your life and not know every street.'],
      ['El tráfico es terrible, eso sí. Pero siempre hay algo que hacer.', 'The traffic is terrible, mind you. But there is always something to do.'],
      ['Una ciudad así no para nunca. Y me encanta, casi siempre.', 'A city like this never stops. And I love it, most of the time.'],
    ],
    middling: [
      ['Ni grande ni pequeña. Justo como debe ser.', 'Not big, not small. Just as it should be.'],
      ['Lo bastante grande para tener de todo, y lo bastante pequeña para ir a pie.', 'Big enough to have everything, small enough to walk.'],
      ['{town} tiene buen tamaño. En un par de días la conoces entera.', '{town} is a good size. You can see all of it in a couple of days.'],
      ['Todos dicen que aquí no pasa nada, y nadie se va.', 'Everybody says nothing happens here, and nobody leaves.'],
    ],
    small: [
      ['Es un lugar pequeño. Aquí todos nos conocemos.', "It's a small place. Everybody knows everybody here."],
      ['Aquí, si estornudas, toda la calle te dice «¡salud!».', 'Here, if you sneeze, the whole street says "bless you!"'],
      ['En {town} no pasa gran cosa, y así nos gusta.', 'Not much happens in {town}, and that is how we like it.'],
      ['¡Eres lo más emocionante que ha pasado aquí en toda la semana!', "You're the most exciting thing to happen here all week!"],
    ],
    coast: [
      ['Aquí vivimos junto al agua. El pescado es buenísimo.', 'We live by the water here. The fish is wonderful.'],
      ['Ve a mirar el agua. Cada día está distinta.', 'Go and look at the water. It is different every day.'],
      ['¿Hueles eso? Es el mar. Nunca cansa.', "Smell that? That's the sea. You never tire of it."],
      ['Los pescadores salen de madrugada y vuelven con el mejor pescado del mundo.', 'The fishermen go out at dawn and come back with the best fish in the world.'],
    ],
    inland: [
      ['Estamos lejos del mar, pero esta tierra es preciosa.', 'We are far from the sea, but this land is beautiful.'],
      ['Aquí no hay playa, lo siento. Pero mira qué campos.', 'No beach here, sorry. But look at those fields.'],
      ['¿El mar? Queda lejísimos. Aquí somos gente de tierra adentro.', 'The sea? It is miles away. We are inland people here.'],
      ['Aquí la tierra lo es todo. Buena tierra, buena gente.', 'Out here the land is everything. Good soil, good people.'],
    ],
    high: [
      ['Aquí estamos muy alto. Ve despacio, que falta el aire.', "We're high up here. Go slowly, the air is thin."],
      ['Desde aquí arriba, la vista es lo mejor que tenemos.', 'Up here, the view is the best thing we have.'],
      ['Viviendo aquí se ponen fuertes las piernas. Nada es plano.', 'Living up here makes your legs strong. Nothing is flat.'],
      ['¡Respira con calma! La altura cuesta al principio.', 'Breathe easy! The altitude is hard at first.'],
    ],
    snowy: [
      ['Nieve nueve meses al año. Los otros tres, barro.', 'Snow nine months a year. The other three, mud.'],
      ['Todo es blanco por aquí. Vas a necesitar mejores botas.', "Everything is white round here. You'll need better boots."],
      ['El frío no nos molesta. Espanta a los turistas... ¡menos a ti!', "We don't mind the cold. It scares the tourists off... except you!"],
      ['Con la nieve recién caída hay tanto silencio que se oyen los pensamientos.', 'When the snow is fresh it is so quiet you can hear your thoughts.'],
    ],
    forest: [
      ['El bosque sigue y sigue por aquí. ¡No te salgas del camino!', 'The forest goes on and on round here. Stay on the path!'],
      ['Date un paseo por el bosque. Despeja la cabeza.', 'Take a walk in the forest. It clears the head.'],
      ['Aquí los abuelos conocen cada árbol del bosque.', 'Here the old folks know every tree in the forest.'],
      ['Árboles, árboles y más árboles. No viviría en otro lugar.', "Trees, trees and more trees. I wouldn't live anywhere else."],
    ],
    desert: [
      ['Aquí es arena hasta donde alcanza la vista.', 'Out here it is sand as far as the eye can see.'],
      ['Bebe mucha agua. El desierto no perdona.', 'Drink plenty of water. The desert does not forgive.'],
      ['Las noches en el desierto son frías, ¿sabes? Nadie se lo cree.', 'Desert nights are cold, you know. Nobody believes it.'],
      ['Espera a la noche y mira las estrellas. Aquí hay millones.', 'Wait for night and look at the stars. There are millions out here.'],
    ],
    plains: [
      ['Todo llano, kilómetros y kilómetros. La lluvia se ve venir con un día de antelación.', 'Flat for miles and miles. You can see the rain coming a day ahead.'],
      ['Aquí el cielo es enorme. No hay nada que pare el viento.', 'The sky is huge out here. Nothing to stop the wind.'],
      ['Buena tierra de pastos. Cuidado con el ganado.', 'Good grazing land. Watch out for the cattle.'],
      ['La hierba no se acaba nunca. Es como un mar verde.', 'The grass never ends. It is like a green sea.'],
    ],
    tropical: [
      ['Aquí todo crece. Clavas un palo y te sale un árbol.', 'Everything grows here. Stick a twig in the ground and you get a tree.'],
      ['Cuando llueve aquí, llueve de verdad. Y luego para, así sin más.', 'When it rains here, it really rains. Then it stops, just like that.'],
      ['Prueba la fruta del mercado. No has probado nada igual.', "Try the fruit at the market. You've never tasted anything like it."],
      ['Aquí está verde todo el año. ¿Invierno? ¿Qué es eso?', 'It is green all year round here. Winter? What is that?'],
    ],
    landmark: [
      ['¡No te pierdas {landmark}! Está a unos {km} km {dir}.', "Don't miss {landmark}! It's about {km} km {dir}."],
      ['¿Ya viste {landmark}? Está a {km} km {dir}, y vale cada paso.', "Have you seen {landmark}? It's {km} km {dir}, and worth every step."],
      ['Todo el mundo va a ver {landmark}. Queda a unos {km} km {dir}.', "Everybody goes to see {landmark}. It's about {km} km {dir}."],
      ['Si tienes un día libre, {landmark} está a {km} km {dir}. Viene gente de todas partes.', 'If you have a free day, {landmark} is {km} km {dir}. People come from everywhere.'],
    ],
    landmarkNear: [
      ['{landmark} está muy cerca. ¡No tiene pérdida!', "{landmark} is very close. You can't miss it!"],
      ['¿Ya fuiste a ver {landmark}? Está aquí al lado.', 'Have you been to see {landmark}? It is right next door.'],
      ['Vemos {landmark} todos los días y todavía nos deja sin palabras.', 'We see {landmark} every day and it still leaves us speechless.'],
      ['Ve a ver {landmark}, está aquí mismo. Temprano, antes de que llegue la gente.', "Go and see {landmark}, it's right here. Early, before the crowds come."],
    ],
    plane: [
      ['Hay una avioneta en un campo {dir}, ¡si sabes pilotar!', "There's a light plane in a field {dir}, if you can fly!"],
      ['Alguien dejó una avioneta en un campo {dir}. ¿Te animas a volar?', 'Somebody left a plane in a field {dir}. Fancy a flight?'],
      ['¿Sabes volar? Hay una avioneta esperando {dir}.', "Can you fly? There's a plane waiting {dir}."],
      ['Si quieres verlo todo desde arriba, hay una avioneta {dir}.', "If you want to see it all from above, there's a plane {dir}."],
    ],
    balloon: [
      ['¡Hay un globo aerostático en un campo {dir}! Imagínate la vista.', "There's a hot-air balloon in a field {dir}! Imagine the view."],
      ['¿Has volado alguna vez en globo? Hay uno {dir}.', 'Have you ever flown in a balloon? There is one {dir}.'],
      ['Del campo que hay {dir} sale un globo. Es mágico.', 'A balloon goes up from the field {dir}. It is magical.'],
      ['Siempre he querido subir al globo que hay {dir}. ¡Pero me da miedo!', "I've always wanted to go up in the balloon {dir}. But I'm scared!"],
    ],
    boat: [
      ['Hay una lancha junto al agua {dir}, por si quieres salir.', "There's a boat by the water {dir}, if you want to go out."],
      ['Si te gusta el mar, hay una lancha {dir}. ¡Pero devuélvela!', "If you like the sea, there's a boat {dir}. But bring it back!"],
      ['Hay un bote amarrado {dir}. Desde aquí puedes navegar a cualquier parte.', 'A boat is tied up {dir}. From here you can sail anywhere.'],
      ['Toma el bote que hay {dir} y ve a ver la costa desde el agua.', 'Take the boat {dir} and see the coast from the water.'],
    ],
    hot: [
      ['¡Qué calor hace hoy! Busca un poco de sombra.', "It's so hot today! Find a bit of shade."],
      ['Uf, qué calor. Bebe agua, que te hace falta.', 'Phew, the heat. Drink some water, you need it.'],
      ['Con este calor no se puede hacer nada más que estar a la sombra.', 'In this heat you can do nothing but sit in the shade.'],
      ['Con este calor, hasta los perros se quedan en casa.', 'In this heat, even the dogs stay indoors.'],
      ['Calor, ¿eh? ¡Y eso que hoy está fresquito!', 'Hot, eh? And today is a cool day!'],
    ],
    cold: [
      ['¡Brr, hoy hace frío! Abrígate bien.', "Brr, it's cold today! Wrap up warm."],
      ['¡Qué frío! ¿Y tus guantes?', 'So cold! Where are your gloves?'],
      ['Hace tanto frío que ya no me siento la nariz.', "It's so cold I can't feel my nose any more."],
      ['¿Frío? Espera a que se levante el viento.', 'Cold? Wait till the wind picks up.'],
      ['Tómate algo calentito. Ayuda.', 'Have something hot to drink. It helps.'],
    ],
    mild: [
      ['Qué buen tiempo hace hoy.', 'What lovely weather today.'],
      ['Ni frío ni calor. Un día perfecto, ¿verdad?', "Not cold, not hot. A perfect day, isn't it?"],
      ['Con un día así, dan ganas de estar en la calle.', 'On a day like this you want to be outside.'],
      ['¡Qué día tan bonito! Ojalá dure.', 'What a beautiful day! Let us hope it lasts.'],
      ['Por días como este vivimos aquí.', 'Days like this are why we live here.'],
    ],
    late: [
      ['Ya es tarde. Por la noche las calles están tranquilas.', "It's late. The streets are quiet at night."],
      ['A estas horas solo andan los gatos. ¡Y nosotros!', 'At this hour only the cats are out. And us!'],
      ['Yo ya debería estar en la cama. ¿Y tú qué haces por aquí?', 'I should be in bed by now. And what are you doing out here?'],
      ['Mira las estrellas. Desde aquí se ven mejor que en ningún otro lugar.', 'Look at the stars. You see them better from here than anywhere.'],
    ],
    early: [
      ['¡Qué temprano! Es la mejor hora del día.', "You're up early! The best time of day."],
      ['La panadería acaba de abrir. ¡Sigue el olor!', 'The bakery has just opened. Follow the smell!'],
      ['Madrugando, ¿eh? Aquí todavía no se ha despertado nadie.', "Up early, eh? Nobody's awake here yet."],
      ['Me encanta la mañana aquí, antes de que empiece el ruido.', 'I love the mornings here, before the noise starts.'],
    ],
    country: [
      ['¿Qué tal te está tratando {country}?', 'How is {country} treating you?'],
      ['Te va a encantar {country}, ya verás.', "You're going to love {country}, you'll see."],
      ['{country} tiene de todo, ya verás. Cada rincón es distinto.', '{country} has everything, you will see. Every corner is different.'],
      ['Nací aquí y {country} me sigue sorprendiendo.', 'I was born here and {country} still surprises me.'],
    ],
    dish: [
      ['Tienes que probar {dish} mientras estés aquí.', "You have to try {dish} while you're here."],
      ['¿Ya probaste {dish}? ¿No? ¡Pues tienes que hacerlo!', 'Have you tried {dish} yet? No? Well, you must!'],
      ['Nadie prepara {dish} como mi abuela.', 'Nobody makes {dish} like my grandmother.'],
      ['Si tienes hambre, pide {dish}. No te vas a arrepentir.', "If you're hungry, order {dish}. You won't regret it."],
    ],
    drink: [
      ['Antes de irte, prueba {drink}. Es lo que tomamos aquí.', 'Before you go, try {drink}. It is what we drink here.'],
      ['Al final del día, no hay nada como {drink}.', 'At the end of the day, nothing beats {drink}.'],
      ['No sabes lo que es bueno hasta que pruebes {drink}.', "You don't know what's good until you've tried {drink}."],
      ['Pide {drink} como la gente de aquí y te van a querer.', "Order {drink} like the locals and they'll love you for it."],
    ],
    festival: [
      ['Tienes que volver para {festival}. ¡Es una maravilla!', "You have to come back for {festival}. It's wonderful!"],
      ['La mejor época para venir es durante {festival}.', 'The best time to come is during {festival}.'],
      ['¿Has oído hablar de {festival}? Te encantaría.', "Have you heard of {festival}? You'd love it."],
      ['Yo cuento los días que faltan para {festival}.', 'I count the days until {festival}.'],
    ],
    sport: [
      ['Aquí todo gira alrededor de {sport}.', 'Here everything revolves around {sport}.'],
      ['¿Te gusta {sport}? Aquí nos vuelve locos.', "Do you like {sport}? Here we're crazy about it."],
      ['Los días de partido, aquí solo se habla de una cosa: {sport}.', 'On match days, people here talk about one thing only: {sport}.'],
      ['Mi abuela no entiende {sport}, pero en los partidos grita más que nadie.', "My grandmother doesn't understand {sport}, but at matches she shouts loudest."],
    ],
    wonder: [
      ['Si tienes tiempo, ve a ver {wonder}. No se olvida nunca.', "If you have time, go and see {wonder}. You'll never forget it."],
      ['¿Ya viste {wonder}? No hay nada igual en el mundo.', 'Have you seen {wonder}? There is nothing like it in the world.'],
      ['Todo el mundo debería ver {wonder} una vez en la vida.', 'Everybody should see {wonder} once in their life.'],
      ['Mis padres me llevaron a ver {wonder} hace años. Todavía sueño con eso.', 'My parents took me to see {wonder} years ago. I still dream about it.'],
    ],
    pride: [
      ['Lo que más orgullo nos da aquí: {pride}.', 'What makes us proudest here: {pride}.'],
      ['No te vayas sin conocer {pride}. Es lo que somos.', "Don't leave without getting to know {pride}. It's who we are."],
      ['¿Sabes qué nos llena de orgullo? {pride}.', 'You know what fills us with pride? {pride}.'],
      ['Pregúntale a cualquiera por {pride} y te hablará durante horas.', 'Ask anyone about {pride} and they will talk for hours.'],
    ],
    proverb: [
      ['Como decimos aquí: «{proverb}»', 'As we say here: “{proverb}”'],
      ['Mi abuela siempre decía: «{proverb}»', 'My grandmother always said: “{proverb}”'],
      ['Aquí hay un dicho: «{proverb}»', 'There is a saying here: “{proverb}”'],
      ['¿Conoces el refrán? «{proverb}»', 'Do you know the saying? “{proverb}”'],
    ],
    chat: [
      ['¿De dónde eres? No eres de por aquí.', "Where are you from? You're not from around here."],
      ['Tómate tu tiempo y mira a tu alrededor. Hay mucho que ver.', 'Take your time and look around. There is a lot to see.'],
      ['¿Viajas sin compañía? Qué valiente.', "Travelling on your own? That's brave."],
      ['Parece que vienes de muy lejos.', 'You look like you have come a long way.'],
      ['Si te pierdes, pregunta. Aquí la gente es amable.', 'If you get lost, just ask. People are kind here.'],
      ['¿Cuál ha sido el mejor lugar hasta ahora?', "What's been the best place so far?"],
      ['Yo siempre he querido viajar. A ver si algún día.', 'I have always wanted to travel. Maybe one day.'],
      ['¿Llevas mapa? Siempre hay que llevar un mapa.', 'Have you got a map? You should always carry a map.'],
    ],
    childGreet: [
      ['¡Hola!', 'Hi!'],
      ['¡Hola! ¿Quién eres?', 'Hello! Who are you?'],
      ['¡Hola! ¡Eres gigante!', "Hi! You're a giant!"],
      ['¡Hola, hola!', 'Hello, hello!'],
    ],
    childChat: [
      ['¡Corro rapidísimo! ¿Quieres ver? Bueno, luego.', 'I run super fast! Want to see? Well, later.'],
      ['¿Eres turista? Mi amigo dice que los turistas son ricos.', 'Are you a tourist? My friend says tourists are rich.'],
      ['¡Ayer se me cayó un diente! ¡Mira! Ah, no se ve.', "I lost a tooth yesterday! Look! Oh, you can't see it."],
      ['Mi mamá dice que no hable con extraños. Pero tú pareces buena gente.', "My mum says I mustn't talk to strangers. But you seem nice."],
      ['¿Tienes perro? Yo quiero un perro.', 'Do you have a dog? I want a dog.'],
      ['¡Cuando crezca voy a dar la vuelta al mundo en avión!', "When I grow up I'm going to fly round the world!"],
      ['¿Sabes algún juego? Yo sé un montón.', 'Do you know any games? I know loads.'],
    ],
    childBye: [
      ['¡Chao, pescado!', 'Bye-bye, fishy!'],
      ['¡Adiós! ¡Vuelve a jugar!', 'Bye! Come back and play!'],
      ['¡Me tengo que ir, me llama mi mamá!', 'I have to go, my mum is calling!'],
      ['¡Adiós, adiós!', 'Bye, bye!'],
    ],
    grumpyGreet: [
      ['Mm. ¿Qué quieres?', 'Hm. What do you want?'],
      ['¿Sí? ¿Qué pasa?', "Yes? What's the matter?"],
      ['Ya. Más turistas.', 'Right. More tourists.'],
      ['Hmm. Hola, supongo.', 'Hmm. Hello, I suppose.'],
    ],
    grumpyChat: [
      ['Esto era mejor antes de que viniera todo el mundo.', 'This place was better before everybody started coming.'],
      ['Todo cuesta el doble que antes.', 'Everything costs twice what it used to.'],
      ['No te pares en medio, que aquí vive gente.', "Don't stand in the way, people live here."],
      ['Los jóvenes de hoy, todo el día con el teléfono.', 'Young people these days, on their phones all day.'],
      ['No sé a qué viene la gente aquí. No hay nada que ver.', "I don't know why people come here. There's nothing to see."],
    ],
    grumpyBye: [
      ['Pues nada. Sigue, sigue.', 'Well then. Off you go.'],
      ['No te entretengo más.', "I won't keep you."],
      ['Mm. Adiós.', 'Hm. Goodbye.'],
      ['Ve con cuidado. Y no pises las flores.', "Mind how you go. And don't step on the flowers."],
    ],
    elderChat: [
      ['Cuando yo era joven, todo esto era campo.', 'When I was young, all this was fields.'],
      ['Llevo aquí toda la vida. ¡Ochenta años! ¿Te lo puedes creer?', "I've been here all my life. Eighty years! Can you believe it?"],
      ['En mis tiempos íbamos a todas partes a pie. Tú también caminas. ¡Así me gusta!', 'In my day we walked everywhere. You walk too. That is what I like to see!'],
      ['Mis nietos viven fuera. Me llaman todos los domingos.', 'My grandchildren live abroad. They call me every Sunday.'],
      ['Todo cambia muy rápido. Pero las calles viejas siguen igual.', 'Everything changes so fast. But the old streets stay the same.'],
    ],
    chattyChat: [
      ['¡Ay, me encanta conocer viajeros! Cuéntamelo todo. No, espera, primero te cuento yo.', 'Oh, I love meeting travellers! Tell me everything. No, wait, let me go first.'],
      ['Mi primo se fue de viaje una vez. ¡Volvió con barba y con esposa!', 'My cousin went travelling once. He came back with a beard and a wife!'],
      ['Mis amigos dicen que puedo hablar todo el día. ¡Y tienen razón!', 'My friends say I could talk all day. And they are right!'],
      ['¿Ya comiste algo? Tienes cara de hambre. Bueno, yo a todo el mundo le veo cara de hambre.', 'Have you eaten? You look hungry. Well, everybody looks hungry to me.'],
      ['Te cuento un secreto: la mejor vista es desde el cerro detrás de la iglesia.', 'Let me tell you a secret: the best view is from the hill behind the church.'],
    ],
    bye: [
      ['¡Adiós! Buen viaje.', 'Goodbye! Have a good trip.'],
      ['¡Cuídate! Disfruta del resto del viaje.', 'Take care! Enjoy the rest of your trip.'],
      ['¡Que te vaya bien!', 'All the best to you!'],
      ['¡Hasta luego! Vuelve a visitarnos.', 'See you! Come back and visit us.'],
      ['Un gusto hablar contigo. ¡Cuídate mucho!', 'Lovely talking to you. Look after yourself!'],
      ['Bueno, sigue tu camino. ¡Hay mucho que ver!', "Well, off you go. There's so much to see!"],
    ],
  },
  countries: {
    // Each fact is a noun phrase with its own article where Spanish takes one ("la paella", "el mate"), so no template puts "a" or "de" in front of it.
    ESP: {
      dish: ['la tortilla de patatas', 'Spanish potato omelette'],
      drink: ['el vino de Rioja', 'Rioja wine'],
      festival: ['las Fallas de Valencia', 'the Fallas of Valencia'],
      sport: ['el fútbol', 'football'],
      wonder: ['la Alhambra de Granada', 'the Alhambra in Granada'],
      pride: ['el flamenco', 'flamenco'],
      proverb: ['Al mal tiempo, buena cara', 'Put a good face on bad weather'],
    },
    MEX: {
      dish: ['los tacos al pastor', 'tacos al pastor'],
      drink: ['el tequila', 'tequila'],
      festival: ['el Día de Muertos', 'the Day of the Dead'],
      sport: ['el fútbol', 'football'],
      wonder: ['Chichén Itzá', 'Chichén Itzá'],
      pride: ['el mariachi', 'mariachi music'],
      proverb: ['Más vale paso que dure y no trote que canse', 'Better a pace that lasts than a trot that tires'],
    },
    ARG: {
      dish: ['el asado', 'a proper asado barbecue'],
      drink: ['el mate', 'mate'],
      festival: ['la Fiesta de la Vendimia de Mendoza', 'the Mendoza Grape Harvest Festival'],
      sport: ['el fútbol', 'football'],
      wonder: ['el glaciar Perito Moreno', 'the Perito Moreno Glacier'],
      pride: ['el tango', 'the tango'],
      proverb: ['El que se quema con leche, ve una vaca y llora', 'Whoever gets burnt by milk cries at the sight of a cow'],
    },
    COL: {
      dish: ['la bandeja paisa', 'bandeja paisa'],
      drink: ['el café colombiano', 'Colombian coffee'],
      festival: ['el Carnaval de Barranquilla', 'the Barranquilla Carnival'],
      sport: ['el fútbol', 'football'],
      wonder: ['la ciudad amurallada de Cartagena', 'the walled city of Cartagena'],
      pride: ['la cumbia', 'cumbia music'],
      proverb: ['A caballo regalado no se le mira el colmillo', "Don't look a gift horse in the teeth"],
    },
    PER: {
      dish: ['el ceviche', 'ceviche'],
      drink: ['el pisco sour', 'pisco sour'],
      festival: ['el Inti Raymi', 'Inti Raymi, the Festival of the Sun'],
      sport: ['el fútbol', 'football'],
      wonder: ['Machu Picchu', 'Machu Picchu'],
      pride: ['la cocina peruana', 'Peruvian cooking'],
      proverb: ['Poco a poco se va lejos', 'Little by little you go far'],
    },
    VEN: {
      dish: ['las arepas', 'arepas'],
      drink: ['el papelón con limón', 'cane-sugar lemonade'],
      festival: ['los Diablos Danzantes de Yare', 'the Dancing Devils of Yare'],
      sport: ['el béisbol', 'baseball'],
      wonder: ['el Salto Ángel', 'Angel Falls'],
      pride: ['el joropo', 'joropo music'],
      proverb: ['Camarón que se duerme se lo lleva la corriente', 'The shrimp that falls asleep is swept away by the current'],
    },
    CHL: {
      dish: ['las empanadas de pino', 'beef empanadas'],
      drink: ['el mote con huesillo', 'mote con huesillo, a peach drink'],
      festival: ['las Fiestas Patrias', 'the September national holidays'],
      sport: ['el fútbol', 'football'],
      wonder: ['el desierto de Atacama', 'the Atacama Desert'],
      pride: ['la poesía de Neruda y Gabriela Mistral', 'the poetry of Neruda and Gabriela Mistral'],
      proverb: ['Más sabe el diablo por viejo que por diablo', 'The devil knows more from being old than from being the devil'],
    },
    ECU: {
      dish: ['el encebollado', 'encebollado, a fish soup'],
      drink: ['el canelazo', 'canelazo, a hot cinnamon drink'],
      festival: ['la Mama Negra de Latacunga', 'the Mama Negra festival of Latacunga'],
      sport: ['el ecuavóley', 'ecuavolley'],
      wonder: ['las islas Galápagos', 'the Galápagos Islands'],
      pride: ['los sombreros de paja toquilla', 'our toquilla straw hats'],
      proverb: ['El que no llora no mama', "The baby who doesn't cry doesn't get fed"],
    },
    GTM: {
      dish: ['el pepián', 'pepián stew'],
      drink: ['el atol de elote', 'sweet corn atole'],
      festival: ['la Semana Santa de Antigua', 'Holy Week in Antigua'],
      sport: ['el fútbol', 'football'],
      wonder: ['el lago de Atitlán', 'Lake Atitlán'],
      pride: ['los tejidos típicos', 'our handwoven textiles'],
      proverb: ['Árbol que nace torcido jamás su tronco endereza', 'A tree born crooked never straightens its trunk'],
    },
    CUB: {
      dish: ['la ropa vieja', 'ropa vieja'],
      drink: ['el mojito', 'a mojito'],
      festival: ['el Carnaval de Santiago de Cuba', 'the Santiago de Cuba Carnival'],
      sport: ['el béisbol', 'baseball'],
      wonder: ['el valle de Viñales', 'the Viñales Valley'],
      pride: ['el son cubano', 'Cuban son music'],
      proverb: ['No hay mal que por bien no venga', 'There is no harm that does not bring some good'],
    },
    BOL: {
      dish: ['las salteñas', 'salteñas'],
      drink: ['el api', 'api, a hot purple-corn drink'],
      festival: ['el Carnaval de Oruro', 'the Oruro Carnival'],
      sport: ['el fútbol', 'football'],
      wonder: ['el salar de Uyuni', 'the Uyuni salt flat'],
      pride: ['el teleférico de La Paz', 'the La Paz cable cars'],
      proverb: ['Dime con quién andas y te diré quién eres', "Tell me who you walk with and I'll tell you who you are"],
    },
    DOM: {
      dish: ['el mangú', 'mangú, mashed plantain'],
      drink: ['la mamajuana', 'mamajuana'],
      festival: ['el Carnaval de La Vega', 'the La Vega Carnival'],
      sport: ['el béisbol', 'baseball'],
      wonder: ['la isla Saona', 'Saona Island'],
      pride: ['el merengue', 'merengue'],
      proverb: ['Cada quien sabe dónde le aprieta el zapato', 'Everyone knows where their own shoe pinches'],
    },
    HND: {
      dish: ['las baleadas', 'baleadas'],
      drink: ['la horchata', 'horchata'],
      festival: ['la Feria Juniana de San Pedro Sula', 'the June Fair in San Pedro Sula'],
      sport: ['el fútbol', 'football'],
      wonder: ['las ruinas de Copán', 'the Maya ruins of Copán'],
      pride: ['la hospitalidad catracha', 'Honduran hospitality'],
      proverb: ['El que anda con lobos a aullar aprende', 'Whoever runs with wolves learns to howl'],
    },
    PRY: {
      dish: ['la sopa paraguaya', 'sopa paraguaya, a corn bread'],
      drink: ['el tereré', 'tereré, iced mate'],
      festival: ['la fiesta de San Juan', 'the feast of Saint John'],
      sport: ['el fútbol', 'football'],
      wonder: ['las ruinas jesuíticas de Trinidad', 'the Jesuit ruins of Trinidad'],
      pride: ['el arpa paraguaya', 'the Paraguayan harp'],
      proverb: ['A buen entendedor, pocas palabras bastan', 'A good listener needs few words'],
    },
    SLV: {
      dish: ['las pupusas', 'pupusas'],
      drink: ['la horchata de morro', 'morro-seed horchata'],
      festival: ['las Fiestas Agostinas', 'the August festivals'],
      sport: ['el fútbol', 'football'],
      wonder: ['el lago de Coatepeque', 'Lake Coatepeque'],
      pride: ['las playas de surf', 'our surfing beaches'],
      proverb: ['El que busca, encuentra', 'Whoever seeks, finds'],
    },
    NIC: {
      dish: ['el nacatamal', 'nacatamal'],
      drink: ['el pinolillo', 'pinolillo, a corn and cacao drink'],
      festival: ['la Gritería', 'La Gritería, the December festival'],
      sport: ['el béisbol', 'baseball'],
      wonder: ['la isla de Ometepe', 'Ometepe Island'],
      pride: ['la poesía de Rubén Darío', 'the poetry of Rubén Darío'],
      proverb: ['Del dicho al hecho hay mucho trecho', 'It is a long way from saying to doing'],
    },
    CRI: {
      dish: ['el gallo pinto', 'gallo pinto, rice and beans'],
      drink: ['el café tico', 'Costa Rican coffee'],
      festival: ['las fiestas de Palmares', 'the Palmares fiestas'],
      sport: ['el fútbol', 'football'],
      wonder: ['el volcán Arenal', 'the Arenal Volcano'],
      pride: ['las carretas pintadas', 'our painted oxcarts'],
      proverb: ['Más vale maña que fuerza', 'Skill beats strength'],
    },
    PAN: {
      dish: ['el sancocho', 'sancocho, a chicken soup'],
      drink: ['el café de Boquete', 'coffee from Boquete'],
      festival: ['el Carnaval de Las Tablas', 'the Las Tablas Carnival'],
      sport: ['el béisbol', 'baseball'],
      wonder: ['el Casco Viejo', 'the Casco Viejo, the old town'],
      pride: ['la pollera', 'the pollera, our national dress'],
      proverb: ['El que no arriesga no gana', 'Nothing ventured, nothing gained'],
    },
    URY: {
      dish: ['el chivito', 'the chivito sandwich'],
      drink: ['el mate', 'mate'],
      festival: ['el Carnaval uruguayo', 'the Uruguayan Carnival'],
      sport: ['el fútbol', 'football'],
      wonder: ['Colonia del Sacramento', 'Colonia del Sacramento'],
      pride: ['el candombe', 'candombe drumming'],
      proverb: ['Donde manda capitán, no manda marinero', 'Where the captain commands, the sailor does not'],
    },
    GNQ: {
      dish: ['el pepesup', 'pepper soup'],
      drink: ['el malamba', 'malamba, a sugar-cane drink'],
      sport: ['el fútbol', 'football'],
      wonder: ['el pico Basilé', 'Pico Basilé'],
      proverb: ['Más vale prevenir que curar', 'Better safe than sorry'],
    },
    PRI: {
      dish: ['el mofongo', 'mofongo'],
      drink: ['el coquito', 'coquito, a coconut eggnog'],
      festival: ['las Fiestas de la Calle San Sebastián', 'the San Sebastián Street Festival'],
      sport: ['el béisbol', 'baseball'],
      wonder: ['el bosque de El Yunque', 'the El Yunque rainforest'],
      pride: ['el coquí', 'the coquí, our little singing frog'],
      proverb: ['Cada oveja con su pareja', 'Every sheep with its mate'],
    },
  },
};

export default ES;
