import type { Language } from '../phrases.ts';

const FA: Language = {
  locale: 'fa',
  name: 'Persian',
  rtl: true,
  join: ' ',
  compass: [
    'به سمت شمال', 'به سمت شمال شرقی', 'به سمت شرق', 'به سمت جنوب شرقی',
    'به سمت جنوب', 'به سمت جنوب غربی', 'به سمت غرب', 'به سمت شمال غربی',
  ],
  lines: {
    morning: [
      ['صبح بخیر!', 'Good morning!'],
      ['صبح شما بخیر! چه صبح قشنگی.', 'Good morning to you! What a lovely morning.'],
      ['سلام، صبح بخیر!', 'Hello, good morning!'],
      ['به‌به، صبح بخیر! روزتان خوش.', 'Well, well, good morning! Have a nice day.'],
    ],
    afternoon: [
      ['روز بخیر!', 'Good day!'],
      ['سلام!', 'Hello!'],
      ['سلام علیکم!', 'Peace be upon you!'],
      ['سلام! چه بعدازظهر خوبی.', 'Hello! What a nice afternoon.'],
    ],
    evening: [
      ['عصر بخیر!', 'Good evening!'],
      ['سلام، عصرتان بخیر!', 'Hello, good evening to you!'],
      ['سلام! هوا برای قدم زدن عالی است.', 'Hello! Perfect weather for a stroll.'],
      ['به‌به، سلام! چه غروب قشنگی.', 'Well, hello! What a lovely sunset.'],
    ],
    night: [
      ['سلام! دیروقت است، نه؟', "Hello! It's late, isn't it?"],
      ['وای! ترساندید مرا. سلام!', 'Oh! You scared me. Hello!'],
      ['سلام! برای قدم زدن شبانه آمده‌اید؟', 'Hello! Out for a night walk?'],
      ['سلام! این وقت شب اینجا چه می‌کنید؟', 'Hello! What brings you out at this hour?'],
    ],
    again: [
      ['باز هم شما! سلام!', 'You again! Hello!'],
      ['دوباره آمدید؟ خوشحالم که می‌بینمتان.', "Back again? I'm glad to see you."],
      ['سلام دوباره!', 'Hello again!'],
      ['همدیگر را دیده بودیم! هنوز در حال گشت‌وگذارید؟', "We've met! Still exploring?"],
    ],
    welcome: [
      ['به {town} خوش آمدید!', 'Welcome to {town}!'],
      ['اینجا {town} است. برای دیدن آمده‌اید؟', 'This is {town}. Have you come to look around?'],
      ['اولین بار است که به {town} می‌آیید؟', 'Is this your first time in {town}?'],
      ['خوش آمدید، قدمتان روی چشم! اینجا {town} است.', 'Welcome, you are most welcome! This is {town}.'],
      ['چه روز خوبی را برای دیدن {town} انتخاب کرده‌اید.', "What a good day you've chosen to see {town}."],
      ['خب، چه چیزی شما را به {town} آورده؟', 'So, what brings you to {town}?'],
    ],
    capitalHere: [
      ['{town} پایتخت کشور ماست.', '{town} is the capital of our country.'],
      ['اینجا پایتخت است. همه‌چیز در {town} اتفاق می‌افتد.', 'This is the capital. Everything happens in {town}.'],
      ['پایتخت است دیگر؛ همیشه شلوغ و پرجنب‌وجوش!', "It's the capital, after all: always busy and bustling!"],
      ['{town} پایتخت است و هیچ‌وقت نمی‌خوابد.', '{town} is the capital and never sleeps.'],
    ],
    capitalThere: [
      ['پایتخت ما {capital} است. ارزش دیدن دارد.', 'Our capital is {capital}. It is worth seeing.'],
      ['به {capital} رفته‌اید؟ پایتخت ماست.', 'Have you been to {capital}? It is our capital.'],
      ['{capital} بزرگ‌تر است، اما من اینجا را ترجیح می‌دهم.', "{capital} is bigger, but I'd rather be here."],
      ['اگر وقت کردید، سری به {capital} بزنید.', 'If you find the time, pay a visit to {capital}.'],
    ],
    big: [
      ['اینجا شهر بزرگی است. راحت گم می‌شوید!', "This is a big city. It's easy to get lost!"],
      ['چقدر آدم! یک عمر هم اینجا بمانید، همه‌ی کوچه‌ها را یاد نمی‌گیرید.', 'So many people! Live here a lifetime and you still would not know every lane.'],
      ['این ترافیک، واقعاً که! اما همیشه یک خبری هست.', 'This traffic, honestly! But there is always something going on.'],
      ['شهر بزرگ هیچ‌وقت نمی‌ایستد. من که دوستش دارم.', 'A big city never stops. I love it, myself.'],
    ],
    middling: [
      ['نه بزرگ است، نه کوچک. درست اندازه.', 'Not big, not small. Just the right size.'],
      ['همه‌چیز دارد، و پیاده هم می‌شود همه‌جایش را گشت.', 'It has everything, and you can still walk all of it.'],
      ['یکی دو روزه همه‌جای {town} را می‌بینید.', "You'll see all of {town} in a day or two."],
      ['همه می‌گویند اینجا خیلی آرام است، ولی هیچ‌کس هم نمی‌رود!', 'Everyone says it is too quiet here, yet nobody ever leaves!'],
    ],
    small: [
      ['اینجا جای کوچکی است. همه همدیگر را می‌شناسند.', 'This is a small place. Everybody knows everybody.'],
      ['اینجا عطسه کنید، کل کوچه می‌گوید عافیت باشد!', 'Sneeze here and the whole lane says bless you!'],
      ['در {town} اتفاق زیادی نمی‌افتد، ما هم همین را دوست داریم.', 'Not much happens in {town}, and that is how we like it.'],
      ['شما هیجان‌انگیزترین اتفاق این هفته‌اید!', 'You are the most exciting thing to happen this week!'],
    ],
    coast: [
      ['ما اینجا کنار آب زندگی می‌کنیم. ماهی‌اش عالی است.', 'We live by the water here. The fish is excellent.'],
      ['بروید دریا را ببینید. هر روز یک‌جور است.', 'Go and see the sea. It is different every day.'],
      ['بوی دریا را حس می‌کنید؟ آدم هیچ‌وقت از آن خسته نمی‌شود.', 'Can you smell the sea? You never tire of it.'],
      ['قایق‌ها صبح زود می‌روند و با تازه‌ترین ماهی برمی‌گردند.', 'The boats go out early and come back with the freshest fish.'],
    ],
    inland: [
      ['از دریا دوریم، اما اینجا سرزمین زیبایی است.', 'We are far from the sea, but this is a beautiful land.'],
      ['اینجا ساحل نداریم. اما آن دشت‌ها را ببینید!', 'No beach here. But look at those plains!'],
      ['دریا؟ راستش را بخواهید، خیلی دور است.', 'The sea? To tell the truth, it is very far away.'],
      ['اینجا زمین همه‌چیز است. خاک خوب، مردم خوب.', 'Here the land is everything. Good soil, good people.'],
    ],
    high: [
      ['اینجا خیلی بالاییم. آرام راه بروید، هوا رقیق است.', 'We are high up here. Walk slowly, the air is thin.'],
      ['در این کوهستان، بهترین چیزی که داریم منظره است.', 'Up in these mountains, the view is the best thing we have.'],
      ['اینجا زندگی کنید، پاهایتان قوی می‌شود. هیچ‌جا صاف نیست!', 'Live here and your legs get strong. Nothing is flat!'],
      ['مواظب نفستان باشید! به هوای کوهستان باید عادت کرد.', 'Mind your breath! Mountain air takes getting used to.'],
    ],
    snowy: [
      ['نه ماه از سال برف است. سه ماه دیگر هم از گل‌ولای می‌نالیم.', 'Snow nine months a year. The other three, we moan about the mud.'],
      ['همه‌جا سفید است. کفش محکم‌تری لازم دارید.', 'Everything is white. You need sturdier shoes.'],
      ['وقتی برف تازه می‌بارد، آن‌قدر ساکت است که صدای فکرتان را می‌شنوید.', 'When fresh snow falls, it is so quiet you can hear yourself think.'],
      ['سرما برای ما چیزی نیست. یک چای داغ و یک بخاری، تمام.', 'The cold is nothing to us. A hot tea and a stove, that is all.'],
    ],
    forest: [
      ['جنگل اینجا تمامی ندارد. از راه بیرون نروید!', 'The forest here never ends. Stay on the path!'],
      ['یک قدم در جنگل بزنید، سرتان سبک می‌شود.', 'Take a walk in the forest, it clears the head.'],
      ['هر پاییز می‌رویم قارچ و تمشک می‌چینیم.', 'Every autumn we go picking mushrooms and blackberries.'],
      ['درخت و درخت و باز هم درخت. جای دیگری را نمی‌خواهم.', "Trees and trees and more trees. I wouldn't want anywhere else."],
    ],
    desert: [
      ['اینجا تا چشم کار می‌کند، شن است.', 'Here there is sand as far as the eye can see.'],
      ['زیاد آب بخورید. بیابان کسی را نمی‌بخشد.', 'Drink plenty of water. The desert forgives no one.'],
      ['شب‌های کویر سرد است. کسی باور نمی‌کند.', 'Desert nights are cold. Nobody believes it.'],
      ['امشب منتظر ستاره‌ها بمانید. اینجا میلیون‌ها ستاره پیداست.', 'Wait for the stars tonight. Millions of them show here.'],
    ],
    plains: [
      ['کیلومترها دشت صاف. آمدن باران را از یک روز قبل می‌بینید.', 'Flat plain for miles. You see the rain coming a day ahead.'],
      ['آسمان اینجا بزرگ است. هیچ‌چیز جلوی باد را نمی‌گیرد.', 'The sky is big here. Nothing stops the wind.'],
      ['همه‌اش چراگاه است. مواظب گله‌ها باشید.', "It's all pasture. Watch out for the herds."],
      ['علف تا بی‌نهایت می‌رود. مثل یک دریای سبز.', 'The grass goes on forever. Like a green sea.'],
    ],
    tropical: [
      ['اینجا همه‌چیز سبز می‌شود. یک چوب بکارید، درخت می‌شود.', 'Everything grows here. Plant a stick and it becomes a tree.'],
      ['باران که می‌آید، حسابی می‌آید. بعد یک‌دفعه بند می‌آید.', 'When the rain comes, it really comes. Then it stops all at once.'],
      ['میوه‌های بازار را امتحان کنید. مثلش را نخورده‌اید.', "Try the fruit at the market. You've never tasted the like."],
      ['اینجا تمام سال سبز است. زمستان؟ زمستان دیگر چیست؟', 'It is green all year. Winter? What is winter?'],
    ],
    landmark: [
      ['{landmark} را از دست ندهید! از اینجا حدود {km} کیلومتر {dir} است.', "Don't miss {landmark}! It's about {km} km from here, {dir}."],
      ['تا حالا {landmark} را دیده‌اید؟ حدود {km} کیلومتر {dir}؛ ارزش هر قدمش را دارد.', "Have you seen {landmark}? About {km} km {dir}, worth every step."],
      ['همه به دیدن {landmark} می‌روند. حدود {km} کیلومتر {dir} است.', 'Everyone goes to see {landmark}. It is about {km} km {dir}.'],
      ['اگر آثار تاریخی دوست دارید، {landmark} را ببینید؛ {km} کیلومتر {dir}.', 'If you like old things, see {landmark}: {km} km {dir}.'],
    ],
    landmarkNear: [
      ['{landmark} خیلی نزدیک است. حتماً پیدایش می‌کنید!', "{landmark} is very close. You'll find it for sure!"],
      ['به {landmark} سر زده‌اید؟ همین بغل است.', 'Have you been to {landmark}? It is right next door.'],
      ['هر روز {landmark} را می‌بینیم و هنوز نفسمان بند می‌آید.', 'We see {landmark} every day and it still takes our breath away.'],
      ['بروید {landmark} را ببینید، همین‌جاست. صبح زود، قبل از شلوغی.', 'Go and see {landmark}, it is right here. Early, before the crowds.'],
    ],
    plane: [
      ['یک هواپیمای کوچک {dir} توی یک مزرعه هست، اگر خلبانی بلدید!', "There's a little plane in a field {dir}, if you can fly!"],
      ['یکی هواپیمایش را {dir} در یک مزرعه گذاشته. پرواز می‌کنید؟', 'Somebody left their plane in a field {dir}. Care to fly?'],
      ['پرواز بلدید؟ یک هواپیما {dir} منتظر است.', 'Can you fly? A plane is waiting {dir}.'],
      ['اگر می‌خواهید همه‌جا را از بالا ببینید، یک هواپیما {dir} هست.', "If you want to see it all from above, there's a plane {dir}."],
    ],
    balloon: [
      ['یک بالن هوای گرم {dir} توی مزرعه هست! منظره را تصور کنید.', "There's a hot-air balloon in a field {dir}! Imagine the view."],
      ['تا حالا سوار بالن شده‌اید؟ یکی {dir} هست.', 'Have you ever ridden in a balloon? There is one {dir}.'],
      ['از مزرعه‌ای {dir} بالن بلند می‌شود. جادویی است.', 'A balloon goes up from a field {dir}. It is magical.'],
      ['همیشه دلم می‌خواست سوار آن بالن شوم. ولی می‌ترسم!', "I've always wanted to ride that balloon. But I'm scared!"],
    ],
    boat: [
      ['یک قایق {dir} کنار آب هست، اگر می‌خواهید بروید روی آب.', "There's a boat by the water {dir}, if you want to go out."],
      ['اگر دریا دوست دارید، یک قایق {dir} هست. فقط پسش بدهید!', "If you love the sea, there's a boat {dir}. Just bring it back!"],
      ['یک قایق {dir} بسته‌اند. از اینجا می‌شود هر جا رفت.', 'A boat is tied up {dir}. From here you can go anywhere.'],
      ['با قایق بروید و ساحل را از روی آب ببینید.', 'Take the boat and see the coast from the water.'],
    ],
    hot: [
      ['امروز هوا گرم است! یک سایه پیدا کنید.', "It's hot today! Find some shade."],
      ['اوف، چه گرمایی! کمی آب بخورید.', 'Phew, what heat! Drink some water.'],
      ['در این گرما فقط می‌شود زیر سایه نشست.', 'In this heat all you can do is sit in the shade.'],
      ['در این گرما حتی گربه‌ها هم بیرون نمی‌آیند.', 'In this heat even the cats stay in.'],
      ['گرم است، نه؟ یک شربت خنک بخورید، حالتان جا می‌آید.', "Hot, isn't it? Have a cool sherbet, it'll bring you back to life."],
    ],
    cold: [
      ['برر، امروز هوا سرد است! لباس گرم بپوشید.', "Brr, it's cold today! Dress warmly."],
      ['یخ زدیم! دستکش‌هایتان کو؟', "We're frozen! Where are your gloves?"],
      ['آن‌قدر سرد است که دماغم را حس نمی‌کنم.', "It's so cold I can't feel my nose."],
      ['سرد است؟ صبر کنید باد بیاید!', 'Cold? Wait till the wind comes!'],
      ['یک چای داغ بخورید، گرمتان می‌کند.', 'Have a hot tea, it will warm you up.'],
    ],
    mild: [
      ['امروز چه هوای خوبی است.', 'What lovely weather today.'],
      ['نه گرم، نه سرد. روز عالی‌ای است، نه؟', "Not hot, not cold. A perfect day, isn't it?"],
      ['در چنین روزی آدم دلش می‌خواهد بیرون باشد.', 'On a day like this you want to be outside.'],
      ['چه هوایی! امیدوارم همین‌طور بماند.', 'What weather! I hope it stays like this.'],
      ['برای همین روزهاست که اینجا زندگی می‌کنیم.', 'Days like this are why we live here.'],
    ],
    late: [
      ['دیروقت است. شب‌ها خیابان‌ها آرام‌اند.', "It's late. The streets are quiet at night."],
      ['این وقت شب فقط گربه‌ها بیرون‌اند. و ما!', 'At this hour only the cats are out. And us!'],
      ['من باید الان خواب باشم. شما چرا بیدارید؟', 'I should be asleep by now. Why are you up?'],
      ['ستاره‌ها را ببینید! از اینجا بهتر از هر جایی پیدا هستند.', 'Look at the stars! You see them best from here.'],
    ],
    early: [
      ['سحرخیزید! بهترین وقت روز است.', 'An early riser! The best time of the day.'],
      ['نانوایی تازه باز کرده. دنبال بوی نان تازه بروید!', 'The bakery has just opened. Follow the smell of fresh bread!'],
      ['سحرخیز باش تا کامروا باشی، نه؟ شهر هنوز بیدار نشده.', "Rise early and you'll prosper, right? The town isn't awake yet."],
      ['صبح‌های اینجا را، قبل از شلوغی، خیلی دوست دارم.', 'I love the mornings here, before the bustle.'],
    ],
    country: [
      ['{country} کشور زیبایی است. لذت ببرید!', '{country} is a beautiful country. Enjoy it!'],
      ['{country} را تا حالا چطور دیدید؟', 'How have you found {country} so far?'],
      ['تا می‌توانید در {country} سفر کنید. هر گوشه‌اش یک‌جور است.', 'Travel around {country} as much as you can. Every corner is different.'],
      ['{country} سرزمین چهار فصل است.', '{country} is a land of four seasons.'],
    ],
    dish: [
      ['{dish} را حتماً امتحان کنید.', 'You must try {dish}.'],
      ['هنوز {dish} نخورده‌اید؟ نه؟ حیف است!', "You haven't had {dish} yet? No? What a shame!"],
      ['هیچ‌کس مثل مادرم {dish} نمی‌پزد.', 'Nobody cooks {dish} like my mother.'],
      ['اگر گرسنه‌اید، {dish} بخورید. پشیمان نمی‌شوید.', "If you're hungry, have {dish}. You won't regret it."],
    ],
    drink: [
      ['قبل از رفتن کمی {drink} بنوشید. اینجا همین را می‌نوشیم.', 'Have some {drink} before you go. It is what we drink here.'],
      ['آخر روز هیچ‌چیز مثل {drink} نمی‌چسبد.', 'Nothing hits the spot like {drink} at the end of the day.'],
      ['تا {drink} را امتحان نکنید، نمی‌دانید چه از دست داده‌اید.', "Until you try {drink}, you don't know what you've been missing."],
      ['مثل آدم‌های محلی {drink} سفارش بدهید، همه عاشقتان می‌شوند.', "Order {drink} like a local and everyone will love you."],
    ],
    festival: [
      ['برای {festival} دوباره بیایید. معرکه است!', 'Come back for {festival}. It is marvellous!'],
      ['بهترین وقت اینجا بودن {festival} است. همه جشن می‌گیرند.', 'The best time to be here is {festival}. Everybody celebrates.'],
      ['اسم {festival} به گوشتان خورده؟ عاشقش می‌شوید.', "Have you heard of {festival}? You'd love it."],
      ['هر سال روزشماری می‌کنم تا {festival} برسد.', 'Every year I count the days till {festival}.'],
    ],
    sport: [
      ['اینجا همه دیوانه‌ی {sport} هستند.', 'Here everybody is crazy about {sport}.'],
      ['{sport} دوست دارید؟ ما اینجا عاشقش هستیم.', 'Do you like {sport}? We adore it here.'],
      ['روز مسابقه، کل شهر فقط از {sport} حرف می‌زند.', 'On match day the whole town talks of nothing but {sport}.'],
      ['کل خانواده‌ام اهل {sport} هستند. مادربزرگم فقط داد می‌زند!', 'My whole family is into {sport}. My grandmother just shouts!'],
    ],
    wonder: [
      ['اگر وقت دارید، {wonder} را ببینید. فراموش‌نشدنی است.', 'If you have time, see {wonder}. It is unforgettable.'],
      ['{wonder} را دیده‌اید؟ در دنیا مثلش نیست.', 'Have you seen {wonder}? There is nothing like it in the world.'],
      ['هر کسی باید یک بار در عمرش {wonder} را ببیند.', 'Everyone should see {wonder} once in their life.'],
      ['بچه که بودم {wonder} را دیدم. هنوز خوابش را می‌بینم.', 'I saw {wonder} as a child. I still dream of it.'],
    ],
    pride: [
      ['ما به {pride} خیلی افتخار می‌کنیم.', 'We are very proud of {pride}.'],
      ['نروید بی‌آنکه چیزی از {pride} بدانید. این ماییم.', "Don't leave without learning about {pride}. That is who we are."],
      ['می‌دانید به چه افتخار می‌کنیم؟ {pride}.', 'Do you know what we are proud of? {pride}.'],
      ['از هر کسی اینجا درباره‌ی {pride} بپرسید، ساعت‌ها حرف می‌زند.', 'Ask anyone here about {pride} and they will talk for hours.'],
    ],
    proverb: [
      ['اینجا می‌گوییم: «{proverb}»', 'Here we say: “{proverb}”'],
      ['مادربزرگم همیشه می‌گفت: «{proverb}»', 'My grandmother always said: “{proverb}”'],
      ['یک ضرب‌المثل داریم: «{proverb}»', 'We have a proverb: “{proverb}”'],
      ['این مثل را شنیده‌اید؟ «{proverb}»', 'Have you heard the saying? “{proverb}”'],
    ],
    chat: [
      ['اهل کجایید؟ اهل اینجا نیستید.', "Where are you from? You're not from here."],
      ['با حوصله اطراف را ببینید. چیزهای زیادی برای دیدن هست.', 'Take your time looking around. There is a lot to see.'],
      ['تنها سفر می‌کنید؟ دل‌وجرأت می‌خواهد.', 'Travelling alone? That takes nerve.'],
      ['به نظر می‌رسد راه درازی آمده‌اید.', 'It looks like you have come a long way.'],
      ['اگر گم شدید، بپرسید. مردم اینجا مهربان‌اند.', 'If you get lost, ask. People here are kind.'],
      ['تا حالا بهترین جایی که رفته‌اید کجا بوده؟', "What's the best place you've been so far?"],
      ['بفرمایید یک چای با هم بخوریم!', 'Please, come and have a tea with me!'],
    ],
    childGreet: [
      ['سلام!', 'Hi!'],
      ['سلام! تو کی هستی؟', 'Hi! Who are you?'],
      ['سلام! چقدر قدت بلند است!', "Hi! You're so tall!"],
      ['سلام سلام!', 'Hello, hello!'],
    ],
    childChat: [
      ['من خیلی تند می‌دوم! می‌خواهی ببینی؟', 'I run really fast! Want to see?'],
      ['تو توریستی؟ دوستم می‌گوید توریست‌ها پولدارند.', 'Are you a tourist? My friend says tourists are rich.'],
      ['دیروز دندانم افتاد! ببین! آخ، نمی‌بینی.', "My tooth fell out yesterday! Look! Oh, you can't see it."],
      ['مامانم می‌گوید با غریبه‌ها حرف نزن. ولی تو مهربانی.', 'Mum says not to talk to strangers. But you are nice.'],
      ['تو سگ داری؟ من یک سگ می‌خواهم.', 'Do you have a dog? I want a dog.'],
      ['بزرگ که شدم، با هواپیما دور دنیا را می‌گردم!', "When I grow up, I'll fly all round the world!"],
      ['قایم‌باشک بازی می‌کنی؟ تو چشم بگذار!', "Want to play hide-and-seek? You're it!"],
    ],
    childBye: [
      ['خداحافظ!', 'Bye!'],
      ['بای بای!', 'Bye bye!'],
      ['باید بروم، مامانم صدایم می‌کند!', 'I have to go, my mum is calling!'],
      ['خداحافظ! باز بیا بازی کنیم!', "Bye! Come back and let's play!"],
    ],
    grumpyGreet: [
      ['هوم. چه می‌خواهید؟', 'Hm. What do you want?'],
      ['بله؟ چه شده؟', "Yes? What's the matter?"],
      ['اِ. یک توریست دیگر.', 'Huh. Another tourist.'],
      ['هوم. سلام، لابد.', 'Hm. Hello, I suppose.'],
    ],
    grumpyChat: [
      ['قبل از این‌که همه بیایند، اینجا بهتر بود.', 'It was better here before everyone started coming.'],
      ['همه‌چیز دو برابر شده. حتی نان!', 'Everything costs double. Even bread!'],
      ['جلوی پیاده‌رو را نگیرید. اینجا آدم زندگی می‌کند.', "Don't block the pavement. People live here."],
      ['این جوان‌های امروزی، همه‌اش سرشان توی گوشی است.', 'Young people today, heads always in their phones.'],
      ['نمی‌دانم چرا مردم می‌آیند اینجا. چیزی برای دیدن نیست.', "I don't know why people come here. There's nothing to see."],
    ],
    grumpyBye: [
      ['خب. بفرمایید بروید.', 'Right. Off you go, then.'],
      ['معطلتان نمی‌کنم.', "I won't keep you."],
      ['هوم. خداحافظ.', 'Hm. Goodbye.'],
      ['مواظب باشید. در را هم ببندید.', 'Watch your step. And shut the door.'],
    ],
    elderChat: [
      ['جوان که بودم، اینجا همه‌اش مزرعه بود.', 'When I was young, all this was farmland.'],
      ['تمام عمرم اینجا بوده‌ام. هشتاد سال! باورتان می‌شود؟', 'I have been here all my life. Eighty years! Can you believe it?'],
      ['زمان ما همه‌جا را پیاده می‌رفتیم.', 'In our day we walked everywhere.'],
      ['نوه‌هایم خارج‌اند. هر جمعه زنگ می‌زنند.', 'My grandchildren live abroad. They call every Friday.'],
      ['همه‌چیز خیلی زود عوض می‌شود. اما کوچه‌های قدیمی همان‌اند.', 'Everything changes so fast. But the old lanes are the same.'],
    ],
    chattyChat: [
      ['وای، عاشق آشنایی با مسافرهام! همه‌چیز را تعریف کنید. نه، صبر کنید، اول من بگویم.', 'Oh, I love meeting travellers! Tell me everything. No, wait, let me go first.'],
      ['پسرخاله‌ام یک بار رفت سفر. با ریش و یک همسر برگشت!', 'My cousin went travelling once. Came back with a beard and a spouse!'],
      ['دوستانم می‌گویند می‌توانم تمام روز حرف بزنم. بی‌راه هم نمی‌گویند!', "My friends say I could talk all day. They're not wrong!"],
      ['غذا خورده‌اید؟ گرسنه به نظر می‌رسید. بفرمایید خانه‌ی ما!', "Have you eaten? You look hungry. Come to our house!"],
      ['یک راز بگویم؟ بهترین منظره‌ی شهر از بالای تپه است.', 'Shall I tell you a secret? The best view in town is from the top of the hill.'],
    ],
    bye: [
      ['خداحافظ! سفر به خیر.', 'Goodbye! Have a good journey.'],
      ['مواظب خودتان باشید! بقیه‌ی سفر خوش بگذرد.', 'Take care! Enjoy the rest of your trip.'],
      ['به سلامت، دوست من!', 'Go safely, my friend!'],
      ['خداحافظ! باز هم به ما سر بزنید.', 'Goodbye! Come and see us again.'],
      ['از هم‌صحبتی با شما خوشحال شدم. خدا نگهدار!', 'It was a pleasure talking to you. God keep you!'],
      ['بروید دیگر! چیزهای زیادی برای دیدن هست.', 'Off you go, then! There is so much to see.'],
    ],
  },
  countries: {
    // Every fact is a bare noun phrase; the templates set it as a subject, before «را» or a preposition's object, or after a colon, and never hang an ezafe or a suffix on it.
    IRN: {
      dish: ['قورمه‌سبزی', 'ghormeh sabzi'],
      drink: ['چای', 'tea'],
      festival: ['شب یلدا', 'Yalda Night'],
      sport: ['کشتی', 'wrestling'],
      wonder: ['کوه دماوند', 'Mount Damavand'],
      pride: ['شعر حافظ', 'the poetry of Hafez'],
      proverb: ['قطره قطره جمع گردد، وانگهی دریا شود', 'Drop by drop it gathers, and then it becomes a sea'],
    },
    AFG: {
      dish: ['قابلی پلو', 'Kabuli pulao'],
      drink: ['چای سبز', 'green tea'],
      festival: ['نوروز', 'Nowruz'],
      sport: ['کرکت', 'cricket'],
      wonder: ['بند امیر', 'the lakes of Band-e Amir'],
      pride: ['مهمان‌نوازی', 'our hospitality'],
      proverb: ['کوه به کوه نمی‌رسد، آدم به آدم می‌رسد', 'Mountain never meets mountain, but people meet again'],
    },
  },
};

export default FA;
