import type { Language } from '../phrases.ts';

/**
 * French: France and its overseas lands, Luxembourg, Monaco, Haiti and the
 * French-speaking countries of Africa. A stranger is *vous*; a child says
 * *tu*. No template puts a name after *à* or *de*, which would contract with
 * an article (*au*, *du*), and no line agrees with the speaker or listener.
 */
const FR: Language = {
  locale: 'fr',
  name: 'French',
  join: ' ',
  compass: ['au nord', 'au nord-est', "à l'est", 'au sud-est', 'au sud', 'au sud-ouest', "à l'ouest", 'au nord-ouest'],
  lines: {
    morning: [
      ['Bonjour !', 'Good morning!'],
      ['Bonjour ! Belle matinée, hein ?', "Good morning! Lovely morning, isn't it?"],
      ['Oh, bonjour ! Bien dormi ?', 'Oh, good morning! Sleep well?'],
      ['Salut ! Bonne journée qui commence !', "Hi! Here's to a good day!"],
    ],
    afternoon: [
      ['Bonjour !', 'Hello!'],
      ['Bon après-midi !', 'Good afternoon!'],
      ['Tiens, bonjour !', 'Oh, hello there!'],
      ['Salut ! Il fait bon cet après-midi, non ?', "Hi! Nice afternoon, isn't it?"],
    ],
    evening: [
      ['Bonsoir !', 'Good evening!'],
      ['Bonsoir ! Belle soirée pour se promener.', 'Good evening! Nice evening for a stroll.'],
      ['Oh, bonsoir à vous.', 'Oh, good evening to you.'],
      ['Bonsoir ! Vous profitez de la soirée ?', 'Good evening! Enjoying the evening?'],
    ],
    night: [
      ['Bonsoir ! Il est tard, non ?', "Good evening! It's late, isn't it?"],
      ["Oh ! Vous m'avez fait peur. Bonsoir !", 'Oh! You gave me a fright. Good evening!'],
      ['Bonsoir ! Une petite balade nocturne ?', 'Good evening! A little night walk?'],
      ['Bonsoir ! Ou bonjour, déjà ? Je ne sais plus.', "Good evening! Or is it good morning already? I've lost track."],
    ],
    again: [
      ['Tiens, encore vous ! Rebonjour !', 'Well, you again! Hello again!'],
      ['Vous revoilà ! Ça me fait plaisir.', "You're back! How nice."],
      ['Rebonjour !', 'Hello again!'],
      ['On se connaît ! Vous explorez toujours ?', "We've met! Still exploring?"],
      ["Ah, c'est vous ! Vous avez trouvé votre chemin ?", "Ah, it's you! Did you find your way?"],
    ],
    welcome: [
      ['Bienvenue à {town} !', 'Welcome to {town}!'],
      ["Ici, c'est {town}. Vous êtes de passage ?", 'This is {town}. Just passing through?'],
      ['Première fois à {town} ?', 'First time in {town}?'],
      ['Vous avez choisi une belle journée pour découvrir {town}.', "You've picked a fine day to discover {town}."],
      ['Bienvenue, bienvenue ! {town} vous ouvre ses portes.', 'Welcome, welcome! {town} opens its doors to you.'],
      ["Alors, qu'est-ce qui vous amène à {town} ?", 'So, what brings you to {town}?'],
    ],
    capitalHere: [
      ['{town} est la capitale de notre pays.', '{town} is the capital of our country.'],
      ["Ici, c'est la capitale, vous savez. Tout se passe à {town}.", 'This is the capital, you know. Everything happens in {town}.'],
      ['Le gouvernement siège ici, à {town}. Que des gens importants en costume !', 'The government sits here in {town}. Nothing but important people in suits!'],
      ['Capitale oblige, {town} ne dort jamais vraiment.', 'Being the capital, {town} never really sleeps.'],
    ],
    capitalThere: [
      ["Notre capitale, c'est {capital}. Elle vaut le détour.", "Our capital is {capital}. It's worth the trip."],
      ["Vous connaissez {capital} ? C'est notre capitale.", 'Do you know {capital}? That is our capital.'],
      ["À {capital}, ils croient diriger le pays. Bon, c'est vrai.", 'In {capital} they think they run the country. Well, they do.'],
      ['{capital} est plus grande, mais je préfère vivre ici.', "{capital} is bigger, but I'd rather live here."],
    ],
    big: [
      ["C'est une grande ville. On s'y perd facilement !", "It's a big city. You get lost here easily!"],
      ['Que de monde ! On peut vivre ici toute sa vie sans connaître toutes les rues.', 'So many people! You can live here all your life and not know every street.'],
      ['Ah, la circulation... Mais il se passe toujours quelque chose.', 'Ah, the traffic... But there is always something going on.'],
      ["Une ville comme ça, ça ne s'arrête jamais. J'adore. Enfin, presque.", 'A city like this never stops. I love it. Well, almost.'],
    ],
    middling: [
      ['Ni grande ni petite. Juste comme il faut.', 'Not big, not small. Just right.'],
      ['Assez grande pour tout avoir, assez petite pour tout faire à pied.', 'Big enough to have everything, small enough to walk everywhere.'],
      ['{town} a la taille idéale. En un jour ou deux, vous aurez tout vu.', "{town} is just the right size. In a day or two you'll have seen it all."],
      ["Tout le monde dit que c'est trop calme, et personne ne s'en va.", 'Everybody says it is too quiet, and nobody ever leaves.'],
    ],
    small: [
      ["C'est un petit endroit. Ici, tout le monde se connaît.", "It's a small place. Everybody knows everybody here."],
      ['Si vous éternuez ici, toute la rue vous dit « À vos souhaits ! »', 'Sneeze here and the whole street says "Bless you!"'],
      ["Il ne se passe pas grand-chose à {town}, et c'est très bien comme ça.", 'Not much happens in {town}, and that suits us fine.'],
      ["Vous êtes l'événement de la semaine, ici !", "You're the event of the week around here!"],
    ],
    coast: [
      ["Ici, on vit au bord de l'eau. Le poisson est excellent.", 'We live by the water here. The fish is excellent.'],
      ["Allez voir l'eau. Elle n'est jamais la même deux jours de suite.", 'Go and look at the water. It is never the same two days running.'],
      ["Vous sentez ? C'est l'air du large. On ne s'en lasse jamais.", "Smell that? That's the sea air. You never tire of it."],
      ["Les bateaux partent à l'aube et rentrent avec le meilleur poisson du monde.", 'The boats go out at dawn and come back with the best fish in the world.'],
    ],
    inland: [
      ['On est loin de la mer, mais la région est magnifique.', 'We are far from the sea, but the region is beautiful.'],
      ['Pas de plage ici, hélas. Mais regardez-moi ces champs !', 'No beach here, alas. But just look at those fields!'],
      ["La mer ? Je ne l'ai jamais vue, pour tout vous dire. C'est loin.", "The sea? Never seen it, to tell the truth. It's a long way."],
      ["Ici, la terre, c'est tout. Bonne terre, braves gens.", 'Out here the land is everything. Good soil, good people.'],
    ],
    high: [
      ["On est en altitude ici. Allez-y doucement, l'air est rare.", "We're high up here. Take it easy, the air is thin."],
      ["Là-haut, la vue, c'est ce qu'on a de plus beau.", 'Up here, the view is the finest thing we have.'],
      ["À vivre ici, on se fait des mollets d'acier. Rien n'est plat !", 'Living up here gives you calves of steel. Nothing is flat!'],
      ['Attention au souffle ! La montagne, ça se mérite.', 'Mind your breath! The mountains have to be earned.'],
    ],
    snowy: [
      ['De la neige neuf mois par an. Les trois autres, on se plaint de la boue.', 'Snow nine months a year. The other three, we complain about the mud.'],
      ['Tout est blanc par ici. Il vous faudra de meilleures bottes que ça.', "Everything is white out here. You'll need better boots than those."],
      ['Le froid ne nous dérange pas. Il éloigne les touristes. Sauf vous, bien sûr !', "The cold doesn't bother us. It keeps the tourists away. Present company excepted!"],
      ["Quand la neige est fraîche, c'est si calme qu'on s'entend penser.", 'When the snow is fresh, it is so quiet you can hear yourself think.'],
    ],
    forest: [
      ['La forêt s\'étend sur des jours de marche. Restez sur le sentier !', 'The forest goes on for days of walking. Stay on the path!'],
      ['Allez vous promener en forêt. Ça vide la tête.', 'Go for a walk in the forest. It clears the head.'],
      ["À l'automne, on va cueillir des champignons et des baies là-bas.", 'Every autumn we go out there picking mushrooms and berries.'],
      ['Des arbres, des arbres et encore des arbres. Je ne vivrais nulle part ailleurs.', "Trees, trees and more trees. I wouldn't live anywhere else."],
    ],
    desert: [
      ["Ici, c'est du sable à perte de vue.", "Out here it's sand as far as the eye can see."],
      ["Buvez beaucoup d'eau. Le désert ne pardonne pas.", 'Drink plenty of water. The desert does not forgive.'],
      ['Les nuits sont froides dans le désert. Personne ne veut le croire.', 'The desert nights are cold. Nobody ever believes it.'],
      ['Attendez les étoiles ce soir. Ici, il y en a des millions.', 'Wait for the stars tonight. Out here there are millions of them.'],
    ],
    plains: [
      ["C'est plat sur des kilomètres. On voit la pluie arriver un jour à l'avance.", 'It is flat for miles. You can see the rain coming a day ahead.'],
      ['Ici, le ciel est immense. Rien n\'arrête le vent.', 'The sky is huge out here. Nothing stops the wind.'],
      ['Ce sont de bons pâturages. Attention aux troupeaux !', 'This is good grazing land. Watch out for the herds!'],
      ["L'herbe n'en finit pas. On dirait une mer verte.", 'The grass never ends. Like a green sea.'],
    ],
    tropical: [
      ['Tout pousse ici. Plantez un bâton, il devient un arbre.', 'Everything grows here. Plant a stick and it becomes a tree.'],
      ["Ici, quand il pleut, il pleut pour de bon. Et puis ça s'arrête, d'un coup.", 'Here, when it rains, it really rains. Then it stops, just like that.'],
      ['Goûtez les fruits du marché. Vous n\'avez jamais rien mangé de pareil.', 'Try the fruit at the market. You have never eaten anything like it.'],
      ["C'est vert toute l'année. L'hiver ? Connais pas.", "It's green all year round. Winter? Never heard of it."],
    ],
    landmark: [
      ["Ne manquez pas {landmark} ! C'est à environ {km} km {dir}.", "Don't miss {landmark}! It's about {km} km {dir}."],
      ["Vous avez vu {landmark} ? C'est à {km} km {dir}, et ça vaut chaque pas.", "Have you seen {landmark}? It's {km} km {dir}, and worth every step."],
      ["Tout le monde va voir {landmark}. C'est à environ {km} km {dir}.", "Everyone goes to see {landmark}. It's about {km} km {dir}."],
      ['Si vous aimez les vieilles pierres, {landmark} est à {km} km {dir}. On vient de loin pour ça.', 'If you like old stones, {landmark} is {km} km {dir}. People come from far away for it.'],
    ],
    landmarkNear: [
      ['{landmark} est tout près. Vous ne pouvez pas vous tromper !', "{landmark} is very close. You can't miss it!"],
      ["Vous avez déjà vu {landmark} ? C'est juste à côté.", "Have you seen {landmark} yet? It's right next door."],
      ['On voit {landmark} tous les jours, et ça me coupe encore le souffle.', 'We see {landmark} every day and it still takes my breath away.'],
      ["Allez voir {landmark}, c'est tout près. Tôt le matin, avant la foule.", "Go and see {landmark}, it's very close. Early, before the crowds."],
    ],
    plane: [
      ['Il y a un petit avion dans un champ {dir}, si vous savez piloter !', "There's a little plane in a field {dir}, if you can fly!"],
      ['Quelqu\'un a laissé un avion dans un champ {dir}. Ça vous dit, un petit vol ?', 'Somebody left a plane in a field {dir}. Fancy a little flight?'],
      ['Vous savez piloter ? Un avion attend {dir}.', "Can you fly? There's a plane waiting {dir}."],
      ["Pour tout voir d'en haut, il y a un avion {dir}.", "To see it all from above, there's a plane {dir}."],
    ],
    balloon: [
      ['Il y a une montgolfière dans un champ {dir} ! Imaginez la vue.', "There's a hot-air balloon in a field {dir}! Imagine the view."],
      ['Vous avez déjà volé en montgolfière ? Il y en a une {dir}.', 'Ever flown in a balloon? There is one {dir}.'],
      ["Une montgolfière s'envole du champ {dir}. C'est magique.", 'A balloon goes up from the field {dir}. It is magical.'],
      ["J'ai toujours rêvé d'essayer la montgolfière {dir}. Mais j'ai trop peur !", "I've always dreamed of trying the balloon {dir}. But I'm too scared!"],
    ],
    boat: [
      ["Il y a un bateau au bord de l'eau {dir}, si vous voulez faire un tour.", "There's a boat by the water {dir}, if you fancy a trip."],
      ["Si vous aimez l'eau, il y a un bateau {dir}. Rapportez-le, hein !", "If you like the water, there's a boat {dir}. Bring it back, mind!"],
      ["Un bateau est amarré {dir}. D'ici, on peut aller n'importe où.", 'A boat is moored {dir}. From here you can go anywhere.'],
      ["Prenez le bateau {dir} et allez voir la côte depuis l'eau.", 'Take the boat {dir} and see the coast from the water.'],
    ],
    hot: [
      ["Il fait chaud aujourd'hui ! Mettez-vous à l'ombre.", "It's hot today! Get into the shade."],
      ["Ouf, quelle chaleur ! Buvez de l'eau, ça vous fera du bien.", 'Phew, what heat! Drink some water, it will do you good.'],
      ["Il fait trop chaud pour faire autre chose que rester à l'ombre.", "It's too hot to do anything but stay in the shade."],
      ["Avec cette chaleur, même les chiens restent à l'intérieur.", 'In this heat, even the dogs stay indoors.'],
      ["Chaud, hein ? Et encore, pour nous, c'est une journée fraîche !", "Hot, isn't it? And for us this is a cool day!"],
    ],
    cold: [
      ["Brr, il fait froid aujourd'hui ! Couvrez-vous bien.", "Brr, it's cold today! Wrap up warm."],
      ['Ça caille ! Où sont vos gants ?', "It's freezing! Where are your gloves?"],
      ['Il fait tellement froid que je ne sens plus mon nez.', "It's so cold I can't feel my nose any more."],
      ['Il fait assez froid pour vous ? Attendez que le vent se lève.', 'Cold enough for you? Wait till the wind gets up.'],
      ['Prenez quelque chose de chaud à boire. Ça aide.', 'Get yourself something hot to drink. It helps.'],
    ],
    mild: [
      ["Quel beau temps aujourd'hui.", 'What lovely weather today.'],
      ['Ni trop chaud ni trop froid. Une journée parfaite, non ?', "Not too hot, not too cold. A perfect day, isn't it?"],
      ['Par un temps pareil, on a envie de rester dehors.', 'On a day like this you want to stay outside.'],
      ['Quel temps magnifique ! Pourvu que ça dure.', "Gorgeous weather! Let's hope it lasts."],
      ["C'est pour des journées comme ça qu'on vit ici.", 'Days like this are why we live here.'],
    ],
    late: [
      ['Il est tard. La nuit, les rues sont calmes.', "It's late. The streets are quiet at night."],
      ["À cette heure-ci, il n'y a que les chats dehors. Et nous !", 'At this hour only the cats are out. And us!'],
      ["Je devrais être au lit. Et vous, qu'est-ce que vous faites debout ?", 'I should be in bed. And what are you doing up?'],
      ["Regardez les étoiles ! D'ici, on les voit très bien.", 'Look at the stars! You can see them really well from here.'],
    ],
    early: [
      ["Déjà debout ? C'est le meilleur moment de la journée.", 'Up already? It is the best part of the day.'],
      ["La boulangerie vient d'ouvrir. Suivez l'odeur !", 'The bakery has just opened. Follow the smell!'],
      ['On se lève tôt, hein ? La ville dort encore.', "An early start, eh? The town isn't even awake."],
      ["J'adore le matin ici, avant que le bruit commence.", 'I love the mornings here, before the noise starts.'],
    ],
    country: [
      ['{country}, quel beau pays ! Profitez-en.', '{country}, what a beautiful country! Enjoy it.'],
      ['Alors, {country}, ça vous plaît jusqu\'ici ?', 'So, {country}: how do you like it so far?'],
      ['{country} : un pays qui se découvre lentement. Prenez votre temps.', '{country}: a country you discover slowly. Take your time.'],
      ['Parcourez tout le pays si vous pouvez. {country}, ça change à chaque coin.', 'Travel the whole country if you can. {country} is different round every corner.'],
    ],
    dish: [
      ['Il faut goûter {dish} pendant votre séjour.', "You have to try {dish} while you're here."],
      ['Vous avez déjà mangé {dish} ? Non ? Il faut absolument !', "Have you had {dish} yet? No? You simply must!"],
      ['Personne ne fait {dish} comme ma mère.', 'Nobody makes {dish} like my mother.'],
      ['Si vous avez faim, prenez {dish}. Vous ne le regretterez pas.', "If you're hungry, get {dish}. You won't regret it."],
    ],
    drink: [
      ["Goûtez {drink} avant de partir. C'est ce qu'on boit ici.", 'Try {drink} before you go. It is what we drink here.'],
      ['Rien ne vaut {drink} en fin de journée.', 'Nothing beats {drink} at the end of the day.'],
      ["Tant que vous n'avez pas goûté {drink}, vous n'avez rien vécu.", "Until you've tasted {drink}, you haven't lived."],
      ["Commandez {drink} comme les gens d'ici, et on vous adoptera.", "Order {drink} like a local and they'll adopt you."],
    ],
    festival: [
      ["Revenez pour {festival}. C'est merveilleux !", "Come back for {festival}. It's wonderful!"],
      ["Le meilleur moment pour venir, c'est pendant {festival}. Tout le monde fait la fête.", 'The best time to come is during {festival}. Everybody celebrates.'],
      ['Vous connaissez {festival} ? Ça vous plairait.', "Have you heard of {festival}? You'd love it."],
      ["Chaque année, j'attends {festival} avec impatience.", 'Every year I wait impatiently for {festival}.'],
    ],
    sport: [
      ["Ici, {sport}, c'est une religion.", 'Here, {sport} is a religion.'],
      ["Vous aimez {sport} ? Ici, c'est une passion.", 'Do you like {sport}? Here it is a passion.'],
      ["Les jours de grand match, toute la ville ne vit que pour ça : {sport}.", 'On big match days the whole town lives for one thing: {sport}.'],
      ['Toute ma famille pratique {sport}. Enfin, ma grand-mère, elle crie.', 'My whole family does {sport}. Well, my grandmother just shouts.'],
    ],
    wonder: [
      ["Si vous avez le temps, allez voir {wonder}. C'est inoubliable.", "If you have time, go and see {wonder}. It's unforgettable."],
      ["Vous avez vu {wonder} ? Il n'y a rien de pareil au monde.", 'Have you seen {wonder}? There is nothing like it in the world.'],
      ['Tout le monde devrait voir {wonder} une fois dans sa vie.', 'Everybody should see {wonder} once in their life.'],
      ["J'ai vu {wonder} enfant. J'en rêve encore.", 'I saw {wonder} as a child. I still dream about it.'],
    ],
    pride: [
      ["Ici, {pride}, c'est notre fierté.", 'Here, {pride} is our pride and joy.'],
      ["Ne partez pas sans découvrir {pride}. C'est ce que nous sommes.", "Don't leave without discovering {pride}. It's who we are."],
      ['Notre plus grande fierté ? {pride}, bien sûr.', 'Our greatest pride? {pride}, of course.'],
      ['Lancez quelqu\'un d\'ici sur {pride} : il en a pour des heures.', 'Get anyone here started on {pride} and they will go on for hours.'],
    ],
    proverb: [
      ['Comme on dit chez nous : « {proverb} »', 'As we say here: "{proverb}"'],
      ['Ma grand-mère disait toujours : « {proverb} »', 'My grandmother always said: "{proverb}"'],
      ['Il y a un dicton ici : « {proverb} »', 'There is a saying here: "{proverb}"'],
      ['Vous connaissez le dicton ? « {proverb} »', 'Do you know the saying? "{proverb}"'],
    ],
    chat: [
      ["Vous venez d'où ? Vous n'êtes pas d'ici.", "Where are you from? You're not from around here."],
      ['Prenez votre temps, regardez autour de vous. Il y a beaucoup à voir.', 'Take your time and look around. There is a lot to see.'],
      ['Vous voyagez en solo ? Il faut du courage.', 'Travelling on your own? That takes courage.'],
      ['On dirait que vous avez beaucoup marché.', 'Looks like you have walked a long way.'],
      ['Si vous vous perdez, demandez. Les gens sont sympas ici.', 'If you get lost, just ask. People are friendly here.'],
      ["C'est quoi, le plus bel endroit que vous ayez vu jusqu'ici ?", "What's the most beautiful place you've seen so far?"],
      ["J'ai toujours rêvé de voyager. Un jour, peut-être.", 'I have always dreamed of travelling. One day, maybe.'],
      ['Vous avez une carte ? Il faut toujours avoir une carte sur soi.', 'Have you got a map? You should always carry a map.'],
    ],
    childGreet: [
      ['Salut !', 'Hi!'],
      ["Bonjour ! T'es qui, toi ?", 'Hello! Who are you?'],
      ["Salut ! Waouh, t'as de grands pieds !", 'Hi! Wow, you have big feet!'],
      ['Coucou, coucou !', 'Hello, hello!'],
    ],
    childChat: [
      ['Je cours super vite ! Tu veux voir ? Bon, plus tard.', 'I can run super fast! Want to see? Well, later.'],
      ['Tu viens d\'un autre pays ? Mon copain dit que les touristes sont riches.', 'Are you from another country? My friend says tourists are rich.'],
      ["J'ai perdu une dent hier ! Regarde ! Ah, on voit pas.", "I lost a tooth yesterday! Look! Oh, you can't see it."],
      ["Maman dit qu'il faut pas parler aux inconnus. Mais toi, t'as l'air sympa.", 'Mum says not to talk to strangers. But you look nice.'],
      ['T\'as un chien ? Moi, je veux un chien.', 'Do you have a dog? I want a dog.'],
      ['Plus tard, je piloterai un avion et je ferai le tour du monde !', "When I'm older I'll fly a plane all round the world!"],
      ["Tu connais des jeux ? Moi, j'en connais plein.", 'Do you know any games? I know loads.'],
    ],
    childBye: [
      ['Au revoir !', 'Bye!'],
      ['Salut ! Reviens jouer !', 'Bye! Come back and play!'],
      ["Faut que j'y aille, maman m'appelle !", 'I have to go, Mum is calling me!'],
      ['Tchao, tchao !', 'Bye-bye!'],
    ],
    grumpyGreet: [
      ["Hm. Qu'est-ce que vous voulez ?", 'Hm. What do you want?'],
      ["Oui ? C'est pour quoi ?", 'Yes? What is it?'],
      ['Ah. Encore des touristes.', 'Oh. More tourists.'],
      ['Mouais. Bonjour, si vous voulez.', 'Hmph. Hello, if you like.'],
    ],
    grumpyChat: [
      ['C\'était mieux avant, quand personne ne venait ici.', 'It was better before, when nobody came here.'],
      ["Tout coûte deux fois plus cher qu'avant.", 'Everything costs twice what it used to.'],
      ['Ne bloquez pas le trottoir, s\'il vous plaît. Il y a des gens qui vivent ici.', "Don't block the pavement, please. People live here."],
      ['Les jeunes d\'aujourd\'hui, toujours le nez sur leur téléphone.', 'Young people today, always with their noses in their phones.'],
      ["Je me demande bien ce que les gens viennent faire ici. Il n'y a rien à voir.", "I really wonder what people come here for. There's nothing to see."],
      ["Et le pain n'a plus le même goût. Plus rien n'a le même goût.", "And the bread doesn't taste the same. Nothing tastes the same any more."],
    ],
    grumpyBye: [
      ['Bon. Allez, filez.', 'Right. Off you go, then.'],
      ['Bon, je ne vous retiens pas.', "Well, I won't keep you."],
      ['Hm. Au revoir.', 'Hm. Goodbye.'],
      ['Faites attention en partant. Et fermez le portail.', 'Mind how you go. And shut the gate.'],
    ],
    elderChat: [
      ["Quand j'étais jeune, tout ça, c'étaient des champs.", 'When I was young, all this was fields.'],
      ["J'ai vécu ici toute ma vie. Quatre-vingts ans ! Vous vous rendez compte ?", 'I have lived here all my life. Eighty years! Can you imagine?'],
      ["De mon temps, on allait partout à pied. Vous aussi, vous marchez. C'est bien !", 'In my day we walked everywhere. You walk too. Good!'],
      ["Mes petits-enfants vivent à l'étranger. Ils appellent tous les dimanches.", 'My grandchildren live abroad. They call every Sunday.'],
      ['Tout change si vite. Mais les vieilles rues, elles, ne bougent pas.', 'Everything changes so fast. But the old streets stay put.'],
    ],
    chattyChat: [
      ["Oh, j'adore rencontrer des voyageurs ! Racontez-moi tout. Non, attendez, je commence.", 'Oh, I love meeting travellers! Tell me everything. No, wait, I go first.'],
      ['Mon cousin est parti en voyage une fois. Il est revenu avec une barbe et une femme !', 'My cousin went travelling once. He came back with a beard and a wife!'],
      ["Mes amis disent que je pourrais parler toute la journée. Ils n'ont pas tort !", "My friends say I could talk all day. They're not wrong!"],
      ["Vous avez mangé ? Vous avez l'air d'avoir faim. Tout le monde a l'air d'avoir faim, pour moi.", 'Have you eaten? You look hungry. Everybody looks hungry to me.'],
      ["Je vous dis un secret : la plus belle vue de la ville, c'est depuis la colline derrière l'église.", 'Let me tell you a secret: the best view in town is from the hill behind the church.'],
    ],
    bye: [
      ['Au revoir ! Bon voyage.', 'Goodbye! Have a good trip.'],
      ['Prenez soin de vous ! Et profitez bien de la suite.', 'Take care! And enjoy the rest of your trip.'],
      ['Bonne route !', 'Safe travels!'],
      ['Allez, à bientôt ! Revenez nous voir.', 'Well, see you soon! Come back and visit us.'],
      ["Ça m'a fait plaisir de discuter. Bonne continuation !", 'It was nice talking. All the best!'],
      ['Allez, filez ! Il y a tant à voir.', "Off you go, then! There's so much to see."],
    ],
  },
  countries: {
    // Every fact is a noun phrase with its own article or determiner ("le ndolé", "la Tabaski"); templates never put one after "à" or "de".
    FRA: {
      dish: ['le bœuf bourguignon', 'beef bourguignon'],
      drink: ['un bon vin rouge', 'a good red wine'],
      festival: ['le 14 Juillet', 'Bastille Day'],
      sport: ['le football', 'football'],
      wonder: ['le Mont-Saint-Michel', 'Mont-Saint-Michel'],
      pride: ['la gastronomie française', 'French cuisine'],
      proverb: ["Petit à petit, l'oiseau fait son nid", 'Little by little, the bird builds its nest'],
    },
    LUX: {
      dish: ['le judd mat gaardebounen', 'judd mat gaardebounen, smoked pork with broad beans'],
      drink: ['le crémant de Luxembourg', 'Luxembourg crémant'],
      festival: ['la Schueberfouer', 'the Schueberfouer fair'],
      sport: ['le cyclisme', 'cycling'],
      wonder: ['la vieille ville de Luxembourg', 'the old town of Luxembourg'],
      pride: ['le multilinguisme', 'speaking several languages'],
      proverb: ['Qui vivra verra', 'Who lives will see'],
    },
    MCO: {
      dish: ['les barbajuans', 'barbajuans, little fried pastries'],
      festival: ['la Sainte-Dévote', 'the feast of Saint Devota'],
      sport: ['la Formule 1', 'Formula One'],
      wonder: ['le Rocher', 'the Rock'],
      pride: ['le Musée océanographique', 'the Oceanographic Museum'],
      proverb: ["L'habit ne fait pas le moine", 'The habit does not make the monk'],
    },
    HTI: {
      dish: ['la soupe joumou', 'soup joumou, the pumpkin soup'],
      drink: ['le rhum Barbancourt', 'Barbancourt rum'],
      festival: ['le carnaval de Jacmel', 'the Jacmel carnival'],
      sport: ['le football', 'football'],
      wonder: ['la citadelle Laferrière', 'the Citadelle Laferrière'],
      pride: ['la peinture haïtienne', 'Haitian painting'],
      proverb: ['Derrière les montagnes, il y a encore des montagnes', 'Beyond the mountains, more mountains'],
    },
    SEN: {
      dish: ['le thiéboudienne', 'thieboudienne, fish and rice'],
      drink: ['le bissap', 'bissap, hibiscus juice'],
      festival: ['la Tabaski', 'Tabaski'],
      sport: ['la lutte sénégalaise', 'Senegalese wrestling'],
      wonder: ['le lac Rose', 'the Pink Lake'],
      pride: ['la teranga', 'teranga, our hospitality'],
      proverb: ['Doucement, doucement, on attrape le singe dans la forêt', 'Slowly, slowly, you catch the monkey in the forest'],
    },
    CIV: {
      dish: ["l'attiéké au poisson braisé", 'attiéké with grilled fish'],
      drink: ['le gnamakoudji', 'gnamakoudji, ginger juice'],
      festival: ["l'Abissa de Grand-Bassam", 'the Abissa festival of Grand-Bassam'],
      sport: ['le football', 'football'],
      wonder: ['le parc national de Taï', 'Taï National Park'],
      pride: ['le coupé-décalé', 'coupé-décalé music'],
      proverb: ['Après la pluie, le beau temps', 'After the rain comes fine weather'],
    },
    CMR: {
      dish: ['le ndolé', 'ndolé, the bitterleaf stew'],
      festival: ['le Ngondo', 'the Ngondo festival'],
      sport: ['le football', 'football'],
      wonder: ['le mont Cameroun', 'Mount Cameroon'],
      pride: ['les Lions indomptables', 'the Indomitable Lions'],
      proverb: ['Chacun voit midi à sa porte', 'Everyone sees noon at their own door'],
    },
    COD: {
      dish: ['le poulet à la moambe', 'chicken moambe'],
      sport: ['le football', 'football'],
      wonder: ['le fleuve Congo', 'the Congo River'],
      pride: ['la rumba congolaise', 'Congolese rumba'],
      proverb: ['Les petits ruisseaux font les grandes rivières', 'Little streams make great rivers'],
    },
    COG: {
      dish: ['le saka-saka', 'saka-saka, cassava leaves'],
      drink: ['le vin de palme', 'palm wine'],
      festival: ['le FESPAM', 'FESPAM, the pan-African music festival'],
      sport: ['le football', 'football'],
      wonder: ["le parc national d'Odzala", 'Odzala National Park'],
      pride: ['la sape', 'la Sape, the art of dressing well'],
      proverb: ["L'union fait la force", 'Unity makes strength'],
    },
    MDG: {
      dish: ['le romazava', 'romazava, the beef and greens stew'],
      drink: ["le ranon'ampango", "ranon'ampango, toasted rice water"],
      festival: ["la fête de l'Indépendance", 'Independence Day'],
      sport: ['le rugby', 'rugby'],
      wonder: ["l'allée des Baobabs", 'the Avenue of the Baobabs'],
      pride: ['les lémuriens', 'the lemurs'],
      proverb: ['Qui va lentement va sûrement', 'Who goes slowly goes surely'],
    },
    MLI: {
      dish: ['le tiguadèguè', 'tigadèguè, the peanut stew'],
      drink: ['le thé à la menthe', 'mint tea'],
      festival: ['le Festival sur le Niger', 'the Festival on the Niger'],
      sport: ['le football', 'football'],
      wonder: ['le pays dogon', 'Dogon Country'],
      pride: ['la kora', 'the kora'],
      proverb: ["Le tronc d'arbre a beau séjourner dans l'eau, il ne deviendra jamais crocodile", 'However long a log lies in the water, it will never become a crocodile'],
    },
    NER: {
      dish: ['le kilichi', 'kilishi, dried spiced meat'],
      drink: ['le thé vert', 'green tea'],
      festival: ['la Cure salée', 'the Cure Salée, the herders’ gathering'],
      sport: ['la lutte traditionnelle', 'traditional wrestling'],
      wonder: ["le massif de l'Aïr", 'the Aïr Mountains'],
      pride: ['les girafes de Kouré', 'the giraffes of Kouré'],
      proverb: ['La main qui donne est au-dessus de celle qui reçoit', 'The hand that gives is above the hand that receives'],
    },
    BFA: {
      dish: ['le tô', 'tô, the millet porridge'],
      drink: ['le dolo', 'dolo, millet beer'],
      festival: ['le FESPACO', 'FESPACO, the film festival'],
      sport: ['le football', 'football'],
      wonder: ['les pics de Sindou', 'the Sindou Peaks'],
      pride: ['le Faso Dan Fani', 'Faso Dan Fani, our woven cloth'],
      proverb: ["C'est en forgeant qu'on devient forgeron", 'It is by forging that you become a blacksmith'],
    },
    BEN: {
      dish: ["l'amiwo", 'amiwo, the red maize paste'],
      drink: ['le sodabi', 'sodabi, palm spirit'],
      sport: ['le football', 'football'],
      wonder: ['Ganvié, la cité lacustre', 'Ganvié, the village on the lake'],
      pride: ["les palais royaux d'Abomey", 'the royal palaces of Abomey'],
      proverb: ['Quand on veut, on peut', 'Where there is a will, there is a way'],
    },
    TGO: {
      dish: ['le fufu', 'fufu'],
      drink: ['le tchoukoutou', 'tchoukoutou, millet beer'],
      sport: ['le football', 'football'],
      wonder: ['le Koutammakou', 'Koutammakou, the land of the Batammariba'],
      pride: ['le Grand Marché de Lomé', 'the Grand Market of Lomé'],
      proverb: ['Tout vient à point à qui sait attendre', 'All things come to those who wait'],
    },
    GIN: {
      dish: ['le riz sauce arachide', 'rice with peanut sauce'],
      drink: ['le jus de gingembre', 'ginger juice'],
      sport: ['le football', 'football'],
      wonder: ['le Fouta-Djalon', 'the Fouta Djallon highlands'],
      pride: ['les Ballets africains', 'the Ballets Africains dance company'],
      proverb: ['Pierre qui roule n’amasse pas mousse', 'A rolling stone gathers no moss'],
    },
    TCD: {
      dish: ['la boule', 'boule, the millet dough'],
      drink: ['le karkanji', 'karkanji, hibiscus tea'],
      sport: ['le football', 'football'],
      wonder: ["les lacs d'Ounianga", 'the Lakes of Ounianga'],
      pride: ['le parc national de Zakouma', 'Zakouma National Park'],
      proverb: ['La nuit porte conseil', 'The night brings counsel'],
    },
    CAF: {
      dish: ['le gozo', 'gozo, the cassava paste'],
      sport: ['le football', 'football'],
      wonder: ['les chutes de Boali', 'the Boali Falls'],
      pride: ['la forêt de Dzanga-Sangha', 'the Dzanga-Sangha forest'],
      proverb: ['Loin des yeux, loin du cœur', 'Far from the eyes, far from the heart'],
    },
    GAB: {
      dish: ['le poulet nyembwe', 'chicken nyembwe, in palm nut sauce'],
      sport: ['le football', 'football'],
      wonder: ['le parc national de la Lopé', 'Lopé National Park'],
      pride: ['la forêt équatoriale', 'the equatorial rainforest'],
      proverb: ['Mieux vaut tard que jamais', 'Better late than never'],
    },
    DJI: {
      dish: ['le skoudehkaris', 'skoudehkaris, spiced rice with meat'],
      sport: ['le football', 'football'],
      wonder: ['le lac Assal', 'Lake Assal'],
      pride: ['les requins-baleines de Tadjourah', 'the whale sharks of Tadjoura'],
      proverb: ['Qui ne risque rien n’a rien', 'Nothing ventured, nothing gained'],
    },
    BDI: {
      dish: ['les brochettes de chèvre', 'goat brochettes'],
      drink: ['le café du Burundi', 'Burundian coffee'],
      sport: ['le football', 'football'],
      wonder: ['le lac Tanganyika', 'Lake Tanganyika'],
      pride: ['les tambourinaires', 'the royal drummers'],
      proverb: ['Chose promise, chose due', 'A thing promised is a thing owed'],
    },
    PYF: {
      dish: ['le poisson cru à la tahitienne', 'Tahitian raw fish in coconut milk'],
      drink: ["l'eau de coco", 'coconut water'],
      festival: ['le Heiva', 'the Heiva festival'],
      sport: ["la va'a", "va'a, outrigger canoe racing"],
      wonder: ['le lagon de Bora-Bora', 'the lagoon of Bora Bora'],
      pride: ['la perle noire de Tahiti', 'the black pearl of Tahiti'],
      proverb: ['Il faut battre le fer pendant qu’il est chaud', 'Strike while the iron is hot'],
    },
    NCL: {
      dish: ['le bougna', 'bougna, cooked in banana leaves'],
      sport: ['le football', 'football'],
      wonder: ["l'île des Pins", 'the Isle of Pines'],
      pride: ['le lagon, classé au patrimoine mondial', 'the lagoon, a World Heritage site'],
      proverb: ['Les bons comptes font les bons amis', 'Good accounts make good friends'],
    },
    SPM: {
      dish: ['la morue', 'salt cod'],
      festival: ['la fête basque', 'the Basque festival'],
      sport: ['la pelote basque', 'Basque pelota'],
      wonder: ["l'île aux Marins", 'the Île aux Marins'],
      pride: ['les maisons colorées de Saint-Pierre', 'the colourful houses of Saint-Pierre'],
      proverb: ['Qui sème le vent récolte la tempête', 'Who sows the wind reaps the storm'],
    },
    MAF: {
      dish: ['le colombo', 'colombo, the Caribbean curry'],
      drink: ['le ti-punch', "ti' punch"],
      festival: ['le carnaval', 'Carnival'],
      wonder: ['la baie Orientale', 'Orient Bay'],
      proverb: ['Rira bien qui rira le dernier', 'He who laughs last laughs best'],
    },
    WLF: {
      drink: ['le kava', 'kava'],
      festival: ['la fête du Territoire', 'Territory Day'],
      wonder: ['le lac Lalolalo', 'Lake Lalolalo'],
      pride: ['le tapa', 'tapa, our bark cloth'],
      proverb: ['Il n’y a pas de fumée sans feu', 'There is no smoke without fire'],
    },
  },
};

export default FR;
