import type { Language } from '../phrases.ts';

const HE: Language = {
  locale: 'he',
  name: 'Hebrew',
  rtl: true,
  join: ' ',
  compass: [
    'צפונה מכאן', 'צפון-מזרחה מכאן', 'מזרחה מכאן', 'דרום-מזרחה מכאן',
    'דרומה מכאן', 'דרום-מערבה מכאן', 'מערבה מכאן', 'צפון-מערבה מכאן',
  ],
  lines: {
    morning: [
      ['בוקר טוב!', 'Good morning!'],
      ['בוקר טוב! איזה בוקר יפה, לא?', "Good morning! Lovely morning, isn't it?"],
      ['הו, שלום! בוקר טוב לכם.', 'Oh, hello! Good morning to you.'],
      ['בוקר! מה נשמע?', "Morning! How's it going?"],
    ],
    afternoon: [
      ['צהריים טובים!', 'Good afternoon!'],
      ['שלום!', 'Hello!'],
      ['שלום שלום!', 'Hello, hello!'],
      ['היי! אחר צהריים נעים, מה?', 'Hi! Nice afternoon, eh?'],
    ],
    evening: [
      ['ערב טוב!', 'Good evening!'],
      ['ערב טוב לכם!', 'Good evening to you!'],
      ['שלום! ערב נחמד לטיול.', 'Hello! A nice evening for a walk.'],
      ['הו, ערב טוב! איזה ערב.', 'Oh, good evening! What an evening.'],
    ],
    night: [
      ['ערב טוב! כבר מאוחר, נכון?', "Good evening! It's late already, isn't it?"],
      ['אוי! הבהלתם אותי. שלום!', 'Oh! You startled me. Hello!'],
      ['שלום! יצאתם לטיול לילי?', 'Hello! Out for a night walk?'],
      ['לילה טוב! או שכבר בוקר?', 'Good night! Or is it morning already?'],
    ],
    again: [
      ['אה, שוב אתם! שלום!', 'Oh, you again! Hello!'],
      ['חזרתם? כיף לראות אתכם.', 'Back again? Nice to see you.'],
      ['שלום שוב!', 'Hello again!'],
      ['כבר נפגשנו! עדיין מטיילים?', "We've met! Still exploring?"],
    ],
    welcome: [
      ['ברוכים הבאים לעיר {town}!', 'Welcome to {town}!'],
      ['זו העיר {town}. באתם לביקור?', 'This is {town}. Are you visiting?'],
      ['פעם ראשונה בעיר {town}?', 'First time in {town}?'],
      ['בחרתם יום טוב לראות את {town}.', "You've picked a good day to see {town}."],
      ['ברוכים הבאים! כאן זה {town}, תרגישו בבית.', 'Welcome! This is {town}, make yourselves at home.'],
      ['נו, מה מביא אתכם לעיר {town}?', 'So, what brings you to {town}?'],
    ],
    capitalHere: [
      ['העיר {town} היא בירת המדינה.', '{town} is the capital of the country.'],
      ['זו הבירה, אתם יודעים. הכול קורה כאן.', 'This is the capital, you know. Everything happens here.'],
      ['בעיר הבירה תמיד יש מה לעשות.', 'In the capital there is always something to do.'],
      ['בתור בירה, העיר {town} אף פעם לא ישנה.', 'Being the capital, {town} never sleeps.'],
    ],
    capitalThere: [
      ['הבירה שלנו היא {capital}. שווה לבקר שם.', 'Our capital is {capital}. Worth a visit.'],
      ['כבר ביקרתם בעיר {capital}?', 'Have you been to {capital} yet?'],
      ['העיר {capital} גדולה יותר, אבל לי טוב כאן.', "{capital} is bigger, but I'm happy here."],
      ['יש לכם זמן? קפיצה לעיר {capital} שווה את זה.', 'Got time? A quick trip to {capital} is worth it.'],
    ],
    big: [
      ['זו עיר גדולה. קל ללכת כאן לאיבוד!', "It's a big city. Easy to get lost here!"],
      ['כמה אנשים! אפשר לגור כאן כל החיים ולא להכיר כל רחוב.', 'So many people! You could live here all your life and not know every street.'],
      ['הפקקים פה, באמת... אבל תמיד קורה משהו.', 'The traffic here, honestly... But something is always going on.'],
      ['עיר כזאת אף פעם לא עוצרת. וזה מה שכיף בה.', "A city like this never stops. That's the fun of it."],
    ],
    middling: [
      ['לא גדולה ולא קטנה. בדיוק במידה.', 'Not big, not small. Just the right size.'],
      ['יש פה הכול, ואפשר ללכת לכל מקום ברגל.', 'It has everything, and you can walk everywhere.'],
      ['גודל נחמד. תוך יום-יומיים תראו הכול.', "A nice size. You'll see it all in a day or two."],
      ['כולם מתלוננים שכאן שקט מדי, ואף אחד לא עוזב.', 'Everyone complains it is too quiet, and nobody leaves.'],
    ],
    small: [
      ['זה מקום קטן. כאן כולם מכירים את כולם.', "It's a small place. Everybody knows everybody."],
      ['מקום קטן. מתעטשים, וכל הרחוב אומר לבריאות.', 'Small place. Sneeze and the whole street says bless you.'],
      ['לא הרבה קורה כאן, וככה אנחנו אוהבים את זה.', 'Not much happens here, and that is how we like it.'],
      ['אתם הדבר הכי מרגש שקרה כאן השבוע!', "You're the most exciting thing to happen here this week!"],
    ],
    coast: [
      ['אנחנו גרים כאן ליד המים. הדגים מצוינים.', 'We live by the water here. The fish is excellent.'],
      ['לכו להסתכל על הים. כל יום הוא אחר.', 'Go and look at the sea. It is different every day.'],
      ['מריחים? זה הים. אי אפשר להתעייף ממנו.', "Smell that? That's the sea. You never tire of it."],
      ['הסירות יוצאות מוקדם וחוזרות עם הדגים הכי טריים.', 'The boats go out early and come back with the freshest fish.'],
    ],
    inland: [
      ['אנחנו רחוקים מהים, אבל הנוף כאן יפהפה.', 'We are far from the sea, but the scenery here is beautiful.'],
      ['אין כאן חוף, מצטערים. אבל תראו את השדות.', 'No beach here, sorry. But look at the fields.'],
      ['הים? רחוק מכאן. אבל האוויר פה נקי.', 'The sea? Far from here. But the air is clean.'],
      ['כאן האדמה היא הכול. אדמה טובה, אנשים טובים.', 'Here the land is everything. Good soil, good people.'],
    ],
    high: [
      ['אנחנו גבוה כאן. לאט לאט, האוויר דליל.', "We're high up here. Slowly, the air is thin."],
      ['בגבעות האלה, הנוף הוא הדבר הכי יפה שיש לנו.', 'Up in these hills, the view is the best thing we have.'],
      ['מי שגר כאן מקבל רגליים חזקות. אין פה שום דבר שטוח!', 'Living here gives you strong legs. Nothing is flat!'],
      ['שימו לב לנשימה! לוקח זמן להתרגל להרים.', 'Mind your breath! The mountains take getting used to.'],
    ],
    snowy: [
      ['שלג תשעה חודשים בשנה. בשלושה האחרים מתלוננים על הבוץ.', 'Snow nine months a year. The other three, we complain about the mud.'],
      ['הכול לבן כאן. תצטרכו נעליים טובות יותר.', "Everything is white here. You'll need better shoes."],
      ['כשהשלג טרי, כל כך שקט שאפשר לשמוע את המחשבות.', 'When the snow is fresh, it is so quiet you can hear your thoughts.'],
      ['הקור לא מפריע לנו. כוס תה חם והכול בסדר.', "The cold doesn't bother us. A cup of hot tea and all is well."],
    ],
    forest: [
      ['היער כאן לא נגמר. תישארו על השביל!', 'The forest here never ends. Stay on the path!'],
      ['לכו לטייל ביער. זה מנקה את הראש.', 'Go for a walk in the forest. It clears the head.'],
      ['כל סתיו יוצאים כאן לקטוף פטריות ופירות יער.', 'Every autumn people here go picking mushrooms and berries.'],
      ['עצים, עצים ועוד עצים. אין מקום יפה מזה.', 'Trees, trees and more trees. No place is lovelier.'],
    ],
    desert: [
      ['כאן יש חול עד האופק.', 'Here there is sand to the horizon.'],
      ['תשתו הרבה מים. המדבר לא סולח.', 'Drink lots of water. The desert does not forgive.'],
      ['הלילות במדבר קרים, אתם יודעים. אף אחד לא מאמין.', 'Desert nights are cold, you know. Nobody believes it.'],
      ['חכו לכוכבים הלילה. כאן רואים מיליונים.', 'Wait for the stars tonight. Here you see millions.'],
    ],
    plains: [
      ['שטוח לאורך קילומטרים. רואים את מזג האוויר מגיע יום מראש.', 'Flat for miles. You see the weather coming a day ahead.'],
      ['שמיים גדולים פה. שום דבר לא עוצר את הרוח.', 'Big sky out here. Nothing stops the wind.'],
      ['הכול כאן אדמת מרעה. תיזהרו מהעדרים.', "It's all grazing land. Watch out for the herds."],
      ['העשב נמשך עד אין סוף. כמו ים ירוק.', 'The grass goes on forever. Like a green sea.'],
    ],
    tropical: [
      ['כאן הכול צומח. תקעו מקל באדמה והוא יהפוך לעץ.', 'Everything grows here. Stick a twig in the ground and it becomes a tree.'],
      ['כשהגשם בא, הוא בא בגדול. ואז נפסק ככה פתאום.', 'When the rain comes, it really comes. Then it stops, just like that.'],
      ['תטעמו את הפירות בשוק. לא טעמתם דבר כזה.', "Taste the fruit at the market. You've never had anything like it."],
      ['ירוק כאן כל השנה. חורף? מה זה חורף?', "It's green all year. Winter? What's winter?"],
    ],
    landmark: [
      ['אל תפספסו את {landmark}! זה בערך {km} ק״מ {dir}.', "Don't miss {landmark}! It's about {km} km {dir}."],
      ['ראיתם כבר את {landmark}? {km} ק״מ {dir}, שווה כל צעד.', 'Have you seen {landmark}? {km} km {dir}, worth every step.'],
      ['כולם נוסעים לראות את {landmark}. זה בערך {km} ק״מ {dir}.', 'Everyone goes to see {landmark}. It is about {km} km {dir}.'],
      ['אוהבים היסטוריה? {landmark}, בערך {km} ק״מ {dir}. באים מכל העולם.', 'Love history? {landmark}, about {km} km {dir}. People come from all over.'],
    ],
    landmarkNear: [
      ['ממש קרוב לכאן: {landmark}. אי אפשר לפספס!', "Very close to here: {landmark}. You can't miss it!"],
      ['כבר ראיתם את {landmark}? זה ממש מעבר לפינה.', 'Have you seen {landmark} yet? It is just round the corner.'],
      ['אנחנו רואים את {landmark} כל יום, וזה עדיין עוצר את הנשימה.', 'We see {landmark} every day, and it still takes our breath away.'],
      ['לכו לראות את {landmark}, זה ממש כאן. מוקדם, לפני ההמונים.', 'Go and see {landmark}, it is right here. Early, before the crowds.'],
    ],
    plane: [
      ['יש מטוס קטן בשדה {dir}, אם אתם יודעים לטוס!', "There's a little plane in a field {dir}, if you can fly!"],
      ['מישהו השאיר מטוס בשדה {dir}. בא לכם לטוס?', 'Somebody left a plane in a field {dir}. Fancy a flight?'],
      ['יודעים לטוס? מטוס מחכה {dir}.', 'Can you fly? A plane is waiting {dir}.'],
      ['רוצים לראות הכול מלמעלה? יש מטוס {dir}.', "Want to see it all from above? There's a plane {dir}."],
    ],
    balloon: [
      ['יש כדור פורח בשדה {dir}! תדמיינו את הנוף.', "There's a hot-air balloon in a field {dir}! Imagine the view."],
      ['טסתם פעם בכדור פורח? יש אחד {dir}.', 'Ever flown in a balloon? There is one {dir}.'],
      ['כדור פורח ממריא מהשדה {dir}. קסום.', 'A balloon takes off from the field {dir}. Magical.'],
      ['תמיד רציתי לנסות את הכדור הפורח. אבל פחדתי!', 'I always wanted to try the balloon. But I got scared!'],
    ],
    boat: [
      ['יש סירה ליד המים {dir}, אם בא לכם לצאת לים.', "There's a boat by the water {dir}, if you fancy going out."],
      ['אוהבים ים? יש סירה {dir}. רק תחזירו אותה!', "Love the sea? There's a boat {dir}. Just bring it back!"],
      ['סירה קשורה {dir}. מכאן אפשר להפליג לכל מקום.', 'A boat is tied up {dir}. From here you can sail anywhere.'],
      ['קחו את הסירה ותראו את החוף מהמים.', 'Take the boat and see the coast from the water.'],
    ],
    hot: [
      ['חם היום! חפשו קצת צל.', "It's hot today! Find some shade."],
      ['פיו, איזה חום! תשתו מים.', 'Phew, what heat! Drink some water.'],
      ['בחום הזה אפשר רק לשבת בצל.', 'In this heat you can only sit in the shade.'],
      ['בחום כזה אפילו החתולים לא יוצאים.', "In heat like this even the cats don't go out."],
      ['חם, נכון? קחו אבטיח קר, זה מציל.', "Hot, isn't it? Get some cold watermelon, it's a lifesaver."],
    ],
    cold: [
      ['ברר, קר היום! תתלבשו חם.', "Brr, it's cold today! Dress warmly."],
      ['קפוא! איפה הכפפות שלכם?', 'Freezing! Where are your gloves?'],
      ['כל כך קר שהאף שלי קפא.', "It's so cold my nose has frozen."],
      ['קר לכם? חכו שהרוח תתחיל.', 'Cold? Wait till the wind starts.'],
      ['תשתו משהו חם. זה עוזר.', 'Have something hot to drink. It helps.'],
    ],
    mild: [
      ['איזה מזג אוויר נהדר היום.', 'What wonderful weather today.'],
      ['לא חם ולא קר. יום מושלם, לא?', "Not hot, not cold. A perfect day, isn't it?"],
      ['ביום כזה רוצים להיות בחוץ.', 'On a day like this you want to be outside.'],
      ['איזה מזג אוויר! שיימשך ככה.', 'What weather! May it last.'],
      ['בשביל ימים כאלה אנחנו גרים כאן.', 'Days like this are why we live here.'],
    ],
    late: [
      ['כבר מאוחר. בלילה הרחובות שקטים.', "It's late. The streets are quiet at night."],
      ['בשעה כזאת רק החתולים בחוץ. וגם אנחנו!', 'At this hour only the cats are out. And us!'],
      ['מזמן הגיע הזמן לישון. למה אתם ערים?', 'It was bedtime long ago. Why are you up?'],
      ['תסתכלו על הכוכבים! מכאן רואים אותם הכי טוב.', 'Look at the stars! You see them best from here.'],
    ],
    early: [
      ['השכמתם! החלק הכי טוב של היום.', "You're up early! The best part of the day."],
      ['המאפייה בדיוק נפתחה. לכו אחרי הריח!', 'The bakery has just opened. Follow the smell!'],
      ['מוקדם, מה? העיר עוד לא התעוררה.', "Early, eh? The town hasn't woken up yet."],
      ['הבקרים כאן, לפני הרעש, הם הכי יפים.', 'The mornings here, before the noise, are the loveliest.'],
    ],
    country: [
      ['{country} היא ארץ יפה. תיהנו!', '{country} is a beautiful country. Enjoy it!'],
      ['איך נראית לכם {country} עד עכשיו?', 'How do you like {country} so far?'],
      ['על המפה {country} קטנה, אבל בלב היא ענקית.', '{country} is small on the map, but huge in the heart.'],
      ['טיילו בכל {country}, אם אפשר. כל פינה אחרת.', 'Travel all over {country}, if you can. Every corner is different.'],
    ],
    dish: [
      ['חייבים לטעום את {dish} כל עוד אתם כאן.', 'You have to taste {dish} while you are here.'],
      ['כבר טעמתם את {dish}? לא? חובה!', 'Have you tried {dish} yet? No? You must!'],
      ['אף אחד לא מכין את {dish} כמו אמא שלי.', 'Nobody makes {dish} like my mother.'],
      ['רעבים? לכו על {dish}. לא תצטערו.', "Hungry? Go for {dish}. You won't regret it."],
    ],
    drink: [
      ['לפני שאתם ממשיכים, תנסו את {drink}. ככה שותים כאן.', 'Before you move on, try {drink}. It is what we drink here.'],
      ['אין כמו {drink} בסוף היום.', 'Nothing beats {drink} at the end of the day.'],
      ['לא חייתם עד שלא טעמתם את {drink}.', "You haven't lived until you've tasted {drink}."],
      ['תזמינו את {drink} כמו מקומיים, וכולם יאהבו אתכם.', 'Order {drink} like a local and everyone will love you.'],
    ],
    festival: [
      ['תחזרו בשביל {festival}. זה נפלא!', "Come back for {festival}. It's wonderful!"],
      ['הזמן הכי טוב להיות כאן זה {festival}. כל המדינה חוגגת.', 'The best time to be here is {festival}. The whole country celebrates.'],
      ['שמעתם על {festival}? הייתם מתים על זה.', "Have you heard of {festival}? You'd love it."],
      ['כל שנה, כולם כאן סופרים את הימים עד {festival}.', 'Every year everyone here counts the days till {festival}.'],
    ],
    sport: [
      ['כאן הכול זה {sport}. כולם משחקים.', "Here it's all about {sport}. Everybody plays."],
      ['אוהבים את {sport}? כאן משוגעים על זה.', 'Do you like {sport}? People here are crazy about it.'],
      ['ביום משחק, כל העיר מדברת רק על {sport}.', 'On match day the whole town talks only about {sport}.'],
      ['כל המשפחה שלי בעניין של {sport}. סבתא בעיקר צועקת.', 'My whole family is into {sport}. Grandma mostly shouts.'],
    ],
    wonder: [
      ['אם יש לכם זמן, לכו לראות את {wonder}. בלתי נשכח.', 'If you have time, go and see {wonder}. Unforgettable.'],
      ['ראיתם את {wonder}? אין דבר כזה בשום מקום בעולם.', 'Have you seen {wonder}? There is nothing like it anywhere.'],
      ['כל אחד צריך לראות את {wonder} פעם בחיים.', 'Everyone should see {wonder} once in their life.'],
      ['בילדות ראיתי את {wonder}. זה נשאר איתי עד היום.', 'I saw {wonder} as a child. It has stayed with me ever since.'],
    ],
    pride: [
      ['במה אנחנו גאים? {pride}.', 'What are we proud of? {pride}.'],
      ['אל תעזבו בלי להכיר את {pride}. זה מי שאנחנו.', "Don't leave without getting to know {pride}. It's who we are."],
      ['הגאווה שלנו: {pride}.', 'Our pride and joy: {pride}.'],
      ['תשאלו כל אחד כאן על {pride}, ותקבלו הרצאה של שעה.', "Ask anyone here about {pride} and you'll get an hour's lecture."],
    ],
    proverb: [
      ['כמו שאומרים אצלנו: "{proverb}"', 'As we say here: “{proverb}”'],
      ['סבתא שלי תמיד אמרה: "{proverb}"', 'My grandmother always said: “{proverb}”'],
      ['יש לנו פתגם: "{proverb}"', 'We have a saying: “{proverb}”'],
      ['מכירים את הפתגם? "{proverb}"', 'Know the saying? “{proverb}”'],
    ],
    chat: [
      ['מאיפה אתם? אתם לא מכאן.', "Where are you from? You're not from here."],
      ['קחו את הזמן ותסתכלו מסביב. יש הרבה מה לראות.', 'Take your time and look around. There is a lot to see.'],
      ['מטיילים לבד? זה אמיץ.', "Travelling alone? That's brave."],
      ['נראה שעברתם דרך ארוכה.', 'Looks like you have come a long way.'],
      ['אם הולכים לאיבוד, פשוט שואלים. אנשים כאן חמים.', 'If you get lost, just ask. People here are warm.'],
      ['מה המקום הכי יפה שראיתם עד עכשיו?', "What's the most beautiful place you've seen so far?"],
      ['תמיד חלמתי לטייל בעולם. אולי יום אחד.', "I've always dreamed of travelling the world. Maybe one day."],
    ],
    childGreet: [
      ['היי!', 'Hi!'],
      ['שלום! מי אתם?', 'Hello! Who are you?'],
      ['וואו, אתם ממש גבוהים!', "Wow, you're really tall!"],
      ['שלום שלום!', 'Hello, hello!'],
    ],
    childChat: [
      ['בא לי כלב. יש לכם כלב?', 'I want a dog. Do you have a dog?'],
      ['נפלה לי שן אתמול! תראו! אוי, אי אפשר לראות.', "My tooth fell out yesterday! Look! Oh, you can't see."],
      ['אמא שלי אומרת לא לדבר עם זרים. אבל אתם נראים נחמדים.', "My mum says don't talk to strangers. But you look nice."],
      ['אתם תיירים? חבר שלי אומר שתיירים עשירים.', 'Are you tourists? My friend says tourists are rich.'],
      ['כשאגדל אטוס במטוס מסביב לעולם!', "When I grow up I'll fly a plane around the world!"],
      ['אתם מכירים משחקים? יש לי המון משחקים.', 'Do you know any games? I have loads of games.'],
      ['אמרו לי שהירח עשוי מגבינה. זה נכון?', 'Somebody told me the moon is made of cheese. Is it true?'],
    ],
    childBye: [
      ['ביי!', 'Bye!'],
      ['ביי! תחזרו לשחק!', 'Bye! Come back and play!'],
      ['אמא קוראת לי, ביי!', 'Mum is calling me, bye!'],
      ['ביי ביי! תבואו שוב!', 'Bye bye! Come again!'],
    ],
    grumpyGreet: [
      ['המ. מה אתם רוצים?', 'Hm. What do you want?'],
      ['כן? מה קרה?', "Yes? What's happened?"],
      ['אוף. עוד תיירים.', 'Ugh. More tourists.'],
      ['נו. שלום, נניח.', 'Well. Hello, let us say.'],
    ],
    grumpyChat: [
      ['פעם היה פה יותר טוב, לפני שכולם התחילו לבוא.', 'It used to be better here, before everybody started coming.'],
      ['הכול עולה כפול ממה שהיה. אפילו הפיתה!', 'Everything costs double what it did. Even pita!'],
      ['אל תחסמו את המדרכה, בבקשה. גרים פה אנשים.', "Don't block the pavement, please. People live here."],
      ['הצעירים של היום, כל הזמן בטלפון.', 'Young people today, always on the phone.'],
      ['למה באים לכאן בכלל? אין פה כלום לראות.', "Why come here at all? There's nothing to see."],
    ],
    grumpyBye: [
      ['טוב. יאללה, לדרך.', 'Right. Go on, off you go.'],
      ['נו, לא אעכב אתכם.', "Well, I won't keep you."],
      ['המ. להתראות.', 'Hm. Goodbye.'],
      ['תיזהרו בדרך. ותסגרו את השער.', 'Careful on the way. And shut the gate.'],
    ],
    elderChat: [
      ['בצעירותי כל זה היה שדות.', 'In my youth all this was fields.'],
      ['כל החיים גרתי כאן. שמונים שנה! אתם מאמינים?', "I've lived here all my life. Eighty years! Can you believe it?"],
      ['בזמנו הלכנו לכל מקום ברגל.', 'Back then we walked everywhere.'],
      ['הנכדים גרים בחו״ל. מתקשרים כל שישי.', 'The grandchildren live abroad. They call every Friday.'],
      ['הכול משתנה כל כך מהר. אבל הרחובות הישנים נשארו אותו דבר.', 'Everything changes so fast. But the old streets stay the same.'],
    ],
    chattyChat: [
      ['אוי, כמה כיף לפגוש מטיילים! ספרו לי הכול. לא, רגע, קודם אני.', 'Oh, how nice to meet travellers! Tell me everything. No, wait, me first.'],
      ['בן הדוד שלי יצא פעם לטיול. חזר עם זקן ועם אישה!', 'My cousin went travelling once. Came back with a beard and a wife!'],
      ['החברים אומרים שאפשר לדבר איתי יום שלם. והם צודקים!', "My friends say you can talk with me all day. And they're right!"],
      ['אכלתם? אתם נראים רעבים. לי כולם נראים רעבים.', 'Have you eaten? You look hungry. Everyone looks hungry to me.'],
      ['אגלה לכם סוד: הנוף הכי יפה בעיר הוא מהגבעה.', "I'll tell you a secret: the best view in town is from the hill."],
    ],
    bye: [
      ['להתראות! נסיעה טובה.', 'Goodbye! Have a good trip.'],
      ['שמרו על עצמכם! המשך טיול מהנה.', 'Take care! Enjoy the rest of your trip.'],
      ['דרך צלחה!', 'Safe travels!'],
      ['ביי! תחזרו לבקר.', 'Bye! Come back and visit.'],
      ['היה כיף לדבר איתכם. בהצלחה!', 'It was fun talking to you. Good luck!'],
      ['יאללה, לכו! יש המון מה לראות.', "Go on, off you go! There's loads to see."],
    ],
  },
  countries: {
    // Every fact is definite (with its article, or a name): the templates set it after «את», after a preposition word, or after a colon, and never let an adjective or verb agree with it.
    ISR: {
      dish: ['השקשוקה', 'shakshuka'],
      drink: ['הלימונענע', 'mint lemonade'],
      festival: ['פורים', 'Purim'],
      sport: ['הכדורגל', 'football'],
      wonder: ['מכתש רמון', 'the Ramon Crater'],
      pride: ['הסטארט-אפים שלנו', 'our start-ups'],
      proverb: ['תפסת מרובה, לא תפסת', 'Grab too much and you have grabbed nothing'],
    },
  },
};

export default HE;
