import type { Language } from '../phrases.ts';

const HI: Language = {
  locale: 'hi',
  name: 'Hindi',
  join: ' ',
  compass: ['उत्तर में', 'उत्तर-पूर्व में', 'पूर्व में', 'दक्षिण-पूर्व में', 'दक्षिण में', 'दक्षिण-पश्चिम में', 'पश्चिम में', 'उत्तर-पश्चिम में'],
  lines: {
    morning: [
      ['सुप्रभात!', 'Good morning!'],
      ['नमस्ते! सुबह-सुबह कितनी ताज़गी है, है ना?', 'Hello! So fresh this early, isn’t it?'],
      ['अरे, नमस्ते जी! सुप्रभात।', 'Oh, hello there! Good morning.'],
      ['नमस्कार! चाय हो गई?', 'Hello! Had your tea yet?'],
    ],
    afternoon: [
      ['नमस्ते!', 'Hello!'],
      ['नमस्ते जी!', 'Hello there!'],
      ['नमस्ते! खाना खा लिया?', 'Hello! Have you eaten?'],
      ['अरे, नमस्कार! दोपहर की धूप देखी?', 'Oh, hello! Seen the afternoon sun?'],
    ],
    evening: [
      ['शुभ संध्या!', 'Good evening!'],
      ['नमस्ते! शाम की सैर हो रही है?', 'Hello! Out for an evening stroll?'],
      ['नमस्कार! कितनी सुहानी शाम है।', 'Hello! What a lovely evening.'],
      ['अरे, नमस्ते जी! शाम हो गई।', 'Oh, hello there! Evening already.'],
    ],
    night: [
      ['नमस्ते! काफ़ी देर हो गई है, है ना?', 'Hello! It’s rather late, isn’t it?'],
      ['अरे! डरा दिया आपने। नमस्ते!', 'Oh! You gave me a fright. Hello!'],
      ['नमस्ते! इतनी रात को सैर?', 'Hello! A walk at this hour of the night?'],
      ['नमस्ते! रात के इस पहर यहाँ कौन?', 'Hello! Who’s out here at this hour of the night?'],
    ],
    again: [
      ['अरे, आप फिर से! नमस्ते!', 'Oh, you again! Hello!'],
      ['फिर से नमस्ते!', 'Hello again!'],
      ['आपसे फिर मुलाक़ात हो गई! घूमना चल रहा है?', 'We meet again! Still exploring?'],
      ['अरे, आप! रास्ता मिल गया?', 'Oh, it’s you! Did you find your way?'],
    ],
    welcome: [
      ['{town} में आपका स्वागत है!', 'Welcome to {town}!'],
      ['यह {town} है। घूमने का इरादा है?', 'This is {town}. Planning to look around?'],
      ['पहली बार {town} आना हुआ?', 'First time in {town}?'],
      ['{town} देखने के लिए आज बढ़िया दिन है।', 'Today’s a great day to see {town}.'],
      ['{town} में पधारने के लिए धन्यवाद!', 'Thank you for gracing {town} with a visit!'],
      ['{town} घूमने का मज़ा लीजिए!', 'Enjoy exploring {town}!'],
    ],
    capitalHere: [
      ['{town} हमारे देश की राजधानी है।', '{town} is the capital of our country.'],
      ['यह राजधानी है। सारा काम-काज यहीं {town} में होता है।', 'This is the capital. Everything gets done right here in {town}.'],
      ['सरकार यहीं {town} में बैठती है। हर तरफ़ बड़े-बड़े दफ़्तर।', 'The government sits here in {town}. Big offices everywhere.'],
      ['राजधानी जो ठहरी! यहाँ की रौनक कभी कम नहीं होती।', 'It’s the capital, after all! The bustle here never dies down.'],
    ],
    capitalThere: [
      ['हमारी राजधानी {capital} है। वहाँ ज़रूर जाइए।', 'Our capital is {capital}. Do go there.'],
      ['कभी {capital} जाना हुआ? वही हमारी राजधानी है।', 'Ever been to {capital}? That’s our capital.'],
      ['{capital} वाले सोचते हैं कि देश वही चलाते हैं। ख़ैर, चलाते तो हैं।', 'People in {capital} think they run the country. Well, they do.'],
      ['{capital} बड़ा शहर है, पर मेरा दिल तो यहीं लगता है।', '{capital} is a big city, but my heart is here.'],
    ],
    big: [
      ['यह एक बड़ा शहर है। यहाँ रास्ता भटकना आसान है!', 'This is a big city. It’s easy to get lost here!'],
      ['इतनी भीड़! यहाँ की हर गली जानने में उम्र निकल जाए।', 'So many people! Knowing every lane here would take a lifetime.'],
      ['यहाँ का ट्रैफ़िक, तौबा! पर रौनक हमेशा रहती है।', 'The traffic here, heaven help us! But there’s always life.'],
      ['बड़ा शहर है, कभी रुकता नहीं। मुझे तो यही पसंद है।', 'It’s a big city, it never stops. That’s what I like.'],
    ],
    middling: [
      ['न बहुत बड़ा, न बहुत छोटा। बिलकुल सही।', 'Not too big, not too small. Just right.'],
      ['ज़रूरत की हर चीज़ मिल जाती है, और सब कुछ पैदल की दूरी पर है।', 'You get everything you need, and it’s all within walking distance.'],
      ['एक-दो दिन में पूरा {town} देख लीजिए।', 'You can see all of {town} in a day or two.'],
      ['सब कहते हैं यहाँ बहुत शांति है, पर जाता कोई नहीं।', 'Everyone says it’s too quiet here, but nobody leaves.'],
    ],
    small: [
      ['यह एक छोटी-सी जगह है। यहाँ सब एक-दूसरे को जानते हैं।', 'It’s a small place. Everybody knows everybody here.'],
      ['छोटा-सा क़स्बा है। छींको तो पूरी गली “जीते रहो” कहती है।', 'Small town. Sneeze and the whole lane says bless you.'],
      ['{town} में कुछ ख़ास नहीं होता, और हमें यही पसंद है।', 'Nothing much happens in {town}, and we like it that way.'],
      ['आप तो इस हफ़्ते की सबसे बड़ी ख़बर हैं!', 'You’re the biggest news of the week!'],
    ],
    coast: [
      ['हम यहाँ पानी के किनारे रहते हैं। यहाँ की मछली बहुत अच्छी है।', 'We live by the water here. The fish is very good.'],
      ['जाकर पानी देखिए। हर दिन अलग रंग होता है।', 'Go and look at the water. It’s a different colour every day.'],
      ['यह ख़ुशबू? समंदर की है। इससे कभी मन नहीं भरता।', 'That smell? It’s the sea. You never tire of it.'],
      ['नावें तड़के निकलती हैं और ताज़ी मछली लेकर लौटती हैं।', 'The boats go out at dawn and come back with fresh fish.'],
    ],
    inland: [
      ['समुद्र यहाँ से दूर है, लेकिन यह इलाक़ा बहुत सुंदर है।', 'The sea is far from here, but this area is very beautiful.'],
      ['यहाँ समुद्र तट नहीं है। पर ये खेत तो देखिए।', 'No beach here. But just look at these fields.'],
      ['समंदर? सच कहूँ तो कभी देखा नहीं। बहुत दूर है।', 'The sea? Honestly, never seen it. It’s very far.'],
      ['यहाँ ज़मीन ही सब कुछ है। अच्छी मिट्टी, अच्छे लोग।', 'Here the land is everything. Good soil, good people.'],
    ],
    high: [
      ['हम काफ़ी ऊँचाई पर हैं। धीरे चलिए, हवा पतली है।', 'We’re quite high up. Go slowly, the air is thin.'],
      ['पहाड़ों में सबसे अच्छी चीज़ यहाँ का नज़ारा है।', 'Up in the hills, the view is the best thing we have.'],
      ['यहाँ रहकर पैर मज़बूत हो जाते हैं। कुछ भी समतल नहीं।', 'Living here makes your legs strong. Nothing is flat.'],
      ['साँस का ध्यान रखिए! पहाड़ों की आदत पड़ने में वक़्त लगता है।', 'Mind your breath! The mountains take some getting used to.'],
    ],
    snowy: [
      ['साल में नौ महीने बर्फ़। बाक़ी तीन महीने कीचड़ की शिकायत।', 'Snow nine months a year. The other three, complaints about mud.'],
      ['यहाँ सब कुछ सफ़ेद है। इन जूतों से काम नहीं चलेगा।', 'Everything is white here. Those shoes won’t do.'],
      ['बर्फ़ ताज़ा हो तो इतनी शांति होती है कि अपनी धड़कन सुनाई दे।', 'When the snow is fresh, it’s so quiet you can hear your heartbeat.'],
      ['ठंड की हमें आदत है। चाय हो तो सब ठीक।', 'We’re used to the cold. With tea, all is well.'],
    ],
    forest: [
      ['यहाँ जंगल मीलों तक फैला है। पगडंडी मत छोड़िए!', 'The forest stretches for miles here. Don’t leave the path!'],
      ['जंगल में थोड़ा टहल आइए। दिमाग़ ताज़ा हो जाता है।', 'Take a little walk in the forest. It clears the head.'],
      ['शाम को जंगल से मोर की आवाज़ आती है।', 'In the evening you hear peacocks calling from the forest.'],
      ['पेड़ ही पेड़। मुझे और कहीं रहना पसंद नहीं।', 'Trees and more trees. I wouldn’t like to live anywhere else.'],
    ],
    desert: [
      ['यहाँ दूर-दूर तक बस रेत ही रेत है।', 'Here it’s nothing but sand as far as you can see.'],
      ['ख़ूब पानी पीजिए। रेगिस्तान किसी को माफ़ नहीं करता।', 'Drink plenty of water. The desert forgives no one.'],
      ['रेगिस्तान की रातें ठंडी होती हैं, लोग यक़ीन नहीं करते।', 'Desert nights are cold, people never believe it.'],
      ['आज रात तारे देखिएगा। यहाँ लाखों दिखते हैं।', 'Look at the stars tonight. You can see millions here.'],
    ],
    plains: [
      ['मीलों तक समतल ज़मीन। मौसम एक दिन पहले आता दिख जाता है।', 'Flat land for miles. You see the weather coming a day ahead.'],
      ['खुला आसमान, और हवा को रोकने वाला कोई नहीं।', 'Open sky, and nothing to stop the wind.'],
      ['चराई की अच्छी ज़मीन है। मवेशियों से बचकर चलिए।', 'It’s good grazing land. Watch out for the cattle.'],
      ['घास ही घास, जैसे कोई हरा समंदर।', 'Grass and more grass, like a green sea.'],
    ],
    tropical: [
      ['यहाँ सब कुछ उगता है। डंडी गाड़िए, पेड़ बन जाएगी।', 'Everything grows here. Plant a stick and it becomes a tree.'],
      ['यहाँ बारिश आती है तो जमकर आती है, फिर अचानक रुक जाती है।', 'When the rain comes here it really pours, then stops just like that.'],
      ['बाज़ार के फल चखिए। ऐसा स्वाद कहीं नहीं मिलेगा।', 'Taste the fruit at the market. You won’t find that flavour anywhere.'],
      ['यहाँ साल भर हरियाली रहती है। सर्दी? वो क्या होती है?', 'It’s green here all year. Winter? What’s that?'],
    ],
    landmark: [
      ['{landmark} ज़रूर देखिए! यह यहाँ से लगभग {km} किमी {dir} है।', 'Do see {landmark}! It’s about {km} km from here, {dir}.'],
      ['{landmark} देखना मत भूलिए! बस {km} किमी {dir}।', 'Don’t forget to see {landmark}! Just {km} km {dir}.'],
      ['सब लोग {landmark} देखने जाते हैं। यहाँ से कोई {km} किमी {dir}।', 'Everyone goes to see {landmark}. Some {km} km from here, {dir}.'],
      ['फ़ुरसत हो तो {landmark} जाइए, {km} किमी {dir}। दूर-दूर से लोग आते हैं।', 'If you have time, go to {landmark}, {km} km {dir}. People come from far and wide.'],
    ],
    landmarkNear: [
      ['{landmark} बहुत पास है। आप उसे ज़रूर देख लेंगे!', '{landmark} is very close. You’ll surely see it!'],
      ['{landmark} यहीं पास में है। देखे बिना मत जाइए।', '{landmark} is right nearby. Don’t leave without seeing it.'],
      ['{landmark} यहीं है, बिलकुल पास। सुबह जल्दी जाइए, भीड़ से पहले।', '{landmark} is right here, very close. Go early, before the crowds.'],
      ['{landmark} को रोज़ देखकर भी दिल नहीं भरता।', 'Even seeing {landmark} every day, the heart never has enough.'],
    ],
    plane: [
      ['खेत में {dir} एक छोटा विमान खड़ा है। उड़ाना आता है?', 'There’s a little plane in a field {dir}. Can you fly?'],
      ['किसी ने {dir} एक विमान छोड़ रखा है। उड़ान भरने का मन है?', 'Somebody has left a plane {dir}. Fancy a flight?'],
      ['उड़ाना आता है? {dir} एक विमान इंतज़ार कर रहा है।', 'Can you fly? A plane is waiting {dir}.'],
      ['ऊपर से सब देखना हो तो {dir} एक विमान है।', 'If you want to see it all from above, there’s a plane {dir}.'],
    ],
    balloon: [
      ['{dir} खेत में एक गर्म हवा वाला गुब्बारा है! सोचिए, क्या नज़ारा होगा।', 'There’s a hot-air balloon in a field {dir}! Imagine the view.'],
      ['कभी गुब्बारे में उड़ान भरी है? {dir} एक है।', 'Ever flown in a balloon? There’s one {dir}.'],
      ['खेत से {dir} एक गुब्बारा ऊपर जाता है। जादू जैसा लगता है।', 'A balloon goes up from the field {dir}. It feels like magic.'],
      ['{dir} वाले गुब्बारे में बैठने का बड़ा मन है, पर डर लगता है!', 'I’d love to ride the balloon {dir}, but it scares me!'],
    ],
    boat: [
      ['{dir} पानी के किनारे एक नाव है, सैर करनी हो तो।', 'There’s a boat by the water {dir}, if you’d like a trip.'],
      ['पानी पसंद है तो {dir} एक नाव है। बस लौटा दीजिएगा!', 'If you like the water, there’s a boat {dir}. Just bring it back!'],
      ['{dir} एक नाव बँधी है। यहाँ से कहीं भी निकला जा सकता है।', 'A boat is tied up {dir}. From here you can go anywhere.'],
      ['{dir} वाली नाव लीजिए और पानी से किनारा देखिए।', 'Take the boat {dir} and see the shore from the water.'],
    ],
    hot: [
      ['आज बहुत गर्मी है! थोड़ी छाँव ढूँढ लीजिए।', 'It’s very hot today! Find a bit of shade.'],
      ['उफ़, क्या गर्मी है! पानी पीजिए।', 'Phew, what heat! Drink some water.'],
      ['इतनी गर्मी में बस छाँव में बैठने का मन करता है।', 'In this heat all you want is to sit in the shade.'],
      ['इस गर्मी में तो कुत्ते भी घर से नहीं निकलते।', 'In this heat even the dogs don’t leave the house.'],
      ['गर्मी है ना? और यह तो हमारे लिए ठंडा दिन है!', 'Hot, isn’t it? And this is a cool day for us!'],
    ],
    cold: [
      ['ब्र्र, आज ठंड है! गर्म कपड़े पहन लीजिए।', 'Brr, it’s cold today! Put on something warm.'],
      ['कड़ाके की ठंड है! दस्ताने कहाँ हैं?', 'It’s bitterly cold! Where are your gloves?'],
      ['इतनी ठंड है कि नाक ने काम करना बंद कर दिया।', 'It’s so cold my nose has stopped working.'],
      ['अभी तो कुछ नहीं, हवा चलने दीजिए फिर देखिए।', 'This is nothing yet, wait till the wind picks up.'],
      ['कुछ गर्म पी लीजिए। अदरक वाली चाय से बढ़िया कुछ नहीं।', 'Have something hot. Nothing beats ginger tea.'],
    ],
    mild: [
      ['आज मौसम कितना अच्छा है।', 'What lovely weather today.'],
      ['न ज़्यादा गर्मी, न ज़्यादा ठंड। एकदम बढ़िया दिन।', 'Not too hot, not too cold. A perfect day.'],
      ['ऐसे दिन तो बाहर ही रहने का मन करता है।', 'On a day like this you just want to be outside.'],
      ['कितना सुहाना मौसम है! बस ऐसा ही रहे।', 'Such pleasant weather! May it stay like this.'],
      ['ऐसे ही दिनों की वजह से यहाँ रहना अच्छा लगता है।', 'Days like this are why it’s good to live here.'],
    ],
    late: [
      ['देर हो गई है। रात में सड़कें शांत रहती हैं।', 'It’s late. The streets are quiet at night.'],
      ['इस वक़्त तो बस बिल्लियाँ घूमती हैं। और हम!', 'At this hour only the cats are out. And us!'],
      ['मुझे तो अब तक सो जाना चाहिए था। आपको नींद नहीं आती?', 'I should be asleep by now. Can’t you sleep?'],
      ['तारे देखिए! यहाँ से सबसे साफ़ दिखते हैं।', 'Look at the stars! They’re clearest from here.'],
    ],
    early: [
      ['इतनी सुबह-सुबह! दिन का सबसे अच्छा वक़्त यही है।', 'So early! This is the best time of the day.'],
      ['चाय की दुकान अभी खुली है। ख़ुशबू के पीछे चलिए!', 'The tea stall has just opened. Follow the smell!'],
      ['अभी तो शहर भी नहीं जागा।', 'The town isn’t even awake yet.'],
      ['शोर शुरू होने से पहले की सुबह मुझे बहुत प्यारी है।', 'I love the morning here, before the noise begins.'],
    ],
    country: [
      ['{country} एक सुंदर देश है। इसका आनंद लीजिए!', '{country} is a beautiful country. Enjoy it!'],
      ['अब तक {country} में घूमना कैसा रहा?', 'How has travelling in {country} been so far?'],
      ['हो सके तो {country} का कोना-कोना घूमिए। हर जगह अलग है।', 'If you can, see every corner of {country}. Each place is different.'],
      ['{country}: रंग, स्वाद और लोग, सब एक से बढ़कर एक।', '{country}: colours, flavours and people, each better than the last.'],
    ],
    dish: [
      ['यहाँ हैं तो {dish} ज़रूर चखिए।', 'While you’re here, do taste {dish}.'],
      ['{dish} बनाने में मेरी माँ का कोई जवाब नहीं।', 'Nobody makes {dish} like my mother.'],
      ['भूख लगी हो तो {dish} मँगवाइए। पछतावा नहीं होगा।', 'If you’re hungry, order {dish}. You won’t regret it.'],
      ['यहाँ का असली स्वाद? {dish}, और कुछ नहीं।', 'The real taste of this place? {dish}, nothing else.'],
    ],
    drink: [
      ['{drink} पीजिए, यहाँ सब यही पीते हैं।', 'Have some {drink}, it’s what everybody drinks here.'],
      ['दिन ढले {drink} मिल जाए, और क्या चाहिए?', '{drink} at the end of the day, what more could you want?'],
      ['एक बार {drink} चखिए, फिर बताइए।', 'Try {drink} once, then tell me.'],
      ['यहाँ वालों की तरह {drink} मँगाइए, सब ख़ुश हो जाएँगे।', 'Order {drink} like a local, and everyone will be delighted.'],
    ],
    festival: [
      ['{festival} के समय फिर आइए। कमाल का माहौल रहता है!', 'Come back for {festival}. The atmosphere is amazing!'],
      ['यहाँ आने का सबसे अच्छा वक़्त? {festival}! पूरा देश जश्न मनाता है।', 'The best time to come? {festival}! The whole country celebrates.'],
      ['{festival} का नाम सुना है? आपको बहुत मज़ा आएगा।', 'Heard of {festival}? You’d have a wonderful time.'],
      ['मुझे तो साल भर {festival} का इंतज़ार रहता है।', 'I wait all year for {festival}.'],
    ],
    sport: [
      ['यहाँ तो बस एक ही खेल है: {sport}!', 'There’s only one game here: {sport}!'],
      ['यहाँ सब {sport} के दीवाने हैं। आपको पसंद है?', 'Everyone here is mad about {sport}. Do you like it?'],
      ['मैच वाले दिन पूरा शहर बस {sport} की बातें करता है।', 'On match day the whole town talks about nothing but {sport}.'],
      ['मेरा पूरा परिवार {sport} खेलता है। दादी बस चिल्लाती हैं।', 'My whole family plays {sport}. Grandma just shouts.'],
    ],
    wonder: [
      ['वक़्त हो तो {wonder} देखने जाइए। ज़िंदगी भर याद रहेगा।', 'If you have time, go and see {wonder}. You’ll remember it all your life.'],
      ['{wonder} जैसा कुछ दुनिया में कहीं नहीं।', 'There’s nothing like {wonder} anywhere in the world.'],
      ['ज़िंदगी में एक बार {wonder} ज़रूर देखिए।', 'See {wonder} at least once in your life.'],
      ['बचपन की सबसे प्यारी याद? {wonder} की सैर।', 'My sweetest childhood memory? A trip to {wonder}.'],
    ],
    pride: [
      ['{pride} हमारी शान है।', '{pride} is our pride and joy.'],
      ['{pride} के बारे में जाने बिना मत जाइए। यही हमारी पहचान है।', 'Don’t leave without learning about {pride}. It’s who we are.'],
      ['हमें किस बात पर गर्व है? {pride}।', 'What are we proud of? {pride}.'],
      ['किसी से भी {pride} के बारे में पूछिए, बातें ख़त्म नहीं होंगी।', 'Ask anyone about {pride}, and the talk will never end.'],
    ],
    proverb: [
      ['हमारे यहाँ कहते हैं: “{proverb}”', 'As we say here: “{proverb}”'],
      ['मेरी दादी हमेशा कहती थीं: “{proverb}”', 'My grandmother always said: “{proverb}”'],
      ['यहाँ एक कहावत है: “{proverb}”', 'There’s a saying here: “{proverb}”'],
      ['वो कहावत सुनी है? “{proverb}”', 'Heard the saying? “{proverb}”'],
    ],
    chat: [
      ['आप कहाँ से हैं? आप यहाँ के नहीं लगते।', 'Where are you from? You don’t seem to be from here.'],
      ['आराम से घूमिए। यहाँ देखने को बहुत कुछ है।', 'Take your time looking around. There’s a lot to see here.'],
      ['अकेले सफ़र? बड़ी हिम्मत की बात है।', 'Travelling alone? That takes courage.'],
      ['लगता है बहुत दूर से पैदल चलकर आना हुआ है।', 'Looks like you’ve walked a long way.'],
      ['रास्ता भटक जाएँ तो किसी से भी पूछ लीजिए। यहाँ के लोग मददगार हैं।', 'If you get lost, just ask anyone. People here are helpful.'],
      ['अब तक की सबसे अच्छी जगह कौन-सी लगी?', 'What’s the best place you’ve seen so far?'],
      ['मेरा भी घूमने का बड़ा मन है। कभी न कभी।', 'I’d love to travel too. Someday.'],
    ],
    childGreet: [
      ['हाय!', 'Hi!'],
      ['नमस्ते! आप कौन हो?', 'Hello! Who are you?'],
      ['हाय! आपका नाम क्या है?', 'Hi! What’s your name?'],
      ['हेलो हेलो!', 'Hello, hello!'],
    ],
    childChat: [
      ['मेरी दौड़ सबसे तेज़ है! देखना है? बाद में।', 'I run the fastest! Want to see? Later.'],
      ['आप टूरिस्ट हो? मेरा दोस्त कहता है टूरिस्ट अमीर होते हैं।', 'Are you a tourist? My friend says tourists are rich.'],
      ['कल मेरा दाँत टूट गया! देखो! अरे, दिख नहीं रहा।', 'My tooth fell out yesterday! Look! Oh, you can’t see it.'],
      ['मम्मी कहती हैं अजनबियों से बात मत करो। पर आपकी मुस्कान अच्छी है।', 'Mum says don’t talk to strangers. But you have a nice smile.'],
      ['आपके पास कुत्ता है? मुझे कुत्ता चाहिए।', 'Do you have a dog? I want a dog.'],
      ['बड़े होकर मुझे हवाई जहाज़ उड़ाकर पूरी दुनिया घूमनी है!', 'When I grow up I want to fly a plane all round the world!'],
      ['मैंने आज स्कूल में पतंग बनाई!', 'I made a kite at school today!'],
    ],
    childBye: [
      ['बाय बाय!', 'Bye bye!'],
      ['बाय! फिर खेलने आना!', 'Bye! Come back and play!'],
      ['मुझे जाना है, मम्मी बुला रही हैं!', 'I have to go, Mum is calling!'],
      ['टाटा, बाय-बाय!', 'Ta-ta, bye-bye!'],
    ],
    grumpyGreet: [
      ['हम्म। क्या चाहिए?', 'Hm. What do you want?'],
      ['हाँ? क्या बात है?', 'Yes? What is it?'],
      ['ओह। एक और टूरिस्ट।', 'Oh. Another tourist.'],
      ['हुँह। नमस्ते, और क्या।', 'Hmph. Hello, I suppose.'],
    ],
    grumpyChat: [
      ['पहले यहाँ बेहतर था, जब सब घूमने नहीं आते थे।', 'It was better here before everyone started visiting.'],
      ['हर चीज़ के दाम दुगने हो गए हैं।', 'The price of everything has doubled.'],
      ['रास्ता मत रोकिए। यहाँ लोग रहते हैं।', 'Don’t block the way. People live here.'],
      ['आजकल के बच्चे, हर वक़्त फ़ोन में घुसे रहते हैं।', 'Kids these days, always buried in their phones.'],
      ['पता नहीं लोग यहाँ क्यों आते हैं। देखने को कुछ है ही नहीं।', 'No idea why people come here. There’s nothing to see.'],
    ],
    grumpyBye: [
      ['ठीक है। अब जाइए।', 'Right. Off you go now.'],
      ['चलिए, मैं आपको रोकूँ क्यों।', 'Well, why should I keep you.'],
      ['हम्म। नमस्ते।', 'Hm. Goodbye.'],
      ['ध्यान से जाइए। और गेट बंद कर दीजिए।', 'Mind how you go. And shut the gate.'],
    ],
    elderChat: [
      ['मेरे बचपन में यहाँ बस खेत ही खेत थे।', 'When I was a child, this was all fields.'],
      ['सारी उम्र यहीं गुज़री है। अस्सी साल! यक़ीन होता है?', 'My whole life has passed here. Eighty years! Can you believe it?'],
      ['हमारे ज़माने में सब पैदल चलते थे। आप भी पैदल हैं, अच्छा है!', 'In our day everyone walked. You’re on foot too, good!'],
      ['पोते-पोतियाँ अब विदेश में रहते हैं। हर रविवार फ़ोन आता है।', 'The grandchildren live abroad now. They call every Sunday.'],
      ['ज़माना कितनी तेज़ी से बदलता है। पर पुरानी गलियाँ वैसी ही हैं।', 'How fast the times change. But the old lanes are just the same.'],
      ['पहले पूरा मोहल्ला एक रेडियो पर क्रिकेट सुनता था।', 'The whole neighbourhood used to listen to cricket on one radio.'],
    ],
    chattyChat: [
      ['अरे वाह, मुसाफ़िर! सब बताइए। नहीं, रुकिए, पहले मैं बताऊँ।', 'Oh wonderful, a traveller! Tell me everything. No, wait, let me go first.'],
      ['मेरा चचेरा भाई एक बार घूमने गया था। लौटा तो दाढ़ी और बीवी दोनों साथ थीं!', 'My cousin went travelling once. He came back with a beard and a wife!'],
      ['दोस्त कहते हैं मेरी बातें कभी ख़त्म नहीं होतीं। सच ही कहते हैं!', 'My friends say my talking never ends. They’re right!'],
      ['कुछ खाया? भूख लगी होगी। मुझे तो हर कोई भूखा लगता है।', 'Have you eaten? You must be hungry. Everyone looks hungry to me.'],
      ['एक राज़ की बात बताऊँ? सबसे अच्छा नज़ारा मंदिर के पीछे वाली पहाड़ी से है।', 'Shall I tell you a secret? The best view is from the hill behind the temple.'],
    ],
    bye: [
      ['अलविदा! आपकी यात्रा शुभ हो।', 'Goodbye! Have a good journey.'],
      ['ध्यान रखिए! बाक़ी सफ़र का मज़ा लीजिए।', 'Take care! Enjoy the rest of your trip.'],
      ['सफ़र मंगलमय हो!', 'Safe and happy travels!'],
      ['फिर आइएगा!', 'Do come again!'],
      ['आपसे बात करके अच्छा लगा। अपना ख़याल रखिए!', 'It was nice talking to you. Look after yourself!'],
      ['चलिए, जाइए! देखने को बहुत कुछ है।', 'Off you go, then! There’s so much to see.'],
    ],
  },
  countries: {
    // Each fact is a noun in the direct case, never followed by a word it would bend for; templates keep it as subject, object or after a colon.
    IND: {
      dish: ['बिरयानी', 'biryani'],
      drink: ['मसाला चाय', 'masala chai'],
      festival: ['दिवाली', 'Diwali'],
      sport: ['क्रिकेट', 'cricket'],
      wonder: ['हिमालय', 'the Himalayas'],
      pride: ['भारतीय शास्त्रीय संगीत', 'Indian classical music'],
      proverb: ['जैसा देश, वैसा भेष', 'As the land, so the dress'],
    },
  },
};

export default HI;
