import type { Language } from '../phrases.ts';

/**
 * Indonesian, as a friendly stranger in the street talks: no pronoun where
 * one can be left out, and *Kak* where a name for the listener is wanted,
 * which asks nothing of their sex. A direction is a bare word, so every
 * template carries its own *ke arah* or *di sebelah*.
 */
const ID: Language = {
  locale: 'id',
  name: 'Indonesian',
  join: ' ',
  compass: ['utara', 'timur laut', 'timur', 'tenggara', 'selatan', 'barat daya', 'barat', 'barat laut'],
  lines: {
    morning: [
      ['Selamat pagi!', 'Good morning!'],
      ['Pagi!', 'Morning!'],
      ['Pagi, Kak! Cerah, ya?', "Morning! Nice and bright, isn't it?"],
      ['Eh, halo! Selamat pagi.', 'Oh, hello! Good morning.'],
    ],
    afternoon: [
      ['Selamat siang!', 'Good afternoon!'],
      ['Siang, Kak!', 'Afternoon!'],
      ['Halo! Siang-siang begini jalan-jalan, ya?', 'Hello! Out walking in the middle of the day?'],
      ['Eh, halo! Selamat siang.', 'Oh, hello! Good afternoon.'],
    ],
    evening: [
      ['Selamat sore!', 'Good evening!'],
      ['Selamat malam!', 'Good evening!'],
      ['Sore, Kak! Enak buat jalan-jalan, ya.', 'Evening! Nice time for a stroll.'],
      ['Halo, selamat malam.', 'Hello, good evening.'],
    ],
    night: [
      ['Selamat malam! Sudah larut, ya?', "Good evening! It's late, isn't it?"],
      ['Eh, kaget saya! Halo.', 'Oh, you startled me! Hello.'],
      ['Halo! Jalan-jalan malam-malam begini?', 'Hello! Out walking at this hour?'],
      ['Malam! Belum tidur juga?', 'Evening! Not asleep yet either?'],
    ],
    again: [
      ['Lho, ketemu lagi! Halo!', 'Oh, we meet again! Hello!'],
      ['Balik lagi? Senang ketemu lagi.', 'Back again? Nice to see you again.'],
      ['Halo lagi!', 'Hello again!'],
      ['Eh, Kakak yang tadi! Masih jalan-jalan?', "Oh, it's you from before! Still exploring?"],
      ['Sudah ketemu jalannya?', 'Did you find your way?'],
    ],
    welcome: [
      ['Selamat datang di {town}!', 'Welcome to {town}!'],
      ['Ini {town}. Sedang berkunjung?', 'This is {town}. Visiting?'],
      ['Baru pertama kali ke {town}?', 'First time in {town}?'],
      ['Pas sekali harinya buat lihat-lihat {town}.', 'A perfect day to look around {town}.'],
      ['Ayo, ayo, selamat datang! {town} senang ada tamu.', 'Come in, come in, welcome! {town} is glad of a guest.'],
      ['Ada perlu apa ke {town}?', 'What brings you to {town}?'],
    ],
    capitalHere: [
      ['{town} ini ibu kota negara kami.', '{town} is the capital of our country.'],
      ['Ini ibu kota, lho. Semua urusan ada di {town}.', 'This is the capital, you know. Everything happens in {town}.'],
      ['Pemerintah ada di sini, di {town}. Banyak orang penting berjas.', 'The government is here in {town}. Lots of important people in suits.'],
      ['Namanya juga ibu kota, {town} tidak pernah tidur.', 'It is the capital, after all: {town} never sleeps.'],
    ],
    capitalThere: [
      ['Ibu kota kami adalah {capital}. Layak dikunjungi.', "Our capital is {capital}. It's worth a visit."],
      ['Sudah pernah ke {capital}? Itu ibu kota kami.', 'Have you been to {capital}? That is our capital.'],
      ['Orang di {capital} merasa paling hebat. Ya, namanya juga ibu kota.', 'People in {capital} think they are the best. Well, it is the capital.'],
      ['{capital} memang lebih besar, tapi saya lebih suka tinggal di sini.', '{capital} is bigger, sure, but I would rather live here.'],
    ],
    big: [
      ['Ini kota besar. Mudah sekali tersesat di sini!', "This is a big city. It's so easy to get lost here!"],
      ['Macetnya, aduh! Tapi selalu ada saja yang seru.', 'The traffic, oh my! But there is always something going on.'],
      ['Orangnya banyak sekali. Seumur hidup di sini pun belum tentu hafal semua jalan.', 'So many people. You could live here all your life and not know every street.'],
      ['Kota sebesar ini tidak pernah berhenti. Saya suka, walau capek.', 'A city this big never stops. I love it, though it wears me out.'],
    ],
    middling: [
      ['Tidak besar, tidak kecil. Pas.', 'Not big, not small. Just right.'],
      ['Semua ada, tapi masih bisa dijelajahi jalan kaki.', 'It has everything, but you can still get around on foot.'],
      ['{town} ukurannya pas. Sehari dua hari sudah bisa keliling.', '{town} is just the right size. In a day or two you can see it all.'],
      ['Katanya terlalu sepi, tapi tidak ada yang mau pindah.', 'They say it is too quiet, but nobody wants to move away.'],
    ],
    small: [
      ['Ini tempat kecil. Semua orang di sini saling kenal.', 'This is a small place. Everybody here knows everybody.'],
      ['Di {town} jarang ada kejadian, dan kami suka begitu.', 'Not much happens in {town}, and we like it that way.'],
      ['Kampung kecil, Kak. Bersin sedikit, satu kampung tahu.', 'A small village. Sneeze once and the whole village knows.'],
      ['Wah, ada tamu! Ini kejadian paling seru minggu ini.', "Oh, a visitor! That's the most exciting thing this week."],
    ],
    coast: [
      ['Kami tinggal di tepi air. Ikannya enak sekali.', 'We live by the water. The fish is delicious.'],
      ['Cium baunya? Itu laut. Tidak pernah bosan.', "Smell that? That's the sea. I never tire of it."],
      ['Nelayan berangkat subuh, pulang bawa ikan paling segar.', 'The fishermen go out at dawn and come back with the freshest fish.'],
      ['Coba lihat lautnya waktu matahari terbenam. Cantik sekali.', 'Go and look at the sea at sunset. It is beautiful.'],
    ],
    inland: [
      ['Kami jauh dari laut, tapi alamnya indah.', 'We are far from the sea, but the countryside is beautiful.'],
      ['Pantai? Jauh sekali dari sini. Tapi lihat sawahnya!', 'The beach? Very far from here. But look at the rice fields!'],
      ['Di sini tanah itu segalanya. Tanahnya subur, orangnya ramah.', 'Out here the land is everything. Fertile soil, friendly people.'],
      ['Terus terang, saya jarang lihat laut. Jauh, sih.', "Honestly, I rarely see the sea. It's far."],
    ],
    high: [
      ['Kita di dataran tinggi. Pelan-pelan saja jalannya.', "We're up in the highlands. Take it slowly."],
      ['Udaranya sejuk di atas sini. Pemandangannya juara!', 'The air is cool up here. The view is the best!'],
      ['Tinggal di sini, kaki pasti kuat. Tidak ada yang datar.', 'Live here and your legs get strong. Nothing is flat.'],
      ['Pagi-pagi kabutnya turun sampai ke jalan. Seperti di atas awan.', 'In the morning the mist comes down to the road. Like being above the clouds.'],
    ],
    snowy: [
      ['Wah, dingin sekali di sini. Semuanya putih!', "Wow, it's so cold here. Everything is white!"],
      ['Salju di sini? Saya sendiri masih heran.', "Snow, here? I still can't get over it myself."],
      ['Pakai sepatu yang tebal. Esnya licin.', 'Wear thick shoes. The ice is slippery.'],
      ['Kalau salju baru turun, sepi sekali. Tenang rasanya.', 'When fresh snow falls, it is so quiet. So peaceful.'],
    ],
    forest: [
      ['Hutannya luas sekali. Jangan keluar dari jalan setapak!', "The forest is huge. Don't leave the path!"],
      ['Jalan-jalan ke hutan, biar kepala segar.', 'Go for a walk in the forest. It clears the head.'],
      ['Pagi-pagi, dengar suara burung dari hutan. Ramai sekali.', 'Early in the morning, listen to the birds in the forest. Such a racket.'],
      ['Pohon, pohon, pohon lagi. Tapi saya tidak mau tinggal di tempat lain.', "Trees, trees and more trees. But I wouldn't live anywhere else."],
    ],
    desert: [
      ['Di sini pasir sejauh mata memandang.', "Here it's sand as far as the eye can see."],
      ['Minum yang banyak, ya. Gurun tidak kenal ampun.', 'Drink plenty, all right? The desert knows no mercy.'],
      ['Malam di gurun dingin, lho. Orang tidak pernah percaya.', 'Desert nights are cold, you know. People never believe it.'],
      ['Tunggu malam nanti. Bintangnya jutaan!', 'Wait until tonight. There are millions of stars!'],
    ],
    plains: [
      ['Datar sejauh mata memandang. Hujan datang pun kelihatan dari jauh.', 'Flat as far as you can see. You can see the rain coming from far away.'],
      ['Langitnya luas di sini. Anginnya tidak ada yang menahan.', 'The sky is huge here. Nothing stops the wind.'],
      ['Padang rumputnya bagus buat ternak. Hati-hati kalau ada sapi lewat.', 'The grassland is good for livestock. Watch out when the cows go by.'],
      ['Rumputnya tidak ada habisnya. Seperti laut hijau.', 'The grass never ends. Like a green sea.'],
    ],
    tropical: [
      ['Kata lagunya, tongkat kayu dan batu jadi tanaman. Benar, lho!', 'As the song goes, sticks and stones turn into plants. It is true!'],
      ['Kalau hujan, ya hujan betul. Lalu tiba-tiba berhenti.', 'When it rains, it really rains. Then it suddenly stops.'],
      ['Coba buah-buahan di pasar. Durian, manggis, rambutan!', 'Try the fruit at the market. Durian, mangosteen, rambutan!'],
      ['Di sini musimnya cuma dua: musim hujan dan musim kemarau.', 'Here there are only two seasons: the rainy one and the dry one.'],
    ],
    landmark: [
      ['Jangan lewatkan {landmark}! Jaraknya sekitar {km} km ke arah {dir}.', "Don't miss {landmark}! It's about {km} km {dir}."],
      ['Sudah lihat {landmark}? Kira-kira {km} km ke {dir}. Tidak rugi!', "Have you seen {landmark}? About {km} km {dir}. Worth it!"],
      ['Semua orang pergi ke {landmark}. Sekitar {km} km dari sini, arah {dir}.', 'Everybody goes to {landmark}. About {km} km from here, {dir}.'],
      ['Kalau suka tempat bersejarah, ada {landmark}, {km} km ke arah {dir}.', 'If you like historic places, there is {landmark}, {km} km {dir}.'],
    ],
    landmarkNear: [
      ['{landmark} dekat sekali. Pasti ketemu!', "{landmark} is very close. You can't miss it!"],
      ['Sudah ke {landmark}? Dekat, tinggal belok saja.', "Been to {landmark} yet? It's close, just round the corner."],
      ['Tiap hari saya lihat {landmark}, dan masih kagum juga.', 'I see {landmark} every day and it still amazes me.'],
      ['Datang ke {landmark} pagi-pagi, sebelum ramai.', 'Go to {landmark} early, before the crowds.'],
    ],
    plane: [
      ['Ada pesawat kecil di lapangan sebelah {dir}. Bisa menerbangkan?', "There's a little plane in a field {dir}. Can you fly?"],
      ['Ada yang meninggalkan pesawat di lapangan, ke arah {dir}. Mau terbang?', 'Somebody left a plane in a field {dir}. Fancy a flight?'],
      ['Bisa menerbangkan pesawat? Ada satu yang menunggu di sebelah {dir}.', "Can you fly a plane? There's one waiting {dir}."],
      ['Mau lihat semuanya dari atas? Ada pesawat di sebelah {dir}.', "Want to see it all from above? There's a plane {dir}."],
    ],
    balloon: [
      ['Ada balon udara di lapangan sebelah {dir}! Bayangkan pemandangannya.', "There's a hot-air balloon in a field {dir}! Imagine the view."],
      ['Pernah naik balon udara? Ada satu di sebelah {dir}.', 'Ever flown in a balloon? There is one {dir}.'],
      ['Balon udara naik dari lapangan di sebelah {dir}. Ajaib rasanya.', 'A balloon goes up from the field {dir}. It feels like magic.'],
      ['Dari dulu saya ingin naik balon di sebelah {dir} itu. Tapi takut!', "I've always wanted to go up in that balloon {dir}. But I'm scared!"],
    ],
    boat: [
      ['Ada perahu di tepi air sebelah {dir}, kalau mau berlayar.', "There's a boat by the water {dir}, if you want to go out."],
      ['Suka laut? Ada perahu di sebelah {dir}. Asal dikembalikan, ya!', "Like the sea? There's a boat {dir}. Just bring it back!"],
      ['Ada perahu tertambat di sebelah {dir}. Dari sini bisa ke mana saja.', 'A boat is tied up {dir}. From here you can go anywhere.'],
      ['Naik perahu di sebelah {dir}, lihat pantainya dari laut.', 'Take the boat {dir} and see the coast from the sea.'],
    ],
    hot: [
      ['Hari ini panas! Cari tempat teduh, ya.', "It's hot today! Find some shade."],
      ['Aduh, panasnya! Minum dulu, kelihatannya haus.', 'Oh, this heat! Have a drink, you look thirsty.'],
      ['Panas begini, enaknya duduk di bawah pohon saja.', 'In heat like this, best just to sit under a tree.'],
      ['Gerah sekali, ya? Es kelapa muda paling cocok sekarang.', "So muggy, isn't it? Iced young coconut is just the thing now."],
      ['Panas, ya? Ini masih biasa buat kami!', "Hot, isn't it? This is just normal for us!"],
    ],
    cold: [
      ['Brr, hari ini dingin! Pakai baju hangat.', "Brr, it's cold today! Wrap up warm."],
      ['Dinginnya sampai ke tulang!', 'The cold goes right to the bone!'],
      ['Dingin, ya? Minum wedang jahe, biar hangat.', "Cold, isn't it? Have some hot ginger drink to warm up."],
      ['Hidung saya sampai beku. Mana jaketnya?', 'My nose is frozen. Where is your jacket?'],
      ['Kalau anginnya bertiup, lebih parah lagi.', 'When the wind blows, it gets even worse.'],
    ],
    mild: [
      ['Cuacanya bagus sekali hari ini.', 'The weather is lovely today.'],
      ['Tidak panas, tidak dingin. Pas sekali, ya?', "Not hot, not cold. Just right, isn't it?"],
      ['Hari seperti ini enaknya di luar.', 'A day like this is for being outside.'],
      ['Cerah sekali! Semoga nanti sore tidak hujan.', "So bright! Let's hope it doesn't rain this afternoon."],
      ['Cuaca begini yang bikin betah tinggal di sini.', 'Weather like this is why we love living here.'],
    ],
    late: [
      ['Sudah larut. Malam hari jalanan sepi.', "It's late. The streets are quiet at night."],
      ['Jam segini cuma kucing yang keluyuran. Dan kita!', 'At this hour only the cats are out. And us!'],
      ['Harusnya saya sudah tidur. Kok belum tidur?', 'I should be asleep by now. How come you are still up?'],
      ['Lihat bintangnya! Paling jelas kalau malam begini.', 'Look at the stars! Clearest on a night like this.'],
    ],
    early: [
      ['Pagi sekali! Ini waktu paling enak.', 'So early! The best time of day.'],
      ['Tukang bubur sudah lewat. Ikuti saja baunya!', 'The porridge seller has just been by. Follow the smell!'],
      ['Bangun pagi, ya? Kotanya saja belum bangun.', "An early riser, eh? The town isn't even awake yet."],
      ['Saya suka pagi di sini, sebelum ramai.', 'I love the mornings here, before the bustle starts.'],
    ],
    country: [
      ['{country} negara yang indah. Selamat menikmati!', '{country} is a beautiful country. Enjoy it!'],
      ['Bagaimana kesannya tentang {country} sejauh ini?', 'What do you make of {country} so far?'],
      ['Kelilingi {country} kalau bisa. Tiap daerah beda-beda.', 'Go all round {country} if you can. Every region is different.'],
      ['Dari Sabang sampai Merauke, {country} luas sekali!', 'From Sabang to Merauke, {country} is huge!'],
    ],
    dish: [
      ['Selama di sini, wajib coba {dish}.', "While you're here, you must try {dish}."],
      ['Sudah makan {dish}? Belum? Wah, harus!', 'Have you had {dish} yet? No? Oh, you must!'],
      ['Tidak ada yang bisa masak {dish} seenak ibu saya.', 'Nobody cooks {dish} as well as my mother.'],
      ['Kalau lapar, cari {dish}. Dijamin tidak menyesal.', "If you're hungry, find some {dish}. You won't regret it."],
    ],
    drink: [
      ['Minum {drink} dulu sebelum pergi. Ini minuman kami.', 'Have some {drink} before you go. It is what we drink here.'],
      ['Sore-sore, paling enak {drink}.', 'In the late afternoon, nothing beats {drink}.'],
      ['Belum sah ke sini kalau belum coba {drink}.', "Your visit doesn't count until you've tried {drink}."],
      ['Pesan {drink} seperti orang sini, pasti disukai.', "Order {drink} like a local and they'll love you for it."],
    ],
    festival: [
      ['Datang lagi waktu {festival}. Meriah sekali!', 'Come back for {festival}. It is so lively!'],
      ['Paling seru ke sini waktu {festival}. Semua orang merayakan.', 'The best time to come is {festival}. Everybody celebrates.'],
      ['Pernah dengar {festival}? Pasti suka.', "Ever heard of {festival}? You'd love it."],
      ['Tiap tahun saya hitung hari sampai {festival}.', 'Every year I count the days until {festival}.'],
    ],
    sport: [
      ['Di sini semua orang gila {sport}.', "Here everybody's crazy about {sport}."],
      ['Suka {sport}? Di sini kami tergila-gila.', 'Do you like {sport}? We are mad about it here.'],
      ['Kalau ada pertandingan {sport}, satu kota nonton bareng.', 'When there is a {sport} match, the whole town watches together.'],
      ['Satu keluarga saya main {sport}. Nenek cuma teriak-teriak.', 'My whole family plays {sport}. Grandma just shouts.'],
    ],
    wonder: [
      ['Kalau sempat, pergi lihat {wonder}. Tidak akan terlupakan.', "If you have time, go and see {wonder}. You'll never forget it."],
      ['Sudah lihat {wonder}? Tidak ada duanya di dunia.', 'Have you seen {wonder}? There is nothing like it in the world.'],
      ['Seumur hidup, sekali saja, harus lihat {wonder}.', 'Once in your life, at least, you have to see {wonder}.'],
      ['Waktu kecil saya pernah ke {wonder}. Sampai sekarang masih terbayang.', 'I went to {wonder} as a child. I can still picture it.'],
    ],
    pride: [
      ['Kami bangga sekali dengan {pride}.', 'We are very proud of {pride}.'],
      ['Jangan pulang sebelum kenal {pride}. Itu jati diri kami.', "Don't go home before you get to know {pride}. It is who we are."],
      ['Tahu apa yang bikin kami bangga? {pride}.', 'Know what makes us proud? {pride}.'],
      ['Tanya siapa saja soal {pride}, bisa cerita berjam-jam.', 'Ask anyone about {pride} and they will talk for hours.'],
    ],
    proverb: [
      ['Kata orang sini: “{proverb}”', 'As we say here: “{proverb}”'],
      ['Nenek saya selalu bilang: “{proverb}”', 'My grandmother always said: “{proverb}”'],
      ['Ada pepatah: “{proverb}”', 'There is a saying: “{proverb}”'],
      ['Tahu peribahasa ini? “{proverb}”', 'Do you know this proverb? “{proverb}”'],
    ],
    chat: [
      ['Dari mana asalnya? Sepertinya bukan orang sini.', "Where are you from? You don't seem to be from around here."],
      ['Santai saja, lihat-lihat. Banyak yang bisa dilihat di sini.', 'Take it easy and look around. There is a lot to see here.'],
      ['Jalan sendirian? Berani, ya.', 'Travelling alone? That takes courage.'],
      ['Sudah makan? Di ujung jalan ada warung yang enak.', "Have you eaten? There's a good little eatery at the end of the street."],
      ['Kalau tersesat, tanya saja. Orang sini ramah-ramah.', 'If you get lost, just ask. People here are friendly.'],
      ['Tempat paling bagus yang sudah dikunjungi di mana?', "What's the best place you've been to so far?"],
      ['Dari dulu saya ingin keliling dunia. Suatu hari nanti.', "I've always wanted to travel the world. One day."],
    ],
    childGreet: [
      ['Halo!', 'Hi!'],
      ['Halo, Kak! Kakak siapa?', 'Hello! Who are you?'],
      ['Hai! Kakak tinggi sekali!', "Hi! You're so tall!"],
      ['Halo, halo, halo!', 'Hello, hello, hello!'],
    ],
    childChat: [
      ['Aku bisa lari cepat sekali! Mau lihat? Nanti, deh.', 'I can run really fast! Want to see? Later, okay.'],
      ['Kakak turis, ya? Kata temanku turis itu kaya-kaya.', 'Are you a tourist? My friend says tourists are all rich.'],
      ['Gigiku copot kemarin! Lihat! Eh, tidak kelihatan, ya.', "My tooth fell out yesterday! Look! Oh, you can't see it."],
      ['Kata Ibu, jangan ngobrol sama orang asing. Tapi Kakak kelihatan baik.', "Mum says don't talk to strangers. But you look nice."],
      ['Kakak punya kucing? Aku mau kucing.', 'Do you have a cat? I want a cat.'],
      ['Kalau sudah besar, aku mau jadi pilot keliling dunia!', "When I grow up I'm going to be a pilot and fly round the world!"],
      ['Kakak bisa main layangan? Aku jago, lho!', "Can you fly a kite? I'm really good at it!"],
    ],
    childBye: [
      ['Dadah!', 'Bye-bye!'],
      ['Dah, Kak! Nanti main lagi, ya!', 'Bye! Come and play again later!'],
      ['Aku pulang dulu, dipanggil Ibu!', 'I have to go home, Mum is calling!'],
      ['Sampai jumpa, Kakak!', 'See you!'],
    ],
    grumpyGreet: [
      ['Hm. Ada apa?', 'Hm. What is it?'],
      ['Ya? Mau apa?', 'Yes? What do you want?'],
      ['Aduh. Turis lagi.', 'Oh dear. Another tourist.'],
      ['Hmm. Ya, halo.', 'Hmm. Yes, hello.'],
    ],
    grumpyChat: [
      ['Dulu di sini lebih enak, sebelum ramai orang datang.', 'It was nicer here before everybody started coming.'],
      ['Semua serba mahal. Dulu harga cabai tidak begini.', "Everything's so expensive. Chillies never used to cost this much."],
      ['Jangan halangi jalan, ya. Orang sini mau lewat.', "Don't block the way, please. People here need to get by."],
      ['Anak muda zaman sekarang, main HP terus.', 'Young people these days, always on their phones.'],
      ['Tidak tahu kenapa orang datang ke sini. Tidak ada apa-apa.', "I don't know why people come here. There's nothing."],
      ['Macet, panas, bising. Mau apa lagi?', 'Traffic jams, heat, noise. What more could you want?'],
    ],
    grumpyBye: [
      ['Ya sudah. Silakan jalan.', 'Right. Off you go.'],
      ['Ya, ya. Saya tidak mau menahan.', "Yes, yes. I won't keep you."],
      ['Hm. Permisi.', 'Hm. Excuse me.'],
      ['Hati-hati di jalan. Dan tutup pagarnya!', 'Mind how you go. And shut the gate!'],
    ],
    elderChat: [
      ['Waktu saya muda, di sini masih sawah semua.', 'When I was young, all of this was rice fields.'],
      ['Seumur hidup saya tinggal di sini. Delapan puluh tahun! Bayangkan.', "I've lived here all my life. Eighty years! Imagine."],
      ['Dulu kami ke mana-mana jalan kaki. Bagus, jalan kaki itu sehat!', 'Back then we walked everywhere. Good, walking is healthy!'],
      ['Cucu-cucu saya sekarang di luar negeri. Tiap Minggu mereka telepon.', 'My grandchildren live abroad now. They call every Sunday.'],
      ['Zaman berubah cepat sekali. Tapi jalan-jalan lama tetap sama.', 'Times change so fast. But the old streets stay the same.'],
    ],
    chattyChat: [
      ['Aduh, senang sekali ketemu pelancong! Ceritakan semuanya. Eh, tunggu, saya dulu.', 'Oh, I love meeting travellers! Tell me everything. No, wait, me first.'],
      ['Sepupu saya pernah merantau. Pulang-pulang bawa jenggot dan istri!', 'My cousin once went off to work far away. Came back with a beard and a wife!'],
      ['Kata teman-teman, saya bisa ngobrol seharian. Memang benar!', 'My friends say I could chat all day. They are right!'],
      ['Sudah makan belum? Kelihatannya lapar. Semua orang kelihatan lapar buat saya.', 'Have you eaten? You look hungry. Everybody looks hungry to me.'],
      ['Mau tahu rahasia? Pemandangan paling bagus itu dari bukit di belakang pasar.', 'Want a secret? The best view in town is from the hill behind the market.'],
    ],
    bye: [
      ['Sampai jumpa! Selamat jalan.', 'Goodbye! Have a good trip.'],
      ['Hati-hati di jalan, ya!', 'Take care on the road!'],
      ['Selamat jalan-jalan! Semoga menyenangkan.', 'Enjoy your travels! Hope it is fun.'],
      ['Dadah! Mampir lagi, ya.', 'Bye! Drop by again.'],
      ['Senang ngobrol. Jaga diri baik-baik!', 'Nice chatting. Look after yourself!'],
      ['Ayo, jalan lagi! Masih banyak yang bisa dilihat.', 'Off you go! There is still so much to see.'],
    ],
  },
  countries: {
    // A bare noun phrase, lower-case unless a proper name: Indonesian has no article to agree.
    IDN: {
      dish: ['rendang', 'rendang (slow-cooked spiced beef)'],
      drink: ['es teh manis', 'sweet iced tea'],
      festival: ['Lebaran', 'Lebaran, the feast after Ramadan'],
      sport: ['bulu tangkis', 'badminton'],
      wonder: ['Gunung Bromo', 'Mount Bromo'],
      pride: ['batik', 'batik'],
      proverb: ['Di mana bumi dipijak, di situ langit dijunjung', 'Wherever you tread the earth, hold up the sky above it'],
    },
  },
};

export default ID;
