import type { Language } from '../phrases.ts';

/**
 * Italian: Italy, San Marino and the Vatican. A stranger is spoken to as
 * *tu*, the way a friendly passer-by would, and nothing agrees with the
 * speaker's or the listener's sex (no *benvenuto*, no *sei stanco*).
 */
const IT: Language = {
  locale: 'it',
  name: 'Italian',
  join: ' ',
  compass: ['a nord', 'a nord-est', 'a est', 'a sud-est', 'a sud', 'a sud-ovest', 'a ovest', 'a nord-ovest'],
  lines: {
    morning: [
      ['Buongiorno!', 'Good morning!'],
      ['Buondì!', 'Morning!'],
      ['Salve! Bella giornata, eh?', 'Hello! Lovely day, eh?'],
      ['Oh, buongiorno a te!', 'Oh, good morning to you!'],
    ],
    afternoon: [
      ['Buon pomeriggio!', 'Good afternoon!'],
      ['Salve!', 'Hello!'],
      ['Ciao! Bel pomeriggio, eh?', 'Hi! Nice afternoon, eh?'],
      ['Oh, ciao! Tutto bene?', 'Oh, hi! All good?'],
    ],
    evening: [
      ['Buonasera!', 'Good evening!'],
      ['Sera!', 'Evening!'],
      ['Buonasera! Bella serata per due passi.', 'Good evening! A nice evening for a stroll.'],
      ['Ah, buonasera a te.', 'Ah, good evening to you.'],
    ],
    night: [
      ['Buonasera! È tardi, vero?', "Good evening! It's late, isn't it?"],
      ['Oh! Mi hai fatto prendere un colpo. Ciao!', 'Oh! You gave me a fright. Hello!'],
      ['Ciao! Passeggiata notturna?', 'Hi! A night-time walk?'],
      ['Buonasera! O è già buongiorno?', 'Good evening! Or is it good morning already?'],
    ],
    again: [
      ['Oh, di nuovo tu! Ciao!', 'Oh, you again! Hi!'],
      ['Ancora qui? Che piacere rivederti.', 'Still here? What a pleasure to see you again.'],
      ['Ciao di nuovo!', 'Hello again!'],
      ['Ci conosciamo già! Stai ancora esplorando?', 'We already know each other! Still exploring?'],
      ['Ah, sei tu! Hai trovato la strada?', "Ah, it's you! Did you find your way?"],
    ],
    welcome: [
      ['Benvenuti a {town}!', 'Welcome to {town}!'],
      ['Siamo a {town}. Sei in visita?', 'This is {town}. Are you visiting?'],
      ['Prima volta a {town}?', 'First time in {town}?'],
      ['Hai scelto proprio una bella giornata per vedere {town}.', "You've picked a really nice day to see {town}."],
      ['{town} ti dà il benvenuto!', '{town} bids you welcome!'],
      ['Allora, cosa ti porta a {town}?', 'So, what brings you to {town}?'],
    ],
    capitalHere: [
      ['{town} è la capitale, sai? Qui succede tutto.', '{town} is the capital, you know. Everything happens here.'],
      ['Qui a {town} c’è il governo. Tutta gente in giacca e cravatta.', "The government is here in {town}. All people in jacket and tie."],
      ['Essendo la capitale, {town} non dorme mai.', 'Being the capital, {town} never sleeps.'],
      ['Siamo nella capitale! Palazzi, ministeri e traffico.', "We're in the capital! Palaces, ministries and traffic."],
    ],
    capitalThere: [
      ['La nostra capitale è {capital}. Merita una visita.', 'Our capital is {capital}. It deserves a visit.'],
      ['Hai già visto {capital}? È la nostra capitale.', "Have you seen {capital} yet? It's our capital."],
      ['A {capital} credono di comandare loro. E in effetti è così.', 'In {capital} they think they run things. And actually they do.'],
      ['{capital} sarà pure la capitale, ma io sto meglio qui.', '{capital} may well be the capital, but I’m better off here.'],
    ],
    big: [
      ['È una grande città. Qui è facile perdersi!', "It's a big city. It's easy to get lost here!"],
      ['Quanta gente! Ci vivi una vita e non conosci tutte le strade.', "So many people! You live here a lifetime and don't know every street."],
      ['Il traffico, qui, è un disastro. Però c’è sempre qualcosa da fare.', "The traffic here is a disaster. But there's always something to do."],
      ['Una città così non si ferma mai. Mi piace, quasi sempre.', 'A city like this never stops. I like it, most of the time.'],
    ],
    middling: [
      ['Né grande né piccola. Proprio giusta.', 'Not big, not small. Just right.'],
      ['Abbastanza grande per avere tutto, abbastanza piccola da girarla a piedi.', 'Big enough to have everything, small enough to see on foot.'],
      ['{town} ha la misura giusta. In un paio di giorni la vedi tutta.', '{town} is just the right size. You can see all of it in a couple of days.'],
      ['Tutti dicono che è troppo tranquilla, e nessuno se ne va mai.', 'Everybody says it is too quiet, and nobody ever leaves.'],
    ],
    small: [
      ['È un posto piccolo. Qui ci conosciamo tutti.', "It's a small place. We all know each other here."],
      ['Paese piccolo: qui si sa tutto di tutti.', 'Small village: here everyone knows everything about everyone.'],
      ['A {town} non succede quasi niente, e ci piace così.', 'Hardly anything happens in {town}, and we like it that way.'],
      ['Sei la novità della settimana, lo sai?', "You're the news of the week, you know?"],
    ],
    coast: [
      ['Qui viviamo sul mare. Il pesce è ottimo.', 'We live by the sea here. The fish is excellent.'],
      ['Vai a guardare il mare. Ogni giorno è diverso.', 'Go and look at the sea. Every day it is different.'],
      ['Senti quest’odore? È il mare. Non ci si stanca mai.', "Smell that? That's the sea. You never get tired of it."],
      ['I pescatori escono all’alba e tornano col pesce più fresco che ci sia.', 'The fishermen go out at dawn and come back with the freshest fish there is.'],
    ],
    inland: [
      ['Siamo lontani dal mare, ma questa terra è bellissima.', 'We are far from the sea, but this land is beautiful.'],
      ['Spiaggia niente, mi spiace. Però guarda che campagna.', 'No beach, sorry. But look at this countryside.'],
      ['Il mare? Per arrivarci ci vuole una giornata.', 'The sea? It takes a whole day to get there.'],
      ['Qui la terra è tutto. Buona terra, brava gente.', 'Here the land is everything. Good soil, good people.'],
    ],
    high: [
      ['Qui siamo in alto. Vacci piano, l’aria è sottile.', "We're high up here. Take it easy, the air is thin."],
      ['Da quassù il panorama è la cosa più bella che abbiamo.', 'From up here the view is the most beautiful thing we have.'],
      ['Vivendo quassù ti vengono due gambe d’acciaio. Niente è in piano.', 'Living up here gives you legs of steel. Nothing is flat.'],
      ['Occhio al fiato! La montagna ci vuole un po’ ad abituarsi.', 'Mind your breath! The mountains take some getting used to.'],
    ],
    snowy: [
      ['Qui la neve dura mezzo anno. L’altro mezzo ci lamentiamo del fango.', 'Snow lasts half the year here. The other half we complain about the mud.'],
      ['È tutto bianco. Ti servono scarpe migliori di quelle.', "It's all white. You'll need better shoes than those."],
      ['Il freddo non ci pesa. Tiene lontani i turisti, presenti esclusi!', "The cold doesn't bother us. It keeps tourists away, present company excepted!"],
      ['Con la neve fresca c’è un silenzio che si sentono i pensieri.', 'With fresh snow it is so quiet you can hear your thoughts.'],
    ],
    forest: [
      ['Qui il bosco non finisce mai. Resta sul sentiero!', 'The woods never end round here. Stay on the path!'],
      ['Fatti una passeggiata nel bosco. Schiarisce le idee.', 'Take a walk in the woods. It clears the mind.'],
      ['In autunno andiamo tutti a funghi e a castagne.', 'In autumn we all go out for mushrooms and chestnuts.'],
      ['Alberi, alberi e ancora alberi. Non vivrei da nessun’altra parte.', "Trees, trees and more trees. I wouldn't live anywhere else."],
    ],
    desert: [
      ['Qui è sabbia a perdita d’occhio.', "Here it's sand as far as the eye can see."],
      ['Bevi tanta acqua. Il deserto non perdona.', 'Drink lots of water. The desert does not forgive.'],
      ['Di notte nel deserto fa freddo, sai? Nessuno ci crede.', 'At night the desert is cold, you know? Nobody believes it.'],
      ['Aspetta le stelle stanotte. Qui se ne vedono milioni.', 'Wait for the stars tonight. Here you can see millions of them.'],
    ],
    plains: [
      ['È tutto piatto. Il temporale lo vedi arrivare da un giorno prima.', "It's all flat. You can see a storm coming a day ahead."],
      ['Qui c’è un cielo enorme, e niente che fermi il vento.', "There's a huge sky here, and nothing to stop the wind."],
      ['Ottimi pascoli, tutto intorno. Occhio alle mandrie!', 'Excellent pasture all around. Watch out for the herds!'],
      ['L’erba non finisce mai. Sembra un mare verde.', 'The grass never ends. It looks like a green sea.'],
    ],
    tropical: [
      ['Qui cresce di tutto. Pianti un bastone e diventa un albero.', 'Everything grows here. Plant a stick and it becomes a tree.'],
      ['Quando piove, qui, viene giù il mondo. Poi smette di colpo.', 'When it rains here, the sky falls down. Then it stops all at once.'],
      ['Assaggia la frutta del mercato. Non hai mai sentito sapori così.', "Taste the fruit at the market. You've never had flavours like it."],
      ['È verde tutto l’anno. L’inverno? E che cos’è?', "It's green all year round. Winter? And what's that?"],
    ],
    landmark: [
      ['Non perderti {landmark}! È a circa {km} km {dir}.', "Don't miss {landmark}! It's about {km} km {dir}."],
      ['Hai visto {landmark}? Sta a {km} km {dir}, e ne vale la pena.', "Have you seen {landmark}? It's {km} km {dir}, and worth it."],
      ['Ci vanno tutti, a vedere {landmark}: circa {km} km {dir}.', 'Everyone goes to see {landmark}: about {km} km {dir}.'],
      ['Se ti piacciono le cose antiche, {landmark} è a {km} km {dir}.', 'If you like old things, {landmark} is {km} km {dir}.'],
    ],
    landmarkNear: [
      ['{landmark} è qui vicino. Non puoi sbagliare!', "{landmark} is close by. You can't miss it!"],
      ['Hai già visto {landmark}? È proprio dietro l’angolo.', "Have you seen {landmark} yet? It's just round the corner."],
      ['Vediamo {landmark} tutti i giorni, e ancora ci toglie il fiato.', 'We see {landmark} every day, and it still takes our breath away.'],
      ['Vai a vedere {landmark}, è qui. Presto, prima della folla.', "Go and see {landmark}, it's right here. Early, before the crowds."],
    ],
    plane: [
      ['C’è un piccolo aereo in un campo {dir}, se sai pilotare!', "There's a little plane in a field {dir}, if you can fly!"],
      ['Qualcuno ha lasciato un aereo in un campo {dir}. Ti va un volo?', 'Someone left a plane in a field {dir}. Fancy a flight?'],
      ['Sai pilotare? C’è un aereo che aspetta {dir}.', "Can you fly? There's a plane waiting {dir}."],
      ['Se vuoi vedere tutto dall’alto, c’è un aereo {dir}.', "If you want to see it all from above, there's a plane {dir}."],
    ],
    balloon: [
      ['C’è una mongolfiera in un campo {dir}! Pensa che panorama.', "There's a hot-air balloon in a field {dir}! Imagine the view."],
      ['Hai mai volato in mongolfiera? Ce n’è una {dir}.', 'Have you ever flown in a balloon? There is one {dir}.'],
      ['Dal campo {dir} si alza una mongolfiera. È una magia.', 'A balloon goes up from the field {dir}. It’s magic.'],
      ['Ho sempre voluto provare la mongolfiera {dir}. Ma che paura!', "I've always wanted to try the balloon {dir}. But how scary!"],
    ],
    boat: [
      ['C’è una barca in riva {dir}, se vuoi uscire in acqua.', "There's a boat on the shore {dir}, if you want to go out on the water."],
      ['Se ti piace il mare, c’è una barca {dir}. Basta che la riporti!', "If you like the sea, there's a boat {dir}. Just bring it back!"],
      ['C’è una barca ormeggiata {dir}. Da qui si va dappertutto.', 'A boat is moored {dir}. From here you can go anywhere.'],
      ['Prendi la barca {dir} e guarda la costa dal mare.', 'Take the boat {dir} and see the coast from the sea.'],
    ],
    hot: [
      ['Oggi fa caldo! Cerca un po’ d’ombra.', "It's hot today! Find a bit of shade."],
      ['Che afa! Bevi un po’ d’acqua, ne hai bisogno.', 'What a stifling heat! Drink some water, you need it.'],
      ['Con questo caldo si può solo stare all’ombra.', 'In this heat you can only sit in the shade.'],
      ['Fa così caldo che anche i gatti restano a casa.', 'In this heat even the cats stay indoors.'],
      ['Si muore di caldo, eh? E per noi oggi è fresco!', 'Boiling, eh? And for us today is cool!'],
    ],
    cold: [
      ['Brr, oggi fa freddo! Copriti bene.', "Brr, it's cold today! Wrap up well."],
      ['Si gela! Dove sono i guanti?', "It's freezing! Where are your gloves?"],
      ['Fa così freddo che non mi sento più il naso.', "It's so cold I can't feel my nose any more."],
      ['Freddino, eh? Aspetta che si alzi il vento.', 'A bit nippy, eh? Wait till the wind picks up.'],
      ['Prenditi qualcosa di caldo al bar. Aiuta.', 'Get yourself something hot at the café. It helps.'],
    ],
    mild: [
      ['Che bel tempo oggi.', 'What lovely weather today.'],
      ['Né caldo né freddo. Una giornata perfetta, no?', 'Not hot, not cold. A perfect day, right?'],
      ['Con una giornata così, viene voglia di stare fuori.', 'On a day like this, you feel like being outside.'],
      ['Che bella giornata! Speriamo che duri.', "What a beautiful day! Let's hope it lasts."],
      ['È per giornate come questa che viviamo qui.', 'Days like this are why we live here.'],
    ],
    late: [
      ['È tardi. Di notte le strade sono tranquille.', "It's late. At night the streets are quiet."],
      ['A quest’ora in giro ci sono solo i gatti. E noi!', 'At this hour only the cats are out. And us!'],
      ['Dovrei essere a letto. E tu che ci fai in giro?', 'I should be in bed. And what are you doing out?'],
      ['Guarda che stelle! Da qui si vedono benissimo.', 'Look at those stars! You can see them beautifully from here.'],
    ],
    early: [
      ['Già in piedi? È la parte più bella della giornata.', 'Up already? It is the best part of the day.'],
      ['Il forno ha appena aperto. Segui il profumo!', 'The bakery has just opened. Follow the smell!'],
      ['Il bar ha appena alzato la saracinesca. Un caffè ci sta.', 'The café has just raised its shutter. A coffee would go down well.'],
      ['Mi piace la mattina qui, prima che cominci il rumore.', 'I love the morning here, before the noise starts.'],
    ],
    country: [
      ['{country}: un paese bellissimo. Goditelo!', '{country}: a beautiful country. Enjoy it!'],
      ['Allora, che te ne pare? {country} ti piace?', 'So, what do you think? Do you like {country}?'],
      ['{country} ha un cuore grande, vedrai.', '{country} has a big heart, you’ll see.'],
      ['Viaggia in lungo e in largo, se puoi: {country} cambia a ogni angolo.', '{country} changes at every corner: travel far and wide if you can.'],
    ],
    dish: [
      ['Finché sei qui, devi assaggiare {dish}.', 'While you are here, you have to try {dish}.'],
      ['Hai già mangiato {dish}? No? Ma come!', "Have you had {dish} yet? No? How can that be!"],
      ['Nessuno prepara {dish} come mia madre.', 'Nobody makes {dish} like my mother.'],
      ['Se hai fame, ordina {dish}. Non te ne pentirai.', "If you're hungry, order {dish}. You won't regret it."],
    ],
    drink: [
      ['Prima di partire, prova {drink}. È quello che beviamo qui.', "Before you leave, try {drink}. It's what we drink here."],
      ['A fine giornata non c’è niente come {drink}.', "At the end of the day there's nothing like {drink}."],
      ['Se non hai mai provato {drink}, non sai cosa ti perdi.', "If you've never tried {drink}, you don't know what you're missing."],
      ['Ordina {drink} come uno del posto e ti vorranno tutti bene.', 'Order {drink} like a local and everyone will love you.'],
    ],
    festival: [
      ['Devi tornare per {festival}. È una meraviglia!', "You must come back for {festival}. It's wonderful!"],
      ['Il periodo migliore per venire? {festival}, senza dubbio.', 'The best time to come? {festival}, no doubt about it.'],
      ['Hai mai sentito parlare di {festival}? Ti piacerebbe.', "Have you ever heard of {festival}? You'd love it."],
      ['Ogni anno aspetto {festival} come un bambino.', 'Every year I wait for {festival} like a child.'],
    ],
    sport: [
      ['Qui si vive per {sport}. Ci giocano tutti.', 'Here we live for {sport}. Everyone plays.'],
      ['Ti piace {sport}? Qui siamo pazzi per quello.', 'Do you like {sport}? Here we are crazy about it.'],
      ['Nei giorni di partita, in città l’unico argomento è {sport}.', 'On match days, the only topic in town is {sport}.'],
      ['Tutta la mia famiglia ama {sport}. Mia nonna, più che altro, urla.', 'My whole family loves {sport}. My grandmother mostly shouts.'],
    ],
    wonder: [
      ['Se hai tempo, vai a vedere {wonder}. Ne vale la pena.', "If you have time, go and see {wonder}. It's worth it."],
      ['Hai visto {wonder}? Non c’è niente di simile al mondo.', 'Have you seen {wonder}? There is nothing like it in the world.'],
      ['Tutti dovrebbero vedere {wonder} almeno una volta nella vita.', 'Everybody should see {wonder} at least once in their life.'],
      ['Da giovane mi portarono a vedere {wonder}. Ci penso ancora.', 'When I was young they took me to see {wonder}. I still think about it.'],
    ],
    pride: [
      ['Sai qual è il nostro orgoglio? {pride}.', 'You know what our pride is? {pride}.'],
      ['Non andartene senza conoscere {pride}. È quello che siamo.', "Don't leave without learning about {pride}. It's who we are."],
      ['Qui una cosa ci rende fieri più di tutte: {pride}.', 'One thing here makes us prouder than anything: {pride}.'],
      ['Nomina {pride} a chiunque qui, e parlerà per ore.', 'Mention {pride} to anyone here, and they will talk for hours.'],
    ],
    proverb: [
      ['Come si dice qui: «{proverb}»', 'As we say here: “{proverb}”'],
      ['Mia nonna diceva sempre: «{proverb}»', 'My grandmother always said: “{proverb}”'],
      ['C’è un proverbio da noi: «{proverb}»', 'There is a saying here: “{proverb}”'],
      ['Lo conosci il detto? «{proverb}»', 'Do you know the saying? “{proverb}”'],
    ],
    chat: [
      ['Di dove sei? Non sei di qui.', "Where are you from? You're not from here."],
      ['Prenditi il tuo tempo e guardati intorno. C’è molto da vedere.', "Take your time and look around. There's a lot to see."],
      ['Se ti perdi, chiedi pure. La gente qui è gentile.', 'If you get lost, just ask. People here are kind.'],
      ['Qual è il posto più bello che hai visto finora?', "What's the most beautiful place you've seen so far?"],
      ['Ho sempre sognato di viaggiare. Prima o poi lo faccio.', "I've always dreamed of travelling. Sooner or later I'll do it."],
      ['Hai una cartina? Una cartina in tasca non guasta mai.', 'Have you got a map? A map in your pocket never hurts.'],
      ['Hai già preso un caffè? Qui il caffè è una cosa seria.', 'Have you had a coffee yet? Coffee is a serious matter here.'],
      ['Da quanto tempo sei in viaggio? Hai l’aria di chi ha visto tanto.', "How long have you been travelling? You look like someone who's seen a lot."],
    ],
    childGreet: [
      ['Ciao!', 'Hi!'],
      ['Ciao! Tu chi sei?', 'Hi! Who are you?'],
      ['Ciao! Arrivi fino al cielo!', 'Hi! You reach all the way to the sky!'],
      ['Ciao ciao ciao!', 'Hi hi hi!'],
    ],
    childChat: [
      ['So correre velocissimo! Vuoi vedere? Magari dopo.', 'I can run super fast! Want to see? Maybe later.'],
      ['Sei un turista? Il mio amico dice che i turisti sono ricchi.', 'Are you a tourist? My friend says tourists are rich.'],
      ['Ieri mi è caduto un dente! Guarda! Ah, non si vede.', "I lost a tooth yesterday! Look! Oh, you can't see it."],
      ['La mamma dice di non parlare con gli sconosciuti. Ma tu hai una faccia simpatica.', 'Mum says not to talk to strangers. But you have a nice face.'],
      ['Hai un cane? Io voglio un cane. Anche un gatto va bene.', 'Do you have a dog? I want a dog. A cat would do too.'],
      ['Da grande farò il giro del mondo in aereo!', "When I grow up I'm going to fly all round the world!"],
      ['Conosci qualche gioco? Io ne conosco un sacco.', 'Do you know any games? I know loads.'],
      ['Oggi a merenda c’era pane e Nutella. È la cosa più buona del mondo!', 'Today for snack there was bread and Nutella. Best thing in the world!'],
    ],
    childBye: [
      ['Ciao ciao!', 'Bye bye!'],
      ['Ciao! Torna a giocare!', 'Bye! Come back and play!'],
      ['Devo andare, mi chiama la mamma!', 'I have to go, Mum is calling me!'],
      ['Ci vediamo! Anzi no, ci vediamo dopo!', 'See you! No wait, see you later!'],
    ],
    grumpyGreet: [
      ['Mah. Che c’è?', 'Hmm. What is it?'],
      ['Sì? Che vuoi?', 'Yes? What do you want?'],
      ['Uff. Altri turisti.', 'Ugh. More tourists.'],
      ['Mh. Buongiorno, se proprio dobbiamo.', 'Hm. Good day, if we really must.'],
    ],
    grumpyChat: [
      ['Si stava meglio quando si stava peggio.', 'We were better off when we were worse off.'],
      ['Costa tutto il doppio. Il caffè, poi, non ne parliamo.', "Everything costs double. And the coffee, let's not even go there."],
      ['Non stare in mezzo al marciapiede, per favore. Qui c’è gente che lavora.', "Don't stand in the middle of the pavement, please. People work here."],
      ['I giovani d’oggi, sempre col telefono in mano.', 'Young people today, always with a phone in their hand.'],
      ['Non so cosa venga a vedere la gente qui. Non c’è niente.', "I don't know what people come to see here. There's nothing."],
      ['E questo lo chiamano caffè? Ai miei tempi sì che era caffè.', 'And they call this coffee? In my day, that was coffee.'],
    ],
    grumpyBye: [
      ['Va be’. Vai, vai.', 'Fine. Go on, go on.'],
      ['Non ti trattengo.', "I won't keep you."],
      ['Mh. Arrivederci.', 'Hm. Goodbye.'],
      ['Vai pure. E chiudi il cancello.', 'Off you go. And shut the gate.'],
    ],
    elderChat: [
      ['Quando ero giovane, qui erano tutti campi.', 'When I was young, all this was fields.'],
      ['Ho vissuto qui tutta la vita. Ottant’anni! Ci credi?', "I've lived here all my life. Eighty years! Can you believe it?"],
      ['Ai miei tempi si andava dappertutto a piedi. Anche tu cammini: fai bene!', 'In my day we walked everywhere. You walk too: good for you!'],
      ['I miei nipoti vivono all’estero. Mi chiamano ogni domenica.', 'My grandchildren live abroad. They call me every Sunday.'],
      ['Cambia tutto così in fretta. Ma le vecchie strade sono sempre quelle.', 'Everything changes so fast. But the old streets are still the same.'],
      ['Una volta la domenica si ballava in piazza. Che tempi!', 'Once upon a time we danced in the square on Sundays. What times!'],
    ],
    chattyChat: [
      ['Che bello incontrare chi viaggia! Raccontami tutto. Anzi no, prima racconto io.', 'How lovely to meet a traveller! Tell me everything. No, wait, I go first.'],
      ['Mio cugino una volta è partito per un viaggio. È tornato con la barba e una moglie!', 'My cousin went travelling once. He came back with a beard and a wife!'],
      ['I miei amici dicono che parlo troppo. Non hanno tutti i torti!', "My friends say I talk too much. They're not entirely wrong!"],
      ['Hai mangiato? Hai l’aria affamata. A me sembrano tutti affamati.', 'Have you eaten? You look hungry. Everyone looks hungry to me.'],
      ['Ti dico un segreto: la vista più bella è dalla collina dietro la chiesa.', "Let me tell you a secret: the best view is from the hill behind the church."],
      ['E poi mia zia, sai mia zia? No, non la conosci. Beh, ti racconto.', "And then my aunt, you know my aunt? No, you don't. Well, let me tell you."],
    ],
    bye: [
      ['Arrivederci! Buon viaggio.', 'Goodbye! Have a good trip.'],
      ['Stammi bene! Goditi il resto del viaggio.', 'Take care! Enjoy the rest of your trip.'],
      ['Buona strada!', 'Safe travels!'],
      ['Ciao! Torna a trovarci.', 'Bye! Come back and see us.'],
      ['È stato un piacere. Abbi cura di te!', 'It was a pleasure. Look after yourself!'],
      ['Vai, vai! C’è tanto da vedere.', "Off you go! There's so much to see."],
    ],
  },
  countries: {
    // Every fact carries its definite article ("la pizza", "l'espresso") and
    // stands where no preposition would contract with it: after a verb, after
    // a colon or a question, or opening a sentence.
    ITA: {
      dish: ['la pizza napoletana', 'Neapolitan pizza'],
      drink: ['l’espresso', 'espresso'],
      festival: ['il Carnevale di Venezia', 'the Venice Carnival'],
      sport: ['il calcio', 'football'],
      wonder: ['le Dolomiti', 'the Dolomites'],
      pride: ['l’arte del Rinascimento', 'Renaissance art'],
      proverb: ['Chi va piano va sano e va lontano', 'Who goes slowly goes safely and goes far'],
    },
    SMR: {
      dish: ['la torta Tre Monti', 'Tre Monti cake'],
      festival: ['la festa di San Marino', 'the feast of Saint Marinus'],
      sport: ['il calcio', 'football'],
      wonder: ['il monte Titano', 'Mount Titano'],
      pride: ['la repubblica più antica del mondo', 'the oldest republic in the world'],
      proverb: ['Chi fa da sé fa per tre', 'Who does it alone does it for three'],
    },
    VAT: {
      festival: ['il Natale', 'Christmas'],
      wonder: ['la Cappella Sistina', 'the Sistine Chapel'],
      pride: ['i Musei Vaticani', 'the Vatican Museums'],
      proverb: ['Tutte le strade portano a Roma', 'All roads lead to Rome'],
    },
  },
};

export default IT;
