import type { Language } from '../phrases.ts';

/**
 * Japanese: polite です/ます to a stranger, plain speech for a child and a
 * curt old-timer. Particles never change with the word before them, so a name
 * takes は, に or の as it stands; a direction is a bare compass word that the
 * template follows with に, へ or の.
 */
const JA: Language = {
  locale: 'ja',
  name: 'Japanese',
  join: '',
  compass: ['北', '北東', '東', '南東', '南', '南西', '西', '北西'],
  lines: {
    morning: [
      ['おはようございます！', 'Good morning!'],
      ['おはようございます。いい朝ですね。', "Good morning. Lovely morning, isn't it?"],
      ['あ、おはようございます！', 'Oh, good morning!'],
      ['おはようございます。今日も一日がんばりましょう。', "Good morning. Let's make the most of the day."],
    ],
    afternoon: [
      ['こんにちは！', 'Hello!'],
      ['あ、どうも、こんにちは。', 'Oh, hi there, hello.'],
      ['こんにちは。いい午後ですね。', 'Hello. Nice afternoon, this.'],
      ['こんにちは！お散歩ですか？', 'Hello! Out for a stroll?'],
    ],
    evening: [
      ['こんばんは！', 'Good evening!'],
      ['こんばんは。散歩にいい時間ですね。', 'Good evening. A nice hour for a walk.'],
      ['あ、こんばんは。', 'Oh, good evening.'],
      ['こんばんは！もう日が暮れますね。', "Good evening! The sun's going down already."],
    ],
    night: [
      ['こんばんは！もう遅い時間ですね。', "Good evening! It's getting late, isn't it?"],
      ['わっ、びっくりした！こんばんは。', 'Whoa, you made me jump! Good evening.'],
      ['こんばんは。夜のお散歩ですか？', 'Good evening. Out for a night walk?'],
      ['こんな時間にどうも。眠れないんですか？', "Hello, at this hour. Can't sleep?"],
    ],
    again: [
      ['あ、また会いましたね！', 'Oh, we meet again!'],
      ['おや、さっきの方ですね。こんにちは！', "Oh, it's you from before. Hello!"],
      ['またお会いしましたね。まだ観光中ですか？', 'We meet again. Still sightseeing?'],
      ['おや、またですね。道はわかりましたか？', 'Oh, you again. Did you find your way?'],
      ['ご縁がありますね。また会えてうれしいです。', 'We must be fated. Nice to see you again.'],
    ],
    welcome: [
      ['{town}へようこそ！', 'Welcome to {town}!'],
      ['ここは{town}です。観光ですか？', 'This is {town}. Are you sightseeing?'],
      ['{town}は初めてですか？', 'Is this your first time in {town}?'],
      ['いい日に{town}に来ましたね。', 'You picked a good day to come to {town}.'],
      ['ようこそ、ようこそ！{town}はいいところですよ。', "Welcome, welcome! {town} is a nice place, you'll see."],
      ['{town}には何をしに来たんですか？', 'So what brings you to {town}?'],
    ],
    capitalHere: [
      ['{town}はこの国の首都です。', '{town} is the capital of this country.'],
      ['ここは首都ですからね。何でも{town}に集まるんです。', "This is the capital, after all. Everything ends up in {town}."],
      ['国会も{town}にあるんですよ。スーツの人が多いでしょう？', 'The parliament is here in {town} too. Lots of people in suits, see?'],
      ['首都だけあって、{town}は眠らない街です。', 'Being the capital, {town} is a city that never sleeps.'],
    ],
    capitalThere: [
      ['首都は{capital}です。一度は行く価値がありますよ。', "The capital is {capital}. It's worth going at least once."],
      ['{capital}にはもう行きましたか？首都ですよ。', "Have you been to {capital} yet? It's the capital."],
      ['{capital}の人は都会ぶってますけど、ここのほうが住みやすいですよ。', 'People in {capital} act very big-city, but life is easier here.'],
      ['{capital}は大きいけど、人が多すぎて疲れますね。', '{capital} is big, but all those people wear you out.'],
    ],
    big: [
      ['ここは大きな街です。迷子になりやすいですよ！', "This is a big city. It's easy to get lost!"],
      ['人が多いでしょう？一生住んでても全部の道はわかりません。', "So many people, right? You could live here all your life and not know every street."],
      ['電車は便利だけど、朝のラッシュは地獄ですよ。', 'The trains are handy, but the morning rush is hell.'],
      ['大都会は忙しいけど、いつも何かやってて楽しいです。', "A big city is hectic, but there's always something on. It's fun."],
    ],
    middling: [
      ['大きすぎず、小さすぎず。ちょうどいい街です。', 'Not too big, not too small. Just the right size.'],
      ['何でもそろってて、歩いて回れる。いい大きさでしょう？', "It has everything and you can walk it. Nice size, isn't it?"],
      ['{town}なら一日二日で全部見られますよ。', 'You can see all of {town} in a day or two.'],
      ['みんな退屈だって言うけど、結局だれも出ていかないんです。', 'Everyone says it is boring, and in the end nobody leaves.'],
    ],
    small: [
      ['ここは小さな町です。みんな顔見知りなんですよ。', "It's a small town. Everybody knows everybody."],
      ['小さい町だから、うわさはすぐ広まります。', 'Small town, so gossip travels fast.'],
      ['{town}には何もないけど、それがいいんです。', "There's nothing in {town}, and that's what's good about it."],
      ['よそから人が来るなんて、今週一番の事件ですよ！', "Someone from outside! That's the big event of the week!"],
    ],
    coast: [
      ['ここは水辺の町です。魚がとてもおいしいですよ。', 'This is a town by the water. The fish is delicious.'],
      ['海を見てきてください。毎日表情が違うんです。', 'Go and look at the sea. It has a different face every day.'],
      ['潮の香りがするでしょう？何年住んでも飽きません。', "Smell the sea air? You never tire of it, however long you live here."],
      ['朝早く船が出て、とれたての魚が市場に並ぶんですよ。', 'The boats go out at dawn and the fresh catch fills the market.'],
    ],
    inland: [
      ['海からは遠いですが、このあたりの景色はきれいです。', "We're far from the sea, but the scenery round here is beautiful."],
      ['海はないけど、山と田んぼがありますから。', 'No sea, but we have mountains and rice fields.'],
      ['海なんて、もう何年も見てないですね。', "The sea? I haven't seen it in years."],
      ['内陸は夏暑くて冬寒い。でも野菜がおいしいんです。', 'Inland, summers are hot and winters cold. But the vegetables are delicious.'],
    ],
    high: [
      ['ここは標高が高いんです。ゆっくり歩いてくださいね。', "We're high up here. Walk slowly."],
      ['山の上だから、景色だけは自慢できます。', "Up on the mountain like this, the view is the one thing we can boast of."],
      ['坂ばかりで、足腰が強くなりますよ。', "It's all slopes. Your legs will get strong."],
      ['空気が薄いでしょう？慣れるまで少しかかります。', 'The air is thin, right? It takes a while to get used to.'],
    ],
    snowy: [
      ['冬は雪かきが毎日の仕事です。', 'In winter, shovelling snow is a daily job.'],
      ['一面真っ白でしょう？その靴だと滑りますよ。', "White everywhere, isn't it? You'll slip in those shoes."],
      ['雪が積もった朝は、音が全部消えてすごく静かなんです。', 'On a morning after snow, every sound vanishes. So quiet.'],
      ['寒さには慣れっこです。こたつがあれば平気。', "We're used to the cold. With a kotatsu, no problem."],
    ],
    forest: [
      ['このあたりは森がずっと続いてます。道から外れないでくださいね。', 'The forest goes on and on round here. Stay on the path.'],
      ['森を歩くと頭がすっきりしますよ。森林浴です。', "Walking in the forest clears the head. Forest bathing, we call it."],
      ['秋になると、みんなでキノコや木の実をとりに行きます。', 'In autumn we all go out picking mushrooms and nuts.'],
      ['見渡すかぎり木、木、木。でもここが好きなんです。', 'Trees, trees, trees as far as you can see. But I love it here.'],
    ],
    desert: [
      ['見渡すかぎり砂ですね。', 'Sand as far as the eye can see.'],
      ['水はたくさん飲んでください。砂漠は甘くないですよ。', "Drink plenty of water. The desert isn't forgiving."],
      ['砂漠の夜は冷えるんです。みんな信じてくれませんけど。', 'Desert nights get cold. Nobody ever believes it.'],
      ['今夜は星を見てください。数えきれないほどですよ。', 'Look at the stars tonight. Too many to count.'],
    ],
    plains: [
      ['どこまでも真っ平らです。雨雲が来るのも一日前からわかります。', 'Flat as far as you go. You can see the rain clouds coming a day off.'],
      ['空が広いでしょう？風をさえぎるものが何もないんです。', "Big sky, isn't it? Nothing to stop the wind."],
      ['いい牧草地ですよ。家畜の群れに気をつけてください。', 'Good pasture, all of it. Watch out for the herds.'],
      ['草原がどこまでも続いて、まるで緑の海です。', 'The grassland goes on forever, like a green sea.'],
    ],
    tropical: [
      ['ここは何でも育ちます。枝を挿せば木になるくらい。', 'Everything grows here. Stick a twig in the ground and it becomes a tree.'],
      ['スコールが来るとすごいですよ。でも、すぐやみます。', 'When a squall comes, it really pours. Then it stops just like that.'],
      ['市場の果物、食べてみてください。びっくりするほど甘いですから。', "Try the fruit at the market. It's amazingly sweet."],
      ['一年中緑です。冬？何ですか、それ。', "It's green all year. Winter? What's that?"],
    ],
    landmark: [
      ['{landmark}はぜひ見てください！ここから{dir}に約{km}キロです。', "Be sure to see {landmark}! It's about {km} km {dir} from here."],
      ['{landmark}には行きましたか？{dir}へ{km}キロくらい、行く価値ありますよ。', "Been to {landmark}? About {km} km {dir}, and well worth it."],
      ['みんな{landmark}に行きますね。{dir}に{km}キロほどです。', "Everyone goes to {landmark}. It's about {km} km {dir}."],
      ['古いものが好きなら、{dir}に{km}キロのところに{landmark}があります。', 'If you like old things, {landmark} is {km} km {dir}.'],
    ],
    landmarkNear: [
      ['{landmark}はすぐ近くです。すぐにわかりますよ！', "{landmark} is very close. You can't miss it!"],
      ['{landmark}にはもう行きましたか？すぐそこですよ。', "Have you been to {landmark} yet? It's just over there."],
      ['毎日{landmark}を見てますけど、いまだに見とれちゃいます。', 'I see {landmark} every day and it still takes my breath away.'],
      ['{landmark}はすぐそこです。混む前の朝早くがおすすめですよ。', '{landmark} is right there. Go early, before the crowds.'],
    ],
    plane: [
      ['{dir}の畑に小さな飛行機がありますよ。操縦できるなら、どうぞ！', "There's a little plane in a field {dir}. Help yourself, if you can fly!"],
      ['誰かが{dir}の野原に飛行機を置いていったんです。乗ってみます？', 'Somebody left a plane in a field {dir}. Fancy a go?'],
      ['飛行機、操縦できますか？{dir}のほうで待ってますよ。', "Can you fly a plane? There's one waiting {dir}."],
      ['上から全部見たいなら、{dir}に飛行機がありますよ。', "If you want to see it all from above, there's a plane {dir}."],
    ],
    balloon: [
      ['{dir}の野原に気球がありますよ！景色、最高でしょうね。', "There's a balloon in a field {dir}! Imagine the view."],
      ['気球に乗ったことありますか？{dir}に一つありますよ。', "Ever been up in a balloon? There's one {dir}."],
      ['{dir}の野原から気球が上がるんです。夢みたいですよ。', 'A balloon goes up from the field {dir}. Like a dream.'],
      ['{dir}の気球、ずっと乗ってみたいんですけど、怖くて。', "I've always wanted to ride the balloon {dir}, but I'm scared."],
    ],
    boat: [
      ['{dir}の水辺にボートがありますよ。出てみたらどうですか？', "There's a boat by the water {dir}. Why not take it out?"],
      ['海が好きなら、{dir}にボートがあります。ちゃんと返してくださいね！', "If you like the sea, there's a boat {dir}. Bring it back, mind!"],
      ['{dir}にボートがつないであります。どこへでも行けますよ。', 'A boat is tied up {dir}. You could go anywhere.'],
      ['{dir}のボートに乗って、海から海岸を眺めてみてください。', 'Take the boat {dir} and see the coast from the water.'],
    ],
    hot: [
      ['今日は暑いですね！日陰で休んでください。', "Hot today! Rest in the shade."],
      ['いやあ、暑い！水分補給、忘れないでくださいね。', "Phew, the heat! Don't forget to drink water."],
      ['こう暑いと、何もする気が起きませんね。', "In heat like this, you don't feel like doing anything."],
      ['暑すぎて、犬も家から出てきませんよ。', "It's so hot even the dogs won't come out."],
      ['蒸しますねえ。熱中症に気をつけて。', "So muggy. Watch out for heatstroke."],
    ],
    cold: [
      ['うう、今日は寒いですね！暖かくしてください。', "Brr, it's cold today! Keep warm."],
      ['寒い！手袋はどうしたんですか？', 'Freezing! Where are your gloves?'],
      ['寒くて鼻の感覚がないです。', "It's so cold I can't feel my nose."],
      ['冷えますねえ。風が出るともっと寒くなりますよ。', "Chilly, isn't it? Wait till the wind picks up."],
      ['温かいものでも飲んでください。体が温まりますよ。', "Have something hot to drink. It'll warm you up."],
    ],
    mild: [
      ['今日はいい天気ですね。', 'Lovely weather today.'],
      ['暑くも寒くもなく、ちょうどいいですね。', "Not hot, not cold. Just right, isn't it?"],
      ['こんな日は外にいたくなりますね。', 'A day like this makes you want to be outside.'],
      ['気持ちのいい日ですね。このまま続くといいんですけど。', "What a pleasant day. Let's hope it lasts."],
      ['こういう日があるから、ここに住んでるんです。', "Days like this are why I live here."],
    ],
    late: [
      ['もう遅いですね。夜は通りが静かです。', "It's late. The streets are quiet at night."],
      ['こんな時間に出歩いてるのは猫くらいですよ。あと私たち。', 'At this hour only the cats are out. And us.'],
      ['もう寝なきゃいけないのに。そちらこそどうしたんですか？', 'I should be asleep by now. What about you?'],
      ['見てください、星がきれいですよ。', 'Look, the stars are beautiful.'],
    ],
    early: [
      ['早起きですね！一日で一番いい時間ですよ。', "You're up early! The best time of the day."],
      ['パン屋さんが開いたところです。いいにおいがするでしょう？', "The bakery's just opened. Smells good, doesn't it?"],
      ['早いですね。町もまだ寝てますよ。', "You're early. The town's still asleep."],
      ['朝のこの静けさが好きなんです。', 'I love how quiet the morning is.'],
    ],
    country: [
      ['{country}は素敵な国です。楽しんでください！', '{country} is a lovely country. Enjoy it!'],
      ['{country}はどうですか？気に入りました？', 'How do you like {country}? Taken to it?'],
      ['{country}は地図で見ると小さいけど、見どころはいっぱいですよ。', '{country} looks small on the map, but there is so much to see.'],
      ['{country}のあちこちを回ってみてください。場所ごとに全然違いますから。', 'Travel all round {country}. Every place is completely different.'],
    ],
    dish: [
      ['せっかく来たなら、{dish}はぜひ食べてみてください。', "Now you're here, you really must try {dish}."],
      ['{dish}はもう食べました？まだ？絶対食べてください！', "Have you had {dish} yet? No? You absolutely must!"],
      ['{dish}なら、うちの母のが一番です。', 'When it comes to {dish}, my mother makes the best.'],
      ['お腹がすいたら{dish}がおすすめです。後悔しませんよ。', "If you're hungry, get {dish}. You won't regret it."],
    ],
    drink: [
      ['帰る前に{drink}を飲んでいってください。ここではみんな飲んでますよ。', 'Have some {drink} before you go. Everyone drinks it here.'],
      ['一日の終わりには、やっぱり{drink}ですね。', 'At the end of the day, it has to be {drink}.'],
      ['{drink}を飲まずに帰るなんて、もったいないですよ。', 'Leaving without trying {drink} would be such a waste.'],
      ['地元の人みたいに{drink}を頼めば、お店の人も喜びますよ。', "Order {drink} like a local and they'll be delighted."],
    ],
    festival: [
      ['{festival}の時期にまた来てください。最高ですよ！', "Come back for {festival}. It's the best!"],
      ['ここに来るなら{festival}の頃が一番です。国中がお祭り気分なんです。', 'The best time to come is {festival}. The whole country is in a festive mood.'],
      ['{festival}って知ってます？きっと気に入りますよ。', "Do you know {festival}? You'd love it."],
      ['毎年{festival}が待ち遠しくて。', 'Every year I can hardly wait for {festival}.'],
    ],
    sport: [
      ['ここでは何と言っても{sport}です。', "Here, it's {sport} above all."],
      ['{sport}は好きですか？ここではみんな夢中なんです。', 'Do you like {sport}? Everyone here is crazy about it.'],
      ['試合の日は、町中{sport}の話ばかりですよ。', 'On a match day, the whole town talks of nothing but {sport}.'],
      ['うちは家族みんな{sport}が好きで。祖母は応援専門ですけど。', 'My whole family loves {sport}. Grandma just does the cheering.'],
    ],
    wonder: [
      ['時間があれば{wonder}に行ってみてください。一生の思い出になりますよ。', "If you have time, go and see {wonder}. You'll remember it all your life."],
      ['{wonder}は見ました？世界のどこにもない景色です。', "Have you seen {wonder}? There's nothing like it in the world."],
      ['一生に一度は{wonder}を見るべきです。', 'Everyone should see {wonder} once in their life.'],
      ['子どものころ{wonder}に行ったんです。今でも夢に見ますよ。', 'I went to {wonder} as a child. I still dream about it.'],
    ],
    pride: [
      ['{pride}は私たちの誇りです。', '{pride} is our pride.'],
      ['帰る前に{pride}のことを知ってください。それが私たちなんです。', "Before you leave, learn about {pride}. That's who we are."],
      ['私たちの自慢ですか？{pride}ですね。', 'What we are proud of? {pride}, I would say.'],
      ['{pride}の話をしたら、ここの人は何時間でも話しますよ。', 'Mention {pride} and people here will talk for hours.'],
    ],
    proverb: [
      ['ここでは「{proverb}」と言うんです。', 'Here we say: “{proverb}”'],
      ['祖母の口癖でした。「{proverb}」って。', 'My grandmother always used to say: “{proverb}”'],
      ['こんなことわざがあります。「{proverb}」', 'There is a saying: “{proverb}”'],
      ['「{proverb}」って、聞いたことありますか？', 'Have you heard this one? “{proverb}”'],
    ],
    chat: [
      ['どちらから来たんですか？この辺の人じゃないですよね。', "Where are you from? You're not from around here, are you?"],
      ['ゆっくり見ていってください。見どころがたくさんありますよ。', 'Take your time looking round. There is plenty to see.'],
      ['一人旅ですか？すごいですね。', "Travelling alone? That's impressive."],
      ['ずいぶん遠くから歩いてきたみたいですね。', 'You look like you have walked a long way.'],
      ['道に迷ったら、遠慮なく聞いてください。', "If you get lost, don't hesitate to ask."],
      ['今まで行った中で、どこが一番よかったですか？', "Of everywhere you've been, where was the best?"],
      ['いつか世界中を旅してみたいんです。', "I'd love to travel the world some day."],
    ],
    childGreet: [
      ['こんにちは！', 'Hello!'],
      ['だれ？どこから来たの？', 'Who are you? Where are you from?'],
      ['わあ、背が高いね！', "Wow, you're tall!"],
      ['やっほー！', 'Yoo-hoo!'],
    ],
    childChat: [
      ['ねえ、足すっごく速いんだよ！見る？あとでね。', "Hey, I can run super fast! Want to see? Later."],
      ['観光客？観光客ってお金持ちなんでしょ？', 'Are you a tourist? Tourists are rich, right?'],
      ['きのう歯が抜けたの！見て！…見えないか。', "I lost a tooth yesterday! Look! ...Oh, you can't see it."],
      ['知らない人と話しちゃダメってママに言われてるけど、いい人そうだから。', "Mum says not to talk to strangers, but you look nice."],
      ['犬飼ってる？犬ほしいなあ。', 'Do you have a dog? I really want a dog.'],
      ['大きくなったら飛行機で世界一周するんだ！', "When I grow up I'm going to fly round the world!"],
      ['なぞなぞ知ってる？いっぱい知ってるよ。', 'Do you know any riddles? I know loads.'],
    ],
    childBye: [
      ['バイバイ！', 'Bye-bye!'],
      ['またね！また遊ぼうね！', "See you! Let's play again!"],
      ['ママが呼んでる、行かなきゃ！', "Mum's calling, I have to go!"],
      ['じゃあね、また来てね！', 'Bye, come back again!'],
    ],
    grumpyGreet: [
      ['ん？何か用ですか。', 'Hm? What do you want?'],
      ['はい？何でしょう。', 'Yes? What is it?'],
      ['はあ、また観光客か。', 'Sigh. Another tourist.'],
      ['ふん。どうも。', 'Hmph. Hello.'],
    ],
    grumpyChat: [
      ['昔はよかったんですよ、観光客が来る前は。', 'It was better before the tourists came.'],
      ['何でもかんでも値上がりして、まったく。', 'Everything keeps going up in price. Honestly.'],
      ['道の真ん中で立ち止まらないでくださいよ。ここは生活の場なんですから。', "Don't stop in the middle of the street. People live here."],
      ['最近の若い人は、スマホばっかり見て。', 'Young people these days, always staring at their phones.'],
      ['こんな所に何を見に来たんだか。何もありませんよ。', "What anyone comes here to see, I don't know. There's nothing."],
    ],
    grumpyBye: [
      ['はい、じゃあ行ってください。', 'Right, off you go, then.'],
      ['引き止めはしませんよ。', "I won't keep you."],
      ['ふん。じゃあ。', 'Hmph. Bye.'],
      ['気をつけて。門は閉めてってくださいよ。', 'Mind how you go. And shut the gate.'],
    ],
    elderChat: [
      ['若いころ、このあたりは一面田んぼでねえ。', 'When I was young, this was all rice fields.'],
      ['ここに住んで八十年になります。信じられます？', "I've lived here eighty years. Can you believe it?"],
      ['昔はどこへでも歩いて行ったものです。あなたも歩いてますね。えらい！', 'We used to walk everywhere. You walk too. Good for you!'],
      ['孫は遠くに住んでて、日曜日に電話をくれるんです。', 'My grandchildren live far away. They call on Sundays.'],
      ['何でもすぐ変わっちゃいますね。でも古い路地は昔のままです。', 'Everything changes so fast. But the old lanes are just as they were.'],
    ],
    chattyChat: [
      ['まあまあ、旅の方ですか！話を聞かせてください。いや、やっぱり先に私から話しますね。', "Well, well, a traveller! Tell me everything. No, wait, I'll go first."],
      ['いとこが昔旅に出てね、ひげと奥さんを連れて帰ってきたんですよ！', 'My cousin went travelling once and came back with a beard and a wife!'],
      ['しゃべりだしたら止まらないって、友だちに言われるんです。その通りなんですけどね！', "My friends say once I start talking I never stop. They're right!"],
      ['ご飯食べました？お腹すいてそうな顔してますよ。', 'Have you eaten? You look hungry.'],
      ['ここだけの話、町で一番の景色はお寺の裏の丘からなんですよ。', 'Between you and me, the best view in town is from the hill behind the temple.'],
    ],
    bye: [
      ['さようなら！良い旅を。', 'Goodbye! Have a good trip.'],
      ['気をつけて。残りの旅も楽しんでくださいね。', 'Take care. Enjoy the rest of your trip.'],
      ['お気をつけて！', 'Travel safely!'],
      ['じゃあ、また遊びに来てくださいね。', 'Well then, come and visit again.'],
      ['話せて楽しかったです。お元気で！', 'It was nice talking. Look after yourself!'],
      ['いってらっしゃい！見るものはたくさんありますよ。', "Off you go! There's so much to see."],
    ],
  },
  countries: {
    // A bare noun, as it stands before a particle: は, を, に and の never change with it.
    JPN: {
      dish: ['ラーメン', 'ramen'],
      drink: ['日本酒', 'sake'],
      festival: ['お花見', 'hanami, the cherry-blossom viewing'],
      sport: ['野球', 'baseball'],
      wonder: ['富士山', 'Mount Fuji'],
      pride: ['おもてなしの心', 'omotenashi, our way of welcoming guests'],
      proverb: ['石の上にも三年', 'Three years on a stone (even a cold stone warms if you sit on it long enough)'],
    },
  },
};

export default JA;
