import type { Language } from '../phrases.ts';

/**
 * Korean: polite 해요체 to a stranger, plainer speech for a child and a curt
 * old-timer. A particle takes its shape from the last sound of the word before
 * it, so no particle ever follows a placeholder: a name stands before a comma,
 * before a noun it modifies (*{town} 방문*), or where speech drops the particle
 * anyway (*{landmark} 보셨어요?*). A direction carries its own 으로.
 */
const KO: Language = {
  locale: 'ko',
  name: 'Korean',
  join: ' ',
  compass: ['북쪽으로', '북동쪽으로', '동쪽으로', '남동쪽으로', '남쪽으로', '남서쪽으로', '서쪽으로', '북서쪽으로'],
  lines: {
    morning: [
      ['좋은 아침이에요!', 'Good morning!'],
      ['안녕하세요! 좋은 아침이네요.', "Hello! Lovely morning, isn't it?"],
      ['아, 안녕하세요! 일찍 나오셨네요.', "Oh, hello! You're out early."],
      ['좋은 아침! 오늘도 힘내세요.', 'Morning! Have a good day.'],
    ],
    afternoon: [
      ['안녕하세요!', 'Hello!'],
      ['아, 안녕하세요! 점심은 드셨어요?', 'Oh, hello! Have you had lunch?'],
      ['안녕하세요, 날이 좋네요.', "Hello, nice day, isn't it?"],
      ['반가워요! 산책 중이세요?', 'Nice to meet you! Out for a walk?'],
    ],
    evening: [
      ['안녕하세요! 좋은 저녁이에요.', 'Hello! Good evening.'],
      ['안녕하세요, 저녁 산책하기 딱 좋네요.', 'Hello, perfect evening for a walk.'],
      ['아, 안녕하세요! 저녁은 드셨어요?', 'Oh, good evening! Have you had dinner?'],
      ['반가워요! 해가 벌써 지네요.', "Nice to meet you! The sun's going down already."],
    ],
    night: [
      ['안녕하세요! 시간이 꽤 늦었네요.', "Hello! It's quite late, isn't it?"],
      ['아이고, 깜짝이야! 안녕하세요.', 'Goodness, you startled me! Hello.'],
      ['안녕하세요! 밤 산책 나오셨어요?', 'Hello! Out for a night walk?'],
      ['이 시간에 누군가 했네요. 안녕하세요!', 'I wondered who was out at this hour. Hello!'],
    ],
    again: [
      ['어, 또 만났네요!', 'Oh, we meet again!'],
      ['또 오셨네요! 반가워요.', "You're back! Good to see you."],
      ['우리 또 보네요. 아직 구경 중이세요?', 'We meet again. Still looking around?'],
      ['아, 아까 그분이네요! 길은 찾으셨어요?', "Ah, it's you from earlier! Did you find your way?"],
      ['인연인가 봐요. 또 만나다니!', 'Must be fate. Meeting again!'],
    ],
    welcome: [
      ['{town} 방문을 환영해요!', 'Welcome to {town}!'],
      ['어서 오세요! 여기는 {town}, 좋은 곳이에요.', 'Welcome! This is {town}, a lovely place.'],
      ['{town}, 처음 오셨어요?', 'Is this your first time in {town}?'],
      ['{town} 구경하기 딱 좋은 날에 오셨네요.', 'You came on the perfect day to see {town}.'],
      ['어서 오세요! {town} 사람들은 손님을 참 좋아해요.', 'Welcome! People in {town} love having visitors.'],
      ['반가워요! {town} 여행 오신 거예요?', 'Nice to meet you! Are you here to see {town}?'],
    ],
    capitalHere: [
      ['{town}, 바로 우리나라의 수도예요.', '{town} is the capital of our country.'],
      ['여기는 수도라서 뭐든지 다 있어요. {town} 사람들은 늘 바빠요.', 'This is the capital, so it has everything. People in {town} are always busy.'],
      ['정부 기관도 다 {town} 안에 있어요. 정장 입은 사람이 많죠?', 'All the government offices are here in {town}. Lots of suits, right?'],
      ['수도답게 이 도시는 잠들 줄을 몰라요.', 'Like a true capital, this city never sleeps.'],
    ],
    capitalThere: [
      ['{capital}, 거기가 우리 수도예요. 꼭 가 보세요.', '{capital} is our capital. Do go and see it.'],
      ['{capital} 가 보셨어요? 우리나라 수도예요.', "Have you been to {capital}? It's our capital."],
      ['{capital} 사람들은 자기들이 최고인 줄 알아요. 뭐, 틀린 말도 아니고요.', 'People in {capital} think they are the best. Well, they are not wrong.'],
      ['{capital} 쪽이 더 크긴 한데, 저는 여기가 더 좋아요.', "{capital} is bigger, but I'd rather be here."],
    ],
    big: [
      ['여기는 큰 도시예요. 길을 잃기 쉬워요!', "This is a big city. It's easy to get lost!"],
      ['사람 정말 많죠? 평생 살아도 골목을 다 못 알아요.', "So many people, right? You could live here all your life and not know every alley."],
      ['출퇴근 시간 지하철은 전쟁이에요. 그래도 볼 건 많아요.', "The subway at rush hour is a war. But there's lots to see."],
      ['큰 도시는 쉴 틈이 없어요. 그래도 저는 좋아요.', 'A big city never stops. I like it, though.'],
    ],
    middling: [
      ['크지도 작지도 않아요. 딱 좋아요.', 'Not big, not small. Just right.'],
      ['있을 건 다 있고, 걸어서 다닐 만해요.', "It has everything you need, and you can walk it."],
      ['{town} 정도면 하루 이틀이면 다 둘러봐요.', 'A place the size of {town}, you can see it all in a day or two.'],
      ['다들 심심하다고 하면서도 아무도 안 떠나요.', 'Everybody says it is boring, and nobody ever leaves.'],
    ],
    small: [
      ['여기는 작은 동네예요. 다들 서로 알아요.', "It's a small place. Everybody knows each other."],
      ['동네가 작아서 소문이 금방 퍼져요.', 'Small place, so gossip spreads fast.'],
      ['{town} 같은 작은 동네엔 별일이 없어요. 그게 좋아요.', 'Nothing much happens in a little place like {town}. That is the good of it.'],
      ['외지 사람이 오다니, 이번 주 최고의 사건이네요!', "A visitor from outside! That's the big event of the week!"],
    ],
    coast: [
      ['우리는 물가에 살아요. 생선이 정말 맛있어요.', 'We live by the water. The fish is delicious.'],
      ['바다 한번 보고 오세요. 매일 달라요.', "Go and look at the sea. It's different every day."],
      ['바다 냄새 나죠? 몇 년을 살아도 안 질려요.', "Smell the sea? You never tire of it, however many years."],
      ['새벽에 배가 나가면 싱싱한 생선이 시장에 들어와요.', 'The boats go out at dawn, and fresh fish reaches the market.'],
    ],
    inland: [
      ['바다에서는 멀지만, 이곳 풍경이 참 아름다워요.', "We're far from the sea, but the scenery here is beautiful."],
      ['바다는 없어도 산이랑 들이 있잖아요.', 'No sea, but we have mountains and fields.'],
      ['바다요? 솔직히 본 지 오래됐어요.', "The sea? Honestly, it's been ages since I saw it."],
      ['여기는 땅이 전부예요. 흙이 좋아서 농사가 잘돼요.', 'Here the land is everything. Good soil, good harvests.'],
    ],
    high: [
      ['여기는 고지대예요. 천천히 걸으세요.', "We're high up here. Walk slowly."],
      ['산 위라서 경치 하나는 최고예요.', "Up on the mountain, the view is the one thing we've got."],
      ['온통 오르막이라 다리가 튼튼해져요.', "It's all uphill. Your legs will get strong."],
      ['숨차죠? 공기가 희박해서 익숙해지려면 좀 걸려요.', 'Out of breath? The air is thin; it takes a while to get used to.'],
    ],
    snowy: [
      ['겨울엔 매일 눈 치우는 게 일이에요.', 'In winter, clearing snow is a daily job.'],
      ['온 세상이 하얗죠? 그 신발로는 미끄러질 거예요.', "White everywhere, isn't it? You'll slip in those shoes."],
      ['눈 온 날 아침은 소리가 다 사라진 것처럼 조용해요.', 'The morning after snow, it is so quiet, as if every sound had gone.'],
      ['추위엔 익숙해요. 뜨끈한 방바닥만 있으면 돼요.', "We're used to the cold. A warm heated floor is all you need."],
    ],
    forest: [
      ['이 근처는 숲이 끝없이 이어져요. 길에서 벗어나지 마세요!', 'The forest goes on and on round here. Stay on the path!'],
      ['숲길 걸으면 머리가 맑아져요.', 'A walk in the woods clears the head.'],
      ['가을이면 다들 버섯이랑 밤을 따러 가요.', 'In autumn everyone goes picking mushrooms and chestnuts.'],
      ['어딜 봐도 나무, 나무, 나무. 그래도 여기가 좋아요.', 'Trees, trees, trees wherever you look. But I love it here.'],
    ],
    desert: [
      ['여기는 보이는 게 다 모래예요.', 'Out here, all you can see is sand.'],
      ['물 많이 드세요. 사막은 봐주는 게 없어요.', 'Drink plenty of water. The desert shows no mercy.'],
      ['사막은 밤에 추워요. 다들 안 믿지만요.', 'The desert gets cold at night. Nobody believes it.'],
      ['오늘 밤엔 별을 보세요. 셀 수도 없을 만큼 많아요.', 'Look at the stars tonight. Too many to count.'],
    ],
    plains: [
      ['끝없이 평평해요. 비구름이 오는 게 하루 전부터 보여요.', "Flat forever. You can see the rain clouds coming a day off."],
      ['하늘 넓죠? 바람을 막을 게 하나도 없어요.', "Big sky, isn't it? Nothing to stop the wind."],
      ['다 좋은 목초지예요. 가축 떼 조심하세요.', 'Good pasture, all of it. Watch out for the herds.'],
      ['풀밭이 끝없이 펼쳐져서 꼭 초록 바다 같아요.', 'The grass stretches on forever, like a green sea.'],
    ],
    tropical: [
      ['여기는 뭐든 잘 자라요. 막대기를 꽂아도 나무가 될걸요.', 'Everything grows here. Stick a twig in and it would become a tree.'],
      ['스콜이 오면 엄청 쏟아져요. 그러다 금방 그쳐요.', 'When a squall comes it really pours. Then it stops just like that.'],
      ['시장 과일 꼭 드셔 보세요. 정말 달아요.', "Try the fruit at the market. It's so sweet."],
      ['일 년 내내 푸르러요. 겨울이요? 그게 뭐예요?', "It's green all year. Winter? What's that?"],
    ],
    landmark: [
      ['{landmark}, 꼭 보세요! 여기서 {dir} 약 {km}km 거리예요.', "Don't miss {landmark}! It's about {km} km {dir} from here."],
      ['{landmark} 보셨어요? {dir} {km}km쯤 가면 있어요. 갈 만해요.', "Seen {landmark}? It's about {km} km {dir}. Worth the trip."],
      ['다들 {landmark} 보러 가요. {dir} {km}km 정도예요.', "Everyone goes to see {landmark}. It's about {km} km {dir}."],
      ['옛날 건물 좋아하시면 {landmark}, 추천해요. {dir} {km}km쯤이에요.', 'If you like old buildings, try {landmark}. About {km} km {dir}.'],
    ],
    landmarkNear: [
      ['{landmark}, 바로 근처에 있어요. 금방 찾을 거예요!', "{landmark} is very close. You'll find it in no time!"],
      ['{landmark} 벌써 가 보셨어요? 바로 코앞이에요.', "Have you been to {landmark} yet? It's right under your nose."],
      ['매일 봐도 {landmark}, 볼 때마다 감탄해요.', 'I see {landmark} every day, and it still amazes me every time.'],
      ['바로 여기 {landmark} 있잖아요. 사람 몰리기 전에 아침 일찍 가 보세요.', '{landmark} is right here. Go early in the morning, before the crowds.'],
    ],
    plane: [
      ['{dir} 가면 들판에 작은 비행기가 있어요. 조종할 줄 아세요?', "There's a little plane in a field {dir}. Can you fly?"],
      ['{dir} 가 보면 비행기가 한 대 있어요. 한번 날아 보실래요?', "There's a plane {dir}. Fancy a flight?"],
      ['비행기 조종하실 줄 알아요? {dir} 가면 하나 있어요.', "Can you fly a plane? There's one {dir}."],
      ['하늘에서 다 내려다보고 싶으면 {dir} 가 보세요. 비행기가 있어요.', "If you want to see it all from above, go {dir}. There's a plane."],
    ],
    balloon: [
      ['{dir} 가면 들판에 열기구가 있어요! 경치가 끝내줄 거예요.', "There's a hot-air balloon in a field {dir}! The view must be amazing."],
      ['열기구 타 보셨어요? {dir} 가면 하나 있어요.', "Ever been up in a balloon? There's one {dir}."],
      ['{dir} 조금 가면 들판에서 열기구가 떠요. 꿈같아요.', 'A balloon goes up from a field a little way {dir}. Like a dream.'],
      ['{dir} 가면 있는 열기구, 저도 늘 타 보고 싶었는데 무서워서요.', "I've always wanted to ride the balloon {dir}, but I'm scared."],
    ],
    boat: [
      ['{dir} 가면 물가에 배가 있어요. 한번 타 보세요.', "There's a boat by the water {dir}. Take it out."],
      ['바다 좋아하시면 {dir} 가 보세요. 배가 있어요. 꼭 돌려놓으시고요!', "If you like the sea, go {dir}. There's a boat. Bring it back, mind!"],
      ['{dir} 가면 배가 한 척 묶여 있어요. 어디든 갈 수 있죠.', 'A boat is tied up {dir}. You could go anywhere.'],
      ['{dir} 가서 배 타고 바다에서 해안을 구경해 보세요.', 'Take the boat {dir} and see the coast from the water.'],
    ],
    hot: [
      ['오늘 덥네요! 그늘을 찾으세요.', "It's hot today! Find some shade."],
      ['아이고, 더워라! 물 많이 드세요.', 'Oh, the heat! Drink plenty of water.'],
      ['너무 더워서 아무것도 하기 싫네요.', "It's too hot to do anything."],
      ['이 더위엔 개들도 집 밖에 안 나와요.', "In this heat even the dogs won't come out."],
      ['푹푹 찌네요. 더위 먹지 않게 조심하세요.', 'So sweltering. Be careful not to get heatstroke.'],
    ],
    cold: [
      ['으, 오늘 춥네요! 따뜻하게 입으세요.', "Brr, it's cold today! Dress warmly."],
      ['꽁꽁 얼겠어요! 장갑은 어디 두셨어요?', 'Freezing! Where did you leave your gloves?'],
      ['너무 추워서 코가 얼얼해요.', "It's so cold my nose is numb."],
      ['춥죠? 바람 불면 더 추워요.', 'Cold, right? Wait till the wind blows.'],
      ['따뜻한 거 한 잔 드세요. 몸이 좀 풀릴 거예요.', "Have something hot to drink. It'll warm you up."],
    ],
    mild: [
      ['오늘 날씨 참 좋네요.', 'The weather is lovely today.'],
      ['덥지도 춥지도 않고, 딱 좋네요.', "Not hot, not cold. Just right."],
      ['이런 날은 밖에 있고 싶어져요.', 'A day like this makes you want to be outside.'],
      ['날씨 정말 좋다! 계속 이러면 좋겠어요.', "What lovely weather! I hope it lasts."],
      ['이런 날이 있어서 여기 사는 거죠.', 'Days like this are why we live here.'],
    ],
    late: [
      ['늦었네요. 밤에는 거리가 조용해요.', "It's late. The streets are quiet at night."],
      ['이 시간엔 고양이밖에 안 다녀요. 아, 우리도 있네요!', 'At this hour only the cats are out. Oh, and us!'],
      ['저도 자야 하는데. 어쩐 일로 안 주무세요?', "I should be asleep too. Why aren't you?"],
      ['저기 별 좀 보세요! 여기서 제일 잘 보여요.', 'Look at the stars! You see them best from here.'],
    ],
    early: [
      ['일찍 일어나셨네요! 하루 중 제일 좋은 시간이에요.', "You're up early! The best time of the day."],
      ['빵집이 막 문을 열었어요. 냄새 좋죠?', 'The bakery has just opened. Smells good, right?'],
      ['부지런하시네요. 동네가 아직 잠들어 있어요.', "Early riser, eh? The town's still asleep."],
      ['시끄러워지기 전, 이 아침이 제일 좋아요.', 'I love this morning hour, before the noise starts.'],
    ],
    country: [
      ['{country}, 정말 아름다운 나라예요. 즐거운 시간 보내세요!', '{country} is a really beautiful country. Enjoy yourself!'],
      ['{country} 여행, 어떠세요? 마음에 드세요?', 'How are you finding your trip in {country}? Do you like it?'],
      ['{country}, 지도에선 작아 보여도 볼 게 정말 많아요.', '{country} may look small on the map, but there is so much to see.'],
      ['시간 되면 {country} 곳곳을 다녀 보세요. 지역마다 다 달라요.', 'If you have time, go all over {country}. Every region is different.'],
    ],
    dish: [
      ['여기 오셨으면 {dish}, 꼭 드셔 보세요.', 'Now that you are here, you must try {dish}.'],
      ['{dish} 드셔 보셨어요? 아직이요? 꼭 드셔야 해요!', 'Have you tried {dish}? Not yet? You really must!'],
      ['{dish} 하면 우리 엄마 솜씨가 최고예요.', 'When it comes to {dish}, nobody beats my mother.'],
      ['배고프시면 {dish}, 추천해요. 후회 안 하실 거예요.', "If you're hungry, I recommend {dish}. You won't regret it."],
    ],
    drink: [
      ['가시기 전에 {drink} 한잔 하세요. 여기 사람들은 다 마셔요.', 'Have some {drink} before you go. Everyone here drinks it.'],
      ['하루를 마무리할 땐 역시 {drink}, 그게 최고예요.', 'To end the day, {drink} is the best, of course.'],
      ['{drink} 안 마셔 보고 가면 후회해요.', "You'll regret it if you leave without trying {drink}."],
      ['현지 사람처럼 {drink} 주문하면 다들 좋아할 거예요.', "Order {drink} like a local and everyone will love you for it."],
    ],
    festival: [
      ['{festival} 때 다시 오세요. 정말 신나요!', "Come back for {festival}. It's so much fun!"],
      ['여기 오기 제일 좋은 때는 {festival} 무렵이에요. 온 나라가 들썩여요.', 'The best time to come is around {festival}. The whole country comes alive.'],
      ['{festival}, 들어 보셨어요? 분명 좋아하실 거예요.', "Have you heard of {festival}? You'd love it, I'm sure."],
      ['해마다 {festival} 날만 손꼽아 기다려요.', 'Every year I count the days till {festival}.'],
    ],
    sport: [
      ['여기선 뭐니 뭐니 해도 {sport}, 이게 최고예요.', 'Here, above all else, it is {sport}.'],
      ['{sport} 좋아하세요? 여기 사람들은 완전히 빠져 있어요.', 'Do you like {sport}? People here are crazy about it.'],
      ['경기 날이면 온 동네가 {sport} 얘기뿐이에요.', 'On a match day the whole town talks of nothing but {sport}.'],
      ['우리 가족은 다 {sport} 광팬이에요. 할머니는 응원 담당이고요.', 'My whole family are {sport} fanatics. Grandma is in charge of cheering.'],
    ],
    wonder: [
      ['시간 되시면 {wonder}, 꼭 가 보세요. 평생 못 잊을 거예요.', "If you have time, go and see {wonder}. You'll never forget it."],
      ['{wonder} 보셨어요? 세상 어디에도 없는 풍경이에요.', "Have you seen {wonder}? There's no view like it in the world."],
      ['평생 한 번은 {wonder} 구경을 해야 해요.', 'Everyone should see {wonder} once in their life.'],
      ['어릴 때 {wonder} 구경 갔었는데, 아직도 꿈에 나와요.', 'I went to see {wonder} as a child, and I still dream of it.'],
    ],
    pride: [
      ['{pride}, 우리가 정말 자랑스러워하는 거예요.', '{pride} is something we are really proud of.'],
      ['가시기 전에 {pride} 얘기 좀 들어 보세요. 그게 바로 우리예요.', "Before you go, hear a bit about {pride}. That's who we are."],
      ['뭐가 자랑이냐고요? {pride}, 그거죠.', "What are we proud of? {pride}, that's what."],
      ['{pride} 얘기만 나오면 여기 사람들은 몇 시간이고 떠들어요.', 'Mention {pride} and people here will talk for hours.'],
    ],
    proverb: [
      ['여기선 이런 말을 해요. “{proverb}”', 'Here we say: “{proverb}”'],
      ['우리 할머니가 늘 그러셨어요. “{proverb}”', 'My grandmother always used to say: “{proverb}”'],
      ['이런 속담이 있어요. “{proverb}”', 'There is a proverb: “{proverb}”'],
      ['그 말 아세요? “{proverb}”', 'Do you know the saying? “{proverb}”'],
    ],
    chat: [
      ['어디서 오셨어요? 이 동네 분이 아니시죠?', "Where are you from? You're not from around here, are you?"],
      ['천천히 둘러보세요. 볼거리가 많아요.', 'Take your time looking round. There is a lot to see.'],
      ['혼자 여행하세요? 용감하시네요.', "Travelling alone? That's brave."],
      ['먼 길 걸어오신 것 같네요.', 'You look like you have walked a long way.'],
      ['길 잃으면 그냥 물어보세요. 여기 사람들 친절해요.', 'If you get lost, just ask. People here are friendly.'],
      ['지금까지 가 본 데 중에 어디가 제일 좋았어요?', "Of everywhere you've been, where was the best?"],
      ['저도 언젠가 세계 여행 해 보고 싶어요.', "I'd like to travel the world some day too."],
    ],
    childGreet: [
      ['안녕하세요!', 'Hello!'],
      ['안녕하세요! 누구세요?', 'Hello! Who are you?'],
      ['우와, 키 진짜 크다!', "Wow, you're really tall!"],
      ['안녕, 안녕!', 'Hi, hi!'],
    ],
    childChat: [
      ['나 달리기 진짜 빨라요! 보여 줄까요?', 'I can run really fast! Want me to show you?'],
      ['관광객이에요? 친구가 관광객은 다 부자래요.', 'Are you a tourist? My friend says tourists are all rich.'],
      ['어제 이 빠졌어요! 봐요! 아, 안 보이나?', "I lost a tooth yesterday! Look! Oh, can't you see it?"],
      ['엄마가 모르는 사람이랑 말하지 말랬는데, 좋은 사람 같아서요.', "Mum said not to talk to strangers, but you seem nice."],
      ['강아지 키워요? 나도 강아지 갖고 싶다.', 'Do you have a puppy? I want a puppy.'],
      ['크면 비행기 타고 세계 일주 할 거예요!', "When I grow up I'm going round the world in a plane!"],
      ['재밌는 놀이 알아요? 난 엄청 많이 알아요.', 'Do you know any fun games? I know loads.'],
    ],
    childBye: [
      ['빠이빠이!', 'Bye-bye!'],
      ['또 와서 같이 놀아요!', 'Come back and play with me!'],
      ['엄마가 불러요, 가야 돼요!', "Mum's calling, I have to go!"],
      ['안녕히 가세요! 또 봐요!', 'Goodbye! See you again!'],
    ],
    grumpyGreet: [
      ['흠. 무슨 일이에요?', 'Hm. What is it?'],
      ['네? 뭐요?', 'Yes? What?'],
      ['또 관광객이군.', 'Another tourist.'],
      ['에휴. 네, 안녕하세요.', 'Sigh. Yes, hello.'],
    ],
    grumpyChat: [
      ['관광객들 몰려오기 전이 훨씬 좋았어요.', 'It was much better before the tourists came flocking.'],
      ['뭐든 값이 두 배로 올랐어요, 참 나.', 'Everything costs twice what it did. Honestly.'],
      ['길 한가운데 서 있지 좀 마요. 사람 사는 동네예요.', "Don't stand in the middle of the street. People live here."],
      ['요즘 젊은 사람들은 휴대폰만 들여다보고.', 'Young people these days, always staring at their phones.'],
      ['여기 뭐 볼 게 있다고 오는지 몰라.', "I don't know what people come here to see."],
    ],
    grumpyBye: [
      ['됐어요, 이제 가 봐요.', 'Right, off you go now.'],
      ['붙잡지 않을 테니 가던 길 가요.', "I won't keep you. Go on your way."],
      ['흠. 잘 가요.', 'Hm. Bye.'],
      ['조심히 가요. 대문은 닫고 가고.', 'Mind how you go. And shut the gate.'],
    ],
    elderChat: [
      ['내가 젊었을 땐 여기가 다 논밭이었어요.', 'When I was young, this was all paddies and fields.'],
      ['여기서 평생 살았어요. 팔십 년! 믿어져요?', "I've lived here all my life. Eighty years! Can you believe it?"],
      ['옛날엔 어디든 걸어 다녔지요. 걸어 다니시네, 잘하시네요!', 'In the old days we walked everywhere. You walk too. Good for you!'],
      ['손주들은 외국에 살아요. 일요일마다 전화해 줘요.', 'My grandchildren live abroad. They call every Sunday.'],
      ['세상이 참 빨리 변해요. 그래도 옛 골목은 그대로예요.', 'The world changes so fast. But the old alleys are just the same.'],
    ],
    chattyChat: [
      ['아이고, 여행자시구나! 얘기 좀 들려주세요. 아니, 제 얘기부터 할게요.', "Oh my, a traveller! Tell me everything. No, wait, I'll go first."],
      ['우리 사촌이 여행을 갔었는데, 수염 기르고 결혼까지 해서 왔지 뭐예요!', 'My cousin went travelling and came back with a beard and married, would you believe!'],
      ['친구들이 저보고 입만 열면 멈출 줄 모른대요. 맞는 말이에요!', "My friends say once I open my mouth I can't stop. They're right!"],
      ['밥은 먹었어요? 배고파 보여요. 제 눈엔 다들 배고파 보이지만요.', 'Have you eaten? You look hungry. Mind you, everyone looks hungry to me.'],
      ['비밀 하나 알려 줄게요. 동네 최고 경치는 절 뒤 언덕이에요.', "Here's a secret: the best view in town is from the hill behind the temple."],
    ],
    bye: [
      ['안녕히 가세요! 즐거운 여행 되세요.', 'Goodbye! Have a great trip.'],
      ['조심히 가세요! 남은 여행도 즐겁게요.', 'Take care! Enjoy the rest of your trip.'],
      ['잘 가요, 좋은 여행 하세요!', 'Bye, have a good journey!'],
      ['또 놀러 오세요!', 'Come and visit again!'],
      ['얘기 즐거웠어요. 건강하세요!', 'It was nice talking. Stay well!'],
      ['어서 가 보세요! 볼 게 얼마나 많은데요.', "Off you go! There's so much to see."],
    ],
  },
  countries: {
    // A bare noun with no particle: the templates set it off with a comma or put it before a noun or verb.
    KOR: {
      dish: ['비빔밥', 'bibimbap'],
      drink: ['막걸리', 'makgeolli rice wine'],
      festival: ['추석', 'Chuseok, the harvest festival'],
      sport: ['야구', 'baseball'],
      wonder: ['제주도', 'Jeju Island'],
      pride: ['한글', 'Hangul, our alphabet'],
      proverb: ['가는 말이 고와야 오는 말이 곱다', 'Kind words going out bring kind words coming back'],
    },
    PRK: {
      dish: ['냉면', 'naengmyeon, cold buckwheat noodles'],
      festival: ['추석', 'Chuseok, the harvest festival'],
      sport: ['축구', 'football'],
      wonder: ['백두산', 'Mount Paektu'],
      proverb: ['백지장도 맞들면 낫다', 'Even a sheet of paper is lighter when two lift it'],
    },
  },
};

export default KO;
