import type { Language } from '../phrases.ts';

/**
 * Malay as it is spoken to a stranger in Malaysia and Brunei: relaxed, with
 * *awak* where a pronoun is wanted and none where it can be left out. A
 * direction is a bare word, so every template carries its own *ke arah* or
 * *di sebelah*.
 */
const MS: Language = {
  locale: 'ms',
  name: 'Malay',
  join: ' ',
  compass: ['utara', 'timur laut', 'timur', 'tenggara', 'selatan', 'barat daya', 'barat', 'barat laut'],
  lines: {
    morning: [
      ['Selamat pagi!', 'Good morning!'],
      ['Pagi!', 'Morning!'],
      ['Pagi! Cerah hari ni, kan?', "Morning! Bright day today, isn't it?"],
      ['Eh, helo! Selamat pagi.', 'Oh, hello! Good morning.'],
    ],
    afternoon: [
      ['Selamat tengah hari!', 'Good afternoon!'],
      ['Selamat petang!', 'Good afternoon!'],
      ['Helo! Panas tengah hari ni, ya.', 'Hello! Hot this afternoon, eh.'],
      ['Eh, helo! Jalan-jalan, ya?', 'Oh, hello! Out for a walk?'],
    ],
    evening: [
      ['Selamat petang!', 'Good evening!'],
      ['Selamat malam!', 'Good evening!'],
      ['Helo! Elok petang ni untuk bersiar-siar.', 'Hello! Nice evening for a stroll.'],
      ['Eh, selamat malam.', 'Oh, good evening.'],
    ],
    night: [
      ['Selamat malam! Dah lewat, kan?', "Good evening! It's late, isn't it?"],
      ['Opocot! Terkejut saya. Helo!', 'Whoa! You gave me a fright. Hello!'],
      ['Helo! Jalan-jalan malam-malam ni?', 'Hello! Out walking at this hour?'],
      ['Malam! Belum tidur lagi?', 'Evening! Not in bed yet?'],
    ],
    again: [
      ['Eh, awak lagi! Helo!', 'Oh, you again! Hello!'],
      ['Datang balik? Seronok jumpa lagi.', 'Back again? Nice to see you again.'],
      ['Helo sekali lagi!', 'Hello again!'],
      ['Kita jumpa lagi! Masih berjalan-jalan?', 'We meet again! Still exploring?'],
      ['Dah jumpa jalan tadi?', 'Did you find your way?'],
    ],
    welcome: [
      ['Selamat datang ke {town}!', 'Welcome to {town}!'],
      ['Ini {town}. Datang melawat?', 'This is {town}. Visiting?'],
      ['Pertama kali ke {town}?', 'First time in {town}?'],
      ['Hari yang elok untuk tengok {town}.', 'A good day to see {town}.'],
      ['Jemput, jemput! Selamat datang ke {town}.', 'Come in, come in! Welcome to {town}.'],
      ['Apa hajat datang ke {town}?', 'What brings you to {town}?'],
    ],
    capitalHere: [
      ['{town} ialah ibu negara kami.', '{town} is our capital.'],
      ['Ini ibu negara, tau. Semua benda berlaku di {town}.', 'This is the capital, you know. Everything happens in {town}.'],
      ['Kerajaan ada di sini, di {town}. Ramai orang penting pakai kot.', 'The government is here in {town}. Lots of important people in suits.'],
      ['Namanya pun ibu negara, {town} tak pernah tidur.', 'It is the capital, after all: {town} never sleeps.'],
    ],
    capitalThere: [
      ['Ibu negara kami ialah {capital}. Memang berbaloi dilawati.', 'Our capital is {capital}. Well worth a visit.'],
      ['Dah pergi ke {capital}? Itulah ibu negara kami.', 'Have you been to {capital}? That is our capital.'],
      ['Orang di {capital} rasa merekalah paling hebat. Ibu negara, kan.', 'People in {capital} think they are the best. It is the capital, after all.'],
      ['{capital} lagi besar, tapi saya lebih suka tinggal di sini.', '{capital} is bigger, but I would rather live here.'],
    ],
    big: [
      ['Ini bandar besar. Senang sesat di sini!', 'This is a big city. Easy to get lost here!'],
      ['Jalan sesak, ya ampun! Tapi selalu ada benda menarik.', 'The traffic, good grief! But there is always something going on.'],
      ['Ramainya orang! Seumur hidup di sini pun belum tentu kenal semua jalan.', 'So many people! You could live here all your life and not know every street.'],
      ['Bandar sebesar ni tak pernah berhenti. Saya suka, walaupun penat.', 'A city this big never stops. I love it, though it wears me out.'],
    ],
    middling: [
      ['Tidak besar, tidak kecil. Sedang elok.', 'Not big, not small. Just right.'],
      ['Semua ada, tapi masih boleh jalan kaki.', 'It has everything, and you can still walk it.'],
      ['{town} ni saiznya elok. Sehari dua dah boleh pusing semua.', '{town} is a nice size. In a day or two you can see it all.'],
      ['Orang kata sunyi sangat, tapi tak ada siapa pun nak pindah.', 'People say it is too quiet, but nobody ever wants to move.'],
    ],
    small: [
      ['Ini tempat kecil. Semua orang di sini kenal satu sama lain.', 'This is a small place. Everybody here knows everybody.'],
      ['Tak banyak yang berlaku di {town}, dan kami suka begitu.', 'Not much happens in {town}, and we like it that way.'],
      ['Kampung kecil ni. Bersin sikit, satu kampung tahu.', 'A small village, this. Sneeze once and the whole village knows.'],
      ['Wah, ada pelawat! Inilah benda paling menarik minggu ni.', 'Oh, a visitor! That is the most exciting thing this week.'],
    ],
    coast: [
      ['Kami tinggal di tepi air. Ikannya sangat sedap.', 'We live by the water. The fish is delicious.'],
      ['Bau tu? Itulah laut. Tak pernah jemu.', "Smell that? That's the sea. Never tire of it."],
      ['Nelayan keluar subuh, balik bawa ikan paling segar.', 'The fishermen go out at dawn and come back with the freshest fish.'],
      ['Tengoklah laut masa matahari terbenam. Cantik sangat.', 'Go and look at the sea at sunset. It is beautiful.'],
    ],
    inland: [
      ['Kami jauh dari laut, tetapi alamnya cantik.', 'We are far from the sea, but the countryside is lovely.'],
      ['Pantai? Jauh dari sini. Tapi tengoklah sawah padi tu!', 'The beach? Far from here. But look at those paddy fields!'],
      ['Di sini tanahlah segalanya. Tanah subur, orang pun baik.', 'Out here the land is everything. Rich soil, good people.'],
      ['Terus terang, saya jarang nampak laut. Jauh sangat.', 'Honestly, I rarely see the sea. It is too far.'],
    ],
    high: [
      ['Kita di tanah tinggi. Jalan perlahan-lahan.', "We're in the highlands. Walk slowly."],
      ['Udara sejuk di atas ni. Pemandangannya terbaik!', 'The air is cool up here. The view is the best!'],
      ['Duduk di sini, kaki mesti kuat. Mana ada jalan rata.', 'Live here and your legs get strong. Nothing is flat.'],
      ['Pagi-pagi kabus turun sampai ke jalan. Macam duduk atas awan.', 'In the morning the mist comes down to the road. Like living above the clouds.'],
    ],
    snowy: [
      ['Sejuknya! Semuanya putih.', 'So cold! Everything is white.'],
      ['Salji di sini? Saya pun masih tak percaya.', "Snow, here? I still can't believe it myself."],
      ['Pakai kasut tebal. Ais licin.', 'Wear thick shoes. The ice is slippery.'],
      ['Bila salji baru turun, sunyi sangat. Tenang rasa hati.', 'When fresh snow falls, it is so quiet. It calms the heart.'],
    ],
    forest: [
      ['Hutan di sini luas sangat. Jangan tinggalkan denai!', "The forest here is huge. Don't leave the trail!"],
      ['Pergilah berjalan dalam hutan. Hilang semua serabut kepala.', 'Go for a walk in the forest. It clears all the clutter from your head.'],
      ['Pagi-pagi, dengar bunyi burung dalam hutan. Riuh sangat.', 'Early in the morning, listen to the birds in the forest. Such a racket.'],
      ['Pokok, pokok, pokok lagi. Tapi saya tak nak tinggal tempat lain.', "Trees, trees and more trees. But I wouldn't live anywhere else."],
    ],
    desert: [
      ['Di sini pasir sejauh mata memandang.', 'Here it is sand as far as the eye can see.'],
      ['Minum air banyak-banyak. Padang pasir tak kenal belas kasihan.', 'Drink lots of water. The desert knows no mercy.'],
      ['Malam di padang pasir sejuk, tau. Orang tak pernah percaya.', 'Desert nights are cold, you know. People never believe it.'],
      ['Tunggu malam nanti. Bintang berjuta-juta!', 'Wait until tonight. Millions of stars!'],
    ],
    plains: [
      ['Rata sejauh mata memandang. Hujan datang pun nampak dari jauh.', 'Flat as far as you can see. You can see the rain coming from far away.'],
      ['Langit luas di sini. Angin tak ada yang menghalang.', 'The sky is huge here. Nothing stops the wind.'],
      ['Padang rumput ni elok untuk ternakan. Hati-hati kalau lembu lalu.', 'This grassland is good for livestock. Watch out when the cows go by.'],
      ['Rumputnya tak habis-habis. Macam laut hijau.', 'The grass never ends. Like a green sea.'],
    ],
    tropical: [
      ['Di sini semua tumbuh. Cucuk batang kayu, jadi pokok.', 'Everything grows here. Stick a branch in the ground and it becomes a tree.'],
      ['Bila hujan, hujan betul-betul. Lepas tu berhenti macam tu saja.', 'When it rains, it really rains. Then it just stops, like that.'],
      ['Cuba buah-buahan di pasar. Durian, manggis, rambutan!', 'Try the fruit at the market. Durian, mangosteen, rambutan!'],
      ['Hijau sepanjang tahun. Musim sejuk? Apa tu?', 'Green all year round. Winter? What is that?'],
    ],
    landmark: [
      ['Jangan lepaskan peluang melihat {landmark}! Jaraknya kira-kira {km} km ke arah {dir}.', "Don't miss the chance to see {landmark}! It's about {km} km {dir}."],
      ['Dah tengok {landmark}? Lebih kurang {km} km ke {dir}. Memang berbaloi!', 'Have you seen {landmark}? About {km} km {dir}. Well worth it!'],
      ['Semua orang pergi ke {landmark}. Kira-kira {km} km dari sini, arah {dir}.', 'Everybody goes to {landmark}. About {km} km from here, {dir}.'],
      ['Kalau suka tempat bersejarah, ada {landmark}, {km} km ke arah {dir}.', 'If you like historic places, there is {landmark}, {km} km {dir}.'],
    ],
    landmarkNear: [
      ['{landmark} sangat dekat. Pasti jumpa!', "{landmark} is very close. You can't miss it!"],
      ['Dah pergi ke {landmark}? Dekat saja, belok sikit.', "Been to {landmark} yet? It's close, just round the corner."],
      ['Tiap hari saya nampak {landmark}, dan masih kagum.', 'I see {landmark} every day and I am still amazed.'],
      ['Pergilah ke {landmark} awal pagi, sebelum ramai orang.', 'Go to {landmark} early in the morning, before the crowds.'],
    ],
    plane: [
      ['Ada kapal terbang kecil di padang sebelah {dir}. Pandai terbang?', "There's a little plane in a field {dir}. Can you fly?"],
      ['Ada orang tinggalkan kapal terbang di padang, arah {dir}. Nak terbang?', 'Somebody left a plane in a field {dir}. Fancy a flight?'],
      ['Pandai bawa kapal terbang? Ada satu menunggu di sebelah {dir}.', "Can you fly a plane? There's one waiting {dir}."],
      ['Nak tengok semua dari atas? Ada kapal terbang di sebelah {dir}.', "Want to see it all from above? There's a plane {dir}."],
    ],
    balloon: [
      ['Ada belon udara panas di padang sebelah {dir}! Bayangkan pemandangannya.', "There's a hot-air balloon in a field {dir}! Imagine the view."],
      ['Pernah naik belon udara panas? Ada satu di sebelah {dir}.', 'Ever been up in a hot-air balloon? There is one {dir}.'],
      ['Belon udara naik dari padang di sebelah {dir}. Macam mimpi.', 'A balloon goes up from the field {dir}. Like a dream.'],
      ['Dah lama saya nak cuba belon di sebelah {dir} tu. Tapi takut!', "I've wanted to try that balloon {dir} for ages. But I'm scared!"],
    ],
    boat: [
      ['Ada bot di tepi air sebelah {dir}, kalau nak keluar ke laut.', "There's a boat by the water {dir}, if you want to go out."],
      ['Suka laut? Ada bot di sebelah {dir}. Asalkan dipulangkan!', "Like the sea? There's a boat {dir}. Just bring it back!"],
      ['Ada bot tertambat di sebelah {dir}. Dari sini boleh belayar ke mana-mana.', 'A boat is tied up {dir}. From here you can sail anywhere.'],
      ['Naik bot di sebelah {dir}, tengok pantai dari laut.', 'Take the boat {dir} and see the coast from the sea.'],
    ],
    hot: [
      ['Panasnya hari ini! Carilah tempat teduh.', 'So hot today! Find some shade.'],
      ['Panasnya! Minum air dulu, nampak dahaga.', 'The heat! Have some water, you look thirsty.'],
      ['Panas macam ni, elok duduk bawah pokok saja.', 'In heat like this, best just to sit under a tree.'],
      ['Berbahang betul hari ni! Air kelapa muda paling sesuai.', 'Scorching today! Young coconut water is just the thing.'],
      ['Panas, kan? Ini biasa saja bagi kami!', "Hot, isn't it? This is nothing for us!"],
    ],
    cold: [
      ['Brr, sejuknya hari ini! Pakai baju tebal.', "Brr, it's cold today! Wear something thick."],
      ['Sejuk sampai ke tulang!', 'Cold right to the bone!'],
      ['Sejuk, kan? Minum teh halia, biar panas badan.', "Cold, isn't it? Have some ginger tea to warm up."],
      ['Hidung saya pun dah beku. Mana jaket?', "Even my nose is frozen. Where's your jacket?"],
      ['Bila angin bertiup, lagi teruk.', 'When the wind blows, it gets worse.'],
    ],
    mild: [
      ['Cantiknya cuaca hari ini.', 'What lovely weather today.'],
      ['Tak panas, tak sejuk. Elok sangat, kan?', "Not hot, not cold. Just lovely, isn't it?"],
      ['Hari macam ni, seronok duduk di luar.', 'A day like this, it is nice to be outside.'],
      ['Cerahnya! Harap-harap tak hujan petang nanti.', "So bright! Let's hope it doesn't rain later."],
      ['Cuaca macam nilah sebab kami sayang tempat ni.', 'Weather like this is why we love this place.'],
    ],
    late: [
      ['Sudah lewat malam. Pada waktu malam jalan-jalan sunyi.', 'It is late. The streets are quiet at night.'],
      ['Waktu begini, kucing saja yang keluar. Dan kita!', 'At this hour only the cats are out. And us!'],
      ['Patutnya saya dah tidur. Kenapa belum tidur lagi?', 'I should be asleep by now. Why are you still up?'],
      ['Tengok bintang tu! Paling jelas malam-malam begini.', 'Look at those stars! Clearest on a night like this.'],
    ],
    early: [
      ['Awalnya bangun! Inilah waktu paling best.', "You're up early! The best time of day."],
      ['Gerai roti canai dah buka. Ikut saja bau dia!', 'The roti canai stall has just opened. Follow the smell!'],
      ['Bangun awal, ya? Bandar pun belum bangun lagi.', "An early riser, eh? The town isn't even awake yet."],
      ['Saya suka pagi di sini, sebelum bising.', 'I love the mornings here, before the noise starts.'],
    ],
    country: [
      ['{country} negara yang indah. Selamat menikmatinya!', '{country} is a beautiful country. Enjoy it!'],
      ['Macam mana {country} setakat ini? Seronok?', "How's {country} so far? Enjoying it?"],
      ['Jelajahlah seluruh {country} kalau boleh. Setiap tempat lain-lain.', 'Explore all of {country} if you can. Every place is different.'],
      ['Selamat datang ke {country}! Buat macam rumah sendiri.', 'Welcome to {country}! Make yourself at home.'],
    ],
    dish: [
      ['Selama di sini, wajib cuba {dish}.', "While you're here, you must try {dish}."],
      ['Dah makan {dish}? Belum? Eh, mesti cuba!', 'Have you had {dish} yet? No? Oh, you must!'],
      ['Tak ada siapa masak {dish} sesedap mak saya.', 'Nobody cooks {dish} as well as my mum.'],
      ['Kalau lapar, carilah {dish}. Takkan menyesal.', "If you're hungry, find some {dish}. You won't regret it."],
    ],
    drink: [
      ['Minumlah {drink} dulu sebelum pergi. Inilah minuman kami.', 'Have some {drink} before you go. It is what we drink here.'],
      ['Petang-petang, {drink} paling sedap.', 'In the late afternoon, {drink} is the best.'],
      ['Belum sah datang sini kalau belum rasa {drink}.', "Your visit doesn't count until you've tasted {drink}."],
      ['Pesan {drink} macam orang tempatan, mesti mereka suka.', "Order {drink} like a local and they'll love you for it."],
    ],
    festival: [
      ['Datanglah lagi masa {festival}. Meriah sangat!', 'Come back for {festival}. It is so lively!'],
      ['Masa paling best ke sini ialah waktu {festival}. Semua orang meraikannya.', 'The best time to come is {festival}. Everybody celebrates.'],
      ['Pernah dengar tentang {festival}? Mesti awak suka.', "Ever heard of {festival}? You'd love it."],
      ['Tiap tahun saya kira hari sampai {festival}.', 'Every year I count the days until {festival}.'],
    ],
    sport: [
      ['Di sini semua orang gila {sport}.', "Here everybody's crazy about {sport}."],
      ['Suka {sport}? Di sini kami memang minat gila.', 'Do you like {sport}? We are mad about it here.'],
      ['Kalau ada perlawanan {sport}, satu bandar tengok sama-sama.', 'When there is a {sport} match, the whole town watches together.'],
      ['Satu keluarga saya main {sport}. Nenek cuma menjerit saja.', 'My whole family plays {sport}. Grandma just shouts.'],
    ],
    wonder: [
      ['Kalau sempat, pergilah tengok {wonder}. Takkan dapat lupa.', "If you have time, go and see {wonder}. You'll never forget it."],
      ['Dah tengok {wonder}? Tak ada duanya di dunia.', 'Have you seen {wonder}? There is nothing like it in the world.'],
      ['Sekali seumur hidup, mesti tengok {wonder}.', 'Once in your life, you have to see {wonder}.'],
      ['Masa kecil saya pernah ke {wonder}. Sampai sekarang masih teringat.', 'I went to {wonder} as a child. I still remember it.'],
    ],
    pride: [
      ['Kami sangat bangga dengan {pride}.', 'We are very proud of {pride}.'],
      ['Jangan balik sebelum kenal {pride}. Itulah jati diri kami.', "Don't go home before you get to know {pride}. It is who we are."],
      ['Tahu apa yang buat kami bangga? {pride}.', 'Know what makes us proud? {pride}.'],
      ['Tanyalah sesiapa di sini tentang {pride}, boleh bercerita berjam-jam.', 'Ask anyone here about {pride} and they will talk for hours.'],
    ],
    proverb: [
      ['Kata orang tua-tua: “{proverb}”', 'As the old folk say: “{proverb}”'],
      ['Nenek saya selalu cakap: “{proverb}”', 'My grandmother always said: “{proverb}”'],
      ['Ada peribahasa: “{proverb}”', 'There is a saying: “{proverb}”'],
      ['Tahu peribahasa ni? “{proverb}”', 'Do you know this proverb? “{proverb}”'],
    ],
    chat: [
      ['Dari mana asal awak? Awak bukan orang sini, kan?', "Where are you from? You're not from around here, are you?"],
      ['Ambil masa, lihat-lihat sekeliling. Banyak yang boleh dilihat di sini.', 'Take your time and look around. There is a lot to see here.'],
      ['Jalan seorang diri? Beraninya.', 'Travelling alone? How brave.'],
      ['Dah makan? Hujung jalan tu ada gerai yang sedap.', "Have you eaten? There's a good stall at the end of that street."],
      ['Kalau sesat, tanya saja. Orang sini peramah.', 'If you get lost, just ask. People here are friendly.'],
      ['Tempat mana paling best setakat ni?', "What's the best place so far?"],
      ['Dari dulu saya teringin nak mengembara. Satu hari nanti.', "I've always longed to travel. One day."],
    ],
    childGreet: [
      ['Hai!', 'Hi!'],
      ['Helo! Awak siapa?', 'Hello! Who are you?'],
      ['Hai! Tingginya awak!', "Hi! You're so tall!"],
      ['Helo, helo, helo!', 'Hello, hello, hello!'],
    ],
    childChat: [
      ['Saya boleh lari laju gila! Nak tengok? Nanti la.', 'I can run super fast! Want to see? Later.'],
      ['Awak pelancong, ya? Kawan saya kata pelancong semua kaya.', 'Are you a tourist? My friend says tourists are all rich.'],
      ['Gigi saya tercabut semalam! Tengok! Eh, tak nampak, ya.', "My tooth came out yesterday! Look! Oh, you can't see it."],
      ['Mak kata jangan cakap dengan orang tak kenal. Tapi awak nampak baik.', "Mum says don't talk to strangers. But you look nice."],
      ['Awak ada kucing? Saya nak kucing.', 'Do you have a cat? I want a cat.'],
      ['Bila besar nanti, saya nak jadi juruterbang, pusing satu dunia!', "When I grow up I'm going to be a pilot and fly round the world!"],
      ['Awak pandai main gasing? Saya terror, tau!', "Can you spin a top? I'm brilliant at it!"],
    ],
    childBye: [
      ['Bai bai!', 'Bye-bye!'],
      ['Bai! Datang main lagi, ya!', 'Bye! Come and play again!'],
      ['Saya kena balik, mak panggil!', 'I have to go home, Mum is calling!'],
      ['Jumpa lagi!', 'See you again!'],
    ],
    grumpyGreet: [
      ['Hmm. Nak apa?', 'Hmm. What do you want?'],
      ['Ya? Apa dia?', 'Yes? What is it?'],
      ['Aduh. Pelancong lagi.', 'Oh dear. Another tourist.'],
      ['Hmph. Ya, helo.', 'Hmph. Yes, hello.'],
    ],
    grumpyChat: [
      ['Dulu tempat ni lagi elok, sebelum ramai orang datang.', 'This place was nicer before everybody started coming.'],
      ['Semua benda mahal. Dulu harga barang tak macam ni.', 'Everything is expensive. Prices were never like this.'],
      ['Jangan halang jalan, ya. Orang sini nak lalu.', "Don't block the way, please. People here need to get by."],
      ['Budak-budak zaman sekarang, asyik main telefon.', 'Kids these days, always on their phones.'],
      ['Tak tahu kenapa orang datang sini. Tak ada apa pun.', "I don't know why people come here. There's nothing."],
      ['Jem, panas, bising. Apa lagi nak?', 'Traffic jams, heat, noise. What more could you want?'],
    ],
    grumpyBye: [
      ['Dah. Pergilah.', 'Right. Off you go.'],
      ['Ya, ya. Saya tak nak lambatkan awak.', "Yes, yes. I won't hold you up."],
      ['Hmm. Selamat jalan.', 'Hmm. Goodbye.'],
      ['Jalan elok-elok. Tutup pagar tu!', 'Mind how you go. And shut that gate!'],
    ],
    elderChat: [
      ['Masa saya muda, semua ni sawah padi.', 'When I was young, all of this was paddy fields.'],
      ['Seumur hidup saya tinggal di sini. Lapan puluh tahun! Bayangkan.', "I've lived here all my life. Eighty years! Imagine."],
      ['Dulu kami ke mana-mana jalan kaki. Bagus, jalan kaki tu sihat!', 'Back then we walked everywhere. Good, walking is healthy!'],
      ['Cucu-cucu saya sekarang di luar negara. Setiap Ahad mereka telefon.', 'My grandchildren live abroad now. They call every Sunday.'],
      ['Zaman berubah cepat sangat. Tapi lorong-lorong lama tetap sama.', 'Times change so fast. But the old lanes stay the same.'],
    ],
    chattyChat: [
      ['Aduh, seronoknya jumpa pengembara! Cerita semua. Eh, tunggu, biar saya dulu.', 'Oh, I love meeting travellers! Tell me everything. No, wait, me first.'],
      ['Sepupu saya pernah merantau. Balik-balik bawa janggut dan isteri!', 'My cousin once went off to work far away. Came back with a beard and a wife!'],
      ['Kawan-kawan kata saya boleh bersembang sepanjang hari. Betul pun!', 'My friends say I could chat all day. They are right!'],
      ['Dah makan belum? Nampak lapar. Semua orang nampak lapar bagi saya.', 'Have you eaten? You look hungry. Everybody looks hungry to me.'],
      ['Nak tahu rahsia? Pemandangan paling cantik dari bukit belakang pasar.', 'Want a secret? The best view is from the hill behind the market.'],
    ],
    bye: [
      ['Selamat jalan! Semoga perjalanan menyeronokkan.', 'Goodbye! Have a lovely trip.'],
      ['Jaga diri, ya!', 'Take care!'],
      ['Selamat berjalan-jalan!', 'Enjoy your travels!'],
      ['Bai! Singgahlah lagi.', 'Bye! Drop by again.'],
      ['Seronok bersembang. Jalan elok-elok!', 'Nice chatting. Go carefully!'],
      ['Pergilah! Banyak lagi yang boleh dilihat.', 'Off you go! There is still so much to see.'],
    ],
  },
  countries: {
    // A bare noun phrase, lower-case unless a proper name: Malay has no article to agree.
    MYS: {
      dish: ['nasi lemak', 'nasi lemak (coconut rice with sambal)'],
      drink: ['teh tarik', 'teh tarik (frothy pulled milk tea)'],
      festival: ['Hari Raya Aidilfitri', 'Hari Raya, the feast after Ramadan'],
      sport: ['badminton', 'badminton'],
      wonder: ['Gunung Kinabalu', 'Mount Kinabalu'],
      pride: ['wau bulan', 'the wau bulan, our moon kite'],
      proverb: ['Biar lambat asalkan selamat', 'Better slow, so long as you get there safely'],
    },
    BRN: {
      dish: ['ambuyat', 'ambuyat (sago starch eaten with dips)'],
      festival: ['Hari Raya Aidilfitri', 'Hari Raya, the feast after Ramadan'],
      sport: ['bola sepak', 'football'],
      wonder: ['Taman Negara Ulu Temburong', 'Ulu Temburong National Park'],
      pride: ['Kampong Ayer', 'Kampong Ayer, our village on the water'],
      proverb: ['Bagai aur dengan tebing', 'Like the bamboo and the riverbank, each holding the other up'],
    },
  },
};

export default MS;
