import type { Language } from '../phrases.ts';

const NL: Language = {
  locale: 'nl',
  name: 'Dutch',
  join: ' ',
  compass: [
    'ten noorden van hier', 'ten noordoosten van hier', 'ten oosten van hier', 'ten zuidoosten van hier',
    'ten zuiden van hier', 'ten zuidwesten van hier', 'ten westen van hier', 'ten noordwesten van hier',
  ],
  lines: {
    morning: [
      ['Goedemorgen!', 'Good morning!'],
      ['Morgen! Lekker begin van de dag, hè?', 'Morning! Nice start to the day, eh?'],
      ['O, hallo! Goedemorgen.', 'Oh, hello! Good morning.'],
      ['Hé, ook al zo vroeg op? Goedemorgen!', 'Hey, up this early too? Good morning!'],
    ],
    afternoon: [
      ['Goedemiddag!', 'Good afternoon!'],
      ['Hallo!', 'Hello!'],
      ['Dag! Mooie middag, hè?', 'Hello! Lovely afternoon, isn’t it?'],
      ['Hoi! Lekker middagje, dit.', 'Hi! Nice afternoon, this.'],
    ],
    evening: [
      ['Goedenavond!', 'Good evening!'],
      ['Avond!', 'Evening!'],
      ['Hallo! Mooie avond voor een wandeling.', 'Hello! Nice evening for a walk.'],
      ['O, goedenavond!', 'Oh, good evening!'],
    ],
    night: [
      ['Goedenavond! Het is al laat, hè?', 'Good evening! It’s late already, isn’t it?'],
      ['O! U liet me schrikken. Hallo!', 'Oh! You gave me a fright. Hello!'],
      ['Hallo! Een nachtelijke wandeling?', 'Hello! A night-time walk?'],
      ['Avond! Of is het al ochtend?', 'Evening! Or is it morning already?'],
    ],
    again: [
      ['Hé, u weer! Hallo!', 'Hey, you again! Hello!'],
      ['Bent u daar weer? Leuk!', 'There you are again? Nice!'],
      ['Hallo nogmaals!', 'Hello again!'],
      ['Wij kennen elkaar! Nog steeds op ontdekking?', 'We’ve met! Still exploring?'],
      ['Ah, u bent het! De weg gevonden?', 'Ah, it’s you! Found your way?'],
    ],
    welcome: [
      ['Welkom in {town}!', 'Welcome to {town}!'],
      ['Dit is {town}. Bent u op bezoek?', 'This is {town}. Are you visiting?'],
      ['Voor het eerst in {town}?', 'First time in {town}?'],
      ['U heeft een mooie dag uitgekozen voor {town}.', 'You’ve picked a nice day for {town}.'],
      ['Welkom, welkom! Fijn dat u {town} komt bekijken.', 'Welcome, welcome! Nice of you to come and see {town}.'],
      ['En, wat brengt u naar {town}?', 'So, what brings you to {town}?'],
    ],
    capitalHere: [
      ['{town} is de hoofdstad van ons land.', '{town} is the capital of our country.'],
      ['Dit is de hoofdstad, hoor. In {town} gebeurt alles.', 'This is the capital, you know. Everything happens in {town}.'],
      ['Als hoofdstad slaapt {town} eigenlijk nooit.', 'Being the capital, {town} never really sleeps.'],
      ['Hoofdstad zijn heeft z’n voordelen. In {town} is altijd wat te doen.', 'Being the capital has its perks. There’s always something on in {town}.'],
    ],
    capitalThere: [
      ['Onze hoofdstad is {capital}. Een bezoek waard.', 'Our capital is {capital}. Worth a visit.'],
      ['Bent u al in {capital} geweest? Dat is onze hoofdstad.', 'Have you been to {capital} yet? That’s our capital.'],
      ['Ze denken in {capital} dat ze de baas zijn. Nou ja, dat klopt ook wel.', 'In {capital} they think they’re in charge. Well, they’re right.'],
      ['{capital} is groter, maar ik woon liever hier.', '{capital} is bigger, but I’d rather live here.'],
    ],
    big: [
      ['Dit is een grote stad. Je verdwaalt hier makkelijk!', 'This is a big city. It’s easy to get lost here!'],
      ['Zoveel mensen! Je woont hier je hele leven en kent nog niet elke straat.', 'So many people! You live here all your life and still don’t know every street.'],
      ['Dat verkeer hier, echt. Maar er is altijd wat te doen.', 'The traffic here, honestly. But there’s always something going on.'],
      ['Zo’n grote stad staat nooit stil. Ik vind het heerlijk. Meestal.', 'A big city like this never stands still. I love it. Mostly.'],
    ],
    middling: [
      ['Niet groot, niet klein. Precies goed.', 'Not big, not small. Just right.'],
      ['Groot genoeg voor alles, klein genoeg om te lopen.', 'Big enough for everything, small enough to walk.'],
      ['{town} heeft een fijne maat. In een dag of twee heeft u alles gezien.', '{town} is a nice size. You’ll have seen it all in a day or two.'],
      ['Iedereen klaagt dat het hier te rustig is, en niemand gaat ooit weg.', 'Everybody complains it’s too quiet here, and nobody ever leaves.'],
    ],
    small: [
      ['Het is een klein plaatsje. Iedereen kent iedereen hier.', 'It’s a small place. Everybody knows everybody here.'],
      ['Klein dorp. Als u niest, zegt de hele straat gezondheid.', 'Small village. If you sneeze, the whole street says bless you.'],
      ['Er gebeurt niet veel in {town}, en dat vinden we prima.', 'Not much happens in {town}, and we’re fine with that.'],
      ['U bent het spannendste wat hier deze week is gebeurd!', 'You’re the most exciting thing to happen here this week!'],
    ],
    coast: [
      ['We wonen hier aan het water. De vis is heel lekker.', 'We live by the water here. The fish is very good.'],
      ['Kijk eens naar het water. Elke dag is het anders.', 'Have a look at the water. It’s different every day.'],
      ['Ruikt u dat? Dat is de zee. Daar krijg je nooit genoeg van.', 'Smell that? That’s the sea. You never get enough of it.'],
      ['De boten gaan vroeg uit en komen terug met de lekkerste vis.', 'The boats go out early and come back with the tastiest fish.'],
    ],
    inland: [
      ['De zee is ver weg, maar het land hier is prachtig.', 'The sea is far away, but the land here is gorgeous.'],
      ['Geen strand hier, helaas. Maar kijk eens naar die velden.', 'No beach here, sadly. But look at those fields.'],
      ['Hier is het land alles. Goede grond, goede mensen.', 'Here the land is everything. Good soil, good people.'],
      ['De zee? Dat is een eind rijden. Maar daar zit hier niemand mee.', 'The sea? That’s a long drive. But nobody here minds.'],
    ],
    high: [
      ['We zitten hier hoog. Doe rustig aan, de lucht is dun.', 'We’re high up here. Take it easy, the air is thin.'],
      ['Zo hoog in de heuvels is het uitzicht het mooiste wat we hebben.', 'This high in the hills, the view is the best thing we have.'],
      ['Hierboven krijgt u vanzelf sterke benen. Niets is vlak.', 'Up here you get strong legs without trying. Nothing is flat.'],
      ['Let op uw adem! Aan de hoogte moet je even wennen.', 'Mind your breath! The altitude takes some getting used to.'],
    ],
    snowy: [
      ['Negen maanden sneeuw per jaar. De andere drie klagen we over de modder.', 'Snow nine months a year. The other three, we complain about the mud.'],
      ['Alles is hier wit. U heeft betere schoenen nodig dan die.', 'Everything is white here. You need better shoes than those.'],
      ['De kou deert ons niet. Die houdt de toeristen weg. Aanwezigen uitgezonderd!', 'The cold doesn’t bother us. It keeps the tourists away. Present company excepted!'],
      ['Als er verse sneeuw ligt, is het zo stil dat je jezelf hoort denken.', 'When there’s fresh snow, it’s so quiet you can hear yourself think.'],
    ],
    forest: [
      ['Het bos gaat hier dagen door. Blijf op het pad!', 'The forest goes on for days here. Stay on the path!'],
      ['Maak een wandeling in het bos. Goed voor het hoofd.', 'Take a walk in the woods. Good for the head.'],
      ['Elke herfst zoeken we daar paddenstoelen en bessen.', 'Every autumn we look for mushrooms and berries out there.'],
      ['Bomen, bomen en nog eens bomen. Ik zou nergens anders willen wonen.', 'Trees, trees and more trees. I wouldn’t want to live anywhere else.'],
    ],
    desert: [
      ['Hier is het zand zover je kunt kijken.', 'Here it’s sand as far as you can see.'],
      ['Drink veel water. De woestijn vergeeft niets.', 'Drink plenty of water. The desert forgives nothing.'],
      ['De nachten in de woestijn zijn koud, hoor. Niemand gelooft het.', 'Desert nights are cold, you know. Nobody believes it.'],
      ['Wacht vannacht op de sterren. Hier zijn er miljoenen.', 'Wait for the stars tonight. Out here there are millions.'],
    ],
    plains: [
      ['Het is hier kilometers vlak. Je ziet het weer een dag van tevoren aankomen.', 'It’s flat for miles here. You see the weather coming a day ahead.'],
      ['Veel lucht hier. Niets houdt de wind tegen.', 'Lots of sky here. Nothing stops the wind.'],
      ['Goed weiland, allemaal. Pas op voor de kuddes.', 'Good pasture, all of it. Watch out for the herds.'],
      ['Het gras houdt nooit op. Net een groene zee.', 'The grass never ends. Just like a green sea.'],
    ],
    tropical: [
      ['Hier groeit alles. Steek een stok in de grond en er komt een boom.', 'Everything grows here. Put a stick in the ground and a tree comes up.'],
      ['Als de regen hier komt, dan komt hij echt. En dan stopt het ineens.', 'When the rain comes here, it really comes. And then it suddenly stops.'],
      ['Proef het fruit van de markt. Zoiets heeft u nog nooit gegeten.', 'Taste the fruit from the market. You’ve never eaten anything like it.'],
      ['Het is hier het hele jaar groen. Winter? Wat is dat?', 'It’s green here all year round. Winter? What’s that?'],
    ],
    landmark: [
      ['Mis {landmark} niet! Het ligt ongeveer {km} km {dir}.', 'Don’t miss {landmark}! It’s about {km} km {dir}.'],
      ['Heeft u {landmark} al gezien? Zo’n {km} km {dir}, elke stap waard.', 'Have you seen {landmark}? Some {km} km {dir}, worth every step.'],
      ['Iedereen gaat naar {landmark}. Het is ongeveer {km} km {dir}.', 'Everybody goes to {landmark}. It’s about {km} km {dir}.'],
      ['Heeft u een dag vrij? {landmark} ligt {km} km {dir}. Mensen komen van heinde en verre.', 'Got a day off? {landmark} is {km} km {dir}. People come from far and wide.'],
    ],
    landmarkNear: [
      ['{landmark} is heel dichtbij. U kunt het niet missen!', '{landmark} is very close. You can’t miss it!'],
      ['Al bij {landmark} geweest? Het is hier om de hoek.', 'Been to {landmark} yet? It’s just round the corner.'],
      ['We zien {landmark} elke dag en ik word er nog steeds stil van.', 'We see {landmark} every day and it still leaves me speechless.'],
      ['Ga {landmark} bekijken, het is vlakbij. Vroeg, voor de drukte.', 'Go and see {landmark}, it’s right nearby. Early, before the crowds.'],
    ],
    plane: [
      ['Er staat een klein vliegtuigje in een weiland {dir}. Kunt u vliegen?', 'There’s a little plane in a field {dir}. Can you fly?'],
      ['Iemand heeft een vliegtuig {dir} in het veld laten staan. Zin in een vlucht?', 'Somebody left a plane in the field {dir}. Fancy a flight?'],
      ['Kunt u vliegen? Er staat {dir} een vliegtuig te wachten.', 'Can you fly? There’s a plane waiting {dir}.'],
      ['Wilt u alles van bovenaf zien? Er staat een vliegtuig {dir}.', 'Want to see it all from above? There’s a plane {dir}.'],
    ],
    balloon: [
      ['Er staat een luchtballon in een weiland {dir}! Stelt u zich dat uitzicht voor.', 'There’s a hot-air balloon in a field {dir}! Imagine that view.'],
      ['Heeft u ooit in een luchtballon gezeten? Er staat er een {dir}.', 'Have you ever been in a hot-air balloon? There’s one {dir}.'],
      ['Uit het veld {dir} stijgt een ballon op. Magisch.', 'A balloon rises from the field {dir}. Magical.'],
      ['Die ballon {dir} wil ik al jaren proberen. Maar ik durf niet!', 'I’ve wanted to try that balloon {dir} for years. But I don’t dare!'],
    ],
    boat: [
      ['Er ligt een boot aan het water {dir}, als u het water op wilt.', 'There’s a boat by the water {dir}, if you want to go out on it.'],
      ['Houdt u van water? Er ligt een boot {dir}. Wel terugbrengen, hè!', 'Like the water? There’s a boat {dir}. Do bring it back, mind!'],
      ['Er ligt {dir} een boot aangemeerd. Daarmee kunt u overal heen.', 'There’s a boat moored {dir}. You could go anywhere in it.'],
      ['Neem de boot {dir} en bekijk de kust eens vanaf het water.', 'Take the boat {dir} and see the coast from the water.'],
    ],
    hot: [
      ['Het is warm vandaag! Zoek wat schaduw op.', 'It’s hot today! Find some shade.'],
      ['Pff, wat een hitte! Drink wat water, u ziet eruit alsof u het nodig heeft.', 'Phew, what heat! Drink some water, you look like you need it.'],
      ['Veel te warm om iets te doen. Behalve in de schaduw zitten.', 'Far too hot to do anything. Except sit in the shade.'],
      ['Met deze hitte blijven zelfs de honden binnen.', 'In this heat even the dogs stay indoors.'],
      ['Warm, hè? Ik smelt gewoon.', 'Hot, isn’t it? I’m just melting.'],
    ],
    cold: [
      ['Brr, het is koud vandaag! Kleed u warm aan.', 'Brr, it’s cold today! Wrap up warm.'],
      ['IJskoud! Waar zijn uw handschoenen?', 'Freezing! Where are your gloves?'],
      ['Zo koud dat mijn neus het niet meer doet.', 'So cold my nose has stopped working.'],
      ['Koud genoeg? Wacht maar tot de wind aantrekt.', 'Cold enough? Just wait till the wind picks up.'],
      ['Neem een kop warme chocolademelk. Dat helpt.', 'Have a cup of hot chocolate. It helps.'],
    ],
    mild: [
      ['Wat een heerlijk weer vandaag.', 'What lovely weather today.'],
      ['Niet te warm, niet te koud. Perfecte dag, toch?', 'Not too warm, not too cold. Perfect day, isn’t it?'],
      ['Op zo’n dag wil je gewoon buiten zijn.', 'On a day like this you just want to be outside.'],
      ['Prachtig weer! Laten we hopen dat het zo blijft.', 'Beautiful weather! Let’s hope it stays that way.'],
      ['Voor dit soort dagen wonen we hier.', 'Days like this are why we live here.'],
    ],
    late: [
      ['Het is laat. ’s Nachts zijn de straten rustig.', 'It’s late. The streets are quiet at night.'],
      ['Op dit uur zijn alleen de katten nog buiten. En wij!', 'At this hour only the cats are out. And us!'],
      ['Ik hoor eigenlijk al in bed te liggen. En u?', 'I really ought to be in bed by now. And you?'],
      ['Kijk eens naar de sterren! Hier ziet u ze het best.', 'Look at the stars! You see them best from here.'],
    ],
    early: [
      ['U bent vroeg op! Het mooiste deel van de dag.', 'You’re up early! The best part of the day.'],
      ['De bakker is net open. Volg uw neus!', 'The bakery has just opened. Follow your nose!'],
      ['Zo vroeg al op pad? De stad slaapt nog.', 'Out and about this early? The town is still asleep.'],
      ['Ik hou van de ochtend hier, voordat de drukte begint.', 'I love the morning here, before the bustle starts.'],
    ],
    country: [
      ['{country} is een prachtig land. Geniet ervan!', '{country} is a beautiful country. Enjoy it!'],
      ['Hoe bevalt {country} u tot nu toe?', 'How are you liking {country} so far?'],
      ['Ze zeggen dat {country} klein is op de kaart, maar groot van hart.', 'They say {country} is small on the map, but big of heart.'],
      ['Reis heel {country} door als het kan. Elke hoek is anders.', 'Travel all over {country} if you can. Every corner is different.'],
    ],
    dish: [
      ['U moet {dish} echt proeven nu u hier bent.', 'You really must try {dish} while you’re here.'],
      ['Heeft u al {dish} gegeten? Nee? O, dat moet!', 'Have you had {dish} yet? No? Oh, you must!'],
      ['Niemand maakt {dish} zoals mijn moeder.', 'Nobody makes {dish} like my mother.'],
      ['Trek? Neem {dish}. Daar krijgt u geen spijt van.', 'Peckish? Have {dish}. You won’t regret it.'],
    ],
    drink: [
      ['Drink {drink} voor u verdergaat. Zo doen we dat hier.', 'Have {drink} before you move on. That’s how we do it here.'],
      ['Niets gaat boven {drink} aan het eind van de dag.', 'Nothing beats {drink} at the end of the day.'],
      ['U heeft pas geleefd als u {drink} heeft geproefd.', 'You haven’t lived until you’ve tasted {drink}.'],
      ['Bestel {drink} zoals de mensen hier, dan hoort u er meteen bij.', 'Order {drink} like the locals and you’ll fit right in.'],
    ],
    festival: [
      ['U moet terugkomen voor {festival}. Het is geweldig!', 'You must come back for {festival}. It’s wonderful!'],
      ['De mooiste tijd om hier te zijn is {festival}. Dan is het overal feest.', 'The best time to be here is {festival}. Everywhere is a party then.'],
      ['Heeft u weleens van {festival} gehoord? Dat zou u geweldig vinden.', 'Have you ever heard of {festival}? You’d love it.'],
      ['Ik tel elk jaar de dagen af tot {festival}.', 'Every year I count down the days to {festival}.'],
    ],
    sport: [
      ['Hier draait alles om {sport}.', 'Here it’s all about {sport}.'],
      ['Houdt u van {sport}? Wij zijn er hier gek op.', 'Do you like {sport}? We’re mad about it here.'],
      ['In het weekend praat iedereen hier maar over één ding: {sport}.', 'At the weekend everyone here talks about one thing: {sport}.'],
      ['Mijn hele familie doet aan {sport}. Nou ja, oma schreeuwt alleen.', 'My whole family does {sport}. Well, Grandma just shouts.'],
    ],
    wonder: [
      ['Als u tijd heeft, ga naar {wonder}. Onvergetelijk.', 'If you have time, go to {wonder}. Unforgettable.'],
      ['Heeft u {wonder} al gezien? Nergens ter wereld is zoiets.', 'Have you seen {wonder} yet? There’s nothing like it in the world.'],
      ['Iedereen zou {wonder} één keer in z’n leven moeten zien.', 'Everyone should see {wonder} once in their life.'],
      ['Als kind ben ik naar {wonder} geweest. Ik droom er nog steeds van.', 'I went to {wonder} as a child. I still dream about it.'],
    ],
    pride: [
      ['We zijn hier heel trots op {pride}.', 'We’re very proud of {pride} here.'],
      ['Ga niet weg zonder iets te weten over {pride}. Dat zijn wij.', 'Don’t leave without learning about {pride}. That’s who we are.'],
      ['Weet u waar we trots op zijn? {pride}.', 'You know what we’re proud of? {pride}.'],
      ['Vraag hier iemand naar {pride} en ze praten uren.', 'Ask anyone here about {pride} and they’ll talk for hours.'],
    ],
    proverb: [
      ['Zoals we hier zeggen: “{proverb}”', 'As we say here: “{proverb}”'],
      ['Mijn oma zei altijd: “{proverb}”', 'My grandma always said: “{proverb}”'],
      ['Er is hier een gezegde: “{proverb}”', 'There’s a saying here: “{proverb}”'],
      ['Kent u het gezegde? “{proverb}”', 'Do you know the saying? “{proverb}”'],
    ],
    chat: [
      ['Waar komt u vandaan? U bent niet van hier.', 'Where are you from? You’re not from here.'],
      ['Neem de tijd en kijk rond. Er is veel te zien.', 'Take your time and look around. There’s a lot to see.'],
      ['Reist u alleen? Dapper, hoor.', 'Travelling alone? That’s brave.'],
      ['U ziet eruit alsof u al een heel eind gelopen heeft.', 'You look like you’ve walked a long way.'],
      ['Verdwaald? Vraag het gewoon. De mensen hier zijn vriendelijk.', 'Lost? Just ask. The people here are friendly.'],
      ['Wat is tot nu toe de mooiste plek waar u bent geweest?', 'What’s the most beautiful place you’ve been so far?'],
      ['Ik heb altijd al willen reizen. Misschien ooit nog.', 'I’ve always wanted to travel. Maybe someday.'],
      ['Heeft u een kaart bij u? Zonder kaart ga je de deur niet uit.', 'Have you got a map on you? You don’t go out without a map.'],
    ],
    childGreet: [
      ['Hoi!', 'Hi!'],
      ['Hallo! Wie ben jij?', 'Hello! Who are you?'],
      ['Hoi! Jij bent lang, zeg!', 'Hi! Wow, you’re tall!'],
      ['Hallo, hallo!', 'Hello, hello!'],
    ],
    childChat: [
      ['Ik kan heel hard rennen! Wil je zien? Straks misschien.', 'I can run really fast! Want to see? Maybe later.'],
      ['Ben jij op vakantie? Mijn vriendje zegt dat mensen op vakantie rijk zijn.', 'Are you on holiday? My friend says people on holiday are rich.'],
      ['Gisteren is mijn tand eruit gevallen! Kijk! O, je kunt het niet zien.', 'My tooth fell out yesterday! Look! Oh, you can’t see it.'],
      ['Mama zegt dat ik niet met vreemden mag praten. Maar jij ziet er lief uit.', 'Mum says I mustn’t talk to strangers. But you look nice.'],
      ['Heb jij een hond? Ik wil zo graag een hond.', 'Do you have a dog? I want a dog so much.'],
      ['Als ik groot ben, vlieg ik met een vliegtuig de hele wereld rond!', 'When I grow up I’ll fly a plane all round the world!'],
      ['Ken jij spelletjes? Ik ken er heel veel.', 'Do you know any games? I know loads.'],
    ],
    childBye: [
      ['Doei!', 'Bye!'],
      ['Dag! Kom je nog eens spelen?', 'Bye! Will you come and play again?'],
      ['Ik moet gaan, mama roept!', 'I have to go, Mum’s calling!'],
      ['Daaag! Tot de volgende keer!', 'Byeee! Till next time!'],
    ],
    grumpyGreet: [
      ['Hm. Wat moet u?', 'Hm. What do you want?'],
      ['Ja? Wat is er?', 'Yes? What is it?'],
      ['Och. Alweer bezoek.', 'Oh. Visitors again.'],
      ['Pff. Goedendag dan maar.', 'Pff. Good day, I suppose.'],
    ],
    grumpyChat: [
      ['Vroeger was het hier beter, voordat iedereen kwam kijken.', 'It was better here before everybody came to look.'],
      ['Alles kost tegenwoordig het dubbele.', 'Everything costs double these days.'],
      ['Niet midden op de stoep staan, graag. Hier wonen mensen.', 'Don’t stand in the middle of the pavement, please. People live here.'],
      ['De jeugd van tegenwoordig, altijd op die telefoon.', 'Young people these days, always on those phones.'],
      ['Ik snap niet wat iedereen hier komt doen. Er is niks te zien.', 'I don’t get what everybody comes here for. There’s nothing to see.'],
    ],
    grumpyBye: [
      ['Zo. Ga maar verder dan.', 'Right. Carry on, then.'],
      ['Nou, ik zal u niet ophouden.', 'Well, I won’t keep you.'],
      ['Hm. Dag.', 'Hm. Bye.'],
      ['Pas maar op. En doe het hek dicht.', 'Mind how you go. And shut the gate.'],
    ],
    elderChat: [
      ['Toen ik jong was, was dit allemaal weiland.', 'When I was young, this was all meadow.'],
      ['Ik woon hier mijn hele leven al. Tachtig jaar! Niet te geloven, hè?', 'I’ve lived here all my life. Eighty years! Hard to believe, eh?'],
      ['Vroeger liepen we overal naartoe. U loopt ook, zie ik. Goed zo!', 'We used to walk everywhere. You walk too, I see. Good!'],
      ['Mijn kleinkinderen wonen nu in het buitenland. Elke zondag bellen ze.', 'My grandchildren live abroad now. They call every Sunday.'],
      ['Alles verandert zo snel. Maar de oude straatjes blijven hetzelfde.', 'Everything changes so fast. But the old streets stay the same.'],
    ],
    chattyChat: [
      ['O, ik vind reizigers zo leuk! Vertel alles. Nee, wacht, ik eerst.', 'Oh, I love travellers! Tell me everything. No, wait, me first.'],
      ['Mijn neef ging een keer op reis. Kwam terug met een baard en een vrouw!', 'My cousin went travelling once. Came back with a beard and a wife!'],
      ['Ik kan de hele dag praten, zeggen mijn vrienden. En ze hebben gelijk!', 'I can talk all day, my friends say. And they’re right!'],
      ['Heeft u al gegeten? U ziet er hongerig uit. Dat zeg ik tegen iedereen.', 'Have you eaten? You look hungry. I say that to everyone.'],
      ['Zal ik u een geheimpje vertellen? Het mooiste uitzicht is vanaf de kerktoren.', 'Shall I tell you a secret? The best view is from the church tower.'],
    ],
    bye: [
      ['Tot ziens! Goede reis.', 'Goodbye! Have a good trip.'],
      ['Het ga u goed! Geniet van de rest van de reis.', 'All the best! Enjoy the rest of your journey.'],
      ['Behouden vaart!', 'Safe travels!'],
      ['Dag! Kom nog eens langs.', 'Bye! Do drop by again.'],
      ['Leuk om even te praten. Pas goed op uzelf!', 'Nice to have a chat. Take good care of yourself!'],
      ['Nou, ga maar gauw! Er is nog zoveel te zien.', 'Well, off you go! There’s still so much to see.'],
    ],
  },
  countries: {
    // Every fact is a noun phrase as it stands as an object ("Heeft u al … geproefd?"): bare for a mass noun or a name, with "een" or "de/het" where Dutch uses one.
    NLD: {
      dish: ['stamppot met rookworst', 'stamppot with smoked sausage'],
      drink: ['een jonge jenever', 'a young jenever'],
      festival: ['Koningsdag', 'King’s Day'],
      sport: ['schaatsen', 'speed skating'],
      wonder: ['de Waddenzee', 'the Wadden Sea'],
      pride: ['Rembrandt en Van Gogh', 'Rembrandt and Van Gogh'],
      proverb: ['Doe maar gewoon, dan doe je al gek genoeg', 'Just act normal, that’s crazy enough already'],
    },
    BEL: {
      dish: ['mosselen met friet', 'mussels with fries'],
      drink: ['een trappist', 'a Trappist beer'],
      festival: ['de Gentse Feesten', 'the Ghent Festivities'],
      sport: ['wielrennen', 'cycling'],
      wonder: ['de Grote Markt van Brussel', 'the Grand-Place in Brussels'],
      pride: ['onze chocolade', 'our chocolate'],
      proverb: ['Beter een goede buur dan een verre vriend', 'Better a good neighbour than a distant friend'],
    },
    SUR: {
      dish: ['pom', 'pom, our festive oven dish'],
      drink: ['een koude Parbo', 'a cold Parbo beer'],
      festival: ['Owru Yari', 'Owru Yari, New Year in Paramaribo'],
      sport: ['voetbal', 'football'],
      wonder: ['het Centraal Suriname Natuurreservaat', 'the Central Suriname Nature Reserve'],
      pride: ['de houten binnenstad van Paramaribo', 'the wooden old town of Paramaribo'],
      proverb: ['Oost west, thuis best', 'East, west, home is best'],
    },
    ABW: {
      dish: ['keshi yena', 'keshi yena, stuffed cheese'],
      drink: ['een koude Balashi', 'a cold Balashi beer'],
      festival: ['Carnaval', 'Carnival'],
      sport: ['windsurfen', 'windsurfing'],
      wonder: ['Eagle Beach', 'Eagle Beach'],
      pride: ['onze gastvrijheid', 'our hospitality'],
      proverb: ['Na regen komt zonneschijn', 'After rain comes sunshine'],
    },
    CUW: {
      dish: ['stoba', 'stoba, a slow-cooked stew'],
      drink: ['blue curaçao', 'blue curaçao'],
      festival: ['Carnaval', 'Carnival'],
      sport: ['honkbal', 'baseball'],
      wonder: ['de Handelskade in Willemstad', 'the Handelskade in Willemstad'],
      pride: ['ons Papiamentu', 'our Papiamentu'],
      proverb: ['Wie het kleine niet eert, is het grote niet weerd', 'Who does not honour the small is not worthy of the great'],
    },
  },
};

export default NL;
