import type { Language } from '../phrases.ts';

const PL: Language = {
  locale: 'pl',
  name: 'Polish',
  join: ' ',
  compass: [
    'na północ stąd', 'na północny wschód stąd', 'na wschód stąd', 'na południowy wschód stąd',
    'na południe stąd', 'na południowy zachód stąd', 'na zachód stąd', 'na północny zachód stąd',
  ],
  lines: {
    morning: [
      ['Dzień dobry!', 'Good morning!'],
      ['Dzień dobry! Piękny poranek, co?', 'Good morning! Lovely morning, eh?'],
      ['Dzień dobry, dzień dobry!', 'Morning, morning!'],
      ['Hej, dzień dobry!', 'Hey, good morning!'],
    ],
    afternoon: [
      ['Dzień dobry!', 'Good afternoon!'],
      ['Cześć!', 'Hi!'],
      ['Witam!', 'Hello!'],
      ['O, dzień dobry! Ładne popołudnie, prawda?', "Oh, hello! Nice afternoon, isn't it?"],
    ],
    evening: [
      ['Dobry wieczór!', 'Good evening!'],
      ['Dobry wieczór! Ładny wieczór na spacer.', 'Good evening! Nice evening for a walk.'],
      ['O, dobry wieczór!', 'Oh, good evening!'],
      ['Cześć! Już wieczór, jak ten czas leci.', 'Hi! Evening already, how time flies.'],
    ],
    night: [
      ['Dobry wieczór! Późno już, prawda?', "Good evening! It's late, isn't it?"],
      ['O rany, ale strach! Dobry wieczór.', 'Oh my, what a fright! Good evening.'],
      ['Nocny spacer? Dobry wieczór!', 'A night walk? Good evening!'],
      ['Dobry wieczór! A może już dzień dobry?', 'Good evening! Or is it good morning already?'],
    ],
    again: [
      ['O, to znowu ty! Cześć!', "Oh, it's you again! Hi!"],
      ['Znowu się widzimy!', 'We meet again!'],
      ['Jeszcze raz dzień dobry!', 'Hello once more!'],
      ['A, to ty! Ciągle zwiedzasz?', "Ah, it's you! Still sightseeing?"],
      ['Proszę, proszę, stary znajomy!', 'Well, well, an old acquaintance!'],
    ],
    welcome: [
      ['Witamy w mieście {town}!', 'Welcome to {town}!'],
      ['To jest {town}. Jesteś tu z wizytą?', 'This is {town}. Are you visiting?'],
      ['Pierwszy raz w mieście {town}?', 'First time in {town}?'],
      ['{town} wita serdecznie!', '{town} gives you a warm welcome!'],
      ['Dobry dzień na zwiedzanie. {town} czeka!', 'A good day for sightseeing. {town} awaits!'],
      ['Co cię sprowadza do miasta {town}?', 'What brings you to {town}?'],
    ],
    capitalHere: [
      ['{town} to stolica naszego kraju.', '{town} is the capital of our country.'],
      ['To stolica, wiesz? Tu dzieje się wszystko.', 'This is the capital, you know. Everything happens here.'],
      ['Tu siedzi rząd. Pełno ważnych ludzi w garniturach.', 'The government sits here. Lots of important people in suits.'],
      ['Stolica nigdy nie śpi, a {town} to najlepszy dowód.', 'The capital never sleeps, and {town} is the best proof.'],
    ],
    capitalThere: [
      ['Stolica naszego kraju to {capital}. Warto tam pojechać.', 'Our capital is {capital}. It is worth a trip.'],
      ['{capital}? To nasza stolica. Koniecznie tam zajrzyj.', '{capital}? That is our capital. Do drop in there.'],
      ['W stolicy, czyli w mieście {capital}, myślą, że rządzą krajem. I mają rację.', "In the capital, {capital}, they think they run the country. And they're right."],
      ['{capital} to większe miasto, ale ja wolę tutaj.', '{capital} is a bigger city, but I prefer it here.'],
    ],
    big: [
      ['To duże miasto. Łatwo się tu zgubić!', "It's a big city. Easy to get lost here!"],
      ['Tyle ludzi! Można tu mieszkać całe życie i nie znać wszystkich ulic.', 'So many people! You could live here all your life and not know every street.'],
      ['Te korki, szkoda gadać. Ale zawsze coś się dzieje.', "The traffic, don't get me started. But there's always something going on."],
      ['Duże miasto nigdy nie zasypia. Kocham je. Prawie zawsze.', 'A big city never falls asleep. I love it. Almost always.'],
    ],
    middling: [
      ['Ani duże, ani małe. W sam raz.', 'Not big, not small. Just right.'],
      ['Wszystko jest pod ręką, a wszędzie dojdziesz pieszo.', 'Everything is close at hand, and you can walk everywhere.'],
      ['{town} ma dobry rozmiar. Zobaczysz wszystko w dzień, dwa.', "{town} is a good size. You'll see it all in a day or two."],
      ['Wszyscy narzekają, że tu nudno, a nikt się nie wyprowadza.', "Everybody complains it's boring here, and nobody moves away."],
    ],
    small: [
      ['To małe miejsce. Wszyscy się tu znają.', "It's a small place. Everybody knows everybody."],
      ['Kichniesz na jednym końcu, a na drugim mówią „na zdrowie”.', 'Sneeze at one end and they say "bless you" at the other.'],
      ['W mieście {town} niewiele się dzieje i dobrze nam z tym.', "Not much happens in {town}, and we're happy that way."],
      ['Jesteś największą atrakcją tygodnia!', "You're the biggest attraction of the week!"],
    ],
    coast: [
      ['Mieszkamy tu nad wodą. Ryby są bardzo dobre.', 'We live by the water here. The fish is very good.'],
      ['Idź popatrzeć na wodę. Każdego dnia jest inna.', "Go and look at the water. It's different every day."],
      ['Czujesz? To zapach wody. Nigdy się nie nudzi.', "Smell that? That's the water. You never tire of it."],
      ['Kutry wypływają o świcie i wracają z najlepszą rybą.', 'The boats go out at dawn and come back with the best fish.'],
    ],
    inland: [
      ['Morze jest daleko, ale okolica jest piękna.', 'The sea is far away, but the area is beautiful.'],
      ['Plaży tu nie ma, ale popatrz na te pola.', 'No beach here, but look at those fields.'],
      ['Morze? Szczerze mówiąc, to kawał drogi stąd.', "The sea? Honestly, it's a long way from here."],
      ['Tu ziemia jest najważniejsza. Dobra gleba, dobrzy ludzie.', 'Out here the land is everything. Good soil, good people.'],
    ],
    high: [
      ['Jesteśmy wysoko. Idź powoli, powietrze jest rzadsze.', "We're high up. Go slowly, the air is thinner."],
      ['W górach najlepszy jest widok.', 'In the mountains, the view is the best thing.'],
      ['Tu nic nie jest płaskie. Nogi będą jak ze stali.', "Nothing is flat here. Your legs will turn to steel."],
      ['Łap oddech! Do gór trzeba się przyzwyczaić.', 'Catch your breath! The mountains take getting used to.'],
    ],
    snowy: [
      ['Śnieg przez dziewięć miesięcy. Przez pozostałe trzy narzekamy na błoto.', 'Snow nine months a year. The other three, we complain about the mud.'],
      ['Wszystko tu białe. Przydałyby się lepsze buty.', 'Everything is white here. Better boots would come in handy.'],
      ['Zimno nam nie przeszkadza. Odstrasza turystów. Oczywiście nie ciebie!', "The cold doesn't bother us. It scares off tourists. Not you, of course!"],
      ['Kiedy spadnie świeży śnieg, jest tak cicho, że słychać własne myśli.', 'When fresh snow falls, it is so quiet you can hear your own thoughts.'],
    ],
    forest: [
      ['Lasy ciągną się tu kilometrami. Trzymaj się ścieżki!', 'The woods go on for miles here. Stay on the path!'],
      ['Idź na spacer do lasu. Głowa odpoczywa.', 'Go for a walk in the forest. It rests the mind.'],
      ['Jesienią całe rodziny chodzą na grzyby.', 'In autumn whole families go mushroom picking.'],
      ['Drzewa, drzewa i jeszcze raz drzewa. Nigdzie indziej nie chcę mieszkać.', "Trees, trees and more trees. I don't want to live anywhere else."],
    ],
    desert: [
      ['Tu piasek aż po horyzont.', 'Here it is sand all the way to the horizon.'],
      ['Pij dużo wody. Pustynia nie wybacza.', 'Drink plenty of water. The desert does not forgive.'],
      ['Noce na pustyni są zimne. Nikt w to nie wierzy.', 'Desert nights are cold. Nobody believes it.'],
      ['Zaczekaj do nocy. Gwiazd jest tu mnóstwo.', 'Wait till nightfall. There are loads of stars here.'],
    ],
    plains: [
      ['Płasko jak stół. Burzę widać na długo, zanim przyjdzie.', 'Flat as a table. You see a storm long before it arrives.'],
      ['Wielkie niebo i nic, co zatrzyma wiatr.', 'A big sky and nothing to stop the wind.'],
      ['Dobre pastwiska. Uważaj na stada!', 'Good pasture. Watch out for the herds!'],
      ['Trawa aż po horyzont. Jak zielone morze.', 'Grass to the horizon. Like a green sea.'],
    ],
    tropical: [
      ['Tu wszystko rośnie. Wbij patyk w ziemię, a wyrośnie drzewo.', 'Everything grows here. Stick a twig in the ground and a tree comes up.'],
      ['Jak pada, to leje. A potem nagle przestaje.', 'When it rains, it pours. And then it suddenly stops.'],
      ['Spróbuj owoców z targu. Takich nie ma nigdzie indziej.', "Try the fruit from the market. There's nothing like it anywhere else."],
      ['Zielono przez cały rok. Zima? Jaka zima?', 'Green all year round. Winter? What winter?'],
    ],
    landmark: [
      ['{landmark} — koniecznie zobacz! To jakieś {km} km {dir}.', "{landmark}: you must see it! It's some {km} km {dir}."],
      ['Warto zobaczyć: {landmark}. To około {km} km {dir}.', "Worth seeing: {landmark}. It's about {km} km {dir}."],
      ['Każdy turysta pyta o jedno: {landmark}. Około {km} km {dir}.', 'Every tourist asks about one thing: {landmark}. About {km} km {dir}.'],
      ['Lubisz zabytki? {landmark} jest {km} km {dir}.', 'Do you like old monuments? {landmark} is {km} km {dir}.'],
    ],
    landmarkNear: [
      ['{landmark} jest bardzo blisko. Nie da się przeoczyć!', "{landmark} is very close. You can't miss it!"],
      ['{landmark} jest tuż za rogiem.', '{landmark} is just round the corner.'],
      ['Codziennie na to patrzę: {landmark}. I wciąż zapiera dech.', 'I look at it every day: {landmark}. It still takes my breath away.'],
      ['Idź zobacz, {landmark} jest zaraz tutaj. Najlepiej rano, przed tłumami.', "Go and see, {landmark} is right here. Best in the morning, before the crowds."],
    ],
    plane: [
      ['{dir} stoi na polu mały samolot. Umiesz latać?', "{dir} there's a little plane in a field. Can you fly?"],
      ['Ktoś zostawił samolot na polu, {dir}. Może lot?', 'Somebody left a plane in a field, {dir}. Fancy a flight?'],
      ['Umiesz pilotować? Samolot czeka {dir}.', 'Can you fly a plane? One is waiting {dir}.'],
      ['Chcesz zobaczyć wszystko z góry? Samolot stoi {dir}.', "Want to see it all from above? There's a plane {dir}."],
    ],
    balloon: [
      ['Na polu {dir} stoi balon! Wyobraź sobie ten widok.', "There's a balloon in the field {dir}! Imagine the view."],
      ['Lot balonem? Jest jeden {dir}.', "A balloon flight? There's one {dir}."],
      ['Z łąki {dir} startuje balon. Magia!', 'A balloon goes up from the meadow {dir}. Magic!'],
      ['Balon stoi {dir}. Marzy mi się taki lot, ale za bardzo się boję!', "The balloon is {dir}. I dream of a flight like that, but I'm too scared!"],
    ],
    boat: [
      ['Nad wodą {dir} stoi łódka, jeśli chcesz popłynąć.', "There's a boat by the water {dir}, if you want to go out."],
      ['Lubisz wodę? Łódka czeka {dir}. Tylko ją oddaj!', 'Like the water? A boat is waiting {dir}. Just bring it back!'],
      ['Łódź jest przycumowana {dir}. Stąd dopłyniesz wszędzie.', 'A boat is moored {dir}. From here you can sail anywhere.'],
      ['Weź łódkę {dir} i obejrzyj brzeg od strony wody.', 'Take the boat {dir} and see the shore from the water.'],
    ],
    hot: [
      ['Dziś jest gorąco! Poszukaj trochę cienia.', "It's hot today! Find some shade."],
      ['Uff, co za upał! Napij się wody.', 'Phew, what heat! Have some water.'],
      ['Za gorąco, żeby cokolwiek robić. Tylko cień.', 'Too hot to do anything. Only shade.'],
      ['W taki upał nawet psy siedzą w domu.', 'In heat like this even the dogs stay indoors.'],
      ['Gorąco, co? A to dla nas chłodny dzień!', "Hot, eh? And this is a cool day for us!"],
    ],
    cold: [
      ['Brr, dziś jest zimno! Ubierz się ciepło.', "Brr, it's cold today! Dress warmly."],
      ['Ale ziąb! Gdzie masz rękawiczki?', "It's freezing! Where are your gloves?"],
      ['Tak zimno, że nosa nie czuję.', "So cold I can't feel my nose."],
      ['Zimno? Poczekaj, aż zawieje.', 'Cold? Wait till the wind picks up.'],
      ['Napij się czegoś gorącego. Pomaga.', 'Have something hot to drink. It helps.'],
    ],
    mild: [
      ['Jaka piękna dziś pogoda.', 'What lovely weather today.'],
      ['Ani za ciepło, ani za zimno. Idealnie, prawda?', "Not too warm, not too cold. Perfect, isn't it?"],
      ['W taki dzień aż chce się wyjść z domu.', 'A day like this makes you want to go out.'],
      ['Piękna pogoda! Oby się utrzymała.', "Beautiful weather! Let's hope it lasts."],
      ['Dla takich dni warto tu mieszkać.', "Days like this are why it's worth living here."],
    ],
    late: [
      ['Już późno. Nocą ulice są spokojne.', "It's late. The streets are quiet at night."],
      ['O tej porze po ulicach chodzą tylko koty. I my!', 'At this hour only the cats are out. And us!'],
      ['Pora spać, a tu jeszcze spacer. Czemu nie śpisz?', "It's bedtime, and here we are walking. Why aren't you asleep?"],
      ['Popatrz na gwiazdy! Stąd widać je najlepiej.', 'Look at the stars! You see them best from here.'],
    ],
    early: [
      ['Wcześnie wstajesz! To najlepsza pora dnia.', "You're up early! The best time of the day."],
      ['Piekarnia właśnie otwarta. Idź za zapachem!', 'The bakery has just opened. Follow the smell!'],
      ['Ranny ptaszek, co? Miasto jeszcze śpi.', 'Early bird, eh? The town is still asleep.'],
      ['Uwielbiam tu poranki, zanim zacznie się hałas.', 'I love the mornings here, before the noise starts.'],
    ],
    country: [
      ['{country} to piękny kraj. Ciesz się nim!', '{country} is a beautiful country. Enjoy it!'],
      ['Jak ci się podoba? {country} to kraj pełen niespodzianek.', 'How do you like it? {country} is a country full of surprises.'],
      ['{country} to kraj, w którym każdy zakątek jest inny.', '{country} is a country where every corner is different.'],
      ['{country} to może nie największy kraj, ale serce ma ogromne.', '{country} may not be the biggest country, but its heart is huge.'],
    ],
    dish: [
      ['{dish} — tego musisz tu spróbować.', "{dish}: you have to try that while you're here."],
      ['{dish}? Jeszcze nie? To trzeba nadrobić!', '{dish}? Not yet? We have to fix that!'],
      ['Najlepsze na świecie? {dish} mojej mamy.', "The best in the world? My mum's {dish}."],
      ['Masz ochotę coś zjeść? {dish}, nie pożałujesz.', "Feel like eating something? {dish}, you won't regret it."],
    ],
    drink: [
      ['{drink} — tego napij się, zanim wyjedziesz.', '{drink}: have some before you leave.'],
      ['Na koniec dnia nie ma nic lepszego niż {drink}.', 'At the end of the day there is nothing better than {drink}.'],
      ['{drink} to coś, czego trzeba tu spróbować.', '{drink} is something you have to try here.'],
      ['Chcesz uchodzić za miejscowego? Zamów to: {drink}.', 'Want to pass for a local? Order this: {drink}.'],
    ],
    festival: [
      ['{festival} to najlepszy czas, żeby tu przyjechać.', '{festival} is the best time to come here.'],
      ['Najpiękniejszy czas w roku? {festival}. Świętuje cały kraj.', 'The most beautiful time of the year? {festival}. The whole country celebrates.'],
      ['{festival} — musisz to kiedyś przeżyć!', '{festival}: you have to experience it one day!'],
      ['Czekam cały rok na jedno: {festival}.', 'I wait all year for one thing: {festival}.'],
    ],
    sport: [
      ['Tu rządzi {sport}. Wszyscy grają.', 'Here {sport} rules. Everybody plays.'],
      ['W dzień meczu całe miasto żyje jednym: {sport}.', 'On match day the whole town lives for one thing: {sport}.'],
      ['{sport} to u nas prawie religia.', '{sport} is almost a religion here.'],
      ['Moja rodzina żyje tym: {sport}. Babcia tylko krzyczy przed telewizorem.', 'My family lives for it: {sport}. Grandma just shouts at the telly.'],
    ],
    wonder: [
      ['{wonder} — jeśli masz czas, musisz to zobaczyć.', '{wonder}: if you have time, you must see it.'],
      ['{wonder} to coś, czego nie ma nigdzie indziej.', '{wonder} is like nothing else anywhere.'],
      ['Każdy powinien raz w życiu to zobaczyć: {wonder}.', 'Everyone should see it once in their life: {wonder}.'],
      ['Mówię ci: {wonder} to widok na całe życie.', "I'm telling you: {wonder} is a sight for a lifetime."],
    ],
    pride: [
      ['Nasza duma? {pride}.', 'Our pride? {pride}.'],
      ['Wiesz, z czego jesteśmy dumni? {pride}.', 'Do you know what we are proud of? {pride}.'],
      ['{pride} to nasz skarb.', '{pride} is our treasure.'],
      ['Zapytaj kogokolwiek o to: {pride}. Będzie gadać godzinami.', "Ask anyone about it: {pride}. They'll talk for hours."],
    ],
    proverb: [
      ['Jak to u nas mówią: „{proverb}”', 'As we say here: “{proverb}”'],
      ['Moja babcia zawsze mówiła: „{proverb}”', 'My grandmother always said: “{proverb}”'],
      ['Jest takie przysłowie: „{proverb}”', 'There is a saying: “{proverb}”'],
      ['Znasz to powiedzenie? „{proverb}”', 'Do you know the saying? “{proverb}”'],
    ],
    chat: [
      ['Skąd jesteś? Nie jesteś stąd.', "Where are you from? You're not from here."],
      ['Nie spiesz się i rozejrzyj się. Jest tu wiele do zobaczenia.', 'Take your time and look around. There is a lot to see here.'],
      ['Podróżujesz w pojedynkę? Odważnie!', 'Travelling on your own? Brave!'],
      ['Wyglądasz na kogoś, kto przeszedł kawał drogi.', 'You look like someone who has walked a long way.'],
      ['Jak się zgubisz, pytaj śmiało. Ludzie tu są życzliwi.', 'If you get lost, just ask. People here are kind.'],
      ['Gdzie było najpiękniej do tej pory?', 'Where has been the most beautiful so far?'],
      ['Marzy mi się podróż dookoła świata. Może kiedyś.', 'I dream of a trip round the world. Maybe one day.'],
      ['Masz mapę? Mapa to podstawa.', 'Have you got a map? A map is the basics.'],
    ],
    childGreet: [
      ['Cześć!', 'Hi!'],
      ['Cześć! A ty kto?', 'Hi! And who are you?'],
      ['Hejka! Ile masz lat?', 'Hiya! How old are you?'],
      ['Cześć, cześć!', 'Hi, hi!'],
    ],
    childChat: [
      ['Umiem bardzo szybko biegać! Chcesz zobaczyć? Może potem.', 'I can run really fast! Want to see? Maybe later.'],
      ['Kolega mówi, że turyści są bogaci. To prawda?', 'My friend says tourists are rich. Is it true?'],
      ['Wczoraj wypadł mi ząb! Patrz! A, nie widać.', "My tooth fell out yesterday! Look! Oh, you can't see it."],
      ['Mama mówi, że nie wolno rozmawiać z obcymi. Ale ty wyglądasz miło.', 'Mum says I must not talk to strangers. But you look nice.'],
      ['Masz psa? Ja chcę psa!', 'Do you have a dog? I want a dog!'],
      ['Jak dorosnę, polecę samolotem dookoła świata!', "When I grow up, I'll fly a plane round the world!"],
      ['Znasz jakieś gry? Ja znam mnóstwo!', 'Do you know any games? I know loads!'],
    ],
    childBye: [
      ['Pa pa!', 'Bye bye!'],
      ['Pa! Przyjdź się pobawić!', 'Bye! Come and play!'],
      ['Muszę lecieć, mama woła!', 'I have to run, mum is calling!'],
      ['Na razie, na razie!', 'See you, see you!'],
    ],
    grumpyGreet: [
      ['Hm. Czego?', 'Hm. What do you want?'],
      ['No? O co chodzi?', "Well? What's this about?"],
      ['Aha. Znowu turyści.', 'Right. Tourists again.'],
      ['Hmpf. No, dzień dobry.', 'Hmph. Well, hello.'],
    ],
    grumpyChat: [
      ['Kiedyś było tu lepiej, zanim wszyscy zaczęli tu przyjeżdżać.', 'It was better here before everybody started coming.'],
      ['Wszystko kosztuje dwa razy tyle co kiedyś.', 'Everything costs twice what it used to.'],
      ['Nie tarasuj chodnika, ludzie tu mieszkają.', "Don't block the pavement, people live here."],
      ['Ta dzisiejsza młodzież. Tylko te telefony.', "Young people these days. Always those phones."],
      ['Nie wiem, po co tu ktoś przyjeżdża. Nie ma na co patrzeć.', "I don't know why anyone comes here. Nothing to look at."],
    ],
    grumpyBye: [
      ['No to idź już.', 'Off you go, then.'],
      ['Nie zatrzymuję.', "I won't keep you."],
      ['Hm. Do widzenia.', 'Hm. Goodbye.'],
      ['Uważaj na siebie. I zamknij furtkę.', 'Mind how you go. And shut the gate.'],
    ],
    elderChat: [
      ['Za mojej młodości tu były same pola.', 'When I was young, this was all fields.'],
      ['Mieszkam tu całe życie. Osiemdziesiąt lat! Wyobrażasz sobie?', "I've lived here all my life. Eighty years! Can you imagine?"],
      ['Za moich czasów wszędzie chodziło się pieszo. Ty też chodzisz. Brawo!', 'In my day we walked everywhere. You walk too. Well done!'],
      ['Wnuki mieszkają teraz za granicą. Dzwonią w każdą niedzielę.', 'My grandchildren live abroad now. They call every Sunday.'],
      ['Wszystko się tak szybko zmienia. Tylko stare uliczki są te same.', 'Everything changes so fast. Only the old streets stay the same.'],
    ],
    chattyChat: [
      ['Och, uwielbiam podróżników! Opowiadaj wszystko. Nie, czekaj, najpierw ja!', 'Oh, I love travellers! Tell me everything. No, wait, me first!'],
      ['Mój kuzyn raz pojechał w podróż. Wrócił z brodą i z żoną!', 'My cousin went travelling once. He came back with a beard and a wife!'],
      ['Przyjaciele mówią, że mogę gadać cały dzień. Mają rację!', "My friends say I could talk all day. They're right!"],
      ['A obiad był? Wszyscy mi wyglądają na głodnych!', 'Had your lunch? Everybody looks hungry to me!'],
      ['Zdradzę ci sekret: najpiękniejszy widok jest ze wzgórza za kościołem.', "I'll tell you a secret: the best view is from the hill behind the church."],
    ],
    bye: [
      ['Do widzenia! Szczęśliwej podróży.', 'Goodbye! Have a good trip.'],
      ['Trzymaj się! Miłej dalszej drogi.', 'Take care! Enjoy the rest of your journey.'],
      ['Szerokiej drogi!', 'Safe travels!'],
      ['Pa! Wpadnij jeszcze kiedyś.', 'Bye! Drop by again some time.'],
      ['Miło się rozmawiało. Uważaj na siebie!', 'Nice talking to you. Look after yourself!'],
      ['No to w drogę! Tyle jeszcze do zobaczenia.', "Off you go, then! There's so much still to see."],
    ],
  },
  countries: {
    // Every fact in the nominative: the templates set it as a subject, after "to", "niż" or a colon or dash.
    POL: {
      dish: ['pierogi', 'pierogi'],
      drink: ['miód pitny', 'mead'],
      festival: ['Wigilia', 'Wigilia, the Christmas Eve supper'],
      sport: ['piłka nożna', 'football'],
      wonder: ['Tatry', 'the Tatra Mountains'],
      pride: ['muzyka Chopina', "Chopin's music"],
      proverb: ['Gość w dom, Bóg w dom', 'A guest in the house is God in the house'],
    },
  },
};

export default PL;
