import type { Language } from '../phrases.ts';

/**
 * Portuguese: Brazil, Portugal, Angola, Mozambique, Guinea-Bissau, Cape
 * Verde, São Tomé and Príncipe and Timor-Leste. The lines lean on the verb
 * alone (*Está de visita?*, *Aproveite!*), which is courteous in Lisbon and
 * natural in São Paulo, rather than choosing between *você* and *tu*; they
 * avoid the words the two sides of the ocean name differently, and nothing
 * agrees with the speaker's or the listener's sex (no *obrigado*, no
 * *bem-vindo* to one person).
 */
const PT: Language = {
  locale: 'pt',
  name: 'Portuguese',
  join: ' ',
  compass: ['ao norte', 'a nordeste', 'a leste', 'a sudeste', 'ao sul', 'a sudoeste', 'a oeste', 'a noroeste'],
  lines: {
    morning: [
      ['Bom dia!', 'Good morning!'],
      ['Olá, bom dia!', 'Hello, good morning!'],
      ['Bom dia! Que manhã bonita, não é?', "Good morning! What a lovely morning, isn't it?"],
      ['Ah, muito bom dia!', 'Ah, a very good morning!'],
    ],
    afternoon: [
      ['Boa tarde!', 'Good afternoon!'],
      ['Olá!', 'Hello!'],
      ['Olá, boa tarde! Tudo bem?', 'Hello, good afternoon! All good?'],
      ['Boa tarde! Está uma tarde agradável, não está?', "Good afternoon! It's a pleasant afternoon, isn't it?"],
    ],
    evening: [
      ['Boa noite!', 'Good evening!'],
      ['Olá, boa noite!', 'Hello, good evening!'],
      ['Boa noite! Bela noite para um passeio.', 'Good evening! A fine evening for a stroll.'],
      ['Ah, boa noite! Tudo bem?', 'Ah, good evening! All well?'],
    ],
    night: [
      ['Boa noite! Já é tarde, não é?', "Good evening! It's late already, isn't it?"],
      ['Ai, que susto! Olá!', 'Oh, what a fright! Hello!'],
      ['Olá! Passeio noturno?', 'Hello! A night-time walk?'],
      ['Boa noite! Ou já é bom dia?', 'Good evening! Or is it good morning already?'],
    ],
    again: [
      ['Olha quem voltou! Olá!', 'Look who is back! Hello!'],
      ['Outra vez por aqui? Que bom rever essa cara.', 'Round here again? Good to see that face again.'],
      ['Olá de novo!', 'Hello again!'],
      ['Já nos conhecemos! Então, já explorou tudo?', 'We have met! So, explored everything yet?'],
      ['Ah, é a pessoa do mapa! Encontrou o caminho?', "Ah, it's the one with the map! Did you find the way?"],
    ],
    welcome: [
      ['Bem-vindos! Isto aqui é {town}.', 'Welcome! This is {town}.'],
      ['Aqui é {town}. Está de visita?', 'This is {town}. Are you visiting?'],
      ['Primeira vez por aqui? Então aproveite bem.', 'First time around here? Then make the most of it.'],
      ['Escolheu um belo dia para conhecer {town}.', 'You picked a fine day to get to know {town}.'],
      ['{town} dá as boas-vindas! Fique à vontade.', '{town} bids you welcome! Make yourself at home.'],
      ['Então, veio conhecer a cidade? Isto é {town}!', 'So, you came to see the town? This is {town}!'],
    ],
    capitalHere: [
      ['{town} é a capital do nosso país.', '{town} is the capital of our country.'],
      ['Isto aqui é a capital, sabe? Aqui acontece de tudo.', 'This is the capital, you know? Everything happens here.'],
      ['O governo fica aqui, sabe? Muita gente engravatada.', 'The government is here, you know. Lots of people in ties.'],
      ['Sendo a capital, {town} nunca dorme de verdade.', 'Being the capital, {town} never really sleeps.'],
    ],
    capitalThere: [
      ['A nossa capital é {capital}. Vale a visita.', 'Our capital is {capital}. Worth the visit.'],
      ['Já conhece {capital}? É a nossa capital.', "Do you know {capital} yet? It's our capital."],
      ['Lá em {capital} acham que mandam em tudo. E mandam mesmo.', 'Over in {capital} they think they run everything. And they really do.'],
      ['{capital} é maior, mas eu prefiro viver aqui.', "{capital} is bigger, but I'd rather live here."],
    ],
    big: [
      ['Esta é uma cidade grande. Aqui é fácil perder o rumo!', "This is a big city. It's easy to lose your way here!"],
      ['Tanta gente! Dá para viver aqui a vida inteira sem conhecer todas as ruas.', "So many people! You can live here a lifetime and not know every street."],
      ['O trânsito aqui é uma loucura. Mas há sempre alguma coisa para fazer.', "The traffic here is crazy. But there's always something to do."],
      ['Uma cidade destas nunca para. Eu gosto, quase sempre.', 'A city like this never stops. I like it, most of the time.'],
    ],
    middling: [
      ['Nem grande, nem pequena. Na medida certa.', 'Neither big nor small. Just the right size.'],
      ['Grande o suficiente para ter tudo, pequena o suficiente para andar a pé.', 'Big enough to have everything, small enough to walk.'],
      ['{town} tem um bom tamanho. Em dois dias dá para ver tudo.', '{town} is a good size. In two days you can see it all.'],
      ['Todos dizem que é sossegada demais, e ninguém vai embora.', 'Everyone says it is too quiet, and nobody leaves.'],
    ],
    small: [
      ['É um lugar pequeno. Aqui todos se conhecem.', "It's a small place. Everyone knows each other here."],
      ['Terra pequena: se alguém espirra, a rua inteira diz saúde.', 'Small town: if someone sneezes, the whole street says bless you.'],
      ['Aqui quase nada acontece, e é assim que gostamos.', 'Hardly anything happens here, and that is how we like it.'],
      ['Isto é a maior novidade da semana: uma visita!', 'This is the biggest news of the week: a visitor!'],
    ],
    coast: [
      ['Aqui vivemos à beira da água. O peixe é muito bom.', 'We live by the water here. The fish is very good.'],
      ['Vá ver o mar. Cada dia é diferente.', 'Go and look at the sea. Every day it is different.'],
      ['Sente este cheiro? É o mar. Ninguém se cansa dele.', "Smell that? That's the sea. You never tire of it."],
      ['Os barcos saem de madrugada e voltam com o melhor peixe que já provou.', "The boats go out at dawn and come back with the best fish you've ever tasted."],
    ],
    inland: [
      ['Estamos longe do mar, mas esta terra é linda.', 'We are far from the sea, but this land is lovely.'],
      ['Praia aqui não há, lamento. Mas olhe só para estes campos.', "There's no beach here, sorry. But just look at these fields."],
      ['O mar? Fica longe daqui. Muito longe.', "The sea? It's far from here. Very far."],
      ['Aqui a terra é tudo. Terra boa, gente boa.', 'Here the land is everything. Good soil, good people.'],
    ],
    high: [
      ['Aqui estamos no alto. Vá com calma, o ar é rarefeito.', "We're high up here. Go easy, the air is thin."],
      ['Aqui de cima, a vista é o melhor que temos.', 'From up here, the view is the best thing we have.'],
      ['Quem vive aqui fica com pernas de aço. Nada é plano.', 'Whoever lives here gets legs of steel. Nothing is flat.'],
      ['Cuidado com o fôlego! No começo, a altitude cansa.', 'Mind your breath! At first, the altitude wears you out.'],
    ],
    snowy: [
      ['Aqui neva metade do ano. Na outra metade, é a lama.', "It snows half the year here. The other half, it's the mud."],
      ['É tudo branco. Vai precisar de botas melhores do que essas.', "It's all white. You'll need better boots than those."],
      ['O frio não nos incomoda. Afasta os turistas, com todo o respeito!', "The cold doesn't bother us. It keeps the tourists away, no offence!"],
      ['Com neve fresca, é tanto silêncio que se ouve o pensamento.', 'With fresh snow it is so quiet you can hear yourself think.'],
    ],
    forest: [
      ['A floresta aqui não acaba nunca. Não saia do trilho!', 'The forest here never ends. Stay on the trail!'],
      ['Dê um passeio pela mata. Faz bem à cabeça.', 'Take a walk in the woods. It does the head good.'],
      ['No outono vamos todos colher cogumelos e frutos silvestres.', 'In autumn we all go picking mushrooms and berries.'],
      ['Árvores, árvores e mais árvores. Não trocava isto por nada.', "Trees, trees and more trees. I wouldn't swap this for anything."],
    ],
    desert: [
      ['Aqui é areia até perder de vista.', 'Here it’s sand as far as the eye can see.'],
      ['Beba muita água. O deserto não perdoa.', 'Drink lots of water. The desert does not forgive.'],
      ['As noites no deserto são frias, sabia? Ninguém acredita.', 'Desert nights are cold, did you know? Nobody believes it.'],
      ['Espere pelas estrelas esta noite. Aqui dá para ver milhões.', 'Wait for the stars tonight. Out here you can see millions.'],
    ],
    plains: [
      ['É tudo plano. Dá para ver a chuva chegar com um dia de antecedência.', "It's all flat. You can see the rain coming a day ahead."],
      ['Céu enorme, aqui. Nada segura o vento.', 'A huge sky here. Nothing holds back the wind.'],
      ['Pasto bom, por todo o lado. Cuidado com o gado!', 'Good pasture everywhere. Watch out for the cattle!'],
      ['O pasto não acaba nunca. Parece um mar verde.', 'The grass never ends. It looks like a green sea.'],
    ],
    tropical: [
      ['Aqui tudo cresce. É só plantar um pau que nasce uma árvore.', 'Everything grows here. Plant a stick and a tree comes up.'],
      ['Quando chove aqui, chove de verdade. Depois para, assim de repente.', 'When it rains here, it really rains. Then it stops, just like that.'],
      ['Prove a fruta do mercado. Nunca comeu nada assim.', "Try the fruit at the market. You've never eaten anything like it."],
      ['É verde o ano todo. Inverno? O que é isso?', "It's green all year. Winter? What's that?"],
    ],
    landmark: [
      ['Não perca {landmark}! Fica a uns {km} km {dir}.', "Don't miss {landmark}! It's about {km} km {dir}."],
      ['Já viu {landmark}? Fica a {km} km {dir} e vale cada passo.', "Have you seen {landmark}? It's {km} km {dir} and worth every step."],
      ['Todos vão ver {landmark}. Fica a uns {km} km {dir}.', "Everybody goes to see {landmark}. It's about {km} km {dir}."],
      ['Se gosta de coisas antigas, {landmark} fica a {km} km {dir}.', 'If you like old things, {landmark} is {km} km {dir}.'],
    ],
    landmarkNear: [
      ['{landmark} fica bem perto. Não tem como errar!', "{landmark} is very close. You can't go wrong!"],
      ['Já foi ver {landmark}? Fica logo ali.', "Have you been to see {landmark}? It's just over there."],
      ['Vemos {landmark} todos os dias e ainda nos tira o fôlego.', 'We see {landmark} every day and it still takes our breath away.'],
      ['Vá ver {landmark}, é já aqui. Cedo, antes da multidão.', "Go and see {landmark}, it's right here. Early, before the crowds."],
    ],
    plane: [
      ['Há um aviãozinho num campo {dir}, se souber pilotar!', "There's a little plane in a field {dir}, if you can fly!"],
      ['Alguém deixou um avião num campo {dir}. Que tal um voo?', 'Someone left a plane in a field {dir}. How about a flight?'],
      ['Sabe pilotar? Há um avião à espera {dir}.', "Can you fly? There's a plane waiting {dir}."],
      ['Se quer ver tudo lá de cima, há um avião {dir}.', "If you want to see it all from above, there's a plane {dir}."],
    ],
    balloon: [
      ['Há um balão de ar quente num campo {dir}! Imagine a vista.', "There's a hot-air balloon in a field {dir}! Imagine the view."],
      ['Já voou de balão? Há um {dir}.', "Ever flown in a balloon? There's one {dir}."],
      ['Do campo {dir} sobe um balão. É uma coisa mágica.', 'A balloon goes up from the field {dir}. It is something magical.'],
      ['Sempre quis andar no balão {dir}. Mas que medo!', 'I always wanted to ride the balloon {dir}. But how scary!'],
    ],
    boat: [
      ['Há um barco na margem {dir}, se quiser ir para a água.', "There's a boat on the shore {dir}, if you want to go out on the water."],
      ['Se gosta de mar, há um barco {dir}. É só devolver depois!', "If you like the sea, there's a boat {dir}. Just bring it back after!"],
      ['Tem um barco amarrado {dir}. Daqui dá para ir a qualquer lado.', "There's a boat tied up {dir}. From here you can go anywhere."],
      ['Com o barco {dir}, dá para ver a costa do lado do mar.', 'With the boat {dir}, you can see the coast from the sea side.'],
    ],
    hot: [
      ['Hoje está calor! Procure uma sombra.', "It's hot today! Find some shade."],
      ['Que calorão! Beba água, faz bem.', 'What a scorcher! Drink some water, it does you good.'],
      ['Com este calor só apetece ficar à sombra.', 'In this heat all you want is to sit in the shade.'],
      ['Com um calor destes, até os cães ficam em casa.', 'In heat like this, even the dogs stay indoors.'],
      ['Quente, não é? E para nós hoje até está fresquinho!', "Hot, isn't it? And for us today is actually cool!"],
    ],
    cold: [
      ['Brr, hoje está frio! Agasalhe-se bem.', "Brr, it's cold today! Wrap up well."],
      ['Que gelo! E as luvas?', 'It’s freezing! Where are the gloves?'],
      ['Está tanto frio que já nem sinto o nariz.', "It's so cold I can't even feel my nose."],
      ['Friozinho, hein? Espere até o vento apertar.', 'A bit chilly, eh? Wait till the wind picks up.'],
      ['Beba algo quente. Ajuda muito.', 'Drink something hot. It helps a lot.'],
    ],
    mild: [
      ['Que tempo bom hoje.', 'What nice weather today.'],
      ['Nem calor nem frio. Um dia perfeito, não acha?', "Not hot, not cold. A perfect day, don't you think?"],
      ['Num dia assim, apetece estar na rua.', 'On a day like this, you want to be outdoors.'],
      ['Que dia lindo! Tomara que dure.', "What a beautiful day! Let's hope it lasts."],
      ['É por dias como este que vivemos aqui.', 'Days like this are why we live here.'],
    ],
    late: [
      ['Já é tarde. À noite as ruas ficam tranquilas.', "It's late. At night the streets are quiet."],
      ['A esta hora só andam por aí os gatos. E nós!', 'At this hour only the cats are out. And us!'],
      ['Eu já devia estar na cama. E o que faz na rua a esta hora?', 'I should be in bed by now. And what are you doing out at this hour?'],
      ['Olhe as estrelas! Daqui dá para ver tão bem.', 'Look at the stars! You can see them so well from here.'],
    ],
    early: [
      ['Já de pé? É a melhor parte do dia.', "Up already? It's the best part of the day."],
      ['A padaria acabou de abrir. Siga o cheirinho!', 'The bakery has just opened. Follow the smell!'],
      ['Madrugou, hein? A cidade ainda nem acordou.', "Up with the lark, eh? The town isn't even awake yet."],
      ['Adoro a manhã aqui, antes de começar o barulho.', 'I love the morning here, before the noise starts.'],
    ],
    country: [
      ['{country}: um país lindo. Aproveite!', '{country}: a lovely country. Enjoy it!'],
      ['Então, que tal? {country} tem muito para ver.', 'So, how is it? {country} has a lot to see.'],
      ['Pode parecer pouca coisa no mapa, mas {country} tem um coração enorme.', 'It may look like little on the map, but {country} has a huge heart.'],
      ['Viaje por todo o lado, se puder. {country} muda a cada canto.', '{country} changes at every corner. Travel everywhere, if you can.'],
    ],
    dish: [
      ['Não deixe de provar {dish} enquanto estiver por aqui.', "Don't miss trying {dish} while you're here."],
      ['Já comeu {dish}? Não? Ah, tem mesmo de provar!', 'Have you had {dish} yet? No? Oh, you really must try it!'],
      ['Ninguém faz {dish} como a minha mãe.', 'Nobody makes {dish} like my mother.'],
      ['Se estiver com fome, peça {dish}. Não se vai arrepender.', "If you're hungry, order {dish}. You won't regret it."],
    ],
    drink: [
      ['Antes de ir, prove {drink}. É o que se bebe aqui.', "Before you go, try {drink}. It's what we drink here."],
      ['No fim do dia, nada melhor que {drink}.', 'At the end of the day, nothing beats {drink}.'],
      ['Quem nunca provou {drink} não sabe o que perde.', "Whoever never tried {drink} doesn't know what they're missing."],
      ['Peça {drink} como quem é daqui e vai ver os sorrisos.', "Order {drink} like a local and you'll see the smiles."],
    ],
    festival: [
      ['Tem de voltar para ver {festival}. É uma maravilha!', 'You have to come back to see {festival}. It is wonderful!'],
      ['A melhor época para vir? {festival}, sem dúvida.', 'The best time to come? {festival}, no doubt.'],
      ['Conhece {festival}? Ia adorar.', "Do you know {festival}? You'd love it."],
      ['Todos os anos espero {festival} como uma criança.', 'Every year I wait for {festival} like a child.'],
    ],
    sport: [
      ['Aqui só se pensa numa coisa: {sport}. Todos jogam.', 'Here there is only one thing on our minds: {sport}. Everyone plays.'],
      ['E {sport}, gosta? Aqui somos doidos por isso.', 'And {sport}, do you like it? Here we are crazy about it.'],
      ['Em dia de jogo, a cidade inteira só quer saber: {sport}, e mais nada.', 'On match day, the whole town cares about one thing: {sport}, nothing else.'],
      ['A família toda adora {sport}. A minha avó, mais do que tudo, grita.', 'The whole family loves {sport}. My grandmother, above all, shouts.'],
    ],
    wonder: [
      ['Se tiver tempo, vá ver {wonder}. Vale muito a pena.', "If you have time, go and see {wonder}. It's well worth it."],
      ['Já viu {wonder}? Não há nada igual no mundo.', "Have you seen {wonder}? There's nothing like it in the world."],
      ['Todos deviam ver {wonder} uma vez na vida.', 'Everybody should see {wonder} once in their life.'],
      ['Quando eu era jovem, fui ver {wonder}. Ainda penso nisso.', 'When I was young, I went to see {wonder}. I still think about it.'],
    ],
    pride: [
      ['Sabe qual é o nosso orgulho? {pride}.', 'You know what our pride is? {pride}.'],
      ['Não vá embora sem conhecer {pride}. É o que nós somos.', "Don't leave without getting to know {pride}. It's who we are."],
      ['Do que mais nos orgulhamos? {pride}.', 'What are we proudest of? {pride}.'],
      ['Pergunte a qualquer pessoa sobre {pride} e prepare-se para horas de conversa.', 'Ask anyone about {pride} and get ready for hours of talk.'],
    ],
    proverb: [
      ['Como se diz por aqui: «{proverb}»', 'As we say round here: “{proverb}”'],
      ['A minha avó dizia sempre: «{proverb}»', 'My grandmother always said: “{proverb}”'],
      ['Há um ditado aqui: «{proverb}»', 'There is a saying here: “{proverb}”'],
      ['Conhece o ditado? «{proverb}»', 'Do you know the saying? “{proverb}”'],
    ],
    chat: [
      ['De onde vem? Não é daqui, certo?', "Where are you from? You're not from here, right?"],
      ['Com calma, olhe à sua volta. Há muito para ver.', "Take it easy, look around. There's a lot to see."],
      ['Se se perder, pergunte. Aqui as pessoas são simpáticas.', 'If you get lost, ask. People here are friendly.'],
      ['Qual foi o lugar mais bonito que viu até agora?', "What's the most beautiful place you've seen so far?"],
      ['Sempre quis viajar. Um dia destes ainda vou.', 'I always wanted to travel. One of these days I will.'],
      ['Traz mapa? Quem viaja deve andar sempre com um mapa.', 'Got a map? Anyone who travels should always carry a map.'],
      ['Parece que andou muito para chegar aqui.', 'Looks like you walked a long way to get here.'],
      ['Já tomou um cafezinho? Aqui café é coisa séria.', 'Have you had a little coffee yet? Coffee is serious business here.'],
    ],
    childGreet: [
      ['Olá!', 'Hi!'],
      ['Olá! Como se chama?', "Hi! What's your name?"],
      ['Olá! Que pessoa tão alta!', 'Hi! What a tall person!'],
      ['Olá, olá, olá!', 'Hi, hi, hi!'],
    ],
    childChat: [
      ['Eu corro muito rápido! Quer ver? Depois mostro.', 'I run really fast! Want to see? I’ll show you later.'],
      ['É turista? O meu amigo diz que os turistas são ricos.', 'Are you a tourist? My friend says tourists are rich.'],
      ['Ontem perdi um dente! Olhe! Ah, não dá para ver.', "I lost a tooth yesterday! Look! Oh, you can't see it."],
      ['A minha mãe diz para não falar com estranhos. Mas tem cara de boa pessoa.', 'My mum says not to talk to strangers. But you look like a good person.'],
      ['Tem um cão? Eu quero tanto um cão. Ou um gato. Ou um papagaio.', 'Do you have a dog? I really want a dog. Or a cat. Or a parrot.'],
      ['Quando eu crescer vou pilotar um avião à volta do mundo!', "When I grow up I'm going to fly a plane round the world!"],
      ['Sabe alguma brincadeira? Eu sei muitas!', 'Do you know any games? I know loads.'],
      ['Hoje comi três doces! Não conte à minha mãe.', "I had three sweets today! Don't tell my mum."],
    ],
    childBye: [
      ['Tchau, tchau!', 'Bye bye!'],
      ['Adeus! Volte para brincar!', 'Bye! Come back and play!'],
      ['Tenho de ir, a minha mãe chamou!', 'I have to go, my mum called me!'],
      ['Até logo! Até amanhã! Até sempre!', 'See you later! See you tomorrow! See you always!'],
    ],
    grumpyGreet: [
      ['Hum. Que é que quer?', 'Hm. What do you want?'],
      ['Sim? Diga lá.', 'Yes? Out with it.'],
      ['Ai. Mais turistas.', 'Oh dear. More tourists.'],
      ['Hmpf. Bom dia, pronto.', 'Hmph. Good day, there.'],
    ],
    grumpyChat: [
      ['Isto era muito melhor antes de vir toda a gente para cá.', 'This was much better before everyone started coming here.'],
      ['Está tudo pelo dobro do preço. Um pão, o dobro!', 'Everything costs double. A loaf of bread, double!'],
      ['Não pare no meio do caminho, por favor. Há quem trabalhe.', "Don't stop in the middle of the way, please. Some people work."],
      ['A juventude de hoje só quer saber do telefone.', 'Young people today only care about their phones.'],
      ['Não sei o que vêm cá ver. Não há nada.', "I don't know what people come here to see. There's nothing."],
      ['No meu tempo é que era. Agora é só barulho.', 'Back in my day, that was the life. Now it is just noise.'],
    ],
    grumpyBye: [
      ['Pronto. Vá lá à sua vida.', 'Right. Off you go about your business.'],
      ['Bem, não quero atrasar ninguém.', "Well, I don't want to hold anyone up."],
      ['Hum. Adeus.', 'Hm. Goodbye.'],
      ['Vá com cuidado. E feche o portão.', 'Mind how you go. And shut the gate.'],
    ],
    elderChat: [
      ['Quando eu era jovem, isto aqui era tudo campo.', 'When I was young, this was all fields.'],
      ['Vivo aqui a vida toda. Oitenta anos! Acredita?', "I've lived here all my life. Eighty years! Can you believe it?"],
      ['No meu tempo íamos a pé para toda a parte. Ainda bem que também anda!', 'In my day we went everywhere on foot. Good that you walk too!'],
      ['Os meus netos vivem lá fora. Ligam todos os domingos.', 'My grandchildren live abroad. They call every Sunday.'],
      ['Tudo muda tão depressa. Mas as ruas velhas continuam iguais.', 'Everything changes so fast. But the old streets stay the same.'],
      ['Antigamente, ao domingo, havia baile na praça. Que tempos!', 'In the old days there was a dance in the square on Sundays. What times!'],
    ],
    chattyChat: [
      ['Adoro conhecer gente que viaja! Quero saber tudo. Não, espere, conto eu primeiro.', 'I love meeting people who travel! I want to know everything. No, wait, I’ll go first.'],
      ['O meu primo foi viajar uma vez. Voltou com barba e uma esposa!', 'My cousin went travelling once. He came back with a beard and a wife!'],
      ['Os meus amigos dizem que eu falo pelos cotovelos. Não estão errados!', "My friends say I talk through my elbows. They're not wrong!"],
      ['Já comeu? Tem cara de fome. Para mim, todos têm cara de fome.', 'Have you eaten? You look hungry. Everyone looks hungry to me.'],
      ['Vou contar um segredo: a melhor vista é do morro atrás da igreja.', 'I’ll tell you a secret: the best view is from the hill behind the church.'],
      ['E a minha tia, conhece a minha tia? Não? Então escute só...', 'And my aunt, do you know my aunt? No? Then just listen...'],
    ],
    bye: [
      ['Até logo! Boa viagem.', 'See you! Have a good trip.'],
      ['Cuide-se! Aproveite o resto da viagem.', 'Take care! Enjoy the rest of your trip.'],
      ['Vá com Deus!', 'Go with God!'],
      ['Tchau! Volte sempre.', 'Bye! Come back any time.'],
      ['Foi um prazer conversar. Boa sorte!', 'It was a pleasure to talk. Good luck!'],
      ['Vá lá, que há muito para ver!', "Off you go, there's lots to see!"],
    ],
  },
  countries: {
    // Every fact carries its definite article ("a feijoada", "o futebol") and
    // stands where no preposition would contract with it: after a verb, after
    // a colon or a question, or opening a sentence.
    BRA: {
      dish: ['a feijoada', 'feijoada'],
      drink: ['a caipirinha', 'caipirinha'],
      festival: ['o Carnaval', 'Carnival'],
      sport: ['o futebol', 'football'],
      wonder: ['as Cataratas do Iguaçu', 'the Iguaçu Falls'],
      pride: ['o samba', 'samba'],
      proverb: ['Quem não tem cão caça com gato', 'Whoever has no dog hunts with a cat'],
    },
    PRT: {
      dish: ['o bacalhau', 'salt cod'],
      drink: ['o vinho do Porto', 'port wine'],
      festival: ['os Santos Populares', 'the Popular Saints festivals'],
      sport: ['o futebol', 'football'],
      wonder: ['o vale do Douro', 'the Douro valley'],
      pride: ['o fado', 'fado'],
      proverb: ['Devagar se vai ao longe', 'Slowly one goes far'],
    },
    AGO: {
      dish: ['a muamba de galinha', 'chicken muamba'],
      festival: ['o Carnaval de Luanda', 'the Luanda Carnival'],
      sport: ['o basquetebol', 'basketball'],
      wonder: ['as quedas de Kalandula', 'the Kalandula Falls'],
      pride: ['o semba', 'semba'],
      proverb: ['Quem espera sempre alcança', 'Whoever waits always gets there'],
    },
    MOZ: {
      dish: ['a matapa', 'matapa'],
      sport: ['o futebol', 'football'],
      wonder: ['o arquipélago de Bazaruto', 'the Bazaruto archipelago'],
      pride: ['a marrabenta', 'marrabenta music'],
      proverb: ['Mais vale um pássaro na mão do que dois a voar', 'A bird in the hand is worth more than two flying'],
    },
    GNB: {
      drink: ['o sumo de caju', 'cashew juice'],
      festival: ['o Carnaval de Bissau', 'the Bissau Carnival'],
      sport: ['o futebol', 'football'],
      wonder: ['o arquipélago dos Bijagós', 'the Bijagós archipelago'],
      proverb: ['Grão a grão enche a galinha o papo', 'Grain by grain the hen fills her crop'],
    },
    CPV: {
      dish: ['a cachupa', 'cachupa'],
      drink: ['o grogue', 'grogue, the sugarcane spirit'],
      festival: ['o Carnaval do Mindelo', 'the Mindelo Carnival'],
      sport: ['o futebol', 'football'],
      wonder: ['o vulcão do Fogo', 'the Fogo volcano'],
      pride: ['a morna', 'morna music'],
      proverb: ['Quem não arrisca não petisca', 'Who risks nothing gets no treat'],
    },
    STP: {
      dish: ['o calulu', 'calulu'],
      drink: ['o vinho de palma', 'palm wine'],
      sport: ['o futebol', 'football'],
      wonder: ['o Pico Cão Grande', 'the Pico Cão Grande'],
      pride: ['o nosso cacau', 'our cocoa'],
      proverb: ['Mais vale tarde do que nunca', 'Better late than never'],
    },
    TLS: {
      drink: ['o café de Timor', 'Timorese coffee'],
      sport: ['o futebol', 'football'],
      wonder: ['o monte Ramelau', 'Mount Ramelau'],
      pride: ['o tais', 'tais weaving'],
      proverb: ['Quem tem boca vai a Roma', 'Whoever has a mouth gets to Rome'],
    },
  },
};

export default PT;
