import type { Language } from '../phrases.ts';

const RO: Language = {
  locale: 'ro',
  name: 'Romanian',
  join: ' ',
  compass: ['spre nord', 'spre nord-est', 'spre est', 'spre sud-est', 'spre sud', 'spre sud-vest', 'spre vest', 'spre nord-vest'],
  lines: {
    morning: [
      ['Bună dimineața!', 'Good morning!'],
      ['Bună dimineața! Ce dimineață frumoasă, nu?', 'Good morning! What a lovely morning, eh?'],
      ['Neața!', 'Morning!'],
      ['O, bună dimineața! Să aveți o zi frumoasă.', 'Oh, good morning! Have a lovely day.'],
    ],
    afternoon: [
      ['Bună ziua!', 'Good afternoon!'],
      ['Bună!', 'Hi!'],
      ['Ziua bună!', 'Good day!'],
      ['O, bună ziua! Frumoasă după-amiază, nu?', 'Oh, hello! Lovely afternoon, isn\'t it?'],
    ],
    evening: [
      ['Bună seara!', 'Good evening!'],
      ['Bună seara! Frumoasă seară de plimbare.', 'Good evening! A lovely evening for a stroll.'],
      ['Seara bună!', 'Evening!'],
      ['Bună seara! A trecut ziua cât ai clipi.', 'Good evening! The day went by in the blink of an eye.'],
    ],
    night: [
      ['Bună seara! E cam târziu, nu?', "Good evening! It's rather late, isn't it?"],
      ['Doamne, ce m-ați speriat! Bună seara.', 'Goodness, you gave me a fright! Good evening.'],
      ['Plimbare de noapte? Bună seara!', 'A night walk? Good evening!'],
      ['Bună seara! Sau e deja bună dimineața?', 'Good evening! Or is it good morning already?'],
    ],
    again: [
      ['O, iar dumneavoastră! Bună!', 'Oh, you again! Hello!'],
      ['Ne-am mai văzut! Tot explorați?', 'We have met before! Still exploring?'],
      ['Bună din nou!', 'Hello again!'],
      ['A, dumneavoastră! V-ați găsit drumul?', 'Ah, you! Did you find your way?'],
      ['Ia te uită, ne revedem!', 'Well look at that, we meet again!'],
    ],
    welcome: [
      ['Bine ați venit în {town}!', 'Welcome to {town}!'],
      ['Aici e {town}. Sunteți în vizită?', 'This is {town}. Are you visiting?'],
      ['Prima dată în {town}?', 'First time in {town}?'],
      ['Ați nimerit o zi bună să vedeți {town}.', 'You have picked a good day to see {town}.'],
      ['Bine ați venit! {town} vă primește cu drag.', '{town} is glad to have you. Welcome!'],
      ['Ce vă aduce în {town}?', 'What brings you to {town}?'],
    ],
    capitalHere: [
      ['{town} este capitala țării noastre.', '{town} is the capital of our country.'],
      ['Aici e capitala, să știți. Totul se întâmplă aici.', 'This is the capital, you know. Everything happens here.'],
      ['Aici stă guvernul. Numai oameni importanți la costum.', 'The government sits here. All important people in suits.'],
      ['Capitala nu doarme niciodată, iar {town} e dovada.', 'The capital never sleeps, and {town} is the proof.'],
    ],
    capitalThere: [
      ['Capitala noastră este {capital}. Merită vizitată.', "Our capital is {capital}. It's worth a visit."],
      ['Ați fost deja la {capital}? E capitala noastră.', 'Have you been to {capital} yet? It is our capital.'],
      ['Cei din {capital} cred că ei conduc țara. Și chiar așa e.', 'The people in {capital} think they run the country. And they do.'],
      ['{capital} e mai mare, dar eu tot aici aș sta.', "{capital} is bigger, but I'd still rather live here."],
    ],
    big: [
      ['E un oraș mare. Aici te pierzi ușor!', "It's a big city. You get lost easily here!"],
      ['Câtă lume! Poți trăi aici o viață și tot nu cunoști toate străzile.', 'So many people! You can live here a lifetime and still not know every street.'],
      ['Traficul ăsta, ce să zic. Dar mereu se întâmplă ceva.', "This traffic, what can I say. But there's always something going on."],
      ['Un oraș mare nu se oprește niciodată. Și asta îmi place.', 'A big city never stops. And I like that.'],
    ],
    middling: [
      ['Nici mare, nici mic. Exact cât trebuie.', 'Not big, not small. Just right.'],
      ['Destul de mare să aibă de toate, destul de mic să-l străbați pe jos.', 'Big enough to have everything, small enough to cross on foot.'],
      ['În {town} vedeți tot într-o zi-două.', "In {town} you'll see everything in a day or two."],
      ['Toți se plâng că e prea liniște, dar nimeni nu pleacă.', "Everybody complains it's too quiet, but nobody leaves."],
    ],
    small: [
      ['E un loc mic. Aici toată lumea se cunoaște.', "It's a small place. Everybody knows everybody here."],
      ['Strănuți la un capăt și la celălalt îți zice cineva „Sănătate!”.', 'Sneeze at one end and somebody at the other says "Bless you!".'],
      ['În {town} nu se întâmplă mare lucru, și ne place așa.', 'Not much happens in {town}, and we like it that way.'],
      ['Sunteți cea mai mare noutate de săptămâna asta!', "You're the biggest news of the week!"],
    ],
    coast: [
      ['Aici trăim lângă apă. Peștele e foarte bun.', 'We live by the water here. The fish is very good.'],
      ['Duceți-vă să vedeți apa. În fiecare zi arată altfel.', 'Go and see the water. It looks different every day.'],
      ['Simțiți? E aerul de la apă. Nu te saturi niciodată de el.', "Smell that? That's the air off the water. You never tire of it."],
      ['Bărcile ies dis-de-dimineață și se întorc cu cel mai bun pește.', 'The boats go out at the crack of dawn and come back with the best fish.'],
    ],
    inland: [
      ['Suntem departe de mare, dar locurile sunt minunate.', 'We are far from the sea, but the countryside is wonderful.'],
      ['Plajă nu avem, dar uitați-vă la câmpurile astea.', "We have no beach, but look at these fields."],
      ['Marea? E departe de tot, o vedem rar.', "The sea? It's a long way off, we rarely see it."],
      ['Aici pământul e totul. Pământ bun, oameni buni.', 'Here the land is everything. Good soil, good people.'],
    ],
    high: [
      ['Suntem sus aici. Mergeți încet, aerul e mai rar.', "We're high up here. Go slowly, the air is thinner."],
      ['La munte, cel mai frumos lucru e priveliștea.', 'In the mountains, the best thing is the view.'],
      ['Aici nimic nu e drept. Faci picioare de fier.', 'Nothing is flat here. You get legs of iron.'],
      ['Trageți aer în piept! Cu muntele trebuie să te obișnuiești.', 'Take a deep breath! The mountains take getting used to.'],
    ],
    snowy: [
      ['Zăpadă nouă luni pe an. Celelalte trei ne plângem de noroi.', 'Snow nine months a year. The other three, we complain about the mud.'],
      ['Totul e alb aici. V-ar trebui niște bocanci mai buni.', 'Everything is white here. You could use better boots.'],
      ['Frigul nu ne deranjează. Ține turiștii departe. Pe dumneavoastră nu, bineînțeles!', "The cold doesn't bother us. It keeps tourists away. Not you, of course!"],
      ['Când e zăpadă proaspătă, e atâta liniște că-ți auzi gândurile.', "When the snow is fresh, it's so quiet you can hear your thoughts."],
    ],
    forest: [
      ['Pădurile țin cât vezi cu ochii. Nu ieșiți de pe potecă!', 'The woods go on as far as the eye can see. Stay on the path!'],
      ['Faceți o plimbare prin pădure. Limpezește mintea.', 'Take a walk in the woods. It clears the mind.'],
      ['Toamna mergem la ciuperci și la mure.', 'In autumn we go picking mushrooms and blackberries.'],
      ['Copaci, copaci și iar copaci. N-aș sta nicăieri altundeva.', "Trees, trees and more trees. I wouldn't live anywhere else."],
    ],
    desert: [
      ['Aici e numai nisip cât vezi cu ochii.', "It's nothing but sand as far as the eye can see."],
      ['Beți multă apă. Deșertul nu iartă.', 'Drink plenty of water. The desert does not forgive.'],
      ['Nopțile în deșert sunt reci. Nimeni nu crede.', 'Desert nights are cold. Nobody believes it.'],
      ['Așteptați să se întunece. Stelele sunt aici cu milioanele.', 'Wait until it gets dark. The stars here come by the million.'],
    ],
    plains: [
      ['E câmpie cât vezi cu ochii. Vezi furtuna venind de departe.', "It's plain as far as the eye can see. You see a storm coming from far off."],
      ['Cer mare și nimic să oprească vântul.', 'A big sky and nothing to stop the wind.'],
      ['Pășuni bune peste tot. Atenție la turme!', 'Good pasture everywhere. Watch out for the herds!'],
      ['Iarba ține până la orizont. Ca o mare verde.', 'The grass runs to the horizon. Like a green sea.'],
    ],
    tropical: [
      ['Aici crește orice. Bagi un băț în pământ și iese copac.', 'Anything grows here. Stick a twig in the ground and out comes a tree.'],
      ['Când plouă aici, plouă de-adevăratelea. Apoi se oprește brusc.', 'When it rains here, it really rains. Then it stops, just like that.'],
      ['Gustați fructele din piață. Așa ceva n-ați mai mâncat.', "Taste the fruit from the market. You've never had anything like it."],
      ['E verde tot anul. Iarnă? Care iarnă?', "It's green all year. Winter? What winter?"],
    ],
    landmark: [
      ['Nu ratați {landmark}! E la vreo {km} km {dir}.', "Don't miss {landmark}! It's some {km} km {dir}."],
      ['Ați văzut {landmark}? E la {km} km {dir}, merită fiecare pas.', "Have you seen {landmark}? It's {km} km {dir}, worth every step."],
      ['Toată lumea merge la {landmark}. E cam la {km} km {dir}.', "Everybody goes to {landmark}. It's about {km} km {dir}."],
      ['Dacă vă plac lucrurile vechi, {landmark} e la {km} km {dir}.', 'If you like old things, {landmark} is {km} km {dir}.'],
    ],
    landmarkNear: [
      ['{landmark} e foarte aproape. Nu aveți cum să greșiți!', "{landmark} is very close. You can't go wrong!"],
      ['Ați fost la {landmark}? E chiar după colț.', 'Have you been to {landmark}? It is just round the corner.'],
      ['Vedem {landmark} în fiecare zi și tot ne taie respirația.', 'We see {landmark} every day and it still takes our breath away.'],
      ['Mergeți să vedeți {landmark}, e chiar aici. Dimineața, înainte de îmbulzeală.', 'Go and see {landmark}, it is right here. In the morning, before the crush.'],
    ],
    plane: [
      ['E un avion mic pe un câmp {dir}, dacă știți să zburați!', "There's a little plane in a field {dir}, if you can fly!"],
      ['Cineva a lăsat un avion pe câmp {dir}. Un zbor?', 'Somebody left a plane in a field {dir}. Fancy a flight?'],
      ['Știți să pilotați? Vă așteaptă un avion {dir}.', 'Can you fly? A plane is waiting for you {dir}.'],
      ['Vreți să vedeți totul de sus? E un avion {dir}.', "Want to see it all from above? There's a plane {dir}."],
    ],
    balloon: [
      ['E un balon cu aer cald pe un câmp {dir}! Închipuiți-vă priveliștea.', "There's a hot-air balloon in a field {dir}! Imagine the view."],
      ['Ați zburat vreodată cu balonul? E unul {dir}.', "Ever flown in a balloon? There's one {dir}."],
      ['De pe câmpul {dir} se ridică un balon. E magic!', 'A balloon rises from the field {dir}. It is magical!'],
      ['Tot vreau să încerc balonul {dir}, dar mi-e prea frică!', "I keep wanting to try the balloon {dir}, but I'm too scared!"],
    ],
    boat: [
      ['E o barcă la apă {dir}, dacă vreți să ieșiți în larg.', "There's a boat on the water {dir}, if you want to go out."],
      ['Vă place apa? E o barcă {dir}. Doar s-o aduceți înapoi!', "Like the water? There's a boat {dir}. Just bring it back!"],
      ['O barcă e legată {dir}. De aici puteți ajunge oriunde.', 'A boat is tied up {dir}. From here you can get anywhere.'],
      ['Luați barca {dir} și vedeți țărmul dinspre apă.', 'Take the boat {dir} and see the shore from the water.'],
    ],
    hot: [
      ['E cald azi! Căutați puțină umbră.', "It's hot today! Find a bit of shade."],
      ['Uf, ce arșiță! Beți niște apă.', 'Phew, what a scorcher! Drink some water.'],
      ['E prea cald să faci ceva. Doar stai la umbră.', 'Too hot to do anything. You just sit in the shade.'],
      ['Pe căldura asta nici câinii nu ies din casă.', "In this heat even the dogs don't leave the house."],
      ['Cald, nu? Și pentru noi azi e o zi răcoroasă!', 'Hot, eh? And for us today is a cool day!'],
    ],
    cold: [
      ['Brr, e frig azi! Îmbrăcați-vă bine.', "Brr, it's cold today! Wrap up well."],
      ['Ger mare! Unde vă sunt mănușile?', 'A hard frost! Where are your gloves?'],
      ['E așa de frig că nu-mi mai simt nasul.', "It's so cold I can't feel my nose any more."],
      ['Frig? Stați să vedeți când bate vântul.', 'Cold? Wait till you see the wind blow.'],
      ['Beți ceva cald. Ajută.', 'Have something hot to drink. It helps.'],
    ],
    mild: [
      ['Ce vreme frumoasă e azi.', 'What lovely weather today.'],
      ['Nici cald, nici frig. Zi perfectă, nu?', "Not hot, not cold. A perfect day, isn't it?"],
      ['Într-o zi ca asta, nu-ți vine să stai în casă.', "On a day like this, you don't feel like staying indoors."],
      ['Ce vreme bună! Să țină.', 'What good weather! May it last.'],
      ['Pentru zile ca asta trăim aici.', 'Days like this are why we live here.'],
    ],
    late: [
      ['E târziu. Noaptea străzile sunt liniștite.', "It's late. The streets are quiet at night."],
      ['La ora asta ies numai pisicile. Și noi!', 'At this hour only the cats are out. And us!'],
      ['Ar trebui să fiu în pat. Dar dumneavoastră de ce nu dormiți?', 'I should be in bed. But why are you not asleep?'],
      ['Uitați-vă la stele! De aici se văd cel mai bine.', 'Look at the stars! You see them best from here.'],
    ],
    early: [
      ['Ce devreme v-ați trezit! E cea mai frumoasă parte a zilei.', "You're up early! It's the best part of the day."],
      ['Brutăria abia s-a deschis. Luați-vă după miros!', 'The bakery has just opened. Follow the smell!'],
      ['Cine se scoală de dimineață departe ajunge, nu?', 'Whoever gets up early goes far, right?'],
      ['Îmi plac diminețile aici, înainte să înceapă gălăgia.', 'I love the mornings here, before the noise starts.'],
    ],
    country: [
      ['{country} e o țară frumoasă. Bucurați-vă de ea!', '{country} is a beautiful country. Enjoy it!'],
      ['Cum vi se pare {country} până acum?', 'How do you find {country} so far?'],
      ['{country}: mică pe hartă, mare la suflet.', '{country}: small on the map, big at heart.'],
      ['Dacă puteți, vedeți cât mai mult din {country}. Fiecare colț e altfel.', 'If you can, see as much of {country} as you can. Every corner is different.'],
    ],
    dish: [
      ['Trebuie să gustați {dish} cât sunteți aici.', "You have to try {dish} while you're here."],
      ['Ați mâncat deja {dish}? Nu? Musai!', "Have you had {dish} yet? No? You must!"],
      ['Nimeni nu face {dish} ca mama.', 'Nobody makes {dish} like my mother.'],
      ['Dacă vă e foame, luați {dish}. Nu veți regreta.', "If you're hungry, get {dish}. You won't regret it."],
    ],
    drink: [
      ['Beți {drink} înainte să plecați. Asta se bea pe la noi.', "Have {drink} before you leave. It's what we drink round here."],
      ['Nimic nu se compară cu {drink} la sfârșitul zilei.', 'Nothing compares with {drink} at the end of the day.'],
      ['Nu ați trăit cu adevărat până nu ați gustat {drink}.', "You haven't really lived until you've tasted {drink}."],
      ['Cereți {drink} și localnicii vă vor îndrăgi pe loc.', 'Ask for {drink} and the locals will love you on the spot.'],
    ],
    festival: [
      ['Ar trebui să prindeți și {festival}. E minunat!', 'You should catch {festival} too. It is wonderful!'],
      ['Cel mai frumos moment al anului? {festival}. Sărbătorește toată lumea.', 'The best moment of the year? {festival}. Everybody celebrates.'],
      ['Abia aștept {festival} în fiecare an.', 'I can hardly wait for {festival} every year.'],
      ['Merită să trăiți {festival} măcar o dată.', "It's worth living through {festival} at least once."],
    ],
    sport: [
      ['Aici toată lumea iubește {sport}.', 'Here everybody loves {sport}.'],
      ['În zi de meci, tot orașul trăiește pentru un singur lucru: {sport}.', 'On match day the whole town lives for one thing: {sport}.'],
      ['Toată familia mea iubește {sport}. Bunica doar strigă la televizor.', 'My whole family loves {sport}. Grandma just shouts at the TV.'],
      ['La noi, nimic nu bate {sport}.', 'Round here, nothing beats {sport}.'],
    ],
    wonder: [
      ['Dacă aveți timp, mergeți să vedeți {wonder}. E de neuitat.', 'If you have time, go and see {wonder}. It is unforgettable.'],
      ['Ați văzut {wonder}? Nu mai e așa ceva nicăieri.', "Have you seen {wonder}? There's nothing like it anywhere."],
      ['Oricine ar trebui să vadă {wonder} măcar o dată în viață.', 'Everyone should see {wonder} at least once in their life.'],
      ['Am văzut {wonder} în copilărie. Încă visez la asta.', 'I saw {wonder} as a child. I still dream about it.'],
    ],
    pride: [
      ['Ne mândrim cu {pride}.', 'We take pride in {pride}.'],
      ['Nu plecați fără să aflați despre {pride}. Asta suntem noi.', "Don't leave without learning about {pride}. That's who we are."],
      ['Știți ce ne umple inima de mândrie? {pride}.', 'Do you know what fills our hearts with pride? {pride}.'],
      ['Întrebați pe oricine de aici despre {pride} și vă ține de vorbă ore întregi.', "Ask anyone here about {pride} and they'll talk your ear off for hours."],
    ],
    proverb: [
      ['Cum se zice la noi: „{proverb}”', 'As we say here: “{proverb}”'],
      ['Bunica mereu zicea: „{proverb}”', 'My grandmother always said: “{proverb}”'],
      ['Avem o vorbă: „{proverb}”', 'We have a saying: “{proverb}”'],
      ['Știți zicala? „{proverb}”', 'Do you know the saying? “{proverb}”'],
    ],
    chat: [
      ['De unde sunteți? Nu sunteți de pe aici.', "Where are you from? You're not from round here."],
      ['Nu vă grăbiți, uitați-vă în jur. Sunt multe de văzut.', "Take your time and look around. There's a lot to see."],
      ['Călătoriți pe cont propriu? Curaj!', 'Travelling on your own? That takes courage!'],
      ['Se vede că ați bătut drum lung.', 'You can tell you have come a long way.'],
      ['Dacă vă rătăciți, întrebați. Oamenii de aici sunt primitori.', 'If you get lost, ask. People here are welcoming.'],
      ['Care a fost cel mai frumos loc de până acum?', 'What has been the most beautiful place so far?'],
      ['Mereu mi-am dorit să călătoresc. Poate într-o zi.', 'I have always wanted to travel. Maybe one day.'],
    ],
    childGreet: [
      ['Bună!', 'Hi!'],
      ['Bună! Tu cine ești?', 'Hi! Who are you?'],
      ['Salut! Câți ani ai?', 'Hi! How old are you?'],
      ['Bună, bună!', 'Hi, hi!'],
    ],
    childChat: [
      ['Eu alerg foarte repede! Vrei să vezi? Poate mai târziu.', 'I can run really fast! Want to see? Maybe later.'],
      ['Prietenul meu zice că turiștii sunt bogați. E adevărat?', 'My friend says tourists are rich. Is that true?'],
      ['Ieri mi-a căzut un dinte! Uite! A, nu se vede.', "A tooth fell out yesterday! Look! Oh, you can't see it."],
      ['Mama zice să nu vorbesc cu străinii. Dar tu pari de treabă.', 'Mum says not to talk to strangers. But you seem all right.'],
      ['Ai un câine? Eu vreau un câine!', 'Do you have a dog? I want a dog!'],
      ['Când o să fiu mare, o să zbor cu avionul în jurul lumii!', "When I'm big, I'm going to fly a plane round the world!"],
      ['Știi vreun joc? Eu știu o grămadă!', 'Do you know any games? I know loads!'],
    ],
    childBye: [
      ['Pa pa!', 'Bye bye!'],
      ['Pa! Mai vino să ne jucăm!', 'Bye! Come back and play!'],
      ['Trebuie să plec, mă strigă mama!', 'I have to go, mum is calling me!'],
      ['Hai pa!', 'Okay, bye!'],
    ],
    grumpyGreet: [
      ['Hm. Ce vreți?', 'Hm. What do you want?'],
      ['Da? Ce e?', 'Yes? What is it?'],
      ['Ah. Iar turiști.', 'Oh. Tourists again.'],
      ['Hm. Bună ziua, fie.', 'Hm. Good day, if you like.'],
    ],
    grumpyChat: [
      ['Era mai bine aici înainte să vină toată lumea.', 'It was better here before everybody started coming.'],
      ['Toate costă dublu față de cum era.', 'Everything costs double what it used to.'],
      ['Nu blocați trotuarul, vă rog. Aici trăiesc oameni.', "Don't block the pavement, please. People live here."],
      ['Tinerii din ziua de azi, numai cu telefonul în mână.', 'Young people these days, always a phone in their hand.'],
      ['Nu știu de ce vine lumea aici. N-ai ce vedea.', "I don't know why people come here. There's nothing to see."],
    ],
    grumpyBye: [
      ['Bine. Mergeți, atunci.', 'Right. Off you go, then.'],
      ['Nu vă mai rețin.', "I won't keep you any longer."],
      ['Hm. La revedere.', 'Hm. Goodbye.'],
      ['Aveți grijă pe unde călcați. Și închideți poarta.', 'Watch where you step. And shut the gate.'],
    ],
    elderChat: [
      ['Pe vremea mea, aici erau numai câmpuri.', 'In my day, this was all fields.'],
      ['Trăiesc aici de-o viață. Optzeci de ani! Vă vine să credeți?', "I've lived here all my life. Eighty years! Can you believe it?"],
      ['Pe vremuri mergeam peste tot pe jos. Și dumneavoastră mergeți pe jos. Bravo!', 'In the old days we walked everywhere. You walk too. Well done!'],
      ['Nepoții mei trăiesc acum în străinătate. Sună în fiecare duminică.', 'My grandchildren live abroad now. They call every Sunday.'],
      ['Totul se schimbă așa de repede. Doar străduțele vechi rămân la fel.', 'Everything changes so fast. Only the old lanes stay the same.'],
    ],
    chattyChat: [
      ['Ah, ce-mi plac călătorii! Povestiți-mi tot. Nu, stați, întâi eu!', 'Oh, how I love travellers! Tell me everything. No, wait, me first!'],
      ['Vărul meu a plecat odată în lume. S-a întors cu barbă și cu nevastă!', 'My cousin went off into the world once. He came back with a beard and a wife!'],
      ['Prietenii zic că pot vorbi o zi întreagă. Și au dreptate!', "My friends say I can talk a whole day. And they're right!"],
      ['Ați mâncat ceva? Toată lumea mi se pare flămândă!', 'Have you eaten anything? Everybody looks hungry to me!'],
      ['Vă spun un secret: cea mai frumoasă priveliște e de pe dealul din spatele bisericii.', "I'll tell you a secret: the best view is from the hill behind the church."],
    ],
    bye: [
      ['La revedere! Drum bun.', 'Goodbye! Safe journey.'],
      ['Aveți grijă de dumneavoastră! Călătorie plăcută.', 'Look after yourself! Enjoy the trip.'],
      ['Drum bun și Doamne-ajută!', 'Safe travels, and God help you on your way!'],
      ['Pa! Să mai treceți pe la noi.', 'Bye! Do come and see us again.'],
      ['Mi-a făcut plăcere. Numai bine!', 'It was a pleasure. All the best!'],
      ['Hai, drum bun! Mai sunt atâtea de văzut.', "Go on, safe travels! There's so much more to see."],
    ],
  },
  countries: {
    // Every fact a noun with its definite article, in the one form Romanian gives it as subject and object: the templates never put it after a preposition that drops the article.
    ROU: {
      dish: ['sarmalele', 'sarmale, the cabbage rolls'],
      drink: ['țuica', 'țuică, the plum brandy'],
      festival: ['Mărțișorul', 'Mărțișor, the first of March'],
      sport: ['fotbalul', 'football'],
      wonder: ['Delta Dunării', 'the Danube Delta'],
      pride: ['mănăstirile pictate din Bucovina', 'the painted monasteries of Bucovina'],
      proverb: ['Graba strică treaba', 'Haste spoils the work'],
    },
    MDA: {
      dish: ['plăcintele', 'plăcinte, the stuffed pies'],
      drink: ['vinul moldovenesc', 'Moldovan wine'],
      festival: ['Ziua Națională a Vinului', 'National Wine Day'],
      sport: ['trânta', 'trântă, our folk wrestling'],
      wonder: ['Orheiul Vechi', 'Old Orhei'],
      pride: ['beciurile de la Mileștii Mici', 'the wine cellars of Mileștii Mici'],
      proverb: ['Omul sfințește locul', 'It is the person who hallows the place'],
    },
  },
};

export default RO;
