import type { Language } from '../phrases.ts';

/**
 * Russian: spoken in Russia, and the language a stranger is greeted in across
 * Belarus, Kazakhstan and Kyrgyzstan. A stranger is «вы», and a name stands
 * in the nominative — as a subject, after a dash or a colon, or in apposition
 * to «город», which takes the case instead.
 */
const RU: Language = {
  locale: 'ru',
  name: 'Russian',
  join: ' ',
  compass: [
    'к северу отсюда', 'к северо-востоку отсюда', 'к востоку отсюда', 'к юго-востоку отсюда',
    'к югу отсюда', 'к юго-западу отсюда', 'к западу отсюда', 'к северо-западу отсюда',
  ],
  lines: {
    morning: [
      ['Доброе утро!', 'Good morning!'],
      ['Утро доброе!', 'Morning!'],
      ['Доброе утро! Хорошо денёк начинается, правда?', "Good morning! Nice start to the day, isn't it?"],
      ['Ой, здравствуйте! С добрым утром.', 'Oh, hello! Good morning to you.'],
    ],
    afternoon: [
      ['Добрый день!', 'Good afternoon!'],
      ['Здравствуйте!', 'Hello!'],
      ['Добрый день! Хороший сегодня денёк.', "Good afternoon! It's a nice day today."],
      ['О, привет! То есть здравствуйте.', 'Oh, hi! I mean, good day to you.'],
    ],
    evening: [
      ['Добрый вечер!', 'Good evening!'],
      ['Вечер добрый!', 'Evening!'],
      ['Здравствуйте! Хороший вечер для прогулки.', 'Hello! A nice evening for a walk.'],
      ['О, добрый вечер!', 'Oh, good evening!'],
    ],
    night: [
      ['Здравствуйте! Поздно уже, правда?', "Hello! It's late, isn't it?"],
      ['Ой! Вы меня напугали. Здравствуйте!', 'Oh! You startled me. Hello!'],
      ['Добрый вечер! Не спится?', "Good evening! Can't sleep?"],
      ['Добрый вечер! Или уже утро?', 'Good evening! Or is it morning already?'],
    ],
    again: [
      ['О, это снова вы! Здравствуйте!', "Oh, it's you again! Hello!"],
      ['Опять к нам? Рады видеть.', 'Back again? Good to see you.'],
      ['Ещё раз здравствуйте!', 'Hello again!'],
      ['А мы уже знакомы! Всё гуляете?', "We've met already! Still wandering about?"],
      ['А, это вы! Нашли дорогу?', 'Ah, it is you! Did you find your way?'],
    ],
    welcome: [
      ['Добро пожаловать в город {town}!', 'Welcome to {town}!'],
      ['Это город {town}. Вы к нам в гости?', 'This is {town}. Are you visiting?'],
      ['Впервые в городе {town}?', 'First time in {town}?'],
      ['Хороший день вы выбрали, чтобы посмотреть город {town}.', 'You picked a good day to see {town}.'],
      ['Милости просим! Город {town} гостям всегда рад.', '{town} is always glad to have guests. Come on in!'],
      ['Ну, что привело вас в город {town}?', 'So, what brings you to {town}?'],
    ],
    capitalHere: [
      ['Город {town} — столица нашей страны.', '{town} is the capital of our country.'],
      ['Это столица, между прочим. Всё самое важное происходит здесь.', 'This is the capital, you know. Everything important happens here.'],
      ['Здесь заседает правительство. Кругом важные люди в костюмах.', 'The government sits here. Important people in suits everywhere.'],
      ['Столица есть столица: жизнь тут не останавливается ни на минуту.', "A capital is a capital: life here doesn't stop for a minute."],
    ],
    capitalThere: [
      ['Наша столица — {capital}. Там стоит побывать.', "Our capital is {capital}. It's worth a visit."],
      ['Вы уже были в столице? Это {capital}.', "Have you been to the capital yet? That's {capital}."],
      ['{capital} думает, что управляет страной. Ну, так оно и есть.', '{capital} thinks it runs the country. Well, it does.'],
      ['{capital} — большой город, но мне и здесь хорошо.', "{capital} is a big city, but I'm happy right here."],
    ],
    big: [
      ['Это большой город. Здесь легко заблудиться!', "It's a big city. Easy to get lost here!"],
      ['Столько народу! Можно всю жизнь прожить и не узнать всех улиц.', 'So many people! You could live here all your life and not know every street.'],
      ['Пробки тут, конечно, жуткие. Зато всегда что-то происходит.', "The traffic jams are awful, of course. But there's always something going on."],
      ['Большой город никогда не останавливается. Люблю его — почти всегда.', 'A big city never stops. I love it, most of the time.'],
    ],
    middling: [
      ['Не большой и не маленький. В самый раз.', 'Not big, not small. Just right.'],
      ['Всё есть, и всё можно обойти пешком.', 'It has everything, and you can walk all of it.'],
      ['Город {town} как раз хорошего размера: за пару дней всё увидите.', "{town} is just the right size: you'll see it all in a couple of days."],
      ['Все жалуются, что тут скучно, а уезжать никто не хочет.', 'Everyone complains it is dull here, and nobody wants to leave.'],
    ],
    small: [
      ['Это небольшое место. Здесь все друг друга знают.', "It's a small place. Everybody knows everybody here."],
      ['Чихнёте на одном конце улицы — на другом скажут «будьте здоровы».', 'Sneeze at one end of the street and they say "bless you" at the other.'],
      ['В городе {town} мало что происходит, и нас это устраивает.', 'Not much happens in {town}, and that suits us fine.'],
      ['Вы тут самое интересное событие за неделю!', "You're the most exciting thing to happen here all week!"],
    ],
    coast: [
      ['Мы живём у воды. Рыба здесь очень хорошая.', 'We live by the water. The fish here is very good.'],
      ['Сходите посмотрите на воду. Она каждый день разная.', 'Go and look at the water. It is different every day.'],
      ['Чувствуете? Это море пахнет. Никогда не надоедает.', 'Smell that? That is the sea. You never tire of it.'],
      ['Лодки уходят затемно, а вечером — свежая рыба на столе.', 'The boats go out before dawn, and by evening there is fresh fish on the table.'],
    ],
    inland: [
      ['Море далеко, но земля здесь красивая.', 'The sea is far away, but the land here is beautiful.'],
      ['Пляжа нет, уж извините. Зато какие поля!', 'No beach, sorry about that. But look at those fields!'],
      ['Море? Туда, честно говоря, далеко ехать.', "The sea? To be honest, it's a long way to go."],
      ['Здесь всё держится на земле. Хорошая земля — хорошие люди.', 'Here everything rests on the land. Good land, good people.'],
    ],
    high: [
      ['Мы тут высоко. Не торопитесь, воздух разрежённый.', "We're high up here. Take it slowly, the air is thin."],
      ['В горах главное богатство — вид.', 'In the mountains, the view is the greatest wealth.'],
      ['Тут у всех крепкие ноги: ничего ровного нет.', 'Everyone here has strong legs: nothing is flat.'],
      ['Дышите глубже! К горам надо привыкнуть.', 'Breathe deeper! The mountains take getting used to.'],
    ],
    snowy: [
      ['Снег девять месяцев в году. Остальные три ругаем грязь.', 'Snow nine months a year. The other three, we grumble about the mud.'],
      ['Всё белым-бело. Вам бы обувь потеплее.', 'Everything is white as white. You could use warmer boots.'],
      ['Мы холода не боимся. Он туристов отпугивает — присутствующие не в счёт!', "We don't mind the cold. It scares off the tourists. Present company excepted!"],
      ['Когда снег свежий, так тихо, что слышно собственные мысли.', 'When the snow is fresh, it is so quiet you can hear your own thoughts.'],
    ],
    forest: [
      ['Лес тут на много дней пути. С тропинки не сходите!', 'The forest goes on for days here. Stay on the path!'],
      ['Прогуляйтесь по лесу — голова проясняется.', 'Take a walk in the woods. It clears the head.'],
      ['Осенью все ходят за грибами и ягодами.', 'In autumn everyone goes out for mushrooms and berries.'],
      ['Деревья, деревья и снова деревья. Ни на что не променяю.', "Trees, trees and more trees. I wouldn't trade it for anything."],
    ],
    desert: [
      ['Тут песок, сколько хватает глаз.', 'Out here it is sand as far as the eye can see.'],
      ['Пейте побольше воды. Пустыня ошибок не прощает.', 'Drink plenty of water. The desert does not forgive mistakes.'],
      ['Ночи в пустыне холодные, между прочим. Никто не верит.', 'Desert nights are cold, you know. Nobody believes it.'],
      ['Дождитесь ночи: звёзд тут миллионы.', 'Wait for the night: there are millions of stars out here.'],
    ],
    plains: [
      ['Кругом ровная степь — непогоду видно за день.', 'Flat steppe all round: you can see bad weather a day away.'],
      ['Небо тут огромное, и ветру ничто не мешает.', 'The sky is huge here, and nothing stops the wind.'],
      ['Хорошие пастбища кругом. Осторожнее со стадами.', 'Good grazing all round. Watch out for the herds.'],
      ['Трава до самого горизонта, как зелёное море.', 'Grass right to the horizon, like a green sea.'],
    ],
    tropical: [
      ['Тут всё растёт: воткни палку — вырастет дерево.', 'Everything grows here: stick a stick in the ground and a tree comes up.'],
      ['Если дождь, то уж ливень. А потом раз — и солнце.', 'When it rains, it pours. Then, just like that, the sun.'],
      ['Попробуйте фрукты на рынке. Таких вы ещё не ели.', "Try the fruit at the market. You've never had anything like it."],
      ['Круглый год зелено. Зима? Что такое зима?', "Green all year round. Winter? What's winter?"],
    ],
    landmark: [
      ['{landmark} — обязательно посмотрите! Это примерно в {km} км {dir}.', "{landmark}, you must see it! It's about {km} km {dir}."],
      ['{landmark} — примерно в {km} км {dir}. Стоит каждого шага!', "{landmark} is about {km} km {dir}. It's worth every step!"],
      ['Все едут смотреть — {landmark}. Это километрах в {km} {dir}.', "Everybody goes to see it: {landmark}. It's some {km} km {dir}."],
      ['Любите старину? Тогда вам сюда: {landmark}, примерно {km} км {dir}.', 'Fond of old things? Then this is for you: {landmark}, about {km} km {dir}.'],
    ],
    landmarkNear: [
      ['{landmark} совсем рядом. Мимо не пройдёте!', "{landmark} is very close. You can't miss it!"],
      ['{landmark} — буквально за углом. Уже были там?', "{landmark} is right round the corner. Have you been yet?"],
      ['Каждый день видим: {landmark}. И всё равно дух захватывает.', 'We see it every day: {landmark}. And it still takes our breath away.'],
      ['Тут рядом {landmark}. Сходите пораньше, пока нет толпы.', '{landmark} is close by. Go early, before the crowds.'],
    ],
    plane: [
      ['Там в поле самолётик стоит, {dir}. Если умеете летать!', "There's a little plane in a field {dir}. If you can fly!"],
      ['Кто-то оставил самолёт в поле {dir}. Не хотите полетать?', 'Somebody left a plane in a field {dir}. Fancy a flight?'],
      ['Умеете летать? Самолёт ждёт {dir}.', 'Can you fly? A plane is waiting {dir}.'],
      ['Хотите увидеть всё сверху? Самолёт стоит {dir}.', "Want to see it all from above? There's a plane {dir}."],
    ],
    balloon: [
      ['Воздушный шар стоит в поле {dir}! Представляете, какой вид?', "There's a hot-air balloon in a field {dir}! Imagine the view!"],
      ['Летали когда-нибудь на воздушном шаре? Один есть {dir}.', 'Ever flown in a balloon? There is one {dir}.'],
      ['С поля {dir} поднимается воздушный шар. Это волшебно.', 'A balloon goes up from the field {dir}. It is magical.'],
      ['Давно мечтаю прокатиться на шаре {dir}, да страшно!', "I've long dreamed of a ride in the balloon {dir}, but I'm scared!"],
    ],
    boat: [
      ['Лодка стоит у воды {dir}, если хотите выйти в море.', "There's a boat by the water {dir}, if you want to go out."],
      ['Любите море? Лодка стоит {dir}. Только верните!', 'Like the sea? There is a boat {dir}. Just bring it back!'],
      ['Лодка привязана {dir}. Отсюда куда угодно можно доплыть.', 'A boat is tied up {dir}. From here you could sail anywhere.'],
      ['Возьмите лодку {dir} и посмотрите на берег с воды.', 'Take the boat {dir} and see the shore from the water.'],
    ],
    hot: [
      ['Сегодня жарко! Найдите тень.', "It's hot today! Find some shade."],
      ['Уф, ну и жара! Попейте воды.', 'Phew, what heat! Have some water.'],
      ['В такую жару только в тенёчке сидеть.', 'In heat like this, all you can do is sit in the shade.'],
      ['В такое пекло даже собаки по домам сидят.', 'In this scorcher even the dogs stay indoors.'],
      ['Жарко, да? А для нас это ещё прохладно!', "Hot, isn't it? And for us this is cool!"],
    ],
    cold: [
      ['Брр, сегодня холодно! Оденьтесь потеплее.', "Brr, it's cold today! Wrap up warm."],
      ['Мороз! А где ваши перчатки?', 'Freezing! Where are your gloves?'],
      ['Так холодно, что нос уже не чувствую.', "It's so cold I can't feel my nose any more."],
      ['Холодно? Подождите, ещё ветер поднимется.', 'Cold? Just wait till the wind picks up.'],
      ['Выпейте чего-нибудь горячего — помогает.', 'Have something hot to drink. It helps.'],
    ],
    mild: [
      ['Какая сегодня чудесная погода.', 'What lovely weather today.'],
      ['Ни жарко, ни холодно. Красота, правда?', "Not hot, not cold. Lovely, isn't it?"],
      ['В такой день хочется гулять.', 'On a day like this you just want to be out walking.'],
      ['Погода — просто загляденье! Лишь бы продержалась.', "The weather is a sight for sore eyes! Let's hope it lasts."],
      ['Вот ради таких дней мы тут и живём.', 'Days like this are why we live here.'],
    ],
    late: [
      ['Уже поздно. Ночью на улицах тихо.', "It's late. The streets are quiet at night."],
      ['В такой час на улице только коты. И мы!', 'At this hour only the cats are out. And us!'],
      ['Мне давно пора спать. А вам что не спится?', "I should have been in bed ages ago. Why aren't you asleep?"],
      ['Посмотрите на звёзды! Отсюда их лучше всего видно.', 'Look at the stars! You see them best from here.'],
    ],
    early: [
      ['Рано вы встали! Лучшее время дня.', "You're up early! The best time of day."],
      ['Пекарня только открылась. Идите на запах!', 'The bakery has just opened. Follow the smell!'],
      ['Ранняя пташка, да? Город ещё не проснулся.', "An early bird, eh? The town isn't even awake yet."],
      ['Люблю тут утро, пока не начался шум.', 'I love the mornings here, before the noise starts.'],
    ],
    country: [
      ['{country} — прекрасная страна. Наслаждайтесь!', '{country} is a wonderful country. Enjoy it!'],
      ['Ну как вам {country}?', 'So, how do you like {country}?'],
      ['{country} — это не только столица. Посмотрите и глубинку!', "{country} isn't just the capital. See the countryside too!"],
      ['{country} — это целый мир. Каждый уголок не похож на другой.', '{country} is a whole world. No two corners are alike.'],
    ],
    dish: [
      ['{dish} — обязательно попробуйте, пока вы здесь.', "{dish}: you have to try it while you're here."],
      ['Уже пробовали? {dish} — это надо попробовать!', "Tried it yet? {dish} is a must!"],
      ['{dish} — вкуснее, чем у моей мамы, не бывает.', "{dish}: nobody makes it better than my mother."],
      ['Проголодались? Спросите, где тут {dish}. Не пожалеете.', "Hungry? Ask where to get {dish}. You won't regret it."],
    ],
    drink: [
      ['{drink} — вот что у нас пьют. Попробуйте перед отъездом.', '{drink} is what we drink here. Try some before you leave.'],
      ['После долгого дня нет ничего лучше, чем {drink}.', 'After a long day, nothing beats {drink}.'],
      ['{drink} — не попробовать просто нельзя.', "{drink}: you simply can't leave without trying it."],
      ['Закажите по-местному: {drink}. Вас сразу полюбят.', "Order like a local: {drink}. They'll love you for it."],
    ],
    festival: [
      ['Приезжайте на праздник — {festival}. Это чудесно!', 'Come back for the holiday, {festival}. It is wonderful!'],
      ['Лучшее время здесь — {festival}. Празднует вся страна.', 'The best time to be here is {festival}. The whole country celebrates.'],
      ['Слышали про такой праздник — {festival}? Вам бы понравилось.', "Have you heard of {festival}? You'd love it."],
      ['Каждый год жду не дождусь: {festival}!', "Every year I can hardly wait for it: {festival}!"],
    ],
    sport: [
      ['Здесь главное — {sport}. Все этим болеют.', 'Here it is all about {sport}. Everybody is mad about it.'],
      ['Любите спорт? У нас {sport} — просто страсть.', 'Do you like sport? Here {sport} is a real passion.'],
      ['В день игры весь город говорит об одном: {sport}.', 'On a game day the whole town talks about one thing: {sport}.'],
      ['У нас в семье все помешаны: {sport}. Бабушка, правда, только болеет у телевизора.', 'Our whole family is crazy about {sport}. Grandma just cheers at the TV.'],
    ],
    wonder: [
      ['Будет время — съездите: {wonder}. Это незабываемо.', "If you have time, go and see {wonder}. It's unforgettable."],
      ['{wonder} — такого больше нигде в мире нет.', "{wonder}: there's nothing like it anywhere in the world."],
      ['{wonder} — это каждый должен увидеть хоть раз в жизни.', '{wonder}: everyone should see it once in their life.'],
      ['В детстве меня туда возили: {wonder}. До сих пор снится.', 'As a child I was taken to see {wonder}. I still dream about it.'],
    ],
    pride: [
      ['Мы очень гордимся: {pride}.', 'We are very proud of this: {pride}.'],
      ['Не уезжайте, не узнав, что такое {pride}. Это про нас.', "Don't leave without learning about {pride}. It's who we are."],
      ['Знаете, чем мы гордимся? {pride}.', 'You know what we are proud of? {pride}.'],
      ['Спросите любого: {pride} — это разговор на несколько часов.', 'Ask anyone: {pride} is a conversation that lasts for hours.'],
    ],
    proverb: [
      ['Как у нас говорят: «{proverb}»', 'As we say here: “{proverb}”'],
      ['Бабушка всегда говорила: «{proverb}»', 'My grandmother always said: “{proverb}”'],
      ['Есть у нас поговорка: «{proverb}»', 'We have a saying: “{proverb}”'],
      ['Знаете поговорку? «{proverb}»', 'Do you know the saying? “{proverb}”'],
    ],
    chat: [
      ['Откуда вы? Вы ведь не отсюда.', "Where are you from? You're not from here, are you?"],
      ['Не спешите, осмотритесь. Здесь есть что посмотреть.', 'Take your time and look around. There is plenty to see.'],
      ['Путешествуете в одиночку? Смело.', "Travelling alone? That's brave."],
      ['Похоже, вы издалека идёте.', 'Looks like you have come a long way on foot.'],
      ['Заблудитесь — спрашивайте. Люди тут отзывчивые.', 'If you get lost, just ask. People here are helpful.'],
      ['А где вам пока больше всего понравилось?', 'Where have you liked best so far?'],
      ['Всю жизнь мечтаю попутешествовать. Может, когда-нибудь.', 'All my life I have dreamed of travelling. Maybe one day.'],
      ['Карта есть? Без карты никуда.', "Got a map? You can't go anywhere without a map."],
    ],
    childGreet: [
      ['Привет!', 'Hi!'],
      ['Здрасьте! А вы кто?', 'Hello! Who are you?'],
      ['Привет! Ого, вы до неба!', "Hi! Wow, you're as tall as the sky!"],
      ['Привет-привет!', 'Hello, hello!'],
    ],
    childChat: [
      ['Я очень быстро бегаю! Показать? Потом покажу.', "I can run really fast! Want to see? I'll show you later."],
      ['Вы приезжие? Мой друг говорит, что все приезжие богатые.', 'Are you from out of town? My friend says out-of-towners are all rich.'],
      ['А у меня вчера зуб выпал! Смотрите! Ой, его же не видно.', "A tooth fell out yesterday! Look! Oh, you can't see it."],
      ['Мама говорит, с чужими нельзя разговаривать. Но с вами, наверное, можно.', "Mum says I mustn't talk to strangers. But you're probably all right."],
      ['У вас есть собака? Я хочу собаку!', 'Do you have a dog? I want a dog!'],
      ['Когда вырасту, облечу на самолёте весь мир!', "When I grow up I'm going to fly a plane all round the world!"],
      ['Вы знаете какие-нибудь игры? Я знаю кучу игр.', 'Do you know any games? I know loads of games.'],
    ],
    childBye: [
      ['Пока-пока!', 'Bye bye!'],
      ['Пока! Приходите ещё поиграть!', 'Bye! Come back and play!'],
      ['Мне пора, мама зовёт!', 'I have to go, Mum is calling!'],
      ['До встречи! Не скучайте!', "See you! Don't be bored!"],
    ],
    grumpyGreet: [
      ['Хм. Чего надо?', 'Hm. What do you want?'],
      ['Ну? Что такое?', 'Well? What is it?'],
      ['Ох. Опять туристы.', 'Oh. Tourists again.'],
      ['Хм. Ну здравствуйте, что ли.', 'Hm. Hello, I suppose.'],
    ],
    grumpyChat: [
      ['Раньше тут было лучше, пока все не начали приезжать.', 'It was better here before everybody started coming.'],
      ['Всё вдвое дороже, чем раньше.', 'Everything costs twice what it used to.'],
      ['Не стойте посреди тротуара, тут люди живут.', "Don't stand in the middle of the pavement. People live here."],
      ['Молодёжь нынче вся в телефонах.', 'Young people these days are always on their phones.'],
      ['Не понимаю, зачем сюда едут. Смотреть нечего.', "I don't see why people come here. There's nothing to see."],
    ],
    grumpyBye: [
      ['Ну всё, идите уже.', 'Right, off you go.'],
      ['Ладно, не смею задерживать.', "Well, I won't keep you."],
      ['Хм. До свидания.', 'Hm. Goodbye.'],
      ['Смотрите под ноги. И калитку закройте.', 'Watch your step. And shut the gate.'],
    ],
    elderChat: [
      ['В моей молодости тут кругом были поля.', 'When I was young, this was all fields.'],
      ['Всю жизнь тут живу. Восемьдесят лет! Представляете?', 'I have lived here all my life. Eighty years! Can you imagine?'],
      ['В наше время все ходили пешком. Вы тоже пешком? Вот и правильно!', 'In our day everybody walked. You walk too? Good for you!'],
      ['Внуки теперь за границей живут. По воскресеньям звонят.', 'My grandchildren live abroad now. They call on Sundays.'],
      ['Всё так быстро меняется. А старые улочки всё те же.', 'Everything changes so fast. But the old streets stay the same.'],
    ],
    chattyChat: [
      ['Ой, как я люблю путешественников! Рассказывайте всё! Нет, погодите, сначала я.', 'Oh, I love travellers! Tell me everything! No, wait, me first.'],
      ['Мой двоюродный брат как-то поехал путешествовать. Вернулся с бородой и с женой!', 'My cousin went travelling once. He came back with a beard and a wife!'],
      ['Друзья говорят, что я могу болтать весь день. И ведь правы!', "My friends say I could talk all day. And they're right!"],
      ['Вы сегодня ели? Вид у вас голодный. Хотя мне все кажутся голодными.', 'Have you eaten today? You look hungry. Mind you, everyone looks hungry to me.'],
      ['Скажу по секрету: лучший вид на город — с холма за церковью.', "Here's a secret: the best view of town is from the hill behind the church."],
    ],
    bye: [
      ['До свидания! Счастливого пути.', 'Goodbye! Have a good journey.'],
      ['Всего доброго! Хорошей дороги.', 'All the best! Safe travels.'],
      ['Удачи в пути!', 'Good luck on the road!'],
      ['Ну, бывайте! Заглядывайте ещё.', 'Well, take care! Drop by again.'],
      ['Приятно было поговорить. Берегите себя!', 'Nice talking to you. Look after yourself!'],
      ['Ну, ступайте! Столько всего ещё впереди.', "Off you go, then! There's so much still ahead."],
    ],
  },
  countries: {
    // Every fact in the nominative, lower-case unless a name: the templates put it as a subject, after a dash or a colon.
    RUS: {
      dish: ['пельмени', 'pelmeni'],
      drink: ['квас', 'kvass'],
      festival: ['Масленица', 'Maslenitsa, the pancake week'],
      sport: ['хоккей', 'ice hockey'],
      wonder: ['озеро Байкал', 'Lake Baikal'],
      pride: ['русский балет', 'Russian ballet'],
      proverb: ['Без труда не вытащишь и рыбку из пруда', "Without effort you won't even pull a little fish out of the pond"],
    },
    BLR: {
      dish: ['драники', 'draniki, the potato pancakes'],
      drink: ['берёзовый сок', 'birch sap'],
      festival: ['Купалье', 'Kupalle, the midsummer night'],
      sport: ['хоккей', 'ice hockey'],
      wonder: ['Беловежская пуща', 'the Białowieża Forest'],
      pride: ['белорусский лён', 'Belarusian linen'],
    },
    KAZ: {
      dish: ['бешбармак', 'beshbarmak'],
      drink: ['кумыс', "kumis, fermented mare's milk"],
      festival: ['Наурыз', 'Nauryz, the spring new year'],
      sport: ['кокпар', 'kokpar, the game played on horseback'],
      wonder: ['Чарынский каньон', 'the Charyn Canyon'],
      pride: ['казахское гостеприимство', 'Kazakh hospitality'],
    },
    KGZ: {
      dish: ['бешбармак', 'beshbarmak'],
      drink: ['кумыс', "kumis, fermented mare's milk"],
      festival: ['Нооруз', 'Nooruz, the spring new year'],
      sport: ['кок-бору', 'kok-boru, the game played on horseback'],
      wonder: ['озеро Иссык-Куль', 'Lake Issyk-Kul'],
      pride: ['эпос о Манасе', 'the epic of Manas'],
    },
  },
};

export default RU;
