import type { Language } from '../phrases.ts';

const SV: Language = {
  locale: 'sv',
  name: 'Swedish',
  join: ' ',
  compass: ['norrut', 'åt nordost', 'österut', 'åt sydost', 'söderut', 'åt sydväst', 'västerut', 'åt nordväst'],
  lines: {
    morning: [
      ['God morgon!', 'Good morning!'],
      ['Morrn! Härlig start på dagen, va?', 'Morning! Lovely start to the day, eh?'],
      ['Åh, hej! God morgon.', 'Oh, hi! Good morning.'],
      ['Hej hej! Också uppe så här tidigt?', 'Hi there! Up this early too?'],
    ],
    afternoon: [
      ['God middag!', 'Good afternoon!'],
      ['Hej!', 'Hi!'],
      ['Tjena! Fin eftermiddag, va?', 'Hiya! Nice afternoon, eh?'],
      ['Hallå där! Skön eftermiddag det här.', 'Hello there! Lovely afternoon, this.'],
    ],
    evening: [
      ['God kväll!', 'Good evening!'],
      ['Hej! Fin kväll för en promenad.', 'Hi! Nice evening for a walk.'],
      ['Åh, god kväll på dig!', 'Oh, good evening to you!'],
      ['Hej hej! Skön kväll, va?', 'Hi there! Lovely evening, eh?'],
    ],
    night: [
      ['God kväll! Det är sent, eller hur?', 'Good evening! It’s late, isn’t it?'],
      ['Oj! Du skrämde mig. Hej!', 'Oh! You gave me a fright. Hi!'],
      ['Hej! Ute på nattpromenad?', 'Hi! Out for a night walk?'],
      ['God kväll! Eller är det redan morgon?', 'Good evening! Or is it morning already?'],
    ],
    again: [
      ['Åh, du igen! Hej!', 'Oh, you again! Hi!'],
      ['Tillbaka igen? Kul att ses.', 'Back again? Nice to see you.'],
      ['Hej igen!', 'Hello again!'],
      ['Vi har ju träffats! Fortfarande ute och upptäcker?', 'We’ve met! Still out exploring?'],
      ['Ah, det är du! Hittade du rätt?', 'Ah, it’s you! Did you find your way?'],
    ],
    welcome: [
      ['Välkommen till {town}!', 'Welcome to {town}!'],
      ['Det här är {town}. Är du på besök?', 'This is {town}. Are you visiting?'],
      ['Första gången i {town}?', 'First time in {town}?'],
      ['Du har valt en fin dag att se {town}.', 'You’ve picked a nice day to see {town}.'],
      ['Välkommen, välkommen! Kul att du hittat hit till {town}.', 'Welcome, welcome! Glad you found your way to {town}.'],
      ['Så, vad för dig till {town}?', 'So, what brings you to {town}?'],
    ],
    capitalHere: [
      ['{town} är vårt lands huvudstad.', '{town} is our country’s capital.'],
      ['Det här är huvudstaden, vet du. Allt händer i {town}.', 'This is the capital, you know. Everything happens in {town}.'],
      ['Här i {town} sitter makthavarna. Massor av viktiga människor i kostym.', 'The people in power sit here in {town}. Loads of important people in suits.'],
      ['Som huvudstad sover {town} aldrig riktigt.', 'Being the capital, {town} never really sleeps.'],
    ],
    capitalThere: [
      ['Vår huvudstad är {capital}. Den är värd ett besök.', 'Our capital is {capital}. It’s worth a visit.'],
      ['Har du varit i {capital} än? Det är vår huvudstad.', 'Have you been to {capital} yet? That’s our capital.'],
      ['Folk i {capital} tror att de styr landet. Och det gör de ju.', 'People in {capital} think they run the country. And they do.'],
      ['{capital} är större, men jag bor hellre här.', '{capital} is bigger, but I’d rather live here.'],
    ],
    big: [
      ['Det här är en stor stad. Det är lätt att gå vilse här!', 'This is a big city. It’s easy to get lost here!'],
      ['Så mycket folk! Man kan bo här hela livet utan att känna till varje gata.', 'So many people! You can live here all your life without knowing every street.'],
      ['Trafiken här, alltså. Men det händer alltid något.', 'The traffic here, honestly. But there’s always something going on.'],
      ['En sån här storstad står aldrig still. Jag älskar det. Oftast.', 'A big city like this never stands still. I love it. Mostly.'],
    ],
    middling: [
      ['Inte stor, inte liten. Lagom.', 'Not big, not small. Just right.'],
      ['Stort nog för att ha allt, litet nog för att gå överallt.', 'Big enough to have everything, small enough to walk everywhere.'],
      ['{town} har en bra storlek. Du hinner se allt på en dag eller två.', '{town} is a good size. You can see it all in a day or two.'],
      ['Alla klagar på att det är för lugnt här, och ingen flyttar någonsin.', 'Everyone complains it’s too quiet here, and nobody ever moves away.'],
    ],
    small: [
      ['Det är en liten ort. Här känner alla varandra.', 'It’s a small place. Everybody knows each other here.'],
      ['Liten ort. Nyser du så säger hela gatan prosit.', 'Small town. Sneeze and the whole street says bless you.'],
      ['Det händer inte mycket i {town}, och det gillar vi.', 'Not much happens in {town}, and we like it that way.'],
      ['Du är det mest spännande som hänt här på hela veckan!', 'You’re the most exciting thing to happen here all week!'],
    ],
    coast: [
      ['Vi bor vid vattnet här. Fisken är jättegod.', 'We live by the water here. The fish is really good.'],
      ['Gå och titta på vattnet. Det är olika varje dag.', 'Go and look at the water. It’s different every day.'],
      ['Känner du doften? Det är havet. Man tröttnar aldrig på det.', 'Smell that? That’s the sea. You never tire of it.'],
      ['Båtarna går ut tidigt och kommer hem med den godaste fisken.', 'The boats go out early and come home with the tastiest fish.'],
    ],
    inland: [
      ['Havet är långt borta, men landskapet här är vackert.', 'The sea is far away, but the countryside here is beautiful.'],
      ['Ingen strand här, tyvärr. Men titta på fälten.', 'No beach here, sadly. But look at the fields.'],
      ['Här ute är jorden allt. God mark, goda människor.', 'Out here the land is everything. Good soil, good people.'],
      ['Havet? Det är en bra bit dit. Men sjöar har vi gott om.', 'The sea? That’s a fair way off. But we have plenty of lakes.'],
    ],
    high: [
      ['Vi är högt upp här. Ta det lugnt, luften är tunn.', 'We’re high up here. Take it easy, the air is thin.'],
      ['Så här uppe i bergen är utsikten det bästa vi har.', 'Up here in the mountains, the view is the best thing we have.'],
      ['Du får starka ben av att bo här uppe. Ingenting är platt.', 'You get strong legs living up here. Nothing is flat.'],
      ['Tänk på andningen! Höjden tar tid att vänja sig vid.', 'Mind your breathing! The altitude takes time to get used to.'],
    ],
    snowy: [
      ['Snö nio månader om året. Resten av tiden klagar vi på slasket.', 'Snow nine months a year. The rest of the time we complain about the slush.'],
      ['Allt är vitt här ute. Du behöver bättre kängor än de där.', 'Everything is white out here. You need better boots than those.'],
      ['Kylan bryr vi oss inte om. Den håller turisterna borta. Närvarande undantagna!', 'We don’t mind the cold. It keeps the tourists away. Present company excepted!'],
      ['När nysnön ligger är det så tyst att man hör sina egna tankar.', 'When the fresh snow lies, it’s so quiet you can hear your own thoughts.'],
    ],
    forest: [
      ['Skogen fortsätter i dagar här. Håll dig på stigen!', 'The forest goes on for days here. Stay on the path!'],
      ['Ta en promenad i skogen. Det rensar huvudet.', 'Take a walk in the forest. It clears the head.'],
      ['Varje höst plockar vi svamp och bär där ute.', 'Every autumn we pick mushrooms and berries out there.'],
      ['Träd, träd och ännu mer träd. Jag skulle inte vilja bo någon annanstans.', 'Trees, trees and more trees. I wouldn’t want to live anywhere else.'],
    ],
    desert: [
      ['Här ute är det sand så långt ögat når.', 'Out here it’s sand as far as the eye can see.'],
      ['Drick mycket vatten. Öknen förlåter inget.', 'Drink plenty of water. The desert forgives nothing.'],
      ['Nätterna i öknen är kalla, vet du. Ingen tror på det.', 'Desert nights are cold, you know. Nobody believes it.'],
      ['Vänta på stjärnorna i natt. Här ute finns det miljontals.', 'Wait for the stars tonight. Out here there are millions.'],
    ],
    plains: [
      ['Det är platt i mil. Man ser vädret komma en dag i förväg.', 'It’s flat for miles. You see the weather coming a day ahead.'],
      ['Stor himmel här ute. Inget som stoppar vinden.', 'Big sky out here. Nothing to stop the wind.'],
      ['Bra betesmark, allihop. Se upp för hjordarna.', 'Good grazing land, all of it. Watch out for the herds.'],
      ['Gräset tar aldrig slut. Som ett grönt hav.', 'The grass never ends. Like a green sea.'],
    ],
    tropical: [
      ['Allt växer här. Sätt ner en pinne så blir det ett träd.', 'Everything grows here. Stick a twig in the ground and it becomes a tree.'],
      ['När regnet kommer här så kommer det på riktigt. Sen slutar det, bara sådär.', 'When the rain comes here, it really comes. Then it stops, just like that.'],
      ['Smaka frukten på torget. Du har aldrig ätit något liknande.', 'Try the fruit at the market. You’ve never eaten anything like it.'],
      ['Det är grönt här året runt. Vinter? Vad är det?', 'It’s green here all year round. Winter? What’s that?'],
    ],
    landmark: [
      ['Missa inte {landmark}! Det ligger ungefär {km} km {dir}.', 'Don’t miss {landmark}! It’s about {km} km {dir}.'],
      ['Har du sett {landmark}? Det ligger {km} km {dir} och är värt varje steg.', 'Have you seen {landmark}? It’s {km} km {dir} and worth every step.'],
      ['Alla åker till {landmark}. Det är ungefär {km} km {dir}.', 'Everybody goes to {landmark}. It’s about {km} km {dir}.'],
      ['Har du en ledig dag? {landmark} ligger {km} km {dir}. Folk kommer från hela världen.', 'Got a free day? {landmark} is {km} km {dir}. People come from all over the world.'],
    ],
    landmarkNear: [
      ['{landmark} ligger alldeles i närheten. Du kan inte missa det!', '{landmark} is right nearby. You can’t miss it!'],
      ['Har du varit vid {landmark} än? Det ligger precis runt hörnet.', 'Have you been to {landmark} yet? It’s just round the corner.'],
      ['Vi ser {landmark} varje dag, och det tar fortfarande andan ur mig.', 'We see {landmark} every day, and it still takes my breath away.'],
      ['Gå och se {landmark}, det är ju här. Tidigt, innan folkmassorna.', 'Go and see {landmark}, it’s right here. Early, before the crowds.'],
    ],
    plane: [
      ['Det står ett litet flygplan på ett fält {dir}, om du kan flyga!', 'There’s a little plane in a field {dir}, if you can fly!'],
      ['Någon har lämnat ett flygplan på en åker {dir}. Sugen på en tur?', 'Somebody left a plane in a field {dir}. Fancy a trip?'],
      ['Kan du flyga? Det står ett plan och väntar {dir}.', 'Can you fly? There’s a plane waiting {dir}.'],
      ['Vill du se allt ovanifrån finns det ett flygplan {dir}.', 'If you want to see it all from above, there’s a plane {dir}.'],
    ],
    balloon: [
      ['Det står en luftballong på ett fält {dir}! Tänk dig utsikten.', 'There’s a hot-air balloon in a field {dir}! Imagine the view.'],
      ['Har du någonsin åkt luftballong? Det finns en {dir}.', 'Have you ever been up in a balloon? There’s one {dir}.'],
      ['En ballong stiger upp från fältet {dir}. Det är magiskt.', 'A balloon rises from the field {dir}. It’s magical.'],
      ['Jag har alltid velat prova ballongen {dir}. Men jag vågar inte!', 'I’ve always wanted to try the balloon {dir}. But I don’t dare!'],
    ],
    boat: [
      ['Det ligger en båt vid vattnet {dir}, om du vill ge dig ut.', 'There’s a boat by the water {dir}, if you want to head out.'],
      ['Gillar du sjön? Det ligger en båt {dir}. Lämna bara tillbaka den!', 'Like being on the water? There’s a boat {dir}. Just bring it back!'],
      ['En båt ligger förtöjd {dir}. Härifrån kan du segla vart som helst.', 'A boat is moored {dir}. From here you could sail anywhere.'],
      ['Ta båten {dir} och se kusten från vattnet.', 'Take the boat {dir} and see the coast from the water.'],
    ],
    hot: [
      ['Det är varmt i dag! Sök lite skugga.', 'It’s hot today! Find some shade.'],
      ['Puh, vilken hetta! Drick lite vatten, det ser ut som du behöver det.', 'Phew, what heat! Drink some water, you look like you need it.'],
      ['Det är för varmt för att göra något annat än att sitta i skuggan.', 'It’s too hot to do anything but sit in the shade.'],
      ['I den här värmen stannar till och med hundarna inne.', 'In this heat even the dogs stay indoors.'],
      ['Varmt, va? Jag smälter snart.', 'Hot, eh? I’m about to melt.'],
    ],
    cold: [
      ['Brr, det är kallt i dag! Klä dig varmt.', 'Brr, it’s cold today! Dress warmly.'],
      ['Iskallt! Var har du vantarna?', 'Freezing! Where are your mittens?'],
      ['Det är så kallt att näsan har slutat fungera.', 'It’s so cold my nose has stopped working.'],
      ['Kallt nog för dig? Vänta bara tills det börjar blåsa.', 'Cold enough for you? Just wait till the wind starts.'],
      ['Skaffa dig något varmt att dricka. Det hjälper.', 'Get yourself something hot to drink. It helps.'],
    ],
    mild: [
      ['Vilket härligt väder i dag.', 'What lovely weather today.'],
      ['Inte för varmt, inte för kallt. Lagom, helt enkelt.', 'Not too warm, not too cold. Just right, simply.'],
      ['En sån här dag vill man bara vara ute.', 'On a day like this you just want to be outside.'],
      ['Underbart väder! Hoppas det håller i sig.', 'Wonderful weather! Let’s hope it lasts.'],
      ['Det är för sådana här dagar vi bor här.', 'Days like this are why we live here.'],
    ],
    late: [
      ['Det är sent. På natten är gatorna lugna.', 'It’s late. The streets are quiet at night.'],
      ['Vid den här tiden är det bara katterna ute. Och vi!', 'At this hour only the cats are out. And us!'],
      ['Jag borde ligga i sängen. Varför är du uppe?', 'I should be in bed. Why are you up?'],
      ['Titta på stjärnorna! Härifrån syns de som bäst.', 'Look at the stars! You see them best from here.'],
    ],
    early: [
      ['Vad tidigt du är uppe! Dagens bästa stund.', 'You’re up early! The best part of the day.'],
      ['Bageriet har precis öppnat. Följ doften!', 'The bakery has just opened. Follow the smell!'],
      ['Morgonpigg, va? Stan har inte ens vaknat än.', 'An early riser, eh? The town isn’t even awake yet.'],
      ['Jag älskar morgonen här, innan oväsendet börjar.', 'I love the morning here, before the noise starts.'],
    ],
    country: [
      ['{country} är ett vackert land. Njut av det!', '{country} is a beautiful country. Enjoy it!'],
      ['Vad tycker du om {country} hittills?', 'What do you think of {country} so far?'],
      ['Folk säger att {country} är litet på kartan men stort i hjärtat.', 'People say {country} is small on the map but big in the heart.'],
      ['Res runt i hela {country} om du kan. Varje hörn är olika.', 'Travel all over {country} if you can. Every corner is different.'],
    ],
    dish: [
      ['Du måste smaka {dish} medan du är här.', 'You have to try {dish} while you’re here.'],
      ['Har du ätit {dish} än? Nej? Åh, det måste du!', 'Have you had {dish} yet? No? Oh, you must!'],
      ['Ingen lagar {dish} som min mamma.', 'Nobody makes {dish} like my mum.'],
      ['Är du hungrig, ta {dish}. Du kommer inte att ångra dig.', 'If you’re hungry, have {dish}. You won’t regret it.'],
    ],
    drink: [
      ['Ta lite {drink} innan du går. Det är det vi dricker här.', 'Have some {drink} before you go. It’s what we drink here.'],
      ['Inget slår {drink} i slutet av dagen.', 'Nothing beats {drink} at the end of the day.'],
      ['Du har inte levt förrän du har smakat {drink}.', 'You haven’t lived until you’ve tasted {drink}.'],
      ['Beställ {drink} som vi gör här, så blir alla glada.', 'Order {drink} the way we do here, and everyone will be happy.'],
    ],
    festival: [
      ['Du borde komma tillbaka till {festival}. Det är underbart!', 'You should come back for {festival}. It’s wonderful!'],
      ['Bästa tiden att vara här är på {festival}. Då firar alla.', 'The best time to be here is at {festival}. Everybody celebrates then.'],
      ['Har du hört talas om {festival}? Det skulle du älska.', 'Have you heard of {festival}? You’d love it.'],
      ['Jag räknar dagarna till {festival} varje år.', 'I count the days to {festival} every year.'],
    ],
    sport: [
      ['Här handlar allt om {sport}.', 'Here it’s all about {sport}.'],
      ['Gillar du {sport}? Här är vi tokiga i det.', 'Do you like {sport}? We’re crazy about it here.'],
      ['På helgerna pratar hela stan bara om en sak: {sport}.', 'At weekends the whole town talks about one thing: {sport}.'],
      ['Hela min familj håller på med {sport}. Ja, farmor skriker mest.', 'My whole family does {sport}. Well, Grandma mostly shouts.'],
    ],
    wonder: [
      ['Om du har tid, åk och se {wonder}. Det glömmer du aldrig.', 'If you have time, go and see {wonder}. You’ll never forget it.'],
      ['Har du sett {wonder}? Det finns inget liknande i världen.', 'Have you seen {wonder}? There’s nothing like it in the world.'],
      ['Alla borde se {wonder} en gång i livet.', 'Everyone should see {wonder} once in their life.'],
      ['Jag såg {wonder} som barn. Jag drömmer fortfarande om det.', 'I saw {wonder} as a child. I still dream about it.'],
    ],
    pride: [
      ['Vi är väldigt stolta över {pride}.', 'We’re very proud of {pride}.'],
      ['Åk inte härifrån utan att lära dig om {pride}. Det är vilka vi är.', 'Don’t leave without learning about {pride}. It’s who we are.'],
      ['Vet du vad vi är stolta över? {pride}.', 'You know what we’re proud of? {pride}.'],
      ['Fråga vem som helst här om {pride}, så pratar de i timmar.', 'Ask anyone here about {pride}, and they’ll talk for hours.'],
    ],
    proverb: [
      ['Som vi säger här: ”{proverb}”', 'As we say here: “{proverb}”'],
      ['Min mormor sa alltid: ”{proverb}”', 'My grandma always said: “{proverb}”'],
      ['Det finns ett talesätt här: ”{proverb}”', 'There’s a saying here: “{proverb}”'],
      ['Känner du till ordspråket? ”{proverb}”', 'Do you know the saying? “{proverb}”'],
    ],
    chat: [
      ['Var kommer du ifrån? Du är inte härifrån.', 'Where are you from? You’re not from around here.'],
      ['Ta den tid du behöver och se dig omkring. Det finns mycket att se.', 'Take all the time you need and look around. There’s a lot to see.'],
      ['Reser du ensam? Modigt.', 'Travelling alone? Brave.'],
      ['Du ser ut att ha gått en lång väg.', 'You look like you’ve walked a long way.'],
      ['Om du går vilse är det bara att fråga. Folk här är trevliga.', 'If you get lost, just ask. People here are friendly.'],
      ['Vilket är det bästa stället du varit på hittills?', 'What’s the best place you’ve been so far?'],
      ['Jag har alltid velat resa. Kanske en dag.', 'I’ve always wanted to travel. Maybe one day.'],
      ['Har du en karta med dig? Utan karta går man inte hemifrån.', 'Have you got a map with you? You don’t leave home without a map.'],
    ],
    childGreet: [
      ['Hej!', 'Hi!'],
      ['Hej! Vem är du?', 'Hi! Who are you?'],
      ['Hej! Vad lång du är!', 'Hi! You’re so tall!'],
      ['Hej hej!', 'Hi hi!'],
    ],
    childChat: [
      ['Jag kan springa jättefort! Vill du se? Kanske sen.', 'I can run super fast! Want to see? Maybe later.'],
      ['Är du turist? Min kompis säger att turister är rika.', 'Are you a tourist? My friend says tourists are rich.'],
      ['Jag tappade en tand i går! Titta! Åh, det syns inte.', 'I lost a tooth yesterday! Look! Oh, you can’t see it.'],
      ['Mamma säger att jag inte får prata med främlingar. Men du ser snäll ut.', 'Mum says I mustn’t talk to strangers. But you look nice.'],
      ['Har du en hund? Jag vill ha en hund.', 'Do you have a dog? I want a dog.'],
      ['När jag blir stor ska jag flyga flygplan jorden runt!', 'When I grow up I’m going to fly planes round the world!'],
      ['Kan du några lekar? Jag kan jättemånga.', 'Do you know any games? I know loads.'],
    ],
    childBye: [
      ['Hej då!', 'Bye!'],
      ['Hej då! Kom tillbaka och lek!', 'Bye! Come back and play!'],
      ['Jag måste gå, mamma ropar!', 'I have to go, Mum’s calling!'],
      ['Puss och kram, hej då!', 'Kisses and hugs, bye!'],
    ],
    grumpyGreet: [
      ['Hm. Vad vill du?', 'Hm. What do you want?'],
      ['Ja? Vad gäller det?', 'Yes? What’s this about?'],
      ['Jaha. Ännu en turist.', 'Right. Another tourist.'],
      ['Mm. Hej, antar jag.', 'Mm. Hello, I suppose.'],
    ],
    grumpyChat: [
      ['Det var bättre här förr, innan alla började komma hit.', 'It was better here before everybody started coming.'],
      ['Allt kostar dubbelt så mycket nu.', 'Everything costs twice as much now.'],
      ['Stå inte mitt på trottoaren. Folk bor här.', 'Don’t stand in the middle of the pavement. People live here.'],
      ['Ungdomarna nuförtiden, alltid med näsan i mobilen.', 'Young people nowadays, always with their noses in their phones.'],
      ['Jag förstår inte varför folk kommer hit. Här finns inget att se.', 'I don’t understand why people come here. There’s nothing to see.'],
    ],
    grumpyBye: [
      ['Jaha. Iväg med dig då.', 'Right. Off you go, then.'],
      ['Ja, jag ska inte hålla dig kvar.', 'Well, I won’t keep you.'],
      ['Hm. Adjö.', 'Hm. Goodbye.'],
      ['Sköt om dig. Och stäng grinden.', 'Take care. And shut the gate.'],
    ],
    elderChat: [
      ['När jag var ung var det här bara åkrar.', 'When I was young, this was all fields.'],
      ['Jag har bott här hela mitt liv. Åttio år! Kan du tänka dig?', 'I’ve lived here all my life. Eighty years! Can you imagine?'],
      ['På min tid gick vi överallt. Du går också, ser jag. Bra!', 'In my day we walked everywhere. You walk too, I see. Good!'],
      ['Barnbarnen bor utomlands nu. De ringer varje söndag.', 'The grandchildren live abroad now. They call every Sunday.'],
      ['Allt förändras så fort. Men de gamla gatorna är sig lika.', 'Everything changes so fast. But the old streets stay the same.'],
    ],
    chattyChat: [
      ['Åh, jag älskar att träffa resenärer! Berätta allt. Nej, vänta, jag börjar.', 'Oh, I love meeting travellers! Tell me everything. No, wait, I’ll start.'],
      ['Min kusin reste bort en gång. Han kom hem med skägg och en fru!', 'My cousin went travelling once. He came home with a beard and a wife!'],
      ['Jag kan prata hela dagen, säger mina vänner. De har inte fel!', 'I can talk all day, my friends say. They’re not wrong!'],
      ['Har du ätit? Du ser hungrig ut. Det tycker jag om alla.', 'Have you eaten? You look hungry. I think that about everyone.'],
      ['Ska jag avslöja en hemlighet? Bästa utsikten har man från kullen bakom kyrkan.', 'Shall I tell you a secret? The best view is from the hill behind the church.'],
    ],
    bye: [
      ['Hej då! Trevlig resa.', 'Bye! Have a nice trip.'],
      ['Ha det så bra! Njut av resten av resan.', 'All the best! Enjoy the rest of the trip.'],
      ['Lycka till på resan!', 'Good luck on your journey!'],
      ['Hej hej! Kom tillbaka och hälsa på.', 'Bye bye! Come back and visit.'],
      ['Kul att prata med dig. Sköt om dig!', 'Nice talking to you. Take care!'],
      ['Iväg med dig nu! Det finns så mycket att se.', 'Off you go now! There’s so much to see.'],
    ],
  },
  countries: {
    // Every fact is a bare noun phrase (no article, or a name) that stands unchanged as an object: "Har du smakat …?"
    SWE: {
      dish: ['köttbullar med lingonsylt', 'meatballs with lingonberry jam'],
      drink: ['kaffe', 'coffee'],
      festival: ['midsommar', 'Midsummer'],
      sport: ['ishockey', 'ice hockey'],
      wonder: ['Stockholms skärgård', 'the Stockholm archipelago'],
      pride: ['allemansrätten', 'the right to roam'],
      proverb: ['Det finns inget dåligt väder, bara dåliga kläder', 'There is no bad weather, only bad clothes'],
    },
    ALA: {
      dish: ['ålandspannkaka', 'Åland pancake'],
      festival: ['midsommar', 'Midsummer'],
      sport: ['segling', 'sailing'],
      wonder: ['Ålands skärgård', 'the Åland archipelago'],
      pride: ['vår sjöfartshistoria', 'our seafaring history'],
      proverb: ['Borta bra men hemma bäst', 'Away is good, but home is best'],
    },
  },
};

export default SV;
