import type { Language } from '../phrases.ts';

/**
 * Swahili as it is spoken to a stranger in Tanzania and Kenya, with *wewe*.
 * A name carries no noun class a template could agree with, so none does: a
 * name stands after *ni*, a verb or *kuhusu*, or in apposition to a common
 * noun that takes the agreement instead (*nchi ya {country}*, *mji wa {capital}*).
 */
const SW: Language = {
  locale: 'sw',
  name: 'Swahili',
  join: ' ',
  compass: [
    'upande wa kaskazini', 'upande wa kaskazini-mashariki', 'upande wa mashariki', 'upande wa kusini-mashariki',
    'upande wa kusini', 'upande wa kusini-magharibi', 'upande wa magharibi', 'upande wa kaskazini-magharibi',
  ],
  lines: {
    morning: [
      ['Habari za asubuhi!', 'Good morning!'],
      ['Hujambo! Umeamkaje?', 'Hello! How did you wake up?'],
      ['Sabalkheri!', 'Good morning!'],
      ['Mambo! Asubuhi njema.', 'Hi! Have a good morning.'],
    ],
    afternoon: [
      ['Habari za mchana!', 'Good afternoon!'],
      ['Mambo vipi!', "Hey, how's it going!"],
      ['Hujambo! Mchana mwema.', 'Hello! Good afternoon to you.'],
      ['Habari yako! Mchana mzuri huu.', 'How are you! Lovely afternoon, this.'],
    ],
    evening: [
      ['Habari za jioni!', 'Good evening!'],
      ['Masalkheri!', 'Good evening!'],
      ['Jioni njema!', 'Good evening to you!'],
      ['Hujambo! Jioni nzuri ya kutembea.', 'Hello! A nice evening for a walk.'],
    ],
    night: [
      ['Habari za usiku! Ni usiku sana, sivyo?', "Good evening! It's very late, isn't it?"],
      ['Lo! Umenishtua. Hujambo!', 'Oh! You startled me. Hello!'],
      ['Mambo! Unatembea usiku huu?', 'Hi! Out walking at this time of night?'],
      ['Usiku mwema! Au tayari ni asubuhi?', 'Good evening! Or is it morning already?'],
    ],
    again: [
      ['Aa, ni wewe tena! Mambo!', "Oh, it's you again! Hi!"],
      ['Umerudi? Nafurahi kukuona.', 'Back again? Nice to see you.'],
      ['Habari tena!', 'Hello again!'],
      ['Tumeonana tena! Bado unatalii?', 'We meet again! Still sightseeing?'],
      ['Umeipata njia uliyokuwa ukitafuta?', 'Did you find the way you were looking for?'],
    ],
    welcome: [
      ['Karibu {town}!', 'Welcome to {town}!'],
      ['Hapa ni {town}. Umekuja kutembelea?', 'This is {town}. Have you come to visit?'],
      ['Ni mara yako ya kwanza hapa {town}?', 'Is this your first time here in {town}?'],
      ['Umechagua siku nzuri kuona {town}.', "You've picked a good day to see {town}."],
      ['Karibu sana! Jisikie nyumbani hapa {town}.', 'You are most welcome! Make yourself at home here in {town}.'],
      ['Nini kimekuleta {town}?', 'What brings you to {town}?'],
    ],
    capitalHere: [
      ['{town} ni mji mkuu wa nchi yetu.', '{town} is the capital of our country.'],
      ['Huu ni mji mkuu, unajua. Kila kitu kinatokea hapa {town}.', 'This is the capital, you know. Everything happens here in {town}.'],
      ['Serikali iko hapa {town}. Watu wengi muhimu wenye suti.', 'The government is here in {town}. Lots of important people in suits.'],
      ['Mji mkuu kama huu haulali kamwe.', 'A capital like this never sleeps.'],
    ],
    capitalThere: [
      ['Mji mkuu wetu ni {capital}. Unafaa kutembelewa.', "Our capital is {capital}. It's worth a visit."],
      ['Umeshafika {capital}? Huo ndio mji mkuu wetu.', 'Have you been to {capital} yet? That is our capital.'],
      ['Watu wa {capital} hudhani wao ndio wanaoendesha nchi. Kweli, ndio wao.', 'People in {capital} think they run the country. Well, they do.'],
      ['Mji wa {capital} ni mkubwa zaidi, lakini mimi napenda kuishi hapa.', "{capital} is bigger, but I'd rather live here."],
    ],
    big: [
      ['Huu ni mji mkubwa. Ni rahisi kupotea hapa!', "This is a big city. It's easy to get lost here!"],
      ['Watu wengi mno! Unaweza kuishi hapa maisha yote na usijue kila mtaa.', 'So many people! You could live here all your life and not know every street.'],
      ['Foleni za magari hapa, jamani! Lakini kila wakati kuna jambo.', 'The traffic here, honestly! But there is always something going on.'],
      ['Mji mkubwa kama huu haupumziki. Naupenda, mara nyingi.', 'A big city like this never rests. I love it, mostly.'],
    ],
    middling: [
      ['Si mkubwa, si mdogo. Unafaa kabisa.', 'Not big, not small. Just right.'],
      ['Una kila kitu, na unaweza kuuzunguka kwa miguu.', 'It has everything, and you can get round it on foot.'],
      ['Mji wa {town} una ukubwa mzuri. Siku moja au mbili utakuwa umeuona wote.', "{town} is a nice size. In a day or two you'll have seen it all."],
      ['Kila mtu analalamika ni kimya mno, lakini hakuna anayeondoka.', 'Everybody complains it is too quiet, and nobody ever leaves.'],
    ],
    small: [
      ['Hapa ni mahali padogo. Kila mtu anamjua mwenzake.', 'This is a small place. Everybody knows everybody.'],
      ['Hakuna mengi yanayotokea hapa {town}, na tunapenda hivyo.', 'Not much happens here in {town}, and we like it that way.'],
      ['Ukipiga chafya, mtaa mzima unasema ‘afya’!', "Sneeze, and the whole street says 'bless you'!"],
      ['Wewe ndiye jambo la kusisimua zaidi wiki hii!', "You're the most exciting thing to happen here all week!"],
    ],
    coast: [
      ['Tunaishi kando ya maji hapa. Samaki ni watamu sana.', 'We live by the water here. The fish is delicious.'],
      ['Unasikia harufu hiyo? Ni bahari. Huwezi kuichoka.', "Smell that? That's the sea. You never tire of it."],
      ['Wavuvi hutoka alfajiri na kurudi na samaki bora kabisa.', 'The fishermen go out at dawn and come back with the very best fish.'],
      ['Tazama ngalawa zikirudi jioni. Ni picha nzuri.', 'Watch the outrigger canoes come home in the evening. A lovely sight.'],
    ],
    inland: [
      ['Tuko mbali na bahari, lakini nchi hii ni nzuri sana.', 'We are far from the sea, but this land is beautiful.'],
      ['Hakuna ufukwe hapa, pole. Lakini tazama mashamba hayo!', 'No beach here, sorry. But look at those fields!'],
      ['Bahari? Kusema kweli, sijawahi kuiona. Iko mbali sana.', "The sea? To be honest, I've never seen it. It's very far."],
      ['Huku ardhi ndiyo kila kitu. Udongo mzuri, watu wazuri.', 'Out here the land is everything. Good soil, good people.'],
    ],
    high: [
      ['Tuko juu sana hapa. Tembea polepole, hewa ni nyepesi.', "We're high up here. Walk slowly, the air is thin."],
      ['Huku milimani, mandhari ndiyo utajiri wetu.', 'Up here in the mountains, the view is our treasure.'],
      ['Ukiishi huku, miguu inakuwa na nguvu. Hakuna tambarare.', 'Live up here and your legs get strong. Nothing is flat.'],
      ['Asubuhi ukungu hushuka mpaka barabarani. Ni kama uko juu ya mawingu.', 'In the morning the mist comes down to the road. Like being above the clouds.'],
    ],
    snowy: [
      ['Theluji kila mahali! Hapa ni baridi kweli kweli.', 'Snow everywhere! It is really, truly cold here.'],
      ['Kila kitu ni cheupe huku. Utahitaji viatu bora kuliko hivyo.', "Everything is white out here. You'll need better shoes than those."],
      ['Theluji ikianguka upya, ni kimya kabisa.', 'When fresh snow falls, it is completely silent.'],
      ['Baridi hii hainitishi tena. Ila vidole vyangu vinalalamika!', "This cold doesn't scare me any more. My fingers complain, though!"],
    ],
    forest: [
      ['Msitu huu hauishi. Usitoke njiani!', "This forest never ends. Don't leave the path!"],
      ['Tembea msituni, kichwa kinatulia.', 'Take a walk in the forest, it calms the head.'],
      ['Asubuhi sikiliza ndege msituni. Ni kelele tupu!', 'In the morning, listen to the birds in the forest. What a racket!'],
      ['Miti, miti na miti zaidi. Sitaki kuishi mahali pengine.', "Trees, trees and more trees. I wouldn't live anywhere else."],
    ],
    desert: [
      ['Hapa ni mchanga kila upande, mpaka macho yanapoishia.', 'Here it is sand on every side, as far as the eye can see.'],
      ['Kunywa maji mengi. Jangwa halisamehe.', 'Drink plenty of water. The desert does not forgive.'],
      ['Usiku jangwani kuna baridi, unajua. Watu hawaamini.', 'Desert nights are cold, you know. People never believe it.'],
      ['Subiri nyota usiku wa leo. Huku ziko mamilioni!', 'Wait for the stars tonight. Out here there are millions!'],
    ],
    plains: [
      ['Ni tambarare kwa kilomita nyingi. Unaona mvua ikija kutoka mbali.', 'It is flat for miles. You can see the rain coming from far away.'],
      ['Anga ni pana hapa. Hakuna kinachozuia upepo.', 'The sky is wide here. Nothing stops the wind.'],
      ["Nyasi nzuri kwa malisho. Angalia ng'ombe wakipita!", 'Good grass for grazing. Watch out for the cattle going by!'],
      ['Savana hii haina mwisho. Ni kama bahari ya kijani.', 'This savanna has no end. It is like a green sea.'],
    ],
    tropical: [
      ['Kila kitu kinaota hapa. Panda kijiti, kinakuwa mti.', 'Everything grows here. Plant a twig and it becomes a tree.'],
      ['Mvua ikinyesha hapa, inanyesha kweli. Kisha inakatika ghafla.', 'When it rains here, it really rains. Then it stops, just like that.'],
      ['Onja matunda sokoni. Embe, nanasi, fenesi!', 'Try the fruit at the market. Mango, pineapple, jackfruit!'],
      ['Ni kijani mwaka mzima. Majira ya baridi? Ndiyo nini?', "It's green all year round. Winter? What's that?"],
    ],
    landmark: [
      ['Usikose kuona {landmark}! Ni kama kilomita {km} kutoka hapa, {dir}.', "Don't miss {landmark}! It's about {km} km from here, {dir}."],
      ['Umeshaona {landmark}? Ni safari ya kilomita {km} hivi, {dir}. Inastahili!', "Have you seen {landmark}? It's a trip of about {km} km, {dir}. Worth it!"],
      ['Kila mtu huenda kuona {landmark}. Ni kilomita {km} hivi, {dir}.', "Everybody goes to see {landmark}. It's about {km} km, {dir}."],
      ['Ukipata nafasi, nenda {landmark}: kilomita {km}, {dir}.', 'If you get the chance, go to {landmark}: {km} km, {dir}.'],
    ],
    landmarkNear: [
      ['Uko karibu sana na {landmark}. Huwezi kukosa!', "You're very close to {landmark}. You can't miss it!"],
      ['Umeshafika {landmark}? Ni hapo tu, kona ya pili.', "Been to {landmark} yet? It's just there, round the corner."],
      ['Kila siku naona {landmark}, na bado nashangaa.', 'I see {landmark} every day and I am still amazed.'],
      ['Nenda ukaone {landmark}, ni hapa hapa. Asubuhi mapema, kabla ya umati.', "Go and see {landmark}, it's right here. Early, before the crowds."],
    ],
    plane: [
      ['Kuna ndege ndogo shambani {dir}, kama unajua kuirusha!', "There's a little plane in a field {dir}, if you can fly it!"],
      ['Mtu ameacha ndege shambani {dir}. Unataka kuruka?', 'Somebody left a plane in a field {dir}. Fancy a flight?'],
      ['Unajua kurusha ndege? Kuna moja inakusubiri {dir}.', "Can you fly a plane? There's one waiting for you {dir}."],
      ['Ukitaka kuona kila kitu kutoka juu, kuna ndege {dir}.', "If you want to see it all from above, there's a plane {dir}."],
    ],
    balloon: [
      ['Kuna puto la hewa moto shambani {dir}! Fikiria mandhari kutoka juu.', "There's a hot-air balloon in a field {dir}! Imagine the view from up there."],
      ['Umewahi kupanda puto la hewa moto? Kuna moja {dir}.', 'Have you ever been up in a hot-air balloon? There is one {dir}.'],
      ['Puto hupaa kutoka shamba lile {dir}. Ni kama ndoto.', 'A balloon goes up from that field {dir}. It is like a dream.'],
      ['Siku zote nimetamani kupanda puto lile {dir}. Lakini naogopa!', "I've always wanted to ride that balloon {dir}. But I'm scared!"],
    ],
    boat: [
      ['Kuna mashua kando ya maji {dir}, kama unataka kwenda baharini.', "There's a boat by the water {dir}, if you want to go out to sea."],
      ['Unapenda bahari? Kuna mashua {dir}. Ila uirudishe!', "Like the sea? There's a boat {dir}. Just bring it back!"],
      ['Mashua imefungwa {dir}. Kutoka hapa unaweza kwenda popote.', 'A boat is tied up {dir}. From here you could go anywhere.'],
      ['Chukua mashua {dir} uone pwani kutoka majini.', 'Take the boat {dir} and see the coast from the water.'],
    ],
    hot: [
      ['Leo kuna joto! Tafuta kivuli kidogo.', "It's hot today! Find a bit of shade."],
      ['Jamani, jua kali! Kunywa maji, unaonekana una kiu.', 'Goodness, what sun! Drink some water, you look thirsty.'],
      ['Joto hili ni la kukaa kivulini tu.', 'This heat is only good for sitting in the shade.'],
      ['Kwa joto hili, hata mbwa wanakaa ndani.', 'In this heat, even the dogs stay indoors.'],
      ['Madafu ndiyo dawa ya joto hili.', 'Young coconuts are the cure for this heat.'],
    ],
    cold: [
      ['Brr, leo kuna baridi! Vaa nguo za joto.', "Brr, it's cold today! Wear something warm."],
      ['Baridi kali! Glavu zako ziko wapi?', 'Freezing! Where are your gloves?'],
      ['Baridi hii inaingia mpaka mifupani.', 'This cold gets right into the bones.'],
      ['Kunywa chai ya moto. Inasaidia.', 'Have some hot tea. It helps.'],
      ['Subiri upepo uanze, ndipo utaona baridi.', "Wait till the wind starts, then you'll see what cold is."],
    ],
    mild: [
      ['Hali ya hewa ni nzuri sana leo.', 'The weather is lovely today.'],
      ['Si joto, si baridi. Siku nzuri, sivyo?', "Not hot, not cold. A lovely day, isn't it?"],
      ['Siku kama hii, unataka kukaa nje tu.', 'A day like this, you just want to be outside.'],
      ['Hali ya hewa safi! Tuombe iendelee hivi.', "Beautiful weather! Let's hope it stays like this."],
      ['Siku kama hizi ndizo zinazotufanya tupende kuishi hapa.', 'Days like these are why we love living here.'],
    ],
    late: [
      ['Ni usiku sasa. Usiku mitaa huwa kimya.', "It's night now. The streets are quiet at night."],
      ['Saa hizi ni paka tu walioko nje. Na sisi!', 'At this hour only the cats are out. And us!'],
      ['Ningekuwa nimelala zamani. Mbona bado uko macho?', 'I should have been asleep long ago. Why are you still up?'],
      ['Tazama nyota! Zinaonekana vizuri sana kutoka hapa.', 'Look at the stars! You see them so well from here.'],
    ],
    early: [
      ['Umeamka mapema! Wakati bora wa siku.', "You're up early! The best time of day."],
      ['Maandazi ya moto yameanza kuuzwa. Fuata harufu!', 'Hot mandazi are already on sale. Follow the smell!'],
      ['Ndege wa mapema, eh? Mji bado haujaamka.', "An early bird, eh? The town isn't even awake yet."],
      ['Napenda asubuhi hapa, kabla ya kelele kuanza.', 'I love the mornings here, before the noise starts.'],
    ],
    country: [
      ['{country} ni nchi nzuri. Furahia!', '{country} is a beautiful country. Enjoy it!'],
      ['Unaionaje nchi ya {country} mpaka sasa?', 'How do you like {country} so far?'],
      ['Tembea kila pembe ya {country} ukiweza. Kila sehemu ni tofauti.', 'Travel every corner of {country} if you can. Every part is different.'],
      ['{country}: milima, mbuga, fukwe. Kuna kila kitu!', '{country}: mountains, parks, beaches. It has everything!'],
    ],
    dish: [
      ['Lazima uonje {dish} ukiwa hapa.', "You have to taste {dish} while you're here."],
      ['Umeshakula {dish}? Bado? Lazima ujaribu!', 'Have you had {dish} yet? Not yet? You must try it!'],
      ['Hakuna anayepika {dish} kama mama yangu.', 'Nobody cooks {dish} like my mother.'],
      ['Ukiwa na njaa, tafuta {dish}. Hutajuta.', "If you're hungry, find some {dish}. You won't regret it."],
    ],
    drink: [
      ['Kunywa {drink} kabla hujaondoka. Ndicho tunachokunywa hapa.', 'Have some {drink} before you go. It is what we drink here.'],
      ['Hakuna kitu kizuri kama {drink} mwisho wa siku.', 'Nothing beats {drink} at the end of the day.'],
      ['Hujaishi mpaka umeonja {drink}.', "You haven't lived until you've tasted {drink}."],
      ['Agiza {drink} kama mwenyeji, watakupenda sana.', "Order {drink} like a local and they'll love you for it."],
    ],
    festival: [
      ['Rudi tena wakati wa {festival}. Ni raha tupu!', 'Come back for {festival}. It is pure joy!'],
      ['Wakati mzuri wa kuwa hapa ni {festival}. Kila mtu anasherehekea.', 'The best time to be here is {festival}. Everybody celebrates.'],
      ['Umewahi kusikia kuhusu {festival}? Ungependa sana.', "Have you heard of {festival}? You'd love it."],
      ['Kila mwaka nahesabu siku mpaka {festival}.', 'Every year I count the days until {festival}.'],
    ],
    sport: [
      ['Hapa kila mtu ni shabiki wa {sport}.', "Here everybody's a fan of {sport}."],
      ['Unapenda {sport}? Hapa ni mapenzi makubwa!', "Do you like {sport}? Here it's a great love!"],
      ['Siku ya mashindano, mji mzima unazungumza {sport} tu.', 'On a big day, the whole town talks about nothing but {sport}.'],
      ['Familia yangu yote inashabikia {sport}. Bibi yangu hupiga kelele tu.', 'My whole family follows {sport}. My grandmother just shouts.'],
    ],
    wonder: [
      ['Ukipata muda, nenda ukaone {wonder}. Hutasahau kamwe.', "If you get time, go and see {wonder}. You'll never forget it."],
      ['Umeshaona {wonder}? Hakuna kitu kama hicho duniani.', 'Have you seen {wonder}? There is nothing like it in the world.'],
      ['Kila mtu anapaswa kuona {wonder} angalau mara moja maishani.', 'Everybody should see {wonder} at least once in their life.'],
      ['Nilienda kuona {wonder} nikiwa mtoto. Bado huota kuhusu safari ile.', 'I went to see {wonder} as a child. I still dream about that trip.'],
    ],
    pride: [
      ['Tunajivunia sana {pride}.', 'We are very proud of {pride}.'],
      ['Usiondoke bila kujifunza kuhusu {pride}. Ndio utambulisho wetu.', "Don't leave without learning about {pride}. It is who we are."],
      ['Unajua tunajivunia nini? {pride}.', 'Do you know what makes us proud? {pride}.'],
      ['Muulize mtu yeyote hapa kuhusu {pride}, ataongea kwa masaa.', 'Ask anyone here about {pride}, and they will talk for hours.'],
    ],
    proverb: [
      ['Kama tunavyosema hapa: “{proverb}”', 'As we say here: “{proverb}”'],
      ['Bibi yangu alikuwa akisema: “{proverb}”', 'My grandmother used to say: “{proverb}”'],
      ['Kuna methali hapa: “{proverb}”', 'There is a proverb here: “{proverb}”'],
      ['Unaijua methali hii? “{proverb}”', 'Do you know this proverb? “{proverb}”'],
    ],
    chat: [
      ['Unatoka wapi? Wewe si mwenyeji wa hapa.', "Where are you from? You're not from around here."],
      ['Usiwe na haraka, angalia huku na huko. Kuna mengi ya kuona.', 'No hurry, look around. There is a lot to see.'],
      ['Unasafiri peke yako? Una ujasiri.', "Travelling alone? You're brave."],
      ['Unaonekana umetembea mwendo mrefu.', 'You look like you have walked a long way.'],
      ['Ukipotea, uliza tu. Watu wa hapa ni wakarimu.', 'If you get lost, just ask. People here are kind.'],
      ['Ni sehemu gani nzuri zaidi uliyotembelea mpaka sasa?', "What's the best place you've been to so far?"],
      ['Hakuna haraka hapa. Pole pole, utafika.', "There's no hurry here. Slowly, slowly, you'll get there."],
    ],
    childGreet: [
      ['Jambo!', 'Hi!'],
      ['Mambo! Wewe ni nani?', 'Hi! Who are you?'],
      ['Shikamoo!', 'My respects! (how a child greets a grown-up)'],
      ['Haloo! Wewe ni mrefu!', "Hello! You're tall!"],
    ],
    childChat: [
      ['Naweza kukimbia haraka sana! Unataka kuona? Baadaye.', 'I can run really fast! Want to see? Later.'],
      ['Wewe ni mtalii? Rafiki yangu anasema watalii ni matajiri.', 'Are you a tourist? My friend says tourists are rich.'],
      ["Jana jino langu limeng'oka! Tazama! Lo, huoni.", "My tooth came out yesterday! Look! Oh, you can't see."],
      ['Mama anasema nisiongee na wageni. Lakini wewe unaonekana mpole.', 'Mum says not to talk to strangers. But you look kind.'],
      ['Una mbwa? Mimi nataka mbwa.', 'Do you have a dog? I want a dog.'],
      ['Nikikua nitarusha ndege duniani kote!', "When I grow up I'll fly a plane all round the world!"],
      ['Unajua kucheza mpira? Mimi ni hodari!', "Can you play football? I'm really good!"],
    ],
    childBye: [
      ['Kwaheri!', 'Bye!'],
      ['Baadaye! Rudi tucheze!', 'See you later! Come back and play!'],
      ['Lazima niende, mama ananiita!', 'I have to go, Mum is calling me!'],
      ['Tutaonana!', 'See you!'],
    ],
    grumpyGreet: [
      ['Hmm. Unataka nini?', 'Hmm. What do you want?'],
      ['Ndiyo? Nini tena?', 'Yes? What now?'],
      ['Aah. Mtalii mwingine.', 'Ah. Another tourist.'],
      ['Hmph. Jambo, nadhani.', 'Hmph. Hello, I suppose.'],
    ],
    grumpyChat: [
      ['Zamani hapa palikuwa pazuri, kabla kila mtu hajaanza kuja.', 'It was nicer here before everybody started coming.'],
      ['Kila kitu kimepanda bei mara mbili.', 'Everything costs twice what it used to.'],
      ['Usizibe njia, tafadhali. Watu wanaishi hapa.', "Don't block the way, please. People live here."],
      ['Vijana wa siku hizi, simu tu mchana kutwa.', 'Young people these days, on their phones all day long.'],
      ['Sijui kwa nini watu wanakuja hapa. Hakuna cha kuona.', "I don't know why people come here. There's nothing to see."],
      ['Foleni, joto, kelele. Nini zaidi?', 'Traffic, heat, noise. What else?'],
    ],
    grumpyBye: [
      ['Haya. Nenda zako basi.', 'Right. Off you go, then.'],
      ['Haya, sitakuchelewesha.', "Fine, I won't hold you up."],
      ['Hmm. Kwaheri.', 'Hmm. Goodbye.'],
      ['Nenda salama. Na ufunge geti!', 'Go safely. And shut the gate!'],
    ],
    elderChat: [
      ['Nilipokuwa kijana, hapa palikuwa mashamba matupu.', 'When I was young, this was all fields.'],
      ['Nimeishi hapa maisha yangu yote. Miaka themanini! Unaamini?', "I've lived here all my life. Eighty years! Can you believe it?"],
      ['Zamani tulitembea kwa miguu kila mahali. Wewe pia unatembea. Safi!', 'Back then we walked everywhere. You walk too. Good!'],
      ["Wajukuu wangu wanaishi ng'ambo sasa. Hupiga simu kila Jumapili.", 'My grandchildren live abroad now. They call every Sunday.'],
      ['Mambo yanabadilika haraka sana. Lakini mitaa ya zamani ni ile ile.', 'Things change so fast. But the old streets are just the same.'],
    ],
    chattyChat: [
      ['Aa, napenda kukutana na wasafiri! Niambie kila kitu. Hapana, subiri, nianze mimi.', 'Oh, I love meeting travellers! Tell me everything. No, wait, let me start.'],
      ['Binamu yangu alisafiri mara moja. Alirudi na ndevu na mke!', 'My cousin went travelling once. He came back with a beard and a wife!'],
      ['Marafiki zangu husema naweza kuongea siku nzima. Hawakosei!', "My friends say I could talk all day. They're not wrong!"],
      ['Umekula? Unaonekana una njaa. Kila mtu anaonekana ana njaa kwangu.', 'Have you eaten? You look hungry. Everybody looks hungry to me.'],
      ['Nikwambie siri: mandhari bora mjini ni kutoka kilima nyuma ya soko.', 'Let me tell you a secret: the best view in town is from the hill behind the market.'],
    ],
    bye: [
      ['Kwaheri! Safari njema.', 'Goodbye! Have a good journey.'],
      ['Tunza afya! Furahia safari yako.', 'Look after yourself! Enjoy your trip.'],
      ['Safari njema, rafiki!', 'Safe travels, friend!'],
      ['Kwaheri ya kuonana! Rudi utuone.', 'Goodbye till we meet again! Come back and see us.'],
      ['Nimefurahi kuongea nawe. Jitunze!', 'It was nice talking to you. Take care!'],
      ['Haya, nenda! Kuna mengi ya kuona.', "Go on, then! There's so much to see."],
    ],
  },
  countries: {
    // A bare noun phrase, lower-case unless a proper name, standing as the object of a verb or after *ni* and *kuhusu*.
    TZA: {
      dish: ['ugali', 'ugali (stiff maize porridge)'],
      drink: ['kahawa ya Kilimanjaro', 'Kilimanjaro coffee'],
      festival: ['tamasha la Sauti za Busara', 'the Sauti za Busara music festival'],
      sport: ['mpira wa miguu', 'football'],
      wonder: ['mbuga ya Serengeti', 'the Serengeti'],
      pride: ['Kiswahili', 'Swahili, our language'],
      proverb: ['Haba na haba hujaza kibaba', 'Little by little fills the measure'],
    },
    KEN: {
      dish: ['nyama choma', 'nyama choma (grilled meat)'],
      drink: ['chai ya maziwa', 'milky Kenyan tea'],
      festival: ['Siku ya Jamhuri', 'Jamhuri Day'],
      sport: ['riadha', 'athletics'],
      wonder: ['mbuga ya Maasai Mara', 'the Maasai Mara'],
      pride: ['wanariadha wetu', 'our runners'],
      proverb: ['Haraka haraka haina baraka', 'Hurry, hurry has no blessing'],
    },
  },
};

export default SW;
