import type { Language } from '../phrases.ts';

const TH: Language = {
  locale: 'th',
  name: 'Thai',
  join: ' ',
  compass: [
    'ทางเหนือ', 'ทางตะวันออกเฉียงเหนือ', 'ทางตะวันออก', 'ทางตะวันออกเฉียงใต้',
    'ทางใต้', 'ทางตะวันตกเฉียงใต้', 'ทางตะวันตก', 'ทางตะวันตกเฉียงเหนือ',
  ],
  lines: {
    morning: [
      ['อรุณสวัสดิ์!', 'Good morning!'],
      ['สวัสดีตอนเช้า!', 'Morning, hello!'],
      ['สวัสดี! เช้านี้อากาศสดชื่นดีนะ', 'Hello! The air is fresh this morning.'],
      ['อ้าว สวัสดี! กินข้าวเช้ารึยัง', 'Oh, hello! Had breakfast yet?'],
    ],
    afternoon: [
      ['สวัสดี!', 'Hello!'],
      ['สวัสดีตอนบ่าย!', 'Good afternoon!'],
      ['หวัดดี! กินข้าวรึยัง', 'Hi! Have you eaten?'],
      ['อ้าว สวัสดี! บ่ายนี้แดดดีนะ', 'Oh, hello! Nice sunshine this afternoon.'],
    ],
    evening: [
      ['สวัสดีตอนเย็น!', 'Good evening!'],
      ['หวัดดี! ออกมาเดินเล่นตอนเย็นเหรอ', 'Hi! Out for an evening stroll?'],
      ['สวัสดี! เย็นนี้ลมเย็นสบายเลย', 'Hello! Lovely cool breeze this evening.'],
      ['อ้าว สวัสดีตอนเย็น!', 'Oh, good evening!'],
    ],
    night: [
      ['สวัสดี! ดึกแล้วนะ ว่าไหม', 'Hello! It’s late, isn’t it?'],
      ['อุ๊ย ตกใจหมดเลย! สวัสดี', 'Oops, you made me jump! Hello.'],
      ['สวัสดี! ออกมาเดินตอนดึกเหรอ', 'Hello! Out walking this late?'],
      ['สวัสดี! ป่านนี้ยังไม่นอนอีกเหรอ', 'Hello! Still not in bed at this hour?'],
    ],
    again: [
      ['อ้าว เจอกันอีกแล้ว! สวัสดี', 'Oh, we meet again! Hello.'],
      ['กลับมาอีกแล้วเหรอ ดีใจที่ได้เจอนะ', 'Back again? Nice to see you.'],
      ['สวัสดีอีกรอบ!', 'Hello once more!'],
      ['อ้าว คุณนี่เอง! หาทางเจอไหม', 'Oh, it’s you! Did you find your way?'],
    ],
    welcome: [
      ['ยินดีต้อนรับสู่ {town}!', 'Welcome to {town}!'],
      ['ที่นี่คือ {town} มาเที่ยวเหรอ', 'This is {town}. Here on holiday?'],
      ['มา {town} ครั้งแรกเหรอ', 'First time in {town}?'],
      ['มาเที่ยว {town} วันนี้เหมาะเลยนะ', 'Today is just right for seeing {town}.'],
      ['ยินดีต้อนรับ ๆ! {town} ดีใจที่คุณมานะ', 'Welcome, welcome! {town} is glad you came.'],
      ['แล้วมา {town} ทำอะไรเหรอ', 'So what brings you to {town}?'],
    ],
    capitalHere: [
      ['{town} เป็นเมืองหลวงของประเทศเรา', '{town} is the capital of our country.'],
      ['ที่นี่เมืองหลวงนะ อะไร ๆ ก็เกิดขึ้นที่ {town}', 'This is the capital, you know. Everything happens in {town}.'],
      ['รัฐบาลอยู่ที่ {town} นี่แหละ คนใส่สูทเต็มไปหมด', 'The government is right here in {town}. People in suits everywhere.'],
      ['เป็นเมืองหลวง {town} เลยไม่เคยหลับ', 'Being the capital, {town} never sleeps.'],
    ],
    capitalThere: [
      ['เมืองหลวงของเราคือ {capital} น่าไปเที่ยวนะ', 'Our capital is {capital}. Worth a visit.'],
      ['ไปเที่ยว {capital} มารึยัง นั่นแหละเมืองหลวงของเรา', 'Been to {capital} yet? That’s our capital.'],
      ['คนที่ {capital} คิดว่าตัวเองบริหารประเทศ ก็จริงนั่นแหละ', 'People in {capital} think they run the country. Well, they do.'],
      ['{capital} ใหญ่กว่าก็จริง แต่อยู่ที่นี่สบายกว่าเยอะ', '{capital} is bigger, sure, but life is much easier here.'],
    ],
    big: [
      ['ที่นี่เป็นเมืองใหญ่ หลงทางง่ายมาก!', 'This is a big city. Very easy to get lost!'],
      ['คนเยอะมาก! อยู่ทั้งชีวิตก็ยังรู้จักไม่ครบทุกซอย', 'So many people! You could live here all your life and not know every soi.'],
      ['รถติดสุด ๆ แต่ก็มีอะไรให้ทำตลอด', 'The traffic is terrible, but there’s always something to do.'],
      ['เมืองใหญ่แบบนี้ไม่เคยหยุด ก็ชอบนะ ส่วนใหญ่', 'A big city like this never stops. I like it, mostly.'],
    ],
    middling: [
      ['ไม่ใหญ่ไม่เล็ก กำลังดี', 'Not big, not small. Just right.'],
      ['ใหญ่พอจะมีทุกอย่าง เล็กพอจะเดินเที่ยวได้', 'Big enough to have everything, small enough to walk around.'],
      ['{town} ขนาดกำลังดี วันสองวันก็เที่ยวทั่ว', '{town} is a nice size. A day or two and you’ve seen it all.'],
      ['ใคร ๆ ก็บ่นว่าเงียบ แต่ไม่มีใครย้ายออกสักคน', 'Everyone complains it’s quiet, but not one person moves away.'],
    ],
    small: [
      ['ที่นี่เป็นเมืองเล็ก ๆ ทุกคนรู้จักกันหมด', 'It’s a little town. Everybody knows everybody.'],
      ['เมืองเล็ก จามทีเดียวคนทั้งซอยรู้', 'Small town. Sneeze once and the whole street knows.'],
      ['ที่ {town} ไม่ค่อยมีอะไรเกิดขึ้น แต่เราก็ชอบแบบนี้', 'Not much happens in {town}, and we like it that way.'],
      ['คุณเป็นเรื่องตื่นเต้นที่สุดของสัปดาห์นี้เลย!', 'You’re the most exciting thing all week!'],
    ],
    coast: [
      ['เราอยู่ริมน้ำ ปลาที่นี่อร่อยมาก', 'We live by the water. The fish here is delicious.'],
      ['ไปดูทะเลสิ ไม่เหมือนกันสักวัน', 'Go and look at the sea. It’s never the same two days running.'],
      ['ได้กลิ่นไหม กลิ่นทะเลไง ไม่มีวันเบื่อ', 'Smell that? That’s the sea. You never tire of it.'],
      ['เรือออกตั้งแต่เช้ามืด กลับมาพร้อมปลาสด ๆ', 'The boats go out before dawn and come back with fresh fish.'],
    ],
    inland: [
      ['ที่นี่ไกลทะเล แต่ธรรมชาติสวยมาก', 'The sea is far from here, but the countryside is beautiful.'],
      ['ที่นี่ไม่มีชายหาดหรอก แต่ดูทุ่งนาสิ', 'No beach here, but look at the rice fields.'],
      ['ทะเลเหรอ บอกตรง ๆ ไม่เคยเห็นเลย ไกลมาก', 'The sea? Honestly, never seen it. It’s very far.'],
      ['ที่นี่ดินคือทุกอย่าง ดินดี คนก็ดี', 'Here the soil is everything. Good soil, good people.'],
    ],
    high: [
      ['ที่นี่อยู่สูงนะ ค่อย ๆ เดิน อากาศเบาบาง', 'It’s high up here. Walk slowly, the air is thin.'],
      ['อยู่บนดอยแบบนี้ วิวสวยที่สุดแล้ว', 'Up in the hills like this, the view is the best thing.'],
      ['อยู่ที่นี่ขาแข็งแรงแน่ ไม่มีตรงไหนเรียบเลย', 'Live here and your legs get strong. Nothing is flat.'],
      ['ระวังเหนื่อยนะ ต้องใช้เวลาปรับตัวกับภูเขา', 'Careful not to wear yourself out. The mountains take getting used to.'],
    ],
    snowy: [
      ['หิมะตกเก้าเดือน อีกสามเดือนก็บ่นเรื่องโคลน', 'Snow nine months a year. The other three, we complain about mud.'],
      ['แถวนี้ขาวไปหมด รองเท้าคู่นั้นไม่ไหวหรอก', 'Everything’s white round here. Those shoes won’t cut it.'],
      ['ตอนหิมะเพิ่งตก เงียบจนได้ยินเสียงหายใจตัวเอง', 'When snow has just fallen, it’s so quiet you hear yourself breathe.'],
      ['หนาวแบบนี้ต้องกินอะไรร้อน ๆ', 'Cold like this calls for something hot to eat.'],
    ],
    forest: [
      ['ป่าแถวนี้กว้างสุดลูกหูลูกตา อย่าออกนอกทางนะ', 'The forest here goes as far as the eye can see. Don’t leave the path.'],
      ['ลองเดินเข้าป่าดูสิ สมองโล่งเลย', 'Try a walk in the forest. It clears your head.'],
      ['หน้าฝนคนแถวนี้เข้าป่าไปเก็บเห็ดกัน', 'In the rainy season people here go into the forest for mushrooms.'],
      ['ต้นไม้ ต้นไม้ แล้วก็ต้นไม้ ไม่อยากอยู่ที่อื่นแล้ว', 'Trees, trees and more trees. Wouldn’t want to live anywhere else.'],
    ],
    desert: [
      ['แถวนี้มีแต่ทรายสุดลูกหูลูกตา', 'Round here it’s sand as far as the eye can see.'],
      ['ดื่มน้ำเยอะ ๆ นะ ทะเลทรายไม่ปรานีใคร', 'Drink lots of water. The desert shows no mercy.'],
      ['กลางคืนในทะเลทรายหนาวนะ ไม่มีใครเชื่อหรอก', 'Desert nights are cold, you know. Nobody believes it.'],
      ['คืนนี้รอดูดาวสิ ที่นี่ดาวเป็นล้านดวง', 'Wait for the stars tonight. There are millions here.'],
    ],
    plains: [
      ['ราบไปหลายกิโล เห็นฝนมาตั้งแต่ไกล', 'Flat for miles. You see the rain coming from far off.'],
      ['ฟ้ากว้าง ไม่มีอะไรกั้นลมเลย', 'Wide sky, nothing to stop the wind.'],
      ['ทุ่งหญ้าเลี้ยงสัตว์ทั้งนั้น ระวังฝูงวัวนะ', 'It’s all grazing land. Watch out for the herds.'],
      ['หญ้าเขียวไปสุดขอบฟ้า เหมือนทะเลสีเขียว', 'Green grass to the horizon, like a green sea.'],
    ],
    tropical: [
      ['ที่นี่ปลูกอะไรก็ขึ้น ปักกิ่งไม้ก็เป็นต้น', 'Anything grows here. Stick a twig in and it’s a tree.'],
      ['ฝนมาทีก็ตกหนัก แล้วก็หยุดไปเฉย ๆ', 'When the rain comes it pours, then just stops.'],
      ['ลองผลไม้ที่ตลาดสิ รับรองไม่เคยกินอะไรแบบนี้', 'Try the fruit at the market. You’ve never tasted anything like it.'],
      ['เขียวทั้งปี หน้าหนาวเหรอ อะไรคือหน้าหนาว', 'Green all year. Winter? What’s winter?'],
    ],
    landmark: [
      ['ต้องไปดู {landmark} ให้ได้นะ! อยู่ห่างจากที่นี่ไป{dir}ประมาณ {km} กม.', 'You must go and see {landmark}! It’s about {km} km from here, {dir}.'],
      ['{landmark} ห้ามพลาดนะ! ไป{dir}ประมาณ {km} กม.', 'Don’t miss {landmark}! About {km} km {dir}.'],
      ['ใคร ๆ ก็ไป {landmark} กัน อยู่{dir}ราว {km} กม.', 'Everybody goes to {landmark}. It’s around {km} km {dir}.'],
      ['ถ้าว่าง ไป {landmark} สิ อยู่{dir} {km} กม. คนมาจากทั่วสารทิศ', 'If you have time, go to {landmark}, {km} km {dir}. People come from all over.'],
    ],
    landmarkNear: [
      ['{landmark} อยู่ใกล้ ๆ นี่เอง หาไม่ยากหรอก!', '{landmark} is just nearby. It’s not hard to find!'],
      ['ไป {landmark} มารึยัง อยู่แค่หัวมุมเอง', 'Been to {landmark} yet? It’s just round the corner.'],
      ['เห็น {landmark} ทุกวันก็ยังทึ่งทุกครั้ง', 'We see {landmark} every day and it still amazes us every time.'],
      ['{landmark} อยู่ตรงนี้เอง ไปแต่เช้าก่อนคนเยอะนะ', '{landmark} is right here. Go early, before the crowds.'],
    ],
    plane: [
      ['มีเครื่องบินลำเล็กจอดอยู่ในทุ่ง{dir} ถ้าขับเป็นนะ!', 'There’s a little plane parked in a field {dir}, if you can fly!'],
      ['มีคนทิ้งเครื่องบินไว้{dir} อยากบินไหม', 'Someone left a plane {dir}. Fancy a flight?'],
      ['ขับเครื่องบินเป็นไหม มีลำนึงรออยู่{dir}', 'Can you fly? There’s one waiting {dir}.'],
      ['อยากดูทุกอย่างจากข้างบน มีเครื่องบินอยู่{dir}นะ', 'If you want to see it all from above, there’s a plane {dir}.'],
    ],
    balloon: [
      ['มีบอลลูนอยู่ในทุ่ง{dir}! คิดดูสิวิวจะสวยแค่ไหน', 'There’s a balloon in a field {dir}! Imagine the view.'],
      ['เคยนั่งบอลลูนไหม มีลูกนึงอยู่{dir}', 'Ever been up in a balloon? There’s one {dir}.'],
      ['บอลลูนลอยขึ้นจากทุ่ง{dir} อย่างกับเวทมนตร์', 'A balloon rises from the field {dir}. Like magic.'],
      ['อยากลองนั่งบอลลูน{dir}มานานแล้ว แต่กลัว!', 'I’ve wanted to ride the balloon {dir} for ages, but I’m scared!'],
    ],
    boat: [
      ['มีเรืออยู่ริมน้ำ{dir} ถ้าอยากออกไปเที่ยว', 'There’s a boat by the water {dir}, if you want to go out.'],
      ['ชอบทะเลใช่ไหม มีเรืออยู่{dir} แต่เอามาคืนด้วยนะ!', 'Like the sea? There’s a boat {dir}. Just bring it back!'],
      ['มีเรือผูกไว้{dir} จากตรงนี้ไปได้ทุกที่', 'A boat is tied up {dir}. From here you can go anywhere.'],
      ['เอาเรือ{dir}ไปดูชายฝั่งจากในน้ำสิ', 'Take the boat {dir} and see the coast from the water.'],
    ],
    hot: [
      ['วันนี้ร้อนจัง! หาที่ร่มหลบแดดนะ', 'So hot today! Find some shade.'],
      ['โอ้โห ร้อนมาก! ดื่มน้ำหน่อยนะ', 'Wow, it’s hot! Drink some water.'],
      ['ร้อนขนาดนี้ ทำอะไรไม่ได้นอกจากนั่งในร่ม', 'In this heat there’s nothing to do but sit in the shade.'],
      ['ร้อนจนหมายังไม่ยอมออกจากบ้าน', 'So hot even the dogs won’t leave the house.'],
      ['ร้อนเนอะ นี่ถือว่าเย็นแล้วนะสำหรับที่นี่!', 'Hot, huh? This counts as cool around here!'],
    ],
    cold: [
      ['บรื๋อ วันนี้หนาวจัง! ใส่เสื้อหนา ๆ นะ', 'Brr, it’s cold today! Wrap up warm.'],
      ['หนาวจะแข็งแล้ว! ถุงมือล่ะ', 'I’m freezing solid! Where are your gloves?'],
      ['หนาวจนจมูกชาไปหมด', 'So cold my nose has gone numb.'],
      ['แค่นี้ยังไม่เท่าไหร่ รอลมมาก่อนเถอะ', 'This is nothing yet. Wait till the wind comes.'],
      ['หาอะไรร้อน ๆ ดื่มสิ ช่วยได้เยอะ', 'Get something hot to drink. It helps a lot.'],
    ],
    mild: [
      ['วันนี้อากาศดีจังเลย', 'What lovely weather today.'],
      ['ไม่ร้อนไม่หนาว วันดี ๆ แบบนี้หายาก', 'Not hot, not cold. Good days like this are rare.'],
      ['วันแบบนี้ต้องออกมาข้างนอก', 'A day like this, you have to be outside.'],
      ['อากาศดีมาก! ขอให้เป็นแบบนี้นาน ๆ', 'Beautiful weather! May it last a long time.'],
      ['วันแบบนี้แหละที่ทำให้อยากอยู่ที่นี่', 'Days like this are what make you want to live here.'],
    ],
    late: [
      ['ดึกแล้ว ตอนกลางคืนถนนเงียบสงบ', 'It’s late. The streets are quiet at night.'],
      ['ป่านนี้มีแต่แมวที่ยังเดินเล่น แล้วก็เรานี่แหละ!', 'At this hour only the cats are out. And us!'],
      ['ป่านนี้ควรนอนกันได้แล้วนะ ทำไมยังไม่นอนล่ะ', 'We should all be in bed by now. Why are you still up?'],
      ['ดูดาวสิ! ตรงนี้เห็นชัดที่สุด', 'Look at the stars! You see them clearest from here.'],
    ],
    early: [
      ['ตื่นเช้าจัง! ช่วงที่ดีที่สุดของวันเลย', 'Up so early! The best part of the day.'],
      ['ร้านโจ๊กเพิ่งเปิด ตามกลิ่นไปเลย!', 'The rice porridge stall has just opened. Follow the smell!'],
      ['ตื่นเช้าเหรอ เมืองยังไม่ตื่นเลย', 'Early riser? The town isn’t even awake yet.'],
      ['ชอบตอนเช้าที่นี่ ก่อนเสียงรถจะเริ่ม', 'I love the mornings here, before the traffic starts.'],
    ],
    country: [
      ['ประเทศ{country}สวยนะ ขอให้สนุกนะ!', '{country} is a beautiful country. Have fun!'],
      ['เที่ยวประเทศ{country}สนุกไหม', 'Are you enjoying your trip round {country}?'],
      ['ถ้ามีเวลา เที่ยวให้ทั่วประเทศ{country}นะ แต่ละที่ไม่เหมือนกันเลย', 'If you have time, travel all over {country}. Every place is different.'],
      ['ประเทศ{country}ใครมาก็ติดใจ', 'Whoever comes to {country} falls for it.'],
    ],
    dish: [
      ['มาถึงนี่แล้วต้องลอง {dish} นะ', 'Now that you’re here, you have to try {dish}.'],
      ['กิน {dish} รึยัง ยังเหรอ ต้องลองเลย!', 'Have you had {dish}? Not yet? You must!'],
      ['ไม่มีใครทำ {dish} อร่อยเท่าแม่อีกแล้ว', 'Nobody makes {dish} as good as Mum.'],
      ['หิวเมื่อไหร่ สั่ง {dish} เลย ไม่ผิดหวังแน่', 'When you’re hungry, order {dish}. You won’t be disappointed.'],
    ],
    drink: [
      ['ก่อนไปลองดื่ม {drink} หน่อย คนที่นี่ดื่มกันทุกคน', 'Try some {drink} before you go. Everyone here drinks it.'],
      ['เหนื่อย ๆ มาได้ {drink} สักแก้ว ฟินที่สุด', 'A glass of {drink} after a tiring day is pure bliss.'],
      ['ยังไม่ได้ลอง {drink} ถือว่ายังมาไม่ถึง', 'If you haven’t tried {drink}, you haven’t really arrived.'],
      ['สั่ง {drink} แบบคนท้องถิ่น แม่ค้าจะชอบคุณเลย', 'Order {drink} like a local and the vendor will love you.'],
    ],
    festival: [
      ['ช่วง {festival} กลับมาอีกนะ สนุกมาก!', 'Come back for {festival}. It’s great fun!'],
      ['ช่วงที่ดีที่สุดคือ {festival} ทั้งประเทศฉลองกันหมด', 'The best time is {festival}. The whole country celebrates.'],
      ['เคยได้ยิน {festival} ไหม ต้องชอบแน่', 'Ever heard of {festival}? You’d love it.'],
      ['รอ {festival} ทุกปีเลย นับวันรอ', 'I wait for {festival} every year, counting the days.'],
    ],
    sport: [
      ['ที่นี่ใคร ๆ ก็คลั่ง {sport}', 'Here everybody is crazy about {sport}.'],
      ['ชอบ {sport} ไหม คนที่นี่บ้ากันมาก', 'Do you like {sport}? People here are mad about it.'],
      ['วันแข่ง ทั้งเมืองพูดแต่เรื่อง {sport}', 'On match day the whole town talks of nothing but {sport}.'],
      ['ทั้งบ้านชอบ {sport} ส่วนยายนั่งเชียร์เสียงดังที่สุด', 'The whole family loves {sport}. Grandma cheers the loudest.'],
    ],
    wonder: [
      ['ถ้ามีเวลา ไปดู {wonder} นะ ไม่มีวันลืม', 'If you have time, go and see {wonder}. You’ll never forget it.'],
      ['เคยเห็น {wonder} ไหม ที่ไหนในโลกก็ไม่เหมือน', 'Have you seen {wonder}? Nowhere in the world is like it.'],
      ['ชาตินี้ต้องไป {wonder} สักครั้ง', 'In this life you have to go to {wonder} once.'],
      ['ตอนเด็ก ๆ เคยไป {wonder} ยังฝันถึงอยู่เลย', 'I went to {wonder} as a kid. I still dream about it.'],
    ],
    pride: [
      ['เราภูมิใจใน {pride} มาก', 'We’re very proud of {pride}.'],
      ['อย่ากลับก่อนได้รู้จัก {pride} นะ นี่แหละตัวตนของเรา', 'Don’t go home before you get to know {pride}. That’s who we are.'],
      ['รู้ไหมอะไรทำให้เราภูมิใจ {pride} ไง', 'Know what makes us proud? {pride}, of course.'],
      ['ถามใครเรื่อง {pride} ก็ได้ คุยได้เป็นชั่วโมง', 'Ask anyone about {pride}, they’ll talk for hours.'],
    ],
    proverb: [
      ['คนไทยมีคำพูดว่า “{proverb}”', 'We Thais have a saying: “{proverb}”'],
      ['ยายชอบพูดเสมอว่า “{proverb}”', 'Grandma always used to say: “{proverb}”'],
      ['มีสุภาษิตว่า “{proverb}”', 'There’s a proverb: “{proverb}”'],
      ['เคยได้ยินไหม “{proverb}”', 'Ever heard this one? “{proverb}”'],
    ],
    chat: [
      ['มาจากไหนเหรอ ไม่ใช่คนแถวนี้ใช่ไหม', 'Where are you from? Not from around here, are you?'],
      ['ค่อย ๆ เดินดูนะ ที่นี่มีอะไรให้ดูเยอะเลย', 'Take your time looking round. There’s plenty to see here.'],
      ['มาคนเดียวเหรอ ใจกล้าจัง', 'Travelling alone? How brave.'],
      ['ดูเหมือนเดินมาไกลนะ', 'Looks like you’ve walked a long way.'],
      ['ถ้าหลงก็ถามได้เลย คนที่นี่ใจดี', 'If you get lost, just ask. People here are kind.'],
      ['ไปมาที่ไหนแล้วบ้าง ที่ไหนดีที่สุด', 'Where have you been so far? Which was the best?'],
      ['อยากไปเที่ยวบ้างจัง สักวันนะ', 'I’d love to travel too. Someday.'],
      ['หิวไหม แถวนี้มีร้านข้าวมันไก่อร่อยนะ', 'Hungry? There’s a great chicken rice place round here.'],
    ],
    childGreet: [
      ['หวัดดี!', 'Hi!'],
      ['สวัสดี! เป็นใครอะ', 'Hello! Who are you?'],
      ['หวัดดี! ตัวสูงจัง!', 'Hi! You’re so tall!'],
      ['สวัสดี ๆ!', 'Hello, hello!'],
    ],
    childChat: [
      ['วิ่งเร็วมากเลยนะ! อยากดูไหม เดี๋ยวก่อน', 'I run super fast! Want to see? Later.'],
      ['เป็นนักท่องเที่ยวเหรอ เพื่อนบอกว่านักท่องเที่ยวรวย', 'Are you a tourist? My friend says tourists are rich.'],
      ['เมื่อวานฟันหลุด! ดูสิ! อ้าว มองไม่เห็นเหรอ', 'A tooth came out yesterday! Look! Oh, can’t you see it?'],
      ['แม่บอกว่าห้ามคุยกับคนแปลกหน้า แต่ดูใจดีนะ', 'Mum says don’t talk to strangers. But you look kind.'],
      ['มีหมาไหม อยากได้หมาจัง', 'Do you have a dog? I really want a dog.'],
      ['โตขึ้นจะขับเครื่องบินรอบโลก!', 'When I grow up I’ll fly a plane round the world!'],
      ['รู้จักเกมอะไรบ้าง หนูรู้เยอะเลย', 'What games do you know? I know loads.'],
    ],
    childBye: [
      ['บ๊ายบาย!', 'Bye bye!'],
      ['บาย! มาเล่นอีกนะ!', 'Bye! Come and play again!'],
      ['ต้องไปแล้ว แม่เรียก!', 'Gotta go, Mum’s calling!'],
      ['ไว้เจอกันใหม่นะ!', 'See you next time!'],
    ],
    grumpyGreet: [
      ['หืม มีอะไร', 'Hm? What is it?'],
      ['ว่าไง มีธุระอะไร', 'Well? What do you want?'],
      ['เฮ้อ นักท่องเที่ยวอีกแล้ว', 'Sigh. Another tourist.'],
      ['อืม สวัสดี ก็ได้', 'Hm. Hello, I suppose.'],
    ],
    grumpyChat: [
      ['เมื่อก่อนดีกว่านี้ ก่อนคนจะแห่มาเที่ยว', 'It was better before, before everyone came flocking here.'],
      ['ของแพงขึ้นเท่าตัวแล้ว', 'Everything costs twice as much now.'],
      ['อย่ายืนขวางทางเท้าสิ คนเขาอยู่กันนะ', 'Don’t block the pavement. People live here.'],
      ['เด็กสมัยนี้ ก้มหน้าดูมือถือทั้งวัน', 'Kids these days, heads down in their phones all day.'],
      ['ไม่รู้คนมาที่นี่ทำไม ไม่มีอะไรให้ดูเลย', 'Don’t know why people come here. There’s nothing to see.'],
    ],
    grumpyBye: [
      ['เอาล่ะ ไปได้แล้ว', 'Right. You can go now.'],
      ['ไม่รั้งไว้หรอก', 'I won’t hold you up.'],
      ['อืม ลาก่อน', 'Hm. Goodbye.'],
      ['เดินดี ๆ ล่ะ แล้วปิดประตูรั้วด้วย', 'Watch your step. And close the gate.'],
    ],
    elderChat: [
      ['สมัยยังเด็ก แถวนี้เป็นทุ่งนาทั้งนั้น', 'When I was young, this was all rice fields.'],
      ['อยู่ที่นี่มาทั้งชีวิต แปดสิบปี! เชื่อไหม', 'I’ve lived here all my life. Eighty years! Can you believe it?'],
      ['สมัยก่อนเดินไปไหนมาไหนกันหมด เห็นเดินแบบนี้ดีแล้ว!', 'In the old days everyone walked everywhere. Good to see you on foot!'],
      ['หลาน ๆ ไปอยู่เมืองนอกกันหมด โทรมาทุกวันอาทิตย์', 'The grandchildren all live abroad. They call every Sunday.'],
      ['อะไร ๆ ก็เปลี่ยนเร็ว แต่ตรอกเก่า ๆ ยังเหมือนเดิม', 'Everything changes so fast, but the old alleys stay the same.'],
    ],
    chattyChat: [
      ['ชอบเจอนักเดินทางจัง! เล่าให้ฟังหน่อย เอ๊ะ เดี๋ยว ขอเล่าก่อน', 'I love meeting travellers! Tell me everything. Oh wait, let me go first.'],
      ['ลูกพี่ลูกน้องเคยไปเที่ยวครั้งนึง กลับมามีทั้งหนวดเคราทั้งแฟน!', 'My cousin went travelling once. Came back with a beard and a sweetheart!'],
      ['เพื่อน ๆ บอกว่าคุยได้ทั้งวัน ก็จริงแหละ!', 'My friends say I can talk all day. It’s true!'],
      ['กินข้าวรึยัง ดูหิว ๆ นะ เห็นใครก็ดูหิวไปหมด', 'Have you eaten? You look hungry. Everyone looks hungry to me.'],
      ['บอกความลับให้ วิวที่สวยที่สุดในเมืองอยู่บนเนินหลังวัด', 'Here’s a secret: the best view in town is from the hill behind the temple.'],
    ],
    bye: [
      ['ลาก่อน! เดินทางปลอดภัยนะ', 'Goodbye! Travel safely.'],
      ['ดูแลตัวเองนะ เที่ยวให้สนุก!', 'Take care, and enjoy your trip!'],
      ['โชคดีนะ!', 'Good luck!'],
      ['แล้วแวะมาอีกนะ!', 'Drop by again!'],
      ['ดีใจที่ได้คุยด้วย รักษาสุขภาพนะ!', 'Nice talking to you. Look after yourself!'],
      ['ไปเถอะ มีอะไรให้ดูอีกเยอะ!', 'Off you go! There’s plenty more to see!'],
    ],
  },
  countries: {
    // Each fact is a bare noun phrase; Thai does not inflect, and templates set it off with a space.
    THA: {
      dish: ['ต้มยำกุ้ง', 'tom yum goong'],
      drink: ['ชาไทย', 'Thai iced tea'],
      festival: ['สงกรานต์', 'Songkran'],
      sport: ['มวยไทย', 'Muay Thai'],
      wonder: ['ดอยอินทนนท์', 'Doi Inthanon'],
      pride: ['น้ำใจของคนไทย', 'Thai kindness'],
      proverb: ['น้ำขึ้นให้รีบตัก', 'When the water rises, hurry to scoop it up'],
    },
  },
};

export default TH;
