import type { Language } from '../phrases.ts';

/**
 * Filipino as it is spoken to a stranger in the street: *ka* and *mo* from a
 * grown-up, *po* and *kayo* from a child, and the English words everybody
 * uses where everybody uses them. A name stands after *ang*, *ng* or *sa*,
 * which never change, and never before a linker (*na*, *-ng*), which does.
 */
const TL: Language = {
  locale: 'fil',
  name: 'Filipino',
  join: ' ',
  compass: [
    'sa hilaga', 'sa hilagang-silangan', 'sa silangan', 'sa timog-silangan',
    'sa timog', 'sa timog-kanluran', 'sa kanluran', 'sa hilagang-kanluran',
  ],
  lines: {
    morning: [
      ['Magandang umaga!', 'Good morning!'],
      ['Magandang umaga! Nagkape ka na?', 'Good morning! Had your coffee yet?'],
      ['Uy, hello! Magandang umaga sa iyo.', 'Oh, hello! Good morning to you.'],
      ['Umaga na! Ang ganda ng simula ng araw, ano?', "Morning! Lovely start to the day, isn't it?"],
    ],
    afternoon: [
      ['Magandang hapon!', 'Good afternoon!'],
      ['Magandang tanghali!', 'Good day!'],
      ['Uy, hello!', 'Oh, hello!'],
      ['Uy, kumusta! Ang sarap ng hapon.', 'Hey, how are you! Lovely afternoon.'],
    ],
    evening: [
      ['Magandang gabi!', 'Good evening!'],
      ['Gabi na! Masarap maglakad ngayon.', "Evening! It's nice for a walk now."],
      ['Uy, magandang gabi sa iyo.', 'Oh, good evening to you.'],
      ['Kumusta! Kumain ka na ba ng hapunan?', 'Hello! Have you had supper yet?'],
    ],
    night: [
      ["Magandang gabi! Gabi na, 'di ba?", "Good evening! It's late, isn't it?"],
      ['Ay! Nagulat ako sa iyo. Hello!', 'Oh! You startled me. Hello!'],
      ['Hello! Naglalakad ka pa sa ganitong oras?', 'Hello! Still out walking at this hour?'],
      ['Magandang gabi! O umaga na ba?', 'Good evening! Or is it morning already?'],
    ],
    again: [
      ['Uy, ikaw ulit! Hello!', 'Oh, you again! Hello!'],
      ['Bumalik ka? Masaya akong makita ka ulit.', 'Back again? Happy to see you again.'],
      ['Hello ulit!', 'Hello again!'],
      ['Nagkita na naman tayo! Nag-iikot ka pa rin?', 'We meet again! Still looking around?'],
      ['Ikaw pala! Nahanap mo na ba ang daan?', "Oh, it's you! Did you find your way?"],
    ],
    welcome: [
      ['Maligayang pagdating sa {town}!', 'Welcome to {town}!'],
      ['Ito ang {town}. Namamasyal ka ba?', 'This is {town}. Are you sightseeing?'],
      ['Unang beses mo ba sa {town}?', 'Is this your first time in {town}?'],
      ['Ang ganda ng araw para makita ang {town}.', 'What a lovely day to see {town}.'],
      ['Tuloy, tuloy! Welcome sa {town}!', 'Come in, come in! Welcome to {town}!'],
      ['Ano ang nagdala sa iyo sa {town}?', 'What brings you to {town}?'],
    ],
    capitalHere: [
      ['Ang {town} ang kabisera ng aming bansa.', '{town} is the capital of our country.'],
      ['Kabisera ito, alam mo. Lahat nangyayari dito sa {town}.', 'This is the capital, you know. Everything happens here in {town}.'],
      ['Nandito sa {town} ang gobyerno. Maraming importanteng tao na naka-amerikana.', 'The government is here in {town}. Lots of important people in suits.'],
      ['Dahil kabisera, hindi natutulog ang {town}.', 'Being the capital, {town} never sleeps.'],
    ],
    capitalThere: [
      ['Ang aming kabisera ay {capital}. Sulit itong puntahan.', "Our capital is {capital}. It's worth a visit."],
      ['Nakapunta ka na ba sa {capital}? Iyon ang kabisera namin.', 'Have you been to {capital}? That is our capital.'],
      ['Akala ng mga tao sa {capital}, sila ang nagpapatakbo ng bansa. Totoo naman.', 'People in {capital} think they run the country. Well, they do.'],
      ['Mas malaki ang {capital}, pero mas gusto kong tumira dito.', "{capital} is bigger, but I'd rather live here."],
    ],
    big: [
      ['Malaking lungsod ito. Madaling maligaw dito!', "This is a big city. It's easy to get lost here!"],
      ['Ang traffic dito, grabe! Pero laging may nangyayari.', 'The traffic here, honestly! But there is always something going on.'],
      ['Ang daming tao! Kahit buong buhay ka rito, hindi mo makikilala lahat ng kalye.', 'So many people! Even after a lifetime here you would not know every street.'],
      ['Hindi tumitigil ang ganito kalaking lungsod. Gusto ko, kadalasan.', 'A city this big never stops. I like it, mostly.'],
    ],
    middling: [
      ['Hindi malaki, hindi maliit. Sakto lang.', 'Not big, not small. Just right.'],
      ['Kumpleto na, pero kaya pang lakarin.', 'It has everything, and you can still walk it.'],
      ['Tamang laki lang ang {town}. Isa o dalawang araw, makikita mo na lahat.', "{town} is just the right size. In a day or two you'll have seen it all."],
      ['Reklamo ng lahat, masyadong tahimik. Pero wala namang umaalis.', 'Everybody complains it is too quiet. But nobody ever leaves.'],
    ],
    small: [
      ['Maliit na lugar ito. Magkakakilala ang lahat dito.', 'This is a small place. Everybody knows everybody here.'],
      ['Walang masyadong nangyayari sa {town}, at gusto namin iyon.', 'Not much happens in {town}, and we like it that way.'],
      ['Maliit na bayan. Bumahing ka lang, alam na ng buong kalye.', 'A small town. Just sneeze and the whole street knows.'],
      ['Ikaw na ang pinakamalaking balita rito ngayong linggo!', "You're the biggest news here this week!"],
    ],
    coast: [
      ['Nakatira kami sa tabi ng tubig. Napakasarap ng isda rito.', 'We live by the water. The fish here is delicious.'],
      ['Naaamoy mo? Dagat iyan. Hindi ka magsasawa.', "Smell that? That's the sea. You never tire of it."],
      ['Maagang pumapalaot ang mga mangingisda at bumabalik na may sariwang isda.', 'The fishermen head out early and come back with fresh fish.'],
      ['Panoorin mo ang paglubog ng araw sa dagat. Ang ganda!', 'Watch the sun set over the sea. So beautiful!'],
    ],
    inland: [
      ['Malayo kami sa dagat, pero maganda ang lugar dito.', 'We are far from the sea, but it is lovely here.'],
      ['Walang beach dito, pasensya na. Pero tingnan mo ang mga palayan!', 'No beach here, sorry. But look at the rice fields!'],
      ['Dagat? Sa totoo lang, bihira kong makita. Malayo kasi.', 'The sea? Honestly, I rarely see it. It is far.'],
      ['Dito, lupa ang lahat. Mataba ang lupa, mababait ang tao.', 'Out here the land is everything. Rich soil, kind people.'],
    ],
    high: [
      ['Mataas tayo rito. Dahan-dahan lang, manipis ang hangin.', "We're high up here. Take it slowly, the air is thin."],
      ['Malamig ang hangin dito sa bundok. Ang ganda ng tanawin!', 'The air is cool up here in the mountains. What a view!'],
      ['Titibay ang binti mo rito. Walang patag!', 'Your legs will get strong here. Nothing is flat!'],
      ['Tuwing umaga, bumababa ang hamog hanggang kalsada. Parang nasa ulap ka.', 'Every morning the mist comes down to the road. Like being in the clouds.'],
    ],
    snowy: [
      ['Puro yelo at niyebe dito! Ang lamig talaga.', 'Nothing but ice and snow here! So cold.'],
      ['Lahat puti rito. Kailangan mo ng mas makapal na sapatos.', 'Everything is white here. You need thicker shoes.'],
      ['Niyebe? Oo, niyebe. Hindi rin ako makapaniwala.', "Snow? Yes, snow. I can't believe it either."],
      ['Kapag bagong bagsak ang niyebe, sobrang tahimik.', 'When the snow has just fallen, it is so quiet.'],
    ],
    forest: [
      ['Walang katapusan ang gubat dito. Huwag kang lalayo sa daan!', "The forest here never ends. Don't stray from the path!"],
      ['Maglakad ka sa gubat. Nakakagaan ng isip.', 'Take a walk in the forest. It lightens the mind.'],
      ['Pakinggan mo ang mga ibon sa gubat tuwing umaga. Ang ingay!', 'Listen to the birds in the forest in the morning. What a racket!'],
      ['Puno, puno, at puno pa. Pero dito ko gustong tumira.', 'Trees, trees and more trees. But this is where I want to live.'],
    ],
    desert: [
      ['Puro buhangin dito hanggang tanaw.', 'Nothing but sand here as far as you can see.'],
      ['Uminom ka ng maraming tubig. Walang awa ang disyerto.', 'Drink plenty of water. The desert has no mercy.'],
      ['Malamig ang gabi sa disyerto, alam mo ba? Walang naniniwala.', 'Desert nights are cold, did you know? Nobody believes it.'],
      ['Hintayin mo ang gabi. Milyon-milyon ang bituin dito!', 'Wait for the night. There are millions of stars here!'],
    ],
    plains: [
      ['Patag hanggang tanaw. Kita mo na ang ulan kahit malayo pa.', 'Flat as far as you can see. You can spot the rain while it is still far off.'],
      ['Malawak ang langit dito. Walang humaharang sa hangin.', 'The sky is wide here. Nothing stops the wind.'],
      ['Magandang pastulan ito. Ingat sa mga kalabaw!', 'This is good grazing land. Watch out for the water buffalo!'],
      ['Walang katapusan ang damuhan. Parang berdeng dagat.', 'The grass never ends. Like a green sea.'],
    ],
    tropical: [
      ['Lahat tumutubo rito. Magtanim ka ng patpat, magiging puno.', 'Everything grows here. Plant a stick and it becomes a tree.'],
      ['Kapag umulan dito, buhos talaga. Tapos biglang titigil.', 'When it rains here, it pours. Then it suddenly stops.'],
      ['Tikman mo ang prutas sa palengke. Mangga, lanzones, rambutan!', 'Try the fruit at the market. Mango, lanzones, rambutan!'],
      ['Dalawa lang ang panahon dito: tag-init at tag-ulan.', 'There are only two seasons here: the hot one and the rainy one.'],
    ],
    landmark: [
      ['Huwag palampasin ang {landmark}! Mga {km} km ito {dir}.', "Don't miss {landmark}! It's about {km} km {dir}."],
      ['Nakita mo na ba ang {landmark}? Mga {km} km {dir}, sulit ang lakad.', "Have you seen {landmark}? About {km} km {dir}, worth every step."],
      ['Pumupunta ang lahat sa {landmark}. Mga {km} km ito {dir}.', "Everybody goes to {landmark}. It's about {km} km {dir}."],
      ['Kung may libre kang araw, nandiyan ang {landmark}, {km} km {dir}.', 'If you have a free day, there is {landmark}, {km} km {dir}.'],
    ],
    landmarkNear: [
      ['Napakalapit lang ng {landmark}. Hindi mo ito malalampasan!', "{landmark} is very close. You can't miss it!"],
      ['Napuntahan mo na ba ang {landmark}? Nasa kanto lang!', "Have you been to {landmark}? It's just round the corner!"],
      ['Araw-araw kong nakikita ang {landmark}, pero namamangha pa rin ako.', 'I see {landmark} every day, and I am still amazed.'],
      ['Puntahan mo ang {landmark}, nandito lang. Agahan mo, bago dumami ang tao.', "Go and see {landmark}, it's right here. Go early, before the crowds."],
    ],
    plane: [
      ['May maliit na eroplano sa bukid {dir}, kung marunong kang magpalipad!', "There's a little plane in a field {dir}, if you can fly!"],
      ['May nag-iwan ng eroplano sa bukid {dir}. Gusto mong lumipad?', 'Somebody left a plane in a field {dir}. Fancy a flight?'],
      ['Marunong ka bang magpalipad? May eroplanong naghihintay {dir}.', "Can you fly? There's a plane waiting {dir}."],
      ['Kung gusto mong makita lahat mula sa itaas, may eroplano {dir}.', "If you want to see it all from above, there's a plane {dir}."],
    ],
    balloon: [
      ['May hot air balloon sa bukid {dir}! Isipin mo ang tanawin.', "There's a hot-air balloon in a field {dir}! Imagine the view."],
      ['Nakasakay ka na ba sa hot air balloon? May isa {dir}.', 'Have you ever ridden in a hot-air balloon? There is one {dir}.'],
      ['Umaangat ang balloon mula sa bukid {dir}. Parang mahika.', 'The balloon rises from the field {dir}. Like magic.'],
      ['Matagal ko nang gustong sumakay sa balloon {dir}. Takot lang ako!', "I've wanted to ride the balloon {dir} for ages. I'm just scared!"],
    ],
    boat: [
      ['May bangka sa tabi ng tubig {dir}, kung gusto mong pumalaot.', "There's a boat by the water {dir}, if you want to head out."],
      ['Mahilig ka sa dagat? May bangka {dir}. Ibalik mo lang, ha!', "Love the sea? There's a boat {dir}. Just bring it back, okay!"],
      ['May nakataling bangka {dir}. Kahit saan puwede kang pumunta mula rito.', 'A boat is tied up {dir}. From here you could go anywhere.'],
      ['Sumakay ka sa bangka {dir} at tingnan ang baybayin mula sa dagat.', 'Take the boat {dir} and see the coast from the sea.'],
    ],
    hot: [
      ['Ang init ngayon! Humanap ka ng lilim.', "It's hot today! Find some shade."],
      ['Grabe ang init! Uminom ka ng tubig, mukhang nauuhaw ka.', 'What heat! Drink some water, you look thirsty.'],
      ['Sa init na ito, upo lang sa lilim ang kaya.', 'In this heat, all you can do is sit in the shade.'],
      ['Sa ganitong init, pati aso nasa loob ng bahay.', 'In heat like this, even the dogs stay indoors.'],
      ['Mainit, ano? Halo-halo ang sagot diyan!', "Hot, isn't it? Halo-halo is the answer to that!"],
    ],
    cold: [
      ['Brr, ang lamig ngayon! Magbalot ka nang mabuti.', "Brr, it's cold today! Wrap up well."],
      ['Ang lamig! Nasaan ang jacket mo?', "It's freezing! Where's your jacket?"],
      ['Sa sobrang lamig, parang namanhid na ang ilong ko.', "It's so cold my nose has gone numb."],
      ['Uminom ka ng mainit na salabat. Nakakatulong.', 'Have some hot ginger tea. It helps.'],
      ['Hintayin mo lang lumakas ang hangin, mas lalamig pa.', 'Just wait till the wind picks up, it gets colder still.'],
    ],
    mild: [
      ['Ang ganda ng panahon ngayon.', 'The weather is lovely today.'],
      ['Hindi mainit, hindi malamig. Sakto, ano?', "Not hot, not cold. Just right, isn't it?"],
      ['Sa ganitong araw, gusto mo lang nasa labas.', 'On a day like this, you just want to be outside.'],
      ['Ang ganda ng panahon! Sana tuloy-tuloy.', "Beautiful weather! Let's hope it lasts."],
      ['Ito ang dahilan kaya ang sarap tumira dito.', 'This is why it is so nice to live here.'],
    ],
    late: [
      ['Gabi na. Tahimik ang mga kalye sa gabi.', "It's late. The streets are quiet at night."],
      ['Sa ganitong oras, pusa lang ang gising. At tayo!', 'At this hour only the cats are awake. And us!'],
      ['Dapat tulog na ako. Bakit gising ka pa?', 'I should be asleep. Why are you still up?'],
      ['Tingnan mo ang mga bituin! Pinakamaganda silang tingnan mula rito.', 'Look at the stars! They look their best from here.'],
    ],
    early: [
      ['Ang aga mo! Ito ang pinakamagandang oras.', "You're up early! This is the best time of day."],
      ['Bukas na ang panaderya. Sundan mo lang ang amoy ng pandesal!', 'The bakery is open. Just follow the smell of pandesal!'],
      ['Maagang ibon, ha? Tulog pa ang buong bayan.', 'An early bird, eh? The whole town is still asleep.'],
      ['Gusto ko ang umaga rito, bago magsimula ang ingay.', 'I love the mornings here, before the noise starts.'],
    ],
    country: [
      ['Magandang bansa ang {country}. Mag-enjoy ka!', '{country} is a beautiful country. Enjoy it!'],
      ['Kumusta naman ang {country} sa iyo sa ngayon?', 'How are you finding {country} so far?'],
      ['Libutin mo ang {country} kung kaya mo. Iba-iba ang bawat sulok.', 'Go all round {country} if you can. Every corner is different.'],
      ['Mahigit pitong libong isla ang {country}! Ilan na ang napuntahan mo?', '{country} is over seven thousand islands! How many have you been to?'],
    ],
    dish: [
      ['Tikman mo ang {dish} habang nandito ka.', "Try {dish} while you're here."],
      ['Nakakain ka na ba ng {dish}? Hindi pa? Naku, dapat!', 'Have you had {dish} yet? Not yet? Oh, you must!'],
      ['Walang nakakapagluto ng {dish} tulad ng nanay ko.', 'Nobody can cook {dish} like my mother.'],
      ['Kung gutom ka, humanap ka ng {dish}. Hindi ka magsisisi.', "If you're hungry, find some {dish}. You won't regret it."],
    ],
    drink: [
      ['Uminom ka muna ng {drink} bago umalis. Iyan ang iniinom namin dito.', 'Have some {drink} before you go. It is what we drink here.'],
      ['Wala nang tatalo sa {drink} sa hapon.', 'Nothing beats {drink} in the afternoon.'],
      ['Hindi ka pa nabubuhay hangga’t hindi mo natitikman ang {drink}.', "You haven't lived until you've tasted {drink}."],
      ['Parang taga-rito, umorder ka ng {drink}. Matutuwa sila sa iyo!', "Order {drink} like a local. They'll love you for it!"],
    ],
    festival: [
      ['Bumalik ka para sa {festival}. Napakasaya!', 'Come back for {festival}. It is so much fun!'],
      ['Pinakamagandang pumunta rito tuwing {festival}. Fiesta talaga!', 'The best time to come is during {festival}. A real fiesta!'],
      ['Narinig mo na ba ang {festival}? Magugustuhan mo.', "Have you heard of {festival}? You'd love it."],
      ['Taon-taon, binibilang ko ang araw hanggang {festival}.', 'Every year I count the days until {festival}.'],
    ],
    sport: [
      ['Dito, {sport} ang lahat. Lahat naglalaro.', "Here it's all about {sport}. Everybody plays."],
      ['Mahilig ka ba sa {sport}? Dito, adik kami diyan!', "Do you like {sport}? Here we're hooked on it!"],
      ['Kapag may laro, puro {sport} ang usapan ng buong bayan.', 'When there is a game, the whole town talks about nothing but {sport}.'],
      ['Buong pamilya ko naglalaro ng {sport}. Si Lola, sumisigaw lang.', 'My whole family plays {sport}. Grandma just shouts.'],
    ],
    wonder: [
      ['Kung may oras ka, puntahan mo ang {wonder}. Hindi mo makakalimutan.', "If you have time, go and see {wonder}. You'll never forget it."],
      ['Nakita mo na ba ang {wonder}? Walang katulad sa buong mundo.', 'Have you seen {wonder}? Nothing like it in the whole world.'],
      ['Dapat makita ng lahat ang {wonder} kahit minsan sa buhay.', 'Everybody should see {wonder} at least once in their life.'],
      ['Bata pa ako nang makita ko ang {wonder}. Napapanaginipan ko pa rin.', 'I was a child when I saw {wonder}. I still dream about it.'],
    ],
    pride: [
      ['Ipinagmamalaki namin ang {pride}.', 'We are proud of {pride}.'],
      ['Huwag kang aalis nang hindi nakikilala ang {pride}. Iyan ang pagkatao namin.', "Don't leave without getting to know {pride}. It's who we are."],
      ['Alam mo kung ano ang ipinagmamalaki namin? Ang {pride}.', 'Do you know what makes us proud? {pride}.'],
      ['Tanungin mo kahit sino rito tungkol sa {pride}, oras-oras silang magkukuwento.', 'Ask anyone here about {pride}, and they will talk for hours.'],
    ],
    proverb: [
      ['Sabi nga namin dito: “{proverb}”', 'As we say here: “{proverb}”'],
      ['Laging sinasabi ng lola ko: “{proverb}”', 'My grandmother always says: “{proverb}”'],
      ['May kasabihan dito: “{proverb}”', 'There is a saying here: “{proverb}”'],
      ['Alam mo ba ang kasabihang ito? “{proverb}”', 'Do you know this saying? “{proverb}”'],
    ],
    chat: [
      ['Taga-saan ka? Hindi ka taga-rito, ano?', "Where are you from? You're not from here, are you?"],
      ['Dahan-dahan lang, tumingin-tingin ka. Maraming makikita rito.', 'Take it slow and look around. There is a lot to see here.'],
      ['Mag-isa ka lang bang naglalakbay? Ang tapang mo.', "Are you travelling alone? That's brave."],
      ['Mukhang malayo na ang nilakad mo.', 'You look like you have walked a long way.'],
      ['Kung maligaw ka, magtanong ka lang. Mababait ang tao rito.', 'If you get lost, just ask. People here are kind.'],
      ['Saan ang pinakamagandang lugar na napuntahan mo?', "What's the best place you've been to?"],
      ['Kumain ka na ba? May masarap na karinderya sa kanto.', "Have you eaten? There's a good little eatery on the corner."],
      ['Gusto ko ring maglakbay balang araw.', 'I would love to travel too, some day.'],
    ],
    childGreet: [
      ['Hi po!', 'Hi!'],
      ['Hello po! Sino po kayo?', 'Hello! Who are you?'],
      ["Hi! Ang tangkad n'yo po!", "Hi! You're so tall!"],
      ['Hello, hello!', 'Hello, hello!'],
    ],
    childChat: [
      ["Ang bilis kong tumakbo! Gusto n'yo pong makita? Mamaya na lang.", 'I can run really fast! Want to see? Later.'],
      ['Turista po kayo? Sabi ng kaibigan ko, mayayaman daw ang turista.', 'Are you a tourist? My friend says tourists are rich.'],
      ["Natanggal ang ngipin ko kahapon! Tingnan n'yo! Ay, hindi n'yo pala makita.", "My tooth came out yesterday! Look! Oh, you can't see it."],
      ['Sabi ni Nanay, huwag daw makipag-usap sa hindi kakilala. Pero mukha po kayong mabait.', "Mum says don't talk to strangers. But you look nice."],
      ['May aso po kayo? Gusto ko ng aso.', 'Do you have a dog? I want a dog.'],
      ['Paglaki ko, magpapalipad ako ng eroplano sa buong mundo!', "When I grow up I'm going to fly a plane all round the world!"],
      ['Marunong po ba kayong maglaro ng patintero? Magaling ako diyan!', "Do you know how to play patintero? I'm great at it!"],
    ],
    childBye: [
      ['Babay!', 'Bye-bye!'],
      ['Bye po! Balik kayo, laro tayo!', "Bye! Come back and we'll play!"],
      ['Alis na po ako, tinatawag na ako ni Nanay!', "I have to go, Mum's calling me!"],
      ['Sige po, ingat!', 'Okay, take care!'],
    ],
    grumpyGreet: [
      ["Hmm. Ano'ng kailangan mo?", 'Hmm. What do you want?'],
      ['O? Ano iyon?', 'Well? What is it?'],
      ['Hay naku. Turista na naman.', 'Oh, good grief. Another tourist.'],
      ['Hmp. Hello na rin.', 'Hmph. Hello, I suppose.'],
    ],
    grumpyChat: [
      ['Mas maganda rito noon, bago dumagsa ang mga tao.', 'It was nicer here before the crowds started pouring in.'],
      ['Doble na ang presyo ng lahat.', 'Everything costs double now.'],
      ['Huwag kang humarang sa bangketa. May nakatira dito.', "Don't block the pavement. People live here."],
      ['Mga kabataan ngayon, puro cellphone.', 'Young people today, nothing but their phones.'],
      ['Ewan ko kung bakit may pumupunta rito. Wala namang makikita.', "I don't know why anyone comes here. There's nothing to see."],
      ['Traffic, init, ingay. Ano pa?', 'Traffic, heat, noise. What else?'],
    ],
    grumpyBye: [
      ['Sige na. Lakad na.', 'Right. Off you go.'],
      ['O siya, hindi na kita aabalahin.', "Well then, I won't keep you."],
      ['Hmm. Paalam.', 'Hmm. Goodbye.'],
      ['Ingat. At isara mo ang gate!', 'Take care. And shut the gate!'],
    ],
    elderChat: [
      ['Noong bata ako, puro palayan ito.', 'When I was young, this was all rice fields.'],
      ['Buong buhay ko dito na ako nakatira. Walumpung taon! Maniniwala ka ba?', "I've lived here all my life. Eighty years! Can you believe it?"],
      ['Noong panahon namin, naglalakad kami kahit saan. Ikaw rin, naglalakad. Mabuti!', 'In our day we walked everywhere. You walk too. Good!'],
      ['Nasa abroad na ang mga apo ko. Tumatawag sila tuwing Linggo.', 'My grandchildren are abroad now. They call every Sunday.'],
      ['Ang bilis ng pagbabago. Pero ang mga lumang kalye, ganoon pa rin.', 'Things change so fast. But the old streets are just the same.'],
    ],
    chattyChat: [
      ['Naku, gustong-gusto kong makakilala ng biyahero! Ikuwento mo lahat. Ay, teka, ako muna.', 'Oh, I love meeting travellers! Tell me everything. Oh, wait, me first.'],
      ['Nag-abroad minsan ang pinsan ko. Umuwi siyang may balbas at may asawa!', 'My cousin went abroad once. He came home with a beard and a wife!'],
      ['Sabi ng mga kaibigan ko, kaya kong magdaldal buong araw. Tama sila!', 'My friends say I could chatter all day. They are right!'],
      ['Kumain ka na? Mukha kang gutom. Lahat mukhang gutom sa akin.', 'Have you eaten? You look hungry. Everybody looks hungry to me.'],
      ['May sikreto ako: ang pinakamagandang tanawin ay mula sa burol sa likod ng simbahan.', "Here's a secret: the best view is from the hill behind the church."],
    ],
    bye: [
      ['Paalam! Ingat sa biyahe.', 'Goodbye! Safe travels.'],
      ['Ingat ka! Mag-enjoy sa paglalakbay.', 'Take care! Enjoy your journey.'],
      ['Ingat, kaibigan!', 'Take care, friend!'],
      ['Sige, balik ka ulit, ha!', 'Okay, come back again, all right!'],
      ['Masaya akong nakausap ka. Ingat lagi!', 'It was nice talking to you. Always take care!'],
      ['Sige, lakad na! Marami ka pang makikita.', "Go on, then! There's a lot more to see."],
    ],
  },
  countries: {
    // A bare noun phrase with no marker: the templates put *ang*, *ng* or *sa* before it and no linker after.
    PHL: {
      dish: ['adobo', 'adobo (meat stewed in vinegar and soy)'],
      drink: ['sago’t gulaman', 'sago’t gulaman (a sweet iced drink)'],
      festival: ['Sinulog', 'the Sinulog festival'],
      sport: ['basketball', 'basketball'],
      wonder: ['Chocolate Hills ng Bohol', 'the Chocolate Hills of Bohol'],
      pride: ['bayanihan', 'bayanihan, our spirit of helping one another'],
      proverb: [
        'Ang hindi lumingon sa pinanggalingan ay hindi makararating sa paroroonan',
        'Whoever does not look back at where they came from will never reach where they are going',
      ],
    },
  },
};

export default TL;
