import type { Language } from '../phrases.ts';

const TR: Language = {
  locale: 'tr',
  name: 'Turkish',
  join: ' ',
  compass: ['kuzeyde', 'kuzeydoğuda', 'doğuda', 'güneydoğuda', 'güneyde', 'güneybatıda', 'batıda', 'kuzeybatıda'],
  lines: {
    morning: [
      ['Günaydın!', 'Good morning!'],
      ['Günaydın! Güzel bir sabah, değil mi?', "Good morning! Lovely morning, isn't it?"],
      ['Aa, merhaba! Hayırlı sabahlar.', 'Oh, hello! A blessed morning to you.'],
      ['Sabahınız hayrolsun!', 'May your morning be a good one!'],
    ],
    afternoon: [
      ['İyi günler!', 'Good day!'],
      ['Merhaba!', 'Hello!'],
      ['Merhabalar, iyi günler!', 'Hello there, good day!'],
      ['Aa, merhaba! Güzel bir öğleden sonra.', 'Oh, hi! A nice afternoon.'],
    ],
    evening: [
      ['İyi akşamlar!', 'Good evening!'],
      ['Akşamınız hayırlı olsun!', 'Have a good evening!'],
      ['Merhaba! Yürüyüş için güzel bir akşam.', 'Hello! Nice evening for a walk.'],
      ['Aa, iyi akşamlar size.', 'Oh, good evening to you.'],
    ],
    night: [
      ['İyi akşamlar! Epey geç oldu, değil mi?', "Good evening! It's quite late, isn't it?"],
      ['Aa! Korkuttunuz beni. Merhaba!', 'Oh! You gave me a fright. Hello!'],
      ['Merhaba! Gece yürüyüşüne mi çıktınız?', 'Hello! Out for a night walk?'],
      ['İyi geceler... yoksa günaydın mı demeli?', 'Good night... or should I say good morning?'],
    ],
    again: [
      ['Aa, yine siz! Merhaba!', 'Oh, you again! Hello!'],
      ['Yine mi geldiniz? Sizi görmek ne güzel.', 'Back again? How nice to see you.'],
      ['Tekrar merhaba!', 'Hello again!'],
      ['Biz tanışmıştık! Hâlâ geziyor musunuz?', "We've met! Still exploring?"],
    ],
    welcome: [
      ['Hoş geldiniz! Burası {town}.', 'Welcome! This is {town}.'],
      ['Burası {town}. Gezmeye mi geldiniz?', 'This is {town}. Are you here sightseeing?'],
      ['İlk kez mi buradasınız? Burası {town}, hoş geldiniz!', 'Is this your first time here? This is {town}, welcome!'],
      ['Hoş geldiniz, safalar getirdiniz! Burası {town}.', 'Welcome, you bring us joy! This is {town}.'],
      ['Güzel bir gün seçmişsiniz. {town} bugün çok güzel.', "You've picked a good day. {town} looks lovely today."],
    ],
    capitalHere: [
      ['{town}, ülkemizin başkenti.', '{town} is the capital of our country.'],
      ['Burası başkent, biliyorsunuz. Her şey burada olur.', 'This is the capital, you know. Everything happens here.'],
      ['Başkentte hayat hiç durmaz. Hep bir koşturmaca!', 'Life never stops in the capital. Always a rush!'],
      ['Başkent olunca {town} hiç uyumaz.', 'Being the capital, {town} never sleeps.'],
    ],
    capitalThere: [
      ['Başkentimiz {capital}. Görmeye değer.', 'Our capital is {capital}. It is worth seeing.'],
      ['Başkente gittiniz mi hiç? Adı {capital}.', 'Have you been to the capital? It is called {capital}.'],
      ['{capital} daha büyük ama ben burada yaşamayı tercih ederim.', "{capital} is bigger, but I'd rather live here."],
      ['Başkent {capital} olabilir ama asıl hayat burada!', 'The capital may be {capital}, but real life is here!'],
    ],
    big: [
      ['Burası büyük bir şehir. Kaybolmak çok kolay!', "This is a big city. It's very easy to get lost!"],
      ['Ne kalabalık! Bir ömür yaşasanız her sokağı bilemezsiniz.', "So crowded! You could live here a lifetime and not know every street."],
      ['Şu trafik yok mu... Ama burada her zaman bir şey olur.', 'Oh, this traffic... But there is always something going on.'],
      ['Büyük şehir hiç durmaz. Ben yine de severim.', 'A big city never stops. I still love it.'],
    ],
    middling: [
      ['Ne büyük ne küçük. Tam kararında.', 'Not big, not small. Just right.'],
      ['Her şey var ama yürüyerek gezilir.', 'It has everything, and you can still walk it.'],
      ['Güzel bir boyutta. Bir iki günde her yeri görürsünüz.', "It's a nice size. You'll see it all in a day or two."],
      ['Herkes çok sakin diye şikâyet eder, ama kimse de gitmez.', 'Everyone complains it is too quiet, and nobody ever leaves.'],
    ],
    small: [
      ['Burası küçük bir yer. Herkes birbirini tanır.', 'This is a small place. Everybody knows everybody.'],
      ['Küçük yer burası. Hapşırsanız bütün sokak çok yaşa der.', 'Small place. Sneeze and the whole street says bless you.'],
      ['Burada pek bir şey olmaz, biz de böyle seviyoruz.', 'Not much happens here, and we like it that way.'],
      ['Haftanın en heyecanlı olayı sizsiniz herhalde!', "You're probably the most exciting thing this week!"],
    ],
    coast: [
      ['Burada suyun kenarında yaşıyoruz. Balığı çok güzeldir.', 'We live by the water here. The fish is excellent.'],
      ['Gidin denize bir bakın. Her gün başka türlü.', 'Go and look at the sea. It is different every day.'],
      ['Bu kokuyu alıyor musunuz? Deniz kokusu. İnsan hiç bıkmaz.', "Smell that? That's the sea. You never tire of it."],
      ['Tekneler sabah erkenden çıkar, en taze balıkla döner.', 'The boats go out early and come back with the freshest fish.'],
    ],
    inland: [
      ['Denizden uzağız ama buranın doğası çok güzel.', 'We are far from the sea, but the countryside here is beautiful.'],
      ['Burada plaj yok maalesef. Ama şu tarlalara bakın.', "No beach here, I'm afraid. But look at those fields."],
      ['Deniz mi? Çok uzakta. Bizim denizimiz bu ovalar.', 'The sea? Very far. These plains are our sea.'],
      ['Toprağı bereketli, insanı güzeldir buranın.', 'The soil here is rich and the people are good.'],
    ],
    high: [
      ['Burası yüksek. Yavaş yürüyün, hava ince.', "It's high up here. Walk slowly, the air is thin."],
      ['Bu tepelerde en güzel şey manzara.', 'Up in these hills, the view is the best thing we have.'],
      ['Burada yaşayanın bacakları güçlü olur. Düz yer yok ki!', 'Living here gives you strong legs. Nothing is flat!'],
      ['Nefesinize dikkat! Dağın havasına alışmak zaman ister.', 'Mind your breath! Mountain air takes some getting used to.'],
    ],
    snowy: [
      ['Yılın dokuz ayı kar. Kalan üç ay da çamurdan şikâyet ederiz.', 'Snow nine months a year. The other three, we complain about the mud.'],
      ['Her yer bembeyaz. Bu ayakkabılardan daha sağlamını giyin.', 'Everything is white. Wear sturdier shoes than those.'],
      ['Kar yeni yağınca öyle sessiz olur ki, kendi düşüncenizi duyarsınız.', 'When fresh snow falls it is so quiet you can hear yourself think.'],
      ['Soğuğa alışkınız. Bir çay, bir soba, gerisi kolay.', "We're used to the cold. A tea, a stove, and the rest is easy."],
    ],
    forest: [
      ['Ormanlar günlerce sürer. Patikadan ayrılmayın!', 'The woods go on for days. Stay on the path!'],
      ['Ormanda bir yürüyüş yapın, kafa dinlendirir.', 'Take a walk in the forest, it rests the mind.'],
      ['Her sonbahar mantar ve böğürtlen toplamaya gideriz.', 'Every autumn we go picking mushrooms and blackberries.'],
      ['Ağaç, ağaç, yine ağaç. Başka yerde yaşayamam.', "Trees, trees and more trees. I couldn't live anywhere else."],
    ],
    desert: [
      ['Burada göz alabildiğine kum var.', 'Here there is sand as far as the eye can see.'],
      ['Bol su için. Çöl affetmez.', 'Drink plenty of water. The desert does not forgive.'],
      ['Çölde geceler soğuk olur, kimse inanmaz.', 'Desert nights are cold, nobody believes it.'],
      ['Bu gece yıldızları bekleyin. Burada milyonlarcası var.', 'Wait for the stars tonight. There are millions of them here.'],
    ],
    plains: [
      ['Kilometrelerce dümdüz. Havanın değiştiğini bir gün önceden görürsünüz.', 'Flat for miles. You see the weather coming a day ahead.'],
      ['Gökyüzü kocaman burada. Rüzgârı durduracak hiçbir şey yok.', 'The sky is huge here. Nothing to stop the wind.'],
      ['Hep otlak burası. Sürülere dikkat edin.', "It's all pasture here. Watch out for the herds."],
      ['Çimen sonsuza kadar uzanıyor. Yeşil bir deniz gibi.', 'The grass stretches forever. Like a green sea.'],
    ],
    tropical: [
      ['Burada her şey büyür. Bir dal dikin, ağaç olur.', 'Everything grows here. Plant a twig and it becomes a tree.'],
      ['Yağmur gelince bir gelir ki! Sonra birden durur.', 'When the rain comes, it really comes! Then it suddenly stops.'],
      ['Pazardaki meyvelerden deneyin. Böylesini hiç yemediniz.', "Try the fruit at the market. You've never had anything like it."],
      ['Burası bütün yıl yemyeşil. Kış mı? O ne ki?', "It's green all year round. Winter? What's that?"],
    ],
    landmark: [
      ['Mutlaka görmeniz gereken bir yer: {landmark}! Buradan yaklaşık {km} km {dir}.', 'A place you must see: {landmark}! About {km} km from here, {dir}.'],
      ['Hiç duydunuz mu? {landmark}, buradan {km} km {dir}. Her adımına değer.', "Ever heard of it? {landmark}, {km} km {dir} of here. Worth every step."],
      ['Herkes oraya gider: {landmark}. Yaklaşık {km} km {dir}.', 'Everyone goes there: {landmark}. About {km} km {dir}.'],
      ['Tarih seviyorsanız {landmark} tam size göre. {km} km {dir}.', 'If you love history, {landmark} is just for you. {km} km {dir}.'],
    ],
    landmarkNear: [
      ['{landmark} çok yakında. Kaçırmanız imkânsız!', "{landmark} is very close. You can't miss it!"],
      ['{landmark} hemen şurada, köşeyi dönünce.', '{landmark} is right there, just round the corner.'],
      ['Her gün görürüz ama {landmark} hâlâ nefesimi keser.', 'We see it every day, but {landmark} still takes my breath away.'],
      ['Tam burada: {landmark}. Kalabalıktan önce, sabah erken gidin.', 'Right here: {landmark}. Go early, before the crowds.'],
    ],
    plane: [
      ['{dir} bir tarlada küçük bir uçak var, uçmayı biliyorsanız!', "There's a little plane in a field {dir}, if you can fly!"],
      ['Biri tarlaya bir uçak bırakmış, {dir}. Bir tur atmaya ne dersiniz?', 'Somebody left a plane in a field {dir}. Fancy a spin?'],
      ['Uçak kullanabilir misiniz? {dir} bir uçak bekliyor.', 'Can you fly a plane? One is waiting {dir}.'],
      ['Her yeri yukarıdan görmek isterseniz {dir} bir uçak var.', "If you want to see it all from above, there's a plane {dir}."],
    ],
    balloon: [
      ['{dir} bir tarlada sıcak hava balonu var! Manzarayı düşünsenize.', "There's a hot-air balloon in a field {dir}! Imagine the view."],
      ['Hiç balona bindiniz mi? {dir} bir tane var.', 'Have you ever flown in a balloon? There is one {dir}.'],
      ['Balon {dir}, tarladan havalanıyor. Büyülü bir şey.', 'The balloon goes up from a field {dir}. It is magical.'],
      ['Hep o balona binmek istedim ama korkuyorum!', "I've always wanted to ride that balloon, but I'm scared!"],
    ],
    boat: [
      ['{dir}, suyun kenarında bir tekne var. Açılmak isterseniz.', "There's a boat by the water {dir}, if you want to go out."],
      ['Denizi seviyorsanız {dir} bir tekne var. Yalnız geri getirin!', "If you love the sea, there's a boat {dir}. Just bring it back!"],
      ['Bir tekne bağlı duruyor, {dir}. Buradan her yere gidilir.', 'A boat is tied up {dir}. From here you can go anywhere.'],
      ['Tekneye binin, kıyıyı bir de denizden görün.', 'Take the boat and see the coast from the water.'],
    ],
    hot: [
      ['Bugün hava sıcak! Biraz gölge bulun.', "It's hot today! Find some shade."],
      ['Of, ne sıcak! Biraz su için, ihtiyacınız var gibi.', 'Phew, the heat! Drink some water, you look like you need it.'],
      ['Bu sıcakta gölgede oturmaktan başka bir şey yapılmaz.', 'In this heat all you can do is sit in the shade.'],
      ['Bu sıcakta kediler bile dışarı çıkmıyor.', 'In this heat even the cats stay indoors.'],
      ['Sıcak, değil mi? Bir ayran için, iyi gelir.', "Hot, isn't it? Have an ayran, it'll do you good."],
    ],
    cold: [
      ['Brr, bugün hava soğuk! Sıkı giyinin.', "Brr, it's cold today! Wrap up warm."],
      ['Buz gibi! Eldivenleriniz nerede?', 'Freezing! Where are your gloves?'],
      ['O kadar soğuk ki burnumu hissetmiyorum.', "It's so cold I can't feel my nose."],
      ['Soğuk mu? Bir de rüzgâr çıksın, o zaman görün.', 'Cold? Wait till the wind picks up, then you will see.'],
      ['Sıcak bir çay için, iyi gelir.', "Have a hot tea, it'll do you good."],
    ],
    mild: [
      ['Bugün hava ne kadar güzel.', 'What lovely weather today.'],
      ['Ne sıcak ne soğuk. Harika bir gün, değil mi?', "Not hot, not cold. A wonderful day, isn't it?"],
      ['Böyle günlerde insan dışarıda olmak ister.', 'On days like this you want to be outside.'],
      ['Hava mis gibi! İnşallah böyle devam eder.', 'The air is lovely! I hope it stays like this.'],
      ['Böyle günler için yaşıyoruz burada.', 'Days like this are why we live here.'],
    ],
    late: [
      ['Geç oldu. Geceleri sokaklar sakindir.', "It's late. The streets are quiet at night."],
      ['Bu saatte sadece kediler dışarıda. Bir de biz!', 'At this hour only the cats are out. And us!'],
      ['Benim çoktan yatmam lazımdı. Siz neden uyanıksınız?', 'I should have been in bed long ago. Why are you up?'],
      ['Yıldızlara bakın! En güzel buradan görünür.', 'Look at the stars! They look best from here.'],
    ],
    early: [
      ['Erkencisiniz! Günün en güzel saati.', "You're up early! The best hour of the day."],
      ['Fırın yeni açıldı. Simit kokusunu takip edin!', 'The bakery has just opened. Follow the smell of simit!'],
      ['Erken kalkan yol alır, derler. Şehir daha uyanmadı bile.', 'The early riser goes far, they say. The town is not even awake yet.'],
      ['Gürültü başlamadan önceki sabahları çok severim.', 'I love the mornings here, before the noise starts.'],
    ],
    country: [
      ['{country} çok güzel bir ülke. Tadını çıkarın!', '{country} is a beautiful country. Enjoy it!'],
      ['Söyleyin bakalım, {country} hoşunuza gitti mi?', 'So tell me, do you like {country}?'],
      ['{country} her köşesi ayrı güzel bir ülke.', '{country} is a country where every corner is beautiful in its own way.'],
      ['{country} dört mevsimi bir arada yaşayan bir ülke.', '{country} is a country that has all four seasons at once.'],
    ],
    dish: [
      ['Buradayken mutlaka deneyin: {dish}.', "While you're here, you must try it: {dish}."],
      ['{dish} yediniz mi? Hayır mı? Olmaz öyle!', "Have you had {dish}? No? That won't do!"],
      ['Annemin yaptığı gibisi yoktur: {dish}.', 'Nobody makes it like my mother: {dish}.'],
      ['Karnınız acıktıysa tavsiyem {dish}. Pişman olmazsınız.', "If you're hungry, my advice is {dish}. You won't regret it."],
    ],
    drink: [
      ['Gitmeden bir {drink} için. Burada bunu içeriz.', 'Have some {drink} before you go. It is what we drink here.'],
      ['Günün sonunda {drink} gibisi yoktur.', 'Nothing beats {drink} at the end of the day.'],
      ['{drink} içmeden buradan gitmek olmaz.', 'You cannot leave here without having {drink}.'],
      ['Yerliler gibi {drink} isteyin, herkes bayılır size.', "Order {drink} like a local and everyone will love you."],
    ],
    festival: [
      ['{festival} zamanı tekrar gelin. Harika olur!', 'Come back for {festival}. It is wonderful!'],
      ['Burada olmanın en güzel zamanı {festival}. Bütün ülke kutlar.', 'The best time to be here is {festival}. The whole country celebrates.'],
      ['{festival} diye bir şey duydunuz mu? Bayılırsınız.', "Have you heard of {festival}? You'd love it."],
      ['Her yıl {festival} için gün sayarım.', 'Every year I count the days till {festival}.'],
    ],
    sport: [
      ['Burada her şey {sport}. Herkes oynar.', "Here it's all about {sport}. Everybody plays."],
      ['{sport} sever misiniz? Biz burada deli oluruz.', 'Do you like {sport}? Here we go crazy for it.'],
      ['Maç günü bütün şehir sadece {sport} konuşur.', 'On match day the whole town talks about nothing but {sport}.'],
      ['Bütün ailem {sport} oynar. Babaannem sadece bağırır.', 'My whole family plays {sport}. My grandmother just shouts.'],
    ],
    wonder: [
      ['Vaktiniz varsa gidin görün: {wonder}. Unutulmaz.', 'If you have time, go and see it: {wonder}. Unforgettable.'],
      ['Dünyada eşi yoktur: {wonder}.', 'There is nothing like it in the world: {wonder}.'],
      ['Herkes hayatında bir kez görmeli: {wonder}.', 'Everyone should see it once in their life: {wonder}.'],
      ['Çocukken {wonder} gezisine gitmiştim, hâlâ rüyamda görürüm.', 'As a child I went on a trip to {wonder}. I still dream about it.'],
    ],
    pride: [
      ['{pride} ile gurur duyuyoruz.', 'We are proud of {pride}.'],
      ['Bizi biz yapan şey: {pride}.', 'What makes us who we are: {pride}.'],
      ['Neyle gurur duyarız, biliyor musunuz? {pride}.', 'Do you know what we are proud of? {pride}.'],
      ['Kime sorsanız {pride} konusunu saatlerce anlatır.', 'Ask anyone about {pride} and they will talk for hours.'],
    ],
    proverb: [
      ['Burada şöyle deriz: “{proverb}”', 'Here we say: “{proverb}”'],
      ['Babaannem hep derdi ki: “{proverb}”', 'My grandmother always said: “{proverb}”'],
      ['Bir atasözümüz vardır: “{proverb}”', 'We have a proverb: “{proverb}”'],
      ['Atalarımız ne demiş, bilirsiniz: “{proverb}”', 'You know what our ancestors said: “{proverb}”'],
    ],
    chat: [
      ['Nerelisiniz? Buralı değilsiniz galiba.', "Where are you from? You're not from here, I think."],
      ['Acele etmeyin, etrafa bakın. Görülecek çok şey var.', 'Take your time and look around. There is a lot to see.'],
      ['Yalnız mı geziyorsunuz? Cesaret ister.', 'Travelling alone? That takes courage.'],
      ['Epey yol yürümüşe benziyorsunuz.', 'You look like you have walked a long way.'],
      ['Kaybolursanız sorun, burada insanlar yardımseverdir.', 'If you get lost, just ask. People here are helpful.'],
      ['Şimdiye kadar gördüğünüz en güzel yer neresi?', "What's the most beautiful place you've seen so far?"],
      ['Bir çayımı içmeden gitmeyin ama!', "Don't leave without having a tea with me!"],
    ],
    childGreet: [
      ['Merhaba!', 'Hello!'],
      ['Selam! Sen kimsin?', 'Hi! Who are you?'],
      ['Merhaba! Ne kadar uzunsun!', "Hello! You're so tall!"],
      ['Selam selam!', 'Hi, hi!'],
    ],
    childChat: [
      ['Ben çok hızlı koşarım! Görmek ister misin?', 'I can run really fast! Want to see?'],
      ['Turist misin? Arkadaşım turistler zengin diyor.', 'Are you a tourist? My friend says tourists are rich.'],
      ['Dün dişim düştü! Bak! Ay, göremezsin ki.', "My tooth fell out yesterday! Look! Oh, you can't see it."],
      ['Annem yabancılarla konuşma diyor. Ama sen iyi birine benziyorsun.', "Mum says don't talk to strangers. But you look nice."],
      ['Köpeğin var mı? Ben de köpek istiyorum.', 'Do you have a dog? I want a dog too.'],
      ['Büyüyünce uçakla bütün dünyayı gezeceğim!', "When I grow up I'm going to fly all round the world!"],
      ['Saklambaç bilir misin? Ebe sensin!', "Do you know hide-and-seek? You're it!"],
    ],
    childBye: [
      ['Görüşürüz!', 'See you!'],
      ['Hoşça kal! Yine gel, oynarız!', 'Bye! Come again and we can play!'],
      ['Gitmem lazım, annem çağırıyor!', 'I have to go, my mum is calling!'],
      ['Bay bay!', 'Bye bye!'],
    ],
    grumpyGreet: [
      ['Hı. Ne istiyorsunuz?', 'Hm. What do you want?'],
      ['Evet? Ne var?', "Yes? What is it?"],
      ['Of. Bir turist daha.', 'Ugh. Another tourist.'],
      ['Hmm. Merhaba, herhalde.', 'Hmm. Hello, I suppose.'],
    ],
    grumpyChat: [
      ['Herkes gelmeye başlamadan önce burası daha güzeldi.', 'It was nicer here before everybody started coming.'],
      ['Her şey eskisinin iki katı. Ekmek bile!', 'Everything costs twice what it used to. Even bread!'],
      ['Kaldırımı kapatmayın lütfen. Burada insanlar yaşıyor.', "Don't block the pavement, please. People live here."],
      ['Şimdiki gençler, hep ellerinde telefon.', 'Young people these days, always a phone in their hand.'],
      ['Neden gelirler bilmem. Görecek bir şey yok ki.', "I don't know why they come. There's nothing to see."],
    ],
    grumpyBye: [
      ['Tamam. Hadi bakalım.', 'Right. Off you go, then.'],
      ['Sizi tutmayayım.', "I won't keep you."],
      ['Hı. Hoşça kalın.', 'Hm. Goodbye.'],
      ['Dikkatli gidin. Kapıyı da kapatın.', 'Mind how you go. And shut the gate.'],
    ],
    elderChat: [
      ['Ben gençken buralar hep tarlaydı.', 'When I was young, all this was fields.'],
      ['Ömrüm burada geçti. Seksen yıl! İnanabiliyor musunuz?', 'I have spent my life here. Eighty years! Can you believe it?'],
      ['Bizim zamanımızda her yere yürüyerek giderdik.', 'In our day we walked everywhere.'],
      ['Torunlarım yurt dışında. Her pazar ararlar.', 'My grandchildren are abroad. They call every Sunday.'],
      ['Her şey çok çabuk değişiyor. Ama eski sokaklar aynı.', 'Everything changes so fast. But the old streets stay the same.'],
    ],
    chattyChat: [
      ['Aa, gezginlerle tanışmaya bayılırım! Anlatın her şeyi. Yok, durun, önce ben anlatayım.', 'Oh, I love meeting travellers! Tell me everything. No, wait, let me go first.'],
      ['Kuzenim bir kere gezmeye gitmişti. Bir sakal ve bir eşle döndü!', 'My cousin went travelling once. Came back with a beard and a spouse!'],
      ['Arkadaşlarım bütün gün konuşabilirim der. Haksız da değiller!', "My friends say I could talk all day. They're not wrong!"],
      ['Yemek yediniz mi? Aç görünüyorsunuz. Bana herkes aç görünür zaten.', 'Have you eaten? You look hungry. Everybody looks hungry to me.'],
      ['Size bir sır vereyim: en güzel manzara tepedeki çay bahçesinden.', 'Let me tell you a secret: the best view is from the tea garden on the hill.'],
    ],
    bye: [
      ['Hoşça kalın! İyi yolculuklar.', 'Goodbye! Have a good trip.'],
      ['Kendinize iyi bakın! Yolunuz açık olsun.', 'Take care! May your road be open.'],
      ['Güle güle! Yine bekleriz.', 'Go with a smile! We hope to see you again.'],
      ['Sizinle konuşmak güzeldi. Selametle!', 'It was nice talking to you. Go safely!'],
      ['Hadi bakalım, görülecek çok yer var!', 'Off you go, then! There is so much to see.'],
    ],
  },
  countries: {
    // Every fact is a bare nominative noun phrase; the templates set it as a subject, after a colon or before a free word, never with a suffix on it.
    TUR: {
      dish: ['İskender kebap', 'Iskender kebab'],
      drink: ['çay', 'Turkish tea'],
      festival: ['Ramazan Bayramı', 'the Ramadan Feast'],
      sport: ['futbol', 'football'],
      wonder: ['Kapadokya', 'Cappadocia'],
      pride: ['misafirperverlik', 'our hospitality'],
      proverb: ['Bir fincan kahvenin kırk yıl hatırı vardır', 'A single cup of coffee is remembered for forty years'],
    },
  },
};

export default TR;
