import type { Language } from '../phrases.ts';

/**
 * Ukrainian: spoken in Ukraine. A stranger is «ви», and a name stands in the
 * nominative — as a subject, after a dash or a colon, or in apposition to
 * «місто», which takes the case instead.
 */
const UK: Language = {
  locale: 'uk',
  name: 'Ukrainian',
  join: ' ',
  compass: [
    'на північ звідси', 'на північний схід звідси', 'на схід звідси', 'на південний схід звідси',
    'на південь звідси', 'на південний захід звідси', 'на захід звідси', 'на північний захід звідси',
  ],
  lines: {
    morning: [
      ['Доброго ранку!', 'Good morning!'],
      ['Добрий ранок!', 'Morning!'],
      ['Доброго ранку! Гарно день починається, правда?', "Good morning! Nice start to the day, isn't it?"],
      ['О, вітаю! Доброго ранку.', 'Oh, hello! Good morning.'],
    ],
    afternoon: [
      ['Добрий день!', 'Good afternoon!'],
      ['Доброго дня!', 'Good day!'],
      ['Вітаю! Гарна сьогодні днина.', "Hello! It's a lovely day today."],
      ['О, привіт! Тобто добрий день.', 'Oh, hi! I mean, good afternoon.'],
    ],
    evening: [
      ['Добрий вечір!', 'Good evening!'],
      ['Доброго вечора!', 'Evening!'],
      ['Вітаю! Гарний вечір для прогулянки.', 'Hello! A nice evening for a walk.'],
      ['О, добрий вечір вам!', 'Oh, good evening to you!'],
    ],
    night: [
      ['Добрий вечір! Уже пізно, правда?', "Good evening! It's late, isn't it?"],
      ['Ой! Ви мене налякали. Добрий вечір!', 'Oh! You gave me a fright. Good evening!'],
      ['Вітаю! Нічна прогулянка?', 'Hello! Out for a night walk?'],
      ['Добрий вечір! Чи вже ранок?', 'Good evening! Or is it morning already?'],
    ],
    again: [
      ['О, знову ви! Вітаю!', "Oh, it's you again! Hello!"],
      ['Знову до нас? Раді бачити.', 'Back again? Good to see you.'],
      ['Ще раз вітаю!', 'Hello again!'],
      ['Ми вже знайомі! Досі гуляєте?', "We've met already! Still wandering about?"],
      ['А, це ви! Знайшли дорогу?', 'Ah, it is you! Did you find your way?'],
    ],
    welcome: [
      ['Ласкаво просимо до міста {town}!', 'Welcome to {town}!'],
      ['Це місто {town}. Ви до нас у гості?', 'This is {town}. Are you visiting?'],
      ['Уперше в місті {town}?', 'First time in {town}?'],
      ['Гарний день ви обрали, щоб побачити місто {town}.', 'You picked a good day to see {town}.'],
      ['Заходьте, заходьте! Місто {town} завжди радо гостям.', 'Come in, come in! {town} is always glad of guests.'],
      ['То що привело вас до міста {town}?', 'So, what brings you to {town}?'],
    ],
    capitalHere: [
      ['Місто {town} — столиця нашої країни.', '{town} is the capital of our country.'],
      ['Це столиця, між іншим. Усе найважливіше відбувається тут.', 'This is the capital, you know. Everything important happens here.'],
      ['Тут засідає уряд. Навколо поважні люди в костюмах.', 'The government sits here. Important people in suits everywhere.'],
      ['Столиця є столиця: життя тут не зупиняється ні на хвилину.', "A capital is a capital: life here doesn't stop for a minute."],
    ],
    capitalThere: [
      ['Наша столиця — {capital}. Там варто побувати.', "Our capital is {capital}. It's worth a visit."],
      ['Ви вже були в столиці? Це {capital}.', "Have you been to the capital yet? That's {capital}."],
      ['{capital} думає, що керує країною. Ну, так воно і є.', '{capital} thinks it runs the country. Well, it does.'],
      ['{capital} — велике місто, але мені й тут добре.', "{capital} is a big city, but I'm happy right here."],
    ],
    big: [
      ['Це велике місто. Тут легко заблукати!', "It's a big city. Easy to get lost here!"],
      ['Стільки людей! Можна все життя прожити й не знати всіх вулиць.', 'So many people! You could live here all your life and not know every street.'],
      ['Затори тут, чесно кажучи, жахливі. Зате завжди щось відбувається.', "The traffic jams are awful, honestly. But there's always something going on."],
      ['Велике місто ніколи не зупиняється. Люблю його — здебільшого.', 'A big city never stops. I love it, mostly.'],
    ],
    middling: [
      ['Не велике й не мале. Саме те, що треба.', 'Not big, not small. Just right.'],
      ['Усе є, і все можна обійти пішки.', 'It has everything, and you can walk all of it.'],
      ['Місто {town} якраз доброго розміру: за день-два все побачите.', "{town} is just the right size: you'll see it all in a day or two."],
      ['Усі скаржаться, що тут нудно, а виїжджати ніхто не хоче.', 'Everyone complains it is dull here, and nobody wants to leave.'],
    ],
    small: [
      ['Це невелике містечко. Тут усі одне одного знають.', "It's a small town. Everybody knows everybody here."],
      ['Чхнете на одному кінці вулиці — на іншому скажуть «будьте здорові».', 'Sneeze at one end of the street and they say "bless you" at the other.'],
      ['У місті {town} мало що відбувається, і нас це влаштовує.', 'Not much happens in {town}, and that suits us fine.'],
      ['Ви тут найцікавіша подія за тиждень!', "You're the most exciting thing to happen here all week!"],
    ],
    coast: [
      ['Ми живемо біля води. Риба тут дуже смачна.', 'We live by the water. The fish here is delicious.'],
      ['Підіть подивіться на воду. Вона щодня інша.', 'Go and look at the water. It is different every day.'],
      ['Відчуваєте? Це море пахне. Ніколи не набридає.', 'Smell that? That is the sea. You never tire of it.'],
      ['Човни виходять удосвіта, а ввечері — свіжа риба на столі.', 'The boats go out at dawn, and by evening there is fresh fish on the table.'],
    ],
    inland: [
      ['Море далеко, але земля тут гарна.', 'The sea is far away, but the land here is beautiful.'],
      ['Пляжу немає, вже вибачте. Зате які поля!', 'No beach, sorry about that. But look at those fields!'],
      ['Море? Туди, чесно кажучи, далеко їхати.', "The sea? To be honest, it's a long way to go."],
      ['Тут усе тримається на землі. Добра земля — добрі люди.', 'Here everything rests on the land. Good land, good people.'],
    ],
    high: [
      ['Ми тут високо. Не поспішайте, повітря розріджене.', "We're high up here. Take it slowly, the air is thin."],
      ['У горах найбільше багатство — краєвид.', 'In the mountains, the view is the greatest wealth.'],
      ['Тут у всіх міцні ноги: нічого рівного немає.', 'Everyone here has strong legs: nothing is flat.'],
      ['Дихайте глибше! До гір треба звикнути.', 'Breathe deeper! The mountains take getting used to.'],
    ],
    snowy: [
      ["Сніг дев'ять місяців на рік. Решту три скаржимося на багнюку.", 'Snow nine months a year. The other three, we complain about the mud.'],
      ['Усе біле-біле. Вам би взуття тепліше.', 'Everything is white as white. You could use warmer boots.'],
      ['Ми холоду не боїмося. Він відлякує туристів — присутніх це не стосується!', "We don't mind the cold. It scares off the tourists. Present company excepted!"],
      ['Коли сніг свіжий, так тихо, що чутно власні думки.', 'When the snow is fresh, it is so quiet you can hear your own thoughts.'],
    ],
    forest: [
      ['Ліс тут на багато днів дороги. Не сходьте зі стежки!', 'The forest goes on for days here. Stay on the path!'],
      ['Прогуляйтеся лісом — голова прояснюється.', 'Take a walk in the woods. It clears the head.'],
      ['Восени всі ходять по гриби та ягоди.', 'In autumn everyone goes out for mushrooms and berries.'],
      ['Дерева, дерева і знову дерева. Ні на що не проміняю.', "Trees, trees and more trees. I wouldn't trade it for anything."],
    ],
    desert: [
      ['Тут пісок, скільки сягає око.', 'Out here it is sand as far as the eye can see.'],
      ['Пийте більше води. Пустеля помилок не прощає.', 'Drink plenty of water. The desert does not forgive mistakes.'],
      ['Ночі в пустелі холодні, між іншим. Ніхто не вірить.', 'Desert nights are cold, you know. Nobody believes it.'],
      ['Дочекайтеся ночі: зірок тут мільйони.', 'Wait for the night: there are millions of stars out here.'],
    ],
    plains: [
      ['Навколо рівний степ — негоду видно за день.', 'Flat steppe all round: you can see bad weather a day away.'],
      ['Небо тут величезне, і вітру ніщо не заважає.', 'The sky is huge here, and nothing stops the wind.'],
      ['Добрі пасовища навколо. Обережно з отарами.', 'Good grazing all round. Watch out for the flocks.'],
      ['Трава аж до обрію, як зелене море.', 'Grass right to the horizon, like a green sea.'],
    ],
    tropical: [
      ['Тут усе росте: встроміть палицю — виросте дерево.', 'Everything grows here: push a stick in the ground and a tree comes up.'],
      ['Як уже дощ, то злива. А потім раз — і сонце.', 'When it rains, it pours. Then, just like that, the sun.'],
      ['Скуштуйте фрукти на ринку. Таких ви ще не їли.', "Taste the fruit at the market. You've never had anything like it."],
      ['Цілий рік зелено. Зима? А що таке зима?', "Green all year round. Winter? What's winter?"],
    ],
    landmark: [
      ["{landmark} — обов'язково подивіться! Це приблизно за {km} км {dir}.", "{landmark}, you must see it! It's about {km} km {dir}."],
      ['{landmark} — приблизно за {km} км {dir}. Туди варто дійти!', "{landmark} is about {km} km {dir}. It's worth the walk!"],
      ['Усі їдуть подивитися — {landmark}. Це кілометрів за {km} {dir}.', "Everybody goes to see it: {landmark}. It's some {km} km {dir}."],
      ['Маєте вільний день? Тоді вам сюди: {landmark}, приблизно {km} км {dir}.', 'Got a free day? Then this is for you: {landmark}, about {km} km {dir}.'],
    ],
    landmarkNear: [
      ['{landmark} зовсім поруч. Не пропустите!', "{landmark} is very close. You can't miss it!"],
      ['{landmark} — буквально за рогом. Уже були там?', '{landmark} is right round the corner. Have you been yet?'],
      ['Щодня бачимо: {landmark}. І все одно дух захоплює.', 'We see it every day: {landmark}. And it still takes our breath away.'],
      ['Тут поруч {landmark}. Ідіть зранку, поки немає натовпу.', '{landmark} is close by. Go in the morning, before the crowds.'],
    ],
    plane: [
      ['Там у полі стоїть літачок, {dir}. Якщо вмієте літати!', "There's a little plane in a field {dir}. If you can fly!"],
      ['Хтось лишив літак у полі {dir}. Не хочете політати?', 'Somebody left a plane in a field {dir}. Fancy a flight?'],
      ['Вмієте літати? Літак чекає {dir}.', 'Can you fly? A plane is waiting {dir}.'],
      ['Хочете побачити все згори? Літак стоїть {dir}.', "Want to see it all from above? There's a plane {dir}."],
    ],
    balloon: [
      ['У полі {dir} стоїть повітряна куля! Уявляєте, який краєвид?', "There's a hot-air balloon in a field {dir}! Imagine the view!"],
      ['Літали колись на повітряній кулі? Одна є {dir}.', 'Ever flown in a balloon? There is one {dir}.'],
      ['З поля {dir} піднімається повітряна куля. Це чарівно.', 'A balloon goes up from the field {dir}. It is magical.'],
      ['Давно мрію полетіти на кулі {dir}, та страшно!', "I've long dreamed of a flight in the balloon {dir}, but I'm scared!"],
    ],
    boat: [
      ['Біля води {dir} є човен, якщо хочете вийти в море.', "There's a boat by the water {dir}, if you want to go out."],
      ['Любите море? Човен стоїть {dir}. Тільки поверніть!', 'Like the sea? There is a boat {dir}. Just bring it back!'],
      ["Човен прив'язаний {dir}. Звідси можна допливти куди завгодно.", 'A boat is tied up {dir}. From here you could sail anywhere.'],
      ['Візьміть човен {dir} і подивіться на берег з води.', 'Take the boat {dir} and see the shore from the water.'],
    ],
    hot: [
      ['Сьогодні спекотно! Знайдіть тінь.', "It's hot today! Find some shade."],
      ['Ух, ну й спека! Випийте води.', 'Phew, what heat! Have some water.'],
      ['У таку спеку тільки в холодку сидіти.', 'In heat like this, all you can do is sit in the shade.'],
      ['У таку спекоту навіть собаки по хатах сидять.', 'In this heat even the dogs stay indoors.'],
      ['Спекотно, еге ж? А для нас це ще прохолодно!', "Hot, isn't it? And for us this is cool!"],
    ],
    cold: [
      ['Брр, сьогодні холодно! Одягніться тепліше.', "Brr, it's cold today! Wrap up warm."],
      ['Мороз! А де ваші рукавички?', 'Freezing! Where are your gloves?'],
      ['Так холодно, що носа вже не відчуваю.', "It's so cold I can't feel my nose any more."],
      ['Холодно? Зачекайте, ще вітер зніметься.', 'Cold? Just wait till the wind picks up.'],
      ['Випийте чогось гарячого — допомагає.', 'Have something hot to drink. It helps.'],
    ],
    mild: [
      ['Яка сьогодні чудова погода.', 'What lovely weather today.'],
      ['Ні спекотно, ні холодно. Краса, правда?', "Not hot, not cold. Lovely, isn't it?"],
      ['У такий день хочеться гуляти.', 'On a day like this you just want to be out walking.'],
      ['Погода — просто диво! Аби протрималася.', "The weather is a marvel! Let's hope it lasts."],
      ['Саме заради таких днів ми тут і живемо.', 'Days like this are why we live here.'],
    ],
    late: [
      ['Уже пізно. Уночі на вулицях тихо.', "It's late. The streets are quiet at night."],
      ['О такій порі на вулиці тільки коти. І ми!', 'At this hour only the cats are out. And us!'],
      ['Мені давно пора спати. А вам чого не спиться?', "I should have been in bed ages ago. Why aren't you asleep?"],
      ['Подивіться на зорі! Звідси їх найкраще видно.', 'Look at the stars! You see them best from here.'],
    ],
    early: [
      ['Рано ви встали! Найкраща пора дня.', "You're up early! The best time of day."],
      ['Пекарня щойно відчинилася. Ідіть на запах!', 'The bakery has just opened. Follow the smell!'],
      ['Рання пташка, еге ж? Місто ще не прокинулося.', "An early bird, eh? The town isn't even awake yet."],
      ['Люблю тут ранок, поки не почався галас.', 'I love the mornings here, before the noise starts.'],
    ],
    country: [
      ['{country} — чудова країна. Насолоджуйтеся!', '{country} is a wonderful country. Enjoy it!'],
      ['Ну як вам {country}?', 'So, how do you like {country}?'],
      ['{country} — це не лише столиця. Подивіться й глибинку!', "{country} isn't just the capital. See the countryside too!"],
      ['{country} — це цілий світ. Кожен куточок не схожий на інший.', '{country} is a whole world. No two corners are alike.'],
    ],
    dish: [
      ["{dish} — обов'язково скуштуйте, поки ви тут.", "{dish}: you have to try it while you're here."],
      ['Уже куштували? {dish} — це треба скуштувати!', 'Tried it yet? {dish} is a must!'],
      ['{dish} — смачніше, ніж у моєї мами, не буває.', '{dish}: nobody makes it better than my mother.'],
      ['Зголодніли? Спитайте, де тут {dish}. Не пошкодуєте.', "Hungry? Ask where to get {dish}. You won't regret it."],
    ],
    drink: [
      ["{drink} — ось що в нас п'ють. Скуштуйте перед від'їздом.", '{drink} is what we drink here. Try some before you leave.'],
      ['Після довгого дня немає нічого кращого, ніж {drink}.', 'After a long day, nothing beats {drink}.'],
      ['{drink} — не скуштувати просто не можна.', "{drink}: you simply can't leave without trying it."],
      ['Замовте по-місцевому: {drink}. Вас одразу полюблять.', "Order like a local: {drink}. They'll love you for it."],
    ],
    festival: [
      ['Приїжджайте на свято — {festival}. Це чудово!', 'Come back for the holiday, {festival}. It is wonderful!'],
      ['Найкраща пора тут — {festival}. Святкує вся країна.', 'The best time to be here is {festival}. The whole country celebrates.'],
      ['Чули про таке свято — {festival}? Вам би сподобалося.', "Have you heard of {festival}? You'd love it."],
      ['Щороку чекаю не дочекаюся: {festival}!', 'Every year I can hardly wait for it: {festival}!'],
    ],
    sport: [
      ['Тут головне — {sport}. Усі за цим уболівають.', 'Here it is all about {sport}. Everybody follows it.'],
      ['Любите спорт? У нас {sport} — справжня пристрасть.', 'Do you like sport? Here {sport} is a real passion.'],
      ['У день гри все місто говорить про одне: {sport}.', 'On a game day the whole town talks about one thing: {sport}.'],
      ['У нас у родині всі схиблені: {sport}. Бабуся, щоправда, тільки вболіває біля телевізора.', 'Our whole family is crazy about {sport}. Grandma just cheers at the TV.'],
    ],
    wonder: [
      ["Буде час — з'їздіть: {wonder}. Це незабутньо.", "If you have time, go and see {wonder}. It's unforgettable."],
      ['{wonder} — такого більше ніде у світі немає.', "{wonder}: there's nothing like it anywhere in the world."],
      ['{wonder} — це кожен має побачити хоч раз у житті.', '{wonder}: everyone should see it once in their life.'],
      ['У дитинстві мене туди возили: {wonder}. Досі сниться.', 'As a child I was taken to see {wonder}. I still dream about it.'],
    ],
    pride: [
      ['Ми дуже цим пишаємося: {pride}.', 'We are very proud of this: {pride}.'],
      ['Не їдьте, не дізнавшись, що таке {pride}. Це про нас.', "Don't leave without learning about {pride}. It's who we are."],
      ['Знаєте, чим ми пишаємося? {pride}.', 'You know what we are proud of? {pride}.'],
      ['Спитайте будь-кого: {pride} — це розмова на кілька годин.', 'Ask anyone: {pride} is a conversation that lasts for hours.'],
    ],
    proverb: [
      ['Як у нас кажуть: «{proverb}»', 'As we say here: “{proverb}”'],
      ['Бабуся завжди казала: «{proverb}»', 'My grandmother always said: “{proverb}”'],
      ['Є в нас приказка: «{proverb}»', 'We have a saying: “{proverb}”'],
      ['Знаєте приказку? «{proverb}»', 'Do you know the saying? “{proverb}”'],
    ],
    chat: [
      ['Звідки ви? Ви ж не звідси.', "Where are you from? You're not from here, are you?"],
      ['Не поспішайте, роздивіться. Тут є що побачити.', 'Take your time and look around. There is plenty to see.'],
      ['Подорожуєте самі? Сміливо.', "Travelling on your own? That's brave."],
      ['Схоже, ви здалеку йдете.', 'Looks like you have come a long way on foot.'],
      ['Заблукаєте — питайте. Люди тут привітні.', 'If you get lost, just ask. People here are friendly.'],
      ['А де вам поки найбільше сподобалося?', 'Where have you liked best so far?'],
      ['Усе життя мрію помандрувати. Може, колись.', 'All my life I have dreamed of travelling. Maybe one day.'],
      ['Мапа є? Без мапи нікуди.', "Got a map? You can't go anywhere without a map."],
    ],
    childGreet: [
      ['Привіт!', 'Hi!'],
      ['Добрий день! А ви хто?', 'Hello! Who are you?'],
      ['Привіт! Ого, ви до неба!', "Hi! Wow, you're as tall as the sky!"],
      ['Привіт-привіт!', 'Hello, hello!'],
    ],
    childChat: [
      ['Я дуже швидко бігаю! Показати? Потім покажу.', "I can run really fast! Want to see? I'll show you later."],
      ['Ви приїжджі? Мій друг каже, що всі приїжджі багаті.', 'Are you from out of town? My friend says out-of-towners are all rich.'],
      ['А в мене вчора зуб випав! Дивіться! Ой, його ж не видно.', "A tooth fell out yesterday! Look! Oh, you can't see it."],
      ['Мама каже, що з чужими не можна говорити. Але з вами, мабуть, можна.', "Mum says I mustn't talk to strangers. But you're probably all right."],
      ['У вас є собака? Я хочу собаку!', 'Do you have a dog? I want a dog!'],
      ['Коли виросту, облечу на літаку весь світ!', "When I grow up I'm going to fly a plane all round the world!"],
      ['Ви знаєте якісь ігри? Я знаю купу ігор.', 'Do you know any games? I know loads of games.'],
    ],
    childBye: [
      ['Па-па!', 'Bye bye!'],
      ['Бувайте! Приходьте ще гратися!', 'Bye! Come back and play!'],
      ['Мені пора, мама кличе!', 'I have to go, Mum is calling!'],
      ['До зустрічі! Не сумуйте!', "See you! Don't be sad!"],
    ],
    grumpyGreet: [
      ['Гм. Чого треба?', 'Hm. What do you want?'],
      ['Ну? Що таке?', 'Well? What is it?'],
      ['Ох. Знову туристи.', 'Oh. Tourists again.'],
      ['Гм. Ну, добрий день, чи що.', 'Hm. Good day, I suppose.'],
    ],
    grumpyChat: [
      ['Раніше тут було краще, поки всі не почали приїжджати.', 'It was better here before everybody started coming.'],
      ['Усе вдвічі дорожче, ніж раніше.', 'Everything costs twice what it used to.'],
      ['Не стійте посеред тротуару, тут люди живуть.', "Don't stand in the middle of the pavement. People live here."],
      ['Молодь нині вся в телефонах.', 'Young people these days are always on their phones.'],
      ['Не розумію, навіщо сюди їдуть. Дивитися нема на що.', "I don't see why people come here. There's nothing to see."],
    ],
    grumpyBye: [
      ['Ну все, ідіть уже.', 'Right, off you go.'],
      ['Гаразд, не смію затримувати.', "Well, I won't keep you."],
      ['Гм. До побачення.', 'Hm. Goodbye.'],
      ['Дивіться під ноги. І хвіртку зачиніть.', 'Watch your step. And shut the gate.'],
    ],
    elderChat: [
      ['Замолоду тут навколо були самі поля.', 'When I was young, this was all fields.'],
      ['Усе життя тут живу. Вісімдесят років! Уявляєте?', 'I have lived here all my life. Eighty years! Can you imagine?'],
      ['За наших часів усі ходили пішки. Ви теж пішки? Оце правильно!', 'In our day everybody walked. You walk too? Good for you!'],
      ['Онуки тепер за кордоном живуть. Щонеділі дзвонять.', 'My grandchildren live abroad now. They call every Sunday.'],
      ['Усе так швидко змінюється. А старі вулички ті самі.', 'Everything changes so fast. But the old streets stay the same.'],
    ],
    chattyChat: [
      ['Ой, як я люблю мандрівників! Розповідайте все! Ні, стривайте, спершу я.', 'Oh, I love travellers! Tell me everything! No, wait, me first.'],
      ['Мій двоюрідний брат якось поїхав мандрувати. Повернувся з бородою і з дружиною!', 'My cousin went travelling once. He came back with a beard and a wife!'],
      ['Друзі кажуть, що я можу балакати цілий день. І таки мають рацію!', "My friends say I could chat all day. And they're right!"],
      ['Ви сьогодні їли? Вигляд у вас голодний. Хоча мені всі здаються голодними.', 'Have you eaten today? You look hungry. Mind you, everyone looks hungry to me.'],
      ['Скажу по секрету: найкращий краєвид на місто — з пагорба за церквою.', "Here's a secret: the best view of town is from the hill behind the church."],
    ],
    bye: [
      ['До побачення! Щасливої дороги.', 'Goodbye! Have a good journey.'],
      ['Усього доброго! Гарної подорожі.', 'All the best! Have a good trip.'],
      ['Щасти в дорозі!', 'Good luck on the road!'],
      ['Ну, бувайте! Заходьте ще.', 'Well, take care! Drop by again.'],
      ['Приємно було поговорити. Бережіть себе!', 'Nice talking to you. Look after yourself!'],
      ['Ну, рушайте! Стільки всього ще попереду.', "Off you go, then! There's so much still ahead."],
    ],
  },
  countries: {
    // Every fact in the nominative, lower-case unless a name: the templates put it as a subject, after a dash or a colon.
    UKR: {
      dish: ['борщ', 'borscht'],
      drink: ['узвар', 'uzvar, the dried-fruit drink'],
      festival: ['Купальська ніч', 'Kupala Night, the midsummer feast'],
      sport: ['футбол', 'football'],
      wonder: ['Карпати', 'the Carpathian Mountains'],
      pride: ['вишиванка', 'the vyshyvanka, the embroidered shirt'],
      proverb: ['Тихше їдеш — далі будеш', 'The slower you ride, the further you get'],
    },
  },
};

export default UK;
