import type { Language } from '../phrases.ts';

const UR: Language = {
  locale: 'ur',
  name: 'Urdu',
  rtl: true,
  join: ' ',
  compass: ['شمال میں', 'شمال مشرق میں', 'مشرق میں', 'جنوب مشرق میں', 'جنوب میں', 'جنوب مغرب میں', 'مغرب میں', 'شمال مغرب میں'],
  lines: {
    morning: [
      ['صبح بخیر!', 'Good morning!'],
      ['السلام علیکم! کیا خوبصورت صبح ہے۔', 'Peace be upon you! What a lovely morning.'],
      ['صبح بخیر! آج کا دن اچھا گزرے۔', 'Good morning! Have a good day.'],
      ['ارے، سلام! صبح بخیر۔', 'Oh, hello! Good morning.'],
    ],
    afternoon: [
      ['السلام علیکم!', 'Peace be upon you!'],
      ['آداب!', 'Greetings!'],
      ['ارے، سلام! کیا حال ہے؟', 'Oh, hello! How are things?'],
      ['سلام! دوپہر کیسی گزر رہی ہے؟', "Hello! How's the afternoon going?"],
    ],
    evening: [
      ['شام بخیر!', 'Good evening!'],
      ['السلام علیکم! کیا سہانی شام ہے۔', 'Peace be upon you! What a pleasant evening.'],
      ['سلام! سیر کے لیے اچھی شام ہے۔', 'Hello! A nice evening for a stroll.'],
      ['ارے، شام بخیر!', 'Oh, good evening!'],
    ],
    night: [
      ['شام بخیر! کافی دیر ہو گئی ہے، ہے نا؟', "Good evening! It's quite late, isn't it?"],
      ['ارے! آپ نے تو ڈرا دیا۔ سلام!', 'Oh! You gave me a fright. Hello!'],
      ['سلام! رات کی سیر ہو رہی ہے؟', 'Hello! Out for a night stroll?'],
      ['اتنی رات گئے؟ خیر، سلام!', 'So late at night? Well, hello!'],
    ],
    again: [
      ['ارے، پھر آپ! سلام!', 'Oh, you again! Hello!'],
      ['دوبارہ ملاقات ہو گئی! بڑی خوشی ہوئی۔', "We've met again! What a pleasure."],
      ['پھر سے سلام!', 'Hello again!'],
      ['ہماری ملاقات ہو چکی ہے! سیر جاری ہے؟', "We've met before! Still exploring?"],
    ],
    welcome: [
      ['{town} میں خوش آمدید!', 'Welcome to {town}!'],
      ['یہ {town} ہے۔ گھومنے کا ارادہ ہے؟', 'This is {town}. Planning to look around?'],
      ['کیا {town} میں پہلی بار آنا ہوا؟', 'Is this your first time in {town}?'],
      ['آئیے، آئیے! {town} میں آپ کا استقبال ہے۔', 'Come in, come in! {town} welcomes you.'],
      ['تو {town} کیسے آنا ہوا؟', 'So, what brings you to {town}?'],
    ],
    capitalHere: [
      ['{town} ہمارے ملک کا دارالحکومت ہے۔', '{town} is the capital of our country.'],
      ['یہ دارالحکومت ہے۔ سب کچھ یہیں ہوتا ہے۔', 'This is the capital. Everything happens right here.'],
      ['دارالحکومت ہونے کی وجہ سے {town} میں ہر وقت رونق رہتی ہے۔', 'Being the capital, {town} is always lively.'],
      ['یہاں بڑے بڑے دفتر ہیں اور سوٹ والے لوگ!', 'Big offices here, and people in suits!'],
    ],
    capitalThere: [
      ['ہمارا دارالحکومت {capital} ہے۔ وہاں ضرور جائیے۔', 'Our capital is {capital}. Do go there.'],
      ['کیا {capital} جانے کا موقع ملا؟', 'Have you had a chance to go to {capital}?'],
      ['{capital} بڑا شہر ہے، مگر یہاں کی بات ہی اور ہے۔', '{capital} is a big city, but this place is something else.'],
      ['وقت ملے تو {capital} ضرور دیکھیے۔', 'If you get the time, do see {capital}.'],
    ],
    big: [
      ['یہ ایک بڑا شہر ہے۔ یہاں راستہ بھٹکنا آسان ہے!', "It's a big city. Easy to lose your way here!"],
      ['کتنے لوگ! یہاں ساری عمر رہ کر بھی ہر گلی کا پتا نہیں چلتا۔', 'So many people! You could live here a lifetime and not know every lane.'],
      ['یہ ٹریفک، توبہ! مگر یہاں ہر وقت کچھ نہ کچھ ہوتا رہتا ہے۔', 'This traffic, good grief! But something is always going on here.'],
      ['بڑا شہر کبھی نہیں رکتا۔ یہی تو مزہ ہے۔', "A big city never stops. That's the fun of it."],
    ],
    middling: [
      ['نہ بہت بڑا، نہ بہت چھوٹا۔ بالکل ٹھیک۔', 'Not too big, not too small. Just right.'],
      ['ضرورت کی ہر چیز ہے، اور پیدل بھی گھوما جا سکتا ہے۔', 'It has everything you need, and you can walk it too.'],
      ['ایک دو دن میں پورا {town} دیکھا جا سکتا ہے۔', 'You can see all of {town} in a day or two.'],
      ['سب کہتے ہیں یہاں بہت سکون ہے، پھر بھی کوئی جاتا نہیں!', 'Everyone says it is too quiet here, yet nobody leaves!'],
    ],
    small: [
      ['یہ ایک چھوٹی سی جگہ ہے۔ یہاں سب ایک دوسرے کو جانتے ہیں۔', 'This is a small place. Everybody knows everybody here.'],
      ['چھوٹی سی جگہ ہے۔ چھینک آئے تو پوری گلی کو پتا چل جاتا ہے۔', 'Tiny place. Sneeze and the whole lane knows about it.'],
      ['{town} میں زیادہ کچھ نہیں ہوتا، اور ہمیں یہی پسند ہے۔', 'Not much happens in {town}, and we like it that way.'],
      ['اس ہفتے کی سب سے بڑی خبر تو آپ ہیں!', "You're the biggest news this week!"],
    ],
    coast: [
      ['ہم یہاں پانی کے کنارے رہتے ہیں۔ یہاں کی مچھلی بہت اچھی ہے۔', 'We live by the water here. The fish is very good.'],
      ['جا کر سمندر دیکھیے۔ ہر روز الگ لگتا ہے۔', 'Go and look at the sea. It looks different every day.'],
      ['یہ خوشبو محسوس ہو رہی ہے؟ یہ سمندر کی ہوا ہے۔', 'Can you smell that? That is the sea air.'],
      ['کشتیاں صبح سویرے نکلتی ہیں اور تازہ مچھلی لے کر لوٹتی ہیں۔', 'The boats go out at dawn and come back with fresh fish.'],
    ],
    inland: [
      ['سمندر یہاں سے دور ہے، لیکن یہ علاقہ بہت خوبصورت ہے۔', 'The sea is far from here, but this area is very beautiful.'],
      ['یہاں ساحل تو نہیں، مگر یہ کھیت دیکھیے!', 'No beach here, but look at these fields!'],
      ['سمندر؟ وہ تو بہت دور ہے۔', 'The sea? That is very far away.'],
      ['یہاں زمین ہی سب کچھ ہے۔ اچھی مٹی، اچھے لوگ۔', 'Here the land is everything. Good soil, good people.'],
    ],
    high: [
      ['ہم یہاں کافی اونچائی پر ہیں۔ آہستہ چلیے، ہوا پتلی ہے۔', 'We are quite high up here. Walk slowly, the air is thin.'],
      ['ان پہاڑوں میں سب سے بڑی دولت یہ نظارہ ہے۔', 'In these mountains, the view is our greatest wealth.'],
      ['یہاں رہنے والوں کی ٹانگیں مضبوط ہوتی ہیں۔ کچھ بھی ہموار نہیں!', 'People who live here have strong legs. Nothing is flat!'],
      ['سانس کا خیال رکھیے! پہاڑی ہوا کی عادت آہستہ آہستہ ہوتی ہے۔', 'Mind your breath! You get used to mountain air slowly.'],
    ],
    snowy: [
      ['سال کے نو مہینے برف، باقی تین مہینے کیچڑ کی شکایت۔', 'Snow nine months a year, and three months of complaining about mud.'],
      ['ہر طرف سفید ہے۔ ان جوتوں سے مضبوط جوتے چاہییں۔', 'White everywhere. You need sturdier shoes than those.'],
      ['تازہ برف گرے تو اتنی خاموشی ہوتی ہے کہ اپنے خیال سنائی دیتے ہیں۔', 'When fresh snow falls, it is so quiet you can hear your own thoughts.'],
      ['سردی سے ہم نہیں ڈرتے۔ گرم چائے ہو تو سب ٹھیک۔', "We don't fear the cold. With hot tea, all is well."],
    ],
    forest: [
      ['یہاں جنگل میلوں تک پھیلا ہے۔ راستے سے مت ہٹیے!', 'The forest here stretches for miles. Stay on the path!'],
      ['جنگل میں ذرا سیر کیجیے، دماغ تازہ ہو جاتا ہے۔', 'Take a walk in the forest, it refreshes the mind.'],
      ['ہر خزاں میں ہم کھمبیاں اور بیر چننے جاتے ہیں۔', 'Every autumn we go picking mushrooms and berries.'],
      ['درخت ہی درخت۔ ایسی جگہ اور کہاں!', 'Trees and more trees. Where else is there a place like this!'],
    ],
    desert: [
      ['یہاں جہاں تک نظر جائے، ریت ہی ریت ہے۔', 'Here there is sand as far as the eye can see.'],
      ['پانی خوب پیجیے۔ صحرا معاف نہیں کرتا۔', 'Drink plenty of water. The desert does not forgive.'],
      ['صحرا کی راتیں ٹھنڈی ہوتی ہیں۔ کوئی یقین نہیں کرتا۔', 'Desert nights are cold. Nobody believes it.'],
      ['آج رات تاروں کا انتظار کیجیے۔ یہاں لاکھوں نظر آتے ہیں۔', 'Wait for the stars tonight. You can see hundreds of thousands here.'],
    ],
    plains: [
      ['میلوں تک ہموار زمین۔ آتا ہوا موسم ایک دن پہلے دکھائی دیتا ہے۔', 'Flat land for miles. You see the weather coming a day ahead.'],
      ['یہاں آسمان بہت بڑا ہے۔ ہوا کو روکنے والا کچھ نہیں۔', 'The sky is huge here. Nothing stops the wind.'],
      ['سب چراگاہیں ہیں۔ ریوڑوں سے بچ کر چلیے۔', 'It is all pasture. Keep clear of the herds.'],
      ['گھاس کا کوئی انت نہیں۔ جیسے ہرا سمندر ہو۔', 'The grass has no end. Like a green sea.'],
    ],
    tropical: [
      ['یہاں سب کچھ اگ آتا ہے۔ لکڑی گاڑ دیجیے، درخت بن جائے گی۔', 'Everything grows here. Plant a stick and it will become a tree.'],
      ['بارش آتی ہے تو خوب آتی ہے، پھر اچانک رک جاتی ہے۔', 'When the rain comes it really pours, then suddenly it stops.'],
      ['بازار کے پھل ضرور چکھیے۔ ایسا ذائقہ کہیں نہیں ملے گا۔', "Do taste the fruit at the market. You won't find a taste like it."],
      ['یہاں سارا سال ہریالی رہتی ہے۔ سردی؟ وہ کیا ہوتی ہے؟', 'It is green here all year. Winter? What is that?'],
    ],
    landmark: [
      ['{landmark} ضرور دیکھیے! یہ یہاں سے تقریباً {km} کلومیٹر {dir} ہے۔', "Do see {landmark}! It's about {km} km from here, {dir}."],
      ['کیا {landmark} دیکھنے کا موقع ملا؟ {km} کلومیٹر {dir}، ہر قدم کے قابل۔', 'Have you had a chance to see {landmark}? {km} km {dir}, worth every step.'],
      ['سب {landmark} دیکھنے جاتے ہیں۔ تقریباً {km} کلومیٹر {dir}۔', 'Everyone goes to see {landmark}. About {km} km {dir}.'],
      ['پرانی جگہوں کا شوق ہو تو {landmark} یہاں سے {km} کلومیٹر {dir} ہے۔', 'If you love old places, {landmark} is {km} km from here, {dir}.'],
    ],
    landmarkNear: [
      ['{landmark} بس یہیں قریب ہے۔ ضرور جائیے!', '{landmark} is just nearby. Do go!'],
      ['کیا {landmark} جانا ہوا؟ بالکل پاس ہے۔', 'Have you been to {landmark}? It is very close.'],
      ['روز {landmark} دیکھتے ہیں، پھر بھی دل نہیں بھرتا۔', 'We see {landmark} every day and never tire of it.'],
      ['صبح سویرے {landmark} جائیے، رش سے پہلے۔ بس قریب ہی ہے۔', 'Go to {landmark} early, before the crowds. It is close by.'],
    ],
    plane: [
      ['{dir} ایک کھیت میں چھوٹا جہاز کھڑا ہے، اگر اڑانا آتا ہو!', "There's a little plane in a field {dir}, if you can fly!"],
      ['کسی نے {dir} کھیت میں جہاز چھوڑ دیا ہے۔ ایک اڑان ہو جائے؟', 'Somebody left a plane in a field {dir}. How about a flight?'],
      ['جہاز اڑانا آتا ہے؟ {dir} ایک جہاز انتظار میں ہے۔', 'Can you fly? A plane is waiting {dir}.'],
      ['سب کچھ اوپر سے دیکھنا ہو تو {dir} ایک جہاز ہے۔', "If you want to see it all from above, there's a plane {dir}."],
    ],
    balloon: [
      ['{dir} کھیت میں گرم ہوا کا غبارہ ہے! ذرا نظارہ سوچیے۔', "There's a hot-air balloon in a field {dir}! Just imagine the view."],
      ['کبھی غبارے میں اڑان بھری؟ {dir} ایک موجود ہے۔', 'Ever flown in a balloon? There is one {dir}.'],
      ['{dir} کھیت سے غبارہ اڑتا ہے۔ جادو سا لگتا ہے۔', 'A balloon rises from a field {dir}. It feels like magic.'],
      ['اس غبارے میں بیٹھنے کا بڑا شوق ہے، پر ڈر لگتا ہے!', "I'd love to ride that balloon, but it scares me!"],
    ],
    boat: [
      ['{dir} پانی کے کنارے ایک کشتی ہے، اگر سیر کرنی ہو۔', "There's a boat by the water {dir}, if you want an outing."],
      ['سمندر پسند ہے تو {dir} ایک کشتی ہے۔ بس واپس کر دیجیے گا!', "If you love the sea, there's a boat {dir}. Just bring it back!"],
      ['{dir} ایک کشتی بندھی ہے۔ یہاں سے کہیں بھی جایا جا سکتا ہے۔', 'A boat is tied up {dir}. From here you can go anywhere.'],
      ['کشتی لیجیے اور ساحل کو پانی سے دیکھیے۔', 'Take the boat and see the coast from the water.'],
    ],
    hot: [
      ['آج بہت گرمی ہے! تھوڑا سایہ ڈھونڈ لیجیے۔', "It's very hot today! Find a bit of shade."],
      ['اف، کتنی گرمی ہے! تھوڑا پانی پی لیجیے۔', 'Ugh, what heat! Have some water.'],
      ['اس گرمی میں بس سائے میں بیٹھا جا سکتا ہے۔', 'In this heat all you can do is sit in the shade.'],
      ['اس گرمی میں تو کتے بھی باہر نہیں نکلتے۔', "In this heat even the dogs don't go out."],
      ['گرمی ہے نا؟ ٹھنڈی لسی پیجیے، جان آ جائے گی۔', "Hot, isn't it? Have a cold lassi, it'll bring you back to life."],
    ],
    cold: [
      ['برر، آج سردی ہے! گرم کپڑے پہن لیجیے۔', "Brr, it's cold today! Put on warm clothes."],
      ['کتنی ٹھنڈ ہے! دستانے کہاں ہیں؟', 'How cold it is! Where are your gloves?'],
      ['اتنی سردی ہے کہ ناک سن ہو گئی۔', "It's so cold my nose has gone numb."],
      ['یہ سردی؟ ابھی تو ہوا بھی نہیں چلی!', "This is cold? The wind hasn't even started!"],
      ['گرم چائے پیجیے، سردی بھاگ جائے گی۔', 'Have some hot tea, it will chase the cold away.'],
    ],
    mild: [
      ['آج موسم کتنا اچھا ہے۔', 'How nice the weather is today.'],
      ['نہ گرمی نہ سردی۔ کیا بہترین دن ہے!', 'Not hot, not cold. What a perfect day!'],
      ['ایسے دن تو باہر ہی رہنے کو دل کرتا ہے۔', 'On days like this you just want to be outside.'],
      ['کیا موسم ہے! اللہ کرے ایسا ہی رہے۔', 'What weather! May it stay like this.'],
      ['ایسے ہی دنوں کے لیے تو ہم یہاں رہتے ہیں۔', 'Days like this are why we live here.'],
    ],
    late: [
      ['دیر ہو گئی ہے۔ رات کو سڑکیں پرسکون رہتی ہیں۔', "It's late. The streets are calm at night."],
      ['اس وقت تو بس بلیاں باہر ہوتی ہیں۔ اور ہم!', 'At this hour only the cats are out. And us!'],
      ['یہ تو سونے کا وقت ہے۔ نیند نہیں آ رہی؟', "It's time for bed. Can't sleep?"],
      ['تارے دیکھیے! یہاں سے سب سے اچھے نظر آتے ہیں۔', 'Look at the stars! They look best from here.'],
    ],
    early: [
      ['اتنی صبح؟ دن کا سب سے اچھا وقت یہی ہے۔', 'So early? This is the best time of the day.'],
      ['نان بائی نے ابھی تنور گرم کیا ہے۔ خوشبو کے پیچھے چلیے!', 'The baker has just heated the oven. Follow the smell!'],
      ['شہر ابھی جاگا بھی نہیں۔', "The town hasn't even woken up yet."],
      ['شور شروع ہونے سے پہلے کی صبح بہت پیاری ہوتی ہے۔', 'The morning before the noise starts is lovely.'],
    ],
    country: [
      ['{country} ایک خوبصورت ملک ہے۔ لطف اٹھائیے!', '{country} is a beautiful country. Enjoy it!'],
      ['{country} اب تک کیسا لگا؟', 'How do you like {country} so far?'],
      ['ہو سکے تو پورا {country} گھومیے۔ ہر کونا الگ ہے۔', 'If you can, travel all over {country}. Every corner is different.'],
      ['{country} میں پہاڑ بھی ہیں، صحرا بھی، سمندر بھی۔', '{country} has mountains, deserts and the sea.'],
    ],
    dish: [
      ['یہاں ہیں تو {dish} ضرور کھائیے۔', "While you're here, do eat {dish}."],
      ['کیا {dish} چکھنے کا موقع ملا؟ نہیں؟ پھر تو ضرور!', 'Have you had a chance to taste {dish}? No? Then you must!'],
      ['جو {dish} میری امی بناتی ہیں، اس کا کوئی جواب نہیں۔', 'The {dish} my mother makes has no equal.'],
      ['بھوک لگی ہے تو {dish} کھائیے۔ پچھتانا نہیں پڑے گا۔', "If you're hungry, have {dish}. You won't regret it."],
    ],
    drink: [
      ['جانے سے پہلے {drink} پیجیے۔ یہاں یہی پیا جاتا ہے۔', 'Have some {drink} before you go. It is what we drink here.'],
      ['دن کے آخر میں {drink} کا کوئی مقابلہ نہیں۔', 'At the end of the day nothing compares with {drink}.'],
      ['زندگی کا مزہ لینا ہو تو {drink} ضرور پیجیے۔', 'If you want to enjoy life, do drink {drink}.'],
      ['مقامی لوگوں کی طرح {drink} منگوائیے، سب خوش ہو جائیں گے۔', 'Order {drink} like a local and everyone will be delighted.'],
    ],
    festival: [
      ['{festival} پر دوبارہ آئیے۔ بہت رونق ہوتی ہے!', 'Come back for {festival}. It is so lively!'],
      ['یہاں آنے کا سب سے اچھا وقت {festival} ہے۔ پورا ملک خوشیاں مناتا ہے۔', 'The best time to come is {festival}. The whole country celebrates.'],
      ['{festival} کا سنا ہے؟ بہت مزہ آئے گا۔', "Have you heard of {festival}? You'd have a great time."],
      ['ہر سال {festival} کا بے چینی سے انتظار رہتا ہے۔', 'Every year we wait impatiently for {festival}.'],
    ],
    sport: [
      ['یہاں سب {sport} کے دیوانے ہیں۔', 'Everyone here is crazy about {sport}.'],
      ['{sport} پسند ہے؟ یہاں تو لوگ اس کے پیچھے پاگل ہیں۔', 'Do you like {sport}? People here are mad about it.'],
      ['میچ والے دن پورا شہر صرف {sport} کی باتیں کرتا ہے۔', 'On match day the whole town talks of nothing but {sport}.'],
      ['ہمارا پورا خاندان {sport} کھیلتا ہے۔ دادی بس شور مچاتی ہیں۔', 'Our whole family plays {sport}. Grandma just makes a racket.'],
    ],
    wonder: [
      ['وقت ہو تو {wonder} ضرور دیکھیے۔ ساری عمر یاد رہے گا۔', 'If you have time, do see {wonder}. You will remember it all your life.'],
      ['کیا {wonder} دیکھنے کا موقع ملا؟ دنیا میں اس جیسا کچھ نہیں۔', 'Have you had a chance to see {wonder}? Nothing in the world is like it.'],
      ['زندگی میں ایک بار {wonder} ضرور دیکھنا چاہیے۔', 'Everyone should see {wonder} once in their life.'],
      ['بچپن میں {wonder} دیکھنے گئے تھے۔ آج تک یاد ہے۔', 'We went to see {wonder} in my childhood. I still remember it.'],
    ],
    pride: [
      ['ہمیں {pride} پر بڑا فخر ہے۔', 'We are very proud of {pride}.'],
      ['{pride} کے بارے میں جانے بغیر مت جائیے۔ یہی ہماری پہچان ہے۔', "Don't leave without learning about {pride}. It is who we are."],
      ['پتا ہے ہمیں کس بات پر فخر ہے؟ {pride}۔', 'Do you know what we are proud of? {pride}.'],
      ['یہاں کسی سے بھی {pride} کا پوچھیے، گھنٹوں بات ہو گی۔', 'Ask anyone here about {pride} and the talk will go on for hours.'],
    ],
    proverb: [
      ['جیسا کہ ہم کہتے ہیں: "{proverb}"', 'As we say: “{proverb}”'],
      ['دادی ہمیشہ کہتی تھیں: "{proverb}"', 'Grandma always used to say: “{proverb}”'],
      ['ہمارے ہاں ایک کہاوت ہے: "{proverb}"', 'We have a saying: “{proverb}”'],
      ['یہ کہاوت سنی ہے؟ "{proverb}"', 'Have you heard this saying? “{proverb}”'],
    ],
    chat: [
      ['آپ کہاں سے ہیں؟', 'Where are you from?'],
      ['آرام سے گھومیے۔ یہاں دیکھنے کو بہت کچھ ہے۔', 'Look around at your ease. There is a lot to see here.'],
      ['اکیلے سفر؟ بڑی ہمت کی بات ہے۔', 'Travelling alone? That takes courage.'],
      ['لگتا ہے لمبا سفر طے کر کے آنا ہوا ہے۔', 'Looks like you have come a long way.'],
      ['راستہ بھول جائیں تو پوچھ لیجیے۔ یہاں کے لوگ مددگار ہیں۔', 'If you lose your way, just ask. People here are helpful.'],
      ['اب تک سب سے اچھی جگہ کون سی لگی؟', 'Which place have you liked best so far?'],
      ['آئیے، ایک کپ چائے ہو جائے!', "Come, let's have a cup of tea!"],
    ],
    childGreet: [
      ['ہیلو!', 'Hello!'],
      ['سلام! آپ کون ہیں؟', 'Hi! Who are you?'],
      ['واہ! آپ کا قد کتنا لمبا ہے!', "Wow! You're so tall!"],
      ['سلام سلام!', 'Hi, hi!'],
    ],
    childChat: [
      ['مجھے بہت تیز دوڑنا آتا ہے! دیکھنا ہے؟', 'I can run really fast! Want to see?'],
      ['آپ سیاح ہیں؟ میرا دوست کہتا ہے سیاح امیر ہوتے ہیں۔', 'Are you a tourist? My friend says tourists are rich.'],
      ['کل میرا دانت ٹوٹ گیا! دیکھیے! اوہ، نظر نہیں آ رہا۔', "My tooth came out yesterday! Look! Oh, you can't see it."],
      ['امی کہتی ہیں اجنبیوں سے بات نہیں کرنی۔ لیکن آپ کی مسکراہٹ اچھی ہے۔', "Mum says don't talk to strangers. But you have a nice smile."],
      ['آپ کے پاس کتا ہے؟ مجھے کتا چاہیے۔', 'Do you have a dog? I want a dog.'],
      ['بڑے ہو کر میرا خواب ہے جہاز میں پوری دنیا گھومنا!', 'When I grow up, my dream is to fly all round the world!'],
      ['چھپن چھپائی کھیلیں؟ باری آپ کی!', "Shall we play hide-and-seek? You're it!"],
    ],
    childBye: [
      ['خدا حافظ!', 'Bye!'],
      ['بائے بائے!', 'Bye bye!'],
      ['امی بلا رہی ہیں، جانا ہے!', 'Mum is calling, I have to go!'],
      ['پھر آئیے گا، ساتھ کھیلنے!', 'Come again, to play together!'],
    ],
    grumpyGreet: [
      ['ہوں۔ کیا چاہیے؟', 'Hm. What do you want?'],
      ['جی؟ کیا بات ہے؟', "Yes? What's the matter?"],
      ['اوہو۔ ایک اور سیاح۔', 'Oh dear. Another tourist.'],
      ['ہوں۔ سلام، خیر۔', 'Hm. Hello, I suppose.'],
    ],
    grumpyChat: [
      ['پہلے یہ جگہ بہتر تھی، جب اتنے لوگ نہیں آتے تھے۔', "This place was better before, when so many people didn't come."],
      ['ہر چیز دگنی مہنگی ہو گئی ہے۔ روٹی تک!', 'Everything costs double now. Even bread!'],
      ['فٹ پاتھ مت روکیے، یہاں لوگ رہتے ہیں۔', "Don't block the pavement, people live here."],
      ['آج کل کے بچے، ہر وقت موبائل میں گھسے رہتے ہیں۔', "Kids these days, always buried in their phones."],
      ['پتا نہیں لوگ یہاں کیوں آتے ہیں۔ دیکھنے کو ہے کیا؟', "I don't know why people come here. What is there to see?"],
    ],
    grumpyBye: [
      ['ٹھیک ہے۔ جائیے اب۔', 'Right. Off you go now.'],
      ['آپ کا وقت ضائع نہیں کرنا۔', "Mustn't waste your time."],
      ['ہوں۔ خدا حافظ۔', 'Hm. Goodbye.'],
      ['دھیان سے جائیے۔ اور دروازہ بند کر دیجیے۔', 'Go carefully. And shut the door.'],
    ],
    elderChat: [
      ['ہماری جوانی میں یہاں سب کھیت ہی کھیت تھے۔', 'In our youth this was all fields.'],
      ['ساری عمر یہیں گزری۔ اسی سال! یقین آتا ہے؟', 'A whole life spent right here. Eighty years! Can you believe it?'],
      ['ہمارے زمانے میں سب پیدل چلتے تھے۔', 'In our day everyone went on foot.'],
      ['پوتے پوتیاں باہر رہتے ہیں۔ ہر اتوار فون آتا ہے۔', 'The grandchildren live abroad. They phone every Sunday.'],
      ['زمانہ بہت تیزی سے بدلتا ہے، مگر پرانی گلیاں وہی ہیں۔', 'Times change so fast, but the old lanes are the same.'],
    ],
    chattyChat: [
      ['ارے، مسافروں سے مل کر بڑی خوشی ہوتی ہے! سب کچھ بتائیے۔ نہیں، رکیے، پہلے میری سنیے۔', 'Oh, I love meeting travellers! Tell me everything. No, wait, hear me out first.'],
      ['میرا کزن ایک بار سفر پر گیا تھا۔ داڑھی اور بیوی لے کر لوٹا!', 'My cousin went travelling once. Came back with a beard and a wife!'],
      ['دوست کہتے ہیں مجھ سے باتیں ختم ہی نہیں ہوتیں۔ ٹھیک ہی کہتے ہیں!', "My friends say I never run out of things to say. They're right!"],
      ['کھانا کھایا؟ بھوک لگ رہی ہو گی۔ آئیے، گھر چلیے!', "Have you eaten? You must be hungry. Come, let's go home!"],
      ['ایک راز کی بات: شہر کا سب سے اچھا نظارہ پہاڑی سے ہے۔', 'A little secret: the best view in town is from the hill.'],
    ],
    bye: [
      ['خدا حافظ! آپ کا سفر اچھا گزرے۔', 'Goodbye! Have a good journey.'],
      ['اپنا خیال رکھیے! باقی سفر اچھا گزرے۔', 'Take care! Enjoy the rest of your trip.'],
      ['اللہ حافظ، دوست!', 'God keep you, friend!'],
      ['پھر آئیے گا!', 'Do come again!'],
      ['آپ سے مل کر خوشی ہوئی۔ سلامت رہیے!', 'It was a pleasure to meet you. Stay well!'],
      ['چلیے، جائیے! ابھی بہت کچھ دیکھنا ہے۔', 'Go on, then! There is still so much to see.'],
    ],
  },
  countries: {
    // Every fact is a bare noun phrase that keeps its form before a postposition; the templates set it as a subject, an object or before «کا»/«پر», and nothing agrees with it.
    PAK: {
      dish: ['بریانی', 'biryani'],
      drink: ['لسی', 'lassi'],
      festival: ['عید الفطر', 'Eid al-Fitr'],
      sport: ['کرکٹ', 'cricket'],
      wonder: ['موئن جو دڑو', 'Mohenjo-daro'],
      pride: ['قوالی', 'qawwali'],
      proverb: ['جیسی کرنی ویسی بھرنی', 'As you sow, so shall you reap'],
    },
  },
};

export default UR;
