import type { Language } from '../phrases.ts';

const VI: Language = {
  locale: 'vi',
  name: 'Vietnamese',
  join: ' ',
  compass: ['bắc', 'đông bắc', 'đông', 'đông nam', 'nam', 'tây nam', 'tây', 'tây bắc'],
  lines: {
    morning: [
      ['Chào buổi sáng!', 'Good morning!'],
      ['Chào bạn! Sáng nay trời mát ghê.', 'Hello! Lovely and cool this morning.'],
      ['Ơ, chào bạn! Ăn sáng chưa?', 'Oh, hello! Had breakfast yet?'],
      ['Chào buổi sáng nhé!', 'Morning to you!'],
    ],
    afternoon: [
      ['Chào buổi chiều!', 'Good afternoon!'],
      ['Chào bạn!', 'Hello!'],
      ['Chào bạn! Ăn trưa chưa?', 'Hello! Had lunch yet?'],
      ['Ơ, chào bạn! Chiều nay đẹp trời nhỉ.', 'Oh, hello! Nice afternoon, isn’t it?'],
    ],
    evening: [
      ['Chào buổi tối!', 'Good evening!'],
      ['Chào bạn! Đi dạo tối à?', 'Hello! Out for an evening walk?'],
      ['Chào bạn! Tối nay gió mát quá.', 'Hello! Such a cool breeze tonight.'],
      ['Ồ, chào buổi tối nhé.', 'Oh, good evening to you.'],
    ],
    night: [
      ['Chào buổi tối! Muộn rồi nhỉ?', 'Good evening! It’s late, isn’t it?'],
      ['Ối, giật cả mình! Chào bạn!', 'Whoa, you made me jump! Hello!'],
      ['Chào bạn! Đi dạo đêm à?', 'Hello! Out for a night walk?'],
      ['Chào bạn! Khuya thế này vẫn chưa ngủ à?', 'Hello! Still not asleep this late?'],
    ],
    again: [
      ['Ơ, lại là bạn! Chào nhé!', 'Oh, it’s you again! Hello!'],
      ['Lại gặp nhau rồi! Vui quá.', 'We meet again! How nice.'],
      ['Chào lần nữa nhé!', 'Hello once again!'],
      ['Bạn đây rồi! Tìm được đường chưa?', 'There you are! Found your way yet?'],
    ],
    welcome: [
      ['Chào mừng bạn đến {town}!', 'Welcome to {town}!'],
      ['Đây là {town}. Bạn đến tham quan à?', 'This is {town}. Are you here sightseeing?'],
      ['Lần đầu đến {town} à?', 'First time in {town}?'],
      ['Hôm nay đẹp trời, đúng dịp để ngắm {town}.', 'Fine weather today, just right for seeing {town}.'],
      ['Chào mừng, chào mừng! {town} rất vui được đón bạn.', 'Welcome, welcome! {town} is happy to have you.'],
      ['Thế, điều gì đưa bạn đến {town}?', 'So, what brings you to {town}?'],
    ],
    capitalHere: [
      ['{town} là thủ đô của nước chúng tôi.', '{town} is the capital of our country.'],
      ['Đây là thủ đô đấy. Chuyện gì cũng diễn ra ở {town}.', 'This is the capital, you know. Everything happens in {town}.'],
      ['Chính phủ đặt ở {town} này. Toàn người mặc vest thôi.', 'The government is here in {town}. Suits everywhere.'],
      ['Là thủ đô nên {town} chẳng bao giờ ngủ.', 'Being the capital, {town} never sleeps.'],
    ],
    capitalThere: [
      ['Thủ đô của chúng tôi là {capital}. Đáng để ghé thăm lắm.', 'Our capital is {capital}. Well worth a visit.'],
      ['Bạn đến {capital} chưa? Đó là thủ đô của chúng tôi.', 'Have you been to {capital}? That’s our capital.'],
      ['Người ở {capital} cứ nghĩ họ điều hành cả nước. Mà đúng thật.', 'People in {capital} think they run the country. And they do.'],
      ['{capital} to hơn, nhưng tôi thích sống ở đây hơn.', '{capital} is bigger, but I’d rather live here.'],
    ],
    big: [
      ['Đây là một thành phố lớn. Ở đây dễ bị lạc lắm!', 'This is a big city. It’s easy to get lost here!'],
      ['Đông người quá! Sống cả đời cũng không biết hết các con hẻm.', 'So many people! You could live here all your life and not know every alley.'],
      ['Kẹt xe thì khỏi nói. Nhưng lúc nào cũng có chuyện để làm.', 'Don’t get me started on the traffic. But there’s always something to do.'],
      ['Thành phố lớn chẳng bao giờ dừng lại. Tôi thích, phần lớn thời gian.', 'A big city never stops. I like it, most of the time.'],
    ],
    middling: [
      ['Không lớn cũng không nhỏ. Vừa vặn.', 'Not big, not small. Just right.'],
      ['Đủ lớn để có mọi thứ, đủ nhỏ để đi bộ.', 'Big enough to have everything, small enough to walk.'],
      ['{town} vừa vặn lắm. Một hai ngày là đi hết.', '{town} is just the right size. A day or two and you’ve seen it all.'],
      ['Ai cũng chê yên tĩnh quá, mà chẳng ai chịu chuyển đi.', 'Everyone grumbles it’s too quiet, yet nobody moves away.'],
    ],
    small: [
      ['Đây là một nơi nhỏ. Ở đây ai cũng biết nhau.', 'It’s a small place. Everybody knows each other here.'],
      ['Chỗ nhỏ lắm. Hắt hơi một cái là cả xóm biết.', 'It’s tiny. Sneeze once and the whole neighbourhood knows.'],
      ['Ở {town} chẳng có gì xảy ra, và chúng tôi thích thế.', 'Nothing happens in {town}, and we like it that way.'],
      ['Bạn là chuyện thú vị nhất cả tuần nay đấy!', 'You’re the most exciting thing all week!'],
    ],
    coast: [
      ['Chúng tôi sống bên sông nước. Cá ở đây ngon lắm.', 'We live by the water. The fish here is delicious.'],
      ['Ra ngắm biển đi. Mỗi ngày một khác.', 'Go and look at the sea. Every day it’s different.'],
      ['Ngửi thấy không? Mùi biển đấy. Không bao giờ chán.', 'Smell that? That’s the sea. You never tire of it.'],
      ['Ghe ra khơi từ sáng sớm, về với mẻ cá tươi nhất.', 'The boats go out at dawn and come back with the freshest catch.'],
    ],
    inland: [
      ['Ở đây xa biển, nhưng cảnh vật rất đẹp.', 'It’s far from the sea here, but the scenery is beautiful.'],
      ['Ở đây không có bãi biển đâu. Nhưng ngắm ruộng đồng kìa.', 'No beach here. But look at those fields.'],
      ['Biển à? Nói thật, tôi chưa thấy bao giờ. Xa lắm.', 'The sea? Honestly, I’ve never seen it. It’s very far.'],
      ['Ở đây đất là tất cả. Đất tốt, người tốt.', 'Here the land is everything. Good soil, good people.'],
    ],
    high: [
      ['Ở đây cao lắm. Đi từ từ thôi, không khí loãng.', 'It’s high up here. Take it slowly, the air is thin.'],
      ['Sống trên núi thế này, cảnh đẹp là thứ quý nhất.', 'Living up in the mountains, the view is the most precious thing.'],
      ['Sống ở đây chân khỏe lắm. Chẳng chỗ nào bằng phẳng.', 'Living here gives you strong legs. Nothing is flat.'],
      ['Giữ hơi nhé! Phải mất một thời gian mới quen núi.', 'Save your breath! It takes a while to get used to the mountains.'],
    ],
    snowy: [
      ['Tuyết chín tháng một năm. Ba tháng còn lại thì than bùn.', 'Snow nine months a year. The other three, we moan about mud.'],
      ['Ở đây trắng xóa cả. Đôi giày đó không ổn đâu.', 'Everything’s white here. Those shoes won’t do.'],
      ['Khi tuyết mới rơi, yên tĩnh đến mức nghe được hơi thở mình.', 'When fresh snow falls, it’s so quiet you can hear yourself breathe.'],
      ['Lạnh thế này phải có bát canh nóng.', 'Cold like this calls for a bowl of hot soup.'],
    ],
    forest: [
      ['Rừng ở đây bạt ngàn. Đừng rời khỏi lối mòn nhé!', 'The forest here is endless. Don’t leave the trail!'],
      ['Đi dạo trong rừng đi. Đầu óc thoáng hẳn.', 'Go for a walk in the forest. It clears the mind.'],
      ['Mùa mưa người ta vào rừng hái nấm.', 'In the rainy season people go into the forest for mushrooms.'],
      ['Cây, cây và cây. Tôi chẳng muốn sống ở đâu khác.', 'Trees, trees and more trees. I wouldn’t live anywhere else.'],
    ],
    desert: [
      ['Ở đây toàn cát, mênh mông tầm mắt.', 'Here it’s all sand, as far as the eye can see.'],
      ['Uống nhiều nước vào. Sa mạc không tha ai đâu.', 'Drink plenty of water. The desert spares no one.'],
      ['Đêm sa mạc lạnh lắm đấy. Chẳng ai tin.', 'Desert nights are really cold. Nobody believes it.'],
      ['Tối nay nhớ ngắm sao. Ở đây có hàng triệu ngôi sao.', 'Remember to look at the stars tonight. There are millions here.'],
    ],
    plains: [
      ['Bằng phẳng hàng cây số. Mưa đến từ xa đã thấy.', 'Flat for miles. You see the rain coming from far away.'],
      ['Trời rộng mênh mông, chẳng gì cản gió.', 'A vast open sky, nothing to stop the wind.'],
      ['Toàn đồng cỏ chăn thả. Cẩn thận đàn bò nhé.', 'It’s all pasture. Watch out for the cattle.'],
      ['Cỏ xanh tít tắp, như một biển xanh.', 'Green grass as far as you can see, like a green sea.'],
    ],
    tropical: [
      ['Ở đây cái gì cũng mọc. Cắm cành xuống là thành cây.', 'Everything grows here. Stick a branch in and it becomes a tree.'],
      ['Mưa ở đây là mưa thật, rồi tạnh cái rụp.', 'When it rains here it really rains, then it stops just like that.'],
      ['Thử trái cây ở chợ đi. Chưa từng ăn thứ gì như thế đâu.', 'Try the fruit at the market. You’ve never had anything like it.'],
      ['Xanh quanh năm. Mùa đông á? Là cái gì vậy?', 'Green all year round. Winter? What’s that?'],
    ],
    landmark: [
      ['Nhất định phải xem {landmark} nhé! Cách đây khoảng {km} km về phía {dir}.', 'You simply must see {landmark}! It’s about {km} km from here, {dir}.'],
      ['Đừng bỏ lỡ {landmark}! Khoảng {km} km về phía {dir}.', 'Don’t miss {landmark}! About {km} km {dir}.'],
      ['Ai cũng đi {landmark}. Cách đây chừng {km} km về phía {dir}.', 'Everyone goes to {landmark}. Around {km} km from here, {dir}.'],
      ['Nếu thích đồ cổ thì đi {landmark}, {km} km về phía {dir}. Người ta đến từ khắp nơi.', 'If you like old things, go to {landmark}, {km} km {dir}. People come from everywhere.'],
    ],
    landmarkNear: [
      ['{landmark} ở ngay gần đây. Bạn không thể bỏ lỡ đâu!', '{landmark} is right nearby. You can’t miss it!'],
      ['Bạn đến {landmark} chưa? Ngay gần đây thôi.', 'Have you been to {landmark}? It’s just close by.'],
      ['Ngày nào cũng thấy {landmark} mà vẫn thấy mê.', 'I see {landmark} every day and I’m still enchanted.'],
      ['{landmark} ở ngay đây. Đi sớm trước khi đông người nhé.', '{landmark} is right here. Go early, before the crowds.'],
    ],
    plane: [
      ['Có một chiếc máy bay nhỏ ở cánh đồng phía {dir}, nếu bạn biết lái!', 'There’s a little plane in a field {dir}, if you can fly!'],
      ['Ai đó để máy bay ở phía {dir}. Muốn bay một chuyến không?', 'Someone left a plane {dir}. Fancy a flight?'],
      ['Biết lái máy bay không? Có một chiếc đang chờ ở phía {dir}.', 'Can you fly? There’s one waiting {dir}.'],
      ['Muốn ngắm mọi thứ từ trên cao thì có máy bay ở phía {dir}.', 'If you want to see it all from above, there’s a plane {dir}.'],
    ],
    balloon: [
      ['Có khinh khí cầu ở cánh đồng phía {dir}! Tưởng tượng cảnh đẹp xem.', 'There’s a hot-air balloon in a field {dir}! Imagine the view.'],
      ['Bạn từng đi khinh khí cầu chưa? Có một cái ở phía {dir}.', 'Ever been up in a balloon? There’s one {dir}.'],
      ['Khinh khí cầu bay lên từ cánh đồng phía {dir}. Kỳ diệu lắm.', 'A balloon goes up from the field {dir}. It’s magical.'],
      ['Tôi luôn muốn thử khinh khí cầu ở phía {dir}. Mà sợ quá!', 'I’ve always wanted to try the balloon {dir}. But I’m too scared!'],
    ],
    boat: [
      ['Có chiếc thuyền bên bờ nước phía {dir}, nếu muốn ra khơi.', 'There’s a boat by the water {dir}, if you want to head out.'],
      ['Thích biển thì có thuyền ở phía {dir}. Nhớ trả lại nhé!', 'If you like the sea, there’s a boat {dir}. Remember to bring it back!'],
      ['Có chiếc thuyền buộc ở phía {dir}. Từ đây đi đâu cũng được.', 'A boat is tied up {dir}. From here you can go anywhere.'],
      ['Lấy thuyền ở phía {dir} ra ngắm bờ biển từ dưới nước đi.', 'Take the boat {dir} and see the coast from the water.'],
    ],
    hot: [
      ['Hôm nay nóng quá! Tìm chỗ râm mát nhé.', 'So hot today! Find somewhere shady.'],
      ['Nóng kinh khủng! Uống nước đi, trông bạn cần lắm.', 'Terribly hot! Drink some water, you look like you need it.'],
      ['Nóng thế này chỉ muốn ngồi trong bóng râm.', 'In heat like this you just want to sit in the shade.'],
      ['Nóng đến chó cũng không thèm ra đường.', 'So hot even the dogs won’t go out.'],
      ['Nóng nhỉ? Thế này là mát so với ở đây đấy!', 'Hot, isn’t it? For us, this is a cool day!'],
    ],
    cold: [
      ['Brr, hôm nay lạnh quá! Mặc ấm vào nhé.', 'Brr, so cold today! Wrap up warm.'],
      ['Lạnh cóng! Găng tay đâu rồi?', 'Freezing! Where are your gloves?'],
      ['Lạnh đến mức mũi tê cứng luôn.', 'So cold my nose has gone numb.'],
      ['Chưa là gì đâu, đợi gió nổi lên xem.', 'This is nothing yet, wait till the wind gets up.'],
      ['Uống gì nóng đi. Đỡ lắm.', 'Have something hot to drink. It really helps.'],
    ],
    mild: [
      ['Hôm nay trời đẹp quá.', 'Such lovely weather today.'],
      ['Không nóng không lạnh. Ngày đẹp quá nhỉ?', 'Not hot, not cold. A perfect day, isn’t it?'],
      ['Ngày thế này phải ra ngoài chơi.', 'On a day like this you have to get outside.'],
      ['Trời đẹp quá! Mong cứ thế này mãi.', 'Beautiful weather! Hope it stays this way.'],
      ['Chính vì những ngày thế này mà chúng tôi ở đây.', 'Days like this are exactly why we live here.'],
    ],
    late: [
      ['Muộn rồi. Ban đêm đường phố yên tĩnh lắm.', 'It’s late. The streets are very quiet at night.'],
      ['Giờ này chỉ có mèo đi dạo. Với cả chúng ta!', 'At this hour only the cats are out walking. And us!'],
      ['Đáng lẽ giờ này tôi phải ngủ rồi. Sao bạn còn thức?', 'I should be asleep by now. Why are you still up?'],
      ['Nhìn sao kìa! Từ đây thấy rõ nhất.', 'Look at the stars! You see them best from here.'],
    ],
    early: [
      ['Dậy sớm thế! Lúc đẹp nhất trong ngày đấy.', 'Up so early! The loveliest time of day.'],
      ['Quán phở vừa mở. Cứ theo mùi mà đi!', 'The pho shop has just opened. Follow the smell!'],
      ['Dậy sớm ghê! Phố còn chưa thức dậy.', 'Early riser! The streets aren’t even awake yet.'],
      ['Tôi thích buổi sáng ở đây, trước khi xe cộ ồn ào.', 'I love the mornings here, before the traffic noise.'],
    ],
    country: [
      ['{country} là một đất nước tuyệt đẹp. Hãy tận hưởng nhé!', '{country} is a gorgeous country. Enjoy it!'],
      ['Bạn thấy {country} thế nào?', 'How do you find {country}?'],
      ['Có dịp thì đi khắp {country} nhé. Mỗi nơi một vẻ.', 'If you get the chance, travel all over {country}. Every place has its own charm.'],
      ['Trên bản đồ {country} không to, nhưng lòng người thì rộng lắm.', 'On the map {country} isn’t big, but its people have big hearts.'],
    ],
    dish: [
      ['Đến đây thì phải ăn {dish} nhé.', 'Since you’re here, you have to eat {dish}.'],
      ['Ăn {dish} chưa? Chưa à? Phải thử ngay!', 'Had {dish} yet? No? Try it right away!'],
      ['Không ai nấu {dish} ngon bằng mẹ tôi.', 'Nobody cooks {dish} as well as my mother.'],
      ['Đói thì gọi {dish}. Không hối hận đâu.', 'If you’re hungry, order {dish}. You won’t regret it.'],
    ],
    drink: [
      ['Trước khi đi, làm một ly {drink} nhé. Ở đây ai cũng uống.', 'Have a glass of {drink} before you go. Everyone drinks it here.'],
      ['Cuối ngày có ly {drink} là nhất.', 'A glass of {drink} at the end of the day is the best.'],
      ['Chưa uống {drink} là chưa đến đây.', 'If you haven’t had {drink}, you haven’t really been here.'],
      ['Gọi {drink} như người địa phương, ai cũng quý bạn.', 'Order {drink} like a local and everyone will love you.'],
    ],
    festival: [
      ['Quay lại vào dịp {festival} nhé. Vui lắm!', 'Come back for {festival}. It’s great fun!'],
      ['Lúc đẹp nhất để đến là dịp {festival}. Cả nước cùng ăn mừng.', 'The best time to come is {festival}. The whole country celebrates.'],
      ['Bạn biết {festival} chưa? Chắc chắn sẽ thích.', 'Do you know {festival}? You’d love it for sure.'],
      ['Năm nào tôi cũng đếm từng ngày đến {festival}.', 'Every year I count the days to {festival}.'],
    ],
    sport: [
      ['Ở đây ai cũng mê {sport}.', 'Everyone here is crazy about {sport}.'],
      ['Bạn thích {sport} không? Ở đây mê lắm.', 'Do you like {sport}? People here love it.'],
      ['Hôm có trận, cả phố chỉ nói chuyện {sport}.', 'On match day the whole street talks of nothing but {sport}.'],
      ['Cả nhà tôi chơi {sport}. Còn bà thì chỉ hò hét cổ vũ.', 'My whole family plays {sport}. Grandma just cheers and shouts.'],
    ],
    wonder: [
      ['Có thời gian thì đi {wonder}. Nhớ mãi không quên.', 'If you have time, go to {wonder}. You’ll never forget it.'],
      ['Bạn thấy {wonder} chưa? Khắp thế giới không đâu giống.', 'Have you seen {wonder}? Nowhere in the world is like it.'],
      ['Đời người phải đến {wonder} một lần.', 'Everyone should go to {wonder} once in their life.'],
      ['Hồi nhỏ tôi được đi {wonder}. Đến giờ vẫn còn mơ thấy.', 'As a child I got to go to {wonder}. I still dream about it.'],
    ],
    pride: [
      ['Chúng tôi rất tự hào về {pride}.', 'We are very proud of {pride}.'],
      ['Đừng về mà chưa biết {pride}. Đó là chúng tôi.', 'Don’t go home without knowing {pride}. That’s who we are.'],
      ['Biết chúng tôi tự hào về gì không? {pride}.', 'Know what we’re proud of? {pride}.'],
      ['Hỏi ai về {pride} cũng được, họ nói cả buổi.', 'Ask anyone about {pride}, they’ll talk for ages.'],
    ],
    proverb: [
      ['Ông bà ta có câu: “{proverb}”', 'Our ancestors had a saying: “{proverb}”'],
      ['Bà tôi hay nói: “{proverb}”', 'My grandmother often said: “{proverb}”'],
      ['Ở đây có câu: “{proverb}”', 'There’s a saying here: “{proverb}”'],
      ['Bạn biết câu này không? “{proverb}”', 'Do you know this one? “{proverb}”'],
    ],
    chat: [
      ['Bạn từ đâu đến? Bạn không phải người ở đây nhỉ.', 'Where are you from? You’re not from here, are you.'],
      ['Cứ thong thả mà ngắm nhìn. Ở đây có nhiều thứ để xem lắm.', 'Take your time and look around. There’s lots to see here.'],
      ['Bạn đi một mình à? Gan thật.', 'Travelling alone? That’s brave.'],
      ['Trông bạn như đi bộ xa lắm rồi.', 'You look like you’ve walked a long way.'],
      ['Lạc đường thì cứ hỏi. Người ở đây dễ mến lắm.', 'If you get lost, just ask. People here are lovely.'],
      ['Đến giờ bạn thích nơi nào nhất?', 'Which place have you liked best so far?'],
      ['Tôi cũng muốn đi đây đi đó. Một ngày nào đó.', 'I’d like to travel around too. Someday.'],
      ['Ngồi uống ly trà đá cho mát không?', 'Want to sit and have an iced tea to cool down?'],
    ],
    childGreet: [
      ['Chào!', 'Hi!'],
      ['Chào! Bạn là ai thế?', 'Hi! Who are you?'],
      ['Chào! Cao quá trời!', 'Hi! You’re so tall!'],
      ['Xin chào, xin chào!', 'Hello, hello!'],
    ],
    childChat: [
      ['Em chạy nhanh lắm! Muốn xem không? Để lát nữa.', 'I run really fast! Want to see? Later.'],
      ['Bạn là khách du lịch à? Bạn em bảo khách du lịch giàu lắm.', 'Are you a tourist? My friend says tourists are really rich.'],
      ['Hôm qua em rụng răng! Nhìn này! Ơ, không thấy à.', 'I lost a tooth yesterday! Look! Oh, you can’t see it.'],
      ['Mẹ bảo không được nói chuyện với người lạ. Nhưng trông bạn hiền lắm.', 'Mum says not to talk to strangers. But you look really kind.'],
      ['Bạn có nuôi chó không? Em muốn có chó ghê.', 'Do you have a dog? I really want a dog.'],
      ['Lớn lên em sẽ lái máy bay đi vòng quanh thế giới!', 'When I grow up I’ll fly a plane all round the world!'],
      ['Bạn biết trò chơi nào không? Em biết nhiều lắm.', 'Do you know any games? I know loads.'],
    ],
    childBye: [
      ['Bai bai!', 'Bye bye!'],
      ['Tạm biệt! Lần sau chơi với em nhé!', 'Bye! Play with me next time!'],
      ['Em phải đi đây, mẹ gọi rồi!', 'I have to go, Mum’s calling!'],
      ['Hẹn gặp lại nha!', 'See you again!'],
    ],
    grumpyGreet: [
      ['Hừm. Cần gì?', 'Hm. What do you need?'],
      ['Gì đấy?', 'What is it?'],
      ['Ôi. Lại khách du lịch.', 'Oh. Another tourist.'],
      ['Hừ. Chào, chắc vậy.', 'Hmph. Hello, I suppose.'],
    ],
    grumpyChat: [
      ['Hồi trước ở đây tốt hơn, trước khi ai cũng kéo đến.', 'It was better here before everyone came flocking in.'],
      ['Cái gì cũng đắt gấp đôi.', 'Everything costs double.'],
      ['Đừng đứng chắn vỉa hè. Người ta còn sống ở đây.', 'Don’t block the pavement. People live here, you know.'],
      ['Bọn trẻ bây giờ, cứ dán mắt vào điện thoại.', 'Young people these days, eyes glued to their phones.'],
      ['Chẳng hiểu sao người ta đến đây. Có gì đâu mà xem.', 'No idea why people come here. There’s nothing to see.'],
    ],
    grumpyBye: [
      ['Thôi. Đi đi.', 'Right. Off you go.'],
      ['Thôi, không giữ bạn nữa.', 'Well, I won’t keep you.'],
      ['Hừm. Tạm biệt.', 'Hm. Goodbye.'],
      ['Đi cẩn thận. Nhớ đóng cổng.', 'Mind how you go. And shut the gate.'],
    ],
    elderChat: [
      ['Hồi tôi còn trẻ, chỗ này toàn ruộng lúa.', 'When I was young, this was all rice paddies.'],
      ['Tôi sống ở đây cả đời. Tám mươi năm! Tin được không?', 'I’ve lived here all my life. Eighty years! Can you believe it?'],
      ['Ngày xưa ai cũng đi bộ. Bạn cũng đi bộ, tốt lắm!', 'In the old days everyone walked. You walk too, very good!'],
      ['Các cháu tôi giờ ở nước ngoài. Chủ nhật nào cũng gọi về.', 'My grandchildren live abroad now. They call home every Sunday.'],
      ['Mọi thứ thay đổi nhanh quá. Nhưng mấy con phố cũ vẫn thế.', 'Everything changes so fast. But the old streets stay the same.'],
    ],
    chattyChat: [
      ['Ôi, tôi mê gặp khách phương xa lắm! Kể hết đi. À khoan, để tôi kể trước.', 'Oh, I love meeting travellers! Tell me everything. Oh wait, let me go first.'],
      ['Ông anh họ tôi đi du lịch một lần. Về mang theo bộ râu và cả vợ!', 'My cousin went travelling once. Came back with a beard and a wife!'],
      ['Bạn bè bảo tôi nói cả ngày không hết. Đúng thật!', 'My friends say I could talk all day. It’s true!'],
      ['Ăn gì chưa? Trông đói lắm. Với tôi ai trông cũng đói.', 'Have you eaten? You look hungry. Everyone looks hungry to me.'],
      ['Bật mí nhé: cảnh đẹp nhất phố là trên đồi sau chùa.', 'Here’s a secret: the best view in town is from the hill behind the pagoda.'],
    ],
    bye: [
      ['Tạm biệt! Chúc bạn thượng lộ bình an.', 'Goodbye! Wishing you a safe journey.'],
      ['Giữ gìn sức khỏe! Đi chơi vui nhé.', 'Stay healthy! Have fun on your travels.'],
      ['Thượng lộ bình an nhé!', 'Safe travels!'],
      ['Tạm biệt! Nhớ quay lại nhé.', 'Goodbye! Be sure to come back.'],
      ['Nói chuyện với bạn vui lắm. Bảo trọng!', 'It was lovely talking to you. Take care!'],
      ['Đi đi! Còn nhiều thứ để xem lắm.', 'Off you go! There’s still lots to see.'],
    ],
  },
  countries: {
    // Each fact is a bare noun phrase, lower-case unless it is a proper name; Vietnamese does not inflect it.
    VNM: {
      dish: ['phở', 'pho'],
      drink: ['cà phê sữa đá', 'iced milk coffee'],
      festival: ['Tết', 'Tet, the Lunar New Year'],
      sport: ['bóng đá', 'football'],
      wonder: ['vịnh Hạ Long', 'Ha Long Bay'],
      pride: ['tà áo dài', 'the ao dai'],
      proverb: ['Uống nước nhớ nguồn', 'When you drink water, remember its source'],
    },
  },
};

export default VI;
