import type { Language } from '../phrases.ts';

const ZH_HANT: Language = {
  locale: 'zh-Hant',
  name: 'Chinese',
  join: '',
  compass: ['北', '東北', '東', '東南', '南', '西南', '西', '西北'],
  lines: {
    morning: [
      ['早安！', 'Good morning!'],
      ['早啊！', 'Morning!'],
      ['早安！今天好早起喔。', "Morning! You're up so early today."],
      ['哈囉，早安！', 'Hello there, good morning!'],
    ],
    afternoon: [
      ['午安！', 'Good afternoon!'],
      ['哈囉！', 'Hello!'],
      ['嗨，午安！吃飽了沒？', 'Hi, good afternoon! Have you eaten?'],
      ['你好！下午出來走走很舒服吧。', "Hello! Nice to be out for a walk in the afternoon, isn't it?"],
    ],
    evening: [
      ['嗨，晚上好啊！', 'Hi, good evening!'],
      ['晚上好！', 'Good evening!'],
      ['嗨！出來散步喔？', 'Hi! Out for a stroll?'],
      ['你好！晚餐吃了嗎？', 'Hello! Had dinner yet?'],
    ],
    night: [
      ['晚上好！已經很晚了，對吧？', "Good evening! It's late, isn't it?"],
      ['哇，嚇我一跳！你好。', 'Whoa, you made me jump! Hello.'],
      ['你好！這麼晚還在外面喔？', 'Hello! Still out this late?'],
      ['嗨！你也是夜貓子嗎？', 'Hi! Are you a night owl too?'],
    ],
    again: [
      ['咦，又是你！哈囉！', 'Oh, you again! Hello!'],
      ['又遇到了！好巧喔。', 'We meet again! What a coincidence.'],
      ['你又回來啦？', 'Back again?'],
      ['是你喔！路有找到嗎？', "Oh, it's you! Did you find your way?"],
      ['我們見過耶！還在到處逛嗎？', "We've met! Still looking around?"],
    ],
    welcome: [
      ['歡迎來到{town}！', 'Welcome to {town}!'],
      ['這裡是{town}。你是來玩的嗎？', 'This is {town}. Are you here to have fun?'],
      ['第一次來{town}嗎？', 'First time in {town}?'],
      ['你挑了個好日子來{town}喔。', "You picked a good day to come to {town}."],
      ['歡迎歡迎！{town}的人最熱情了。', 'Welcome, welcome! The people of {town} are the friendliest.'],
      ['來{town}是出差還是旅行？', 'Are you in {town} on business or travelling?'],
    ],
    capitalHere: [
      ['{town}是政府所在地，什麼大事都在這裡。', '{town} is the seat of government. Everything important happens here.'],
      ['在{town}，走在路上常常遇到穿西裝的大人物。', 'In {town} you often pass important people in suits on the street.'],
      ['{town}從早忙到晚，好像從來不睡覺。', '{town} is busy from morning to night. It never seems to sleep.'],
      ['這裡就是{town}，大家都想來這邊打拚。', 'This is {town}. Everyone wants to come here to make it.'],
    ],
    capitalThere: [
      ['有空可以去{capital}看看，很值得。', "If you have time, go and see {capital}. It's worth it."],
      ['你去過{capital}了嗎？那邊很熱鬧喔。', 'Have you been to {capital} yet? It is very lively there.'],
      ['{capital}是比較大啦，但我還是喜歡住這裡。', "{capital} is bigger, sure, but I still prefer living here."],
      ['{capital}的人走路都好快，我跟不上。', 'People in {capital} all walk so fast. I can never keep up.'],
    ],
    big: [
      ['這是一座大城市，在這裡很容易迷路！', "This is a big city. It's easy to get lost here!"],
      ['人好多喔！住一輩子也走不完每一條街。', 'So many people! You could live here your whole life and not walk every street.'],
      ['這裡塞車很誇張，不過好玩的東西也超多。', 'The traffic here is crazy, but there are loads of fun things too.'],
      ['大城市就是這樣，二十四小時都有事情在發生。', "That's a big city for you: something is happening twenty-four hours a day."],
    ],
    middling: [
      ['不大也不小，剛剛好。', 'Not big, not small. Just right.'],
      ['該有的都有，走路就逛得完。', 'It has everything, and you can walk all of it.'],
      ['{town}大小剛好，一兩天就可以逛完。', "{town} is just the right size. You can see it all in a day or two."],
      ['大家都嫌這裡太安靜，可是沒有人捨得搬走。', 'Everyone says it is too quiet here, but nobody can bear to move away.'],
    ],
    small: [
      ['這是個小地方，大家都互相認識。', "It's a small place. Everyone knows everyone."],
      ['小地方啦，隔壁打個噴嚏整條街都知道。', "It's a small place. Sneeze next door and the whole street knows."],
      ['{town}沒什麼大事，我們就喜歡這樣。', 'Nothing much happens in {town}, and we like it like that.'],
      ['你是我們這禮拜最大的新聞耶！', "You're the biggest news we've had all week!"],
    ],
    coast: [
      ['我們住在水邊，這裡的魚很好吃。', 'We live by the water. The fish here is delicious.'],
      ['去海邊看看吧，每天的海都長得不一樣。', 'Go and look at the sea. It looks different every day.'],
      ['聞到了嗎？海的味道，怎麼聞都不會膩。', 'Can you smell it? The sea. You never get tired of it.'],
      ['漁船天還沒亮就出海，回來的海鮮超新鮮。', 'The fishing boats go out before dawn, and the seafood they bring back is super fresh.'],
    ],
    inland: [
      ['這裡離海很遠，但風景很美。', "We're far from the sea, but the scenery is beautiful."],
      ['這邊沒有海灘啦，不過你看那片田。', "No beach round here, but look at those fields."],
      ['我們靠土地吃飯，土好，人也好。', 'We live off the land. Good soil, good people.'],
      ['想看海要開好久的車，不過山也很漂亮啊。', "It's a long drive to see the sea, but the hills are lovely too."],
    ],
    high: [
      ['這裡海拔比較高，走慢一點喔。', "We're quite high up here. Walk a bit slower."],
      ['住在山上，最值錢的就是這片風景。', 'Living up in the hills, the view is the most precious thing we have.'],
      ['在這裡住久了，腳力都練出來了，沒有一條路是平的。', 'Live here long enough and your legs get strong. No road is flat.'],
      ['山上早晚溫差大，記得多帶件外套。', 'Up in the mountains mornings and nights are chilly. Bring an extra jacket.'],
    ],
    snowy: [
      ['一年有大半年在下雪，剩下的時間在抱怨泥巴。', 'It snows most of the year. The rest of the time we complain about the mud.'],
      ['這裡到處白茫茫的，你那雙鞋不夠厚喔。', "Everything is white out here. Those shoes aren't thick enough."],
      ['下完雪之後好安靜，安靜到聽得到自己在想什麼。', "After it snows it's so quiet you can hear yourself think."],
      ['我們不怕冷啦，冷才好，觀光客比較少。', "We don't mind the cold. It's good, it keeps the tourists away."],
    ],
    forest: [
      ['這一帶的森林好大，不要離開步道喔！', 'The forest round here is huge. Stay on the trail!'],
      ['去森林走一走，吸收一下芬多精吧。', 'Go for a walk in the woods and breathe in the forest air.'],
      ['每年秋天我們都會上山採香菇、摘野果。', 'Every autumn we go up to pick mushrooms and wild berries.'],
      ['放眼望去全是樹，我可不想住別的地方。', "Trees as far as you can see. I wouldn't live anywhere else."],
    ],
    desert: [
      ['這裡一眼望過去全是沙。', 'Out here it is sand as far as the eye can see.'],
      ['水要多喝！沙漠可不是開玩笑的。', "Drink plenty of water! The desert is no joke."],
      ['沙漠的晚上超冷，講了都沒人相信。', 'Desert nights are really cold. Nobody believes it when you tell them.'],
      ['晚上抬頭看看，這裡的星星多到數不完。', 'Look up tonight. There are more stars here than you can count.'],
    ],
    plains: [
      ['這裡一整片平平的，天氣要變老遠就看得到。', "It's flat all over. You can see the weather changing from miles away."],
      ['天好大，風一吹什麼都擋不住。', 'The sky is huge, and nothing stops the wind.'],
      ['都是很好的草地，小心牛群喔。', 'This is all good grassland. Watch out for the cattle.'],
      ['草地一望無際，好像綠色的海。', 'The grass stretches forever, like a green sea.'],
    ],
    tropical: [
      ['這裡什麼都長得起來，插根樹枝就變一棵樹。', 'Anything grows here. Stick a branch in the ground and it turns into a tree.'],
      ['這邊的雨說來就來，說停就停。', 'The rain here comes out of nowhere and stops just as suddenly.'],
      ['去市場買點水果吧，甜到你會嚇一跳。', "Buy some fruit at the market. It's so sweet it'll surprise you."],
      ['一年四季都綠油油的，冬天？沒聽過。', "It's lush and green all year round. Winter? Never heard of it."],
    ],
    landmark: [
      ['一定要去看看{landmark}！從這裡往{dir}大約{km}公里。', "You must go and see {landmark}! It's about {km} km {dir} of here."],
      ['{landmark}去過了嗎？往{dir}走差不多{km}公里，很值得。', "Been to {landmark}? About {km} km {dir}, well worth it."],
      ['來這裡的人都會去{landmark}，在{dir}邊，大概{km}公里。', "Everyone who comes here visits {landmark}. It's {dir}, about {km} km."],
      ['喜歡古蹟的話，{landmark}在{dir}邊{km}公里左右，很多人專程去看。', 'If you like historic places, {landmark} is about {km} km {dir}. Lots of people go just for it.'],
    ],
    landmarkNear: [
      ['{landmark}就在附近，你一定找得到！', "{landmark} is close by. You're sure to find it!"],
      ['你去過{landmark}了嗎？轉個彎就到了。', "Have you been to {landmark}? It's just round the corner."],
      ['我每天都看到{landmark}，還是覺得很厲害。', 'I see {landmark} every day and I still think it is amazing.'],
      ['{landmark}就在這邊，早點去，人比較少。', '{landmark} is right here. Go early, there are fewer people.'],
    ],
    plane: [
      ['{dir}邊的田裡停了一架小飛機，你會開嗎？', "There's a little plane parked in a field {dir}. Can you fly?"],
      ['有人把飛機停在{dir}邊的空地上，要不要去飛一圈？', 'Somebody parked a plane on a field {dir}. Fancy a flight?'],
      ['你會開飛機嗎？{dir}邊就有一架。', "Can you fly? There's one {dir}."],
      ['想從天上看這裡嗎？{dir}邊有飛機喔。', "Want to see this place from the sky? There's a plane {dir}."],
    ],
    balloon: [
      ['{dir}邊的田裡有一顆熱氣球！想想看那個風景。', "There's a hot-air balloon in a field {dir}! Imagine the view."],
      ['你坐過熱氣球嗎？{dir}邊就有一顆。', "Have you ever been in a hot-air balloon? There's one {dir}."],
      ['{dir}邊那顆熱氣球飛起來超漂亮的。', 'That balloon {dir} is so beautiful when it goes up.'],
      ['我一直很想坐{dir}邊那顆熱氣球，可是我怕高！', "I've always wanted to ride the balloon {dir}, but I'm scared of heights!"],
    ],
    boat: [
      ['{dir}邊的水邊有一艘船，想出去晃晃可以用。', "There's a boat by the water {dir}, if you want to go out."],
      ['喜歡海的話，{dir}邊有一艘船。記得還回來喔！', "If you like the sea, there's a boat {dir}. Remember to bring it back!"],
      ['{dir}邊綁著一艘船，從這裡哪裡都去得了。', "There's a boat tied up {dir}. From here you could go anywhere."],
      ['坐{dir}邊那艘船，從海上看看海岸吧。', 'Take the boat {dir} and see the coast from the sea.'],
    ],
    hot: [
      ['今天真熱！找個陰涼的地方吧。', "It's really hot today! Find some shade."],
      ['熱死了！多喝水喔，你看起來快融化了。', "It's boiling! Drink lots of water, you look like you're melting."],
      ['這麼熱，只想躲在冷氣房裡。', 'In this heat all I want is to hide somewhere with air conditioning.'],
      ['這種天氣，連狗都懶得出門。', "In this weather even the dogs can't be bothered to go out."],
      ['很熱吧？對我們來說這樣還算涼的！', "Hot, isn't it? For us this is still cool!"],
    ],
    cold: [
      ['哎呀，今天好冷！多穿點衣服。', "Oh, it's so cold today! Wear more layers."],
      ['冷死了！你的手套呢？', "It's freezing! Where are your gloves?"],
      ['冷到我鼻子都沒感覺了。', "It's so cold I can't feel my nose."],
      ['這還不算冷，等風吹起來你就知道。', "This isn't cold yet. Wait till the wind starts."],
      ['去喝點熱的吧，身體會暖起來。', 'Go and drink something hot. It will warm you up.'],
    ],
    mild: [
      ['今天天氣真好。', 'Lovely weather today.'],
      ['不冷不熱，超舒服的，對吧？', "Not cold, not hot. So comfortable, right?"],
      ['這種天氣就是要出來走走。', 'Weather like this is for being outside.'],
      ['天氣這麼好，希望可以多維持幾天。', "Such lovely weather. I hope it lasts a few more days."],
      ['就是為了這種日子，我們才住在這裡。', 'Days like this are why we live here.'],
    ],
    late: [
      ['已經很晚了，晚上街上很安靜。', "It's late. The streets are quiet at night."],
      ['這個時間，外面只剩貓了。還有我們！', 'At this hour only the cats are out. And us!'],
      ['我早就該睡了，你怎麼還沒睡？', "I should have been asleep ages ago. Why are you still up?"],
      ['肚子餓的話，便利商店還開著喔。', "If you're hungry, the convenience store is still open."],
    ],
    early: [
      ['好早起喔！這是一天最舒服的時候。', "You're up early! This is the nicest time of the day."],
      ['早餐店剛開，跟著香味走就對了！', 'The breakfast shop has just opened. Just follow the smell!'],
      ['這麼早？整個城市都還沒醒呢。', 'This early? The whole town is still asleep.'],
      ['我最喜歡這裡的早上，還沒開始吵。', 'I love the mornings here, before the noise starts.'],
    ],
    country: [
      ['{country}是個很棒的地方，好好玩喔！', '{country} is a wonderful place. Have fun!'],
      ['{country}，到目前為止你覺得怎麼樣？', 'So, {country}: what do you think of it so far?'],
      ['有機會的話在{country}多走走，每個角落都不一樣。', 'If you get the chance, travel more around {country}. Every corner is different.'],
      ['說到{country}，我可以講三天三夜。', 'I could talk about {country} for three days and nights.'],
    ],
    dish: [
      ['來了一定要吃吃看{dish}。', 'While you are here you have to try {dish}.'],
      ['你吃過{dish}了嗎？還沒？那不行喔！', "Have you had {dish}? Not yet? That won't do!"],
      ['誰做的{dish}都比不上我媽做的。', 'Nobody makes {dish} like my mum.'],
      ['肚子餓就去吃{dish}，保證不會後悔。', "If you're hungry, go and have {dish}. You won't regret it."],
    ],
    drink: [
      ['走之前來點{drink}吧，我們這裡都喝這個。', 'Have some {drink} before you go. It is what we all drink here.'],
      ['忙了一整天，來一杯{drink}最療癒。', 'After a long day, {drink} is the best therapy.'],
      ['沒喝過{drink}，就等於沒來過。', "If you haven't had {drink}, you haven't really been here."],
      ['像在地人一樣點{drink}，老闆一定很開心。', 'Order {drink} like a local and the owner will be delighted.'],
    ],
    festival: [
      ['你應該{festival}的時候再來，超熱鬧的！', 'You should come back for {festival}. It is so lively!'],
      ['一年裡最棒的時候就是{festival}。', 'The best time of the year here is {festival}.'],
      ['你有聽過{festival}嗎？你一定會喜歡。', "Have you heard of {festival}? You'd love it."],
      ['我每年都在倒數{festival}。', 'Every year I count down to {festival}.'],
    ],
    sport: [
      ['我們這裡最瘋的就是{sport}。', 'What people here go craziest for is {sport}.'],
      ['你喜歡{sport}嗎？這裡的人超迷的。', 'Do you like {sport}? People here are obsessed with it.'],
      ['一到比賽的日子，大家聊的都是{sport}。', 'On match days everyone talks about nothing but {sport}.'],
      ['我阿公每天都在看{sport}，看到會對電視大叫。', 'My grandpa watches {sport} every day and shouts at the TV.'],
    ],
    wonder: [
      ['有時間的話去看看{wonder}吧，一輩子忘不了。', 'If you have time, go and see {wonder}. You will never forget it.'],
      ['你看過{wonder}嗎？全世界只有這裡有。', 'Have you seen {wonder}? There is nothing like it anywhere else.'],
      ['人這一輩子，一定要去一次{wonder}。', 'Everyone has to see {wonder} once in their life.'],
      ['我小時候去過{wonder}，到現在還會夢到。', 'I went to {wonder} as a child. I still dream about it.'],
    ],
    pride: [
      ['我們最自豪的，就是{pride}。', 'What we are proudest of is {pride}.'],
      ['走之前一定要認識一下{pride}，那就是我們。', "Before you leave, get to know {pride}. That's who we are."],
      ['問我們最驕傲的是什麼？{pride}。', 'Ask what we are proudest of? {pride}.'],
      ['隨便問一個人{pride}，都可以跟你聊半天。', 'Ask anyone here about {pride} and they will talk your ear off.'],
    ],
    proverb: [
      ['我們這裡有句話：「{proverb}」', 'We have a saying here: “{proverb}”'],
      ['我阿嬤常說：「{proverb}」', 'My grandma always says: “{proverb}”'],
      ['老一輩的人都說：「{proverb}」', 'The older generation always say: “{proverb}”'],
      ['你聽過這句話嗎？「{proverb}」', 'Have you heard this saying? “{proverb}”'],
    ],
    chat: [
      ['你是哪裡人？你不是本地人吧。', "Where are you from? You're not from around here, are you?"],
      ['慢慢逛，這裡有很多值得看的東西。', 'Take your time. There is a lot worth seeing here.'],
      ['一個人出來旅行喔？好勇敢。', 'Travelling on your own? That is brave.'],
      ['你看起來走了很遠的路耶。', 'You look like you have walked a long way.'],
      ['迷路的話就問人，這裡的人都很熱心。', 'If you get lost, just ask. People here are really helpful.'],
      ['到目前為止，你最喜歡哪裡？', 'Where have you liked best so far?'],
      ['我一直很想出國看看，以後再說吧。', 'I have always wanted to travel abroad. Some day, maybe.'],
      ['要吃東西的話，巷子裡那家小店很道地。', 'If you want to eat, the little shop down the alley is the real deal.'],
    ],
    childGreet: [
      ['嗨！', 'Hi!'],
      ['哈囉！你是誰？', 'Hello! Who are you?'],
      ['哇，你好高喔！', "Wow, you're so tall!"],
      ['哈囉哈囉！', 'Hello hello!'],
    ],
    childChat: [
      ['我跑超快的！要不要看？等一下好了。', "I run super fast! Want to see? Maybe in a bit."],
      ['你是觀光客嗎？我同學說觀光客都很有錢。', 'Are you a tourist? My classmate says tourists are all rich.'],
      ['我昨天掉了一顆牙！你看！啊，看不到。', "I lost a tooth yesterday! Look! Oh, you can't see it."],
      ['媽媽說不可以跟陌生人講話，可是你看起來人很好。', 'Mum says not to talk to strangers, but you look nice.'],
      ['你有養狗狗嗎？我好想養一隻。', "Do you have a doggy? I really want one."],
      ['我長大要開飛機，繞地球一圈！', "When I grow up I'm going to fly a plane round the world!"],
      ['你會玩剪刀石頭布嗎？我每次都贏喔！', 'Can you play rock-paper-scissors? I win every time!'],
    ],
    childBye: [
      ['掰掰！', 'Bye bye!'],
      ['掰掰！下次再來找我玩！', 'Bye! Come and play with me next time!'],
      ['我要走了，媽媽在叫我！', 'I have to go, Mum is calling me!'],
      ['拜拜！明天見！', 'Bye! See you tomorrow!'],
    ],
    grumpyGreet: [
      ['嗯？幹嘛？', 'Hm? What?'],
      ['有什麼事嗎？', 'Is there something you want?'],
      ['唉，又一個觀光客。', 'Sigh. Another tourist.'],
      ['嗯……你好啦。', 'Hm... hello, I guess.'],
    ],
    grumpyChat: [
      ['以前這裡多安靜，現在到處都是觀光客。', 'It used to be so quiet here. Now there are tourists everywhere.'],
      ['現在什麼都漲價，一碗麵比以前貴一倍。', 'Everything has gone up. A bowl of noodles costs twice what it used to.'],
      ['不要擋在路中間，這裡是有人住的。', "Don't stand in the middle of the road. People live here."],
      ['現在的年輕人喔，走路都在滑手機。', 'Young people these days, scrolling their phones even when they walk.'],
      ['真不懂有什麼好看的，不就幾條街嗎。', "I don't get what there is to see. It's just a few streets."],
    ],
    grumpyBye: [
      ['好啦，去吧去吧。', 'All right, off you go.'],
      ['好了，不耽誤你了。', "Right, I won't keep you."],
      ['嗯，再見。', 'Hm. Goodbye.'],
      ['走路看路，不要踩到我的花。', 'Watch where you walk. Mind my flowers.'],
    ],
    elderChat: [
      ['我小時候，這裡全部都是稻田。', 'When I was little, this was all rice paddies.'],
      ['我在這裡住了一輩子，八十年了！你相信嗎？', "I've lived here my whole life. Eighty years! Can you believe it?"],
      ['我們那個年代去哪裡都用走的。你也用走的？很好！', 'In my day we walked everywhere. You walk too? Good!'],
      ['孫子都在外地工作，過年才回來。', 'My grandchildren work far away. They only come home for New Year.'],
      ['變化好快喔，只剩這幾條老街還跟以前一樣。', 'Things change so fast. Only these old streets are still the same.'],
    ],
    chattyChat: [
      ['哎呀，我最喜歡跟旅客聊天了！你先說，不對，我先說！', 'Oh, I love chatting with travellers! You first. No, wait, me first!'],
      ['我表哥出國玩一趟，回來多了一個老婆！', 'My cousin went abroad on holiday once and came back with a wife!'],
      ['朋友都說我很會講，一點都沒錯！', "My friends say I can really talk, and they're not wrong!"],
      ['吃飽了沒？你看起來好餓。每個人在我眼裡都好餓。', 'Have you eaten? You look hungry. Everyone looks hungry to me.'],
      ['偷偷告訴你：看全城最美的地方是後面那座小山。', 'Just between us: the prettiest view of town is from the little hill behind.'],
    ],
    bye: [
      ['再見！一路順風。', 'Goodbye! Have a smooth journey.'],
      ['保重喔！接下來玩得開心。', 'Take care! Have fun on the rest of your trip.'],
      ['一路平安啊，朋友！', 'Safe travels, friend!'],
      ['掰掰！有空再來玩喔。', 'Bye! Come back and visit sometime.'],
      ['跟你聊天很開心，照顧好自己！', 'It was lovely talking to you. Look after yourself!'],
      ['快去吧！好玩的地方還很多呢。', "Off you go! There's plenty more to see."],
    ],
  },
  countries: {
    // Every fact is a bare noun phrase with no measure word, as it stands after 吃吃看, 喝, 去看, 是.
    TWN: {
      dish: ['牛肉麵', 'beef noodle soup'],
      drink: ['珍珠奶茶', 'bubble tea'],
      festival: ['元宵節的平溪天燈', 'the sky lanterns of Pingxi at the Lantern Festival'],
      sport: ['棒球', 'baseball'],
      wonder: ['太魯閣峽谷', 'Taroko Gorge'],
      pride: ['夜市文化', 'the night markets'],
      proverb: ['吃果子拜樹頭', 'When you eat the fruit, give thanks to the tree'],
    },
    HKG: {
      dish: ['點心', 'dim sum'],
      drink: ['港式奶茶', 'Hong Kong-style milk tea'],
      festival: ['長洲太平清醮', 'the Cheung Chau Bun Festival'],
      sport: ['賽馬', 'horse racing'],
      wonder: ['維多利亞港的夜景', 'the night view of Victoria Harbour'],
      pride: ['茶餐廳文化', 'the cha chaan teng, our local cafés'],
      proverb: ['食得是福', 'Being able to eat is a blessing'],
    },
    MAC: {
      dish: ['葡式蛋撻', 'Portuguese egg tarts'],
      festival: ['醉龍節', 'the Drunken Dragon Festival'],
      wonder: ['大三巴牌坊', 'the Ruins of St. Paul’s'],
      pride: ['土生葡人美食', 'Macanese cooking'],
      proverb: ['飲水思源', 'When you drink water, remember its source'],
    },
  },
};

export default ZH_HANT;
