import type { Language } from '../phrases.ts';

const ZH: Language = {
  locale: 'zh-Hans',
  name: 'Chinese',
  join: '',
  compass: ['北', '东北', '东', '东南', '南', '西南', '西', '西北'],
  lines: {
    morning: [
      ['早上好！', 'Good morning!'],
      ['早啊！', 'Morning!'],
      ['早！今天起得挺早嘛。', "Morning! You're up nice and early."],
      ['哎，你好！早上好呀。', 'Oh, hello! Good morning to you.'],
    ],
    afternoon: [
      ['下午好！', 'Good afternoon!'],
      ['你好你好！', 'Hello, hello!'],
      ['哟，你好！吃过午饭了吗？', 'Oh, hi! Have you had lunch yet?'],
      ['你好！下午出来逛逛挺舒服的。', "Hello! An afternoon stroll is nice, isn't it?"],
    ],
    evening: [
      ['晚上好！', 'Good evening!'],
      ['你好！吃饭了没？', 'Hello! Have you eaten yet?'],
      ['晚上好！出来散步啊？', 'Good evening! Out for a walk?'],
      ['哎，晚上好呀。', 'Oh, good evening to you.'],
    ],
    night: [
      ['晚上好！已经很晚了，是吧？', "Good evening! It's late, isn't it?"],
      ['哎哟，吓我一跳！你好。', 'Oh! You gave me a fright. Hello.'],
      ['你好！这么晚还在外面逛？', 'Hello! Still out walking this late?'],
      ['你好！这个点儿还没睡啊？', "Hello! Not asleep at this hour?"],
    ],
    again: [
      ['哎，又是你！你好！', 'Oh, you again! Hello!'],
      ['又见面了！真巧。', 'We meet again! What a coincidence.'],
      ['你又回来啦？', 'Back again?'],
      ['是你啊！路找到了吗？', "Ah, it's you! Did you find your way?"],
      ['咱们见过！还在到处转吗？', "We've met! Still wandering around?"],
    ],
    welcome: [
      ['欢迎来到{town}！', 'Welcome to {town}!'],
      ['这里是{town}。你是来旅游的吗？', 'This is {town}. Are you here on holiday?'],
      ['第一次来{town}吗？', 'First time in {town}?'],
      ['你今天来{town}，赶上好日子了。', "You've come to {town} on a good day."],
      ['欢迎欢迎！{town}的人最好客了。', 'Welcome, welcome! The people of {town} love having guests.'],
      ['来{town}是办事还是玩儿？', 'Are you in {town} for work or for fun?'],
    ],
    capitalHere: [
      ['{town}是我们的首都。', '{town} is our capital.'],
      ['这儿可是首都，什么大事都在{town}。', "This is the capital, you know. All the big things happen in {town}."],
      ['首都嘛，{town}一天到晚都热闹。', "Being the capital, {town} is busy from morning to night."],
      ['在{town}，随便走走都能碰到穿西装的大人物。', 'In {town}, you bump into important people in suits just walking around.'],
    ],
    capitalThere: [
      ['我们的首都是{capital}，值得去看看。', "Our capital is {capital}. It's worth a visit."],
      ['去过{capital}没有？那是我们的首都。', "Have you been to {capital}? That's our capital."],
      ['{capital}是大，可我还是喜欢住这儿。', "{capital} is bigger, but I'd still rather live here."],
      ['{capital}的人啊，总觉得自己见过大世面。', 'People in {capital} always think they have seen the world.'],
    ],
    big: [
      ['这是一座大城市，在这里很容易迷路！', "This is a big city. It's easy to get lost here!"],
      ['人山人海的！住一辈子也走不完所有的街。', 'Crowds everywhere! You could live here all your life and not walk every street.'],
      ['这里堵车是真堵，不过好玩的也是真多。', 'The traffic here is really bad, but there really is a lot to do.'],
      ['大城市就是这样，节奏快，从来不停。', "That's a big city for you: fast, and it never stops."],
    ],
    middling: [
      ['不大也不小，刚刚好。', 'Not big, not small. Just right.'],
      ['该有的都有，走路就能逛完。', 'It has everything you need, and you can walk all of it.'],
      ['{town}不大不小，一两天就能逛个遍。', "{town} is a nice size. You'll see all of it in a day or two."],
      ['大家都说这儿太安静，可谁也舍不得走。', 'Everyone says it is too quiet here, but nobody wants to leave.'],
    ],
    small: [
      ['这是个小地方，大家都互相认识。', "It's a small place. Everyone knows everyone."],
      ['小地方，谁家有点事，整条街都知道。', "Small place. If anything happens in one house, the whole street knows."],
      ['{town}没什么大事，我们就喜欢这样。', 'Nothing much happens in {town}, and we like it that way.'],
      ['你呀，是这礼拜这儿最新鲜的事儿了！', "You're the most exciting thing to happen here all week!"],
    ],
    coast: [
      ['我们住在水边，这里的鱼很好吃。', 'We live by the water. The fish here is delicious.'],
      ['去海边看看吧，每天的海都不一样。', 'Go and look at the sea. It is different every day.'],
      ['闻到没有？海的味道，一辈子都闻不腻。', "Smell that? That's the sea. You never get tired of it."],
      ['渔船天不亮就出海，回来的海鲜特别新鲜。', 'The fishing boats go out before dawn and bring back the freshest seafood.'],
    ],
    inland: [
      ['这里离海很远，但风景很美。', "We're far from the sea, but the scenery is beautiful."],
      ['海滩是没有的，不过你看那片田。', "There's no beach, I'm afraid. But look at those fields."],
      ['大海？说实话我还没见过呢，太远了。', "The sea? To be honest I've never seen it. It's too far."],
      ['我们这儿靠地吃饭，土好，人也好。', 'Here we live off the land. Good soil, good people.'],
    ],
    high: [
      ['这儿地势高，走慢点，空气稀薄。', "We're high up here. Go slowly, the air is thin."],
      ['住在山上，最值钱的就是这风景。', 'Living up in the hills, the view is the most precious thing we have.'],
      ['在这儿住久了，腿脚都练出来了，没一处是平的。', 'Live here long enough and you get strong legs. Nothing is flat.'],
      ['慢慢喘口气，山里得适应一下。', 'Catch your breath. The mountains take some getting used to.'],
    ],
    snowy: [
      ['一年有大半年都是雪，剩下的时间在抱怨泥巴。', 'Snow for most of the year. The rest of the time we complain about the mud.'],
      ['这里到处白茫茫的，你得换双厚点的鞋。', "Everything is white out here. You'll want thicker shoes than those."],
      ['冷是冷，可下完雪静得能听见自己想事儿。', "It's cold, but after fresh snow it's so quiet you can hear yourself think."],
      ['我们不怕冷，冬天还能在冰上钓鱼呢。', "We don't mind the cold. In winter we even go ice fishing."],
    ],
    forest: [
      ['这一带林子大得很，别离开小路！', 'The forest round here is huge. Stay on the path!'],
      ['去林子里走走吧，脑子一下就清醒了。', 'Go for a walk in the woods. It clears your head right away.'],
      ['每年秋天我们都上山采蘑菇、摘野果。', 'Every autumn we go up to pick mushrooms and wild berries.'],
      ['满眼都是树，我可不想住别的地方。', "Trees as far as you can see. I wouldn't live anywhere else."],
    ],
    desert: [
      ['这里一眼望去全是沙子。', 'Out here it is sand as far as the eye can see.'],
      ['多喝水！沙漠可不跟你开玩笑。', "Drink plenty of water! The desert doesn't joke around."],
      ['沙漠的晚上冷得很，说了都没人信。', 'Desert nights are really cold. Nobody believes it when you tell them.'],
      ['晚上抬头看看，这儿的星星多得数不清。', 'Look up tonight. There are more stars here than you can count.'],
    ],
    plains: [
      ['一马平川，天要变了老远就看得见。', "It's flat as far as you can see. You spot the weather coming from miles off."],
      ['这儿天大地大，风一刮就没个挡的。', 'Big sky, wide land. Nothing stops the wind here.'],
      ['都是好草场，小心牛羊啊。', 'Good grazing land, all of it. Watch out for the herds.'],
      ['草一眼望不到头，跟绿色的海一样。', 'The grass goes on forever, like a green sea.'],
    ],
    tropical: [
      ['这儿什么都长，插根树枝都能长成树。', 'Everything grows here. Stick a branch in the ground and it becomes a tree.'],
      ['这里的雨说来就来，说停就停。', 'Here the rain comes out of nowhere and stops just as fast.'],
      ['去市场尝尝水果吧，保证你没吃过这么甜的。', "Try the fruit at the market. I promise you've never had anything so sweet."],
      ['一年四季都是绿的，冬天？没听说过。', "It's green all year round. Winter? Never heard of it."],
    ],
    landmark: [
      ['一定要去看看{landmark}！从这里往{dir}大约{km}公里。', "You must go and see {landmark}! It's about {km} km {dir} of here."],
      ['{landmark}去过没有？往{dir}走{km}公里左右，绝对值得。', "Been to {landmark}? About {km} km {dir}, and absolutely worth it."],
      ['来这儿的人都要去{landmark}，在{dir}边，大概{km}公里。', "Everyone who comes here goes to {landmark}. It's {dir}, about {km} km."],
      ['有空的话，{landmark}在{dir}边{km}公里，好多人专门来看。', 'If you have time, {landmark} is {km} km {dir}. People come just to see it.'],
    ],
    landmarkNear: [
      ['{landmark}就在附近，你一定能找到！', "{landmark} is close by. You can't miss it!"],
      ['去过{landmark}了吗？拐个弯就到。', "Have you been to {landmark} yet? It's just round the corner."],
      ['我天天看着{landmark}，还是觉得了不起。', 'I see {landmark} every day and I still think it is amazing.'],
      ['{landmark}就在这儿，早点去，人少。', "{landmark} is right here. Go early, before the crowds."],
    ],
    plane: [
      ['{dir}边的田里停着一架小飞机，你会开吗？', "There's a little plane parked in a field {dir}. Can you fly?"],
      ['有人把飞机停在{dir}边的地里了，想不想飞一圈？', 'Somebody left a plane in a field {dir}. Fancy a flight?'],
      ['会开飞机吗？{dir}边就有一架。', "Can you fly? There's one {dir} of here."],
      ['想从天上看看这儿？{dir}边有架飞机。', "Want to see this place from the sky? There's a plane {dir}."],
    ],
    balloon: [
      ['{dir}边的田里有个热气球！想想那风景。', "There's a hot-air balloon in a field {dir}! Imagine the view."],
      ['坐过热气球没有？{dir}边就有一个。', "Ever flown in a hot-air balloon? There's one {dir}."],
      ['{dir}边那块地上的热气球，飞起来可美了。', 'The balloon in the field {dir} is beautiful when it goes up.'],
      ['我一直想坐{dir}边那个热气球，就是胆子太小！', "I've always wanted to ride the balloon {dir}. I'm just too scared!"],
    ],
    boat: [
      ['{dir}边水边有条船，想出去转转的话可以用。', "There's a boat by the water {dir}, if you want to go out."],
      ['喜欢海的话，{dir}边有条船。记得还回来啊！', "If you like the sea, there's a boat {dir}. Remember to bring it back!"],
      ['{dir}边拴着一条船，从这儿哪儿都能去。', "A boat is tied up {dir}. From here you could go anywhere."],
      ['坐{dir}边那条船，从水上看看海岸吧。', 'Take the boat {dir} and see the coast from the water.'],
    ],
    hot: [
      ['今天真热！找个阴凉的地方吧。', "It's really hot today! Find some shade."],
      ['热死了！多喝点水，你看着都快晒化了。', "Boiling! Drink some water, you look like you're melting."],
      ['这么热的天，只想在树底下坐着。', 'On a day this hot, all you want is to sit under a tree.'],
      ['这天气，连狗都躲在屋里不出来。', 'In this weather even the dogs stay indoors.'],
      ['热吧？对我们来说这还算凉快的！', "Hot, isn't it? For us this counts as cool!"],
    ],
    cold: [
      ['哎呀，今天好冷！多穿点衣服。', "Oh, it's so cold today! Put more clothes on."],
      ['冻死了！你手套呢？', "Freezing! Where are your gloves?"],
      ['冷得我鼻子都没知觉了。', "It's so cold I can't feel my nose."],
      ['这还不算冷，等风刮起来你就知道了。', "This isn't cold yet. Wait till the wind picks up."],
      ['去喝点热的吧，暖暖身子。', 'Go and have something hot to drink. It warms you up.'],
    ],
    mild: [
      ['今天天气真好。', 'Lovely weather today.'],
      ['不冷不热，舒服极了，对吧？', "Not cold, not hot. So comfortable, isn't it?"],
      ['这种天就该出来走走。', 'A day like this, you should be outside.'],
      ['天气这么好，希望能多晴几天。', "Such nice weather. Let's hope it stays a few more days."],
      ['就是为了这样的日子，我们才住在这儿。', 'Days like this are why we live here.'],
    ],
    late: [
      ['已经很晚了，晚上街上很安静。', "It's late. The streets are quiet at night."],
      ['这个点儿，外面就剩猫了。还有咱俩！', "At this hour only the cats are out. And the two of us!"],
      ['我早该睡了，你怎么还不睡？', "I should have been in bed long ago. Why aren't you?"],
      ['你看天上的星星！这儿看得最清楚。', 'Look at the stars! You see them best from here.'],
    ],
    early: [
      ['起得真早！一天里最好的时候。', "You're up early! The best time of the day."],
      ['早点铺刚开门，跟着香味走就对了！', 'The breakfast stall has just opened. Just follow the smell!'],
      ['这么早？城里还没睡醒呢。', 'This early? The town is not even awake yet.'],
      ['我就喜欢这儿的早晨，还没开始吵。', 'I love the mornings here, before the noise starts.'],
    ],
    country: [
      ['{country}是一个美丽的国家，好好享受吧！', '{country} is a beautiful country. Enjoy it!'],
      ['{country}，你觉得怎么样？', 'So, {country}: how do you like it?'],
      ['有机会就在{country}多走走，每个地方都不一样。', 'Travel around {country} if you can. Every place is different.'],
      ['说起{country}，三天三夜也讲不完。', 'You could talk about {country} for three days and nights and not finish.'],
    ],
    dish: [
      ['来了一定要尝尝{dish}。', 'While you are here you must try {dish}.'],
      ['{dish}吃过没有？没有？那可不行！', 'Have you had {dish}? No? Oh, that will not do!'],
      ['谁做的{dish}都比不上我妈做的。', 'Nobody makes {dish} like my mum.'],
      ['饿了就去吃{dish}，保证你不后悔。', "If you're hungry, go and eat {dish}. You won't regret it."],
    ],
    drink: [
      ['走之前来点{drink}吧，我们这儿就喝这个。', 'Have some {drink} before you go. That is what we drink here.'],
      ['忙了一天，来一杯{drink}最舒服。', 'After a long day, nothing beats {drink}.'],
      ['没喝过{drink}，等于白来。', "If you haven't had {drink}, you haven't really been here."],
      ['点{drink}的时候像个本地人，老板准喜欢你。', 'Order {drink} like a local and the owner will love you.'],
    ],
    festival: [
      ['你应该{festival}的时候再来，热闹极了！', 'You should come back for {festival}. It is so lively!'],
      ['一年里最好的时候就是{festival}。', 'The best time of the year here is {festival}.'],
      ['听说过{festival}吗？你肯定会喜欢。', "Have you heard of {festival}? You'd love it."],
      ['我每年都掰着手指头等{festival}。', 'Every year I count the days till {festival} on my fingers.'],
    ],
    sport: [
      ['我们这儿最火的是{sport}，男女老少都会。', 'The big thing here is {sport}. Young and old, everyone plays.'],
      ['你喜欢{sport}吗？我们这儿的人可着迷了。', 'Do you like {sport}? People here are crazy about it.'],
      ['一到比赛，满城都在聊{sport}。', 'On match days the whole town talks about nothing but {sport}.'],
      ['我们全家都玩{sport}，奶奶负责在旁边喊加油。', 'My whole family plays {sport}. Grandma is in charge of cheering.'],
    ],
    wonder: [
      ['有时间的话去看看{wonder}吧，一辈子忘不了。', 'If you have time, go and see {wonder}. You will never forget it.'],
      ['{wonder}你见过吗？全世界独一份。', 'Have you seen {wonder}? There is nothing else like it in the world.'],
      ['人这一辈子，总得去一次{wonder}。', 'Everyone should see {wonder} once in their life.'],
      ['我小时候去过{wonder}，到现在还会梦到。', 'I went to {wonder} as a child. I still dream about it.'],
    ],
    pride: [
      ['说到骄傲，我们最自豪的就是{pride}。', 'If you ask what we are proud of, it is {pride}.'],
      ['走之前一定要了解一下{pride}，那就是我们。', "Before you leave, learn about {pride}. That's who we are."],
      ['我们最骄傲的是什么？{pride}。', 'What are we proudest of? {pride}.'],
      ['随便问谁{pride}，都能跟你聊上半天。', 'Ask anyone here about {pride} and they will talk for hours.'],
    ],
    proverb: [
      ['我们这儿有句话：“{proverb}”', 'We have a saying here: “{proverb}”'],
      ['我奶奶老说：“{proverb}”', 'My grandma always used to say: “{proverb}”'],
      ['老话说得好：“{proverb}”', 'As the old saying goes: “{proverb}”'],
      ['你听过这句话吗？“{proverb}”', 'Have you heard this one? “{proverb}”'],
    ],
    chat: [
      ['你是哪里人？你不是本地人吧。', "Where are you from? You're not from around here, are you?"],
      ['慢慢逛，这里有很多值得看的东西。', 'Take your time. There is a lot worth seeing here.'],
      ['一个人出来旅行啊？真有胆量。', 'Travelling on your own? That takes guts.'],
      ['看你的样子，走了不少路吧。', 'You look like you have walked a long way.'],
      ['迷路了就问人，这儿的人都很热心。', 'If you get lost, just ask. People here are very helpful.'],
      ['到现在为止，哪儿最好玩？', "What's the best place you've been so far?"],
      ['我一直想出去看看世界，以后再说吧。', 'I have always wanted to see the world. Some day, maybe.'],
      ['吃饭了没？附近有家小馆子特别地道。', "Have you eaten? There's a little place nearby that's the real thing."],
    ],
    childGreet: [
      ['你好！', 'Hi!'],
      ['你好！你是谁呀？', 'Hello! Who are you?'],
      ['哇，你好高啊！', "Wow, you're so tall!"],
      ['你好你好你好！', 'Hello hello hello!'],
    ],
    childChat: [
      ['我跑得可快了！要不要看？等会儿吧。', 'I can run really fast! Want to see? Maybe later.'],
      ['你是游客吗？我同学说游客都很有钱。', 'Are you a tourist? My classmate says tourists are all rich.'],
      ['我昨天掉了一颗牙！你看！哎，看不见。', "I lost a tooth yesterday! Look! Oh, you can't see it."],
      ['妈妈说不能跟陌生人说话，可你看起来挺好的。', 'Mum says not to talk to strangers, but you look nice.'],
      ['你家有小狗吗？我好想养一只。', "Do you have a puppy? I really want one."],
      ['我长大要开飞机，绕地球飞一圈！', "When I grow up I'm going to fly a plane all the way round the world!"],
      ['你会玩石头剪刀布吗？我每次都赢！', 'Can you play rock-paper-scissors? I win every time!'],
    ],
    childBye: [
      ['拜拜！', 'Bye bye!'],
      ['拜拜！下次再来找我玩！', 'Bye! Come and play with me next time!'],
      ['我得走了，妈妈在叫我！', 'I have to go, Mum is calling me!'],
      ['再见！明天见！', 'Bye! See you tomorrow!'],
    ],
    grumpyGreet: [
      ['嗯？干吗？', 'Hm? What is it?'],
      ['有事吗？', 'Something you want?'],
      ['哼，又一个游客。', 'Hmph. Another tourist.'],
      ['嗯……你好吧。', 'Hm... hello, I suppose.'],
    ],
    grumpyChat: [
      ['以前这儿多清静，现在全是来旅游的。', 'It used to be so peaceful here. Now it is all tourists.'],
      ['现在什么都贵，一碗面比以前贵一倍。', 'Everything is expensive now. A bowl of noodles costs twice what it did.'],
      ['别挡道，这儿可是有人住的。', "Don't block the way. People live here, you know."],
      ['现在的年轻人啊，走路都盯着手机。', 'Young people these days, staring at their phones even when they walk.'],
      ['真不明白有什么好看的，不就是几条街嘛。', "I don't know what there is to see. It's just a few streets."],
    ],
    grumpyBye: [
      ['行了，走吧走吧。', 'Right, off you go, off you go.'],
      ['好了，不耽误你了。', "Well, I won't keep you."],
      ['嗯，再见。', 'Hm. Goodbye.'],
      ['走路看着点儿，别踩了我的花。', 'Watch where you walk. Mind my flowers.'],
    ],
    elderChat: [
      ['我小时候，这儿全是庄稼地。', 'When I was little, this was all farmland.'],
      ['我在这儿住了一辈子，八十年了！你信吗？', "I've lived here all my life. Eighty years! Can you believe it?"],
      ['我们那时候去哪儿都靠两条腿。你也走路？好！', 'In my day we went everywhere on foot. You walk too? Good!'],
      ['孙子孙女都在外地，逢年过节才回来。', 'My grandchildren live far away. They only come back for the holidays.'],
      ['变化太快了，就剩这几条老街还跟以前一样。', 'Things change so fast. Only these old streets are the same as before.'],
    ],
    chattyChat: [
      ['哎呀，我最喜欢跟外地人聊天了！你先说，不对不对，我先说！', 'Oh, I love chatting to visitors! You go first. No, no, let me go first!'],
      ['我表哥出去旅游了一趟，回来带了个媳妇！', 'My cousin went travelling once and came back with a wife!'],
      ['朋友都说我是个话痨，说得一点没错！', "My friends say I'm a chatterbox, and they are absolutely right!"],
      ['吃了吗？你看着饿了。在我眼里谁都像没吃饱的。', 'Have you eaten? You look hungry. Everyone looks hungry to me.'],
      ['告诉你个秘密：看全城最好的地方是后面那座小山。', 'Let me tell you a secret: the best view of town is from the little hill behind.'],
    ],
    bye: [
      ['再见！一路顺风。', 'Goodbye! Have a smooth journey.'],
      ['保重！接下来玩得开心。', 'Take care! Enjoy the rest of your trip.'],
      ['一路平安啊，朋友！', 'Safe travels, friend!'],
      ['拜拜！有空再来玩啊。', 'Bye! Come back and visit when you can.'],
      ['跟你聊天真开心，照顾好自己！', 'It was lovely talking to you. Look after yourself!'],
      ['去吧去吧！好玩的地方多着呢。', "Off you go! There's so much more to see."],
    ],
  },
  countries: {
    // Every fact is a bare noun phrase with no measure word, as it stands after 尝尝, 喝, 去看, 是.
    CHN: {
      dish: ['北京烤鸭', 'Peking duck'],
      drink: ['绿茶', 'green tea'],
      festival: ['春节', 'the Spring Festival'],
      sport: ['乒乓球', 'table tennis'],
      wonder: ['长城', 'the Great Wall'],
      pride: ['五千年的历史和文化', 'five thousand years of history and culture'],
      proverb: ['不到长城非好汉', "You're not a true hero until you've reached the Great Wall"],
    },
    SGP: {
      dish: ['海南鸡饭', 'Hainanese chicken rice'],
      drink: ['拉茶', 'teh tarik, pulled milk tea'],
      festival: ['农历新年', 'Lunar New Year'],
      sport: ['足球', 'football'],
      wonder: ['滨海湾花园', 'Gardens by the Bay'],
      pride: ['小贩中心的美食文化', 'the food culture of the hawker centres'],
      proverb: ['入乡随俗', 'When you enter a village, follow its customs'],
    },
  },
};

export default ZH;
