/**
 * The flag specs. `flags.ts` explains the coordinate system and paints these.
 *
 * ## The colour decision, made on purpose
 *
 * These are **true flag colours, not palette colours**, and that is a departure
 * from every other file in the project.
 *
 * `theme.ts` exists so that a monument written by one hand and a coastline
 * generated by another look like one drawing. That argument does not survive
 * contact with a flag. A flag is not scenery invented for this world, it is a
 * quotation of a real object, and a red that is not Spain's red does not read as
 * a stylistic choice — it reads as a mistake, to everyone who has ever seen the
 * Spanish flag, which is everyone. The palette has one red, one green and one
 * blue; the world has Spain, Portugal, Italy and Mexico all wanting a different
 * green, and pulling them to a single one would make four flags wrong to save an
 * abstraction.
 *
 * What holds the flags to the rest of the drawing is not their fills but their
 * ink: every flag is framed by the same 3px `#1e0603` border, the same 12px
 * radius and the same hard shadow as the HUD cards, all of them palette values.
 * Flat fills inside, palette ink around. The only palette colours that appear
 * here are on the fallback plate in `flags.ts`, which is deliberately not a flag.
 *
 * ## Fidelity
 *
 * Where a flag carries a coat of arms, it is reduced to a mark and the key goes
 * in `SIMPLIFIED`. At the sizes this is drawn a real one is four illegible
 * pixels, and inventing detail is a worse lie than admitting to a placeholder.
 * Where a flag is a picture the vocabulary cannot honestly reach, it is left
 * out and falls through to the plate. A good spec with honest gaps beats a full
 * set where a fifth are wrong.
 */
import type { FlagSpec, Layer, Painter } from './flags.ts';

const TAU = Math.PI * 2;

const WHITE = '#ffffff';
const BLACK = '#000000';
/** The card cream, the one palette colour used as a field: see `nepal`. */
const CREAM = '#fff2e8';
const INK = '#1e0603';

/** Pan-Arab and pan-African, which between them account for some forty flags. */
const RED = '#ce1126';
const GREEN = '#007a3d';
const YELLOW = '#fcd116';

const UK_BLUE = '#012169';
const UK_RED = '#c8102e';

// --- shorthands ------------------------------------------------------------

const fill = (c: string): Layer => ({ t: 'fill', c });
const h = (...c: string[]): Layer => ({ t: 'bands', d: 'h', c });
const v = (...c: string[]): Layer => ({ t: 'bands', d: 'v', c });
const hw = (c: string[], w: number[]): Layer => ({ t: 'bands', d: 'h', c, w });
const vw = (c: string[], w: number[]): Layer => ({ t: 'bands', d: 'v', c, w });
const rect = (x: number, y: number, w: number, ht: number, c: string): Layer => ({ t: 'rect', x, y, w, h: ht, c });
const cross = (c: string, w: number, x?: number, y?: number, len?: number): Layer => ({ t: 'cross', c, w, x, y, len });
const disc = (x: number, y: number, r: number, c: string): Layer => ({ t: 'disc', x, y, r, c });
const ring = (x: number, y: number, r: number, w: number, c: string): Layer => ({ t: 'ring', x, y, r, w, c });
const star = (x: number, y: number, r: number, c: string, n?: number, rot?: number): Layer => ({ t: 'star', x, y, r, c, n, rot });
const stars = (x: number, y: number, rr: number, n: number, r: number, c: string, from?: number, to?: number): Layer =>
  ({ t: 'stars', x, y, rr, n, r, c, from, to });
const crescent = (x: number, y: number, r: number, cut: number, dx: number, c: string): Layer =>
  ({ t: 'crescent', x, y, r, cut, dx, c });
const sun = (x: number, y: number, r: number, n: number, len: number, c: string, spread?: number): Layer =>
  ({ t: 'sun', x, y, r, n, len, c, spread });
const poly = (points: number[][], c: string): Layer => ({ t: 'poly', p: points, c });
const draw = (f: (p: Painter) => void): Layer => ({ t: 'draw', f });

/** A triangle from the hoist, apex at mid-height. Twenty-odd flags have one. */
const hoist = (w: number, c: string): Layer => poly([[0, 0], [w, 0.5], [0, 1]], c);

/** Nordic crosses all sit at the same offset from the hoist. */
const NORDIC_X = 0.36;
const nordic = (c: string, w: number): Layer => cross(c, w, NORDIC_X);

// --- shared painters -------------------------------------------------------

/**
 * A stand-in for a coat of arms: a heater shield, a rim, and nothing else. Used
 * wherever a flag's centrepiece is heraldry. Anything more would be invention.
 */
function shieldPath(p: Painter, cx: number, cy: number, r: number): void {
  const { ctx } = p;
  const x = p.fx(cx);
  const y = p.fy(cy);
  const s = p.s(r);
  ctx.beginPath();
  ctx.moveTo(x - s * 0.8, y - s);
  ctx.lineTo(x + s * 0.8, y - s);
  ctx.lineTo(x + s * 0.8, y + s * 0.25);
  ctx.quadraticCurveTo(x + s * 0.8, y + s, x, y + s * 1.15);
  ctx.quadraticCurveTo(x - s * 0.8, y + s, x - s * 0.8, y + s * 0.25);
  ctx.closePath();
}

function shield(p: Painter, cx: number, cy: number, r: number, face: string, edge: string): void {
  const { ctx } = p;
  shieldPath(p, cx, cy, r);
  ctx.fillStyle = face;
  ctx.fill();
  ctx.lineWidth = p.s(r * 0.16);
  ctx.strokeStyle = edge;
  ctx.stroke();
}

/**
 * The double-headed eagle, for Albania, Montenegro and Serbia. A silhouette
 * built from two wings, two necks and a tail: at 70 pixels wide that is what
 * the real one resolves to anyway.
 */
function doubleEagle(p: Painter, cx: number, cy: number, r: number, c: string): void {
  const { ctx } = p;
  const x = p.fx(cx);
  const y = p.fy(cy);
  const s = p.s(r);
  ctx.fillStyle = c;
  // Body and tail, down the middle.
  ctx.beginPath();
  ctx.moveTo(x - s * 0.22, y - s * 0.22);
  ctx.lineTo(x + s * 0.22, y - s * 0.22);
  ctx.lineTo(x + s * 0.18, y + s * 0.40);
  ctx.lineTo(x + s * 0.40, y + s * 0.98);
  ctx.lineTo(x + s * 0.14, y + s * 0.86);
  ctx.lineTo(x, y + s * 1.0);
  ctx.lineTo(x - s * 0.14, y + s * 0.86);
  ctx.lineTo(x - s * 0.40, y + s * 0.98);
  ctx.lineTo(x - s * 0.18, y + s * 0.40);
  ctx.closePath();
  ctx.fill();
  for (const side of [-1, 1]) {
    // Wing: up and out from the shoulder, scalloped back down to the body.
    ctx.beginPath();
    ctx.moveTo(x + side * s * 0.18, y - s * 0.18);
    ctx.lineTo(x + side * s * 0.46, y - s * 0.50);
    ctx.lineTo(x + side * s * 0.92, y - s * 0.34);
    ctx.lineTo(x + side * s * 0.76, y - s * 0.10);
    ctx.lineTo(x + side * s * 0.94, y + s * 0.06);
    ctx.lineTo(x + side * s * 0.70, y + s * 0.22);
    ctx.lineTo(x + side * s * 0.82, y + s * 0.38);
    ctx.lineTo(x + side * s * 0.52, y + s * 0.48);
    ctx.lineTo(x + side * s * 0.20, y + s * 0.32);
    ctx.closePath();
    ctx.fill();
    // Neck, head and beak, turned outward. The heads carry the whole reading:
    // small ones make the bird look like a butterfly.
    ctx.beginPath();
    ctx.moveTo(x + side * s * 0.04, y - s * 0.22);
    ctx.quadraticCurveTo(x + side * s * 0.14, y - s * 0.66, x + side * s * 0.40, y - s * 0.74);
    ctx.lineTo(x + side * s * 0.50, y - s * 0.54);
    ctx.quadraticCurveTo(x + side * s * 0.28, y - s * 0.48, x + side * s * 0.26, y - s * 0.18);
    ctx.closePath();
    ctx.fill();
    ctx.beginPath();
    ctx.arc(x + side * s * 0.44, y - s * 0.76, s * 0.22, 0, TAU);
    ctx.fill();
    ctx.beginPath();
    ctx.moveTo(x + side * s * 0.58, y - s * 0.88);
    ctx.lineTo(x + side * s * 1.02, y - s * 0.76);
    ctx.lineTo(x + side * s * 0.58, y - s * 0.62);
    ctx.closePath();
    ctx.fill();
  }
}

/** The Union Flag, drawn from its construction rather than from memory. */
function unionJack(p: Painter): void {
  const { ctx } = p;
  p.fill(UK_BLUE);
  p.band(0, 0, 1, 1, 0.30, WHITE);
  p.band(1, 0, 0, 1, 0.30, WHITE);

  // The counterchange. Each red arm is offset perpendicular to its own
  // direction, always the same way round the flag, which is what gives the
  // design its 180-degree rotational symmetry and no mirror symmetry at all.
  // The test everyone knows: in the top hoist quadrant the broad white must be
  // *above* the red. Get the sign wrong and the flag flies upside down.
  const cx = p.fx(0.5);
  const cy = p.fy(0.5);
  for (const corner of [[0, 0], [1, 0], [1, 1], [0, 1]]) {
    ctx.save();
    ctx.beginPath();
    ctx.rect(p.fx(corner[0]! * 0.5), p.fy(corner[1]! * 0.5), p.w / 2, p.h / 2);
    ctx.clip();
    const dx = p.fx(corner[0]!) - cx;
    const dy = p.fy(corner[1]!) - cy;
    const len = Math.hypot(dx, dy);
    // perp = (dy, -dx): for the hoist-top arm that points left and down, which
    // puts the red below the centreline and the broad white above it.
    const ox = ((dy / len) * p.s(0.085));
    const oy = ((-dx / len) * p.s(0.085));
    ctx.beginPath();
    ctx.moveTo(cx + ox, cy + oy);
    ctx.lineTo(cx + dx * 1.2 + ox, cy + dy * 1.2 + oy);
    ctx.lineWidth = p.s(0.10);
    ctx.strokeStyle = UK_RED;
    ctx.stroke();
    ctx.restore();
  }

  p.layers([cross(WHITE, 0.34), cross(UK_RED, 0.20)]);
}

/** A British ensign: coloured field, union in the canton, badge in the fly. */
const ensign = (field: string, ...badge: Layer[]): FlagSpec => [
  fill(field),
  { t: 'flag', k: 'GBR', x: 0, y: 0, w: 0.5, h: 0.5 },
  ...badge,
];

/**
 * The badge on a British ensign is always a coat of arms, and there are nine of
 * them in this dataset. A white roundel with a coloured charge is what they all
 * reduce to; the colour is the one thing about each that is legible.
 */
const badge = (c: string): Layer[] => [
  disc(0.74, 0.48, 0.27, WHITE),
  draw((p) => shield(p, 0.74, 0.46, 0.18, c, INK)),
];

/**
 * The Sun of May, for Argentina and Uruguay: thirty-two rays alternating
 * straight and wavy. The wave is carried by the ray's length and width rather
 * than by an actual curve — at any size this gets drawn, a wavy ray and a
 * slightly longer straight one are the same handful of pixels. The human face
 * in the middle is the part that does not survive, which is why both flags are
 * in `SIMPLIFIED`.
 */
function sunOfMay(p: Painter, cx: number, cy: number, r: number, c: string): void {
  const { ctx } = p;
  const x = p.fx(cx);
  const y = p.fy(cy);
  ctx.fillStyle = c;
  for (let i = 0; i < 32; i++) {
    const a = (i / 32) * TAU;
    const len = p.s(r * (i % 2 === 0 ? 2.35 : 1.95));
    const half = (Math.PI / 32) * (i % 2 === 0 ? 0.9 : 0.6);
    ctx.beginPath();
    ctx.moveTo(x + Math.sin(a - half) * p.s(r), y - Math.cos(a - half) * p.s(r));
    ctx.lineTo(x + Math.sin(a) * len, y - Math.cos(a) * len);
    ctx.lineTo(x + Math.sin(a + half) * p.s(r), y - Math.cos(a + half) * p.s(r));
    ctx.closePath();
    ctx.fill();
  }
  p.disc(cx, cy, r, c);
}

/**
 * A field whose hoist edge is a row of points, as on Bahrain's and Qatar's. The
 * count is the whole difference between those two flags.
 */
function serrated(p: Painter, edge: number, count: number, depth: number, c: string): void {
  const path: number[][] = [[1, 0]];
  for (let i = 0; i <= count * 2; i++) {
    path.push([i % 2 === 0 ? edge : edge - depth, i / (count * 2)]);
  }
  path.push([1, 1]);
  p.poly(path, c);
}

/** Waves, for the two flags in this set that draw the sea. */
function waves(p: Painter, top: number, rows: number, span: number, c: string, width: number): void {
  const { ctx } = p;
  ctx.strokeStyle = c;
  ctx.lineWidth = p.s(width);
  ctx.lineCap = 'round';
  for (let r = 0; r < rows; r++) {
    const y = top + (span * (r + 0.5)) / rows;
    ctx.beginPath();
    for (let i = 0; i <= 48; i++) {
      const x = i / 48;
      const yy = y + Math.sin(i * 0.52) * 0.035;
      if (i === 0) ctx.moveTo(p.fx(x), p.fy(yy));
      else ctx.lineTo(p.fx(x), p.fy(yy));
    }
    ctx.stroke();
  }
}

// --- Europe ----------------------------------------------------------------

const EUROPE: Record<string, FlagSpec> = {
  ALA: [fill('#0053a5'), nordic('#ffce00', 0.24), nordic('#d21034', 0.10)],
  ALB: [fill('#e41e20'), draw((p) => doubleEagle(p, 0.5, 0.5, 0.32, BLACK))],
  AND: [
    vw(['#10069f', '#fedd00', '#d0103a'], [8, 9, 8]),
    draw((p) => shield(p, 0.5, 0.5, 0.26, '#fedd00', '#a00c1f')),
  ],
  AUT: [h('#ed2939', WHITE, '#ed2939')],
  BEL: [v(BLACK, '#fae042', '#ed2939')],
  BGR: [h(WHITE, '#00966e', '#d62612')],
  BIH: [
    fill('#002395'),
    // The right angle sits on the *upper fly* and the triangle spans the full
    // height, so the hypotenuse runs down to the right and the stars descend
    // with it. Drawn the other way round it is a different flag entirely.
    poly([[0.22, 0], [0.88, 0], [0.88, 1]], '#fecb00'),
    draw((p) => {
      // Seven whole stars and two halves, cut off by the top and bottom edges.
      for (let i = 0; i < 9; i++) {
        const t = -0.055 + (i * 1.11) / 8;
        p.star(0.11 + t * 0.66, t, 0.075, WHITE);
      }
    }),
  ],
  BLR: [
    hw(['#c8313e', '#4aa657'], [2, 1]),
    rect(0, 0, 0.11, 1, WHITE),
    // The hoist ornament, reduced to its motif: a stack of red diamonds.
    draw((p) => {
      for (let i = 0; i < 5; i++) {
        p.poly([[0.055, 0.06 + i * 0.2], [0.10, 0.16 + i * 0.2], [0.055, 0.26 + i * 0.2], [0.01, 0.16 + i * 0.2]], '#c8313e');
      }
    }),
  ],
  CHE: [fill('#d52b1e'), cross(WHITE, 0.20, 0.5, 0.5, 0.64)],
  CYP: [
    fill(WHITE),
    // Cyprus draws its own outline on its flag. Ours is hand-cut, not taken
    // from `countries.json`: this module has to work without the world loaded.
    poly([
      [0.22, 0.42], [0.27, 0.35], [0.34, 0.31], [0.42, 0.31], [0.49, 0.28],
      [0.56, 0.26], [0.63, 0.22], [0.72, 0.16], [0.80, 0.12], [0.81, 0.17],
      [0.72, 0.23], [0.64, 0.28], [0.57, 0.33], [0.53, 0.40], [0.46, 0.48],
      [0.36, 0.52], [0.27, 0.50],
    ], '#d57800'),
    // Two olive branches, rising from the foot of the flag.
    draw((p) => {
      const { ctx } = p;
      ctx.strokeStyle = '#4e5b31';
      ctx.lineWidth = p.s(0.04);
      ctx.lineCap = 'round';
      for (const side of [-1, 1]) {
        const tip = 0.5 + side * 0.22;
        ctx.beginPath();
        ctx.moveTo(p.fx(0.5), p.fy(0.92));
        ctx.quadraticCurveTo(p.fx(0.5 + side * 0.14), p.fy(0.86), p.fx(tip), p.fy(0.60));
        ctx.stroke();
        for (let i = 0; i < 4; i++) {
          const t = 0.28 + i * 0.22;
          const u = 1 - t;
          const lx = u * u * 0.5 + 2 * u * t * (0.5 + side * 0.14) + t * t * tip;
          const ly = u * u * 0.92 + 2 * u * t * 0.86 + t * t * 0.60;
          ctx.save();
          ctx.beginPath();
          ctx.ellipse(p.fx(lx), p.fy(ly), p.s(0.065), p.s(0.024), side * 1.1, 0, TAU);
          ctx.fillStyle = '#4e5b31';
          ctx.fill();
          ctx.restore();
        }
      }
    }),
  ],
  CZE: [h(WHITE, '#d7141a'), hoist(0.5, '#11457e')],
  DEU: [h(BLACK, '#dd0000', '#ffce00')],
  DNK: [fill('#c8102e'), nordic(WHITE, 0.24)],
  ESP: [
    hw(['#aa151b', '#f1bf00', '#aa151b'], [1, 2, 1]),
    // The arms, at the only level of detail that survives a 26-pixel chip: a
    // quartered shield between the two Pillars of Hercules, under a crown.
    draw((p) => {
      const { ctx } = p;
      const k = p.h / p.w;
      const cx = 0.33;
      for (const side of [-1, 1]) {
        const x = cx + side * 0.225 * k;
        p.rect(x - 0.009 * k, 0.36, 0.018 * k, 0.30, '#aa151b');
        p.rect(x - 0.016 * k, 0.335, 0.032 * k, 0.03, '#aa151b');
      }
      shield(p, cx, 0.5, 0.17, '#f1bf00', '#aa151b');
      ctx.save();
      shieldPath(p, cx, 0.5, 0.17);
      ctx.clip();
      p.rect(cx - 0.15 * k, 0.33, 0.15 * k, 0.17, '#aa151b');
      p.rect(cx, 0.50, 0.15 * k, 0.21, '#aa151b');
      p.rect(cx, 0.33, 0.15 * k, 0.17, '#f5f5f5');
      p.rect(cx - 0.15 * k, 0.50, 0.15 * k, 0.21, '#f5f5f5');
      ctx.restore();
      p.rect(cx - 0.055 * k, 0.285, 0.11 * k, 0.028, '#aa151b');
    }),
  ],
  EST: [h('#0072ce', BLACK, WHITE)],
  FIN: [fill(WHITE), nordic('#003580', 0.24)],
  FRA: [v('#002395', WHITE, '#ed2939')],
  FRO: [fill(WHITE), nordic('#0065bd', 0.28), nordic('#ed2939', 0.13)],
  GBR: [draw(unionJack)],
  GGY: [fill(WHITE), cross('#e8112d', 0.26), cross('#f9dd16', 0.09)],
  IMN: [
    fill('#cf142b'),
    // The triskelion: three armoured legs bent at the knee. Without the feet it
    // reads as an abstract pinwheel and, worse, as something else entirely.
    draw((p) => {
      const { ctx } = p;
      ctx.strokeStyle = '#f6d02f';
      ctx.lineWidth = p.s(0.10);
      ctx.lineCap = 'round';
      ctx.lineJoin = 'round';
      for (let i = 0; i < 3; i++) {
        const a = (i / 3) * TAU;
        const kx = p.fx(0.5) + Math.sin(a) * p.s(0.20);
        const ky = p.fy(0.5) - Math.cos(a) * p.s(0.20);
        const b = a + 2.1;
        const fx = kx + Math.sin(b) * p.s(0.20);
        const fy = ky - Math.cos(b) * p.s(0.20);
        ctx.beginPath();
        ctx.moveTo(p.fx(0.5), p.fy(0.5));
        ctx.lineTo(kx, ky);
        ctx.lineTo(fx, fy);
        ctx.stroke();
        // The foot, turned out from the shin.
        const c = b + 1.5;
        ctx.beginPath();
        ctx.moveTo(fx, fy);
        ctx.lineTo(fx + Math.sin(c) * p.s(0.11), fy - Math.cos(c) * p.s(0.11));
        ctx.stroke();
      }
      p.disc(0.5, 0.5, 0.075, '#f6d02f');
    }),
  ],
  IRL: [v('#169b62', WHITE, '#ff883e')],
  ISL: [fill('#02529c'), nordic(WHITE, 0.28), nordic('#dc1e35', 0.13)],
  ITA: [v('#008c45', '#f4f5f0', '#cd212a')],
  GRC: [
    hw([...Array.from({ length: 9 }, (_, i) => (i % 2 === 0 ? '#0d5eaf' : WHITE))], Array.from({ length: 9 }, () => 1)),
    draw((p) => {
      // The canton is five stripes tall and square, so its width is measured in
      // height units — not in width fractions like everything else here.
      const side = p.s(5 / 9);
      p.ctx.fillStyle = '#0d5eaf';
      p.ctx.fillRect(p.x, p.y, side, side);
      p.ctx.fillStyle = WHITE;
      p.ctx.fillRect(p.x, p.y + side / 2 - p.s(0.055), side, p.s(0.11));
      p.ctx.fillRect(p.x + side / 2 - p.s(0.055), p.y, p.s(0.11), side);
    }),
  ],
  GRL: [
    h(WHITE, '#d00c33'),
    // The disc is counterchanged: red where the flag is white, white where red.
    draw((p) => {
      const { ctx } = p;
      const x = p.fx(0.32);
      const y = p.fy(0.5);
      const r = p.s(0.34);
      ctx.beginPath();
      ctx.arc(x, y, r, Math.PI, TAU);
      ctx.fillStyle = '#d00c33';
      ctx.fill();
      ctx.beginPath();
      ctx.arc(x, y, r, 0, Math.PI);
      ctx.fillStyle = WHITE;
      ctx.fill();
    }),
  ],
  HRV: [
    h('#ff0000', WHITE, '#171796'),
    draw((p) => {
      shield(p, 0.5, 0.47, 0.24, WHITE, INK);
      // The chequy, clipped to the shield. In pixels: the cells have to be
      // square, and the shield is measured in height units.
      const { ctx } = p;
      ctx.save();
      shieldPath(p, 0.5, 0.47, 0.24);
      ctx.clip();
      const cell = p.s(0.077);
      const left = p.fx(0.5) - cell * 2.5;
      const top = p.fy(0.47) - p.s(0.24);
      ctx.fillStyle = '#ff0000';
      for (let r = 0; r < 6; r++) {
        for (let c = 0; c < 5; c++) {
          if ((r + c) % 2 === 0) ctx.fillRect(left + c * cell, top + r * cell, cell, cell);
        }
      }
      ctx.restore();
    }),
  ],
  HUN: [h('#cd2a3e', WHITE, '#436f4d')],
  JEY: [
    fill(WHITE),
    { t: 'saltire', c: '#e8112d', w: 0.20 },
    draw((p) => {
      p.disc(0.5, 0.22, 0.11, '#f9dd16');
      p.disc(0.5, 0.22, 0.06, '#e8112d');
    }),
  ],
  KOS: [
    fill('#244aa5'),
    // The gold outline of the country, cut by hand at this size.
    poly([
      [0.42, 0.30], [0.52, 0.32], [0.58, 0.42], [0.57, 0.55], [0.50, 0.68],
      [0.43, 0.70], [0.38, 0.62], [0.36, 0.46], [0.38, 0.34],
    ], '#d0a650'),
    stars(0.47, 0.86, 0.68, 6, 0.075, WHITE, -0.55, 0.55),
  ],
  LIE: [
    h('#002b7f', '#ce1126'),
    draw((p) => {
      p.disc(0.22, 0.25, 0.10, '#ffd83d');
      p.poly([[0.16, 0.30], [0.28, 0.30], [0.26, 0.20], [0.22, 0.25], [0.18, 0.20]], '#ffd83d');
    }),
  ],
  LTU: [h('#fdb913', '#006a44', '#c1272d')],
  LUX: [h('#ed2939', WHITE, '#00a1de')],
  LVA: [hw(['#9e3039', WHITE, '#9e3039'], [2, 1, 2])],
  MDA: [
    v('#0046ae', '#ffd200', '#cc092f'),
    draw((p) => shield(p, 0.5, 0.5, 0.22, '#cc092f', '#0046ae')),
  ],
  MKD: [
    fill('#d20000'),
    // Eight rays that broaden as they go, reaching the edges. Not a sun with a
    // rim: the rays *are* the design, so they are drawn as wedges to the corners.
    draw((p) => {
      const { ctx } = p;
      const x = p.fx(0.5);
      const y = p.fy(0.5);
      ctx.fillStyle = '#ffe600';
      const reach = Math.hypot(p.w, p.h);
      for (let i = 0; i < 8; i++) {
        const a = (i / 8) * TAU + Math.PI / 8;
        const half = 0.115;
        ctx.beginPath();
        ctx.moveTo(x + Math.sin(a - half) * p.s(0.12), y - Math.cos(a - half) * p.s(0.12));
        ctx.lineTo(x + Math.sin(a - half * 1.4) * reach, y - Math.cos(a - half * 1.4) * reach);
        ctx.lineTo(x + Math.sin(a + half * 1.4) * reach, y - Math.cos(a + half * 1.4) * reach);
        ctx.lineTo(x + Math.sin(a + half) * p.s(0.12), y - Math.cos(a + half) * p.s(0.12));
        ctx.closePath();
        ctx.fill();
      }
      p.disc(0.5, 0.5, 0.20, '#ffe600');
      p.disc(0.5, 0.5, 0.155, '#d20000');
    }),
  ],
  MLT: [
    v(WHITE, '#cf142b'),
    // The George Cross in the canton, on its grey ground.
    draw((p) => {
      const { ctx } = p;
      const w = p.s(0.22);
      const x = p.fx(0.05);
      const y = p.fy(0.10);
      ctx.fillStyle = '#efefef';
      ctx.fillRect(x, y, w, w * 1.2);
      ctx.strokeStyle = '#9a9a9a';
      ctx.lineWidth = p.s(0.016);
      ctx.strokeRect(x, y, w, w * 1.2);
      ctx.fillStyle = '#9a9a9a';
      ctx.fillRect(x + w * 0.4, y + w * 0.2, w * 0.2, w * 0.8);
      ctx.fillRect(x + w * 0.15, y + w * 0.45, w * 0.7, w * 0.2);
    }),
  ],
  MNE: [
    fill('#c40308'),
    draw((p) => {
      p.ctx.strokeStyle = '#d4af37';
      p.ctx.lineWidth = p.s(0.075);
      p.ctx.strokeRect(p.fx(0.02) + p.s(0.037), p.fy(0.02) + p.s(0.037), 0.96 * p.w - p.s(0.075), 0.96 * p.h - p.s(0.075));
      doubleEagle(p, 0.5, 0.5, 0.30, '#d4af37');
    }),
  ],
  NLD: [h('#ae1c28', WHITE, '#21468b')],
  NOR: [fill('#ba0c2f'), nordic(WHITE, 0.30), nordic('#00205b', 0.16)],
  POL: [h(WHITE, '#dc143c')],
  PRT: [
    rect(0, 0, 0.4, 1, '#006600'),
    rect(0.4, 0, 0.6, 1, '#ff0000'),
    // The armillary sphere: concentric rings and a band, then the shield.
    draw((p) => {
      const { ctx } = p;
      const x = p.fx(0.4);
      const y = p.fy(0.5);
      ctx.strokeStyle = '#ffd700';
      ctx.lineWidth = p.s(0.030);
      ctx.beginPath();
      ctx.arc(x, y, p.s(0.31), 0, TAU);
      ctx.stroke();
      ctx.beginPath();
      ctx.arc(x, y, p.s(0.235), 0, TAU);
      ctx.stroke();
      ctx.beginPath();
      ctx.ellipse(x, y, p.s(0.11), p.s(0.31), 0, 0, TAU);
      ctx.stroke();
      ctx.beginPath();
      ctx.ellipse(x, y, p.s(0.31), p.s(0.10), 0, 0, TAU);
      ctx.stroke();
      shield(p, 0.4, 0.5, 0.20, WHITE, '#ff0000');
      for (const [dx, dy] of [[0, -0.09], [0, 0.09], [-0.06, 0], [0.06, 0], [0, 0]]) {
        p.disc(0.4 + (dx! * p.h) / p.w, 0.5 + dy!, 0.028, '#003399');
      }
    }),
  ],
  ROU: [v('#002b7f', '#fcd116', '#ce1126')],
  RUS: [h(WHITE, '#0039a6', '#d52b1e')],
  SMR: [
    h(WHITE, '#5eb6e4'),
    draw((p) => {
      shield(p, 0.5, 0.5, 0.22, '#5eb6e4', '#c8b273');
      for (const dx of [-0.05, 0, 0.05]) {
        p.rect(0.5 + (dx * p.h) / p.w - 0.012, 0.42, 0.024, 0.12, WHITE);
      }
    }),
  ],
  SRB: [
    h('#c6363c', '#0c4076', WHITE),
    draw((p) => doubleEagle(p, 0.35, 0.5, 0.30, '#c6363c')),
  ],
  SVK: [
    h(WHITE, '#0b4ea2', '#ee1c25'),
    draw((p) => {
      shield(p, 0.36, 0.5, 0.26, '#ee1c25', WHITE);
      // The double cross on three hills.
      p.rect(0.36 - 0.012, 0.34, 0.024, 0.30, WHITE);
      p.rect(0.36 - 0.045, 0.40, 0.09, 0.045, WHITE);
      p.rect(0.36 - 0.062, 0.49, 0.124, 0.045, WHITE);
      p.poly([[0.30, 0.68], [0.36, 0.60], [0.42, 0.68]], '#0b4ea2');
    }),
  ],
  SVN: [
    h(WHITE, '#0000c4', '#e03c31'),
    draw((p) => {
      shield(p, 0.30, 0.42, 0.24, '#0000c4', WHITE);
      p.poly([[0.24, 0.52], [0.30, 0.34], [0.36, 0.52]], WHITE);
      p.stars(0.30, 0.26, 0.10, 2, 0.035, '#ffdf00', -1.2, 1.2);
    }),
  ],
  SWE: [fill('#006aa7'), nordic('#fecc00', 0.26)],
  UKR: [h('#0057b7', '#ffd700')],
};

// --- Asia ------------------------------------------------------------------

const ASIA: Record<string, FlagSpec> = {
  // The black-red-green tricolour, which is what flies for Afghanistan at the
  // United Nations. The 2021 change is contested; this is the neutral answer.
  AFG: [v(BLACK, '#be0000', '#007a36'), ring(0.5, 0.48, 0.21, 0.05, WHITE), rect(0.44, 0.68, 0.12, 0.035, WHITE)],
  ARE: [h(GREEN, WHITE, BLACK), rect(0, 0, 0.25, 1, RED)],
  ARM: [h('#d90012', '#0033a0', '#f2a800')],
  AZE: [
    h('#00b5e2', '#ed2939', '#3f9c35'),
    crescent(0.44, 0.5, 0.15, 0.12, 0.045, WHITE),
    star(0.60, 0.5, 0.09, WHITE, 8),
  ],
  BGD: [fill('#006a4d'), disc(0.45, 0.5, 0.30, '#f42a41')],
  BHR: [fill(WHITE), draw((p) => serrated(p, 0.32, 5, 0.10, '#ce1126'))],
  BRN: [
    fill('#f7e017'),
    poly([[0, 0.22], [1, 0.55], [1, 0.75], [0, 0.42]], WHITE),
    poly([[0, 0.42], [1, 0.75], [1, 0.92], [0, 0.60]], BLACK),
    draw((p) => {
      p.disc(0.5, 0.52, 0.16, '#e8112d');
      p.poly([[0.42, 0.44], [0.58, 0.44], [0.55, 0.62], [0.45, 0.62]], '#f7e017');
    }),
  ],
  BTN: [
    poly([[0, 0], [1, 0], [0, 1]], '#ffd520'),
    poly([[1, 0], [1, 1], [0, 1]], '#ff4e12'),
    // The dragon, as a body arcing along the divide with a head at the fly.
    draw((p) => {
      const { ctx } = p;
      ctx.strokeStyle = WHITE;
      ctx.lineWidth = p.s(0.13);
      ctx.lineCap = 'round';
      ctx.lineJoin = 'round';
      ctx.beginPath();
      ctx.moveTo(p.fx(0.16), p.fy(0.78));
      ctx.quadraticCurveTo(p.fx(0.42), p.fy(0.34), p.fx(0.66), p.fy(0.44));
      ctx.quadraticCurveTo(p.fx(0.82), p.fy(0.50), p.fx(0.86), p.fy(0.30));
      ctx.stroke();
      p.disc(0.86, 0.28, 0.09, WHITE);
      p.poly([[0.90, 0.22], [0.99, 0.16], [0.92, 0.30]], WHITE);
    }),
  ],
  CHN: [
    fill('#ee1c25'),
    star(0.17, 0.28, 0.16, '#ffde00'),
    draw((p) => {
      // The four small stars each point at the big one.
      const small: number[][] = [[0.33, 0.11], [0.38, 0.22], [0.38, 0.36], [0.33, 0.47]];
      for (const [sx, sy] of small) {
        const a = Math.atan2((0.17 - sx!) * p.w, -(0.28 - sy!) * p.h);
        p.star(sx!, sy!, 0.055, '#ffde00', 5, -a);
      }
    }),
  ],
  GEO: [
    fill(WHITE),
    cross('#ff0000', 0.20),
    draw((p) => {
      for (const [qx, qy] of [[0.24, 0.25], [0.76, 0.25], [0.24, 0.75], [0.76, 0.75]]) {
        p.layers([cross('#ff0000', 0.045, qx, qy, 0.17)]);
      }
    }),
  ],
  HKG: [
    fill('#de2910'),
    draw((p) => {
      // Five petals turning about the centre.
      for (let i = 0; i < 5; i++) {
        const a = (i / 5) * TAU;
        const { ctx } = p;
        ctx.save();
        ctx.translate(p.fx(0.5), p.fy(0.5));
        ctx.rotate(a);
        ctx.beginPath();
        ctx.moveTo(0, 0);
        ctx.quadraticCurveTo(p.s(0.14), -p.s(0.22), 0, -p.s(0.30));
        ctx.quadraticCurveTo(-p.s(0.14), -p.s(0.22), 0, 0);
        ctx.fillStyle = WHITE;
        ctx.fill();
        ctx.restore();
      }
    }),
  ],
  IDN: [h('#ff0000', WHITE)],
  IND: [
    h('#ff9933', WHITE, '#138808'),
    draw((p) => {
      p.ring(0.5, 0.5, 0.13, 0.022, '#000080');
      const { ctx } = p;
      ctx.strokeStyle = '#000080';
      ctx.lineWidth = p.s(0.012);
      for (let i = 0; i < 24; i++) {
        const a = (i / 24) * TAU;
        ctx.beginPath();
        ctx.moveTo(p.fx(0.5) + Math.sin(a) * p.s(0.02), p.fy(0.5) - Math.cos(a) * p.s(0.02));
        ctx.lineTo(p.fx(0.5) + Math.sin(a) * p.s(0.13), p.fy(0.5) - Math.cos(a) * p.s(0.13));
        ctx.stroke();
      }
      p.disc(0.5, 0.5, 0.028, '#000080');
    }),
  ],
  IRN: [
    h('#239f40', WHITE, '#da0000'),
    draw((p) => {
      // The emblem: four crescents around a central sword.
      p.rect(0.5 - 0.008, 0.38, 0.016, 0.24, '#da0000');
      for (const side of [-1, 1]) {
        p.crescent(0.5 + (side * 0.055 * p.h) / p.w, 0.5, 0.11, 0.085, side * 0.03, '#da0000');
      }
      // The band edges carry a repeated inscription; at this size it is a rhythm.
      const { ctx } = p;
      ctx.fillStyle = '#da0000';
      for (let i = 0; i < 22; i++) ctx.fillRect(p.fx(0.02 + i * 0.045), p.fy(0.345), p.s(0.016), p.s(0.028));
      ctx.fillStyle = '#239f40';
      for (let i = 0; i < 22; i++) ctx.fillRect(p.fx(0.02 + i * 0.045), p.fy(0.628), p.s(0.016), p.s(0.028));
    }),
  ],
  IRQ: [
    h('#ce1126', WHITE, BLACK),
    draw((p) => {
      const { ctx } = p;
      ctx.strokeStyle = '#007a3d';
      ctx.lineWidth = p.s(0.035);
      ctx.lineCap = 'round';
      for (let i = 0; i < 3; i++) {
        ctx.beginPath();
        ctx.moveTo(p.fx(0.34 + i * 0.11), p.fy(0.56));
        ctx.quadraticCurveTo(p.fx(0.39 + i * 0.11), p.fy(0.40), p.fx(0.44 + i * 0.11), p.fy(0.56));
        ctx.stroke();
      }
      ctx.beginPath();
      ctx.moveTo(p.fx(0.30), p.fy(0.58));
      ctx.lineTo(p.fx(0.70), p.fy(0.58));
      ctx.stroke();
    }),
  ],
  ISR: [
    fill(WHITE),
    rect(0, 0.14, 1, 0.11, '#0038b8'),
    rect(0, 0.75, 1, 0.11, '#0038b8'),
    draw((p) => {
      const { ctx } = p;
      ctx.strokeStyle = '#0038b8';
      ctx.lineWidth = p.s(0.035);
      for (const flip of [1, -1]) {
        ctx.beginPath();
        for (let i = 0; i < 3; i++) {
          const a = (i / 3) * TAU;
          const x = p.fx(0.5) + Math.sin(a) * p.s(0.20) * 1;
          const y = p.fy(0.5) - flip * Math.cos(a) * p.s(0.20);
          if (i === 0) ctx.moveTo(x, y);
          else ctx.lineTo(x, y);
        }
        ctx.closePath();
        ctx.stroke();
      }
    }),
  ],
  JOR: [h(BLACK, WHITE, '#007a3b'), hoist(0.36, RED), star(0.14, 0.5, 0.09, WHITE, 7)],
  JPN: [fill(WHITE), disc(0.5, 0.5, 0.30, '#bc002d')],
  KAZ: [
    fill('#00afca'),
    sun(0.52, 0.44, 0.11, 32, 0.10, '#fec50c', 0.3),
    draw((p) => {
      // The steppe eagle below the sun: two long wings and a small body.
      for (const side of [-1, 1]) {
        p.poly([
          [0.52 + side * 0.01, 0.70], [0.52 + side * 0.10, 0.655], [0.52 + side * 0.20, 0.645],
          [0.52 + side * 0.16, 0.685], [0.52 + side * 0.07, 0.715],
        ], '#fec50c');
      }
      p.poly([[0.505, 0.66], [0.535, 0.66], [0.528, 0.78], [0.512, 0.78]], '#fec50c');
      p.disc(0.52, 0.645, 0.022, '#fec50c');
      for (let i = 0; i < 6; i++) {
        p.poly([[0.03, 0.06 + i * 0.155], [0.075, 0.115 + i * 0.155], [0.03, 0.17 + i * 0.155]], '#fec50c');
      }
    }),
  ],
  KGZ: [
    fill('#e8112d'),
    sun(0.5, 0.5, 0.17, 40, 0.10, '#ffef00', 0.3),
    draw((p) => {
      const { ctx } = p;
      ctx.strokeStyle = '#e8112d';
      ctx.lineWidth = p.s(0.022);
      ctx.beginPath();
      ctx.arc(p.fx(0.5), p.fy(0.5), p.s(0.115), 0, TAU);
      ctx.stroke();
      for (let i = 0; i < 3; i++) {
        const a = (i / 3) * TAU;
        ctx.beginPath();
        ctx.moveTo(p.fx(0.5) - Math.sin(a) * p.s(0.13), p.fy(0.5) + Math.cos(a) * p.s(0.13));
        ctx.lineTo(p.fx(0.5) + Math.sin(a) * p.s(0.13), p.fy(0.5) - Math.cos(a) * p.s(0.13));
        ctx.stroke();
      }
    }),
  ],
  KHM: [
    hw(['#032ea1', '#e00025', '#032ea1'], [1, 2, 1]),
    // Angkor Wat: three towers on a plinth.
    draw((p) => {
      for (const [tx, ty] of [[0.5, 0.30], [0.415, 0.38], [0.585, 0.38]]) {
        p.poly([[tx! - 0.035, 0.62], [tx! - 0.028, ty! + 0.06], [tx!, ty!], [tx! + 0.028, ty! + 0.06], [tx! + 0.035, 0.62]], WHITE);
      }
      p.rect(0.36, 0.62, 0.28, 0.035, WHITE);
      p.rect(0.33, 0.665, 0.34, 0.03, WHITE);
    }),
  ],
  KOR: [
    fill(WHITE),
    draw((p) => {
      const { ctx } = p;
      const x = p.fx(0.5);
      const y = p.fy(0.5);
      const r = p.s(0.24);
      ctx.save();
      ctx.translate(x, y);
      ctx.rotate(-Math.PI / 3);
      ctx.beginPath();
      ctx.arc(0, 0, r, 0, TAU);
      ctx.fillStyle = '#cd2e3a';
      ctx.fill();
      ctx.beginPath();
      ctx.arc(0, 0, r, 0, Math.PI);
      ctx.fillStyle = '#0047a0';
      ctx.fill();
      ctx.beginPath();
      ctx.arc(-r / 2, 0, r / 2, 0, TAU);
      ctx.fillStyle = '#cd2e3a';
      ctx.fill();
      ctx.beginPath();
      ctx.arc(r / 2, 0, r / 2, 0, TAU);
      ctx.fillStyle = '#0047a0';
      ctx.fill();
      ctx.restore();
      // The four trigrams, each a stack of three bars facing the centre.
      const trigrams: [number, number, number[]][] = [
        [-1, -1, [1, 1, 1]],
        [-1, 1, [1, 0, 1]],
        [1, -1, [0, 1, 0]],
        [1, 1, [0, 0, 0]],
      ];
      ctx.fillStyle = BLACK;
      for (const [sx, sy, bars] of trigrams) {
        ctx.save();
        ctx.translate(p.fx(0.5 + sx * 0.215), p.fy(0.5 + sy * 0.30));
        ctx.rotate(Math.atan2(-sx * 0.215 * p.w, sy * 0.30 * p.h));
        const bw = p.s(0.20);
        const bh = p.s(0.028);
        bars.forEach((solid, i) => {
          const by = (i - 1) * p.s(0.048) - bh / 2;
          if (solid === 1) ctx.fillRect(-bw / 2, by, bw, bh);
          else {
            ctx.fillRect(-bw / 2, by, bw * 0.42, bh);
            ctx.fillRect(bw * 0.08, by, bw * 0.42, bh);
          }
        });
        ctx.restore();
      }
    }),
  ],
  KWT: [
    h(GREEN, WHITE, RED),
    poly([[0, 0], [0.28, 1 / 3], [0.28, 2 / 3], [0, 1]], BLACK),
  ],
  LAO: [hw([RED, '#002868', RED], [1, 2, 1]), disc(0.5, 0.5, 0.22, WHITE)],
  LBN: [
    hw(['#ed1c24', WHITE, '#ed1c24'], [1, 2, 1]),
    draw((p) => {
      p.rect(0.49, 0.55, 0.02, 0.12, '#6b4423');
      for (let i = 0; i < 3; i++) {
        const w = 0.16 - i * 0.045;
        p.poly([[0.5 - w, 0.60 - i * 0.09], [0.5 + w, 0.60 - i * 0.09], [0.5, 0.44 - i * 0.09]], '#00a850');
      }
    }),
  ],
  LKA: [
    fill('#ffbe29'),
    rect(0.04, 0.08, 0.14, 0.84, '#00534e'),
    rect(0.18, 0.08, 0.14, 0.84, '#eb7400'),
    rect(0.36, 0.08, 0.60, 0.84, '#8d153a'),
    draw((p) => {
      // The lion: a body, a maned head, four legs, a tail and a raised sword.
      const gold = '#ffbe29';
      p.poly([[0.56, 0.42], [0.78, 0.42], [0.80, 0.56], [0.56, 0.58]], gold);
      p.disc(0.56, 0.40, 0.075, gold);
      for (const lx of [0.60, 0.68, 0.74]) p.rect(lx, 0.56, 0.022, 0.14, gold);
      p.poly([[0.79, 0.44], [0.86, 0.30], [0.89, 0.33], [0.82, 0.48]], gold);
      p.rect(0.518, 0.16, 0.014, 0.24, gold);
      p.poly([[0.505, 0.38], [0.545, 0.38], [0.525, 0.44]], gold);
      for (const [lx, ly] of [[0.40, 0.16], [0.40, 0.82], [0.90, 0.16], [0.90, 0.82]]) {
        p.poly([[lx!, ly! - 0.09], [lx! + 0.035, ly!], [lx!, ly! + 0.09], [lx! - 0.035, ly!]], '#ffbe29');
      }
    }),
  ],
  MMR: [h('#fecb00', '#34b233', '#ea2839'), star(0.5, 0.5, 0.34, WHITE)],
  MNG: [
    v('#c4272f', '#015197', '#c4272f'),
    draw((p) => {
      // The soyombo, as its stack: flame, sun, moon, then the bars.
      const x = 0.165;
      p.poly([[x - 0.03, 0.24], [x, 0.13], [x + 0.03, 0.24]], '#f9cf02');
      p.disc(x, 0.29, 0.035, '#f9cf02');
      p.crescent(x, 0.375, 0.05, 0.04, 0.018, '#f9cf02');
      p.rect(x - 0.05, 0.44, 0.10, 0.035, '#f9cf02');
      p.rect(x - 0.05, 0.70, 0.10, 0.035, '#f9cf02');
      p.rect(x - 0.05, 0.52, 0.026, 0.15, '#f9cf02');
      p.rect(x + 0.024, 0.52, 0.026, 0.15, '#f9cf02');
      p.poly([[x - 0.02, 0.52], [x + 0.02, 0.52], [x, 0.60]], '#f9cf02');
      p.poly([[x - 0.02, 0.67], [x + 0.02, 0.67], [x, 0.59]], '#f9cf02');
    }),
  ],
  MYS: [
    hw(Array.from({ length: 14 }, (_, i) => (i % 2 === 0 ? '#cc0001' : WHITE)), Array.from({ length: 14 }, () => 1)),
    rect(0, 0, 0.5, 8 / 14, '#010066'),
    crescent(0.18, 0.28, 0.14, 0.115, 0.045, '#ffcc00'),
    star(0.32, 0.30, 0.11, '#ffcc00', 14),
  ],
  NPL: [
    // Not a rectangle, and pretending otherwise would be the one flag everyone
    // notices. The box stays card-coloured and the pennant is drawn inside it.
    fill(CREAM),
    draw((p) => {
      const { ctx } = p;
      const outline: number[][] = [[0.14, 0.06], [0.68, 0.40], [0.38, 0.40], [0.80, 0.87], [0.14, 0.87]];
      ctx.lineJoin = 'round';
      // Widest stroke first, then narrower, then the fill: the ink ends up
      // outside the blue border and the blue outside the crimson, in one pass.
      p.polyPath(outline);
      ctx.lineWidth = p.s(0.13);
      ctx.strokeStyle = INK;
      ctx.stroke();
      ctx.lineWidth = p.s(0.10);
      ctx.strokeStyle = '#003893';
      ctx.stroke();
      ctx.fillStyle = '#dc143c';
      ctx.fill();
      // Moon above, sun below.
      p.crescent(0.27, 0.22, 0.08, 0.062, 0.026, WHITE);
      p.sun(0.29, 0.64, 0.042, 12, 0.034, WHITE, 0.55);
    }),
  ],
  OMN: [
    h(WHITE, '#db161b', '#008000'),
    rect(0, 0, 0.28, 1, '#db161b'),
    draw((p) => {
      // Khanjar and two crossed sabres.
      p.rect(0.135, 0.10, 0.015, 0.14, WHITE);
      p.crescent(0.142, 0.24, 0.075, 0.06, 0.0, WHITE);
      p.band(0.06, 0.10, 0.22, 0.24, 0.018, WHITE);
      p.band(0.22, 0.10, 0.06, 0.24, 0.018, WHITE);
    }),
  ],
  PAK: [
    fill('#01411c'),
    rect(0, 0, 0.25, 1, WHITE),
    crescent(0.60, 0.52, 0.24, 0.19, 0.07, WHITE),
    star(0.76, 0.36, 0.11, WHITE, 5, 0.6),
  ],
  PHL: [
    h('#0038a8', '#ce1126'),
    hoist(0.5, WHITE),
    sun(0.17, 0.5, 0.075, 8, 0.075, '#fcd116', 0.35),
    star(0.055, 0.11, 0.055, '#fcd116'),
    star(0.055, 0.89, 0.055, '#fcd116'),
    star(0.44, 0.5, 0.055, '#fcd116'),
  ],
  PRK: [
    hw(['#024fa2', WHITE, '#ed1c27', WHITE, '#024fa2'], [6, 2, 20, 2, 6]),
    disc(0.33, 0.5, 0.20, WHITE),
    star(0.33, 0.5, 0.155, '#ed1c27'),
  ],
  PSE: [h(BLACK, WHITE, '#007a3b'), hoist(0.36, RED)],
  QAT: [fill(WHITE), draw((p) => serrated(p, 0.32, 9, 0.10, '#8a1538'))],
  SAU: [
    fill('#006c35'),
    draw((p) => {
      // The shahada above the sword: a script rhythm, not letters.
      const { ctx } = p;
      ctx.strokeStyle = WHITE;
      ctx.lineWidth = p.s(0.045);
      ctx.lineCap = 'round';
      ctx.beginPath();
      ctx.moveTo(p.fx(0.16), p.fy(0.42));
      ctx.lineTo(p.fx(0.84), p.fy(0.42));
      ctx.stroke();
      ctx.lineWidth = p.s(0.028);
      for (let i = 0; i < 7; i++) {
        const x = 0.20 + i * 0.095;
        ctx.beginPath();
        ctx.moveTo(p.fx(x), p.fy(0.40));
        ctx.quadraticCurveTo(p.fx(x + 0.03), p.fy(0.24), p.fx(x + 0.06), p.fy(0.38));
        ctx.stroke();
      }
      p.rect(0.22, 0.62, 0.62, 0.045, WHITE);
      p.poly([[0.22, 0.605], [0.10, 0.6425], [0.22, 0.68]], WHITE);
      p.rect(0.84, 0.585, 0.035, 0.10, WHITE);
    }),
  ],
  SGP: [
    h('#ed2939', WHITE),
    crescent(0.22, 0.25, 0.17, 0.135, 0.05, WHITE),
    stars(0.36, 0.25, 0.11, 5, 0.05, WHITE),
  ],
  // Adopted in 2025, replacing the 1980 flag. Green over white over black with
  // three red stars.
  SYR: [h('#007a3d', WHITE, BLACK), star(0.35, 0.5, 0.10, '#ce1126'), star(0.5, 0.5, 0.10, '#ce1126'), star(0.65, 0.5, 0.10, '#ce1126')],
  THA: [hw(['#a51931', WHITE, '#2d2a4a', WHITE, '#a51931'], [1, 1, 2, 1, 1])],
  TJK: [
    hw(['#cc0000', WHITE, '#006600'], [2, 3, 2]),
    draw((p) => {
      p.poly([[0.42, 0.55], [0.42, 0.46], [0.455, 0.50], [0.5, 0.44], [0.545, 0.50], [0.58, 0.46], [0.58, 0.55]], '#f8c300');
      p.stars(0.5, 0.66, 0.30, 7, 0.032, '#f8c300', -0.75, 0.75);
    }),
  ],
  TKM: [
    fill('#28ae66'),
    rect(0.10, 0, 0.11, 1, '#b5121b'),
    draw((p) => {
      for (let i = 0; i < 5; i++) {
        p.poly([[0.155, 0.10 + i * 0.19], [0.205, 0.16 + i * 0.19], [0.155, 0.22 + i * 0.19], [0.105, 0.16 + i * 0.19]], WHITE);
      }
    }),
    crescent(0.42, 0.30, 0.16, 0.13, 0.045, WHITE),
    stars(0.57, 0.30, 0.14, 5, 0.045, WHITE),
  ],
  TLS: [
    fill('#dc241f'),
    poly([[0, 0], [0.78, 0.5], [0, 1]], '#ffc726'),
    poly([[0, 0], [0.5, 0.5], [0, 1]], BLACK),
    star(0.16, 0.5, 0.13, WHITE, 5, 0.6),
  ],
  TUR: [
    fill('#e30a17'),
    crescent(0.40, 0.5, 0.28, 0.225, 0.055, WHITE),
    star(0.585, 0.5, 0.115, WHITE, 5, 0.35),
  ],
  TWN: [
    fill('#fe0000'),
    rect(0, 0, 0.5, 0.5, '#000095'),
    sun(0.25, 0.25, 0.075, 12, 0.06, WHITE, 0.55),
    disc(0.25, 0.25, 0.055, '#000095'),
    disc(0.25, 0.25, 0.045, WHITE),
  ],
  UZB: [
    hw(['#0099b5', '#ce1126', WHITE, '#ce1126', '#1eb53a'], [10, 1, 10, 1, 10]),
    crescent(0.20, 0.24, 0.14, 0.115, 0.04, WHITE),
    // Twelve stars in rows of three, four and five.
    draw((p) => {
      for (let row = 0; row < 3; row++) {
        for (let i = 0; i < 3 + row; i++) p.star(0.30 + i * 0.055, 0.13 + row * 0.11, 0.035, WHITE);
      }
    }),
  ],
  VNM: [fill('#da251d'), star(0.5, 0.5, 0.30, '#ffff00')],
  YEM: [h('#ce1126', WHITE, BLACK)],

  CYN: [
    fill(WHITE),
    rect(0, 0.10, 1, 0.10, '#e30a17'),
    rect(0, 0.80, 1, 0.10, '#e30a17'),
    crescent(0.42, 0.5, 0.19, 0.155, 0.04, '#e30a17'),
    star(0.60, 0.5, 0.09, '#e30a17', 5, 0.35),
  ],
};

// --- Africa ----------------------------------------------------------------

const AFRICA: Record<string, FlagSpec> = {
  AGO: [
    h('#ce1126', BLACK),
    draw((p) => {
      p.ring(0.42, 0.5, 0.16, 0.05, '#f9d616');
      p.band(0.36, 0.66, 0.66, 0.36, 0.035, '#f9d616');
      p.star(0.5, 0.32, 0.075, '#f9d616');
    }),
  ],
  BDI: [
    fill(WHITE),
    poly([[0.07, 0], [0.93, 0], [0.5, 0.42]], '#ce1126'),
    poly([[0.07, 1], [0.93, 1], [0.5, 0.58]], '#ce1126'),
    poly([[0, 0.07], [0.42, 0.5], [0, 0.93]], '#1eb53a'),
    poly([[1, 0.07], [0.58, 0.5], [1, 0.93]], '#1eb53a'),
    disc(0.5, 0.5, 0.26, WHITE),
    star(0.5, 0.35, 0.07, '#ce1126'),
    star(0.42, 0.60, 0.07, '#ce1126'),
    star(0.58, 0.60, 0.07, '#ce1126'),
  ],
  BEN: [h('#fcd116', '#e8112d'), rect(0, 0, 1 / 3, 1, '#008751')],
  BFA: [h('#ef2b2d', '#009e49'), star(0.5, 0.5, 0.16, '#fcd116')],
  BWA: [hw(['#75aadb', WHITE, BLACK, WHITE, '#75aadb'], [9, 1, 4, 1, 9])],
  CAF: [
    h('#003082', WHITE, '#289728', '#ffce00'),
    rect(0.44, 0, 0.12, 1, '#d21034'),
    star(0.10, 0.13, 0.09, '#ffce00'),
  ],
  CIV: [v('#f77f00', WHITE, '#009e60')],
  CMR: [v('#007a5e', '#ce1126', '#fcd116'), star(0.5, 0.5, 0.14, '#fcd116')],
  COD: [
    fill('#007fff'),
    { t: 'diag', c: '#f7d618', w: 0.30, up: true },
    { t: 'diag', c: '#ce1021', w: 0.18, up: true },
    star(0.11, 0.20, 0.13, '#f7d618'),
  ],
  COG: [
    fill('#fbde4a'),
    poly([[0, 0], [0.55, 0], [0, 1]], '#009543'),
    poly([[1, 0], [1, 1], [0.45, 1]], '#dc241f'),
  ],
  COM: [
    h('#ffc61e', WHITE, '#ce1126', '#3a75c4'),
    hoist(0.5, '#3d8e33'),
    crescent(0.20, 0.5, 0.20, 0.16, 0.055, WHITE),
    draw((p) => {
      for (let i = 0; i < 4; i++) p.star(0.26, 0.26 + i * 0.16, 0.045, WHITE);
    }),
  ],
  CPV: [
    hw(['#003893', WHITE, '#cf2027', WHITE, '#003893'], [6, 1, 1, 1, 3]),
    stars(0.375, 0.625, 0.30, 10, 0.045, '#f7d116'),
  ],
  DJI: [h('#6ab2e7', '#12ad2b'), hoist(0.42, WHITE), star(0.16, 0.5, 0.11, '#d7141a')],
  DZA: [
    v('#006233', WHITE),
    crescent(0.50, 0.5, 0.24, 0.19, 0.06, '#d21034'),
    star(0.62, 0.5, 0.11, '#d21034', 5, 0.35),
  ],
  EGY: [
    h('#ce1126', WHITE, BLACK),
    draw((p) => {
      // The eagle of Saladin, as a shielded bird.
      p.poly([[0.5, 0.36], [0.60, 0.40], [0.66, 0.48], [0.58, 0.47], [0.56, 0.56], [0.44, 0.56], [0.42, 0.47], [0.34, 0.48], [0.40, 0.40]], '#c09300');
      p.poly([[0.46, 0.56], [0.54, 0.56], [0.52, 0.66], [0.48, 0.66]], '#c09300');
      p.disc(0.5, 0.335, 0.035, '#c09300');
    }),
  ],
  ERI: [
    poly([[0, 0], [1, 0], [1, 0.5]], '#4189dd'),
    poly([[0, 1], [1, 1], [1, 0.5]], '#12ad2e'),
    poly([[0, 0], [1, 0.5], [0, 1]], '#ea0437'),
    // The olive branch inside its wreath.
    draw((p) => {
      const { ctx } = p;
      ctx.strokeStyle = '#ffc726';
      ctx.lineWidth = p.s(0.03);
      ctx.beginPath();
      ctx.arc(p.fx(0.20), p.fy(0.5), p.s(0.26), 0.5, TAU - 0.5);
      ctx.stroke();
      p.rect(0.196, 0.34, 0.010, 0.32, '#ffc726');
      for (let i = 0; i < 4; i++) {
        for (const side of [-1, 1]) {
          ctx.save();
          ctx.beginPath();
          ctx.ellipse(p.fx(0.20 + side * 0.035), p.fy(0.40 + i * 0.07), p.s(0.055), p.s(0.02), side * 0.7, 0, TAU);
          ctx.fillStyle = '#ffc726';
          ctx.fill();
          ctx.restore();
        }
      }
    }),
  ],
  ESH: [
    h(BLACK, WHITE, '#007a3b'),
    hoist(0.5, '#c4111b'),
    crescent(0.68, 0.5, 0.115, 0.09, -0.03, '#c4111b'),
    star(0.60, 0.5, 0.075, '#c4111b'),
  ],
  ETH: [
    h('#078930', '#fcdd09', '#da121a'),
    disc(0.5, 0.5, 0.30, '#0f47af'),
    star(0.5, 0.5, 0.22, '#fcdd09'),
    disc(0.5, 0.5, 0.06, '#0f47af'),
  ],
  GAB: [h('#009e60', '#fcd116', '#3a75c4')],
  GHA: [h('#ce1126', '#fcd116', '#006b3f'), star(0.5, 0.5, 0.13, BLACK)],
  GIN: [v('#ce1126', '#fcd116', '#009460')],
  GMB: [hw(['#ce1126', WHITE, '#0c1c8c', WHITE, '#3a7728'], [6, 1, 4, 1, 6])],
  GNB: [h('#fcd116', '#009e49'), rect(0, 0, 1 / 3, 1, '#ce1126'), star(1 / 6, 0.5, 0.14, BLACK)],
  GNQ: [
    h('#3e9a00', WHITE, '#e32118'),
    hoist(0.30, '#0073ce'),
    draw((p) => shield(p, 0.62, 0.5, 0.15, WHITE, '#7a5c2e')),
  ],
  KEN: [
    hw([BLACK, WHITE, '#bb0000', WHITE, '#006600'], [6, 1, 6, 1, 6]),
    draw((p) => {
      p.band(0.44, 0.14, 0.56, 0.86, 0.022, WHITE);
      p.band(0.56, 0.14, 0.44, 0.86, 0.022, WHITE);
      const { ctx } = p;
      ctx.save();
      ctx.beginPath();
      ctx.ellipse(p.fx(0.5), p.fy(0.5), p.s(0.13), p.s(0.34), 0, 0, TAU);
      ctx.fillStyle = '#bb0000';
      ctx.fill();
      ctx.clip();
      p.rect(0.42, 0.22, 0.16, 0.10, WHITE);
      p.rect(0.42, 0.68, 0.16, 0.10, WHITE);
      p.rect(0.42, 0.44, 0.16, 0.12, BLACK);
      ctx.restore();
    }),
  ],
  LBR: [
    hw(Array.from({ length: 11 }, (_, i) => (i % 2 === 0 ? '#bf0a30' : WHITE)), Array.from({ length: 11 }, () => 1)),
    rect(0, 0, 0.4, 6 / 11, '#002868'),
    star(0.2, 3 / 11, 0.16, WHITE),
  ],
  LBY: [
    hw(['#e70013', BLACK, '#239e46'], [1, 2, 1]),
    crescent(0.47, 0.5, 0.15, 0.12, 0.04, WHITE),
    star(0.575, 0.5, 0.075, WHITE, 5, 0.35),
  ],
  LSO: [
    hw(['#00209f', WHITE, '#009543'], [3, 4, 3]),
    draw((p) => {
      // The mokorotlo, the conical Basotho hat.
      p.poly([[0.5, 0.30], [0.58, 0.60], [0.42, 0.60]], BLACK);
      p.rect(0.39, 0.60, 0.22, 0.03, BLACK);
    }),
  ],
  MAR: [
    fill('#c1272d'),
    draw((p) => {
      p.starPath(0.5, 0.5, 0.30, 5, 0);
      p.ctx.lineWidth = p.s(0.035);
      p.ctx.strokeStyle = '#006233';
      p.ctx.stroke();
    }),
  ],
  MDG: [h('#fc3d32', '#007e3a'), rect(0, 0, 1 / 3, 1, WHITE)],
  MLI: [v('#14b53a', '#fcd116', '#ce1126')],
  MOZ: [
    hw(['#009a49', WHITE, BLACK, WHITE, '#fcd116'], [6, 1, 6, 1, 6]),
    hoist(0.42, '#e21c21'),
    star(0.14, 0.5, 0.13, WHITE),
    draw((p) => {
      p.rect(0.10, 0.46, 0.10, 0.02, BLACK);
      p.band(0.09, 0.58, 0.20, 0.42, 0.02, BLACK);
    }),
  ],
  MRT: [
    fill('#006233'),
    rect(0, 0, 1, 0.12, '#cd2a3e'),
    rect(0, 0.88, 1, 0.12, '#cd2a3e'),
    crescent(0.5, 0.46, 0.24, 0.20, 0.0, '#ffc400'),
    star(0.5, 0.42, 0.09, '#ffc400'),
  ],
  MUS: [h('#ea2839', '#1a206d', '#ffd500', '#00a551')],
  MWI: [
    h(BLACK, '#ce1126', '#339e35'),
    draw((p) => {
      const { ctx } = p;
      ctx.beginPath();
      ctx.arc(p.fx(0.5), p.fy(1 / 3), p.s(0.10), Math.PI, TAU);
      ctx.fillStyle = '#ce1126';
      ctx.fill();
      ctx.strokeStyle = '#ce1126';
      ctx.lineWidth = p.s(0.018);
      for (let i = 1; i < 12; i++) {
        const a = Math.PI + (i / 12) * Math.PI;
        ctx.beginPath();
        ctx.moveTo(p.fx(0.5) + Math.cos(a) * p.s(0.12), p.fy(1 / 3) + Math.sin(a) * p.s(0.12));
        ctx.lineTo(p.fx(0.5) + Math.cos(a) * p.s(0.20), p.fy(1 / 3) + Math.sin(a) * p.s(0.20));
        ctx.stroke();
      }
    }),
  ],
  NAM: [
    poly([[0, 0], [1, 0], [0, 1]], '#003580'),
    poly([[1, 0], [1, 1], [0, 1]], '#009543'),
    { t: 'diag', c: WHITE, w: 0.36, up: true },
    { t: 'diag', c: '#d21034', w: 0.24, up: true },
    sun(0.22, 0.26, 0.055, 12, 0.055, '#ffce00', 0.4),
  ],
  NER: [h('#e05206', WHITE, '#0db02b'), disc(0.5, 0.5, 0.15, '#e05206')],
  NGA: [v('#008751', WHITE, '#008751')],
  RWA: [hw(['#00a1de', '#fad201', '#20603d'], [2, 1, 1]), sun(0.78, 0.25, 0.055, 24, 0.045, '#e5be01', 0.35)],
  SDN: [h('#d21034', WHITE, BLACK), hoist(0.36, '#007229')],
  SEN: [v('#00853f', '#fdef42', '#e31b23'), star(0.5, 0.5, 0.16, '#00853f')],
  SLE: [h('#1eb53a', WHITE, '#0072c6')],
  SOM: [fill('#4189dd'), star(0.5, 0.5, 0.30, WHITE)],
  SSD: [
    hw([BLACK, WHITE, '#da121a', WHITE, '#0f47af'], [6, 1, 6, 1, 6]),
    hoist(0.44, '#078930'),
    star(0.14, 0.5, 0.11, '#fcdd09'),
  ],
  STP: [
    hw(['#12ad2b', '#ffce00', '#12ad2b'], [1, 2, 1]),
    hoist(0.30, '#d21034'),
    star(0.55, 0.5, 0.11, BLACK),
    star(0.75, 0.5, 0.11, BLACK),
  ],
  SWZ: [
    hw(['#3e5eb9', '#ffd900', '#b10c0c', '#ffd900', '#3e5eb9'], [3, 1, 8, 1, 3]),
    draw((p) => {
      p.band(0.30, 0.42, 0.70, 0.42, 0.03, BLACK);
      p.band(0.30, 0.58, 0.70, 0.58, 0.03, BLACK);
      const { ctx } = p;
      ctx.save();
      ctx.beginPath();
      ctx.ellipse(p.fx(0.5), p.fy(0.5), p.s(0.20), p.s(0.13), 0, 0, TAU);
      ctx.fillStyle = WHITE;
      ctx.fill();
      ctx.clip();
      p.rect(0.30, 0.44, 0.40, 0.06, BLACK);
      ctx.restore();
    }),
  ],
  SYC: [
    poly([[0, 1], [0, 0], [0.34, 0]], '#003f87'),
    poly([[0, 1], [0.34, 0], [0.67, 0]], '#fcd856'),
    poly([[0, 1], [0.67, 0], [1, 0], [1, 0.34]], '#d62828'),
    poly([[0, 1], [1, 0.34], [1, 0.67]], WHITE),
    poly([[0, 1], [1, 0.67], [1, 1]], '#007a3d'),
  ],
  TCD: [v('#002664', '#fecb00', '#c60c30')],
  TGO: [
    hw(Array.from({ length: 5 }, (_, i) => (i % 2 === 0 ? '#006a4e' : '#ffce00')), Array.from({ length: 5 }, () => 1)),
    rect(0, 0, 0.4, 0.6, '#d21034'),
    star(0.2, 0.3, 0.18, WHITE),
  ],
  TUN: [
    fill('#e70013'),
    disc(0.5, 0.5, 0.32, WHITE),
    crescent(0.5, 0.5, 0.22, 0.175, 0.06, '#e70013'),
    star(0.60, 0.5, 0.10, '#e70013', 5, 0.35),
  ],
  TZA: [
    poly([[0, 0], [1, 0], [0, 1]], '#1eb53a'),
    poly([[1, 0], [1, 1], [0, 1]], '#00a3dd'),
    { t: 'diag', c: '#fcd116', w: 0.34, up: true },
    { t: 'diag', c: BLACK, w: 0.22, up: true },
  ],
  UGA: [
    hw([BLACK, '#fcdc04', '#d90000', BLACK, '#fcdc04', '#d90000'], [1, 1, 1, 1, 1, 1]),
    disc(0.5, 0.5, 0.26, WHITE),
    draw((p) => {
      // The crested crane, standing.
      p.poly([[0.46, 0.66], [0.47, 0.48], [0.55, 0.44], [0.58, 0.50], [0.52, 0.56], [0.51, 0.66]], '#8d8c8d');
      p.rect(0.49, 0.62, 0.012, 0.10, '#8d8c8d');
      p.disc(0.565, 0.42, 0.035, '#d90000');
      p.poly([[0.58, 0.40], [0.64, 0.41], [0.58, 0.44]], BLACK);
    }),
  ],
  ZAF: [
    hw(['#de3831', '#002395'], [1, 1]),
    draw((p) => {
      p.band(0, 0, 0.42, 0.5, 0.40, WHITE);
      p.band(0, 1, 0.42, 0.5, 0.40, WHITE);
      p.band(0.40, 0.5, 1, 0.5, 0.40, WHITE);
      p.band(0, 0, 0.42, 0.5, 0.26, '#007a4d');
      p.band(0, 1, 0.42, 0.5, 0.26, '#007a4d');
      p.band(0.40, 0.5, 1, 0.5, 0.26, '#007a4d');
      p.poly([[0, 0.02], [0.38, 0.5], [0, 0.98]], '#ffb612');
      p.poly([[0, 0.13], [0.28, 0.5], [0, 0.87]], BLACK);
    }),
  ],
  ZMB: [
    fill('#198a00'),
    rect(0.62, 0.36, 0.125, 0.64, '#de2010'),
    rect(0.745, 0.36, 0.125, 0.64, BLACK),
    rect(0.87, 0.36, 0.125, 0.64, '#ef7d00'),
    draw((p) => {
      p.poly([[0.66, 0.28], [0.78, 0.16], [0.88, 0.10], [0.84, 0.22], [0.94, 0.20], [0.82, 0.30], [0.72, 0.30]], '#ef7d00');
    }),
  ],
  ZWE: [
    hw(['#319208', '#ffd200', '#de2010', BLACK, '#de2010', '#ffd200', '#319208'], [1, 1, 1, 1, 1, 1, 1]),
    poly([[0, 0], [0.40, 0.5], [0, 1]], BLACK),
    poly([[0, 0.045], [0.355, 0.5], [0, 0.955]], WHITE),
    star(0.115, 0.5, 0.20, '#de2010'),
    draw((p) => {
      p.poly([[0.10, 0.50], [0.15, 0.42], [0.17, 0.46], [0.14, 0.54], [0.155, 0.60], [0.10, 0.58]], '#ffd200');
    }),
  ],

  SOL: [
    h('#3d9e33', WHITE, '#ce1126'),
    star(0.5, 0.83, 0.11, BLACK),
    draw((p) => {
      const { ctx } = p;
      ctx.strokeStyle = BLACK;
      ctx.lineWidth = p.s(0.028);
      ctx.lineCap = 'round';
      ctx.beginPath();
      ctx.moveTo(p.fx(0.20), p.fy(0.42));
      ctx.lineTo(p.fx(0.80), p.fy(0.42));
      ctx.stroke();
      ctx.lineWidth = p.s(0.02);
      for (let i = 0; i < 6; i++) {
        const x = 0.24 + i * 0.095;
        ctx.beginPath();
        ctx.moveTo(p.fx(x), p.fy(0.40));
        ctx.quadraticCurveTo(p.fx(x + 0.03), p.fy(0.28), p.fx(x + 0.06), p.fy(0.39));
        ctx.stroke();
      }
    }),
  ],
};

// --- The Americas ----------------------------------------------------------

const AMERICAS: Record<string, FlagSpec> = {
  ABW: [
    fill('#418fde'),
    rect(0, 0.62, 1, 0.08, '#f9e814'),
    rect(0, 0.76, 1, 0.08, '#f9e814'),
    draw((p) => {
      // A four-pointed star, white-edged.
      p.starPath(0.18, 0.30, 0.20, 4, 0);
      p.ctx.fillStyle = '#ef3340';
      p.ctx.fill();
      p.ctx.lineWidth = p.s(0.035);
      p.ctx.strokeStyle = WHITE;
      p.ctx.stroke();
    }),
  ],
  AIA: [...ensign(UK_BLUE, ...badge('#f47b20'))],
  ATG: [
    fill('#ce1126'),
    draw((p) => {
      const { ctx } = p;
      ctx.save();
      p.polyPath([[0.13, 0], [0.87, 0], [0.5, 1]]);
      ctx.clip();
      p.rect(0, 0, 1, 0.42, BLACK);
      p.rect(0, 0.42, 1, 0.16, '#0072c6');
      p.rect(0, 0.58, 1, 0.42, WHITE);
      p.sun(0.5, 0.42, 0.09, 16, 0.11, '#ffcc00', 0.4);
      p.rect(0, 0.42, 1, 0.005, '#0072c6');
      ctx.restore();
    }),
  ],
  BHS: [hw(['#00abc9', '#ffc72c', '#00abc9'], [1, 1, 1]), hoist(0.42, BLACK)],
  BLZ: [
    fill('#003f87'),
    rect(0, 0, 1, 0.10, '#ce1126'),
    rect(0, 0.90, 1, 0.10, '#ce1126'),
    disc(0.5, 0.5, 0.36, WHITE),
    ring(0.5, 0.5, 0.30, 0.07, '#2e8b57'),
    draw((p) => shield(p, 0.5, 0.5, 0.18, WHITE, '#003f87')),
  ],
  BMU: [...ensign('#cf142b', ...badge('#007a3d'))],
  BRB: [
    v('#00267f', '#ffc726', '#00267f'),
    draw((p) => {
      p.rect(0.492, 0.42, 0.016, 0.34, BLACK);
      p.rect(0.44, 0.40, 0.12, 0.03, BLACK);
      for (const dx of [-0.052, 0, 0.052]) {
        p.poly([[0.5 + dx - 0.014, 0.40], [0.5 + dx + 0.014, 0.40], [0.5 + dx, 0.24]], BLACK);
      }
    }),
  ],
  CAN: [
    vw(['#d80621', WHITE, '#d80621'], [1, 2, 1]),
    // Eleven points, mirrored about the stem. Half-widths are relative so the
    // leaf cannot grow out of the white band whatever the box's aspect.
    draw((p) => {
      const half: number[][] = [
        [0.00, 0.00], [0.11, 0.19], [0.38, 0.15], [0.31, 0.31], [0.70, 0.44],
        [0.61, 0.50], [1.00, 0.63], [0.82, 0.68], [0.86, 0.76], [0.45, 0.71],
        [0.52, 0.92], [0.20, 0.84], [0.09, 1.00],
      ];
      const at = (q: number[], side: number): number[] => [0.5 + side * q[0]! * 0.20, 0.10 + q[1]! * 0.80];
      const points = half.map((q) => at(q, 1));
      for (let i = half.length - 1; i >= 0; i--) points.push(at(half[i]!, -1));
      p.poly(points, '#d80621');
    }),
  ],
  CRI: [hw(['#002b7f', WHITE, '#ce1126', WHITE, '#002b7f'], [1, 1, 2, 1, 1])],
  CUB: [
    hw(Array.from({ length: 5 }, (_, i) => (i % 2 === 0 ? '#002a8f' : WHITE)), Array.from({ length: 5 }, () => 1)),
    hoist(0.4, '#cf142b'),
    star(0.13, 0.5, 0.13, WHITE),
  ],
  CUW: [
    fill('#002b7f'),
    rect(0, 0.60, 1, 0.14, '#f9e814'),
    star(0.14, 0.22, 0.11, WHITE),
    star(0.27, 0.42, 0.075, WHITE),
  ],
  CYM: [...ensign(UK_BLUE, ...badge('#00778b'))],
  DMA: [
    fill('#006b3f'),
    draw((p) => {
      // Three stripes side by side make one cross, so the arms are drawn as
      // parallel bars rather than as concentric crosses.
      const bands = ['#fcd116', BLACK, WHITE];
      const { ctx } = p;
      const bar = p.s(0.055);
      bands.forEach((c, i) => {
        ctx.fillStyle = c;
        ctx.fillRect(p.x, p.fy(0.5) - bar * 1.5 + i * bar, p.w, bar);
        ctx.fillRect(p.fx(0.5) - bar * 1.5 + i * bar, p.y, bar, p.h);
      });
      p.disc(0.5, 0.5, 0.22, '#d41c30');
      p.stars(0.5, 0.5, 0.19, 10, 0.032, '#006b3f');
      p.poly([[0.48, 0.56], [0.49, 0.46], [0.53, 0.44], [0.54, 0.50], [0.51, 0.56]], '#6f2da8');
    }),
  ],
  DOM: [
    fill('#002d62'),
    rect(0.5, 0, 0.5, 0.5, '#ce1126'),
    rect(0, 0.5, 0.5, 0.5, '#ce1126'),
    cross(WHITE, 0.22),
    draw((p) => shield(p, 0.5, 0.5, 0.15, WHITE, '#002d62')),
  ],
  ECU: [
    hw(['#ffdd00', '#034ea2', '#ed1c24'], [2, 1, 1]),
    draw((p) => {
      p.poly([[0.5, 0.30], [0.60, 0.44], [0.5, 0.58], [0.40, 0.44]], '#034ea2');
      p.poly([[0.44, 0.28], [0.56, 0.28], [0.5, 0.16]], '#c8a951');
      p.rect(0.494, 0.56, 0.012, 0.14, '#c8a951');
    }),
  ],
  GRD: [
    fill('#ce1126'),
    draw((p) => {
      const m = 0.16;
      p.poly([[m * (p.h / p.w), m], [1 - m * (p.h / p.w), m], [0.5, 0.5]], '#fcd116');
      p.poly([[m * (p.h / p.w), 1 - m], [1 - m * (p.h / p.w), 1 - m], [0.5, 0.5]], '#fcd116');
      p.poly([[m * (p.h / p.w), m], [0.5, 0.5], [m * (p.h / p.w), 1 - m]], '#007a5e');
      p.poly([[1 - m * (p.h / p.w), m], [0.5, 0.5], [1 - m * (p.h / p.w), 1 - m]], '#007a5e');
      for (let i = 0; i < 3; i++) {
        p.star(0.28 + i * 0.22, 0.08, 0.06, '#fcd116');
        p.star(0.28 + i * 0.22, 0.92, 0.06, '#fcd116');
      }
      p.disc(0.5, 0.5, 0.15, '#ce1126');
      p.star(0.5, 0.5, 0.12, '#fcd116');
      p.disc(0.235, 0.5, 0.075, '#ce1126');
      p.disc(0.235, 0.5, 0.055, '#fcd116');
    }),
  ],
  GTM: [
    v('#4997d0', WHITE, '#4997d0'),
    draw((p) => {
      p.ring(0.5, 0.55, 0.20, 0.05, '#3e7f3e');
      p.band(0.42, 0.66, 0.58, 0.36, 0.022, '#8d6a3f');
      p.band(0.58, 0.66, 0.42, 0.36, 0.022, '#8d6a3f');
      p.poly([[0.40, 0.44], [0.60, 0.44], [0.5, 0.34]], '#3e7f3e');
    }),
  ],
  GUM: [
    fill('#00307d'),
    draw((p) => {
      p.ctx.strokeStyle = '#c8102e';
      p.ctx.lineWidth = p.s(0.09);
      p.ctx.strokeRect(p.x + p.s(0.045), p.y + p.s(0.045), p.w - p.s(0.09), p.h - p.s(0.09));
      const { ctx } = p;
      ctx.beginPath();
      ctx.ellipse(p.fx(0.5), p.fy(0.5), p.s(0.17), p.s(0.30), 0, 0, TAU);
      ctx.fillStyle = '#9fd6e8';
      ctx.fill();
      ctx.lineWidth = p.s(0.02);
      ctx.strokeStyle = '#c8102e';
      ctx.stroke();
      p.poly([[0.44, 0.62], [0.56, 0.62], [0.5, 0.40]], WHITE);
    }),
  ],
  HND: [
    hw(['#0073cf', WHITE, '#0073cf'], [1, 1, 1]),
    draw((p) => {
      for (const [sx, sy] of [[0.5, 0.5], [0.42, 0.42], [0.58, 0.42], [0.42, 0.58], [0.58, 0.58]]) {
        p.star(sx!, sy!, 0.07, '#0073cf');
      }
    }),
  ],
  HTI: [
    h('#00209f', '#d21034'),
    rect(0.36, 0.30, 0.28, 0.40, WHITE),
    draw((p) => {
      p.rect(0.494, 0.36, 0.012, 0.20, '#0f5132');
      p.poly([[0.47, 0.38], [0.53, 0.38], [0.5, 0.32]], '#0f5132');
      p.rect(0.42, 0.60, 0.16, 0.02, '#8d6a3f');
    }),
  ],
  JAM: [
    poly([[0, 0], [1, 0], [0.5, 0.5]], BLACK),
    poly([[0, 1], [1, 1], [0.5, 0.5]], BLACK),
    poly([[0, 0], [0.5, 0.5], [0, 1]], '#009b3a'),
    poly([[1, 0], [0.5, 0.5], [1, 1]], '#009b3a'),
    { t: 'saltire', c: '#fed100', w: 0.20 },
  ],
  KNA: [
    poly([[0, 0], [1, 0], [0, 1]], '#009e49'),
    poly([[1, 0], [1, 1], [0, 1]], '#ce1126'),
    { t: 'diag', c: '#ffcd00', w: 0.42, up: true },
    { t: 'diag', c: BLACK, w: 0.30, up: true },
    star(0.30, 0.68, 0.10, WHITE),
    star(0.66, 0.30, 0.10, WHITE),
  ],
  LCA: [
    fill('#6cf'),
    poly([[0.5, 0.10], [0.30, 0.86], [0.70, 0.86]], WHITE),
    poly([[0.5, 0.18], [0.335, 0.86], [0.665, 0.86]], BLACK),
    poly([[0.5, 0.48], [0.30, 0.86], [0.70, 0.86]], '#fcd116'),
  ],
  MEX: [
    v('#006847', WHITE, '#ce1126'),
    draw((p) => {
      // The eagle on the cactus, as a bird over a wreath.
      p.poly([[0.48, 0.42], [0.56, 0.38], [0.62, 0.44], [0.55, 0.46], [0.53, 0.58], [0.46, 0.58], [0.44, 0.46], [0.38, 0.44], [0.44, 0.38]], '#6b4423');
      p.disc(0.475, 0.355, 0.03, '#6b4423');
      p.poly([[0.49, 0.335], [0.545, 0.345], [0.49, 0.375]], '#6b4423');
      p.ring(0.5, 0.63, 0.11, 0.035, '#2e6f40');
    }),
  ],
  MSR: [...ensign(UK_BLUE, ...badge('#1e6b52'))],
  NIC: [
    hw(['#0067c6', WHITE, '#0067c6'], [1, 1, 1]),
    draw((p) => {
      p.poly([[0.5, 0.34], [0.62, 0.62], [0.38, 0.62]], WHITE);
      p.ctx.lineWidth = p.s(0.02);
      p.ctx.strokeStyle = '#0067c6';
      p.polyPath([[0.5, 0.34], [0.62, 0.62], [0.38, 0.62]]);
      p.ctx.stroke();
      p.poly([[0.44, 0.58], [0.5, 0.46], [0.56, 0.58]], '#3d3d3d');
      p.band(0.42, 0.46, 0.58, 0.46, 0.02, '#ffcc00');
    }),
  ],
  PAN: [
    fill(WHITE),
    rect(0.5, 0, 0.5, 0.5, '#da121a'),
    rect(0, 0.5, 0.5, 0.5, '#072357'),
    star(0.25, 0.25, 0.16, '#072357'),
    star(0.75, 0.75, 0.16, '#da121a'),
  ],
  PRI: [
    hw(Array.from({ length: 5 }, (_, i) => (i % 2 === 0 ? '#ed0000' : WHITE)), Array.from({ length: 5 }, () => 1)),
    hoist(0.4, '#0050f0'),
    star(0.13, 0.5, 0.13, WHITE),
  ],
  SLV: [
    hw(['#0f47af', WHITE, '#0f47af'], [1, 1, 1]),
    draw((p) => {
      p.poly([[0.5, 0.32], [0.63, 0.62], [0.37, 0.62]], WHITE);
      p.ctx.lineWidth = p.s(0.02);
      p.ctx.strokeStyle = '#0f47af';
      p.polyPath([[0.5, 0.32], [0.63, 0.62], [0.37, 0.62]]);
      p.ctx.stroke();
      p.poly([[0.44, 0.58], [0.5, 0.44], [0.56, 0.58]], '#3d7a3d');
      p.ring(0.5, 0.5, 0.24, 0.03, '#3d7a3d');
    }),
  ],
  SXM: [
    h('#ce1126', '#003da5'),
    hoist(0.44, WHITE),
    draw((p) => shield(p, 0.16, 0.5, 0.19, '#ffcc00', '#003da5')),
  ],
  TCA: [...ensign(UK_BLUE, ...badge('#ffb612'))],
  TTO: [
    fill('#ce1126'),
    { t: 'diag', c: WHITE, w: 0.36 },
    { t: 'diag', c: BLACK, w: 0.22 },
  ],
  USA: [
    draw((p) => {
      p.layers([hw(Array.from({ length: 13 }, (_, i) => (i % 2 === 0 ? '#b31942' : WHITE)), Array.from({ length: 13 }, () => 1))]);
      const canton = 7 / 13;
      p.rect(0, 0, 0.4, canton, '#0a3161');
      // Nine rows: six stars, then five, alternating. Fifty in total.
      for (let row = 0; row < 9; row++) {
        const n = row % 2 === 0 ? 6 : 5;
        const y = ((row + 1) / 10) * canton;
        for (let i = 0; i < n; i++) {
          const x = (((row % 2 === 0 ? i + 1 : i + 1.5) / 7) * 0.4);
          p.star(x, y, 0.024, WHITE);
        }
      }
    }),
  ],
  VCT: [
    vw(['#0072c6', '#fcd116', '#009e60'], [1, 2, 1]),
    draw((p) => {
      for (const [dx, dy] of [[-0.075, 0.42], [0.075, 0.42], [0, 0.62]]) {
        const x = 0.5 + (dx! * p.h) / p.w;
        p.poly([[x, dy! - 0.09], [x + (0.055 * p.h) / p.w, dy!], [x, dy! + 0.09], [x - (0.055 * p.h) / p.w, dy!]], '#009e60');
      }
    }),
  ],
  VGB: [...ensign(UK_BLUE, ...badge('#1e6b52'))],
  VIR: [
    fill(WHITE),
    draw((p) => {
      p.poly([[0.5, 0.28], [0.66, 0.36], [0.74, 0.50], [0.60, 0.48], [0.56, 0.66], [0.44, 0.66], [0.40, 0.48], [0.26, 0.50], [0.34, 0.36]], '#f0b323');
      p.disc(0.5, 0.26, 0.045, WHITE);
      p.ctx.lineWidth = p.s(0.015);
      p.ctx.strokeStyle = '#4c6ea8';
      p.ctx.stroke();
      p.rect(0.455, 0.44, 0.09, 0.16, '#4c6ea8');
    }),
  ],

  // South America.
  ARG: [
    hw(['#75aadb', WHITE, '#75aadb'], [1, 1, 1]),
    draw((p) => sunOfMay(p, 0.5, 0.5, 0.085, '#f6b40e')),
  ],
  BOL: [
    h('#d52b1e', '#f9e300', '#007934'),
    draw((p) => {
      p.disc(0.5, 0.5, 0.17, '#d9c89e');
      p.ring(0.5, 0.5, 0.17, 0.03, '#a05a2c');
      p.poly([[0.44, 0.56], [0.5, 0.44], [0.56, 0.56]], '#5b7c3a');
    }),
  ],
  BRA: [
    fill('#009c3b'),
    poly([[0.5, 0.06], [0.955, 0.5], [0.5, 0.94], [0.045, 0.5]], '#ffdf00'),
    disc(0.5, 0.5, 0.245, '#002776'),
    draw((p) => {
      const { ctx } = p;
      ctx.save();
      ctx.beginPath();
      ctx.arc(p.fx(0.5), p.fy(0.5), p.s(0.245), 0, TAU);
      ctx.clip();
      ctx.beginPath();
      ctx.arc(p.fx(0.5), p.fy(0.5) + p.s(0.60), p.s(0.66), Math.PI * 1.17, Math.PI * 1.83);
      ctx.lineWidth = p.s(0.075);
      ctx.strokeStyle = WHITE;
      ctx.stroke();
      // Stars, above and below the band. Not the real 27 constellations: at
      // this size they are pinpricks, and a plausible scatter is honest about
      // that where a wrong constellation would not be.
      const dots: number[][] = [
        [0.44, 0.40], [0.50, 0.37], [0.56, 0.41], [0.52, 0.44], [0.46, 0.46],
        [0.58, 0.47], [0.41, 0.48], [0.50, 0.62], [0.55, 0.64], [0.45, 0.64],
        [0.60, 0.58], [0.40, 0.58], [0.50, 0.68],
      ];
      for (const [sx, sy] of dots) p.star(sx!, sy!, 0.018, WHITE);
      ctx.restore();
    }),
  ],
  CHL: [
    fill('#d52b1e'),
    rect(0, 0, 1, 0.5, WHITE),
    rect(0, 0, 1 / 3, 0.5, '#0039a6'),
    star(1 / 6, 0.25, 0.16, WHITE),
  ],
  COL: [hw(['#fcd116', '#003893', '#ce1126'], [2, 1, 1])],
  FLK: [...ensign(UK_BLUE, ...badge('#3f6f3f'))],
  GUY: [
    fill('#009e49'),
    poly([[0, 0], [0.62, 0.5], [0, 1]], WHITE),
    poly([[0, 0], [0.54, 0.5], [0, 1]], '#fcd116'),
    poly([[0, 0], [0.36, 0.5], [0, 1]], BLACK),
    poly([[0, 0], [0.30, 0.5], [0, 1]], '#ce1126'),
  ],
  PER: [
    vw(['#d91023', WHITE, '#d91023'], [1, 1, 1]),
    draw((p) => shield(p, 0.5, 0.5, 0.24, WHITE, '#d91023')),
  ],
  PRY: [
    h('#d52b1e', WHITE, '#0038a8'),
    disc(0.5, 0.5, 0.15, WHITE),
    ring(0.5, 0.5, 0.15, 0.02, '#0038a8'),
    star(0.5, 0.5, 0.075, '#009b3a'),
  ],
  SUR: [
    hw(['#377e3f', WHITE, '#b40a2d', WHITE, '#377e3f'], [2, 1, 4, 1, 2]),
    star(0.5, 0.5, 0.20, '#ecc81d'),
  ],
  URY: [
    hw(Array.from({ length: 9 }, (_, i) => (i % 2 === 0 ? WHITE : '#0038a8')), Array.from({ length: 9 }, () => 1)),
    rect(0, 0, 0.44, 4 / 9, WHITE),
    draw((p) => sunOfMay(p, 0.22, 2 / 9, 0.05, '#fcd116')),
  ],
  VEN: [
    hw(['#ffcc00', '#00247d', '#cf142b'], [1, 1, 1]),
    stars(0.5, -0.10, 0.62, 8, 0.05, WHITE, Math.PI - 0.62, Math.PI + 0.62),
  ],
};

// --- Oceania and the open ocean --------------------------------------------

const OCEANIA: Record<string, FlagSpec> = {
  ASM: [
    fill('#0060af'),
    poly([[1, 0], [0.02, 0.5], [1, 1]], '#c8102e'),
    poly([[1, 0.10], [0.15, 0.5], [1, 0.90]], WHITE),
    draw((p) => {
      p.poly([[0.42, 0.42], [0.62, 0.38], [0.78, 0.46], [0.60, 0.50], [0.56, 0.62], [0.44, 0.58]], '#8d6a3f');
      p.disc(0.40, 0.40, 0.035, WHITE);
    }),
  ],
  AUS: [
    fill('#012169'),
    { t: 'flag', k: 'GBR', x: 0, y: 0, w: 0.5, h: 0.5 },
    star(0.25, 0.75, 0.13, WHITE, 7),
    star(0.72, 0.20, 0.065, WHITE, 7),
    star(0.62, 0.47, 0.065, WHITE, 7),
    star(0.72, 0.74, 0.065, WHITE, 7),
    star(0.84, 0.56, 0.065, WHITE, 7),
    star(0.76, 0.44, 0.035, WHITE, 5),
  ],
  COK: [
    fill('#012169'),
    { t: 'flag', k: 'GBR', x: 0, y: 0, w: 0.5, h: 0.5 },
    stars(0.75, 0.5, 0.32, 15, 0.045, WHITE),
  ],
  FJI: [
    fill('#68bfe5'),
    { t: 'flag', k: 'GBR', x: 0, y: 0, w: 0.5, h: 0.5 },
    draw((p) => shield(p, 0.74, 0.5, 0.26, WHITE, '#c8102e')),
  ],
  FSM: [
    fill('#75b2dd'),
    star(0.5, 0.25, 0.10, WHITE),
    star(0.5, 0.75, 0.10, WHITE),
    star(0.395, 0.5, 0.10, WHITE),
    star(0.605, 0.5, 0.10, WHITE),
  ],
  KIR: [
    fill('#002b7f'),
    rect(0, 0, 1, 0.5, '#ce1126'),
    draw((p) => {
      const { ctx } = p;
      ctx.save();
      ctx.beginPath();
      ctx.rect(p.x, p.y, p.w, p.h * 0.5);
      ctx.clip();
      p.sun(0.5, 0.5, 0.12, 17, 0.16, '#fcd116', 0.4);
      ctx.restore();
      // The frigatebird, wings out over the sun.
      p.poly([[0.5, 0.18], [0.30, 0.10], [0.16, 0.16], [0.36, 0.20], [0.5, 0.26], [0.64, 0.20], [0.84, 0.16], [0.70, 0.10]], '#fcd116');
      waves(p, 0.55, 3, 0.40, WHITE, 0.045);
    }),
  ],
  MHL: [
    fill('#003893'),
    poly([[0, 1], [1, 0.28], [1, 0.52], [0, 1]], '#dd7500'),
    poly([[0, 1], [1, 0.05], [1, 0.28], [0, 1]], WHITE),
    star(0.24, 0.28, 0.16, WHITE, 24),
  ],
  MNP: [
    fill('#0033a0'),
    star(0.5, 0.42, 0.14, WHITE),
    draw((p) => {
      p.poly([[0.44, 0.72], [0.44, 0.58], [0.56, 0.58], [0.56, 0.72]], '#9c9c9c');
      p.poly([[0.40, 0.58], [0.60, 0.58], [0.56, 0.50], [0.44, 0.50]], '#9c9c9c');
      p.ring(0.5, 0.56, 0.30, 0.045, '#c8a951');
    }),
  ],
  NCL: [
    h('#0035ad', '#ed1c24', '#009543'),
    disc(0.34, 0.5, 0.30, '#fae600'),
    draw((p) => {
      p.ctx.lineWidth = p.s(0.03);
      p.ctx.strokeStyle = BLACK;
      p.ctx.beginPath();
      p.ctx.arc(p.fx(0.34), p.fy(0.5), p.s(0.30), 0, TAU);
      p.ctx.stroke();
      // The fleche faitiere: a shaft with a crossbar and a finial.
      p.rect(0.334, 0.28, 0.012, 0.44, BLACK);
      p.rect(0.30, 0.42, 0.08, 0.02, BLACK);
      p.disc(0.34, 0.26, 0.045, BLACK);
    }),
  ],
  NFK: [
    vw(['#008000', WHITE, '#008000'], [1, 2, 1]),
    draw((p) => {
      p.rect(0.494, 0.62, 0.012, 0.14, '#006400');
      for (let i = 0; i < 4; i++) {
        const w = 0.11 - i * 0.024;
        p.poly([[0.5 - w, 0.70 - i * 0.13], [0.5 + w, 0.70 - i * 0.13], [0.5, 0.48 - i * 0.13]], '#006400');
      }
    }),
  ],
  NIU: [
    fill('#ffcc00'),
    { t: 'flag', k: 'GBR', x: 0, y: 0, w: 0.5, h: 0.5 },
    disc(0.25, 0.25, 0.09, '#012169'),
    star(0.25, 0.25, 0.075, '#ffcc00'),
  ],
  NZL: [
    fill('#012169'),
    { t: 'flag', k: 'GBR', x: 0, y: 0, w: 0.5, h: 0.5 },
    draw((p) => {
      const cross_: number[][] = [[0.80, 0.24], [0.68, 0.44], [0.86, 0.60], [0.74, 0.80]];
      for (const [sx, sy] of cross_) {
        p.star(sx!, sy!, 0.085, WHITE);
        p.star(sx!, sy!, 0.055, '#c8102e');
      }
    }),
  ],
  PCN: [...ensign(UK_BLUE, ...badge('#1e6b52'))],
  PLW: [fill('#4aadd6'), disc(0.42, 0.5, 0.32, '#ffde00')],
  PNG: [
    fill('#ce1126'),
    poly([[0, 0], [1, 1], [0, 1]], BLACK),
    draw((p) => {
      for (const [sx, sy] of [[0.14, 0.55], [0.30, 0.72], [0.16, 0.88], [0.36, 0.90]]) {
        p.star(sx!, sy!, 0.065, WHITE);
      }
      p.star(0.24, 0.80, 0.035, WHITE);
      // The bird of paradise, tail streaming to the fly.
      p.poly([[0.62, 0.40], [0.72, 0.30], [0.80, 0.34], [0.74, 0.42], [0.90, 0.36], [0.78, 0.50], [0.66, 0.50]], '#fcd116');
      p.poly([[0.60, 0.26], [0.70, 0.28], [0.62, 0.36]], '#fcd116');
    }),
  ],
  PYF: [
    hw(['#ce1126', WHITE, '#ce1126'], [1, 2, 1]),
    disc(0.5, 0.5, 0.22, WHITE),
    // A double canoe under a rayed sun, on the sea.
    draw((p) => {
      const { ctx } = p;
      ctx.save();
      ctx.beginPath();
      ctx.arc(p.fx(0.5), p.fy(0.5), p.s(0.22), 0, TAU);
      ctx.clip();
      ctx.strokeStyle = '#f5a623';
      ctx.lineWidth = p.s(0.016);
      for (let i = 0; i < 9; i++) {
        const a = -Math.PI / 2 + ((i - 4) / 9) * Math.PI * 0.9;
        ctx.beginPath();
        ctx.moveTo(p.fx(0.5), p.fy(0.52));
        ctx.lineTo(p.fx(0.5) + Math.cos(a) * p.s(0.20), p.fy(0.52) + Math.sin(a) * p.s(0.20));
        ctx.stroke();
      }
      for (let i = 0; i < 5; i++) p.rect(0.44 + i * 0.03, 0.42, 0.012, 0.10, '#ce1126');
      p.poly([[0.36, 0.52], [0.64, 0.52], [0.60, 0.60], [0.40, 0.60]], '#ce1126');
      p.rect(0.30, 0.64, 0.40, 0.025, '#0038a8');
      p.rect(0.32, 0.70, 0.36, 0.025, '#0038a8');
      ctx.restore();
      p.ring(0.5, 0.5, 0.22, 0.025, '#ce1126');
    }),
  ],
  SLB: [
    poly([[0, 0], [1, 0], [0, 1]], '#0051ba'),
    poly([[1, 0], [1, 1], [0, 1]], '#215b33'),
    { t: 'diag', c: '#fcd116', w: 0.12, up: true },
    draw((p) => {
      for (const [sx, sy] of [[0.10, 0.12], [0.26, 0.12], [0.10, 0.34], [0.26, 0.34], [0.18, 0.23]]) {
        p.star(sx!, sy!, 0.055, WHITE);
      }
    }),
  ],
  TON: [
    fill('#c10000'),
    rect(0, 0, 0.42, 0.5, WHITE),
    cross('#c10000', 0.08, 0.21, 0.25, 0.30),
  ],
  VUT: [
    h('#d21034', '#009543'),
    draw((p) => {
      p.rect(0, 0.42, 1, 0.16, BLACK);
      p.poly([[0, 0], [0.46, 0.5], [0, 1]], BLACK);
      p.band(0, 0.06, 0.42, 0.5, 0.05, '#fdce12');
      p.band(0, 0.94, 0.42, 0.5, 0.05, '#fdce12');
      p.band(0.40, 0.5, 1, 0.5, 0.05, '#fdce12');
      p.crescent(0.20, 0.5, 0.16, 0.125, 0.045, '#fdce12');
    }),
  ],
  WSM: [
    fill('#ce1126'),
    rect(0, 0, 0.5, 0.5, '#002b7f'),
    draw((p) => {
      for (const [sx, sy] of [[0.16, 0.10], [0.30, 0.20], [0.16, 0.36], [0.36, 0.34]]) {
        p.star(sx!, sy!, 0.055, WHITE);
      }
      p.star(0.24, 0.25, 0.032, WHITE);
    }),
  ],

  // The open-ocean features. `IOT` is the British Indian Ocean Territory,
  // which the outlines do not draw — every Chagos ring is under the bake's
  // floor — and is kept for the day they do, like `SXM`.
  ATF: [
    fill('#003da5'),
    draw((p) => {
      p.rect(0.02, 0.04, 0.10, 0.42, '#002395');
      p.rect(0.12, 0.04, 0.10, 0.42, WHITE);
      p.rect(0.22, 0.04, 0.10, 0.42, '#ed2939');
      for (const [sx, sy] of [[0.62, 0.24], [0.74, 0.36], [0.86, 0.24], [0.68, 0.60], [0.80, 0.60]]) {
        p.star(sx!, sy!, 0.075, '#f5d130');
      }
    }),
  ],
  IOT: [
    draw((p) => {
      p.fill(WHITE);
      for (let i = 0; i < 3; i++) p.rect(0, 0.16 + i * 0.28, 1, 0.14, '#0072ce');
      waves(p, 0, 6, 1, '#0072ce', 0.02);
      p.flag('GBR', 0, 0, 0.5, 0.5);
      p.rect(0.76, 0.44, 0.02, 0.28, '#5a3a1a');
      for (let i = 0; i < 4; i++) {
        const a = (i / 4) * Math.PI - Math.PI * 0.1;
        p.band(0.77, 0.46, 0.77 + Math.cos(a) * 0.16, 0.46 - Math.abs(Math.sin(a)) * 0.22, 0.03, '#1e6b52');
      }
      p.disc(0.77, 0.24, 0.075, '#ffcc00');
    }),
  ],
  SGS: [...ensign(UK_BLUE, ...badge('#1e6b52'))],
  SHN: [...ensign(UK_BLUE, ...badge('#0072ce'))],
};

const ANTARCTIC: Record<string, FlagSpec> = {
  // No official flag exists. This is Graham Bartram's design, the one that
  // actually gets flown at the stations: the continent, white on UN blue.
  ATA: [
    fill('#3a7ac8'),
    // The continent in polar projection, peninsula reaching for South America.
    poly([
      [0.50, 0.22], [0.58, 0.24], [0.65, 0.29], [0.69, 0.37], [0.70, 0.47],
      [0.67, 0.57], [0.61, 0.67], [0.54, 0.73], [0.46, 0.75], [0.40, 0.72],
      [0.36, 0.66], [0.33, 0.68], [0.30, 0.64], [0.33, 0.57], [0.34, 0.48],
      [0.29, 0.40], [0.23, 0.30], [0.26, 0.27], [0.34, 0.36], [0.38, 0.43],
      [0.41, 0.32], [0.45, 0.25],
    ], WHITE),
  ],
};

export const FLAGS: Record<string, FlagSpec> = {
  ...EUROPE,
  ...ASIA,
  ...AFRICA,
  ...AMERICAS,
  ...OCEANIA,
  ...ANTARCTIC,
};

/**
 * Territories that officially fly someone else's flag. Drawing a local
 * unofficial flag instead would be a nicer picture and a worse fact.
 */
export const FLAG_ALIAS: Record<string, string> = {
  MAF: 'FRA', // Saint-Martin: the collectivity flies the French tricolour.
  SPM: 'FRA', // Saint Pierre and Miquelon: likewise.
  WLF: 'FRA', // Wallis and Futuna: likewise.
  HMD: 'AUS', // Heard and McDonald: an external territory of Australia.
  // Christmas Island and the Cocos, which Natural Earth draws as one feature,
  // the Indian Ocean Territories. Two external territories of Australia; the
  // islands' own flags are unofficial. Not the British Indian Ocean Territory,
  // which is `IOT` below and is too small for the outlines to draw.
  IOA: 'AUS',
  WSB: 'GBR', // Akrotiri: a Sovereign Base Area, which flies the Union flag.
  ESB: 'GBR', // Dhekelia: likewise.
  USG: 'USA', // Guantanamo Bay: a US naval base on land leased from Cuba.
  KAB: 'KAZ', // Baikonur: Kazakh ground under a Russian lease.
};

/**
 * Admin-0 features that are nobody's to fly a flag over, drawn as the plate on
 * purpose. 1:10m draws them as their own polygons, so the chip names them and
 * has to show something: an alias would be a claim this project is in no
 * position to make, and a spec would be a flag that does not exist.
 *
 * - `CNM`, the UN buffer zone across Cyprus: patrolled by the UN, and neither
 *   side's.
 * - `BRT`, Bir Tawil: the one piece of land on Earth claimed by nobody.
 * - `KAS`, the Siachen Glacier: held by India, claimed by Pakistan.
 * - `SPI`, the Southern Patagonian Ice Field: the stretch of the Andes where
 *   Chile and Argentina have never agreed a line.
 *
 * `pnpm check` asserts every country has a spec, an alias or a place here.
 */
export const NO_FLAG = new Set(['CNM', 'BRT', 'KAS', 'SPI']);

/**
 * Flags whose emblem is a mark rather than the real thing. The field and the
 * layout are right; the device is not.
 *
 * The line, so the coverage number stays honest and the next person applies it
 * the same way: a **pictorial** device — a person, an animal, a plant, a coat
 * of arms, a script, a face, a national outline cut by hand — that has been
 * reduced or dropped puts the flag in here. Geometric devices are drawn exactly
 * and stay out: stripes, crosses, saltires, discs, crescents, stars, India's
 * chakra, Korea's taegeuk and trigrams, North Macedonia's rays.
 *
 * Argentina and Uruguay are what the rule caught late. Their sun has 32 rays
 * *and a human face*, and a sun without the face is precisely what the tag is
 * for.
 */
export const SIMPLIFIED = new Set([
  'ALB', 'AND', 'BLR', 'CYP', 'ESP', 'HRV', 'IMN', 'JEY', 'KOS', 'LIE', 'MDA',
  'MLT', 'MNE', 'PRT', 'SMR', 'SRB', 'SVK', 'SVN',
  'AFG', 'BRN', 'BTN', 'IRN', 'IRQ', 'KAZ', 'KGZ', 'KHM', 'LKA', 'MNG', 'NPL',
  'OMN', 'SAU', 'TJK', 'TKM',
  'AGO', 'EGY', 'ERI', 'GNQ', 'KEN', 'LSO', 'MOZ', 'SWZ', 'UGA', 'ZMB', 'ZWE',
  'SOL',
  'AIA', 'BLZ', 'BMU', 'CYM', 'DMA', 'DOM', 'GRD', 'GTM', 'GUM', 'HTI', 'MEX',
  'MSR', 'NIC', 'SLV', 'SXM', 'TCA', 'VGB', 'VIR', 'BOL', 'BRA', 'ECU', 'FLK',
  'PER', 'PRY',
  'ASM', 'FJI', 'KIR', 'MNP', 'NCL', 'PCN', 'PNG', 'PYF', 'SGS', 'SHN', 'IOT',
  'ATF', 'VUT',
  // Found by re-reading the sheet against the rule above, not while drawing.
  'ARG', 'URY', 'PHL', 'ETH', 'LBN', 'CAN', 'ATA', 'HKG', 'MAR', 'BRB', 'NFK',
]);
